Communications SDK: APDevPacket.h File Reference
APDevPacket.h File Reference
The autopilot development comm packets. The file includes functions to form and decode Piccolo comm packets with special commands and data for autopilot development purposes. These are in a separate file from AutopilotPacket.c to prevent end-users from modifying the development parameters.
#include "AutopilotPacket.h"
Enumerations
enum AutopilotDevPacketTypes {
DEV_GPS_ENABLE = 250, DEV_GPS_POSVEL, DEV_PACKET_RESERVED_252, DEV_PACKET_RESERVED_253,
DEV_PACKET_RESERVED_254, DEV_PACKET_RESERVED_255
}
Functions
void FormGPSPosVelPacket (AutopilotPkt_t *pPkt, double Lat, double Lon, double Alt, float VNorth, float VEast, float VDown)
Form a GPS position and velocity packet.
BOOL DecodeGPSPosVelPacket (const AutopilotPkt_t *pPkt, double *pLat, double *pLon, double *pAlt, float *pVNorth, float *pVEast, float *pVDown)
Decode a GPS position and velocity packet.
Detailed Description
The autopilot development comm packets. The file includes functions to form and decode Piccolo comm packets with special commands and data for autopilot development purposes. These are in a separate file from AutopilotPacket.c to prevent end-users from modifying the development parameters.
Enumeration Type Documentation
enum AutopilotDevPacketTypes
Autopilot stream message types
Enumerator
DEV_GPS_ENABLE
Command to force enable/disable use of GPS and/or barometer data.
DEV_GPS_POSVEL
GPS position and velocity sent regardless of the enable/disable status.
Function Documentation
BOOL DecodeGPSPosVelPacket (const AutopilotPkt_t * pPkt, double * pLat, double * pLon, double * pAlt, float * pVNorth, float * pVEast, float * pVDown)
Decode a GPS position and velocity packet.
Decode a GPS position and velocity packet.
Parameters
pPkt points to autopilot packet.
pLat points to the latitude in radians.
pLon points to the longitude in radians.
pAlt points to the altitude in meters.
pVNorth points to the North component of groundspeed in m/s.
pVEast points to the East component of groundspeed in m/s.
pVDown points to the Down component of groundspeed in m/s.
Returns
TRUE if packet size and type were valid.
References SimplePkt_t::Data, DataToDouble(), DataToFloat(), DataToUInt16(), DEV_GPS_POSVEL, Float16ToFloat(), SimplePkt_t::PktType, and SimplePkt_t::Size.
void FormGPSPosVelPacket (AutopilotPkt_t * pPkt, double Lat, double Lon, double Alt, float VNorth, float VEast, float VDown)
Form a GPS position and velocity packet.
Form a GPS position and velocity packet.
Parameters
pPkt points to the resulting autopilot packet.
Lat is the latitude in radians.
Lon is the longitude in radians.
Alt is the altitude in meters.
VNorth is the North component of groundspeed in m/s.
VEast is the East component of groundspeed in m/s.
VDown is the Down component of groundspeed in m/s.
References SimplePkt_t::Data, DEV_GPS_POSVEL, DoubleToData(), FloatToData(), FloatToFloat16(), MakeAutopilotPacket(), and UInt16ToData().