Communications SDK: attitude.c File Reference
attitude.c File Reference
Quaternion attitude representation functions This file includes quaternion utilities such as conversions to/from Euler angles, generation of Direction Cosine Matrix (DCM), the Jacobian of the DCM, as well as the quaternion dynamics (kinematic equations)
#include <math.h>
#include <string.h>
#include "attitude.h"
#include "UnivData.h"
#include "Matrix.h"
#include "MathUtil.h"
Macros
#define QUAT_SING_THRESHOLD 0.49999
Quaternion singularity threshold.
#define QUAT_SING_THRESHOLDf 0.49995f
Functions
void QuatConj (double Quat[N_QUAT])
Calculate the conjugate of a quaternion in place.
void QuatConjf (float Quat[N_QUAT])
Calculate the conjugate of a quaternion in place.
void Quat2Euler (const double Quat[N_QUAT], double Euler[NAXIS])
Calculate Euler angles from attitude quaternion.
void Euler2Quat (const double Euler[NAXIS], double Quat[N_QUAT])
Calculate attitude quaternion from Euler angles.
void Quat2DCM (const double Quat[N_QUAT], double *DCM)
Calculate inertial-to-body transformation matrix from attitude quaternion.
void DCM2Quat (double *DCM, double Quat[N_QUAT])
Calculate attitude quaternion from inertial-to-body transformation matrix.
void RotateNav2Body (const double Quat[N_QUAT], const double VecN[NDIR], double VecB[N3D])
Translate a 3-D vector from inertial frame to body frame.
void RotateBody2Nav (const double Quat[N_QUAT], const double VecB[N3D], double VecN[NDIR])
Translate a 3-D vector from body frame to inertial frame.
double MagnitudeQuat (const double Quat[N_QUAT])
Calculate magnitude of a quaternion vector.
void NormalizeQuat (const double QuatIn[N_QUAT], double QuatOut[N_QUAT])
Normalize a quaternion vector.
void QuatDynamics (const double Quat[N_QUAT], const double Gyro[NAXIS], double QuatDot[N_QUAT])
Attitude propagation equations (kinematics) with quaternion formulation.
void EulerDynamics (const double Euler[NAXIS], const double Gyro[NAXIS], double EulerDot[NAXIS])
Computer Euler derivatives.
void EulerDynamicsf (const float Euler[NAXIS], const float Gyro[NAXIS], float EulerDot[NAXIS])
Computer Euler derivatives.
void QuatJacobian (const double Quat[N_QUAT], const double Gyro[NAXIS], double *JQuat, double *JRates)
Jacobian of the kinematic equations with respect to quaternion elements and angular rates.
void DCMJacobian (const double Quat[N_QUAT], double *JDCM)
Jacobian of the inertial-to-body transformation matrix with respect to quaternion elements.
double AngleDifference (double a, double b)
The error between two angles -> between -pi and pi.
void QuatProduct (const double q[N_QUAT], const double s[N_QUAT], double p[N_QUAT])
Quaternion multiplication operation.
void QuatProductf (const float q[N_QUAT], const float s[N_QUAT], float p[N_QUAT])
Quaternion multiplication operation.
void VecQuatProduct (const double v[N3D], const double q[N_QUAT], double p[N_QUAT])
Quaternion multiplication of a 3-D vector with a quaternion.
void VecQuatProductf (const float v[N3D], const float q[N_QUAT], float p[N_QUAT])
Quaternion multiplication of a 3-D vector with a quaternion.
void QuatErrFast (const double Qinitial[N_QUAT], const double Qfinal[N_QUAT], double Err[NAXIS])
Compute the attitude error efficiently under the assumption of small attitude error.
void QuatErrLim (const double Qinitial[N_QUAT], const double Qfinal[N_QUAT], double MaxErr, double Err[NAXIS])
Compute the angular error corresponding to the multiplicative error between two quaternions.
void QuatErr (const double Quat1[N_QUAT], const double Quat2[N_QUAT], double Err[NAXIS])
Compute the attitude error between two quaternions.
void EulerErr (const double Euler1[NAXIS], const double Euler2[NAXIS], double Err[NAXIS])
Compute the attitude error between two Euler vectors.
void RotateNav2Body_2D (double Psi, const double VecN[NDIR], double VecB[N3D])
Rotate a vector about the vertical axis, from navigation frame to body frame.
void RotateBody2Nav_2D (double Psi, const double VecB[N3D], double VecN[NDIR])
Rotate a vector about the vertical axis, from body frame to navigation frame.
void QuatDynamicsf (const float Quat[N_QUAT], const float Gyro[NAXIS], float QuatDot[N_QUAT])
Compute the attitude quaternion time derivative.
void QuatErrFastf (const float Qinitial[N_QUAT], const float Qfinal[N_QUAT], float Err[NAXIS])
Compute the attitude error efficiently under the assumption of small attitude error.
void QuatErrLimf (const float Qinitial[N_QUAT], const float Qfinal[N_QUAT], float MaxErr, float Err[NAXIS])
Compute the angular error corresponding to the multiplicative error between two quaternions.
void QuatErrf (const float Quat1[N_QUAT], const float Quat2[N_QUAT], float Err[NAXIS])
Compute the attitude error between two quaternions.
void EulerErrf (const float Euler1[NAXIS], const float Euler2[NAXIS], float Err[NAXIS])
Compute the attitude error between two Euler vectors.
void RotateNav2Body_2Df (float Psi, const float VecN[NDIR], float VecB[N3D])
Rotate a vector about the vertical axis, from navigation frame to body frame.
void RotateBody2Nav_2Df (float Psi, const float VecB[N3D], float VecN[NDIR])
Rotate a vector about the vertical axis, from body frame to navigation frame.
float MagnitudeQuatf (const float Quat[N_QUAT])
Compute magnitude (norm) of the quaternion vector.
void NormalizeQuatf (const float QuatIn[N_QUAT], float QuatOut[N_QUAT])
Normalize the attitude quaternion.
void Quat2Eulerf (const float Quat[N_QUAT], float Euler[NAXIS])
Convert quaternion to Euler angles.
void Euler2Quatf (const float Euler[NAXIS], float Quat[N_QUAT])
Convert Euler angles to quaternion.
void Quat2DCMf (const float Quat[N_QUAT], float *DCM)
Calculate inertial-to-body transformation matrix from attitude quaternion.
void RotateNav2Bodyf (const float Quat[N_QUAT], const float VecN[NDIR], float VecB[N3D])
Transfer a float vector from navigation frame to body frame.
void RotateBody2Navf (const float Quat[N_QUAT], const float VecB[N3D], float VecN[NDIR])
Transfer a float vector from body frame to navigation frame.
void CalculateRollDeriv (double dPhi[N_QUAT], const double Quat[N_QUAT])
Calculate the roll angle derivatives to quaternion elements.
void CalculatePitchDeriv (double dTheta[N_QUAT], const double Quat[N_QUAT])
Calculate the pitch angle derivatives to quaternion elements.
void CalculateHeadingDeriv (double dPsi[N_QUAT], const double Quat[N_QUAT])
Calculate the heading angle derivatives to quaternion elements.
void CalculateRollDerivf (float dPhi[N_QUAT], const float Quat[N_QUAT])
Calculate the roll angle derivatives to quaternion elements.
void CalculatePitchDerivf (float dTheta[N_QUAT], const float Quat[N_QUAT])
Calculate the pitch angle derivatives to quaternion elements.
void CalculateHeadingDerivf (float dPsi[N_QUAT], const float Quat[N_QUAT])
Calculate the heading angle derivatives to quaternion elements.
void CalculateEulerSigma (double EulerSigma[NAXIS], const double QuatSigma[N_QUAT], const double Quat[N_QUAT])
Calculate Euler angles standard deviation from quaternion standard deviation.
void CalculateEulerSigmaEx (double EulerSigma[NAXIS], const double QuatSigma[N_QUAT], double Theta, double Psi)
Calculate Euler angles standard deviation from quaternion standard deviation, given the Euler angles.
void CalculateEulerSigmaf (float EulerSigma[NAXIS], const float QuatSigma[N_QUAT], const double Quat[N_QUAT])
Calculate Euler angles standard deviation from quaternion standard deviation.
void CalculateEulerSigmaExf (float EulerSigma[NAXIS], const float QuatSigma[N_QUAT], float Theta, float Psi)
Calculate Euler angles standard deviation from quaternion standard deviation, given the Euler angles.
double RollAngleFromQuat (const double Quat[N_QUAT])
Calculate roll angle from quaternion.
double PitchAngleFromQuat (const double Quat[N_QUAT])
Calculate pitch angle from quaternion.
double HeadingAngleFromQuat (const double Quat[N_QUAT])
Calculate heading angle from quaternion.
float RollAngleFromQuatf (const float Quat[N_QUAT])
Calculate roll angle from quaternion.
float PitchAngleFromQuatf (const float Quat[N_QUAT])
Calculate pitch angle from quaternion.
float HeadingAngleFromQuatf (const float Quat[N_QUAT])
Calculate heading angle from quaternion.
void QuatFromRollAngle (double Quat[N_QUAT], double Phi)
Make quaternion for a roll angle rotation.
void QuatFromPitchAngle (double Quat[N_QUAT], double Theta)
Make quaternion for a pitch angle rotation.
void QuatFromHeadingAngle (double Quat[N_QUAT], double Psi)
Make quaternion for a heading angle rotation.
void QuatFromRollPitchAngle (double Quat[N_QUAT], double Phi, double Theta)
Make quaternion for a combined roll+pitch rotation.
void QuatFromRollAnglef (float Quat[N_QUAT], float Phi)
Make quaternion for a roll angle rotation.
void QuatFromPitchAnglef (float Quat[N_QUAT], float Theta)
Make quaternion for a pitch angle rotation.
void QuatFromHeadingAnglef (float Quat[N_QUAT], float Psi)
Make quaternion for a heading angle rotation.
void QuatFromRollPitchAnglef (float Quat[N_QUAT], float Phi, float Theta)
Make quaternion for a combined roll+pitch rotation.
void QuatForTracking (double Quat[N_QUAT], double Pan, double Tilt)
Build quaternion for tracking transformation.
void QuatForTrackingf (float Quat[N_QUAT], float Pan, float Tilt)
Build quaternion for tracking transformation.
void GetTrackVectorAngles (double *pPan, double *pTilt, const double Track[N3D])
Calculate the pan and tilt angles of a tracking vector.
void GetTrackVectorAnglesf (float *pPan, float *pTilt, const float Track[N3D])
Calculate the pan and tilt angles of a tracking vector.
void GetTrackVectorAnglesSigma (double *pPanSigma, double *pTiltSigma, const double Track[N3D], const double TrackSigma[N3D])
Calculate the pan and tilt angles standard deviations of a tracking vector.
void GetTrackVectorAnglesSigmaf (float *pPanSigma, float *pTiltSigma, const float Track[N3D], const float TrackSigma[N3D])
Calculate the pan and tilt angles standard deviations of a tracking vector.
void GetTrackVectorFromAngles (double Track[N3D], double Pan, double Tilt)
Calculate a tracking vector from pan and tilt angles.
void GetTrackVectorFromAnglesf (float Track[N3D], float Pan, float Tilt)
Calculate a tracking vector from pan and tilt angles.
void GetTrackVectorSigmaFromAngles (double TrackSigma[N3D], double Pan, double Tilt, double PanSigma, double TiltSigma)
Calculate a tracking vector's standard deviation from pan and tilt angles standard deviation.
void GetTrackVectorSigmaFromAnglesf (float TrackSigma[N3D], float Pan, float Tilt, float PanSigma, float TiltSigma)
Calculate a tracking vector's standard deviation from pan and tilt angles standard deviation.
void QuatFromHalfAngle (double Quat[N_QUAT], const double Axis[N3D], double Cphi, double Sphi)
Build quaternion give trigonometric functions of the half-angle.
void QuatFromHalfAnglef (float Quat[N_QUAT], const float Axis[N3D], float Cphi, float Sphi)
Build quaternion give trigonometric functions of the half-angle.
void QuatForFixedAxisRotation (double Quat[N_QUAT], const double Axis[N3D], double Angle)
Build quaternion for a rotation about a fixed arbitrary axis.
void QuatForFixedAxisRotationf (float Quat[N_QUAT], const float Axis[N3D], float Angle)
Build quaternion for a rotation about a fixed arbitrary axis.
void PropagateQuaternion (double Quat[N_QUAT], const double delta[NAXIS])
Discrete quaternion propagation using Maclaurin series expansion.
void PropagateQuaternionf (float Quat[N_QUAT], const float delta[NAXIS])
Discrete quaternion propagation using Maclaurin series expansion.
void UpdateQuaternionB (double Quat[N_QUAT], const double deltaB[NAXIS])
Update a nav-to-body quaternion by an angle increment in body frame.
void UpdateQuaternionBf (float Quat[N_QUAT], const float deltaB[NAXIS])
Update a nav-to-body quaternion by an angle increment in body frame.
void UpdateQuaternionN (double Quat[N_QUAT], const double deltaN[NDIR])
Update a nav-to-body quaternion by the inverse of an angle increment in nav frame.
void UpdateQuaternionNf (float Quat[N_QUAT], const float deltaN[NDIR])
Update a nav-to-body quaternion by the inverse of an angle increment in nav frame.
void SetHeadingInQuat (double Quat[N_QUAT], double NewHeading)
Change a quaternion such that that heading angle matches a specified value.
void SetHeadingInQuatf (float Quat[N_QUAT], float NewHeading)
Change a quaternion such that that heading angle matches a specified value.
void GetBodyToNavMat (double C[N_DCM], const double Quat[N_QUAT])
Calculate the body-to-nav direction cosine matrix.
void GetBodyToNavMatf (float C[N_DCM], const float Quat[N_QUAT])
Calculate the body-to-nav direction cosine matrix.
void GetNavToBodyMat (double C[N_DCM], const double Quat[N_QUAT])
Calculate the nav-to-body direction cosine matrix.
void GetNavToBodyMatf (float C[N_DCM], const float Quat[N_QUAT])
Calculate the nav-to-body direction cosine matrix.
void GetQuatFromBodyToNavMat (double Quat[N_QUAT], const double C[N_DCM])
Calculate the quaternion for nav-to-body frame transformation.
void GetQuatFromBodyToNavMatf (float Quat[N_QUAT], const float C[N_DCM])
Calculate the quaternion for nav-to-body frame transformation.
void GetQuatFromNavToBodyMat (double Quat[N_QUAT], const double C[N_DCM])
Calculate the quaternion for nav-to-body frame transformation.
void GetQuatFromNavToBodyMatf (float Quat[N_QUAT], const float C[N_DCM])
Calculate the quaternion for nav-to-body frame transformation.
void GetNavToBodyMatFromVec (double C[N_DCM], const double VecN[N3D], const double VecB[N3D])
Calculate the direction cosine matrix given a vector in two reference frames.
Detailed Description
Quaternion attitude representation functions This file includes quaternion utilities such as conversions to/from Euler angles, generation of Direction Cosine Matrix (DCM), the Jacobian of the DCM, as well as the quaternion dynamics (kinematic equations)
Macro Definition Documentation
#define QUAT_SING_THRESHOLD 0.49999
Quaternion singularity threshold.
Referenced by HeadingAngleFromQuat(), PitchAngleFromQuat(), and RollAngleFromQuat().
Function Documentation
double AngleDifference (double a, double b)
The error between two angles -> between -pi and pi.
Compute the error in the range [-pi, pi] between two arbitrary angles err = (a - b). This is useful in a heading controller to compute the heading error such that the vehicle always takes the shortest turn toward the commanded heading.
Parameters
a is the angle from which we subtract.
b is the angle which is subtracted.
Returns
the angle error a - b that is in the range [-pi, pi].
Referenced by EulerErr(), and EulerErrf().
void CalculateEulerSigma (double EulerSigma[NAXIS], const double QuatSigma[N_QUAT], const double Quat[N_QUAT])
Calculate Euler angles standard deviation from quaternion standard deviation.
Calculate Euler angles standard deviation from quaternion standard deviation by first-order Taylor series expansion.
Parameters
EulerSigma is an array that returns the Euler angles standard deviations.
QuatSigma is an array that contains the quaternion standard deviations.
Quat is the attitude quaternion array.
References CalculateEulerSigmaEx(), NAXIS, PSI, Quat2Euler(), and THETA.
void CalculateEulerSigmaEx (double EulerSigma[NAXIS], const double QuatSigma[N_QUAT], double Theta, double Psi)
Calculate Euler angles standard deviation from quaternion standard deviation, given the Euler angles.
Calculate Euler angles standard deviation from quaternion standard deviation.
Parameters
EulerSigma is an array that returns the Euler angles standard deviations.
QuatSigma is an array that contains the quaternion standard deviations.
Theta is the pitch angle, in rad.
Psi is the heading (yaw) angle, in rad.
References E0, EX, EY, EZ, N_QUAT, PITCH_AXIS, QuatFromHeadingAngle(), QuatFromPitchAngle(), ROLL_AXIS, and YAW_AXIS.
Referenced by CalculateEulerSigma().
void CalculateEulerSigmaExf (float EulerSigma[NAXIS], const float QuatSigma[N_QUAT], float Theta, float Psi)
Calculate Euler angles standard deviation from quaternion standard deviation, given the Euler angles.
Calculate Euler angles standard deviation from quaternion standard deviation.
Parameters
EulerSigma is an array that returns the Euler angles standard deviations.
QuatSigma is an array that contains the quaternion standard deviations.
Theta is the pitch angle, in rad.
Psi is the heading (yaw) angle, in rad.
References E0, EX, EY, EZ, N_QUAT, PITCH_AXIS, QuatFromHeadingAnglef(), QuatFromPitchAnglef(), ROLL_AXIS, and YAW_AXIS.
Referenced by CalculateEulerSigmaf().
void CalculateEulerSigmaf (float EulerSigma[NAXIS], const float QuatSigma[N_QUAT], const double Quat[N_QUAT])
Calculate Euler angles standard deviation from quaternion standard deviation.
Calculate Euler angles standard deviation from quaternion standard deviation by first-order Taylor series expansion.
Parameters
EulerSigma is an array that returns the Euler angles standard deviations.
QuatSigma is an array that contains the quaternion standard deviations.
Quat is the attitude quaternion array.
References CalculateEulerSigmaExf(), NAXIS, PSI, Quat2Euler(), and THETA.
void CalculateHeadingDeriv (double dPsi[N_QUAT], const double Quat[N_QUAT])
Calculate the heading angle derivatives to quaternion elements.
Calculate the heading angle derivatives to quaternion elements.
Parameters
dPsi is an array that returns the derivatives of the heading angle with respect to quaternion elements.
Quat is the attitude quaternion.
References E0, EX, EY, and EZ.
void CalculateHeadingDerivf (float dPsi[N_QUAT], const float Quat[N_QUAT])
Calculate the heading angle derivatives to quaternion elements.
Calculate the heading angle derivatives to quaternion elements.
Parameters
dPsi is an array that returns the derivatives of the heading angle with respect to quaternion elements.
Quat is the attitude quaternion.
References E0, EX, EY, and EZ.
void CalculatePitchDeriv (double dTheta[N_QUAT], const double Quat[N_QUAT])
Calculate the pitch angle derivatives to quaternion elements.
Calculate the pitch angle derivatives to quaternion elements.
Parameters
dTheta is an array that returns the derivatives of the pitch angle with respect to quaternion elements.
Quat is the attitude quaternion.
References E0, EX, EY, and EZ.
void CalculatePitchDerivf (float dTheta[N_QUAT], const float Quat[N_QUAT])
Calculate the pitch angle derivatives to quaternion elements.
Calculate the pitch angle derivatives to quaternion elements.
Parameters
dTheta is an array that returns the derivatives of the pitch angle with respect to quaternion elements.
Quat is the attitude quaternion.
References E0, EX, EY, and EZ.
void CalculateRollDeriv (double dPhi[N_QUAT], const double Quat[N_QUAT])
Calculate the roll angle derivatives to quaternion elements.
Calculate the roll angle derivatives to quaternion elements.
Parameters
dPhi is an array that returns the derivatives of the roll angle with respect to quaternion elements.
Quat is the attitude quaternion.
References E0, EX, EY, and EZ.
void CalculateRollDerivf (float dPhi[N_QUAT], const float Quat[N_QUAT])
Calculate the roll angle derivatives to quaternion elements.
Calculate the roll angle derivatives to quaternion elements.
Parameters
dPhi is an array that returns the derivatives of the roll angle with respect to quaternion elements.
Quat is the attitude quaternion.
References E0, EX, EY, and EZ.
void DCM2Quat (double * DCM, double Quat[N_QUAT])
Calculate attitude quaternion from inertial-to-body transformation matrix.
Extract the quaterion attitude representation given the nav-to-body DCM
Parameters
DCM is the nav-to-body direction cosine matrix
Quat is the vehicle attitude in quaterions
References GetQuatFromNavToBodyMat().
void DCMJacobian (const double Quat[N_QUAT], double * JDCM)
Jacobian of the inertial-to-body transformation matrix with respect to quaternion elements.
Compute the Jacobian of the direction cosine matrix
Parameters
Quat is the vehicle attitude in quaterions
JDCM is the 9x4 Jacobian of the DCM
References C11, C12, C13, C21, C22, C23, C31, C32, C33, E0, EX, EY, and EZ.
void Euler2Quat (const double Euler[NAXIS], double Quat[N_QUAT])
Calculate attitude quaternion from Euler angles.
Compute quaternions corresponding to the attitude given in Euler angles
Parameters
Euler is the resulting Euler angle vector
Quat is the quaternion vector
References N_QUAT, PHI, PSI, QuatFromHeadingAngle(), QuatFromRollPitchAngle(), QuatProduct(), and THETA.
void Euler2Quatf (const float Euler[NAXIS], float Quat[N_QUAT])
Convert Euler angles to quaternion.
Calculate attitude quaternion from Euler angles.
Compute quaternions corresponding to the attitude given in Euler angles
Parameters
Euler is the resulting Euler angle vector
Quat is the quaternion vector
References N_QUAT, PHI, PSI, QuatFromHeadingAnglef(), QuatFromRollPitchAnglef(), QuatProductf(), and THETA.
Referenced by DecodeGimbalTelemetryPacket().
void EulerDynamics (const double Euler[NAXIS], const double Gyro[NAXIS], double EulerDot[NAXIS])
Computer Euler derivatives.
The 6-DOF kinematic equations using Euler attitude representation
Parameters
Euler is the vehicle attitude in euler angles (yaw, pitch, roll)
Gyro is the vehicle angular rate vector
EulerDot receives the Euler derivatives vector
References PHI, PSI, and THETA.
void EulerDynamicsf (const float Euler[NAXIS], const float Gyro[NAXIS], float EulerDot[NAXIS])
Computer Euler derivatives.
The 6-DOF kinematic equations using Euler attitude representation
Parameters
Euler is the vehicle attitude in euler angles (yaw, pitch, roll)
Gyro is the vehicle angular rate vector
EulerDot receives the Euler derivatives vector
References PHI, PSI, and THETA.
void EulerErr (const double Euler1[NAXIS], const double Euler2[NAXIS], double Err[NAXIS])
Compute the attitude error between two Euler vectors.
Compute the attitude error between two Euler attitude representations de = e1 - e2.
Parameters
Euler1 is the attitude that we subtract from.
Euler2 is the attitude to be subtracted.
Err is the resulting attitude difference.
References AngleDifference(), and NAXIS.
Referenced by QuatErr().
void EulerErrf (const float Euler1[NAXIS], const float Euler2[NAXIS], float Err[NAXIS])
Compute the attitude error between two Euler vectors.
Compute the attitude error between two Euler attitude representations de = e1 - e2.
Parameters
Euler1 is the attitude that we subtract from.
Euler2 is the attitude to be subtracted.
Err is the resulting attitude difference.
References AngleDifference(), and NAXIS.
Referenced by QuatErrf().
void GetBodyToNavMat (double C[N_DCM], const double Quat[N_QUAT])
Calculate the body-to-nav direction cosine matrix.
Calculate the body-to-nav direction cosine matrix, given the nav-to-body quaternion.
Parameters
C is the body-to-nav direction cosine matrix.
Quat is the input quaternion.
References C11, C12, C13, C21, C22, C23, C31, C32, C33, E0, EX, EY, and EZ.
Referenced by RotateBody2Nav().
void GetBodyToNavMatf (float C[N_DCM], const float Quat[N_QUAT])
Calculate the body-to-nav direction cosine matrix.
Calculate the body-to-nav direction cosine matrix, given the nav-to-body quaternion.
Parameters
C is the body-to-nav direction cosine matrix.
Quat is the input quaternion.
References C11, C12, C13, C21, C22, C23, C31, C32, C33, E0, EX, EY, and EZ.
Referenced by RotateBody2Navf().
void GetNavToBodyMat (double C[N_DCM], const double Quat[N_QUAT])
Calculate the nav-to-body direction cosine matrix.
Calculate the nav-to-body direction cosine matrix, given the nav-to-body quaternion.
Parameters
C is the nav-to-body direction cosine matrix.
Quat is the input quaternion.
References C11, C12, C13, C21, C22, C23, C31, C32, C33, E0, EX, EY, and EZ.
Referenced by Quat2DCM(), and RotateNav2Body().
void GetNavToBodyMatf (float C[N_DCM], const float Quat[N_QUAT])
Calculate the nav-to-body direction cosine matrix.
Calculate the nav-to-body direction cosine matrix, given the nav-to-body quaternion.
Parameters
C is the nav-to-body direction cosine matrix.
Quat is the input quaternion.
References C11, C12, C13, C21, C22, C23, C31, C32, C33, E0, EX, EY, and EZ.
Referenced by Quat2DCMf(), and RotateNav2Bodyf().
void GetNavToBodyMatFromVec (double C[N_DCM], const double VecN[N3D], const double VecB[N3D])
Calculate the direction cosine matrix given a vector in two reference frames.
Calculate the direction cosine matrix given a vector in two reference frames. If the vector V is represented by VN in the nav frame and by VB in the body frame, then we are computing the nav-to-body direction cosine matrix C, where VB = C * VN.
Parameters
C returns the nav-to-body direction cosine matrix.
VecN is a vector represented in nav frame.
VecB is the same vector represented in body frame.
References CrossProduct3D(), DotProduct3D(), MatrixEye(), MatrixMultiply(), MultiplyVectorByScaler3D(), N3D, N_DCM, and SkewSymmetric3().
void GetQuatFromBodyToNavMat (double Quat[N_QUAT], const double C[N_DCM])
Calculate the quaternion for nav-to-body frame transformation.
Calculate the quaternion for nav-to-body frame transformation, given the body-to-nav direction cosine matrix.
Parameters
Quat is the quaternion describing the attitude of the body frame relative to the nav frame.
C is the direction cosine matrix for body frame to nav frame transformation.
References C11, C12, C13, C21, C22, C23, C31, C32, C33, E0, EX, EY, EZ, and N_QUAT.
Referenced by GetQuatFromNavToBodyMat().
void GetQuatFromBodyToNavMatf (float Quat[N_QUAT], const float C[N_DCM])
Calculate the quaternion for nav-to-body frame transformation.
Calculate the quaternion for nav-to-body frame transformation, given the body-to-nav direction cosine matrix.
Parameters
Quat is the quaternion describing the attitude of the body frame relative to the nav frame.
C is the direction cosine matrix for body frame to nav frame transformation.
References C11, C12, C13, C21, C22, C23, C31, C32, C33, E0, EX, EY, EZ, and N_QUAT.
Referenced by GetQuatFromNavToBodyMatf().
void GetQuatFromNavToBodyMat (double Quat[N_QUAT], const double C[N_DCM])
Calculate the quaternion for nav-to-body frame transformation.
Calculate the quaternion for nav-to-body frame transformation, given the nav-to-body direction cosine matrix.
Parameters
Quat is the quaternion describing the attitude of the body frame relative to the nav frame.
C is the direction cosine matrix for nav frame to body frame transformation.
References EX, GetQuatFromBodyToNavMat(), and N_QUAT.
Referenced by DCM2Quat().
void GetQuatFromNavToBodyMatf (float Quat[N_QUAT], const float C[N_DCM])
Calculate the quaternion for nav-to-body frame transformation.
Calculate the quaternion for nav-to-body frame transformation, given the nav-to-body direction cosine matrix.
Parameters
Quat is the quaternion describing the attitude of the body frame relative to the nav frame.
C is the direction cosine matrix for nav frame to body frame transformation.
References EX, GetQuatFromBodyToNavMatf(), and N_QUAT.
void GetTrackVectorAngles (double * pPan, double * pTilt, const double Track[N3D])
Calculate the pan and tilt angles of a tracking vector.
Calculate the pan and tilt angles of a tracking vector.
Parameters
pPan returns the pan or heading angle of the vector, in rad.
pTilt returns the tilt or pitch angle of the vector, in rad.
Track is a tracking vector pointing from the base to the tracking target.
References X_AXIS, Y_AXIS, and Z_AXIS.
void GetTrackVectorAnglesf (float * pPan, float * pTilt, const float Track[N3D])
Calculate the pan and tilt angles of a tracking vector.
Calculate the pan and tilt angles of a tracking vector/
Parameters
pPan returns the pan or heading angle of the vector, in rad.
pTilt returns the tilt or pitch angle of the vector, in rad.
Track is a tracking vector pointing from the base to the tracking target.
References X_AXIS, Y_AXIS, and Z_AXIS.
void GetTrackVectorAnglesSigma (double * pPanSigma, double * pTiltSigma, const double Track[N3D], const double TrackSigma[N3D])
Calculate the pan and tilt angles standard deviations of a tracking vector.
Calculate the pan and tilt angles standard deviations of a tracking vector.
Parameters
pPanSigma returns the pan or heading angle standard deviation of the vector, in rad.
pTiltSigma returns the tilt or pitch angle standard deviation of the vector, in rad.
Track is a tracking vector pointing from the base to the tracking target.
TrackSigma is the tracking vector standard deviation.
References X_AXIS, Y_AXIS, and Z_AXIS.
void GetTrackVectorAnglesSigmaf (float * pPanSigma, float * pTiltSigma, const float Track[N3D], const float TrackSigma[N3D])
Calculate the pan and tilt angles standard deviations of a tracking vector.
Calculate the pan and tilt angles standard deviations of a tracking vector.
Parameters
pPanSigma returns the pan or heading angle standard deviation of the vector, in rad.
pTiltSigma returns the tilt or pitch angle standard deviation of the vector, in rad.
Track is a tracking vector pointing from the base to the tracking target.
TrackSigma is the tracking vector standard deviation.
References X_AXIS, Y_AXIS, and Z_AXIS.
void GetTrackVectorFromAngles (double Track[N3D], double Pan, double Tilt)
Calculate a tracking vector from pan and tilt angles.
Calculate a tracking vector from pan and tilt angles.
Parameters
Track is the resulting unit vector along the track.
Pan is the tracking pan (heading) angle, in rad.
Tilt is the tracking tilt (pitch) angle, in rad.
References X_AXIS, Y_AXIS, and Z_AXIS.
void GetTrackVectorFromAnglesf (float Track[N3D], float Pan, float Tilt)
Calculate a tracking vector from pan and tilt angles.
Calculate a tracking vector from pan and tilt angles.
Parameters
Track is the resulting unit vector along the track.
Pan is the tracking pan (heading) angle, in rad.
Tilt is the tracking tilt (pitch) angle, in rad.
References X_AXIS, Y_AXIS, and Z_AXIS.
void GetTrackVectorSigmaFromAngles (double TrackSigma[N3D], double Pan, double Tilt, double PanSigma, double TiltSigma)
Calculate a tracking vector's standard deviation from pan and tilt angles standard deviation.
Calculate a tracking vector's standard deviation from pan and tilt angles standard deviation.
Parameters
TrackSigma is the resulting tracking vector standard deviation.
Pan is the tracking pan (heading) angle, in rad.
Tilt is the tracking tilt (pitch) angle, in rad.
PanSigma is the pan angle standard deviation, in rad.
TiltSigma is the tilt angle standard deviation, in rad.
References X_AXIS, Y_AXIS, and Z_AXIS.
void GetTrackVectorSigmaFromAnglesf (float TrackSigma[N3D], float Pan, float Tilt, float PanSigma, float TiltSigma)
Calculate a tracking vector's standard deviation from pan and tilt angles standard deviation.
Calculate a tracking vector's standard deviation from pan and tilt angles standard deviation.
Parameters
TrackSigma is the resulting tracking vector standard deviation.
Pan is the tracking pan (heading) angle, in rad.
Tilt is the tracking tilt (pitch) angle, in rad.
PanSigma is the pan angle standard deviation, in rad.
TiltSigma is the tilt angle standard deviation, in rad.
References X_AXIS, Y_AXIS, and Z_AXIS.
double HeadingAngleFromQuat (const double Quat[N_QUAT])
Calculate heading angle from quaternion.
Calculate heading angle from quaternion.
Parameters
Quat is the attitude quaternion array.
Returns
Heading angle in rad.
References E0, EX, EY, EZ, and QUAT_SING_THRESHOLD.
Referenced by Quat2Euler(), QuatErrLim(), and SetHeadingInQuat().
float HeadingAngleFromQuatf (const float Quat[N_QUAT])
Calculate heading angle from quaternion.
Calculate heading angle from quaternion.
Parameters
Quat is the attitude quaternion array.
Returns
Heading angle in rad.
References E0, EX, EY, and EZ.
Referenced by Quat2Eulerf(), QuatErrLimf(), and SetHeadingInQuatf().
double MagnitudeQuat (const double Quat[N_QUAT])
Calculate magnitude of a quaternion vector.
Compute magnitude of quaternion vector (should be approx. 1)
Parameters
Quat is the vehicle attitude in quaterions
Returns
magnitude of quaternion vector
References E0, EX, EY, and EZ.
Referenced by NormalizeQuat().
float MagnitudeQuatf (const float Quat[N_QUAT])
Compute magnitude (norm) of the quaternion vector.
Compute magnitude of quaternion vector (should be approx. 1)
Parameters
Quat is the vehicle attitude in quaterions
Returns
magnitude of quaternion vector
References E0, EX, EY, and EZ.
Referenced by NormalizeQuatf().
void NormalizeQuat (const double QuatIn[N_QUAT], double QuatOut[N_QUAT])
Normalize a quaternion vector.
Check quaternion vector norm and normalize if it exceeds the threshold MAX_QUAT_ERR
Parameters
QuatIn is the vehicle attitude in quaterions
QuatOut is the normalized quaterion vector
References MagnitudeQuat(), MAX_QUAT_ERR, and N_QUAT.
void NormalizeQuatf (const float QuatIn[N_QUAT], float QuatOut[N_QUAT])
Normalize the attitude quaternion.
Check quaternion vector norm and normalize if it exceeds the threshold MAX_QUAT_ERR
Parameters
QuatIn is the vehicle attitude in quaterions
QuatOut is the normalized quaterion vector
References MagnitudeQuatf(), MAX_QUAT_ERR, and N_QUAT.
double PitchAngleFromQuat (const double Quat[N_QUAT])
Calculate pitch angle from quaternion.
Calculate pitch angle from quaternion.
Parameters
Quat is the attitude quaternion array.
Returns
Pitch angle in rad.
References E0, EX, EY, EZ, and QUAT_SING_THRESHOLD.
Referenced by Quat2Euler().
float PitchAngleFromQuatf (const float Quat[N_QUAT])
Calculate pitch angle from quaternion.
Calculate pitch angle from quaternion.
Parameters
Quat is the attitude quaternion array.
Returns
Pitch angle in rad.
References E0, EX, EY, and EZ.
Referenced by Quat2Eulerf().
void PropagateQuaternion (double Quat[N_QUAT], const double delta[NAXIS])
Discrete quaternion propagation using Maclaurin series expansion.
Discrete quaternion propagation using Maclaurin series expansion.
Parameters
Quat is the quaternion that will be propagated.
delta is an incremental angle array, in body axes, in rad.
References UpdateQuaternionB().
void PropagateQuaternionf (float Quat[N_QUAT], const float delta[NAXIS])
Discrete quaternion propagation using Maclaurin series expansion.
Discrete quaternion propagation using Maclaurin series expansion.
Parameters
Quat is the quaternion that will be propagated.
delta is an incremental angle array, in body axes, in rad.
References UpdateQuaternionBf().
void Quat2DCM (const double Quat[N_QUAT], double * DCM)
Calculate inertial-to-body transformation matrix from attitude quaternion.
Compute the nav-to-body direction cosine matrix
Parameters
Quat is the vehicle attitude in quaterions
DCM is the nav-to-body direction cosine matrix
References GetNavToBodyMat().
void Quat2DCMf (const float Quat[N_QUAT], float * DCM)
Calculate inertial-to-body transformation matrix from attitude quaternion.
Compute the nav-to-body direction cosine matrix
Parameters
Quat is the vehicle attitude in quaterions
DCM is the nav-to-body direction cosine matrix
References GetNavToBodyMatf().
void Quat2Euler (const double Quat[N_QUAT], double Euler[NAXIS])
Calculate Euler angles from attitude quaternion.
Compute Euler angles corresponding to the attitude given in quaternions
Parameters
Quat is the quaternion vector
Euler is the resulting Euler angle vector
References HeadingAngleFromQuat(), PHI, PitchAngleFromQuat(), PSI, RollAngleFromQuat(), and THETA.
Referenced by CalculateEulerSigma(), CalculateEulerSigmaf(), and QuatErr().
void Quat2Eulerf (const float Quat[N_QUAT], float Euler[NAXIS])
Convert quaternion to Euler angles.
Compute Euler angles corresponding to the attitude given in quaternions
Parameters
Quat is the quaternion vector
Euler is the resulting Euler angle vector
References HeadingAngleFromQuatf(), PHI, PitchAngleFromQuatf(), PSI, RollAngleFromQuatf(), and THETA.
Referenced by DecodeGimbalTelemetryPacket(), and QuatErrf().
void QuatConj (double Quat[N_QUAT])
Calculate the conjugate of a quaternion in place.
Calculate the conjugate of a quaternion in place
Parameters
Quat is the quaternion to complement.
References EX, EY, and EZ.
void QuatConjf (float Quat[N_QUAT])
Calculate the conjugate of a quaternion in place.
Calculate the conjugate of a quaternion in place
Parameters
Quat is the quaternion to complement.
References EX, EY, and EZ.
void QuatDynamics (const double Quat[N_QUAT], const double Gyro[NAXIS], double QuatDot[N_QUAT])
Attitude propagation equations (kinematics) with quaternion formulation.
The 6-DOF kinematic equations using quaterion attitude representation
Parameters
Quat is the vehicle attitude in quaterions
Gyro is the vehicle angular rate vector
QuatDot is the quaterion derivatives vector
References E0, EX, EY, EZ, PITCH_AXIS, ROLL_AXIS, and YAW_AXIS.
void QuatDynamicsf (const float Quat[N_QUAT], const float Gyro[NAXIS], float QuatDot[N_QUAT])
Compute the attitude quaternion time derivative.
The 6-DOF kinematic equations using quaterion attitude representation
Parameters
Quat is the vehicle attitude in quaterions
Gyro is the vehicle angular rate vector
QuatDot is the quaterion derivatives vector
References E0, EX, EY, EZ, PITCH_AXIS, ROLL_AXIS, and YAW_AXIS.
void QuatErr (const double Quat1[N_QUAT], const double Quat2[N_QUAT], double Err[NAXIS])
Compute the attitude error between two quaternions.
Compute the attitude error between two quaternions. The result of the subtraction is an Euler angle difference.
Parameters
Quat1 is the quaternion that we subtract from.
Quat2 is the quaternion to be subtracted.
Err is the resulting attitude error Quat1 - Quat2.
References EulerErr(), NAXIS, and Quat2Euler().
void QuatErrf (const float Quat1[N_QUAT], const float Quat2[N_QUAT], float Err[NAXIS])
Compute the attitude error between two quaternions.
Compute the attitude error between two quaternions. The result of the subtraction is an Euler angle difference.
Parameters
Quat1 is the quaternion that we subtract from.
Quat2 is the quaternion to be subtracted.
Err is the resulting attitude error Quat1 - Quat2.
References EulerErrf(), NAXIS, and Quat2Eulerf().
void QuatErrFast (const double Qinitial[N_QUAT], const double Qfinal[N_QUAT], double Err[NAXIS])
Compute the attitude error efficiently under the assumption of small attitude error.
Compute the angular change from an initial attitude to a final attitude. The method used here is very efficient, but it works under the assumption that the attitude error is small.
Parameters
Qinitial is the initial attitude quaternion.
Qfinal is the final attitude quaternion.
Err is the angular error vector in body frame, in rad.
References E0, EX, EY, EZ, N_QUAT, NAXIS, and QuatProduct().
Referenced by QuatErrLim().
void QuatErrFastf (const float Qinitial[N_QUAT], const float Qfinal[N_QUAT], float Err[NAXIS])
Compute the attitude error efficiently under the assumption of small attitude error.
Compute the angular change from an initial attitude to a final attitude. The method used here is very efficient, but it works under the assumption that the attitude error is small.
Parameters
Qinitial is the initial attitude quaternion.
Qfinal is the final attitude quaternion.
Err is the angular error vector in body frame, in rad.
References E0, EX, EY, EZ, N_QUAT, NAXIS, and QuatProductf().
Referenced by QuatErrLimf().
void QuatErrLim (const double Qinitial[N_QUAT], const double Qfinal[N_QUAT], double MaxErr, double Err[NAXIS])
Compute the angular error corresponding to the multiplicative error between two quaternions.
Compute the angular error corresponding to the multiplicative error between two quaternions.
Parameters
Qinitial is the initial quaternion that the error is relative to, qi.
Qfinal is the final quaternion that the error leads to, qf.
MaxErr is the maximum heading angle error allowed between the two quaternions, in rad.
Err is an array that returns the angular error of qf relative to qi, in rad.
References HeadingAngleFromQuat(), N_QUAT, QuatErrFast(), QuatFromHeadingAngle(), QuatProduct(), and SubtractAngles().
void QuatErrLimf (const float Qinitial[N_QUAT], const float Qfinal[N_QUAT], float MaxErr, float Err[NAXIS])
Compute the angular error corresponding to the multiplicative error between two quaternions.
Compute the angular error corresponding to the multiplicative error between two quaternions.
Parameters
Qinitial is the initial quaternion that the error is relative to, qi.
Qfinal is the final quaternion that the error leads to, qf.
MaxErr is the maximum heading angle error allowed between the two quaternions, in rad.
Err is an array that returns the angular error of qf relative to qi, in rad.
References HeadingAngleFromQuatf(), N_QUAT, QuatErrFastf(), QuatFromHeadingAnglef(), QuatProductf(), and SubtractAnglesf().
void QuatForFixedAxisRotation (double Quat[N_QUAT], const double Axis[N3D], double Angle)
Build quaternion for a rotation about a fixed arbitrary axis.
Build quaternion for a rotation about a fixed arbitrary axis.
Parameters
Quat is the resulting rotation quaternion.
Axis is a 3D unit vector that defines the rotation axis.
Angle is the desired rotation angle, in rad.
References QuatFromHalfAngle().
void QuatForFixedAxisRotationf (float Quat[N_QUAT], const float Axis[N3D], float Angle)
Build quaternion for a rotation about a fixed arbitrary axis.
Build quaternion for a rotation about a fixed arbitrary axis.
Parameters
Quat is the resulting rotation quaternion.
Axis is a 3D unit vector that defines the rotation axis.
Angle is the desired rotation angle, in rad.
References QuatFromHalfAnglef().
void QuatForTracking (double Quat[N_QUAT], double Pan, double Tilt)
Build quaternion for tracking transformation.
Build quaternion for tracking trasformation. The tracking transformation consists of two rotations: first by pan (or heading), and then by tilt (or pitch).
Parameters
Quat is the resulting quaternion that defines the orientation of the track line.
Pan is the pan or heading angle, in rad.
Tilt is the tilt or pitch angle, in rad.
References N_QUAT, QuatFromHeadingAngle(), QuatFromPitchAngle(), and QuatProduct().
void QuatForTrackingf (float Quat[N_QUAT], float Pan, float Tilt)
Build quaternion for tracking transformation.
Build quaternion for tracking transformation. The tracking transformation consists of two rotations: first by pan (or heading), and then by tilt (or pitch).
Parameters
Quat is the resulting quaternion that defines the orientation of the track line.
Pan is the pan or heading angle, in rad.
Tilt is the tilt or pitch angle, in rad.
References N_QUAT, QuatFromHeadingAnglef(), QuatFromPitchAnglef(), and QuatProductf().
Referenced by DecodeGimbalTelemetryPacket().
void QuatFromHalfAngle (double Quat[N_QUAT], const double Axis[N3D], double Cphi, double Sphi)
Build quaternion give trigonometric functions of the half-angle.
Build quaternion give trigonometric functions of the half-angle.
Parameters
Quat is the resulting rotation quaternion.
Axis is a 3D unit vector that defines the rotation axis.
Cphi is the cosine of the half-angle.
Sphi is the sine of the half-angle.
References E0, EX, EY, EZ, X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by QuatForFixedAxisRotation(), UpdateQuaternionB(), and UpdateQuaternionN().
void QuatFromHalfAnglef (float Quat[N_QUAT], const float Axis[N3D], float Cphi, float Sphi)
Build quaternion give trigonometric functions of the half-angle.
Build quaternion give trigonometric functions of the half-angle.
Parameters
Quat is the resulting rotation quaternion.
Axis is a 3D unit vector that defines the rotation axis.
Cphi is the cosine of the half-angle.
Sphi is the sine of the half-angle.
References E0, EX, EY, EZ, X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by QuatForFixedAxisRotationf(), UpdateQuaternionBf(), and UpdateQuaternionNf().
void QuatFromHeadingAngle (double Quat[N_QUAT], double Psi)
Make quaternion for a heading angle rotation.
Make quaternion for a heading angle rotation.
Parameters
Quat is the resulting attitude quaternion.
Psi is the heading angle in rad.
References E0, EX, EY, and EZ.
Referenced by CalculateEulerSigmaEx(), Euler2Quat(), QuatErrLim(), QuatForTracking(), and SetHeadingInQuat().
void QuatFromHeadingAnglef (float Quat[N_QUAT], float Psi)
Make quaternion for a heading angle rotation.
Make quaternion for a heading angle rotation.
Parameters
Quat is the resulting attitude quaternion.
Psi is the heading angle in rad.
References E0, EX, EY, and EZ.
Referenced by CalculateEulerSigmaExf(), Euler2Quatf(), QuatErrLimf(), QuatForTrackingf(), and SetHeadingInQuatf().
void QuatFromPitchAngle (double Quat[N_QUAT], double Theta)
Make quaternion for a pitch angle rotation.
Make quaternion for a pitch angle rotation.
Parameters
Quat is the resulting attitude quaternion.
Theta is the pitch angle in rad.
References E0, EX, EY, and EZ.
Referenced by CalculateEulerSigmaEx(), QuatForTracking(), and QuatFromRollPitchAngle().
void QuatFromPitchAnglef (float Quat[N_QUAT], float Theta)
Make quaternion for a pitch angle rotation.
Make quaternion for a pitch angle rotation.
Parameters
Quat is the resulting attitude quaternion.
Theta is the pitch angle in rad.
References E0, EX, EY, and EZ.
Referenced by CalculateEulerSigmaExf(), QuatForTrackingf(), and QuatFromRollPitchAnglef().
void QuatFromRollAngle (double Quat[N_QUAT], double Phi)
Make quaternion for a roll angle rotation.
Make quaternion for a roll angle rotation.
Parameters
Quat is the resulting attitude quaternion.
Phi is the roll angle in rad.
References E0, EX, EY, and EZ.
Referenced by QuatFromRollPitchAngle().
void QuatFromRollAnglef (float Quat[N_QUAT], float Phi)
Make quaternion for a roll angle rotation.
Make quaternion for a roll angle rotation.
Parameters
Quat is the resulting attitude quaternion.
Phi is the roll angle in rad.
References E0, EX, EY, and EZ.
Referenced by QuatFromRollPitchAnglef().
void QuatFromRollPitchAngle (double Quat[N_QUAT], double Phi, double Theta)
Make quaternion for a combined roll+pitch rotation.
Make quaternion for a combined roll+pitch rotation.
Parameters
Quat is the resulting attitude quaternion.
Phi is the roll angle, in rad.
Theta is the pitch angle, in rad.
References N_QUAT, QuatFromPitchAngle(), QuatFromRollAngle(), and QuatProduct().
Referenced by Euler2Quat().
void QuatFromRollPitchAnglef (float Quat[N_QUAT], float Phi, float Theta)
Make quaternion for a combined roll+pitch rotation.
Make quaternion for a combined roll+pitch rotation.
Parameters
Quat is the resulting attitude quaternion.
Phi is the roll angle, in rad.
Theta is the pitch angle, in rad.
References N_QUAT, QuatFromPitchAnglef(), QuatFromRollAnglef(), and QuatProductf().
Referenced by Euler2Quatf().
void QuatJacobian (const double Quat[N_QUAT], const double Gyro[NAXIS], double * JQuat, double * JRates)
Jacobian of the kinematic equations with respect to quaternion elements and angular rates.
Compute the Jacobian matrices of the quaternion dynamics
Parameters
Quat is the vehicle attitude in quaterions
Gyro is the vehicle angular rate vector
JQuat is the 4x4 quaternion Jacobian matrix d[e0 ex ey ez]/d[e0 ex ey ez]
JRates is the 3x4 angular rates Jacobian matrix d[e0 ex ey ez]/d[p q r]
References E0, EX, EY, EZ, PITCH_AXIS, ROLL_AXIS, and YAW_AXIS.
void QuatProduct (const double q[N_QUAT], const double s[N_QUAT], double p[N_QUAT])
Quaternion multiplication operation.
The quaternion multiplication operation
Parameters
q = first quaternion
s = second quaternion
p = quaternion product result
References E0, EX, EY, and EZ.
Referenced by Euler2Quat(), QuatErrFast(), QuatErrLim(), QuatForTracking(), QuatFromRollPitchAngle(), SetHeadingInQuat(), UpdateQuaternionB(), and UpdateQuaternionN().
void QuatProductf (const float q[N_QUAT], const float s[N_QUAT], float p[N_QUAT])
Quaternion multiplication operation.
The quaternion multiplication operation
Parameters
q = first quaternion
s = second quaternion
p = quaternion product result
References E0, EX, EY, and EZ.
Referenced by DecodeGimbalTelemetryPacket(), Euler2Quatf(), QuatErrFastf(), QuatErrLimf(), QuatForTrackingf(), QuatFromRollPitchAnglef(), SetHeadingInQuatf(), UpdateQuaternionBf(), and UpdateQuaternionNf().
double RollAngleFromQuat (const double Quat[N_QUAT])
Calculate roll angle from quaternion.
Calculate roll angle from quaternion.
Parameters
Quat is the attitude quaternion array.
Returns
Roll angle in rad.
References E0, EX, EY, EZ, and QUAT_SING_THRESHOLD.
Referenced by Quat2Euler().
float RollAngleFromQuatf (const float Quat[N_QUAT])
Calculate roll angle from quaternion.
Calculate roll angle from quaternion.
Parameters
Quat is the attitude quaternion array.
Returns
Roll angle in rad.
References E0, EX, EY, and EZ.
Referenced by Quat2Eulerf().
void RotateBody2Nav (const double Quat[N_QUAT], const double VecB[N3D], double VecN[NDIR])
Translate a 3-D vector from body frame to inertial frame.
Rotate a vector from body frame to navigation frame
Parameters
Quat is the vehicle attitude in quaterions
VecB is the vector in body frame
VecN is the vector in navigation frame
References GetBodyToNavMat(), MatrixMultiply(), and N_DCM.
void RotateBody2Nav_2D (double Psi, const double VecB[N3D], double VecN[NDIR])
Rotate a vector about the vertical axis, from body frame to navigation frame.
Rotate a vector about the vertical axis, from body frame to navigation frame.
Parameters
Psi is the aircraft heading angle.
VecB is a 3-D vector in vehicle frame.
VecN is the resulting 3-D vector in navigation frame (local tangent plane).
References DOWN, EAST, NORTH, X_AXIS, Y_AXIS, and Z_AXIS.
void RotateBody2Nav_2Df (float Psi, const float VecB[N3D], float VecN[NDIR])
Rotate a vector about the vertical axis, from body frame to navigation frame.
Rotate a vector about the vertical axis, from body frame to navigation frame.
Parameters
Psi is the aircraft heading angle.
VecB is a 3-D vector in vehicle frame.
VecN is the resulting 3-D vector in navigation frame (local tangent plane).
References DOWN, EAST, NORTH, X_AXIS, Y_AXIS, and Z_AXIS.
void RotateBody2Navf (const float Quat[N_QUAT], const float VecB[N3D], float VecN[NDIR])
Transfer a float vector from body frame to navigation frame.
Rotate a vector from body frame to navigation frame
Parameters
Quat is the vehicle attitude in quaterions
VecB is the vector in body frame
VecN is the vector in navigation frame
References GetBodyToNavMatf(), MatrixMultiplyf(), and N_DCM.
void RotateNav2Body (const double Quat[N_QUAT], const double VecN[NDIR], double VecB[N3D])
Translate a 3-D vector from inertial frame to body frame.
Rotate a vector from navigation frame to body frame
Parameters
Quat is the vehicle attitude in quaterions
VecN is the vector in navigation frame
VecB is the vector in body frame
References GetNavToBodyMat(), MatrixMultiply(), and N_DCM.
void RotateNav2Body_2D (double Psi, const double VecN[NDIR], double VecB[N3D])
Rotate a vector about the vertical axis, from navigation frame to body frame.
Rotate a vector about the vertical axis, from navigation frame to body frame.
Parameters
Psi is the aircraft heading angle.
VecN is a 3-D vector in navigation frame (local tangent plane).
VecB is the resulting 3-D vector in vehicle frame.
References DOWN, EAST, NORTH, X_AXIS, Y_AXIS, and Z_AXIS.
void RotateNav2Body_2Df (float Psi, const float VecN[NDIR], float VecB[N3D])
Rotate a vector about the vertical axis, from navigation frame to body frame.
Rotate a vector about the vertical axis, from navigation frame to body frame.
Parameters
Psi is the aircraft heading angle.
VecN is a 3-D vector in navigation frame (local tangent plane).
VecB is the resulting 3-D vector in vehicle frame.
References DOWN, EAST, NORTH, X_AXIS, Y_AXIS, and Z_AXIS.
void RotateNav2Bodyf (const float Quat[N_QUAT], const float VecN[NDIR], float VecB[N3D])
Transfer a float vector from navigation frame to body frame.
Rotate a vector from navigation frame to body frame
Parameters
Quat is the vehicle attitude in quaterions
VecN is the vector in navigation frame
VecB is the vector in body frame
References GetNavToBodyMatf(), MatrixMultiplyf(), and N_DCM.
void SetHeadingInQuat (double Quat[N_QUAT], double NewHeading)
Change a quaternion such that that heading angle matches a specified value.
Change an attitude quaternion such that its corresponding heading angle matches a specified value.
Parameters
Quat is the quaternion array that will be modified.
NewHeading is the desired heading value, in rad.
References HeadingAngleFromQuat(), N_QUAT, QuatFromHeadingAngle(), and QuatProduct().
void SetHeadingInQuatf (float Quat[N_QUAT], float NewHeading)
Change a quaternion such that that heading angle matches a specified value.
Change an attitude quaternion such that its corresponding heading angle matches a specified value. Single-precision function.
Parameters
Quat is the quaternion array that will be modified.
NewHeading is the desired heading value, in rad.
References HeadingAngleFromQuatf(), N_QUAT, QuatFromHeadingAnglef(), and QuatProductf().
void UpdateQuaternionB (double Quat[N_QUAT], const double deltaB[NAXIS])
Update a nav-to-body quaternion by an angle increment in body frame.
Update a nav-to-body quaternion by an angle increment in body frame.
Parameters
Quat is the quaternion that will be updated by right-hand multiplication.
deltaB is an incremental angle array, in body axes, in rad.
References N_QUAT, PITCH_AXIS, QuatFromHalfAngle(), QuatProduct(), ROLL_AXIS, and YAW_AXIS.
Referenced by PropagateQuaternion().
void UpdateQuaternionBf (float Quat[N_QUAT], const float deltaB[NAXIS])
Update a nav-to-body quaternion by an angle increment in body frame.
Update a nav-to-body quaternion by an angle increment in body frame.
Parameters
Quat is the quaternion that will be updated by right-hand multiplication.
deltaB is an incremental angle array, in body axes, in rad.
References N_QUAT, PITCH_AXIS, QuatFromHalfAnglef(), QuatProductf(), ROLL_AXIS, and YAW_AXIS.
Referenced by PropagateQuaternionf().
void UpdateQuaternionN (double Quat[N_QUAT], const double deltaN[NDIR])
Update a nav-to-body quaternion by the inverse of an angle increment in nav frame.
Update a nav-to-body quaternion by the inverse of an angle increment in nav frame.
Parameters
Quat is the quaternion that will be updated by left-hand multiplication.
deltaN is an incremental angle array, in nav frame, in rad.
References DOWN, EAST, N_QUAT, NORTH, QuatFromHalfAngle(), and QuatProduct().
void UpdateQuaternionNf (float Quat[N_QUAT], const float deltaN[NDIR])
Update a nav-to-body quaternion by the inverse of an angle increment in nav frame.
Update a nav-to-body quaternion by the inverse of an angle increment in nav frame.
Parameters
Quat is the quaternion that will be updated by left-hand multiplication.
deltaN is an incremental angle array, in nav frame, in rad.
References DOWN, EAST, N_QUAT, NORTH, QuatFromHalfAnglef(), and QuatProductf().
void VecQuatProduct (const double v[N3D], const double q[N_QUAT], double p[N_QUAT])
Quaternion multiplication of a 3-D vector with a quaternion.
Quaternion multiplication of a 3-D vector with a quaternion.
Parameters
v = 3-element vector
q = quaternion
p = 4-element product result.
References E0, EX, EY, EZ, X_AXIS, Y_AXIS, and Z_AXIS.
void VecQuatProductf (const float v[N3D], const float q[N_QUAT], float p[N_QUAT])
Quaternion multiplication of a 3-D vector with a quaternion.
Quaternion multiplication of a 3-D vector with a quaternion.
Parameters
v = 3-element vector
q = quaternion
p = 4-element product result.
References E0, EX, EY, EZ, X_AXIS, Y_AXIS, and Z_AXIS.