Communications SDK: AutopilotPacket.h File Reference
AutopilotPacket.h File Reference
Autopilot stream packet utilities.
#include "StreamPackets.h"
#include "PiccoloDefinitions.h"
Classes
struct AvailableData_t
Macros
#define AUTOPILOT_PKT_OVERHEAD SIMPLE_PKT_OVERHEAD
#define MAX_WAYPOINTS_IN_PACKET 14
Maximum number of waypoints you can fit in one packet.
#define MAX_WAYPOINTS_IN_FLIGHT (3*MAX_WAYPOINTS_IN_PACKET)
Maximum amount of unacknowledged waypoint traffic.
Defines used with the waypoint list packet
#define GET_WAYPOINT_LIST 0
Request waypoints (if uplink packet)
#define CURRENT_WAYPOINTS 0
Currently active list (if downlink packet)
#define DELETE_WAYPOINTS 1
Delete waypoints (if uplink packet)
#define REQUEST_WAYPOINTS 2
Request waypoints (if uplink packet)
#define WAYPOINT_BLOCK 3
Prepare to receive waypoints (both ways)
#define WAYPOINT_ACK 4
Acknowledge receive of waypoints (both ways)
Enumerations
enum AutopilotPacketTypes {
USER_WARNING, CONFIG_UNLOCK, BANDWIDTH_MODE, FEATURE_CODE,
CONFIG_LOCK, ACTUATOR_TABLE, PAYLOAD_MASS, ELEVATION_DATA,
LEGACY_WAYPOINT, LEGACY_WAYPOINT_LIST, TRACK, THROTTLE_MIN,
MISSION_SETTINGS, ECU_STATUS, SENSOR_ORIENTATION, ALTIMETER_SETTING,
SYSTEM_RESET, SYSTEM_VERSION, RESET_REPORT, ACTUATOR_TEST,
MISSION_LIMITS, BOUNDARY, USER_ACTION, CONFIG_UNLOCK_QUIET,
AUTOPILOT_LOOP, AUTO_FLARE_DISABLE, DESCRIPTION, USER_SPACE,
MANUAL_FLARE_COMMAND, WAYPOINT_LIST_RANGE, MAG_CALIBRATION, ENGINE_KILL,
RADIO_TRANSMIT_DISABLE, RADIO_SETTINGS, EXTERNAL_SERIAL_SETUP, EXTERNAL_IO_SETUP,
EXTERNAL_IO_SAMPLE, WAYPOINTS, EXTERNAL_ADC_SAMPLE, LAND_NOW,
EDC_EMU_SENSORS, ECU_COMMAND, CLEAR_PDYN_FAULT, CREATE_SIMPLE_LANDING,
GPS_HEALTH, AIR_DATA_ZERO, PRE_LAUNCH_MODE, NEW_MANUAL_ASSIST_MODE,
LIGHTS_CMD, BRAKES_CMD, PARACHUTE_CMD, DROP_CMD,
THROTTLE_TRIM, DEVICE_DETAILS, AVAILABLE_ID_36, SERVO_TELEMETRY,
TRANSPONDER_INSTALLATION, TRANSPONDER_STATUS, SYSTEM_STATUS, TRANSPONDER_CONTROL,
TRANSPONDER_PREFLIGHT, RAW_VIBRATION_DATA, FREQ_SWEEP_CMD, LINK_BRIDGE,
DOUBLET_CMD, DOUBLET_AP_DATA, DOUBLET_SENSOR_DATA, CONTROLLER_DATA_REQUEST,
CONTROLLER_DATA, TELEMETRY_HI_RES, TELEMETRY_LO_RES, LEGACY_SYSTEM_STATUS_HI_RES,
LEGACY_SYSTEM_STATUS_LO_RES, LAUNCH_NOW, CONTROLLER_DATA_DEFAULT, SET_FUEL_LEVEL,
SENSOR_ERROR, CONTROLLER_ABORT, MOVING_BASELINE_STATUS, SET_FUEL_IFLOCKED,
LATITUDE_RESERVED_0, LATITUDE_RESERVED_1, LATITUDE_RESERVED_2, LATITUDE_RESERVED_3,
LATITUDE_RESERVED_4, LATITUDE_RESERVED_5, LATITUDE_RESERVED_6, LATITUDE_RESERVED_7,
LATITUDE_RESERVED_8, LATITUDE_RESERVED_9, LATITUDE_RESERVED_A, LATITUDE_RESERVED_B,
LATITUDE_RESERVED_C, LATITUDE_RESERVED_D, LATITUDE_RESERVED_E, LATITUDE_RESERVED_F,
NUM_AP_PACKETS
}
enum ControllerPacketTypes {
CONTROLLER_PACKET_1 = 220, CONTROLLER_PACKET_2, CONTROLLER_PACKET_3, CONTROLLER_PACKET_4,
CONTROLLER_PACKET_5, CONTROLLER_PACKET_6, CONTROLLER_PACKET_7, CONTROLLER_PACKET_8,
CONTROLLER_PACKET_9, CONTROLLER_PACKET_10, CONTROLLER_PACKET_11, CONTROLLER_PACKET_12,
CONTROLLER_PACKET_13, CONTROLLER_PACKET_14, CONTROLLER_PACKET_15, CONTROLLER_PACKET_16,
CONTROLLER_PACKET_17, CONTROLLER_PACKET_18, CONTROLLER_PACKET_19, CONTROLLER_PACKET_20
}
enum UserWarningTypes {
HARDWARE_WARNING = 250, SENSOR_WARNING, NAV_WARNING, COMM_WARNING,
MISSION_WARNING, CONTROLLER_WARNING
}
Predefined user warning types.
Functions
void * DecodeControllerDataPacket (AutopilotPkt_t *pPkt, UInt8 *pController, UInt8 *pVersion, UInt8 *pCategory, UInt8 *pDataID, UInt8 *pNumData)
Extract the controller data from an autopilot packet.
void FormControllerDataPacket (AutopilotPkt_t *pPkt, UInt8 Controller, UInt8 Version, UInt8 Category, UInt8 DataID, UInt8 NumData, const void *pData)
Form a controller data packet which contains 32-bit data words.
BOOL DecodeControllerDataRequestPacket (const AutopilotPkt_t *pPkt, UInt8 *pController, UInt8 *pVersion, UInt8 *pCategory, UInt8 *pDataID, UInt8 *pNumData)
Extract the controller data request from an autopilot packet.
BOOL DecodeTransponderControlPacket (const AutopilotPkt_t *pPkt, UInt16 *pCode, BOOL *pIdent, UInt8 *pMode)
Extract the data from a transponder control packet.
void FormTransponderControlPacket (AutopilotPkt_t *pPkt, UInt16 Code, BOOL Ident, UInt8 Mode)
Form a tranponder control packet.
void FormTransponderPreflightPacket (AutopilotPkt_t *pPkt, const char FlightID[9])
Form the transponder preflight packet.
BOOL DecodeTransponderPreflightPacket (const AutopilotPkt_t *pPkt, char FlightID[9])
Decode the transponder preflight packet.
void FormTransponderInstallationPacket (AutopilotPkt_t *pPkt, UInt32 ICAOAddress, const char Registration[9])
Form the transponder installation packet.
BOOL DecodeTransponderInstallationPacket (const AutopilotPkt_t *pPkt, UInt32 *pICAOAddress, char Registration[9])
Decode the transponder installation packet.
void FormRadioSettingsPacket (AutopilotPkt_t *pPkt, const RadioSettings_t *pSettings)
Form a radio settings packet.
BOOL DecodeRadioSettingsPacket (const AutopilotPkt_t *pPkt, RadioSettings_t *pSettings)
Extract the data from a radio settings packet.
void FormAutopilotLoopControlPacket (AutopilotPkt_t *pPkt, const AutopilotLoopCmd_t *pCmd)
Form an autopilot loop control packet.
void FormAutopilotLoopControlPacketEx (AutopilotPkt_t *pPkt, const AutopilotLoopCmd_t *pCmd, BOOL UpdateEEPROM)
Form an autopilot loop control packet.
BOOL DecodeAutopilotLoopControlPacket (const AutopilotPkt_t *pPkt, AutopilotLoopCmd_t *pCmd)
Decode an autopilot loop control packet.
BOOL DecodeAutopilotLoopControlPacketEx (const AutopilotPkt_t *pPkt, AutopilotLoopCmd_t *pCmd, BOOL *pUpdateEEPROM)
Decode an autopilot loop control packet.
void FormActuatorTablePacket (AutopilotPkt_t *pPkt, const ActuatorTable_t *pTable, UInt8 Actuator, UInt8 Type, UInt8 Virtual, UInt8 Fast)
Form a autopilot actuator table calibration packet.
BOOL DecodeActuatorTablePacket (const AutopilotPkt_t *pPkt, ActuatorTable_t *pTable, UInt8 *pActuator, UInt8 *pType, UInt8 *pVirtual, UInt8 *pFast)
Decode a autopilot actator table calibration packet.
void FormOrientationPacket (AutopilotPkt_t *pPkt, const float Euler[NAXIS], const float IMUtoAnt[N3D], const float IMUtoAnt2[N3D])
Form an autopilot orientation packet.
BOOL DecodeOrientationPacket (const AutopilotPkt_t *pPkt, float Euler[NAXIS], float IMUtoAnt[N3D], float IMUtoAnt2[N3D])
Decode an autopilot orientation packet.
UInt16 DecodeWaypointsPacket (const AutopilotPkt_t *pPkt, FPPoint_t Points[MAX_WAYPOINTS_IN_PACKET], BOOL *pAck)
Decode a autopilot waypoints packet.
void FormWaypointsPacket (AutopilotPkt_t *pPkt, const FPPoint_t Points[MAX_WAYPOINTS_IN_PACKET], UInt16 Num, BOOL Ack)
Form a autopilot waypoints packet including the packet header and crc.
UInt8 DecodeWaypointListPacket (const AutopilotPkt_t *pPkt, FPMask_t Mask)
Extract the data from a waypoint list packet.
void FormWaypointListPacket (AutopilotPkt_t *pPkt, const FPMask_t Mask, UInt8 Flag)
Form a waypoint list packet.
void FormWaypointListRangePacket (AutopilotPkt_t *pPkt, UInt16 Start, UInt16 End, UInt8 Flag)
Form a autopilot waypoint list packet with a contiguous range of asserted.
void FormLegacyWaypointPacket (AutopilotPkt_t *pPkt, const FPPoint_t *pPoint, UInt8 Index)
Form a legacy autopilot waypoint packet (before 2.2.x)*/.
UInt16 DecodeLegacyWaypointPacket (const AutopilotPkt_t *pPkt, FPPoint_t *pPoint)
Decode a autopilot legacy waypoint packet (prior to version 2.2.x.
UInt8 DecodeLegacyWaypointListPacket (const AutopilotPkt_t *pPkt, FPMask_t Mask)
Decode a legacy autopilot waypoint list packet (before software 2.2.x).
void FormLegacyWaypointListPacket (AutopilotPkt_t *pPkt, const FPMask_t Mask, UInt8 Flag)
Form a legacy autopilot waypoint list packet (before software 2.2.x)
BOOL DecodeMissionLimitsPacket (const AutopilotPkt_t *pPkt, MissionLimits_t *pMission)
Decode mission limits packet.
void FormMissionLimitsPacket (AutopilotPkt_t *pPkt, const MissionLimits_t *pMission)
Form a mission limits packet.
void FormMagCalPacket (AutopilotPkt_t *pPkt, const float HardIronErr[N3D], const float ScaleFactErr[N3D])
Form a magnetometer calibration packet.
BOOL DecodeMagCalPacket (const AutopilotPkt_t *pPkt, float HardIronErr[N3D], float ScaleFactErr[N3D])
Decode a magnetometer calibration packet.
void FormExternalSerialSetupPacket (AutopilotPkt_t *pPkt, const ExternalSerial_t *pSerial)
Form a serial port setup packet.
BOOL DecodeExternalSerialSetupPacket (const AutopilotPkt_t *pPkt, ExternalSerial_t *pSerial)
Decode a serial port setup packet.
void FormExternalIOSetupPacket (AutopilotPkt_t *pPkt, const ExternalIO_t *pExternalIO, UInt8 pin, UInt32 SampleTime)
Create an external IO setup packet.
void FormExternalIOSetupPacketEx (AutopilotPkt_t *pPkt, const ExternalIO_t *pExternalIO, UInt8 pin, UInt32 SampleTime, BOOL UpdateEEPROM)
Create an external IO setup packet.
UInt8 DecodeExternalIOSetupPacket (const AutopilotPkt_t *pPkt, ExternalIO_t *pExternalIO, UInt32 *pSampleTime)
Extract the data from an external IO setup packet.
UInt8 DecodeExternalIOSetupPacketEx (const AutopilotPkt_t *pPkt, ExternalIO_t *pExternalIO, UInt32 *pSampleTime, BOOL *pUpdateEEPROM)
Extract the data from an external IO setup packet.
void FormSimpleLandingPacket (AutopilotPkt_t *pPkt, const SimpleLandingPattern_t *pLand)
Create a simple landing packet.
BOOL DecodeSimpleLandingPacket (const AutopilotPkt_t *pPkt, SimpleLandingPattern_t *pLand)
Extract the data from a simple landing packet.
void FormAltimeterSettingPacket (AutopilotPkt_t *pPkt, UInt32 Altimeter, BOOL ControlToGPS)
Create an altimeter setting packet.
BOOL DecodeAltimeterSettingPacket (const AutopilotPkt_t *pPkt, UInt32 *pAltimeter, BOOL *pControlToGPS)
Extract the data from a altimeter setting packet.
void FormBandwidthModePacket (AutopilotPkt_t *pPkt, BandwidthMode_t Mode)
Build a bandwidth mode packet.
BOOL DecodeBandwidthModePacket (const AutopilotPkt_t *pPkt, BandwidthMode_t *pMode)
Decode a bandwidth mode packet.
void FormPayloadMassPacket (AutopilotPkt_t *pPkt, float PayloadMass)
Form the payload mass packet including the packet header and crc.
BOOL DecodePayloadMassPacket (const AutopilotPkt_t *pPkt, float *pPayloadMass)
Decode the payload mass packet.
void FormThrottleMinPacket (AutopilotPkt_t *pPkt, float Throttle)
Form the throttle min packet, including the header and crc.
BOOL DecodeThrottleMinPacket (const AutopilotPkt_t *pPkt, float *pThrottle)
Decode the throttle min packet.
void FormECUCommandPacket (AutopilotPkt_t *pPkt, const ECUCommand_t *pCmd)
Form the ECU command packet.
BOOL DecodeECUCommandPacket (const AutopilotPkt_t *pPkt, ECUCommand_t *pCmd)
Decode the ECU command packet.
Detailed Description
Autopilot stream packet utilities.
This module provides functions for encoding and decoding packets from the autopilot stream to and from network representation as documented in "Piccolo Communications".
Macro Definition Documentation
#define CURRENT_WAYPOINTS 0
Currently active list (if downlink packet)
#define DELETE_WAYPOINTS 1
Delete waypoints (if uplink packet)
#define GET_WAYPOINT_LIST 0
Request waypoints (if uplink packet)
#define MAX_WAYPOINTS_IN_FLIGHT (3*MAX_WAYPOINTS_IN_PACKET)
Maximum amount of unacknowledged waypoint traffic.
#define MAX_WAYPOINTS_IN_PACKET 14
Maximum number of waypoints you can fit in one packet.
Referenced by FormWaypointsPacket().
#define REQUEST_WAYPOINTS 2
Request waypoints (if uplink packet)
#define WAYPOINT_ACK 4
Acknowledge receive of waypoints (both ways)
#define WAYPOINT_BLOCK 3
Prepare to receive waypoints (both ways)
Enumeration Type Documentation
enum AutopilotPacketTypes
Autopilot stream message types
Enumerator
USER_WARNING
User warning.
CONFIG_UNLOCK
Configuration unlock.
BANDWIDTH_MODE
Bandwidth mode request.
FEATURE_CODE
Feature code information.
CONFIG_LOCK
Configuration lockout.
ACTUATOR_TABLE
Control surface calibration.
PAYLOAD_MASS
Set or request the payload mass value.
ELEVATION_DATA
Ground elevation information.
LEGACY_WAYPOINT
Deprecated waypoint list.
LEGACY_WAYPOINT_LIST
Deprecated list of waypoint indices.
TRACK
Tracker command.
THROTTLE_MIN
Min throttle setting.
MISSION_SETTINGS
Mission settings.
ECU_STATUS
ECU status information.
SENSOR_ORIENTATION
Avionics installation orientation.
ALTIMETER_SETTING
Altimeter base pressure setting.
SYSTEM_RESET
System reset command.
SYSTEM_VERSION
System hardware and firmware version.
RESET_REPORT
Reset report packet.
ACTUATOR_TEST
Control actuator test.
MISSION_LIMITS
Mission Limits.
BOUNDARY
Airspace boundary.
USER_ACTION
User action command.
CONFIG_UNLOCK_QUIET
Configuration unlock without respone.
AUTOPILOT_LOOP
Individual autopilot loop control.
AUTO_FLARE_DISABLE
Disable/Enable automatic flare.
DESCRIPTION
Description field in EEPROM.
USER_SPACE
User data space in EEPROM.
MANUAL_FLARE_COMMAND
Issue a manual flare command.
WAYPOINT_LIST_RANGE
Waypoint list range packet.
MAG_CALIBRATION
Magnetometer calibration.
ENGINE_KILL
Engine kill command.
RADIO_TRANSMIT_DISABLE
Transmit disable for radio systems.
RADIO_SETTINGS
Radio settings.
EXTERNAL_SERIAL_SETUP
External serial port setup.
EXTERNAL_IO_SETUP
External IO setup.
EXTERNAL_IO_SAMPLE
External IO input sample.
WAYPOINTS
Multiple waypoints.
EXTERNAL_ADC_SAMPLE
External analog input sample.
LAND_NOW
The command to autoland the aircraft using the default landing waypoint.
EDC_EMU_SENSORS
Engine data converter / Engine monitor unit.
ECU_COMMAND
ECU command packet.
CLEAR_PDYN_FAULT
Clear air data fault cmd.
CREATE_SIMPLE_LANDING
Directs the navigator to create a simple landing pattern flightplan.
GPS_HEALTH
GPS health data.
AIR_DATA_ZERO
Zero just the air data sensors.
PRE_LAUNCH_MODE
Go to prelaunch mode.
NEW_MANUAL_ASSIST_MODE
Manual assist mode command.
LIGHTS_CMD
Lights command.
BRAKES_CMD
Brakes command.
PARACHUTE_CMD
Parachute command.
DROP_CMD
Drop command.
THROTTLE_TRIM
Set throttle trim.
DEVICE_DETAILS
Device detail information.
AVAILABLE_ID_36
Obsolete packet ID.
SERVO_TELEMETRY
Servo telemetry data.
TRANSPONDER_INSTALLATION
Transponder Mode S installation message.
TRANSPONDER_STATUS
Transponder status information.
SYSTEM_STATUS
System status information.
TRANSPONDER_CONTROL
Transponder control.
TRANSPONDER_PREFLIGHT
Transponder Mode S preflight message.
RAW_VIBRATION_DATA
Raw vibration data, 1024 samples at 1khz, 6 sensros.
FREQ_SWEEP_CMD
Command for initiating a frequency sweep maneuver.
LINK_BRIDGE
Bridging data from link to link.
DOUBLET_CMD
Command for initiating a doublet maneuver.
DOUBLET_AP_DATA
Returns autopilot data for a doublet.
DOUBLET_SENSOR_DATA
Returns high speed sensor data for a doublet.
CONTROLLER_DATA_REQUEST
Request controller data.
CONTROLLER_DATA
Controller data.
TELEMETRY_HI_RES
High resolution telemetry.
TELEMETRY_LO_RES
Low resolution telemetry.
LEGACY_SYSTEM_STATUS_HI_RES
Legacy high resolution status.
LEGACY_SYSTEM_STATUS_LO_RES
Legacy low resolution status.
LAUNCH_NOW
Launch now command.
CONTROLLER_DATA_DEFAULT
Default controller data.
SET_FUEL_LEVEL
Packet used to set the fuel level.
SENSOR_ERROR
Set the sensor errors.
CONTROLLER_ABORT
Issue an abort command to the controller.
MOVING_BASELINE_STATUS
Status of the moving baseline landing system.
SET_FUEL_IFLOCKED
Packet used to set the fuel level if the system is locked.
LATITUDE_RESERVED_0
Packet reserved for Latitude.
LATITUDE_RESERVED_1
Packet reserved for Latitude.
LATITUDE_RESERVED_2
Packet reserved for Latitude.
LATITUDE_RESERVED_3
Packet reserved for Latitude.
LATITUDE_RESERVED_4
Packet reserved for Latitude.
LATITUDE_RESERVED_5
Packet reserved for Latitude.
LATITUDE_RESERVED_6
Packet reserved for Latitude.
LATITUDE_RESERVED_7
Packet reserved for Latitude.
LATITUDE_RESERVED_8
Packet reserved for Latitude.
LATITUDE_RESERVED_9
Packet reserved for Latitude.
LATITUDE_RESERVED_A
Packet reserved for Latitude.
LATITUDE_RESERVED_B
Packet reserved for Latitude.
LATITUDE_RESERVED_C
Packet reserved for Latitude.
LATITUDE_RESERVED_D
Packet reserved for Latitude.
LATITUDE_RESERVED_E
Packet reserved for Latitude.
LATITUDE_RESERVED_F
Packet reserved for Latitude.
NUM_AP_PACKETS
The number of autopilot stream packets.
enum ControllerPacketTypes
Controller telemetry packet types, spanning from 220 to 239
enum UserWarningTypes
Predefined user warning types.
Enumerator
HARDWARE_WARNING
Warn on CPU and board problems.
SENSOR_WARNING
Warn on abnormal sensor data.
NAV_WARNING
Warn on nav filter and sensor fusion issues.
COMM_WARNING
Warn on communications and radio problems.
MISSION_WARNING
Warn on mission limits violations.
CONTROLLER_WARNING
Warn on controller issues.
Function Documentation
BOOL DecodeActuatorTablePacket (const AutopilotPkt_t * pPkt, ActuatorTable_t * pTable, UInt8 * pActuator, UInt8 * pType, UInt8 * pVirtual, UInt8 * pFast)
Decode a autopilot actator table calibration packet.
Decode a autopilot actator table calibration packet. This packet contains the calibration data for a single actuator.
Parameters
pPkt points to a autopilot packet to be decoded.
pTable points to a actuator calibration table to receive the data.
pActuator receives the actuator index.
pType receives the actuator type.
pVirtual receives the virtual actuator enable flag.
pFast receives the fast actuator enable flag.
Returns
TRUE if the packet is valid.
References ACTUATOR_TABLE, ActuatorTable_t::Angle, SimplePkt_t::Data, DataToSInt16(), DataToUInt16(), NUM_ACTUATOR_POINTS, NUM_ACTUATORS, SimplePkt_t::PktType, SimplePkt_t::Size, and ActuatorTable_t::Width.
BOOL DecodeAltimeterSettingPacket (const AutopilotPkt_t * pPkt, UInt32 * pAltimeter, BOOL * pControlToGPS)
Extract the data from a altimeter setting packet.
Extract the data from a altimeter setting packet
Parameters
pPkt points to a packet containing the data.
pAltimeter points to space to receive the altimeter setting in Pascals.
pControlToGPS points to space to receive the control to GPS altitude flag.
Returns
TRUE if the packet is valid, else FALSE.
References ALTIMETER_SETTING, SimplePkt_t::Data, DataToUInt32(), SimplePkt_t::PktType, and SimplePkt_t::Size.
BOOL DecodeAutopilotLoopControlPacket (const AutopilotPkt_t * pPkt, AutopilotLoopCmd_t * pCmd)
Decode an autopilot loop control packet.
Decode a autopilot loop control packet. The loop control packet is used to change individual autopilot loops without changing the state of the other loops.
Parameters
pPkt points to a autopilot packet to be decoded.
pCmd points to a loop command data structure to receive the data.
Returns
TRUE if the packet is valid, else FALSE.
References DecodeAutopilotLoopControlPacketEx().
BOOL DecodeAutopilotLoopControlPacketEx (const AutopilotPkt_t * pPkt, AutopilotLoopCmd_t * pCmd, BOOL * pUpdateEEPROM)
Decode an autopilot loop control packet.
Decode a autopilot loop control packet. The loop control packet is used to change individual autopilot loops without changing the state of the other loops.
Parameters
pPkt points to a autopilot packet to be decoded.
pCmd points to a loop command data structure to receive the data.
pUpdateEEPROM receives the UpdateEEPROM flag.
Returns
TRUE if the packet is valid, else FALSE.
References AUTOPILOT_LOOP, AutopilotLoopCmd_t::Control, SimplePkt_t::Data, DataToFloat(), AutopilotLoopCmd_t::Loop, SimplePkt_t::PktType, SimplePkt_t::Size, and AutopilotLoopCmd_t::Value.
Referenced by DecodeAutopilotLoopControlPacket().
BOOL DecodeBandwidthModePacket (const AutopilotPkt_t * pPkt, BandwidthMode_t * pMode)
Decode a bandwidth mode packet.
Extract the data from a bandwidth mode packet
Parameters
pPkt points to a packet containing the data.
pMode points to space to receive the data.
Returns
TRUE if the packet is valid, else FALSE.
References BANDWIDTH_MODE, BandwidthMode_t::ConEnable, BandwidthMode_t::ConMode, SimplePkt_t::Data, BandwidthMode_t::Link, BandwidthMode_t::LoRes, BandwidthMode_t::NavEnable, BandwidthMode_t::NavMode, SimplePkt_t::PktType, BandwidthMode_t::RegularMode, and SimplePkt_t::Size.
void* DecodeControllerDataPacket (AutopilotPkt_t * pPkt, UInt8 * pController, UInt8 * pVersion, UInt8 * pCategory, UInt8 * pDataID, UInt8 * pNumData)
Extract the controller data from an autopilot packet.
Extract the controller data from an autopilot packet. The packet contents may be changed during this function.
Parameters
pPkt points to the autopilot packet to decode.
pController receivers the controller ID value.
pVersion receives the controller version value.
pCategory receives the data category.
pDataID receives the starting DataID.
pNumData receives the number of data elements in the packet.
Returns
A pointer to the data elements, correctly formattted for the host system. This points to space inside the autopilot packet. NULL is returned if an error occurs.
References CONTROLLER_DATA, SimplePkt_t::Data, DataToUInt32(), IsValidFloat(), SimplePkt_t::PktType, and SimplePkt_t::Size.
BOOL DecodeControllerDataRequestPacket (const AutopilotPkt_t * pPkt, UInt8 * pController, UInt8 * pVersion, UInt8 * pCategory, UInt8 * pDataID, UInt8 * pNumData)
Extract the controller data request from an autopilot packet.
BOOL DecodeECUCommandPacket (const AutopilotPkt_t * pPkt, ECUCommand_t * pCmd)
Decode the ECU command packet.
Decode the ECU command packet.
Parameters
pPkt points to an autopilot packet to be decoded.
pCmd points to an ECU command structure that will receive the decoded data.
Returns
TRUE if the packet is valid, FALSE otherwise
References ECUCommand_t::ClearErrorBitsA, ECUCommand_t::ClearErrorBitsB, SimplePkt_t::Data, DataToUInt16(), ECUCommand_t::Destination, ECU_COMMAND, ECUCommand_t::EngineMode, ECUCommand_t::ErrorBitsA, ECUCommand_t::ErrorBitsB, SimplePkt_t::PktType, ECUCommand_t::PrimeEngine, ECUCommand_t::ReservedFlags, ECUCommand_t::ResetFuel, ECUCommand_t::SetEngineMode, and SimplePkt_t::Size.
UInt8 DecodeExternalIOSetupPacket (const AutopilotPkt_t * pPkt, ExternalIO_t * pExternalIO, UInt32 * pSampleTime)
Extract the data from an external IO setup packet.
Decode a external IO setup packet which contains the IO setup data for one pin.
Parameters
pPkt points to a autopilot packet containing the data
pExternalIO points to a structure to receive the IO setup data.
pSampleTime points to space to receive the sample time in milliseconds of the external IO.
Returns
the pin number that this setup data applies to. If the packet is not valid then the return is 0xFF.
References DecodeExternalIOSetupPacketEx().
UInt8 DecodeExternalIOSetupPacketEx (const AutopilotPkt_t * pPkt, ExternalIO_t * pExternalIO, UInt32 * pSampleTime, BOOL * pUpdateEEPROM)
Extract the data from an external IO setup packet.
Decode a external IO setup packet which contains the IO setup data for one pin.
Parameters
pPkt points to a autopilot packet containing the data
pExternalIO points to a structure to receive the IO setup data.
pSampleTime points to space to receive the sample time in milliseconds of the external IO.
pUpdateEEPROM receives the update eeprom flag.
Returns
the pin number that this setup data applies to. If the packet is not valid then the return is 0xFF.
References SimplePkt_t::Data, DataToSInt32(), EXTERNAL_IO_SETUP, ExternalIO_t::Mode, NUM_EXTERNAL_ADC_PINS, ExternalIO_t::Parameter1, ExternalIO_t::Parameter2, SimplePkt_t::PktType, and SimplePkt_t::Size.
Referenced by DecodeExternalIOSetupPacket().
BOOL DecodeExternalSerialSetupPacket (const AutopilotPkt_t * pPkt, ExternalSerial_t * pSerial)
Decode a serial port setup packet.
Decode a external serial setup packet.
Parameters
pPkt points to a autopilot packet containing the data
pSerial points to a structure to receive the serial setup data.
Returns
TRUE If packet is valid, else FALSE.
References SimplePkt_t::Data, EXTERNAL_SERIAL_SETUP, SimplePkt_t::PktType, and SimplePkt_t::Size.
UInt8 DecodeLegacyWaypointListPacket (const AutopilotPkt_t * pPkt, FPMask_t Mask)
Decode a legacy autopilot waypoint list packet (before software 2.2.x).
Decode a legacy autopilot waypoint list packet (before software 2.2.x). This packet contains a flight plan mask with one bit for every possible waypoint.
Parameters
pPkt points to a autopilot packet to be decoded.
Mask is the flight plan mask which receives the data.
Returns
The flags field included with the packet. If the packet is invalid then the return is 0xFF.
References SimplePkt_t::Data, LEGACY_FP_MASK_BYTES, LEGACY_WAYPOINT_LIST, SimplePkt_t::PktType, and SimplePkt_t::Size.
UInt16 DecodeLegacyWaypointPacket (const AutopilotPkt_t * pPkt, FPPoint_t * pPoint)
Decode a autopilot legacy waypoint packet (prior to version 2.2.x.
Decode a autopilot legacy waypoint packet (prior to version 2.2.x. This packet contains the data for a single waypoint.
Parameters
pPkt points to a autopilot packet to be decoded.
pPoint to a waypoint structure to receive the data.
Returns
The index of this waypoint structure. If the packet is not valid 0xFFFF is returned.
References FPPoint_t::AGL, Waypoint_t::Alt, SimplePkt_t::Data, DataToSInt16(), DataToSInt32(), FPPoint_t::Direction, FPPoint_t::Drop, FPPoint_t::Hover, FPPoint_t::Land, Waypoint_t::Lat, LEGACY_WAYPOINT, FPPoint_t::Lights, Waypoint_t::Lon, FPPoint_t::Next, FPPoint_t::OrbitAboveAlt, FPPoint_t::OrbitBelowAlt, FPPoint_t::OrbitRadius, FPPoint_t::OrbitTime, FPPoint_t::Parachute, SimplePkt_t::PktType, FPPoint_t::Point, FPPoint_t::PreTurn, FPPoint_t::Reserved, SimplePkt_t::Size, FPPoint_t::Slope, FPPoint_t::This, and FPPoint_t::User.
BOOL DecodeMagCalPacket (const AutopilotPkt_t * pPkt, float HardIronErr[N3D], float ScaleFactErr[N3D])
Decode a magnetometer calibration packet.
Decode a packet with magnetometer calibration data.
Parameters
pPkt points to a autopilot packet;
HardIronErr is a vector of hard iron errors;
ScaleFactErr is a vector of scale factor errors.
Returns
TRUE if the packet is valid, else FALSE.
References SimplePkt_t::Data, DataToFloat(), MAG_CALIBRATION, N3D, SimplePkt_t::PktType, and SimplePkt_t::Size.
BOOL DecodeMissionLimitsPacket (const AutopilotPkt_t * pPkt, MissionLimits_t * pMission)
Decode mission limits packet.
Decode a autopilot mission limits packet. The mission limits packet contains timeouts and actions which limit are used to limit the scope of the mission.
Parameters
pPkt points to a autopilot packet to be decoded.
pMission points to space to receive the mission limits data.
Returns
TRUE If packet is valid, else FALSE.
References MissionLimits_t::AltitudeMax, MissionLimits_t::AltitudeMin, MissionLimits_t::AutolandWaypoint, Failure_t::BoundaryCausesFT, Failure_t::CommCausesFT, MissionLimits_t::CommTimeout, MissionLimits_t::CritFuel, Failure_t::CritFuelCausesAbort, SimplePkt_t::Data, DataToSInt16(), DataToUInt16(), DataToUInt32(), Failure_t::EngineKillsDeadman, MissionLimits_t::Failure, Failure_t::FlightTimeandCommCauseLanding, MissionLimits_t::FlightTimeout, Failure_t::FTCausesAbort, Failure_t::FTCausesAeroTerm, Failure_t::FTCausesParachute, Failure_t::FTDropsDeadman, Failure_t::FTKillsEngine, Failure_t::GPSandCommCauseFT, Failure_t::GPSCausesFT, MissionLimits_t::GPSTimeout, Failure_t::HighAltitudeCausesFT, Failure_t::IgnoreTimeoutsInPrelaunch, MissionLimits_t::LostCommWaypoint, Failure_t::LowAltitudeCausesFT, Failure_t::LowFuelCausesAutoLand, MissionLimits_t::MinFuel, MISSION_LIMITS, MissionLimits_t::PilotTimeout, SimplePkt_t::PktType, SimplePkt_t::Size, and MissionLimits_t::UseMaxAltForLostComm.
BOOL DecodeOrientationPacket (const AutopilotPkt_t * pPkt, float Euler[NAXIS], float IMUtoAnt[N3D], float IMUtoAnt2[N3D])
Decode an autopilot orientation packet.
Decode a autopilot sensor orientation packet. This packet contains the Euler angle rotations to go from avionics axis to vehicle axis, as well as the IMU to GPS antenna relative position vectors; First offset corresponds to the main GPS antenna, the second offset corresponds to a secondary GPS antenna used by the Novatel Align rover receiver for GPS heading calculation.
Parameters
pPkt points to a autopilot packet to be decoded.
Euler points to an array to hold the Euler angles (ROLL, PITCH, YAW).
IMUtoAnt points to an array to hold the IMU to main GPS antenna relative position vector, in vehicle frame, in meters.
IMUtoAnt2 points to an array to hold the IMU to rover GPS antenna relative position vector, in vehicle frame, in meters.
Returns
TRUE if the packet is valid, else FALSE.
References SimplePkt_t::Data, DataToFloat(), N3D, SimplePkt_t::PktType, SENSOR_ORIENTATION, and SimplePkt_t::Size.
BOOL DecodePayloadMassPacket (const AutopilotPkt_t * pPkt, float * pPayloadMass)
Decode the payload mass packet.
Decode a payload mass packet
Parameters
pPkt points to a autopilot packet to be decoded.
pPayloadMass points to space to receive the mass in kilograms.
Returns
TRUE If packet is valid, else FALSE.
References SimplePkt_t::Data, DataToFloat(), PAYLOAD_MASS, SimplePkt_t::PktType, and SimplePkt_t::Size.
BOOL DecodeRadioSettingsPacket (const AutopilotPkt_t * pPkt, RadioSettings_t * pSettings)
Extract the data from a radio settings packet.
Decode a autopilot radio settings packet. The radio settings packet is used to control the channel and output power of the radio.
Parameters
pPkt points to a autopilot packet to be decoded.
pSettings points to a radio settings structure to receive the data.
Returns
TRUE if the packet is valid, else FALSE.
References RadioSettings_t::AESMode, RadioSettings_t::Channel, SimplePkt_t::Data, DataToFloat(), RadioSettings_t::Freq, RadioSettings_t::Key, SimplePkt_t::PktType, RadioSettings_t::Power, RADIO_SETTINGS, SimplePkt_t::Size, RadioSettings_t::Speed, and RadioSettings_t::Type.
BOOL DecodeSimpleLandingPacket (const AutopilotPkt_t * pPkt, SimpleLandingPattern_t * pLand)
Extract the data from a simple landing packet.
Decode a packet containing the simple landing pattern information necessary for creating a simple landing pattern flightplan.
Parameters
pPkt points to a autopilot packet to receive the formatted data.
pLand points to a simple landing pattern data structure.
Returns
TRUE if the packet is valid, else FALSE.
References Waypoint_t::Alt, CREATE_SIMPLE_LANDING, SimplePkt_t::Data, DataToSInt16(), DataToSInt32(), DataToUInt16(), SimpleLandingPattern_t::Dir, SimpleLandingPattern_t::Heading, Waypoint_t::Lat, Waypoint_t::Lon, SimplePkt_t::PktType, SimplePkt_t::Size, SimpleLandingPattern_t::Start, and SimpleLandingPattern_t::WpT.
BOOL DecodeThrottleMinPacket (const AutopilotPkt_t * pPkt, float * pThrottle)
Decode the throttle min packet.
Decode the min throttle packet
Parameters
pPkt points to a autopilot packet to be decoded.
pThrottle points to space to receive the min throttle setting.
Returns
TRUE If packet is valid, else FALSE.
References SimplePkt_t::Data, DataToUInt16(), SimplePkt_t::PktType, SimplePkt_t::Size, and THROTTLE_MIN.
BOOL DecodeTransponderControlPacket (const AutopilotPkt_t * pPkt, UInt16 * pCode, BOOL * pIdent, UInt8 * pMode)
Extract the data from a transponder control packet.
Decode a autopilot transponder control packet. The tranponder packet is used to control the squawk and ident of the transponder
Parameters
pPkt points to a autopilot packet to be decoded.
pCode points to space to receive the squawk code.
pIdent points to space to receive the ident flag.
Mode points to space to receive the transponder mode, 0 for standby, 1 for A mode, 2 for C Mode.
Returns
TRUE if the packet is valid, else FALSE.
References SimplePkt_t::Data, DataToUInt16(), SimplePkt_t::PktType, SimplePkt_t::Size, and TRANSPONDER_CONTROL.
BOOL DecodeTransponderInstallationPacket (const AutopilotPkt_t * pPkt, UInt32 * pICAOAddress, char Registration[9])
Decode the transponder installation packet.
Decode the transponder installation packet, which provides the ICAO address and aircraft registration.
Parameters
pPkt points to the autopilot packet that holds the transponder installation data.
pICAOAddress points to a 4-byte integer that will receive the 3-byte ICAO address.
Registration is a string that will receive the aircraft registration.
Returns
TRUE if the packet is successfully decoded.
References SimplePkt_t::Data, DataToUInt24(), SimplePkt_t::PktType, SimplePkt_t::Size, and TRANSPONDER_INSTALLATION.
BOOL DecodeTransponderPreflightPacket (const AutopilotPkt_t * pPkt, char FlightID[9])
Decode the transponder preflight packet.
Decode the transponder preflight packet, which provides the flight identifier.
Parameters
pPkt points to the autopilot packet that holds the preflight transponder settings.
FlightID is a character string that will receive the flight id used when filing the flight plan, size requirement 9 characters.
Returns
TRUE if the packet is valid.
References SimplePkt_t::Data, SimplePkt_t::PktType, SimplePkt_t::Size, and TRANSPONDER_PREFLIGHT.
UInt8 DecodeWaypointListPacket (const AutopilotPkt_t * pPkt, FPMask_t Mask)
Extract the data from a waypoint list packet.
Decode a autopilot waypoint list packet. This packet contains a flight plan mask with one bit for every possible waypoint.
Parameters
pPkt points to a autopilot packet to be decoded.
Mask is the flight plan mask which receives the data.
Returns
The flags field included with the packet. If the packet is invalid then the return is 0xFF.
References ClearAllFPMaskBits(), SimplePkt_t::Data, DataToUInt24(), FP_MASK_BYTES, NUM_FP_POINTS, SimplePkt_t::PktType, SetFPMaskBit(), SimplePkt_t::Size, and WAYPOINT_LIST_RANGE.
UInt16 DecodeWaypointsPacket (const AutopilotPkt_t * pPkt, FPPoint_t Points[MAX_WAYPOINTS_IN_PACKET], BOOL * pAck)
Decode a autopilot waypoints packet.
Decode a autopilot waypoints packet. This packet contains the data for up to MAX_WAYPOINTS_IN_PACKET (14) waypoints.
Parameters
pPkt points to a autopilot packet to be decoded.
Points receives all the waypoints in the packet.
pAck receives the ack bit.
Returns
The number of points decoded from the packet, or 0 if the packet is invalid.
References SimplePkt_t::Data, DataToUInt32(), NUM_FP_POINTS, SimplePkt_t::PktType, SimplePkt_t::Size, and WAYPOINTS.
void FormActuatorTablePacket (AutopilotPkt_t * pPkt, const ActuatorTable_t * pTable, UInt8 Actuator, UInt8 Type, UInt8 Virtual, UInt8 Fast)
Form a autopilot actuator table calibration packet.
Form a autopilot actuator table calibration packet including the packet header and crc. The actuator calibration packet encodes the relationship between pulse width and actuator position for a single actuator. It also encodes the functional type of the actuator.
Parameters
pPkt points to a autopilot packet to receive the formatted data.
pTable points to a single actuator calibration table.
Actuator is the actuator index that the table refers to.
Type is the actuator type of the actuator.
Virtual is the virtual actuator flag.
Fast is the fast actuator flag.
References ACTUATOR_TABLE, ActuatorTable_t::Angle, SimplePkt_t::Data, MakeAutopilotPacket(), NUM_ACTUATOR_POINTS, RoundToSInt16(), SInt16ToData(), UInt16ToData(), and ActuatorTable_t::Width.
Referenced by CommBase_SendActuatorTablePacket().
void FormAltimeterSettingPacket (AutopilotPkt_t * pPkt, UInt32 Altimeter, BOOL ControlToGPS)
Create an altimeter setting packet.
Create an altimeter setting packet
Parameters
pPkt points to space to receive the formatted packet.
Altimeter is the altimeter setting in Pascals.
ControlToGPS should be TRUE to tell the autopilot to fly according to GPS altitude (else barometer).
References ALTIMETER_SETTING, SimplePkt_t::Data, MakeAutopilotPacket(), and UInt32ToData().
Referenced by CommBase_SendAltimeterSettingPacket().
void FormAutopilotLoopControlPacket (AutopilotPkt_t * pPkt, const AutopilotLoopCmd_t * pCmd)
Form an autopilot loop control packet.
Form a autopilot stream loop control packet including the packet header and crc. The loop control packet is used to change individual autopilot loops without changing the state of the other loops.
Parameters
pPkt points to a autopilot packet to receive the formatted data.
pCmd points to individual loop data to be included in the packet.
References FormAutopilotLoopControlPacketEx().
void FormAutopilotLoopControlPacketEx (AutopilotPkt_t * pPkt, const AutopilotLoopCmd_t * pCmd, BOOL UpdateEEPROM)
Form an autopilot loop control packet.
Form a autopilot stream loop control packet including the packet header and crc. The loop control packet is used to change individual autopilot loops without changing the state of the other loops.
Parameters
pPkt points to a autopilot packet to receive the formatted data.
pCmd points to individual loop data to be included in the packet.
UpdateEEPROM should be TRUE to make the autopilot update its EEPROM with this data.
References AUTOPILOT_LOOP, AutopilotLoopCmd_t::Control, SimplePkt_t::Data, FloatToData(), AutopilotLoopCmd_t::Loop, MakeAutopilotPacket(), and AutopilotLoopCmd_t::Value.
Referenced by CommBase_SendAutopilotLoopControlPacket(), and FormAutopilotLoopControlPacket().
void FormBandwidthModePacket (AutopilotPkt_t * pPkt, BandwidthMode_t Mode)
Build a bandwidth mode packet.
Build a bandwidth mode packet
Parameters
pPkt receives the formatted packet.
Mode is the bandwidth mode.
References BANDWIDTH_MODE, BandwidthMode_t::ConEnable, BandwidthMode_t::ConMode, SimplePkt_t::Data, BandwidthMode_t::Link, BandwidthMode_t::LoRes, MakeAutopilotPacket(), BandwidthMode_t::NavEnable, BandwidthMode_t::NavMode, and BandwidthMode_t::RegularMode.
Referenced by CommBase_SendBandwidthModePacket().
void FormControllerDataPacket (AutopilotPkt_t * pPkt, UInt8 Controller, UInt8 Version, UInt8 Category, UInt8 DataID, UInt8 NumData, const void * pData)
Form a controller data packet which contains 32-bit data words.
Form a controller data packet which contains 32-bit data words
Parameters
pPkt points to the autopilot packet to format
Controller is the controller ID value.
Version is the controller version value.
Category is the data category.
DataID is the starting DataID.
NumData is the number of data elements to encode.
pData points to the data to encode.
References CONTROLLER_DATA, SimplePkt_t::Data, MakeAutopilotPacket(), MAX_SIMPLE_DATA, and UInt32ToData().
Referenced by CommBase_SendControllerDataPacket().
void FormECUCommandPacket (AutopilotPkt_t * pPkt, const ECUCommand_t * pCmd)
Form the ECU command packet.
Form the ECU command packet.
Parameters
pPkt points to an autopilot packet that will receive the formatted data.
pCmd points to an ECU command structure.
References ECUCommand_t::ClearErrorBitsA, ECUCommand_t::ClearErrorBitsB, SimplePkt_t::Data, ECUCommand_t::Destination, ECU_COMMAND, ECUCommand_t::EngineMode, ECUCommand_t::ErrorBitsA, ECUCommand_t::ErrorBitsB, MakeAutopilotPacket(), ECUCommand_t::PrimeEngine, ECUCommand_t::ResetFuel, ECUCommand_t::SetEngineMode, and UInt16ToData().
void FormExternalIOSetupPacket (AutopilotPkt_t * pPkt, const ExternalIO_t * pExternalIO, UInt8 pin, UInt32 SampleTime)
Create an external IO setup packet.
Form an autopilot packet with the setup parameters for a single external IO pin.
Parameters
pPkt points to a autopilot packet to receive the formatted data.
pExternalIO points to a structure containing the setup parameters.
pin identifies which IO pin these setup data apply to.
SampleTime is the time in milliseconds that the external IO inputs should be sampled.
References FormExternalIOSetupPacketEx().
void FormExternalIOSetupPacketEx (AutopilotPkt_t * pPkt, const ExternalIO_t * pExternalIO, UInt8 pin, UInt32 SampleTime, BOOL UpdateEEPROM)
Create an external IO setup packet.
Form an autopilot packet with the setup parameters for a single external IO pin.
Parameters
pPkt points to a autopilot packet to receive the formatted data.
pExternalIO points to a structure containing the setup parameters.
pin identifies which IO pin these setup data apply to.
SampleTime is the time in milliseconds that the external IO inputs should be sampled.
UpdateEEPROM should be true to trigger an EEPROM update.
References SimplePkt_t::Data, EXTERNAL_IO_SETUP, MakeAutopilotPacket(), ExternalIO_t::Mode, ExternalIO_t::Parameter1, ExternalIO_t::Parameter2, and SInt32ToData().
Referenced by CommBase_SendExternalIOSetupPacket(), and FormExternalIOSetupPacket().
void FormExternalSerialSetupPacket (AutopilotPkt_t * pPkt, const ExternalSerial_t * pSerial)
Form a serial port setup packet.
Form an autopilot packet with the external serial setup parameters.
Parameters
pPkt points to a autopilot packet to receive the formatted data.
pSerial points to a structure containing the serial setup parameters.
References SimplePkt_t::Data, EXTERNAL_SERIAL_SETUP, and MakeAutopilotPacket().
Referenced by CommBase_SendExternalSerialSetupPacket().
void FormLegacyWaypointListPacket (AutopilotPkt_t * pPkt, const FPMask_t Mask, UInt8 Flag)
Form a legacy autopilot waypoint list packet (before software 2.2.x)
Form a legacy autopilot waypoint list packet (before software 2.2.x) including the packet header and crc. This packet contains a flight plan mask with one bit for every possible waypoint; and a flags parameter telling the avionics how to use the mask.
Parameters
pPkt points to a autopilot packet to receive the formatted data.
Maks is the flight plan mask to be encoded.
Flag is the flight plan mask flags field. The flag should have one of these values:
GET_WAYPOINT_LIST: indicates that the avionics should downlink a valid waypoint list.
DELETE_WAYPOINTS: indicates that the avionics should delete each waypoint in the list.
REQUEST_WAYPOINTS: indicates that the avionics should downlink each waypoint in the list.
WAYPOINT_BLOCK: indicates that a waypoint bock transfer is beginning. The waypoints to be transferred are in the list.
References SimplePkt_t::Data, LEGACY_FP_MASK_BYTES, LEGACY_WAYPOINT_LIST, and MakeAutopilotPacket().
Referenced by CommBase_SendLegacyWaypointListPacket().
void FormLegacyWaypointPacket (AutopilotPkt_t * pPkt, const FPPoint_t * pPoint, UInt8 Index)
Form a legacy autopilot waypoint packet (before 2.2.x)*/.
Form a legacy autopilot waypoint packet (before 2.2.x) including the packet header and crc. This packet contains all the data for a single waypoint.
Parameters
pPkt points to a autopilot packet to receive the formatted data.
pPoint contains the waypoint data.
Index is the waypoint index.
References FPPoint_t::AGL, Waypoint_t::Alt, SimplePkt_t::Data, FPPoint_t::Direction, FPPoint_t::Drop, FPPoint_t::Hover, FPPoint_t::Land, Waypoint_t::Lat, LEGACY_WAYPOINT, FPPoint_t::Lights, Waypoint_t::Lon, MakeAutopilotPacket(), FPPoint_t::Next, FPPoint_t::OrbitAboveAlt, FPPoint_t::OrbitBelowAlt, FPPoint_t::OrbitRadius, FPPoint_t::OrbitTime, FPPoint_t::Parachute, FPPoint_t::Point, FPPoint_t::PreTurn, RoundToSInt32(), RoundToUInt8(), SInt16ToData(), SInt32ToData(), FPPoint_t::Slope, and FPPoint_t::User.
Referenced by CommBase_SendLegacyWaypointPacket().
void FormMagCalPacket (AutopilotPkt_t * pPkt, const float HardIronErr[N3D], const float ScaleFactErr[N3D])
Form a magnetometer calibration packet.
Form a packet with the magnetometer calibration data.
Parameters
pPkt points to a autopilot packet;
HardIronErr is a vector of hard iron errors;
ScaleFactErr is a vector of scale factor errors.
References SimplePkt_t::Data, FloatToData(), MAG_CALIBRATION, MakeAutopilotPacket(), and N3D.
Referenced by CommBase_SendMagCalPacket().
void FormMissionLimitsPacket (AutopilotPkt_t * pPkt, const MissionLimits_t * pMission)
Form a mission limits packet.
Form a autopilot mission limits packet including the packet header and crc. The mission limits packet contains timeouts and actions which limit are used to limit the scope of the mission.
Parameters
pPkt points to a autopilot packet to receive the formatted data.
pMission points to the mission limit data.
References MissionLimits_t::AltitudeMax, MissionLimits_t::AltitudeMin, MissionLimits_t::AutolandWaypoint, Failure_t::BoundaryCausesFT, Failure_t::CommCausesFT, MissionLimits_t::CommTimeout, MissionLimits_t::CritFuel, Failure_t::CritFuelCausesAbort, SimplePkt_t::Data, Failure_t::EngineKillsDeadman, MissionLimits_t::Failure, Failure_t::FlightTimeandCommCauseLanding, MissionLimits_t::FlightTimeout, Failure_t::FTCausesAbort, Failure_t::FTCausesAeroTerm, Failure_t::FTCausesParachute, Failure_t::FTDropsDeadman, Failure_t::FTKillsEngine, Failure_t::GPSandCommCauseFT, Failure_t::GPSCausesFT, MissionLimits_t::GPSTimeout, Failure_t::HighAltitudeCausesFT, Failure_t::IgnoreTimeoutsInPrelaunch, MissionLimits_t::LostCommWaypoint, Failure_t::LowAltitudeCausesFT, Failure_t::LowFuelCausesAutoLand, MakeAutopilotPacket(), MissionLimits_t::MinFuel, MISSION_LIMITS, MissionLimits_t::PilotTimeout, SInt16ToData(), UInt16ToData(), UInt32ToData(), and MissionLimits_t::UseMaxAltForLostComm.
Referenced by CommBase_SendMissionLimitsPacket().
void FormOrientationPacket (AutopilotPkt_t * pPkt, const float Euler[NAXIS], const float IMUtoAnt[N3D], const float IMUtoAnt2[N3D])
Form an autopilot orientation packet.
Form a autopilot orientation packet including the packet header and crc. This packet contains the Euler angle rotations to go from avionics axis to vehicle axis, as well as the IMU to GPS antenna relative position vectors; First offset corresponds to the main GPS antenna, the second offset corresponds to a secondary GPS antenna used by the Novatel Align rover receiver for GPS heading calculation.
Parameters
pPkt points to a autopilot packet to receive the formatted data.
Euler is an array of Euler angles (ROLL, PITCH, YAW).
IMUtoAnt is an array of IMU to main GPS antenna offsets in meters (vehicle axes).
IMUtoAnt2 is an array of IMU to rover GPS antenna offsets in meters (vehicle axes).
References SimplePkt_t::Data, FloatToData(), MakeAutopilotPacket(), N3D, and SENSOR_ORIENTATION.
Referenced by CommBase_SendOrientationPacket().
void FormPayloadMassPacket (AutopilotPkt_t * pPkt, float PayloadMass)
Form the payload mass packet including the packet header and crc.
Form a payload mass packet including the packet header and crc.
Parameters
pPkt points to a autopilot packet to receive the formatted data.
PayloadMass is the mass in kilograms.
References SimplePkt_t::Data, FloatToData(), MakeAutopilotPacket(), and PAYLOAD_MASS.
Referenced by CommBase_SendPayloadMassPacket().
void FormRadioSettingsPacket (AutopilotPkt_t * pPkt, const RadioSettings_t * pSettings)
Form a radio settings packet.
Form a autopilot radio settings packet including the packet header and crc. The radio settings packet is used to control the channel and output power of the radio.
Parameters
pPkt points to a autopilot packet to receive the formatted data.
pSettings points to radio settings to be included in the packet.
References RadioSettings_t::AESMode, RadioSettings_t::Channel, SimplePkt_t::Data, FloatToData(), RadioSettings_t::Freq, RadioSettings_t::Key, MakeAutopilotPacket(), RadioSettings_t::Power, RADIO_SETTINGS, RoundToUInt8(), RadioSettings_t::Speed, and RadioSettings_t::Type.
Referenced by CommBase_SendRadioSettingsPacket().
void FormSimpleLandingPacket (AutopilotPkt_t * pPkt, const SimpleLandingPattern_t * pLand)
Create a simple landing packet.
Form a packet containing the simple landing pattern information necessary for creating a simple landing pattern flightplan.
Parameters
pPkt points to a autopilot packet to receive the formatted data.
pLand points to a simple landing pattern data structure.
References Waypoint_t::Alt, CREATE_SIMPLE_LANDING, SimplePkt_t::Data, SimpleLandingPattern_t::Dir, SimpleLandingPattern_t::Heading, Waypoint_t::Lat, Waypoint_t::Lon, MakeAutopilotPacket(), RoundToSInt16(), RoundToSInt32(), SInt16ToData(), SInt32ToData(), SimpleLandingPattern_t::Start, UInt16ToData(), and SimpleLandingPattern_t::WpT.
Referenced by CommBase_SendSimpleLandingPacket().
void FormThrottleMinPacket (AutopilotPkt_t * pPkt, float Throttle)
Form the throttle min packet, including the header and crc.
Form the throttle min packet, including the header and crc
Parameters
pPkt points to a autopilot packet to receive the formatted data.
Throttle is the min throttle value from 0 to 1.
References SimplePkt_t::Data, MakeAutopilotPacket(), RoundToUInt16(), THROTTLE_MIN, and UInt16ToData().
Referenced by CommBase_SendThrottleMinPacket().
void FormTransponderControlPacket (AutopilotPkt_t * pPkt, UInt16 Code, BOOL Ident, UInt8 Mode)
Form a tranponder control packet.
Form a autopilot transponder control packet including the packet header and crc. The transponder control packet is used to set the squawk code and ident flag of an external transponder
Parameters
Code is the transponder squawk code to use.
Ident should be true to cause the tranponder to Ident.
Mode specifies the transponder mode, 0 for standby, 1 for A mode, 2 for C Mode.
References SimplePkt_t::Data, MakeAutopilotPacket(), TRANSPONDER_CONTROL, and UInt16ToData().
Referenced by CommBase_SendTransponderControlPacket().
void FormTransponderInstallationPacket (AutopilotPkt_t * pPkt, UInt32 ICAOAddress, const char Registration[9])
Form the transponder installation packet.
Form the transponder installation packet, which provides the ICAO address and aircraft registration.
Parameters
pPkt points to the autopilot packet that will receive the transponder installation data.
ICAOAddress is the 3-byte ICAO address.
Registration is the aircraft registration string.
References SimplePkt_t::Data, MakeAutopilotPacket(), TRANSPONDER_INSTALLATION, and UInt24ToData().
Referenced by CommBase_SendTransponderInstallationPacket().
void FormTransponderPreflightPacket (AutopilotPkt_t * pPkt, const char FlightID[9])
Form the transponder preflight packet.
Form the transponder preflight packet, which provides the flight identifier.
Parameters
pPkt points to the autopilot packet that will receive the preflight transponder settings.
FlightID is a null-terminated string that holds the flight id used when filing the flight plan.
References SimplePkt_t::Data, MakeAutopilotPacket(), and TRANSPONDER_PREFLIGHT.
Referenced by CommBase_SendTransponderPreflightPacket().
void FormWaypointListPacket (AutopilotPkt_t * pPkt, const FPMask_t Mask, UInt8 Flags)
Form a waypoint list packet.
Form a autopilot waypoint list packet with a non-contiguous range of asserted waypoints.
Parameters
pPkt points to a autopilot packet to receive the formatted data.
Mask is the flight plan mask to be encoded.
Flags is the flight plan mask flags field.
References SimplePkt_t::Data, FP_MASK_BYTES, MakeAutopilotPacket(), UInt24ToData(), and WAYPOINT_LIST_RANGE.
Referenced by CommBase_SendWaypointListPacket().
void FormWaypointListRangePacket (AutopilotPkt_t * pPkt, UInt16 Start, UInt16 End, UInt8 Flags)
Form a autopilot waypoint list packet with a contiguous range of asserted.
Form a autopilot waypoint list packet with a contiguous range of asserted waypoints.
Parameters
pPkt points to a autopilot packet to receive the formatted data.
Start is the first waypoint index to be asserted.
End is the last waypoint index to be asserted.
Flags is the flight plan mask flags field.
References SimplePkt_t::Data, MakeAutopilotPacket(), UInt32ToData(), and WAYPOINT_LIST_RANGE.
Referenced by CommBase_SendWaypointListRangePacket().
void FormWaypointsPacket (AutopilotPkt_t * pPkt, const FPPoint_t Points[MAX_WAYPOINTS_IN_PACKET], UInt16 Num, BOOL Ack)
Form a autopilot waypoints packet including the packet header and crc.
Form a autopilot waypoint packet including the packet header and crc. This packet contains all the data for one or more waypoints (up to MAX_WAYPOINTS_IN_PACKET).
Parameters
pPkt points to a autopilot packet to receive the formatted data.
Points contains the waypoints data.
Num is the number of waypoints to encode, up to MAX_WAYPOINTS_IN_PACKET.
Ack should be TRUE to set the ack bit.
References SimplePkt_t::Data, MakeAutopilotPacket(), MAX_WAYPOINTS_IN_PACKET, RoundToUInt8(), UInt32ToData(), and WAYPOINTS.
Referenced by CommBase_SendWaypointsPacket().