Communications SDK: AutopilotPacketGnd.h File Reference
AutopilotPacketGnd.h File Reference
Autopilot packet utilities used on the ground.
#include "AutopilotPacket.h"
Classes
struct UserData_t
struct LowSpeedDoubletData_t
struct HighSpeedDoubletData_t
Functions
BOOL DecodeGPSHealth (const AutopilotPkt_t *pPkt, GPSUser_t *pGPS, UInt8 *pIndex, UInt8 *pNum)
Decode GPS health information for a single GPS.
void FormSensorErrorPacket (AutopilotPkt_t *pPkt, const SensorErrorData_t *pSensorError)
Build a sensor error packet.
BOOL DecodeSensorErrorPacket (const AutopilotPkt_t *pPkt, SensorErrorData_t *pSensorError)
Decode a sensor error packet.
const char * DecodeDeviceDetails (AutopilotPkt_t *pPkt, UInt8 *pIndex, UInt8 *pDevice, BOOL *pComplete)
Decode device details packet.
void FormUserActionPacket (AutopilotPkt_t *pPkt, UInt8 ActionIndex, BOOL On)
Form the user action command.
BOOL DecodeECUStatusPacket (const AutopilotPkt_t *pPkt, ECU_t *pECU)
Decode an ECU status packet.
BOOL DecodeTelemetryHiResPacket (const AutopilotPkt_t *pPkt, UserData_t *pData)
Decode a high resolution telemetry packet.
BOOL DecodeTelemetryLoResPacket (const AutopilotPkt_t *pPkt, UserData_t *pData)
Decode a low resolution telemetry packet.
BOOL DecodeSystemStatusPacket (const AutopilotPkt_t *pPkt, SystemDiagnostic_t *pSystem, NavDiagnostic_t *pNav, AutopilotStatus_t *pStatus, BOOL *pLong)
Decode a system status packet.
BOOL DecodeLegacySystemStatusHiResPacket (const AutopilotPkt_t *pPkt, SystemDiagnostic_t *pSystem, NavDiagnostic_t *pNav, AutopilotStatus_t *pStatus, BOOL *pLong)
Decode a legacy high resolution system status packet.
BOOL DecodeLegacySystemStatusLoResPacket (const AutopilotPkt_t *pPkt, SystemDiagnostic_t *pSystem, NavDiagnostic_t *pNav, AutopilotStatus_t *pStatus, BOOL *pLong)
Decode a legacy low resolution system status packet.
void FormControllerDataRequestPacket (AutopilotPkt_t *pPkt, UInt8 Controller, UInt8 Version, UInt8 Category, UInt8 DataID, UInt8 NumData)
Form a controller data request packet.
void FormControllerDataDefaultPacket (AutopilotPkt_t *pPkt, UInt8 Controller, UInt8 Version, UInt8 Category, UInt8 DataID, UInt8 NumData)
Form a controller data default packet.
UInt32 DecodeLowSpeedDoubletDataPacket (const AutopilotPkt_t *pPkt, UInt16 *pSampleIndex, UInt16 *pSampleRate, UInt16 *pTotalSamples, LowSpeedDoubletData_t Data[10])
Decode a low speed doublet data packet.
UInt32 DecodeHighSpeedDoubletDataPacket (const AutopilotPkt_t *pPkt, UInt16 *pSampleIndex, UInt16 *pSampleRate, UInt16 *pTotalSamples, HighSpeedDoubletData_t Data[10])
Decode a high speed doublet data packet.
void FormDoubletCommandPacket (AutopilotPkt_t *pPkt, const DoubletCmd_t *pCmd)
Form a packet commanding a doublet manuever.
void FormFrequencySweepCommandPacket (AutopilotPkt_t *pPkt, const FrequencySweepCmd_t *pCmd)
Form a packet commanding a frequency sweep manuever.
UInt8 DecodeRawVibrationPacket (const AutopilotPkt_t *pPkt, UInt16 *pSampleIndex, UInt16 Data[64], UInt16 *pOffset, float *pGain)
Decode a raw vibration packet.
BOOL DecodeExternalIOSamplePacket (const AutopilotPkt_t *pPkt, UInt32 Sample[NUM_EXTERNAL_IO_PINS])
Extract the data from an external IO sample packet.
BOOL DecodeExternalADCSamplePacket (const AutopilotPkt_t *pPkt, float Sample[NUM_EXTERNAL_ADC_PINS])
Extract the data from a payload analog input samples packet.
BOOL DecodeResetReportPacket (const AutopilotPkt_t *pPkt, UInt16 *pRSR, UInt16 *pVec, UInt32 *pPC, UInt32 *pMSR, UInt32 *pLink, UInt32 *pFPSCR)
Extract the data from a reset report packet.
BOOL DecodeSystemVersionPacket (const AutopilotPkt_t *pPkt, Version_t *pVersion, Board_t *pBoard)
Extract the data from a system version packet.
void FormActuatorTestPacket (AutopilotPkt_t *pPkt, float Angle, float Width, float Freq, float Dev, UInt8 Index)
Form an actuator test command packet.
void FormSetFuelLevelPacket (AutopilotPkt_t *pPkt, float Fuel, BOOL Electric)
Form a set fuel level packet.
void FormSetFuelIfLockedPacket (AutopilotPkt_t *pPkt, float Fuel, BOOL Electric)
Form a packet to set the fuel level even if the autopilot is locked.
BOOL DecodeMovingBaseStatusPacket (const AutopilotPkt_t *pPkt, MovingBaseStatus_t *pStatus)
Extract the data from a moving base status packet.
const char * DecodeUserWarningPacket (AutopilotPkt_t *pPkt, UInt8 *pType, UInt8 *pCode)
Extract the data from a user warning packet.
void FormFeatureCodePacket (AutopilotPkt_t *pPkt, const UInt8 Data[8])
Form feature code packet.
void FormTerrainElevationDataPacket (AutopilotPkt_t *pPkt, UInt32 Time, const float Elevations[6])
Elevation data for uplink to the avionics.
void FormMissionSettingsPacket (AutopilotPkt_t *pPkt, SInt16 MinAltitude, SInt16 MaxAltitude, UInt32 FlightTimeout)
Form the mission settings packet.
void FormBoundaryPacket (AutopilotPkt_t *pPkt, const Boundary_t *pBnd)
Form the airspace boundary packet.
BOOL DecodeBoundaryPacket (const AutopilotPkt_t *pPkt, Boundary_t *pBnd)
Decode the airspace boundary packet.
void FormConfigurationLockPacket (AutopilotPkt_t *pPkt, const char Password[32])
Form a configuration lock packet.
void FormConfigurationUnlockPacket (AutopilotPkt_t *pPkt, const char Password[32], BOOL Silent)
Form a configuration unlock packet.
BOOL DecodeTransponderStatusPacket (const AutopilotPkt_t *pPkt, XPDRStatus_t *pStatus)
Decode the transponder status packet.
UInt32 DecodeServoTelemetryPacket (const AutopilotPkt_t *pPkt, ServoTelemetry_t ServoTel[NUM_ACTUATORS])
Decode the servo telemetry packet.
Detailed Description
Autopilot packet utilities used on the ground.
This module provides packet creation and decoding functions for autopilot stream packets that are specific to ground systems as documented in "Piccolo Communications".
Function Documentation
BOOL DecodeBoundaryPacket (const AutopilotPkt_t * pPkt, Boundary_t * pBnd)
Decode the airspace boundary packet.
Decode the airspace boundary packet.
Parameters
pPkt is the packet to decode.
pBnd receives the airspace boundary data.
References BOUNDARY, SimplePkt_t::Data, DataToSInt16(), DataToSInt32(), Boundary_t::East, Boundary_t::lat, Boundary_t::lon, Boundary_t::N, Boundary_t::North, NUM_BOUNDARY, SimplePkt_t::PktType, and SimplePkt_t::Size.
const char* DecodeDeviceDetails (AutopilotPkt_t * pPkt, UInt8 * pIndex, UInt8 * pDevice, BOOL * pComplete)
Decode device details packet.
Decode device details packet.
Parameters
pPkt is the radio to decode.
pIndex receives the packet order index.
pDevice is the device enumerator, reserved (0), internal radio (1), ublox GPS (2), Novatel (3)
pComplete will be TRUE if this is the last radio details packet in the report, else FALSE if more packets are coming.
Returns
a pointer to the null-terminated radio details string in this packet, or NULL if there was a problem with the packet, in which case pComplete will be FALSE.
References SimplePkt_t::Data, DEVICE_DETAILS, MAX_SIMPLE_DATA, SimplePkt_t::PktType, and SimplePkt_t::Size.
BOOL DecodeECUStatusPacket (const AutopilotPkt_t * pPkt, ECU_t * pECU)
Decode an ECU status packet.
Decode a ECU status packet.
Parameters
pPkt points to a autopilot packet to receive the formatted data.
pECU receives the data.
Returns
TRUE if the packet is valid, else FALSE.
References ECU_t::AFR, ECUFlags_t::AFRandComp_included, ECU_t::AFRcomp, ECU_t::CHT_A, ECUFlags_t::CHT_A_included, ECU_t::CHT_B, ECUFlags_t::CHT_B_included, SimplePkt_t::Data, DataToSInt16(), DataToUInt16(), DataToUInt32(), ECU_STATUS, ECUFlags_t::ECU_volt_included, ECU_t::EGT_A, ECUFlags_t::EGT_A_included, ECU_t::EGT_B, ECUFlags_t::EGT_B_included, ECU_t::EngineTime, ECUFlags_t::EngineTime_included, ECU_t::ErrorBits, ECUFlags_t::ErrorBits_A_included, ECUFlags_t::ErrorBits_B_included, ECU_t::Flags, ECU_t::FuelPress, ECUFlags_t::FuelPress_included, ECU_t::IAT, ECUFlags_t::IAT_included, ECU_t::InjectAngle, ECUFlags_t::InjectAngle_included, ECU_t::InjectTime, ECUFlags_t::InjectTime_included, ECUFlags_t::IsRight, ECU_t::MAP, ECUFlags_t::MAP_included, ECUFlags_t::Mode, SimplePkt_t::PktType, ECUFlags_t::Reserved, ECU_t::SerialNum, ECUFlags_t::SerialNumber_included, SimplePkt_t::Size, ECU_t::TPS, ECUFlags_t::TPS_included, ECUFlags_t::Vendor, and ECU_t::Volts.
BOOL DecodeExternalADCSamplePacket (const AutopilotPkt_t * pPkt, float Sample[NUM_EXTERNAL_ADC_PINS])
Extract the data from a payload analog input samples packet.
Decode a external analog sample packet which contains the analog sample data for all the payload analog pins.
Parameters
pPkt points to a autopilot packet containing the data.
Sample is an array to receive the input samples.
Returns
TRUE if the packet is valid, else FALSE.
References SimplePkt_t::Data, DataToFloat(), EXTERNAL_ADC_SAMPLE, NUM_EXTERNAL_ADC_PINS, SimplePkt_t::PktType, and SimplePkt_t::Size.
BOOL DecodeExternalIOSamplePacket (const AutopilotPkt_t * pPkt, UInt32 Sample[NUM_EXTERNAL_IO_PINS])
Extract the data from an external IO sample packet.
Referenced by FormActuatorTestPacket().
BOOL DecodeGPSHealth (const AutopilotPkt_t * pPkt, GPSUser_t * pGPS, UInt8 * pIndex, UInt8 * pNum)
Decode GPS health information for a single GPS.
Decode GPS health information for a single GPS.
Parameters
pPkt contains the data to decode.
pGPS receives the GPS health information.
pIndex is the index of this GPS.
pNum is the number of GPSs being reported on.
References GPSUser_t::Accuracy, GPSUser_t::Altitude, SatStatus_t::Azimuth, SimplePkt_t::Data, DataToSInt16(), DataToSInt32(), DataToUInt16(), DataToUInt24(), DGPS_FIX, GPSUser_t::Direction, SatStatus_t::Elevation, FIX3D, FIXEDHEIGHT_PVTYPE, FIXEDPOS_PVTYPE, SatStatus_t::Geometry, GPS_HEALTH, GPSUser_t::GPSType, IONOFREE_FLOAT_PVTYPE, L1_FLOAT_PVTYPE, L1_INTEGER_PVTYPE, SatStatus_t::L1CNo, SatStatus_t::L1TimeOfLock, SatStatus_t::L2CNo, SatStatus_t::L2TimeOfLock, GPSUser_t::Latitude, LLAandNEDtoECEF(), GPSUser_t::Longitude, NARROW_FLOAT_PVTYPE, NARROW_INTEGER_PVTYPE, NO_SATS, NONE_PVTYPE, NUM_SATS, OMNISTAR_HP_PVTYPE, OMNISTAR_VBS_PVTYPE, OMNISTAR_XP_PVTYPE, GPSUser_t::PDOP, SimplePkt_t::PktType, POS_LOCK, GPSUser_t::PosECEF, PROPAGATED_PVTYPE, PSRDIFF_PVTYPE, GPSUser_t::Sat, SBAS_FIX, SBAS_PVTYPE, SINGLE_PVTYPE, SimplePkt_t::Size, GPSUser_t::SolnType, GPSUser_t::Speed, GPSUser_t::Status, SatStatus_t::SVID, GPSUser_t::TrackedSats, SatStatus_t::Used, GPSUser_t::UsedInINS, GPSUser_t::VDown, GPSUser_t::VEast, GPSUser_t::VelECEF, GPSUser_t::VisibleSats, and GPSUser_t::VNorth.
UInt32 DecodeHighSpeedDoubletDataPacket (const AutopilotPkt_t * pPkt, UInt16 * pSampleIndex, UInt16 * pSampleRate, UInt16 * pTotalSamples, HighSpeedDoubletData_t Data[10])
Decode a high speed doublet data packet.
Deocde a packet containing up to ten samples of high speed doublet data.
Parameters
pPkt points to an autopilot packet containing data to be decoded
pSampleIndex points to space to receive the sample index, which gives the starting index for data in this packet.
pSampleRate points to space to receive the sample rate, in samples per second, of the data in this packet. Together with the SampleIndex this allows the caller to determine where in doublet time this data are located.
pTotalSamples points to space to receive the total number of samples in the series of doublet downlink packets.
pData points to space to receive up to ten samples of data.
Returns
The number of samples contained in this packet, which may be less than ten. Zero if the packet is bad.
References HighSpeedDoubletData_t::Accel, SimplePkt_t::Data, DataToSInt16(), DataToUInt16(), DOUBLET_SENSOR_DATA, HighSpeedDoubletData_t::Gyro, NAXIS, NUM_EXTERNAL_ADC_PINS, HighSpeedDoubletData_t::Pdynamic, SimplePkt_t::PktType, HighSpeedDoubletData_t::Pstatic, and SimplePkt_t::Size.
BOOL DecodeLegacySystemStatusHiResPacket (const AutopilotPkt_t * pPkt, SystemDiagnostic_t * pSystem, NavDiagnostic_t * pNav, AutopilotStatus_t * pStatus, BOOL * pLong)
Decode a legacy high resolution system status packet.
Interpret a legacy autopilot high resolution status packet, which gives the status of the loops, actions, and flight termination data.
Parameters
pPkt points to a autopilot packet containing data to decode.
pSystem points to space to receive the system diagnostics.
pNav points to space to receive the navigation diagnostics.
pStatus points to space to receive the autopiot status.
pLong will be set to TRUE if track and loop target data are included in the packet
Returns
TRUE if the packet is valid, else FALSE.
References GenericActionBits_t::Action0, GenericActionBits_t::Action1, GenericActionBits_t::Action2, GenericActionBits_t::Action3, GenericActionBits_t::Action4, GenericActionBits_t::Action5, GenericActionBits_t::Action6, GenericActionBits_t::Action7, AutopilotStatus_t::ActionsDefined, AutopilotStatus_t::ActionStates, ActionBits_t::AeroTermination, Waypoint_t::Alt, AutopilotStatus_t::AssistMode, ActionBits_t::Brakes, AutopilotStatus_t::ConType, AutopilotStatus_t::ConVersion, SystemDiagnostic_t::CPULoad, SimplePkt_t::Data, DataToFloat(), DataToSInt32(), DataToUInt16(), DataToUInt24(), ActionBits_t::Drop, AutopilotStatus_t::ElapsedTime, ActionBits_t::EngineKill, AutopilotStatus_t::FlightTime, Float16ToFloat(), Waypoint_t::Lat, ActionBits_t::LaunchAction1, ActionBits_t::LaunchAction2, LEGACY_SYSTEM_STATUS_HI_RES, ActionBits_t::Lights, Waypoint_t::Lon, AutopilotStatus_t::LoopTargets, AutopilotStatus_t::MaxLimits, AutopilotStatus_t::MinLimits, AutopilotStatus_t::NumLoops, ActionBits_t::Parachute, AutopilotStatus_t::PilotPercentage, AutopilotStatus_t::PilotRate, SimplePkt_t::PktType, SimplePkt_t::Size, AutopilotStatus_t::SurfaceTestTime, SystemDiagnostic_t::UplinkRatio, ActionBits_t::User, AutopilotStatus_t::Waypoint1, AutopilotStatus_t::Waypoint1AGL, AutopilotStatus_t::Waypoint2, AutopilotStatus_t::Waypoint2AGL, AutopilotStatus_t::WaypointFrom, and AutopilotStatus_t::WaypointTo.
BOOL DecodeLegacySystemStatusLoResPacket (const AutopilotPkt_t * pPkt, SystemDiagnostic_t * pSystem, NavDiagnostic_t * pNav, AutopilotStatus_t * pStatus, BOOL * pLong)
Decode a legacy low resolution system status packet.
Interpret a legacy autopilot low resolution status packet, which gives the status of the loops, actions, and flight termination data.
Parameters
pPkt points to a autopilot packet containing data to decode.
pSystem points to space to receive the system diagnostics.
pNav points to space to receive the navigation diagnostics.
pStatus points to space to receive the autopiot status.
pLong will be set to TRUE if track and loop target data are included in the packet
Returns
TRUE if the packet is valid, else FALSE.
References NavStatus_t::AccBiasGood, NavDiagnostic_t::AccelBias, GenericActionBits_t::Action0, GenericActionBits_t::Action1, GenericActionBits_t::Action2, GenericActionBits_t::Action3, GenericActionBits_t::Action4, GenericActionBits_t::Action5, GenericActionBits_t::Action6, GenericActionBits_t::Action7, AutopilotStatus_t::ActionsDefined, AutopilotStatus_t::ActionStates, ActionBits_t::AeroTermination, NavStatus_t::AGLGood, DataSource_t::AGLInRange, DataSource_t::AGLInstalled, DataSource_t::AirDataExternal, Waypoint_t::Alt, DataSource_t::AltControlType, AutopilotStatus_t::APMode, AutopilotStatus_t::AssistMode, NavStatus_t::AttitudeGood, AutopilotStatus_t::AutoEngineKill, AutopilotStatus_t::AutoFlareDisable, NavStatus_t::BaroGood, SystemDiagnostic_t::BoardTemp, AutopilotStatus_t::BoundaryIsViolated, ActionBits_t::Brakes, AutopilotStatus_t::CommTimeout, AutopilotStatus_t::ConfigLock, AutopilotStatus_t::ConType, AutopilotStatus_t::ConVersion, SystemDiagnostic_t::CPULoad, SystemDiagnostic_t::CPUVoltageBIT, SimplePkt_t::Data, DataToUInt16(), DataToUInt24(), AutopilotStatus_t::Deadman, ActionBits_t::Drop, AutopilotStatus_t::ElapsedTime, ActionBits_t::EngineKill, AutopilotStatus_t::ETA, SystemDiagnostic_t::FirstStageBIT, SystemDiagnostic_t::FiveAnalogBIT, SystemDiagnostic_t::FiveDigitalBIT, AutopilotStatus_t::FlightTermination, AutopilotStatus_t::FlightTime, AutopilotStatus_t::FlightTimerElapsed, Float16ToFloat(), NavDiagnostic_t::GeoidUndulation, AutopilotStatus_t::GlobalOn, DataSource_t::GPSExternal, AutopilotStatus_t::GPSTimeout, SystemDiagnostic_t::GPSVoltageBIT, NavDiagnostic_t::GyroBias, NavStatus_t::GyroBiasGood, NavStatus_t::HeadingGood, NavDiagnostic_t::HortSigma_m, DataSource_t::IMUExternal, SystemDiagnostic_t::InputCurrent, SystemDiagnostic_t::InputVoltage, Waypoint_t::Lat, ActionBits_t::LaunchAction1, ActionBits_t::LaunchAction2, ActionBits_t::LaunchAction3, ActionBits_t::LaunchAction4, LEGACY_SYSTEM_STATUS_LO_RES, ActionBits_t::Lights, Waypoint_t::Lon, AutopilotStatus_t::LoopStatus0, AutopilotStatus_t::LoopStatus1, AutopilotStatus_t::LoopStatus2, AutopilotStatus_t::LoopStatus3, AutopilotStatus_t::LoopStatus4, AutopilotStatus_t::LoopStatus5, AutopilotStatus_t::LoopStatus6, AutopilotStatus_t::LoopStatus7, AutopilotStatus_t::LoopTargets, AutopilotStatus_t::LoopTelemMax0, AutopilotStatus_t::LoopTelemMax1, AutopilotStatus_t::LoopTelemMax2, AutopilotStatus_t::LoopTelemMax3, AutopilotStatus_t::LoopTelemMax4, AutopilotStatus_t::LoopTelemMax5, AutopilotStatus_t::LoopTelemMax6, AutopilotStatus_t::LoopTelemMax7, AutopilotStatus_t::LoopTelemMin0, AutopilotStatus_t::LoopTelemMin1, AutopilotStatus_t::LoopTelemMin2, AutopilotStatus_t::LoopTelemMin3, AutopilotStatus_t::LoopTelemMin4, AutopilotStatus_t::LoopTelemMin5, AutopilotStatus_t::LoopTelemMin6, AutopilotStatus_t::LoopTelemMin7, NavDiagnostic_t::MagBias, NavStatus_t::MagBiasGood, NavStatus_t::MagGood, DataSource_t::MagInstalled, AutopilotStatus_t::ManualEngineKill, AutopilotStatus_t::MaxLimits, AutopilotStatus_t::MinLimits, NavStatus_t::Mode, N3D, NavDiagnostic_t::NavStatus, NavDiagnostic_t::NovStatus, AutopilotStatus_t::NumLoops, AutopilotStatus_t::OperatorEngineKill, AutopilotStatus_t::Orbit, AutopilotStatus_t::OrbitRadius, ActionBits_t::Parachute, AutopilotStatus_t::ParachutePendingRPM, AutopilotStatus_t::PilotPercentage, AutopilotStatus_t::PilotRate, SimplePkt_t::PktType, NavStatus_t::PositionGood, SystemDiagnostic_t::RadioVoltageBIT, SystemDiagnostic_t::RSSI, SystemDiagnostic_t::ServoCurrent, SystemDiagnostic_t::ServoVoltage, SimplePkt_t::Size, NovatelStatus_t::SolnType, NavDiagnostic_t::Source, AutopilotStatus_t::SurfaceTestIndex, AutopilotStatus_t::SurfaceTestTime, NavStatus_t::TASGood, SystemDiagnostic_t::TempDisagreeBIT, AutopilotStatus_t::TrackerStatus, ActionBits_t::User, NavStatus_t::VelocityGood, NavDiagnostic_t::VertSigma_m, SystemDiagnostic_t::VSWR, AutopilotStatus_t::Waypoint1, AutopilotStatus_t::Waypoint2, AutopilotStatus_t::WaypointFrom, AutopilotStatus_t::WaypointTo, and NavStatus_t::WindGood.
UInt32 DecodeLowSpeedDoubletDataPacket (const AutopilotPkt_t * pPkt, UInt16 * pSampleIndex, UInt16 * pSampleRate, UInt16 * pTotalSamples, LowSpeedDoubletData_t Data[10])
Decode a low speed doublet data packet.
Deocde a packet containing up to ten samples of low speed autopilot doublet data.
Parameters
pPkt points to an autopilot packet containing data to be decoded
pSampleIndex points to space to receive the sample index, which gives the starting index for data in this packet.
pSampleRate points to space to receive the sample rate, in samples per second, of the data in this packet. Together with the SampleIndex this allows the caller to determine where in doublet time this data are located.
pTotalSamples points to space to receive the total number of samples in the series of doublet downlink packets.
pData points to space to receive up to ten samples of data.
Returns
The number of samples contained in this packet, which may be less than ten. Zero if the packet is bad.
References LowSpeedDoubletData_t::Controls, SimplePkt_t::Data, DataToSInt16(), DataToUInt16(), DOUBLET_AP_DATA, LowSpeedDoubletData_t::Euler, LowSpeedDoubletData_t::LeftRPM, NAXIS, NUM_CONTROL_AXIS, SimplePkt_t::PktType, LowSpeedDoubletData_t::RightRPM, and SimplePkt_t::Size.
BOOL DecodeMovingBaseStatusPacket (const AutopilotPkt_t * pPkt, MovingBaseStatus_t * pStatus)
Extract the data from a moving base status packet.
Decode a moving baseline status packet.
Parameters
pPkt points to a autopilot packet containing the data.
pStatus recevies the decoded data.
Returns
TRUE if the packet is valid, else FALSE.
References ALT, MovingBaseStatus_t::Baseline, MovingBaseStatus_t::BelowTrack, MovingBaseStatus_t::CrossTrack, SimplePkt_t::Data, DataToSInt16(), DataToSInt32(), DataToUInt16(), DataToUInt24(), DataToUInt32(), MovingBaseStatus_t::Error, MovingBaseStatus_t::ETA, Float16ToFloat(), MovingBaseStatus_t::Heading, MovingBaseStatus_t::IsPPS, MovingBaseStatus_t::Lag, LAT, LON, MOVING_BASELINE_STATUS, N3D, MovingBaseStatus_t::NumSats, SimplePkt_t::PktType, MovingBaseStatus_t::RightHand, SimplePkt_t::Size, MovingBaseStatus_t::SolnType, MovingBaseStatus_t::State, MovingBaseStatus_t::SystemTime, and MovingBaseStatus_t::TDPos.
UInt8 DecodeRawVibrationPacket (const AutopilotPkt_t * pPkt, UInt16 * pSampleIndex, UInt16 Data[64], UInt16 * pOffset, float * pGain)
Decode a raw vibration packet.
decode a autopilot raw vibration data packet. The raw vibration data packet contains 64 samples of raw sensor data sampled at high right.
Parameters
pPkt points to a autopilot packet containing the data to be decoded.
pSampleIndex points to space to receive the sample index, which which identifies where in the buffer of 1024 samples this data belong.
Data points to space to receive the samples.
pOffset points to space to receive the offset in counts of the data.
pGain points to space to receive the gain, in engineering units per count, of the data.
Returns
The index of sensor data contained in this packet, or 255 if the packet is bad.
References SimplePkt_t::Data, DataToUInt16(), Float16ToFloat(), SimplePkt_t::PktType, RAW_VIBRATION_DATA, and SimplePkt_t::Size.
BOOL DecodeResetReportPacket (const AutopilotPkt_t * pPkt, UInt16 * pRSR, UInt16 * pVec, UInt32 * pPC, UInt32 * pMSR, UInt32 * pLink, UInt32 * pFPSCR)
Extract the data from a reset report packet.
Extract the data from a reset report packet
Parameters
pPkt points to a packet containing the data.
pSRS points to space receive the contents of the reset status register.
pVec points to space to receive the exception vector (if any).
pPC points to space to receive the exception program counter (if any).
pMSR points to space to receive the exception machine state register (if any).
pLink points to space to receive the link register (if any).
pFPSCR points to space to receive the floating point status and control register (if any).
TRUE if the packet is valid, else FALSE.
References SimplePkt_t::Data, DataToUInt16(), DataToUInt32(), SimplePkt_t::PktType, RESET_REPORT, and SimplePkt_t::Size.
BOOL DecodeSensorErrorPacket (const AutopilotPkt_t * pPkt, SensorErrorData_t * pSensorError)
Decode a sensor error packet.
Extract the data from a sensor error packet
Parameters
pPkt points to a packet containing the data.
pSensorError receives the new sensor data.
Returns
TRUE if the packet is valid, else FALSE.
References SensorErrorData_t::AGLOffset, SensorErrorData_t::AllowControllerTAS, SimplePkt_t::Data, DataToSInt16(), SensorErrorData_t::DisableAlign, SensorErrorData_t::DisableAlt, SensorErrorData_t::DisableInternalMag, SensorErrorData_t::DisableSBAS, SensorErrorData_t::DisableVDown, SensorErrorData_t::MagOnlyInAHRS, SensorErrorData_t::OATfromStandardAtmo, SimplePkt_t::PktType, SensorErrorData_t::PositionCorr, SENSOR_ERROR, SimplePkt_t::Size, SensorErrorData_t::TASCutoff, SensorErrorData_t::TASFilterWindow, and SensorErrorData_t::TempRise.
UInt32 DecodeServoTelemetryPacket (const AutopilotPkt_t * pPkt, ServoTelemetry_t ServoTel[NUM_ACTUATORS])
Decode the servo telemetry packet.
Decode the servo telemetry packet.
Parameters
pPkt points to the autopilot packet that contains servo telemetry data.
ServoTel is an array containing telemetry data for each servo.
Returns
The number of elements returned in the telemetry data array.
References SimplePkt_t::Data, DataToSInt16(), DataToUInt16(), and SimplePkt_t::Size.
BOOL DecodeSystemStatusPacket (const AutopilotPkt_t * pPkt, SystemDiagnostic_t * pSystem, NavDiagnostic_t * pNav, AutopilotStatus_t * pStatus, BOOL * pLong)
Decode a system status packet.
Decode a autopilot status packet, either short or long
Parameters
pPkt points to a autopilot packet containing data to decode.
pSystem points to space to receive the data.
pNav points to space to receive the data.
pStatus points to space to receive the data.
pLong is set TRUE if the packet is long format.
Returns
The number of bytes decoded, or zero if the packet is bad.
References NavStatus_t::AccBiasGood, NavDiagnostic_t::AccelBias, GenericActionBits_t::Action0, GenericActionBits_t::Action1, GenericActionBits_t::Action2, GenericActionBits_t::Action3, GenericActionBits_t::Action4, GenericActionBits_t::Action5, GenericActionBits_t::Action6, GenericActionBits_t::Action7, AutopilotStatus_t::ActionsDefined, AutopilotStatus_t::ActionStates, ActionBits_t::AeroTermination, NavStatus_t::AGLGood, AutopilotStatus_t::AGLGood, DataSource_t::AGLInRange, DataSource_t::AGLInstalled, DataSource_t::AirDataExternal, DataSource_t::AirspeedSource, Waypoint_t::Alt, DataSource_t::AltControlType, AutopilotStatus_t::APMode, AutopilotStatus_t::AssistMode, NavStatus_t::AttitudeGood, AutopilotStatus_t::AutoEngineKill, AutopilotStatus_t::AutoFlareDisable, NavStatus_t::BaroGood, SystemDiagnostic_t::BoardTemp, AutopilotStatus_t::BoundaryIsViolated, ActionBits_t::Brakes, AutopilotStatus_t::CommTimeout, AutopilotStatus_t::ConfigLock, AutopilotStatus_t::ConType, AutopilotStatus_t::ConVersion, SystemDiagnostic_t::CPULoad, SystemDiagnostic_t::CPUVoltageBIT, SimplePkt_t::Data, DataToFloat(), DataToSInt16(), DataToSInt32(), DataToUInt16(), DataToUInt24(), AutopilotStatus_t::Deadman, ActionBits_t::Drop, AutopilotStatus_t::ElapsedTime, ActionBits_t::EngineKill, AutopilotStatus_t::ETA, SystemDiagnostic_t::FirstStageBIT, SystemDiagnostic_t::FiveAnalogBIT, SystemDiagnostic_t::FiveDigitalBIT, AutopilotStatus_t::FlightTermination, AutopilotStatus_t::FlightTime, AutopilotStatus_t::FlightTimerElapsed, Float16ToFloat(), NavDiagnostic_t::GeoidUndulation, AutopilotStatus_t::GlobalOn, DataSource_t::GPSExternal, AutopilotStatus_t::GPSTimeout, SystemDiagnostic_t::GPSVoltageBIT, NavDiagnostic_t::GyroBias, NavStatus_t::GyroBiasGood, NavStatus_t::HeadingGood, NavDiagnostic_t::HortSigma_m, DataSource_t::IMUExternal, SystemDiagnostic_t::InputCurrent, SystemDiagnostic_t::InputVoltage, Waypoint_t::Lat, ActionBits_t::LaunchAction1, ActionBits_t::LaunchAction2, ActionBits_t::LaunchAction3, ActionBits_t::LaunchAction4, ActionBits_t::Lights, Waypoint_t::Lon, AutopilotStatus_t::LoopStatus0, AutopilotStatus_t::LoopStatus1, AutopilotStatus_t::LoopStatus2, AutopilotStatus_t::LoopStatus3, AutopilotStatus_t::LoopStatus4, AutopilotStatus_t::LoopStatus5, AutopilotStatus_t::LoopStatus6, AutopilotStatus_t::LoopStatus7, AutopilotStatus_t::LoopTargets, AutopilotStatus_t::LoopTelemMax0, AutopilotStatus_t::LoopTelemMax1, AutopilotStatus_t::LoopTelemMax2, AutopilotStatus_t::LoopTelemMax3, AutopilotStatus_t::LoopTelemMax4, AutopilotStatus_t::LoopTelemMax5, AutopilotStatus_t::LoopTelemMax6, AutopilotStatus_t::LoopTelemMax7, AutopilotStatus_t::LoopTelemMin0, AutopilotStatus_t::LoopTelemMin1, AutopilotStatus_t::LoopTelemMin2, AutopilotStatus_t::LoopTelemMin3, AutopilotStatus_t::LoopTelemMin4, AutopilotStatus_t::LoopTelemMin5, AutopilotStatus_t::LoopTelemMin6, AutopilotStatus_t::LoopTelemMin7, NavStatus_t::MagBiasGood, NavStatus_t::MagGood, DataSource_t::MagInstalled, AutopilotStatus_t::ManualEngineKill, AutopilotStatus_t::MaxLimits, AutopilotStatus_t::MaxWaypt1000, AutopilotStatus_t::MinLimits, NavStatus_t::Mode, N3D, NavDiagnostic_t::NavStatus, SystemDiagnostic_t::NoInternalGPS, NavDiagnostic_t::NovStatus, AutopilotStatus_t::NumLoops, AutopilotStatus_t::OperatorEngineKill, AutopilotStatus_t::Orbit, AutopilotStatus_t::OrbitRadius, ActionBits_t::Parachute, AutopilotStatus_t::ParachutePendingRPM, AutopilotStatus_t::PilotPercentage, AutopilotStatus_t::PilotRate, SimplePkt_t::PktType, NavStatus_t::PositionGood, SystemDiagnostic_t::PrimaryAirDataReversed, SystemDiagnostic_t::PrimaryIMUBIT, SystemDiagnostic_t::PrimaryPdynamicBIT, SystemDiagnostic_t::PrimaryPstaticBIT, SystemDiagnostic_t::RadioVoltageBIT, SystemDiagnostic_t::RSSI, SystemDiagnostic_t::SecondaryAirDataReversed, SystemDiagnostic_t::SecondaryIMUBIT, SystemDiagnostic_t::SecondaryPdynamicBIT, SystemDiagnostic_t::SecondaryPstaticBIT, SystemDiagnostic_t::ServoCurrent, SystemDiagnostic_t::ServoVoltage, SimplePkt_t::Size, NovatelStatus_t::SolnType, NavDiagnostic_t::Source, AutopilotStatus_t::SurfaceTestIndex, AutopilotStatus_t::SurfaceTestTime, SYSTEM_STATUS, NavStatus_t::TASGood, SystemDiagnostic_t::TempBIT, SystemDiagnostic_t::TempDisagreeBIT, SystemDiagnostic_t::TertiaryAirDataReversed, SystemDiagnostic_t::TertiaryIMUBIT, SystemDiagnostic_t::TertiaryPdynamicBIT, SystemDiagnostic_t::TertiaryPstaticBIT, AutopilotStatus_t::TrackerStatus, SystemDiagnostic_t::UplinkRatio, ActionBits_t::User, NavStatus_t::VelocityGood, NavDiagnostic_t::VertSigma_m, SystemDiagnostic_t::VSWR, AutopilotStatus_t::Waypoint1, AutopilotStatus_t::Waypoint1AGL, AutopilotStatus_t::Waypoint2, AutopilotStatus_t::Waypoint2AGL, AutopilotStatus_t::WaypointFrom, AutopilotStatus_t::WaypointTo, and NavStatus_t::WindGood.
BOOL DecodeSystemVersionPacket (const AutopilotPkt_t * pPkt, Version_t * pVersion, Board_t * pBoard)
Extract the data from a system version packet.
Decode a autopilot system version packet. This packet contains hardware firmware version numbers.
Parameters
pPkt points to a autopilot packet to be decoded.
pVersion points to space to receive the firmware version information. If NULL the version information is not decoded.
pBoard points to space to receive the hardware version information. If NULL the version information is not decoded.
Returns
TRUE If packet is valid, else FALSE.
References Board_t::BoardSN, Board_t::Config, SimplePkt_t::Data, DataToUInt16(), DataToUInt32(), Version_t::Date, Board_t::Date, Date_t::day, Version_t::Description, Board_t::FeatureCode, Version_t::MajorVersion, Version_t::MinorVersion, Date_t::month, Version_t::PatchNum, SimplePkt_t::PktType, Board_t::ProductSN, Version_t::Released, Board_t::Rev, Version_t::Revision, SimplePkt_t::Size, Version_t::SubVersion, SYSTEM_VERSION, and Date_t::year.
BOOL DecodeTelemetryHiResPacket (const AutopilotPkt_t * pPkt, UserData_t * pData)
Decode a high resolution telemetry packet.
Decode a high resolution autopilot telemetry data packet.
Parameters
pPkt points to a autopilot packet to receive the formatted data.
pData receives the data.
Returns
TRUE if the packet is valid, else FALSE.
References UserData_t::Accel, UserData_t::Actuators, UserData_t::AGL, AvailableData_t::AGL, AvailableData_t::AGLfromsensor, TelemLimits_t::AGLLow, UserData_t::AlignHeading, AvailableData_t::AlignHeading, UserData_t::AlignHeadingSigma, UserData_t::AlignSolnType, UserData_t::AlignTrackedSats, UserData_t::AlignVisibleSats, GPSUser_t::Altitude, TelemLimits_t::AltitudeHigh, TelemLimits_t::AltitudeLow, TelemLimits_t::AltMaskedByState, UserData_t::AltUsed, AvailableData_t::AltUsed, UserData_t::AvailableData, UserData_t::BaroAlt, AvailableData_t::CalSensor, SimplePkt_t::Data, DataToSInt16(), DataToSInt32(), DataToUInt16(), DataToUInt24(), DataToUInt32(), GPSUser_t::day, UserData_t::Density, GPSUser_t::Direction, UserData_t::Electric, UserData_t::Euler, Float16ToFloat(), UserData_t::Fuel, AvailableData_t::Fuel, UserData_t::FuelFlow, UserData_t::GPS, AvailableData_t::GPS, gps_to_ymdhms(), AvailableData_t::GPSResiduals, UserData_t::GroundContact, UserData_t::Gyro, GPSUser_t::hours, UserData_t::IAS, TelemLimits_t::IASHigh, TelemLimits_t::IASLow, TelemLimits_t::IASMaskedByState, GPSUser_t::ITOW, GPSUser_t::Latitude, UserData_t::LeftRPM, UserData_t::Limits, LLAandNEDtoECEF(), GPSUser_t::Longitude, UserData_t::MagField, UserData_t::MagHeading, AvailableData_t::Magnetometer, GPSUser_t::minutes, GPSUser_t::month, N3D, NUM_ACTUATORS, AvailableData_t::NumActuators, UserData_t::OAT, GPSUser_t::PDOP, UserData_t::Pdynamic, PITCH_AXIS, TelemLimits_t::PitchHigh, SimplePkt_t::PktType, GPSUser_t::PosECEF, UserData_t::PRes, UserData_t::Pstatic, AvailableData_t::RawSensor, UserData_t::RightRPM, ROLL_AXIS, TelemLimits_t::RollHigh, TelemLimits_t::RPMHigh, TelemLimits_t::RPMLow, TelemLimits_t::RPMMaskedByState, GPSUser_t::seconds, SimplePkt_t::Size, GPSUser_t::SolnType, GPSUser_t::Speed, GPSUser_t::Status, UserData_t::SystemTime, UserData_t::TAS, TELEMETRY_HI_RES, TelemLimits_t::TerMaskedByState, GPSUser_t::TrackedSats, GPSUser_t::VDown, GPSUser_t::VEast, GPSUser_t::VelECEF, GPSUser_t::VisibleSats, GPSUser_t::VNorth, UserData_t::VRes, GPSUser_t::Week, UserData_t::WeightOnWheel, TelemLimits_t::WindsHigh, UserData_t::WindSouth, UserData_t::WindWest, YAW_AXIS, and GPSUser_t::year.
BOOL DecodeTelemetryLoResPacket (const AutopilotPkt_t * pPkt, UserData_t * pData)
Decode a low resolution telemetry packet.
Decode a low resolution autopilot telemetry data packet.
Parameters
pPkt points to a autopilot packet to receive the formatted data.
pData receives the data.
Returns
TRUE if the packet is valid, else FALSE.
References UserData_t::Accel, UserData_t::Actuators, UserData_t::AGL, AvailableData_t::AGL, AvailableData_t::AGLfromsensor, TelemLimits_t::AGLLow, UserData_t::AlignHeading, AvailableData_t::AlignHeading, UserData_t::AlignHeadingSigma, UserData_t::AlignSolnType, UserData_t::AlignTrackedSats, UserData_t::AlignVisibleSats, GPSUser_t::Altitude, TelemLimits_t::AltitudeHigh, TelemLimits_t::AltitudeLow, TelemLimits_t::AltMaskedByState, UserData_t::AltUsed, AvailableData_t::AltUsed, UserData_t::AvailableData, UserData_t::BaroAlt, AvailableData_t::CalSensor, SimplePkt_t::Data, DataToUInt16(), DataToUInt24(), DataToUInt32(), GPSUser_t::day, UserData_t::Density, GPSUser_t::Direction, UserData_t::Electric, UserData_t::Euler, Float16ToFloat(), UserData_t::Fuel, AvailableData_t::Fuel, UserData_t::FuelFlow, UserData_t::GPS, AvailableData_t::GPS, gps_to_ymdhms(), AvailableData_t::GPSResiduals, UserData_t::GroundContact, UserData_t::Gyro, GPSUser_t::hours, UserData_t::IAS, TelemLimits_t::IASHigh, TelemLimits_t::IASLow, TelemLimits_t::IASMaskedByState, GPSUser_t::ITOW, GPSUser_t::Latitude, UserData_t::LeftRPM, UserData_t::Limits, GPSUser_t::Longitude, UserData_t::MagField, UserData_t::MagHeading, AvailableData_t::Magnetometer, GPSUser_t::minutes, GPSUser_t::month, N3D, NUM_ACTUATORS, AvailableData_t::NumActuators, UserData_t::OAT, GPSUser_t::PDOP, UserData_t::Pdynamic, PITCH_AXIS, TelemLimits_t::PitchHigh, SimplePkt_t::PktType, UserData_t::PRes, UserData_t::Pstatic, AvailableData_t::RawSensor, UserData_t::RightRPM, ROLL_AXIS, TelemLimits_t::RollHigh, TelemLimits_t::RPMHigh, TelemLimits_t::RPMLow, TelemLimits_t::RPMMaskedByState, GPSUser_t::seconds, SimplePkt_t::Size, GPSUser_t::SolnType, GPSUser_t::Speed, GPSUser_t::Status, UserData_t::SystemTime, UserData_t::TAS, TELEMETRY_LO_RES, TelemLimits_t::TerMaskedByState, GPSUser_t::TrackedSats, GPSUser_t::VDown, GPSUser_t::VEast, GPSUser_t::VisibleSats, GPSUser_t::VNorth, UserData_t::VRes, GPSUser_t::Week, UserData_t::WeightOnWheel, TelemLimits_t::WindsHigh, UserData_t::WindSouth, UserData_t::WindWest, X_AXIS, Y_AXIS, YAW_AXIS, GPSUser_t::year, and Z_AXIS.
BOOL DecodeTransponderStatusPacket (const AutopilotPkt_t * pPkt, XPDRStatus_t * pStatus)
Decode the transponder status packet.
Decode the transponder status packet
Parameters
pPkt points to the autopilot packet that contains the transponder status data.
pStatus points to a transponder status structure that will return the decoded data.
Returns
TRUE if decoding of the transponder status packet was successful.
References XPDRStatus_t::Altitude, XPDRStatus_t::AltSource, SimplePkt_t::Data, DataToUInt16(), DataToUInt24(), XPDRStatus_t::Error, XPDRStatus_t::GPSError, XPDRStatus_t::ICAOError, XPDRStatus_t::Ident, XPDRStatus_t::Mode, XPDRStatus_t::OverTemp, SimplePkt_t::PktType, XPDRStatus_t::PowerUp, SimplePkt_t::Size, XPDRStatus_t::SquawkCode, XPDRStatus_t::SquitterFail, TRANSPONDER_STATUS, and XPDRStatus_t::Type.
const char* DecodeUserWarningPacket (AutopilotPkt_t * pPkt, UInt8 * pType, UInt8 * pCode)
Extract the data from a user warning packet.
Decode a user warning packet. This packet contains an ASCII string which can be displayed to the user as a warning.
Parameters
pPkt points to a autopilot packet containing the data.
pType receives the type info in the pakcet.
pCode receives the code info in the packet.
Returns
A null terminated string pointer containing the error, or NULL if the packet is invalid.
References SimplePkt_t::Data, MAX_SIMPLE_DATA, SimplePkt_t::PktType, SimplePkt_t::Size, and USER_WARNING.
void FormActuatorTestPacket (AutopilotPkt_t * pPkt, float Angle, float Width, float Freq, float Dev, UInt8 Index)
Form an actuator test command packet.
Form a autopilot actuator test packet including the packet header and crc. The actuator test packet is used to send test signals to specific control actuators.
Parameters
pPkt points to a autopilot packet to receive the formatted data.
Angle is the actuator angle to apply to the test, in rad. Pass more than 3.14 to disable angle test.
Width is the actuator pulse width to apply to the test, in microseconds. Pass zero to disable pulse test.
Freq is the frequency in hertz to use for sinusoidal test, pass more than 0.01 to enable.
Dev is the amplitude of the sinusoidal test in radians.
Index is the index of the control surface to apply the test to.
References ACTUATOR_TEST, SimplePkt_t::Data, DataToUInt32(), DecodeExternalIOSamplePacket(), EXTERNAL_IO_SAMPLE, MakeAutopilotPacket(), NUM_EXTERNAL_DIO_PINS, SimplePkt_t::PktType, RoundToSInt16(), RoundToUInt8(), SInt16ToData(), and SimplePkt_t::Size.
Referenced by CommBase_SendSurfaceTestPacket().
void FormBoundaryPacket (AutopilotPkt_t * pPkt, const Boundary_t * pBnd)
Form the airspace boundary packet.
Form the airspace boundary packet.
Parameters
pPkt receives the formatted packet.
pBnd is the boundary information to put in the packet.
References BOUNDARY, SimplePkt_t::Data, Boundary_t::East, Boundary_t::lat, Boundary_t::lon, MakeAutopilotPacket(), Boundary_t::N, Boundary_t::North, NUM_BOUNDARY, RoundToSInt16(), RoundToSInt32(), SInt16ToData(), and SInt32ToData().
Referenced by CommBase_SendBoundaryPacket().
void FormConfigurationLockPacket (AutopilotPkt_t * pPkt, const char Password[32])
Form a configuration lock packet.
Form a configuration lock packet including a password if provided.
Parameters
pPkt receives the formatted packet.
Password is the password to use. Pass NULL for a zero length lock packet with no password.
References CONFIG_LOCK, SimplePkt_t::Data, and MakeAutopilotPacket().
Referenced by CommBase_SendConfigurationLockPacket().
void FormConfigurationUnlockPacket (AutopilotPkt_t * pPkt, const char Password[32], BOOL Silent)
Form a configuration unlock packet.
Form a configuration unlock packet including a password if provided.
Parameters
pPkt receives the formatted packet.
Password is the password to use. Pass NULL for a zero length unlock packet with no password.
Silent should be TRUE to send the quiet version of this packet.
References CONFIG_UNLOCK, CONFIG_UNLOCK_QUIET, SimplePkt_t::Data, and MakeAutopilotPacket().
Referenced by CommBase_SendConfigurationUnlockPacket().
void FormControllerDataDefaultPacket (AutopilotPkt_t * pPkt, UInt8 Controller, UInt8 Version, UInt8 Category, UInt8 DataID, UInt8 NumData)
Form a controller data default packet.
Form a controller data request packet
Parameters
pPkt points to the autopilot packet to format
Controller is the controller ID value.
Version is the controller version value.
Category is the data category.
DataID is the starting DataID.
NumData is the number of data elements to encode.
References CONTROLLER_DATA_DEFAULT, SimplePkt_t::Data, and MakeAutopilotPacket().
Referenced by CommBase_SendControllerDataDefaultPacket().
void FormControllerDataRequestPacket (AutopilotPkt_t * pPkt, UInt8 Controller, UInt8 Version, UInt8 Category, UInt8 DataID, UInt8 NumData)
Form a controller data request packet.
Form a controller data request packet
Parameters
pPkt points to the autopilot packet to format
Controller is the controller ID value.
Version is the controller version value.
Category is the data category.
DataID is the starting DataID.
NumData is the number of data elements to encode.
References CONTROLLER_DATA_REQUEST, SimplePkt_t::Data, and MakeAutopilotPacket().
Referenced by CommBase_RequestControllerDataPacket().
void FormDoubletCommandPacket (AutopilotPkt_t * pPkt, const DoubletCmd_t * pCmd)
Form a packet commanding a doublet manuever.
Form a doublet command packet which instructs the autopilot to deflect a single control axis for a specified period of time in order to evaluate open loop plant dynamics.
Parameters
pPkt points to a autopilot packet to receive the formatted data.
pCmd points to the doublet command data to be included in the packet.
References DoubletCmd_t::APOff, DoubletCmd_t::Axis, DoubletCmd_t::Center, SimplePkt_t::Data, DoubletCmd_t::Delta, DOUBLET_CMD, DoubletCmd_t::Duration, MakeAutopilotPacket(), DoubletCmd_t::PosAndNeg, DoubletCmd_t::PulseTime, RoundToSInt16(), SInt16ToData(), and UInt16ToData().
Referenced by CommBase_SendDoubletCommandPacket().
void FormFeatureCodePacket (AutopilotPkt_t * pPkt, const UInt8 Data[8])
Form feature code packet.
Create a packet used to change the feature code.
Parameters
pPkt receives the created packet.
Data is the 8 byte hash to use for the feature code.
References SimplePkt_t::Data, FEATURE_CODE, and MakeAutopilotPacket().
Referenced by CommBase_SendFeatureCodePacket().
void FormFrequencySweepCommandPacket (AutopilotPkt_t * pPkt, const FrequencySweepCmd_t * pCmd)
Form a packet commanding a frequency sweep manuever.
Form a packet commanding a frequency sweep manuever which instructs the autopilot to perform a frequency sweep of a single control axis for system identification.
Parameters
pPkt points to a autopilot packet to receive the formatted data.
pCmd points to the frequency sweep settings structure.
References FrequencySweepCmd_t::Axis, SimplePkt_t::Data, FrequencySweepCmd_t::EndAmplitude, FrequencySweepCmd_t::EndFrequency, FREQ_SWEEP_CMD, MakeAutopilotPacket(), FrequencySweepCmd_t::OffAxisAPOff, FrequencySweepCmd_t::OnAxisAPOff, RoundFloatToUInt16(), RoundFloatToUInt8(), FrequencySweepCmd_t::StartAmplitude, FrequencySweepCmd_t::StartFrequency, FrequencySweepCmd_t::TotalTime, FrequencySweepCmd_t::TrimTime, and UInt16ToData().
Referenced by CommBase_SendFrequencySweepCommandPacket().
void FormMissionSettingsPacket (AutopilotPkt_t * pPkt, SInt16 MinAltitude, SInt16 MaxAltitude, UInt32 FlightTimeout)
Form the mission settings packet.
Create a packet used to update altitude limits and flight timeout.
Parameters
pPkt receives the created packet.
MinAltitude is the minimum altitude in meters.
MaxAltitude is the maximum altitude in meters.
FlightTimeout is the flight timeout in seconds
References SimplePkt_t::Data, MakeAutopilotPacket(), MISSION_SETTINGS, SInt16ToData(), and UInt32ToData().
Referenced by CommBase_SendMissionSettingsPacket().
void FormSensorErrorPacket (AutopilotPkt_t * pPkt, const SensorErrorData_t * pSensorError)
Build a sensor error packet.
Build a sensor error packet
Parameters
pPkt receives the formatted packet.
pSensorError is the data to format.
References SensorErrorData_t::AGLOffset, SensorErrorData_t::AllowControllerTAS, SimplePkt_t::Data, SensorErrorData_t::DisableAlign, SensorErrorData_t::DisableAlt, SensorErrorData_t::DisableInternalMag, SensorErrorData_t::DisableSBAS, SensorErrorData_t::DisableVDown, SensorErrorData_t::MagOnlyInAHRS, MakeAutopilotPacket(), SensorErrorData_t::OATfromStandardAtmo, SensorErrorData_t::PositionCorr, RoundToSInt16(), RoundToSInt8(), RoundToUInt8(), SENSOR_ERROR, SInt16ToData(), SensorErrorData_t::TASCutoff, SensorErrorData_t::TASFilterWindow, and SensorErrorData_t::TempRise.
Referenced by CommBase_SendSensorErrorPacket().
void FormSetFuelIfLockedPacket (AutopilotPkt_t * pPkt, float Fuel, BOOL Electric)
Form a packet to set the fuel level even if the autopilot is locked.
Form a set fuel level packet including the packet header and crc. This packet is used to set the fuel level even if the autopilot is locked.
Parameters
pPkt points to a autopilot packet to receive the formatted data.
Fuel is the fuel level in kilograms or Watt-Hours.
Electric is TRUE for electric motor (fuel in Watt-Hours).
References SimplePkt_t::Data, FloatToData(), MakeAutopilotPacket(), and SET_FUEL_IFLOCKED.
Referenced by CommBase_SendSetFuelIfLockedPacket().
void FormSetFuelLevelPacket (AutopilotPkt_t * pPkt, float Fuel, BOOL Electric)
Form a set fuel level packet.
Form a set fuel level packet including the packet header and crc.
Parameters
pPkt points to a autopilot packet to receive the formatted data.
Fuel is the fuel level in kilograms or Watt-Hours.
Electric is TRUE for electric motor (fuel in Watt-Hours).
References MakeAutopilotPacket(), and SET_FUEL_LEVEL.
Referenced by CommBase_SendSetFuelLevelPacket().
void FormTerrainElevationDataPacket (AutopilotPkt_t * pPkt, UInt32 Time, const float Elevations[6])
Elevation data for uplink to the avionics.
Create a packet used to uplink terrain elevation data to the avionics.
Parameters
pPkt receives the created packet.
Time is the system time at which the elevation data apply.
Elevations is the array of terrian elevations spaced 2 seconds apart, with the first element corresponding to Time.
References SimplePkt_t::Data, ELEVATION_DATA, MakeAutopilotPacket(), RoundToUInt16(), UInt16ToData(), and UInt32ToData().
Referenced by CommBase_SendTerrainElevationDataPacket().
void FormUserActionPacket (AutopilotPkt_t * pPkt, UInt8 ActionIndex, BOOL On)
Form the user action command.
Form the user action command
Parameters
pPkt points to the autopilot packet to format
ActionIndex is the index of the user action.
On should be TRUE to assert the action.
References SimplePkt_t::Data, MakeAutopilotPacket(), and USER_ACTION.
Referenced by CommBase_SendUserActionPacket().