Communications SDK: BsplineCurve.h File Reference
BsplineCurve.h File Reference
3-D basis spline curve library.
Enumerations
enum {
UNIFORM_METHOD, CHORD_METHOD, CENTRIPETAL_METHOD, UNIVERSAL_METHOD,
NUM_PARAM_SELECT_METHODS
}
Different methods for parameter selection in interpolation and approximation.
Functions
void GetCurveTriad (const double dCdu[3], const double d2Cdu2[3], double Tangent[3], double Normal[3], double Binormal[3], double *pCurvature)
Calculate the moving triad of a parametric curve C(u) (tangent + normal + binormal) and its curvature.
int CreateBsplineCurveKnots (int n, int p, int bClampBegin, int bClampEnd, double *uc)
Create an uniform knot array for an open b-spline curve.
void GetBsplineCurveBasisFun (double *uc, int m, int p, double u, double *N)
Calculate the basis function coefficients for a bspline curve at a single point in the parameter domain.
void EvaluateBsplineCurve (const double P[][3], int n, const double *uc, int m, double u, double C[3])
Evaluate a bspline curve at a single point in the parameter domain.
void GetBsplineCurveDerivControlPts (const double P[][3], int n, const double *uc, int m, double Q[][3])
Calculate the control polygon of the derivative of a b-spline curve.
void EvaluateBsplineCurveFirstDeriv (const double Q1[][3], int n, const double *uc, int m, double u, double dCdu[3])
Evaluate the first-order derivative dC/du of a b-spline curve C(u)
void EvaluateBsplineCurveSecondDeriv (const double Q2[][3], int n, const double *uc, int m, double u, double d2Cdu2[3])
Evaluate the second-order derivative d2C/du2 of a b-spline curve C(u)
int InterpolateBsplineCurve (const double D[][3], int n, int p, int method, double P[][3], double *u, int *m, double *t)
Interpolate through a series of data points using a bspline curve of arbitrary degree.
int ApproximateBsplineCurve (const double D[][3], int n, int p, int h, int method, double P[][3], double *u, int *m, double *t)
A least-squares approximation using a b-spline curve of specified degree and number of control points.
double MinDistanceToBsplineCurve (const double P[][3], const double Q1[][3], const double Q2[][3], int n, const double *uc, int m, const double R[3], double *u)
Calculate the minimum distance from an arbitrary point to a b-spline curve.
double MinDistanceToLinearBspline (const double P[][3], int n, const double *uc, const double R[3], double *u)
Calculate the minimum distance from an arbitrary point to a linear b-spline.
double DistanceAlongBsplineCurve (const double Q1[][3], int n, const double *uc, int m, double ustart, double ustop, int m1)
Calculate distance along the b-spline curve between two parameter values.
double MaxErrorInterpolateBsplineCurve (const double P[][3], const double Q[][3], int n, const double *uc, int m, double tstart, double tend, double step, double Pmax[3])
Calculate the max error between a line segment between two data points and an interpolation curve that passes through them.
int RefineDataInterpolateBsplineCurve (const double Din[][3], int nin, int p, int method, double limit, int maxiter, int nmax, double Dout[][3], int *nout, double *maxerr, int *iter)
Refine a data array such that its b-spline interpolation error relative to linear interpolation is within an acceptable limit.
Detailed Description
3-D basis spline curve library.
This module provides functions for computing b-spline curves of arbitrary degree. It also includes functions for calculating the first and second-order derivatives, generation of knot vector distributions, global interpolation, global approximations, for 3-dimensional problems. The main references for the algorithms implemented here are http://www.cs.mtu.edu/~shene/COURSES/cs3621/NOTES/ web notes, and the textbook "A Practical Guide to Splines" by C. de Boor.
Enumeration Type Documentation
anonymous enum
Different methods for parameter selection in interpolation and approximation.
Function Documentation
int ApproximateBsplineCurve (const double D[][3], int n, int p, int h, int method, double P[][3], double * u, int * m, double * t)
A least-squares approximation using a b-spline curve of specified degree and number of control points.
A least-squares approximation using a b-spline curve of a specified degree p and a specified number of control points h which is less than the number of input data points n. Reference: http://www.cs.mtu.edu/~shene/COURSES/cs3621/NOTES/INT-APP/CURVE-APP-global.html
Parameters
D is the 3-D data point array, size (n+1)x3.
n defines the number of data points.
p is the degree of the resulting bspline curve.
method is the method to be used for parameter selection, see NUM_PARAM_SELECT_METHODS.
h defines the number of bspline control points, n > h >= p >= 1.
P returns the resulting 3-D control point array, size (h+1)x3.
u returns the resulting knot vector, size m+1.
m returns the size of the knot vector m = h+p+1.
t returns the set of parameter values corresponding to the data points in D, size n+1.
Returns
TRUE if the approximation was successful, or FALSE if solving the linear system failed.
References BacksubLU(), GetBsplineCurveBasisFun(), MatrixLUInPlace(), MatrixSqr(), and N3D.
int CreateBsplineCurveKnots (int n, int p, int bClampBegin, int bClampEnd, double * uc)
Create an uniform knot array for an open b-spline curve.
Create an uniform knot array for a b-spline curve.
Parameters
n defines the number of control points (n+1).
p is the degree of the b-spline curve.
bClampBegin should be TRUE if we want the curve to be clamped at the beginning.
bClampEnd should be TRUE if we want the curve to be clamped at the end.
uc is an array that will return the knot distribution, size m+1.
The size of the knot vector m = n + p + 1.
Referenced by EvaluateBsplineCurveSecondDeriv().
double DistanceAlongBsplineCurve (const double Q1[][3], int n, const double * uc, int m, double ustart, double ustop, int m1)
Calculate distance along the b-spline curve between two parameter values.
Calculate distance along the b-spline curve between two parameter values. This is done by integrating ds = sqrt((dx/du)^2+(dy/du)^2+(dz/du)^2)*du between the start and stop parameters.
Parameters
Q1 is an array with the 3-D control points of the first-order derivative of the b-spline, size nx3.
n defines the size of the control point array.
uc is the knot vector for the b-spline curve, size m+1.
m defines the size of the knot vector.
ustart is the start parameter.
ustop is the stop parameter.
m1 is the number of grid points from "ustart" to "ustop". Since the grid has a fixed number of points, the smaller the parameter interval, the more accurate the calculated distance will be.
Returns
The distance along the b-spline curve between the two parameter values.
References EvaluateBsplineCurveFirstDeriv(), and VectorLength3D().
void EvaluateBsplineCurve (const double P[][3], int n, const double * uc, int m, double u, double C[3])
Evaluate a bspline curve at a single point in the parameter domain.
De Boor's algorithm is a generalization of de Casteljau's algorithm. It provides a fast and numerically stable way for finding a point on a B-spline curve given a u in the domain. Reference: http://www.cs.mtu.edu/~shene/COURSES/cs3621/NOTES/spline/B-spline/de-Boor.html Note that the degree of the curve is implicitly calculated from the number of control points "n" and the number of knots "m" as p = m - n - 1.
Parameters
P is the 3-D control point array, size (n+1)x3.
n specifies the size of the control point array.
uc is the knot array, size m+1.
m specifies the size of the knot array.
u is parameter in the [0, 1] interval at which the curve will be evaluated.
C is an array that receives the 3-D position of the parametric curve C(u) evaluated at "u".
References N3D.
Referenced by EvaluateBsplineCurveFirstDeriv(), EvaluateBsplineCurveSecondDeriv(), MaxErrorInterpolateBsplineCurve(), and MinDistanceToBsplineCurve().
void EvaluateBsplineCurveFirstDeriv (const double Q1[][3], int n, const double * uc, int m, double u, double dCdu[3])
Evaluate the first-order derivative dC/du of a b-spline curve C(u)
Evaluate the first-order derivative dC/du of a b-spline curve C(u).
Parameters
Q1 is the 3-D control point array of the curve derivative, size nx3.
n specifies the size of the control point array for the original curve C(u).
uc is the knot array, size m+1.
m specifies the size of the knot array.
u is parameter in the [0, 1] interval at which the curve derivative will be evaluated.
dCdu is an array that receives the 3-D position of the parametric curve dC/du evaluated at "u".
References EvaluateBsplineCurve().
Referenced by DistanceAlongBsplineCurve(), MaxErrorInterpolateBsplineCurve(), and MinDistanceToBsplineCurve().
void EvaluateBsplineCurveSecondDeriv (const double Q2[][3], int n, const double * uc, int m, double u, double d2Cdu2[3])
Evaluate the second-order derivative d2C/du2 of a b-spline curve C(u)
Evaluate the second-order derivative d2C/du2 of a b-spline curve C(u).
Parameters
Q2 is the 3-D control point array of the curve second derivative, size (n-1)x3.
n specifies the size of the control point array for the original curve C(u).
uc is the knot array, size m+1.
m specifies the size of the knot array.
u is parameter in the [0, 1] interval at which the curve second derivative will be evaluated.
d2Cdu2 is an array that receives the 3-D position of the parametric curve d2C/du2 evaluated at "u".
References CreateBsplineCurveKnots(), EvaluateBsplineCurve(), and GetBsplineCurveBasisFun().
Referenced by MinDistanceToBsplineCurve().
void GetBsplineCurveBasisFun (double * uc, int m, int p, double u, double * N)
Calculate the basis function coefficients for a bspline curve at a single point in the parameter domain.
Calculate the basis function coefficients for a given knot vector, degree of the curve and parameter value. Reference: http://www.cs.mtu.edu/~shene/COURSES/cs3621/NOTES/spline/B-spline/bspline-curve-coef.html
Parameters
uc is the knot vector, of size m+1.
m is the knot vector size.
p is the bspline curve degree.
u is the parameter value at which the basis functions will be evaluated.
N points to the resulting basis functions coefficient array, size n+1, where n = m - p - 1.
Referenced by ApproximateBsplineCurve(), EvaluateBsplineCurveSecondDeriv(), and InterpolateBsplineCurve().
void GetBsplineCurveDerivControlPts (const double P[][3], int n, const double * uc, int m, double Q[][3])
Calculate the control polygon of the derivative of a b-spline curve.
Calculate the control points Q of a b-spline curve that is the dC/du derivative of another b-spline C(u) defined by the control points P. The derivative of any b-spline of degree "p" is another b-spline of degree "p-1", defined by a new set of control points which are calculated here. Reference: http://www.cs.mtu.edu/~shene/COURSES/cs3621/NOTES/spline/B-spline/bspline-derv.html
Parameters
P is the 3-D control point array, size (n+1)x3.
n specifies the size of the control point array.
uc is the knot array, size m+1.
m specifies the size of the knot array.
Q receives the 3-D control point array of the derivative curve, size nx3.
Referenced by RefineDataInterpolateBsplineCurve().
void GetCurveTriad (const double dCdu[3], const double d2Cdu2[3], double Tangent[3], double Normal[3], double Binormal[3], double * pCurvature)
Calculate the moving triad of a parametric curve C(u) (tangent + normal + binormal) and its curvature.
Calculate the moving triad of a parametric curve C(u) (tangent + normal + binormal) and its curvature, given the first and second order derivatives with respect to the curve parameter dC/du and d2C/du2. The tangent and normal vectors lie in the curvature plane. The binormal is perpendicular to the curvature plane. Reference: http://www.cs.mtu.edu/~shene/COURSES/cs3621/NOTES/curves/normal.html
Parameters
dCdu is the first-order derivative of the curve w.r.t its parameter u.
d2Cdu2 is the second-order derivative of the curve w.r.t. its parameter u.
Tangent is an array that receives the tangent unit vector.
Normal is an array that receives the normal unit vector.
Binormal is an array that receives the binormal unit vector (normal to the osculating plane).
pCurvature is a pointer that receives the curvature k = 1/R.
References CrossProduct3D(), UnitVector3D(), X_AXIS, Y_AXIS, and Z_AXIS.
int InterpolateBsplineCurve (const double D[][3], int n, int p, int method, double P[][3], double * u, int * m, double * t)
Interpolate through a series of data points using a bspline curve of arbitrary degree.
Interpolate through a series of data points using a bspline curve of arbitrary degree. The parameter set is determined using the universal method. Reference: http://www.cs.mtu.edu/~shene/COURSES/cs3621/NOTES/INT-APP/CURVE-INT-global.html
Parameters
D is the 3-D data point array, size (n+1)x3.
n defines the number of data points.
p is the degree of the resulting bspline curve.
method is the method to be used for parameter selection, see NUM_PARAM_SELECT_METHODS.
P returns the resulting 3-D control point array, size (n+1)x3.
u returns the resulting knot vector, size m+1.
m returns size of the knot vector m = n+p+1.
t returns the set of parameter values corresponding to the data points in D, size n+1.
Returns
TRUE if the interpolation was successful, or FALSE if solving the linear system failed.
References BacksubLU(), GetBsplineCurveBasisFun(), MatrixLUInPlace(), N3D, and TransposeSquare().
Referenced by RefineDataInterpolateBsplineCurve().
double MaxErrorInterpolateBsplineCurve (const double P[][3], const double Q[][3], int n, const double * uc, int m, double tstart, double tend, double step, double Pmax[3])
Calculate the max error between a line segment between two data points and an interpolation curve that passes through them.
Calculate the max error between a line segment between two data points and an interpolation curve that passes through them.
Parameters
P is the array of control points for the interpolation b-spline curve, size (n+1)x3.
Q is the array of control points for the interpolation b-spline curve derivative, size nx3.
n defines the size of the control point arrays.
uc is the knot vector, size m+1.
m defines the size of the knot vector.
tstart is the curve parameter at the starting point position.
tend is the curve parameter at the ending point position.
step is a step size (resolution) at which the error will be evaluated.
Pmax returns the position on the straight line between the starting and ending points at which curve error is the largest.
Returns
The maximum error between the interpolated b-spline curve and the straight line segment between the two points.
References DotProduct3D(), EvaluateBsplineCurve(), EvaluateBsplineCurveFirstDeriv(), SubtractVectors3D(), UnitVector3D(), and VectorLength3D().
Referenced by RefineDataInterpolateBsplineCurve().
double MinDistanceToBsplineCurve (const double P[][3], const double Q1[][3], const double Q2[][3], int n, const double * uc, int m, const double R[3], double * u)
Calculate the minimum distance from an arbitrary point to a b-spline curve.
Calculate the minimum distance from an arbitrary point to a b-spline curve.
Parameters
P is an array with the 3-D control points of the b-spline curve, size (n+1)x3.
Q1 is an array with the 3-D control points of the b-spline curve first-order derivative, size nx3.
Q2 is an array with the 3-D control points of the b-spline curve second-order derivative, size (n-1)x3.
n defines the size of the control point array.
uc is the knot array of size m+1.
m defines the size of the knot array.
R is an arbitrary point in the 3-D space.
u is a pointer to the initial guess for the curve parameter at minimum distance location; this will also return the actual minimum distance location on the curve.
Returns
The minimum distance between the arbitrary point and the b-spline curve.
References DotProduct3D(), EvaluateBsplineCurve(), EvaluateBsplineCurveFirstDeriv(), EvaluateBsplineCurveSecondDeriv(), SubtractVectors3D(), UnitVector3D(), and VectorLength3D().
double MinDistanceToLinearBspline (const double P[][3], int n, const double * t, const double R[3], double * u)
Calculate the minimum distance from an arbitrary point to a linear b-spline.
Calculate the minimum distance from an arbitrary point to a linear b-spline.
Parameters
P is an array with the 3-D control points of the b-spline curve, size (n+1)x3.
n defines the size of the control point array.
t is the array of curve parameters at data point locations, size n+1.
R is an arbitrary point in the 3-D space.
u is a pointer for returning the actual minimum distance location on the curve.
Returns
The minimum distance between the arbitrary point and the b-spline curve.
int RefineDataInterpolateBsplineCurve (const double Din[][3], int nin, int p, int method, double limit, int maxiter, int nmax, double Dout[][3], int * nout, double * maxerr, int * iter)
Refine a data array such that its b-spline interpolation error relative to linear interpolation is within an acceptable limit.
Refine a data array such that its b-spline interpolation error relative to linear interpolation is within an acceptable limit
References GetBsplineCurveDerivControlPts(), InterpolateBsplineCurve(), and MaxErrorInterpolateBsplineCurve().