Communications SDK: ByteOrder.h File Reference
ByteOrder.h File Reference
Network and host byte ordering functions.
#include "Types.h"
Functions
UInt16 DataToUInt16 (const UInt8 *pData)
SInt16 DataToSInt16 (const UInt8 *pData)
UInt32 DataToUInt24 (const UInt8 *pData)
UInt32 DataToUInt32 (const UInt8 *pData)
SInt32 DataToSInt32 (const UInt8 *pData)
UInt64 DataToUInt64 (const UInt8 *pData)
SInt64 DataToSInt64 (const UInt8 *pData)
float DataToFloat (const UInt8 *pData, BOOL *Invalid)
double DataToDouble (const UInt8 *pData, BOOL *Invalid)
UInt32 UInt16ToData (UInt8 *pData, UInt16 Value)
UInt32 SInt16ToData (UInt8 *pData, SInt16 Value)
UInt32 UInt24ToData (UInt8 *pData, UInt32 Value)
UInt32 UInt32ToData (UInt8 *pData, UInt32 Value)
UInt32 SInt32ToData (UInt8 *pData, SInt32 Value)
UInt32 UInt64ToData (UInt8 *pData, UInt64 Value)
UInt32 SInt64ToData (UInt8 *pData, SInt64 Value)
UInt32 FloatToData (UInt8 *pData, float Value)
UInt32 DoubleToData (UInt8 *pData, double Value)
UInt16 leDataToUInt16 (const UInt8 *pData)
SInt16 leDataToSInt16 (const UInt8 *pData)
UInt32 leDataToUInt32 (const UInt8 *pData)
SInt32 leDataToSInt32 (const UInt8 *pData)
UInt64 leDataToUInt64 (const UInt8 *pData)
double leDataToDouble (const UInt8 *pData, BOOL *pInvalid)
float leDataToFloat (const UInt8 *pData, BOOL *pInvalid)
BOOL IsValidFloat (UInt32 FloatCandidate)
BOOL IsValidDouble (UInt64 DoubleCandidate)
SInt32 RoundToInteger (register double Value)
SInt32 RoundToSInt32 (double Value)
SInt16 RoundToSInt16 (double Value)
SInt8 RoundToSInt8 (double Value)
UInt32 RoundToUInt32 (double Value)
UInt32 RoundToUInt24 (double Value)
UInt16 RoundToUInt16 (double Value)
UInt8 RoundToUInt8 (double Value)
SInt32 RoundFloatToInteger (float Value)
SInt32 RoundFloatToSInt32 (float Value)
SInt16 RoundFloatToSInt16 (float Value)
SInt8 RoundFloatToSInt8 (float Value)
UInt32 RoundFloatToUInt32 (float Value)
UInt32 RoundFloatToUInt24 (float Value)
UInt16 RoundFloatToUInt16 (float Value)
UInt8 RoundFloatToUInt8 (float Value)
UInt32 UInt16ToleData (UInt8 *pData, UInt16 Value)
UInt32 SInt16ToleData (UInt8 *pData, SInt16 Value)
UInt32 UInt32ToleData (UInt8 *pData, UInt32 Value)
UInt32 SInt32ToleData (UInt8 *pData, SInt32 Value)
UInt32 UInt64ToleData (UInt8 *pData, UInt64 Value)
UInt32 FloatToleData (UInt8 *pData, float Value)
UInt32 DoubleToleData (UInt8 *pData, double Value)
UInt16 FloatToFloat16 (float Data)
float Float16ToFloat (UInt16 Data)
float FloatValidate (UInt32 Data, BOOL *pInvalid)
double DoubleValidate (UInt64 Data, BOOL *pInvalid)
Detailed Description
Network and host byte ordering functions.
This module contains the functions to switch between network and host byte order.
Function Documentation
double DataToDouble (const UInt8 * pData, BOOL * pInvalid)
Convert a string of bytes in network byte order to a double precision 64-bit floating point number in host byte order. Note that pData must point to an aligned address. If it does not use the function DataToDoubleMisaligned().
Parameters
pData points to a four byte string of data in network byte order
pInvalid points to space to receive a flag indicating if the data represent a valid floating point number. If it does not then pInvalid will be written to a 1.
Returns
The floating point value encoded in the string.
References DataToUInt64(), and DoubleValidate().
Referenced by DecodeGPSPosVelPacket().
float DataToFloat (const UInt8 * pData, BOOL * pInvalid)
Convert a string of bytes in network byte order to a single precision 32-bit floating point number in host byte order.
Parameters
pData points to a four byte string of data in network byte order
pInvalid points to space to receive a flag indicating if the data represent a valid floating point number. If it does not then pInvalid will be written to a 1.
Returns
The floating point value encoded in the string. If the number is not valid than 1.0 is returned
References DataToUInt32(), and FloatValidate().
Referenced by DecodeAutopilotLoopControlPacketEx(), DecodeExternalADCSamplePacket(), DecodeGimbalMagCalPacket(), DecodeGPSPosVelPacket(), DecodeGSRadioSettingsPacket(), DecodeGSSpectrumSweepDetails(), DecodeLegacySystemStatusHiResPacket(), DecodeLensDiagnosticsPacket(), DecodeMagCalPacket(), DecodeMC_AxisParamPacket(), DecodeMC_LimitsPacket(), DecodeMC_MotionCalibrationParamPacket(), DecodeOrientationPacket(), DecodePayloadMassPacket(), DecodeRadioSettingsPacket(), DecodeSPOIPathSettings(), DecodeSystemStatusPacket(), DecodeVps3OverlaySettings(), and FormVGSRadioSettings().
SInt16 DataToSInt16 (const UInt8 * pData)
Convert a string of bytes in network byte order to a signed 16-bit integer in host byte order.
Parameters
pData points to a two byte string of data in network byte order
Returns
The 16-bit signed integer encoded in the string.
Referenced by DecodeActuatorTablePacket(), DecodeBoundaryPacket(), DecodeDualAntStatusPacket(), DecodeECUStatusPacket(), DecodeFrameShiftPacket(), DecodeGimbalAnglePacket(), DecodeGimbalAxisSettingsPacket(), DecodeGimbalCameraAlignPacket(), DecodeGimbalCameraCmdPacket(), DecodeGimbalCurrentPacket(), DecodeGimbalFLIRConfigurationPacket(), DecodeGimbalGeoreferencePacket(), DecodeGimbalGPSLeverArmPacket(), DecodeGimbalIRCamConfigurationPacket(), DecodeGimbalRatePacket(), DecodeGimbalRetractorConfigurationPacket(), DecodeGimbalSensorConfigPacket(), DecodeGimbalSPOICmdPacket(), DecodeGimbalStabDevTelemetry(), DecodeGimbalTelemetryPacket(), DecodeGimbalTrackCommand(), DecodeGimbalTrackingData(), DecodeGimbalVersion2Packet(), DecodeGimbalVersionPacket(), DecodeGPSHealth(), DecodeGSGPSHealth(), DecodeGSTelemetryPacket(), DecodeHighSpeedDoubletDataPacket(), DecodeLegacyWaypointPacket(), DecodeLensCalFocusPacket(), DecodeLensDevCommandPacket(), DecodeLensDiagnosticsPacket(), DecodeLensPrefocusPacket(), DecodeLowSpeedDoubletDataPacket(), DecodeMissionLimitsPacket(), DecodeMotionCtrlDiagnosticsPacket(), DecodeMovingBaseStatusPacket(), DecodeScanModeControlPacket(), DecodeSensorErrorPacket(), DecodeServoTelemetryPacket(), DecodeSimpleLandingPacket(), DecodeSPOIPathSettings(), DecodeStabDevT2Settings(), DecodeSystemStatusPacket(), DecodeTelemetryHiResPacket(), DecodeVGSAntennaYaw(), and DecodeVGSTelemetry().
SInt32 DataToSInt32 (const UInt8 * pData)
Convert a string of bytes in network byte order to a signed 32-bit integer in host byte order.
Parameters
pData points to a four byte string of data in network byte order
Returns
The 32-bit signed integer encoded in the string.
Referenced by DecodeBoundaryPacket(), DecodeDGPSBasePacket(), DecodeExternalIOSetupPacketEx(), DecodeGimbalGeoreferencePacket(), DecodeGimbalSPOICmdPacket(), DecodeGimbalTargetLocationEstimate(), DecodeGimbalTelemetryPacket(), DecodeGPSHealth(), DecodeGSGPSHealth(), DecodeGSTelemetryPacket(), DecodeLegacySystemStatusHiResPacket(), DecodeLegacyWaypointPacket(), DecodeMovingBaseStatusPacket(), DecodeSimpleLandingPacket(), DecodeSystemStatusPacket(), DecodeTelemetryHiResPacket(), and DecodeVGSTelemetry().
SInt64 DataToSInt64 (const UInt8 * pData)
Convert a string of bytes in network byte order to a unsigned 64-bit integer in host byte order.
Parameters
pData points to a eight byte string of data in network byte order
Returns
The 64-bit unsigned integer encoded in the string.
References DataToUInt32().
UInt16 DataToUInt16 (const UInt8 * pData)
Convert a string of bytes in network byte order to a unsigned 16-bit integer in host byte order.
Parameters
pData points to a two byte string of data in network byte order
Returns
The 16-bit unsigned integer encoded in the string.
Referenced by DecodeActuatorTablePacket(), DecodeCameraDefinitionsPacket(), DecodeCanPassthroughPacket(), DecodeDGPSBasePacket(), DecodeDualAntStatusPacket(), DecodeECUCommandPacket(), DecodeECUStatusPacket(), DecodeFpgaBitVersionPacket(), DecodeFrameShiftPacket(), DecodeGimbalAglPacket(), DecodeGimbalAxisSettingsPacket(), DecodeGimbalCameraAlignPacket(), DecodeGimbalCameraCmdPacket(), DecodeGimbalDiagnosticsPacket(), DecodeGimbalFLIRConfigurationPacket(), DecodeGimbalGeoreferencePacket(), DecodeGimbalIRCamConfigurationPacket(), DecodeGimbalLasersInstalledPacket(), DecodeGimbalRawVibrationPacket(), DecodeGimbalResetReportPacket(), DecodeGimbalRetractorConfigurationPacket(), DecodeGimbalRigTestCmdPacket(), DecodeGimbalTelemetryPacket(), DecodeGimbalTrackerSettingsAdvancedCommand(), DecodeGimbalVersion2Packet(), DecodeGimbalVersionPacket(), DecodeGPSHealth(), DecodeGPSPosVelPacket(), DecodeGSGPSHealth(), DecodeGSResetReportPacket(), DecodeGSSpectrumSweepDetails(), DecodeGSTelemetryPacket(), DecodeGSVersionPacket(), DecodeHighSpeedDoubletDataPacket(), DecodeLaserEnablePswdPacket(), DecodeLegacySystemStatusHiResPacket(), DecodeLegacySystemStatusLoResPacket(), DecodeLensControlVersionPacket(), DecodeLensDiagnosticsPacket(), DecodeLensPrefocusPacket(), DecodeLensRegisterPacket(), DecodeLowSpeedDoubletDataPacket(), DecodeMbAppVersionPacket(), DecodeMbUserWarningPacket(), DecodeMicroblazeDiagnosticsPacket(), DecodeMISBSettingsPacket(), DecodeMissionLimitsPacket(), DecodeMotionCtrlDiagnosticsPacket(), DecodeMotionCtrlVersionPacket(), DecodeMovingBaseStatusPacket(), DecodeRawVibrationPacket(), DecodeResetReportPacket(), DecodeServoTelemetryPacket(), DecodeSimpleLandingPacket(), DecodeSPOIPathPointData(), DecodeSuCsxConfigurationPacket(), DecodeSystemStatusPacket(), DecodeSystemVersionPacket(), DecodeTelemetryHiResPacket(), DecodeTelemetryLoResPacket(), DecodeThrottleMinPacket(), DecodeTransponderControlPacket(), DecodeTransponderStatusPacket(), DecodeVGSTelemetry(), DecodeVps3UserWarningPacket(), and DecodeVps3VersionPacket().
UInt32 DataToUInt24 (const UInt8 * pData)
Convert a string of bytes in network byte order into an unsigned 24-bit integer in host byte order. Since not all hosts support an intrinsic 24-bit type the data is returned as 32-bits
Parameters
pData points to space to receive a three byte string of data in network byte order
Returns
Returns a 32-bit integer (high byte always zero)
Referenced by DecodeGimbalDiagnosticsPacket(), DecodeGimbalGeoreferencePacket(), DecodeGimbalTelemetryPacket(), DecodeGimbalTrackingData(), DecodeGimbalWaterMarkPacket(), DecodeGPSHealth(), DecodeGSGPSHealth(), DecodeGSTelemetryPacket(), DecodeLegacySystemStatusHiResPacket(), DecodeLegacySystemStatusLoResPacket(), DecodeMovingBaseStatusPacket(), DecodeSPOIPathPointData(), DecodeSystemStatusPacket(), DecodeTelemetryHiResPacket(), DecodeTelemetryLoResPacket(), DecodeTransponderInstallationPacket(), DecodeTransponderStatusPacket(), and DecodeWaypointListPacket().
UInt32 DataToUInt32 (const UInt8 * pData)
Convert a string of bytes in network byte order to a unsigned 32-bit integer in host byte order.
Parameters
pData points to a four byte string of data in network byte order
Returns
The 32-bit unsigned integer encoded in the string.
Referenced by DataToFloat(), DataToSInt64(), DataToUInt64(), DecodeAltimeterSettingPacket(), DecodeControllerDataPacket(), DecodeDualAntStatusPacket(), DecodeECUStatusPacket(), DecodeGimbalCurrentPacket(), DecodeGimbalGeoreferencePacket(), DecodeGimbalRatePacket(), DecodeGimbalResetReportPacket(), DecodeGimbalSensorConfigPacket(), DecodeGimbalStabDevTelemetry(), DecodeGimbalTargetLocationEstimate(), DecodeGimbalTelemetryPacket(), DecodeGimbalVersion2Packet(), DecodeGimbalVersionPacket(), DecodeGSResetReportPacket(), DecodeGSTelemetryPacket(), DecodeGSVersionPacket(), DecodeLensRegisterPacket(), DecodeMbResetReportPacket(), DecodeMicroblazeDiagnosticsPacket(), DecodeMISBSettingsPacket(), DecodeMissionLimitsPacket(), DecodeMovingBaseStatusPacket(), DecodeResetReportPacket(), DecodeSPOIPathSettings(), DecodeSystemVersionPacket(), DecodeTelemetryHiResPacket(), DecodeTelemetryLoResPacket(), DecodeVGSTelemetry(), DecodeVps3DiagnosticsPacket(), DecodeVps3ResetReportPacket(), DecodeWaypointsPacket(), and FormActuatorTestPacket().
UInt64 DataToUInt64 (const UInt8 * pData)
Convert a string of bytes in network byte order to a unsigned 64-bit integer in host byte order.
Parameters
pData points to a eight byte string of data in network byte order
Returns
The 64-bit unsigned integer encoded in the string.
References DataToUInt32().
Referenced by DataToDouble(), and DecodeVps3OverlaySettings().
UInt32 DoubleToData (UInt8 * pData, double Value)
Convert a 64-bit single precision floating point number in host byte order into a string of bytes in network byte order. This function can be used even if pData points to an unaligned address.
Parameters
pData points to space to receive a eight byte string of data in network byte order
Value is the floating point data to be encoded.
Returns
Number of bytes required to encode Value.
References UInt64ToData().
Referenced by FormGPSPosVelPacket().
UInt32 DoubleToleData (UInt8 * pData, double Value)
Convert a 64-bit single precision floating point number in host byte order into a string of bytes in little endian byte order. This function can be used even if pData points to an unaligned address. NOTE: Works on little-endian target only.
Parameters
pData points to space to receive a eight byte string of data in network byte order
Value is the floating point data to be encoded.
Returns
Number of bytes required to encode Value.
References UInt64ToleData().
double DoubleValidate (UInt64 Data, BOOL * pInvalid)
Validate a floating point number in integer representation. If the number is valid return the floating point result.
Parameters
Data is the 64-bit integer expression of the floating point number.
pInvalid points to space to receive a flag indicating if the data represent a valid floating point number. If it does not then pInvalid will be written to a 1.
Returns
The floating point value represented by Data. If the number is not valid than 1.0 is returned
References IsValidDouble().
Referenced by DataToDouble(), and leDataToDouble().
float Float16ToFloat (UInt16 Data)
Convert a 16-bit floating point value to 32-bit IEEE-754 floating point Do this by expanding the exponent to 8 bits (from 6) and the mantissa to 23 bits (from 9)
Parameters
Data is the 16-bit floating point data to convert.
Returns
The 32-bit IEEE-754 representation.
References FloatToFloat16().
Referenced by DecodeDGPSBasePacket(), DecodeGimbalRawVibrationPacket(), DecodeGPSPosVelPacket(), DecodeLegacySystemStatusHiResPacket(), DecodeLegacySystemStatusLoResPacket(), DecodeMovingBaseStatusPacket(), DecodeRawVibrationPacket(), DecodeSystemStatusPacket(), DecodeTelemetryHiResPacket(), and DecodeTelemetryLoResPacket().
UInt32 FloatToData (UInt8 * pData, float Value)
Convert a 32-bit single precision floating point number in host byte order into a string of bytes in network byte order. This function can be used even if pData points to an unaligned address.
Parameters
pData points to space to receive a four byte string of data in network byte order
Value is the floating point data to be encoded.
Returns
Number of bytes required to encode Value.
References UInt32ToData().
Referenced by FormAutopilotLoopControlPacketEx(), FormGimbalMagCalPacket(), FormGPSPosVelPacket(), FormGSRadioSettingsPacket(), FormGSSpectrumSweepDetails(), FormMagCalPacket(), FormMC_AxisParamPacket(), FormMC_LimitsPacket(), FormMC_MotionCalibrationParamPacket(), FormOrientationPacket(), FormPayloadMassPacket(), FormRadioSettingsPacket(), FormSetFuelIfLockedPacket(), FormSPOIPathSettings(), FormVGSRadioSettings(), and FormVps3OverlaySettings().
UInt16 FloatToFloat16 (float Data)
Convert a 32-bit IEEE-754 floating point value to 16-bits. Do this by limiting the exponent to 6 bits (from 8) and the mantissa to 9 bits (from 23). Underflows will be returned as zeros and overflows will be returned with the largest 6-bit exponent.
Parameters
Data is the 32-bit floating point data to convert.
Returns
The 16-bit representation.
Referenced by Float16ToFloat(), FormDGPSBasePacket(), and FormGPSPosVelPacket().
UInt32 FloatToleData (UInt8 * pData, float Value)
Convert a 32-bit single precision floating point number in host byte order into a string of bytes in little endian byte order. This function can be used even if pData points to an unaligned address. NOTE: Works on little-endian target only.
Parameters
pData points to space to receive a four byte string of data in network byte order
Value is the floating point data to be encoded.
Returns
Number of bytes required to encode Value.
References UInt32ToleData().
float FloatValidate (UInt32 Data, BOOL * pInvalid)
Validate a floating point number in integer representation. If the number is valid return the floating point result.
Parameters
Data is the 32-bit integer expression of the floating point number.
pInvalid points to space to receive a flag indicating if the data represent a valid floating point number. If it does not then pInvalid will be written to a 1.
Returns
The floating point value represented by Data. If the number is not valid than 1.0 is returned
References IsValidFloat().
Referenced by DataToFloat(), and leDataToFloat().
BOOL IsValidDouble (UInt64 DoubleCandidate)
Check the passed 64-bit field to determine if it represents a valid double precision floating point number. There are four cases, infinity, NaN, Denormalized, and normalized. Only the last case is valid
Parameters
DoubleCandidate is the 64-bit double precision floating point candidate.
Returns
TRUE if the floating point candidate represents a valid number.
Referenced by DoubleValidate().
BOOL IsValidFloat (UInt32 FloatCandidate)
Check the passed 32-bit field to determine if it represents a valid single precision floating point number. There are four cases, infinity, NaN, Denormalized, and normalized. Only the last case is valid
Parameters
FloatCandidate is the 32-bit single precision floating point candidate.
Returns
TRUE if the floating point candidate represents a valid number.
Referenced by DecodeControllerDataPacket(), and FloatValidate().
double leDataToDouble (const UInt8 * pData, BOOL * pInvalid)
Convert a string of bytes in little endian byte order to a double precision 64-bit floating point number in host byte order. Note that pData must point to an aligned address. If it does not use the function DataToDoubleMisaligned().
Parameters
pData points to a four byte string of data in network byte order
pInvalid points to space to receive a flag indicating if the data represent a valid floating point number. If it does not then pInvalid will be written to a 1.
Returns
The floating point value encoded in the string.
References DoubleValidate(), and leDataToUInt64().
float leDataToFloat (const UInt8 * pData, BOOL * pInvalid)
Convert a string of bytes in little endian byte order to a single precision 32-bit floating point number in host byte order.
Parameters
pData points to a four byte string of data in network byte order
pInvalid points to space to receive a flag indicating if the data represent a valid floating point number. If it does not then pInvalid will be written to a 1.
Returns
The floating point value encoded in the string. If the number is not valid than 1.0 is returned
References FloatValidate(), and leDataToUInt32().
SInt16 leDataToSInt16 (const UInt8 * pData)
Convert a string of bytes in little endian order to a signed 16-bit integer in host byte order.
Parameters
pData points to a four byte string of data in little endian byte order
Returns
The 32-bit unsigned integer encoded in the string.
SInt32 leDataToSInt32 (const UInt8 * pData)
Convert a string of bytes in little endian order to signed 32-bit integer in host byte order.
Parameters
pData points to a four byte string of data in little endian byte order
Returns
The 32-bit signed integer encoded in the string.
UInt16 leDataToUInt16 (const UInt8 * pData)
Convert a string of bytes in little endian order to a unsigned 16-bit integer in host byte order.
Parameters
pData points to a four byte string of data in little endian byte order
Returns
The 32-bit unsigned integer encoded in the string.
UInt32 leDataToUInt32 (const UInt8 * pData)
Convert a string of bytes in little endian order to a unsigned 32-bit integer in host byte order.
Parameters
pData points to a four byte string of data in little endian byte order
Returns
The 32-bit unsigned integer encoded in the string.
Referenced by leDataToFloat().
UInt64 leDataToUInt64 (const UInt8 * pData)
Convert a string of bytes in little endian order to unsigned 64-bit integer in host byte order.
Parameters
pData points to a four byte string of data in little endian byte order
Returns
The 32-bit signed integer encoded in the string.
Referenced by leDataToDouble().
SInt16 RoundFloatToSInt16 (float Value)
Return a correctly rounded integer result, instead of a truncated result the result returned is limited to the bounds of a signed 16-bit integer (-32768 to 32767)
Parameters
Value is the floating point value to be rounded to an integer.
Returns
The correctly rounded integer.
References RoundToSInt16().
Referenced by FormFrameShiftPacket(), FormLensCalFocusPacket(), and FormScanModeControlPacket().
SInt32 RoundFloatToSInt32 (float Value)
Return a correctly rounded integer result, instead of a truncated result the result returned is limited to the bounds of a signed 32-bit integer (-2147483648 to 2147483647)
Parameters
Value is the floating point value to be rounded to an integer.
Returns
The correctly rounded integer.
References RoundToSInt32().
SInt8 RoundFloatToSInt8 (float Value)
Return a correctly rounded integer result, instead of a truncated result the result returned is limited to the bounds of a signed 8-bit integer (-128 to 127)
Parameters
Value is the floating point value to be rounded to an integer.
Returns
The correctly rounded integer.
References RoundToSInt8().
UInt16 RoundFloatToUInt16 (float Value)
Return a correctly rounded integer result, instead of a truncated result the result returned is limited to the bounds of a unsigned 16-bit integer (0 to 65535)
Parameters
Value is the floating point value to be rounded to an integer.
Returns
The correctly rounded integer.
References RoundToUInt16().
Referenced by FormFrequencySweepCommandPacket(), and FormLensPrefocusPacket().
UInt32 RoundFloatToUInt24 (float Value)
Return a correctly rounded integer result, instead of a truncated result the result returned is limited to the bounds of a unsigned 24-bit integer (0 to 16777215)
Parameters
Value is the floating point value to be rounded to an integer.
Returns
The correctly rounded integer.
References RoundToUInt24().
UInt32 RoundFloatToUInt32 (float Value)
Return a correctly rounded integer result, instead of a truncated result the result returned is limited to the bounds of a unsigned 32-bit integer (0 to 4294967295)
Parameters
Value is the floating point value to be rounded to an integer.
Returns
The correctly rounded integer.
References RoundToUInt32().
UInt8 RoundFloatToUInt8 (float Value)
Return a correctly rounded integer result, instead of a truncated result the result returned is limited to the bounds of a unsigned 8-bit integer (0 to 255)
Parameters
Value is the floating point value to be rounded to an integer.
Returns
The correctly rounded integer.
References RoundToUInt8().
Referenced by FormFrequencySweepCommandPacket(), FormMISBSettingsPacket(), and FormScanModeControlPacket().
SInt16 RoundToSInt16 (double Value)
Return a correctly rounded integer result, instead of a truncated result the result returned is limited to the bounds of a signed 16-bit integer (-32768 to 32767)
Parameters
Value is the floating point value to be rounded to an integer.
Returns
The correctly rounded integer.
Referenced by FormActuatorTablePacket(), FormActuatorTestPacket(), FormBoundaryPacket(), FormDoubletCommandPacket(), FormDualAntStatusPacket(), FormGimbalAxisSettingsPacket(), FormGimbalCameraAlignPacket(), FormGimbalCameraCmdPacket(), FormGimbalCmdPacket(), FormGimbalGPSLeverArmPacket(), FormGimbalHostAttitudePacket(), FormGimbalHostGPSPacket(), FormGimbalHostSensorPacket(), FormGimbalInitialHeadingPacket(), FormGimbalRetractorConfigurationPacket(), FormGimbalSensorConfigPacket(), FormGimbalSPOICmdPacket(), FormGimbalTrackCommand(), FormGimbalTrackingData(), FormGSGPSHealthPacket(), FormGSTelemetryPacket(), FormSensorErrorPacket(), FormSimpleLandingPacket(), FormSPOIPathSettings(), FormVGSAntennaCommand(), FormVGSAntennaYaw(), and RoundFloatToSInt16().
SInt32 RoundToSInt32 (double Value)
Return a correctly rounded integer result, instead of a truncated result the result returned is limited to the bounds of a signed 32-bit integer (-2147483648 to 2147483647)
Parameters
Value is the floating point value to be rounded to an integer.
Returns
The correctly rounded integer.
Referenced by FormBoundaryPacket(), FormDGPSBasePacket(), FormGimbalHostGPSPacket(), FormGimbalSPOICmdPacket(), FormGimbalTargetLocationEstimate(), FormGSGPSHealthPacket(), FormGSTelemetryPacket(), FormLegacyWaypointPacket(), FormSimpleLandingPacket(), and RoundFloatToSInt32().
SInt8 RoundToSInt8 (double Value)
Return a correctly rounded integer result, instead of a truncated result the result returned is limited to the bounds of a signed 8-bit integer (-128 to 127)
Parameters
Value is the floating point value to be rounded to an integer.
Returns
The correctly rounded integer.
Referenced by FormGSTelemetryPacket(), FormSensorErrorPacket(), and RoundFloatToSInt8().
UInt16 RoundToUInt16 (double Value)
Return a correctly rounded integer result, instead of a truncated result the result returned is limited to the bounds of a unsigned 16-bit integer (0 to 65535)
Parameters
Value is the floating point value to be rounded to an integer.
Returns
The correctly rounded integer.
Referenced by CommBase_SendThrottleTrimPacket(), ConvertFromLegacyTypeToLegacyCameraDef(), FormCameraDefinitionsPacket(), FormDGPSBasePacket(), FormDualAntStatusPacket(), FormGimbalAxisSettingsPacket(), FormGimbalCameraAlignPacket(), FormGimbalHostGPSPacket(), FormGimbalLasersInstalledPacket(), FormGimbalRigTestCmdPacket(), FormGimbalTrackerSettingsAdvancedCommand(), FormGSGPSHealthPacket(), FormGSTelemetryPacket(), FormSPOIPathPointData(), FormTerrainElevationDataPacket(), FormThrottleMinPacket(), and RoundFloatToUInt16().
UInt32 RoundToUInt24 (double Value)
Return a correctly rounded integer result, instead of a truncated result the result returned is limited to the bounds of a unsigned 24-bit integer (0 to 16777215)
Parameters
Value is the floating point value to be rounded to an integer.
Returns
The correctly rounded integer.
Referenced by FormGimbalHostAttitudePacket(), FormGimbalTrackingData(), FormGSGPSHealthPacket(), FormGSTelemetryPacket(), FormSPOIPathPointData(), and RoundFloatToUInt24().
UInt32 RoundToUInt32 (double Value)
Return a correctly rounded integer result, instead of a truncated result the result returned is limited to the bounds of a unsigned 32-bit integer (0 to 4294967295)
Parameters
Value is the floating point value to be rounded to an integer.
Returns
The correctly rounded integer.
Referenced by FormGSTelemetryPacket(), and RoundFloatToUInt32().
UInt8 RoundToUInt8 (double Value)
Return a correctly rounded integer result, instead of a truncated result the result returned is limited to the bounds of a unsigned 8-bit integer (0 to 255)
Parameters
Value is the floating point value to be rounded to an integer.
Returns
The correctly rounded integer.
Referenced by FormActuatorTestPacket(), FormDualAntStatusPacket(), FormGimbalAxisSettingsPacket(), FormGimbalCameraZoomPacket(), FormGimbalCmdPacket(), FormGimbalFilterPacket(), FormGimbalHostGPSPacket(), FormGimbalLasersInstalledPacket(), FormGimbalTrackerSettingsAdvancedCommand(), FormGSRadioSettingsPacket(), FormGSTelemetryPacket(), FormLegacyWaypointPacket(), FormRadioSettingsPacket(), FormSensorErrorPacket(), FormVGSRadioSettings(), FormWaypointsPacket(), and RoundFloatToUInt8().
UInt32 SInt16ToData (UInt8 * pData, SInt16 Value)
Convert a signed 16-bit integer in host byte order into a string of bytes in network byte order.
Parameters
pData points to space to receive a two byte string of data in network byte order
Value is the integer to be encoded.
Returns
Number of bytes required to encode Value.
Referenced by DecodeLensPrefocusPacket(), FormActuatorTablePacket(), FormActuatorTestPacket(), FormBoundaryPacket(), FormDoubletCommandPacket(), FormDualAntStatusPacket(), FormFrameShiftPacket(), FormGimbalAxisSettingsPacket(), FormGimbalCameraAlignPacket(), FormGimbalCameraCmdPacket(), FormGimbalCmdPacket(), FormGimbalFLIRConfigurationPacket(), FormGimbalGPSLeverArmPacket(), FormGimbalHostAttitudePacket(), FormGimbalHostGPSPacket(), FormGimbalHostSensorPacket(), FormGimbalInitialHeadingPacket(), FormGimbalIRCamConfigurationPacket(), FormGimbalRetractorConfigurationPacket(), FormGimbalSensorConfigPacket(), FormGimbalSPOICmdPacket(), FormGimbalTrackCommand(), FormGimbalTrackingData(), FormGSGPSHealthPacket(), FormGSTelemetryPacket(), FormLegacyWaypointPacket(), FormLensCalFocusPacket(), FormLensDevCommandPacket(), FormMissionLimitsPacket(), FormMissionSettingsPacket(), FormScanModeControlPacket(), FormSensorErrorPacket(), FormSimpleLandingPacket(), FormSPOIPathSettings(), FormStabDevT2Settings(), FormVGSAntennaCommand(), and FormVGSAntennaYaw().
UInt32 SInt16ToleData (UInt8 * pData, SInt16 Value)
Convert a signed 16-bit integer in host byte order into a string of bytes in little endian byte order. NOTE: Works on little-endian target only.
Parameters
pData points to space to receive a two byte string of data in little endian byte order
Value is the integer to be encoded.
Returns
Number of bytes required to encode Value.
UInt32 SInt32ToData (UInt8 * pData, SInt32 Value)
Convert a signed 32-bit integer in host byte order into a string of bytes in network byte order.
Parameters
pData points to space to receive a four byte string of data in network byte order
Value is the integer to be encoded.
Returns
Number of bytes required to encode Value.
Referenced by CommBase_SendAirDataZeroPacket(), FormBoundaryPacket(), FormDGPSBasePacket(), FormExternalIOSetupPacketEx(), FormGimbalHostGPSPacket(), FormGimbalSPOICmdPacket(), FormGimbalTargetLocationEstimate(), FormGSGPSHealthPacket(), FormGSTelemetryPacket(), FormLegacyWaypointPacket(), and FormSimpleLandingPacket().
UInt32 SInt32ToleData (UInt8 * pData, SInt32 Value)
Convert a signed 32-bit integer in host byte order into a string of bytes in little endian byte order. NOTE: Works on little-endian target only.
Parameters
pData points to space to receive a four byte string of data in little endian byte order
Value is the integer to be encoded.
Returns
Number of bytes required to encode Value.
UInt32 SInt64ToData (UInt8 * pData, SInt64 Value)
Convert a signed 64-bit integer in host byte order into a string of bytes in network byte order.
Parameters
pData points to space to receive a eight byte string of data in network byte order
Value is the integer to be encoded.
Returns
Number of bytes required to encode Value.
UInt32 UInt16ToData (UInt8 * pData, UInt16 Value)
Convert a unsigned 16-bit integer in host byte order into a string of bytes in network byte order.
Parameters
pData points to space to receive a two byte string of data in network byte order
Value is the integer to be encoded.
Returns
Number of bytes required to encode Value.
Referenced by CommBase_SendBrakesCommandPacket(), CommBase_SendThrottleTrimPacket(), CommBase_SendTrackCommandPacket(), FormActuatorTablePacket(), FormCameraDefinitionsPacket(), FormCanPassthroughPacket(), FormDGPSBasePacket(), FormDoubletCommandPacket(), FormDualAntStatusPacket(), FormECUCommandPacket(), FormFrameShiftPacket(), FormFrequencySweepCommandPacket(), FormGimbalAglPacket(), FormGimbalAxisSettingsPacket(), FormGimbalCameraAlignPacket(), FormGimbalCameraCmdPacket(), FormGimbalFLIRConfigurationPacket(), FormGimbalHostGPSPacket(), FormGimbalHostSensorPacket(), FormGimbalIRCamConfigurationPacket(), FormGimbalLasersInstalledPacket(), FormGimbalRetractorConfigurationPacket(), FormGimbalRigTestCmdPacket(), FormGimbalTrackerSettingsAdvancedCommand(), FormGPSPosVelPacket(), FormGSGPSHealthPacket(), FormGSResetReportPacket(), FormGSSpectrumSweepDetails(), FormGSTelemetryPacket(), FormGSVersionPacket(), FormLaserEnablePswdPacket(), FormLensPrefocusPacket(), FormLensRegisterPacket(), FormMC_DoMotionCalibrationPacket(), FormMISBSettingsPacket(), FormMissionLimitsPacket(), FormSimpleLandingPacket(), FormSPOIPathPointData(), FormSuCsxConfigurationPacket(), FormTerrainElevationDataPacket(), FormThrottleMinPacket(), and FormTransponderControlPacket().
UInt32 UInt16ToleData (UInt8 * pData, UInt16 Value)
Convert a unsigned 16-bit integer in host byte order into a string of bytes in little endian byte order. NOTE: Works on little-endian target only.
Parameters
pData points to space to receive a two byte string of data in little endian byte order
Value is the integer to be encoded.
Returns
Number of bytes required to encode Value.
UInt32 UInt24ToData (UInt8 * pData, UInt32 Value)
Convert a unsigned 24-bit integer in host byte order into a string of bytes in network byte order.
Parameters
pData points to space to receive a three byte string of data in network byte order
Value is the integer to be encoded.
Returns
Number of bytes required to encode Value.
Referenced by FormGimbalHostAttitudePacket(), FormGimbalTrackingData(), FormGimbalWaterMarkPacket(), FormGSGPSHealthPacket(), FormGSTelemetryPacket(), FormSPOIPathPointData(), FormTransponderInstallationPacket(), and FormWaypointListPacket().
UInt32 UInt32ToData (UInt8 * pData, UInt32 Value)
Convert a unsigned 32-bit integer in host byte order into a string of bytes in network byte order.
Parameters
pData points to space to receive a four byte string of data in network byte order
Value is the integer to be encoded.
Returns
Number of bytes required to encode Value.
Referenced by FloatToData(), FormAltimeterSettingPacket(), FormControllerDataPacket(), FormDualAntStatusPacket(), FormGimbalHostAttitudePacket(), FormGimbalHostGPSPacket(), FormGimbalHostSensorPacket(), FormGimbalSensorConfigPacket(), FormGimbalTargetLocationEstimate(), FormGSResetReportPacket(), FormGSTelemetryPacket(), FormGSVersionPacket(), FormLensRegisterPacket(), FormMISBSettingsPacket(), FormMissionLimitsPacket(), FormMissionSettingsPacket(), FormSPOIPathSettings(), FormTerrainElevationDataPacket(), FormWaypointListRangePacket(), and FormWaypointsPacket().
UInt32 UInt32ToleData (UInt8 * pData, UInt32 Value)
Convert a unsigned 32-bit integer in host byte order into a string of bytes in little endian byte order. NOTE: Works on little-endian target only.
Parameters
pData points to space to receive a four byte string of data in little endian byte order
Value is the integer to be encoded.
Returns
Number of bytes required to encode Value.
Referenced by FloatToleData().
UInt32 UInt64ToData (UInt8 * pData, UInt64 Value)
Convert a unsigned 64-bit integer in host byte order into a string of bytes in network byte order.
Parameters
pData points to space to receive a eight byte string of data in network byte order
Value is the integer to be encoded.
Returns
Number of bytes required to encode Value.
Referenced by DoubleToData(), and FormVps3OverlaySettings().
UInt32 UInt64ToleData (UInt8 * pData, UInt64 Value)
Convert a unsigned 64-bit integer in host byte order into a string of bytes in little endian byte order. NOTE: Works on little-endian target only.
Parameters
pData points to space to receive a eight byte string of data in little endian byte order
Value is the integer to be encoded.
Returns
Number of bytes required to encode Value.
Referenced by DoubleToleData().