Communications SDK: UdpAutoDetector Class Reference
UdpAutoDetector Class Reference
Class for automatically detecting a UDP server.
#include <UdpAutoDetector.h>
Public Member Functions
UdpAutoDetector (void)
Constructor.
~UdpAutoDetector (void)
Destructor.
std::string getLastError (void)
Get the last returned error condition (TBD)
BOOL checkForNewServers (UdpServerType_t Filter, UdpServerFlag_t Flags)
Check for any new UDP servers.
UdpServerList_t getServerList (void)
Get the current list of UDP servers on the subnet.
Detailed Description
Class for automatically detecting a UDP server.
Constructor & Destructor Documentation
UdpAutoDetector::UdpAutoDetector (void)
Constructor.
Construct an auto-detector object. This will open the appropriate sockets and initialize the packet processing data.
UdpAutoDetector::~UdpAutoDetector (void)
Destructor.
Destruct a UDP auto-detection object.
Member Function Documentation
BOOL UdpAutoDetector::checkForNewServers (UdpServerType_t Types, UdpServerFlag_t Flags)
Check for any new UDP servers.
Check for any new servers that have appeared on the network. Call this function periodically to search for UDP servers - it's probably not necessary to call this function more frequently than about 1 Hz.
Parameters
Filter Sets the types of servers to check for.
Returns
Returns TRUE if new server information was found, otherwise FALSE.
References UdpServer_t::Address, StreamPkt_t::Data, DecodeGSNamePacket(), StreamPkt_t::DestHi, StreamPkt_t::DestLo, GS_STREAM, LookForGroundStationPacketInByte(), LookForStreamPacketInByte(), UdpServer_t::Name, OI_ADDRESS, UdpServer_t::Port, StreamPkt_t::Size, StreamPkt_t::Stream, and UdpServer_t::TimeStamp.
Referenced by getLastError(), and getServerList().
std::string UdpAutoDetector::getLastError (void) inline
Get the last returned error condition (TBD)
References checkForNewServers().
UdpServerList_t UdpAutoDetector::getServerList (void) inline
Get the current list of UDP servers on the subnet.
References checkForNewServers().
The documentation for this class was generated from the following files:
UdpAutoDetector.h
UdpAutoDetector.cpp