Communications SDK: CctSocket Class Reference
CctSocket Class Reference
#include <CctSocket.h>
Public Member Functions
CctSocket (void)
Constructor.
~CctSocket (void)
Destructor.
BOOL open (UInt32 Address, SocketType_t Type, UInt16 RemotePort, UInt16 LocalPort, UInt32 TxBufSize, UInt32 RxBufSize)
Open a new socket.
void close (void)
Close this socket.
BOOL isOpen (void)
Test for.
SInt32 read (UInt8 *pData, UInt32 MaxLength)
Read bytes from an opened socket.
SInt32 write (UInt8 *pData, UInt32 Length, BOOL More)
Write bytes to an opened socket.
Protected Attributes
struct sockaddr_in * m_pTxSockAddr
UInt32 m_Handle
SocketType_t m_Type
Queue_t * m_pRxQ
Queue_t * m_pTxQ
UInt8 * m_pRxBuf
UInt8 * m_pTxBuf
Detailed Description
IP socket interface class.
Constructor & Destructor Documentation
CctSocket::CctSocket (void)
Constructor.
Constructs a new instance of the socket interface class.
CctSocket::~CctSocket (void)
Destructor.
Destructs an instance of the socket interface class.
References close().
Member Function Documentation
void CctSocket::close (void)
Close this socket.
Close this socket and clean up all of the internal class data.
References DestroyQ(), and SOCKET_TYPE_NULL.
Referenced by ~CctSocket().
BOOL CctSocket::isOpen (void) inline
Test for.
References read(), SOCKET_TYPE_NULL, and write().
BOOL CctSocket::open (UInt32 Address, SocketType_t Type, UInt16 RemotePort, UInt16 LocalPort, UInt32 TxBufSize, UInt32 RxBufSize)
Open a new socket.
Open a new socket with a given set of parameters.
Parameters
Address The 32-bit IPv4 address to connect to.
Type Socket type specifier (TCP, UDP, etc).
RemotePort IP port on the remote host to send packets to.
LocalPort IP port on the local host to receive packets from.
TxBufSize The maximum number of bytes to buffer locally before sending a consolidated packet.
RxBufSize The maximum number of bytes to buffer locally upon receipt.
Returns
TRUE if the socket was successfully opened, otherwise FALSE.
References CreateQ(), SOCKET_TYPE_TCP, and SOCKET_TYPE_UDP.
SInt32 CctSocket::read (UInt8 * pData, UInt32 MaxLength)
Read bytes from an opened socket.
Read a series of bytes from a previously opened socket.
Parameters
pData A pointer to an array which can receive data from the socket.
MaxLength The maximum number of bytes that can fit in the array pointed to by pData.
Returns
The number of bytes read from the socket, or -1 if an error occurred.
References BlockDeQ(), BlockEnQ(), QAvailable(), Queue_t::Size, SOCKET_TYPE_TCP, and SOCKET_TYPE_UDP.
Referenced by isOpen().
SInt32 CctSocket::write (UInt8 * pData, UInt32 Length, BOOL More)
Write bytes to an opened socket.
References BlockDeQ(), BlockEnQ(), QAvailable(), QHolding(), Queue_t::Size, SOCKET_TYPE_TCP, and SOCKET_TYPE_UDP.
Referenced by isOpen().
The documentation for this class was generated from the following files:
CctSocket.h
CctSocket.cpp