Communications SDK: CCommManager Class Reference
CCommManager Class Reference
#include <CommManager.h>
Public Member Functions
CCommManager (const char *ReplayFile, int ListenPort=-1)
CCommManager (int chan, const char *ServerAddress="", int Port=-1, BOOL EnableLogging=TRUE, const char *pIridiumNumber=NULL, const char *pLogPath=NULL, BOOL ListenOnly=FALSE)
CCommManager (int chan, UInt32 baud, const char *ServerAddress="", int Port=-1, BOOL EnableLogging=TRUE, const char *pIridiumNumber=NULL, const char *pLogPath=NULL, BOOL ListenOnly=FALSE)
~CCommManager (void)
void ChangeLogFile (BOOL EnableLogging=TRUE, const char *pLogPath=NULL)
Change, restart, or stop the log file.
BOOL NewSerialPortConfiguration (int chan, UInt32 baud, const char *pIridiumNumber=NULL, BOOL EnableLogging=TRUE, const char *pLogPath=NULL, BOOL ListenOnly=FALSE)
Change the serial port configuration.
BOOL NewNetworkClientConfiguration (const char *ServerAddress, BOOL EnableLogging=TRUE, const char *pLogPath=NULL, BOOL ListenOnly=FALSE)
Change the network client configuration.
BOOL NewReplayFileConfiguration (const char *ReplayFile)
Change the replay file configuration.
BOOL NewNetworkServerConfiguration (int ListenPort)
Change the network server configuration.
BOOL GetSerialPortConfiguration (UInt8 *chan, UInt32 *baud)
Return the current serial port parameters.
BOOL GetSatCommConfiguration (std::string &Number)
Return the current Iridium configuration.
BOOL GetNetworkClientConfiguration (std::string &ServerAddress)
Return the network client parametes.
BOOL GetReplayFileConfiguration (std::string &ReplayFile)
Return the replay file name.
int GetNetworkServerConfiguration (void)
Return the network server configuration.
void GetVersionInformation (Version_t *pVersion)
Get the version of the communications manager software.
void SetNewNetworkCallBack (void(*NewNetworkCallBack)(UInt16 NetworkID, void *Parameter), void *Parameter)
Register the call back function for new networks.
Queue_t * GetStreamRxBuffer (UInt16 NetworkID, UInt8 Stream)
Get stream receive pointer.
Queue_t * GetStreamTxBuffer (UInt16 NetworkID, UInt8 Stream)
Get stream transmit pointer.
Queue_t * GetUserLogBuffer (void)
Get user log buffer pointer.
void RunNetwork (void)
Call periodically to service the communications.
void SendAutopilotPacket (UInt16 NetworkID, const AutopilotPkt_t *pPkt)
Send a autopilot packet.
void SendZeroLengthAutopilotPacket (UInt16 NetworkID, UInt8 PktType)
Send a zero length autopilot packet.
void SendGroundStationPacket (const GroundStationPkt_t *pPkt)
Send an groundstation packet.
void SendZeroLengthGroundStationPacket (UInt8 PktType)
Send a zero length ground station packet.
void SendGimbalPacket (UInt16 NetworkID, const GimbalPkt_t *pPkt)
Send a gimbal packet on the gimbal stream to the autopilot.
void SendBlock (UInt16 NetworkID, UInt8 Stream, UInt8 *pData, UInt32 Size)
Send a block of data in a packet.
void SendStreamPacket (StreamPkt_t *pPkt)
Send a low level packet of data.
void LogUserData (UInt8 *pData, UInt32 Size)
Write a block of custom user data to the telemetry file.
SInt32 CreateNetwork (UInt16 NetworkID)
Creates a network.
void DestroyNetwork (UInt16 NetworkID)
Destroys a network.
void DestroyAllNetworks (void)
Destroys all networks.
UInt32 GetNumNets (void)
Get the number of networks that exist.
SInt32 GetIDFromIndex (UInt32 index)
Get the network IDs that are stored by the comm manager.
SInt32 GetIndexFromID (UInt16 NetworkID)
Get the index into a network from ID.
void PauseReplay (void)
Disable the replay.
void ResumeReplay (void)
Enable the replay.
BOOL IsInReplay (void)
Return the state of the replay mode flag.
BOOL IsInListenOnly (void)
Return the state of listen only mode flag.
UInt32 GetNumStreamBytes (void)
Get the number of bytes read from the groundstation or from the relplay.
UInt32 GetFileSize (void)
Get the size of the log or replay file.
UInt32 GetReplayFileLocation (void)
Get the location of the file position.
void SetReplayFileLocation (UInt32 location)
Set the location of the file position.
void SetReplayRate (UInt32 ReplayRate)
Set the current replay rate.
UInt32 GetReplayRate (void)
Get the replay rate.
const char * GetLastError (void)
Get the last error information.
void ClearLastError (void)
Clear the error string.
float ComputeDownlinkPercent (UInt16 NetworkID)
Compute the downlink percentage for a specific network.*/.
size_t GetSatcommStatusString (char *pString, size_t count)
Get satcomm dialer status string.
size_t GetSatcommErrorString (char *pString, size_t count)
Get satcomm dialer error string.
void HangUpSatcommRedial (void)
Hang up satcomm and redial.
void HangUpSatcommIdle (void)
Hang up satcomm and go to an idle state.
void StartDialingSatcomm (void)
Start the dialing sequence.
void SetSatcommPhoneNumber (const char *pPhoneNum)
Set/change the satcomm phone number.
void SendUserActionPacket (UInt16 NetworkID, UInt8 ActionIndex, BOOL On)
Create and send a user action command packet.
void SendConfigurationLockPacket (UInt16 NetworkID, const char Password[32]=NULL)
Create and send a configuration lock packet.
void SendConfigurationUnlockPacket (UInt16 NetworkID, const char Password[32]=NULL, BOOL Silent=FALSE)
Create and send a configuration unlock packet.
void SendControllerDataPacket (UInt16 NetworkID, UInt8 Controller, UInt8 Version, UInt8 Category, UInt8 DataID, UInt8 NumData, const void *pData)
Create and send a controller packet.
void SendControllerDataDefaultPacket (UInt16 NetworkID, UInt8 Controller, UInt8 Version, UInt8 Category, UInt8 DataID, UInt8 NumData)
Create and send a controller packet to default data.
void SendTransponderControlPacket (UInt16 NetworkID, UInt16 Code, BOOL Ident, UInt8 Mode)
Create and send a transponder control packet.
void SendTransponderPreflightPacket (UInt16 NetworkID, const char FlightID[9])
Create and send a transponder preflight packet.
void SendTransponderInstallationPacket (UInt16 NetworkID, UInt32 ICAOAddress, const char Registration[9])
Create and send a transponder installation packet.
void SendRadioSettingsPacket (UInt16 NetworkID, const RadioSettings_t *pSettings)
Create and send a radio settings packet.
void SendAutopilotLoopControlPacket (UInt16 NetworkID, const AutopilotLoopCmd_t *pCmd, BOOL UpdateEEPROM=TRUE)
Create and send a autopilot loop control packet.
void SendActuatorTablePacket (UInt16 NetworkID, const ActuatorTable_t *pTable, UInt8 Sur, UInt8 Type, UInt8 Virtual, UInt8 Fast)
Create and send a control actuator calibration packet.
void SendActuatorTypePacket (UInt16 NetworkID, UInt8 Sur, UInt8 Type)
Create and send a packet to change actuator type.
void SendOrientationPacket (UInt16 NetworkID, const float Euler[NAXIS], const float IMUtoAnt[N3D], const float IMUtoAnt2[N3D])
Create and send a sensor orientatin packet.
void SendWaypointsPacket (UInt16 NetworkID, const FPPoint_t Points[MAX_WAYPOINTS_IN_PACKET], UInt16 Num, BOOL Ack)
Create and send waypoints packet.
void SendWaypointListPacket (UInt16 NetworkID, const FPMask_t Mask, UInt8 Flag)
Create and send a waypoint list packet.
void SendWaypointListRangePacket (UInt16 NetworkID, UInt16 Start, UInt16 End, UInt8 Flag)
Create and send a waypoint list packet using a range of points.
void SendLegacyWaypointPacket (UInt16 NetworkID, const FPPoint_t *pPoint, UInt8 Index)
Create and send a legacy waypoint packet.
void SendLegacyWaypointListPacket (UInt16 NetworkID, const FPMask_t Mask, UInt8 Flag)
Create and send a legacy waypoint list packet.
void SendSurfaceTestPacket (UInt16 NetworkID, float Angle, float Width, float Freq, float Dev, UInt8 Index)
Create and send a surface test packet.
void SendMissionLimitsPacket (UInt16 NetworkID, const MissionLimits_t *pMission)
Create and send a mission limits packet.
void SendMissionSettingsPacket (UInt16 NetworkID, SInt16 MinAltitude, SInt16 MaxAltitude, UInt32 FlightTimeout)
Create and a send a mission settings packet.
void SendBoundaryPacket (UInt16 NetworkID, const Boundary_t *pBnd)
Create and send a airspace boundary packet.
void SendMagCalPacket (UInt16 NetworkID, const float HardIronErr[N3D], const float ScaleFactErr[N3D])
Create and send a magnetic sensor calibration packet.
void SendSensorErrorPacket (UInt16 NetworkID, const SensorErrorData_t *pSensorError)
Create and send a sensor error.
void SendExternalSerialSetupPacket (UInt16 NetworkID, const ExternalSerial_t *pSerial)
Create and send a external serial setup packet.
void SendExternalIOSetupPacket (UInt16 NetworkID, const ExternalIO_t *pExternalIO, UInt8 pin, UInt32 SampleTime, BOOL UpdateEEPROM=TRUE)
Create and send a external IO setup packet.
void SendSimpleLandingPacket (UInt16 NetworkID, const SimpleLandingPattern_t *pLand)
Create and send a simple landing packet.
void SendAltimeterSettingPacket (UInt16 NetworkID, UInt32 Altimeter, BOOL ControlToGPS)
Create and send an altimeter setting packet.
void SendBandwidthModePacket (UInt16 NetworkID, BandwidthMode_t Bandwidth)
Create and send a bandwidth mode packet.
void SendEngineKillPacket (UInt16 NetworkID, BOOL EngineKill)
Create and send the engine kill packet.
void SendLandNowPacket (UInt16 NetworkID)
Create and send the land now command packet.
void SendLaunchNowPacket (UInt16 NetworkID)
Create and send the launch now command packet.
void SendPrelaunchPacket (UInt16 NetworkID)
Create and send the go to prelaunch command packet.
void SendAirDataZeroPacket (UInt16 NetworkID, float ActualAltitude)
Create and send the zero air data command packet.
void SendManualAssistModePacket (UInt16 NetworkID, UInt8 Mode)
Create and send the manual assist mode command packet.
void SendLightsCommandPacket (UInt16 NetworkID, BOOL LightsOn)
Create and send the lights command packet.
void SendDropCommandPacket (UInt16 NetworkID, BOOL DropOn)
Create and send the drop command packet.
void SendParachuteCommandPacket (UInt16 NetworkID, BOOL ParachuteDeploy)
Create and send the parachute command packet.
void SendBrakesCommandPacket (UInt16 NetworkID, float Brakes)
Create and send the brakes command packet.
void SendThrottleTrimPacket (UInt16 NetworkID, float Throttle)
Create and send the throttle trim command packet.
void SendTrackCommandPacket (UInt16 NetworkID, UInt16 Waypoint, BOOL GoTo)
Create and send a track command packet.
void SendDescriptionPacket (UInt16 NetworkID, const char Description[64])
Create and send a parameter description packet.
void SendUserSpacePacket (UInt16 NetworkID, const UInt8 User[64])
Create and send a user space packet.
void SendDoubletCommandPacket (UInt16 NetworkID, const DoubletCmd_t *pDoublet)
Create and send a doublet command packet.
void SendFrequencySweepCommandPacket (UInt16 NetworkID, const FrequencySweepCmd_t *pFreqSwp)
Create and send a frequency sweep command packet.
void SendSetFuelLevelPacket (UInt16 NetworkID, float Fuel, BOOL Electric)
Create and send a set fuel level packet.
void SendSetFuelIfLockedPacket (UInt16 NetworkID, float Fuel, BOOL Electric)
Create and send a set fuel level packet for fuel update while locked.
void SendPayloadMassPacket (UInt16 NetworkID, float PayloadMass)
Create and send a payload mass packet.
void SendThrottleMinPacket (UInt16 NetworkID, float Throttle)
Create and send a throttle min packet.
void SendFeatureCodePacket (UInt16 NetworkID, const UInt8 Data[8])
Create and send a feature code packet.
void SendTerrainElevationDataPacket (UInt16 NetworkID, UInt32 Time, float Elevations[6])
Create and send terrain elevation information.
void RequestControllerDataPacket (UInt16 NetworkID, UInt8 Controller, UInt8 Version, UInt8 Category, UInt8 DataID, UInt8 NumData)
Request some controller data.
void RequestTransponderControlPacket (UInt16 NetworkID)
Request the transponder control packet.
void RequestTransponderPreflightPacket (UInt16 NetworkID)
Request the transponder preflight packet.
void RequestTransponderInstallationPacket (UInt16 NetworkID)
Request the transponder installation packet.
void RequestRadioSettingsPacket (UInt16 NetworkID)
Request the radio settings packet.
void RequestActuatorTablePacket (UInt16 NetworkID, UInt8 Sur)
Request the autopilot surface table calibration packet.
void RequestOrientationPacket (UInt16 NetworkID)
Request the autopilot orientation packet.
void RequestMissionLimitsPacket (UInt16 NetworkID)
Request the autopilot mission limits packet.
void RequestMagCalPacket (UInt16 NetworkID)
Request the packet with the magnetometer calibration data.
void RequestSensorErrorPacket (UInt16 NetworkID)
Request the packet with the sensor error data.
void RequestExternalSerialSetupPacket (UInt16 NetworkID)
Request the autopilot packet with the external serial setup parameters.
void RequestExternalIOSetupPacket (UInt16 NetworkID, UInt8 pin)
Request then autopilot packet with the setup parameters for a single external IO pin.
void RequestDescriptionPacket (UInt16 NetworkID)
Request the parameter description packet.
void RequestUserSpacePacket (UInt16 NetworkID)
Request the user space packet.
void RequestAltimeterSettingPacket (UInt16 NetworkID)
Request the altimeter setting packet.
void RequestBandwidthModePacket (UInt16 NetworkID, UInt8 NetID)
Request the bandwidth mode packet.
void RequestSystemVersionPacket (UInt16 NetworkID)
Request system version packet.
void RequestRawVibrationDataPacket (UInt16 NetworkID)
Request the raw vibration sensor data.
void RequestPayloadMassPacket (UInt16 NetworkID)
Request the payload mass packet.
void RequestThrottleMinPacket (UInt16 NetworkID)
Request the throttle min packet.
void SendGSAddAddressPacket (UInt16 Address)
Create and send a ground station add address packet.
void SendGSAddPilotAddressPacket (UInt16 Pilot)
Create and send a ground station add pilot address packet.
void SendGSDeleteAddressPacket (UInt16 DelAddress, UInt16 KeepAddress=0)
Create and send a ground station delete address packet.
void SendGSRadioSettingsPacket (const RadioSettings_t *pSettings)
Create and a ground station radio settings packet.
void SendDGPSBasePacket (const DGPSParameter_t *pDGPS)
Create and send a ground station differential corrections packet.
void SendGSDynamicEnumerationPacket (BOOL On)
Create and send a dynamic enumeration on/off packet.
void SendGSConfiguration (UInt8 ConfigEnum, UInt8 SBASDisable, UInt8 EnableGD, UInt32 Baud, UInt8 EnableMHXRelay)
Create and send a ground station configuration packet.
void RequestGSRadioSettingsPacket (void)
Request ground station radio settings.
void RequestGSSpectrumSweepPacket (float StartFreq, float Spacing, UInt16 Dwell, UInt8 NumMeasurements)
Request ground station spectrum sweep, coherent frequency radio.
void RequestGSSpectrumSweepPacket (void)
Request ground station spectrum sweep, hopping radio.
void RequestGSFirmwarePacket (void)
Request the software and hardware configuration settings from the ground station.
void RequestDGPSBasePacket (void)
Request the packet with DGPS base settings.
void RequestGimbalSPOICmdPacket (UInt16 NetworkID)
Request a sensor point of interest command packet.
void SendGimbalCmdPacket (UInt16 NetworkID, float Pan, float Tilt, SInt8 ZoomRate, float CamTimeout, UInt8 Flags, float ImpulseTime, SInt8 FocusRate=0, UInt8 Flags1=0)
Create and send a gimbal command packet containing pan, tilt, zoom and focus rate, and mode.
void SendGimbalSPOICmdPacket (UInt16 NetworkID, const double Pos[NPOS], const float Vel[NDIR], UInt8 Flags)
Create and send a gimbal sensor point of interest packet containing the position of the SPOI.
void SendGimbalCameraCmdPacket (UInt16 NetworkID, UInt8 Camera, float HFOV, UInt16 Focus, UInt8 Mode, UInt8 Shutter, UInt8 Bright, UInt8 Flags)
Create and send a camera command packet.
void SendGimbalAxisSettingsPacket (UInt16 NetworkID, const float NoGoCenter[NGIMBAL_SHORT], const float NoGoRange[NGIMBAL_SHORT], const float MaxRate[NGIMBAL_SHORT], const float MaxAccel[NGIMBAL_SHORT], const float PosGain[NGIMBAL_SHORT], const float VelGain[NGIMBAL_SHORT], const float DerGain[NGIMBAL_SHORT], BOOL Temporary=FALSE, BOOL Factory=FALSE)
Create and send a gimbal axis settings packet.
void SendGimbalSerialInterfacePacket (UInt16 NetworkID, GimbalSerial_t Serial[6], BOOL Temporary)
Create and send gimbal packet rate packet.
void SendGimbalCameraAlignPacket (UInt16 NetworkID, float Zoom1, const float Error1[NGIMBAL], float Zoom2, const float Error2[NGIMBAL], UInt8 Camera, BOOL Factory=FALSE)
Create and send gimbal camera alignment packet.
void SendGimbalCameraTypesPacket (UInt16 NetworkID, const CameraDefinition_t Cam[NUM_CAMERAS], const BOOL Send[NUM_CAMERAS], BOOL Factory=FALSE)
Create and send gimbal camera definitions packet.
void SendGimbalLaserSetupPacket (UInt16 NetworkID, LaserSetup_t Lasers[NUM_LASERS], BOOL Factory=FALSE)
Create and send gimbal laser setup packet.
void SendGimbalLaserArmPacket (UInt16 NetworkID, UInt8 LaserIndex, BOOL Arm)
Create and send gimbal laser arm packet.
void SendGimbalLaserFirePacket (UInt16 NetworkID, UInt8 LaserIndex, UInt8 Power)
Create and send gimbal laser fire packet.
void SendGimbalRetractDeployCmdPacket (UInt16 NetworkID, UInt32 Deploy)
Create and send gimbal retract/deploy command.
void SendGimbalTrackCmdPacket (UInt16 NetworkID, float InitialX, float InitialY, UInt8 Algorithm, UInt8 Size, UInt8 Stamp)
Create and send gimbal track command packet.
void RequestGimbalCameraCmdPacket (UInt16 NetworkID, UInt8 Camera)
Request a camera command packet.
void RequestGimbalAxisSettingsPacket (UInt16 NetworkID, BOOL Factory=FALSE)
Request a gimbal axis settings packet.
void RequestGimbalCameraAlignPacket (UInt16 NetworkID, UInt8 Camera, BOOL Factory=FALSE)
Request camera alignment information.
void RequestGimbalCameraTypesPacket (UInt16 NetworkID, BOOL Factory=FALSE)
Request gimbal camera types.
void RequestGimbalLaserSetupPacket (UInt16 NetworkID, BOOL Factory=FALSE)
Request gimbal laser setup.
BOOL WriteTextLogHeader (FILE *pFile)
Write the header for the log file.
BOOL WriteTextLogLine (FILE *pFile, const UserData_t *pData, UInt8 AckRatio, const double TrackPosition[N3D]=NULL, const float TrackVelocity[N3D]=NULL, const float ADCSample[NUM_EXTERNAL_ADC_PINS]=NULL, const ECU_t *pLeftECU=NULL, const ECU_t *pRightECU=NULL, const MovingBaseStatus_t *pMBStatus=NULL, const GPSUser_t *pGSGPS=NULL, float GSRSSI=0.0f, float GSPilotPercentage=0.0f, float GSPilotRate=0.0f)
Write a single line of data for the log file.
Detailed Description
Communications manager class
Constructor & Destructor Documentation
CCommManager::CCommManager (const char * ReplayFile, int ListenPort = -1)
Construct the CommManager and setup the input/output system. This version of the communications manager is used for replay mode. In replay mode bytes are read from a file rather than from the serial port or socket.
Parameters
ReplayFile is the name of the file containing the data to be replayed.
ListenPort specifies the port number to listen on for a server.
   Pass a port number greater than 1023 to enable this communications
   manager to be a server.  It will listen for incoming TCP connections
   on this port and establish connnections.  As a server the comm
   manager will route data between the serial port connected to a
   groundstation and any of the client TCP connections.
References CommBase_OpenReplay().
CCommManager::CCommManager (int chan, const char * ServerAddress = "", int ListenPort = -1, BOOL EnableLogging = TRUE, const char * pIridiumNumber = NULL, const char * pLogPath = NULL, BOOL ListenOnly = FALSE)
Construct the CommManager and setup the input/output system.
Parameters
chan is the identifier of the serial port to use (COM1, COM2, etc), or -1 to autodetect the USB-Serial ground station port.
ServerAddress is a character string describing the TCP/IP network address and port number of a communications server. The address can be in dotted decimal form ("192.168.0.1:2000"), or it can be a host name ("www.mydomain.com:Port"), or it can contain a local host name ("Server:Port"). If the communications manager succeeds in connecting to the server it will not open the serial port indicated by the first parameter. If you don't want to connect to a server pass a NULL pointer or a zero-length string ("").
ListenPort specifies the port number to listen on for a server. Pass a port number greater than 1023 to enable this communications manager to be a server. It will listen for incoming TCP connections on this port and establish up to 10 concurrent connections. As a server the communications manager will route data between the serial port connected to a groundstation and any of the client TCP connections. If this parameter is valid then ServerAddress is ignored.
EnableLogging specifies whether the communications manager records a log file of data received from the ground station.
pIridiumNumber points to a string containing the Iridium phone number to be dialed.
pLogPath points to the path to write log files to.
listenOnly flag is the communications is read-only (no uplink)
References CommBase_OpenSerial(), and CommBase_OpenSocket().
CCommManager::CCommManager (int chan, UInt32 baud, const char * ServerAddress = "", int ListenPort = -1, BOOL EnableLogging = TRUE, const char * pIridiumNumber = NULL, const char * pLogPath = NULL, BOOL ListenOnly = FALSE)
Communications manager constructor which supports iridium functionality. The Iridium functionality maintains an Iridium dialing state machine, assuming the Iridium modem is directly connected to the serial port.
Parameters
chan specifies the com port number. If chan is -1 then this function tries to autodetect the USB serial module com port reserved for Iridium.
baud is the baud rate to use for the serial port.
ServerAddress is a character string describing the TCP/IP network address and port number of a communications server. The address can be in dotted decimal form ("192.168.0.1:2000"), or it can be a host name ("www.mydomain.com:Port"), or it can contain a local host name ("Server:Port"). If the communications manager succeeds in connecting to the server it will not open the serial port indicated by the first parameter. If you don't want to connect to a server pass a NULL pointer or a zero-length string ("").
ListenPort specifies the port number to listen on for a server. Pass a port number greater than 1023 to enable this communications manager to be a server. It will listen for incoming TCP connections on this port and establish connnections. As a server the comm manager will route data between the serial port connected to a groundstation and any of the client TCP connections. If this parameter is valid then ServerAddress is ignored.
EnableLogging specifies whether the communications manager records a log file of data received from the ground station.
pIridiumNumber points to a string containing the Iridium phone number to be dialed.
pLogPath points to the path to write log files to.
listenOnly flag is the communications is read-only (no uplink)
References CommBase_OpenSerial(), and CommBase_OpenSocket().
CCommManager::~CCommManager (void)
Closes any open communications resources
References CommBase_Close().
Member Function Documentation
void CCommManager::ChangeLogFile (BOOL EnableLogging = TRUE, const char * pLogPath = NULL)
Change, restart, or stop the log file.
Change the binary log file. This function can be used to close and re-open the log file, in the same or different location. This function can also be used to stop or start logging.
Parameters
EnableLogging should be TRUE to enable the binary logging.
pLogPath specifies the path touse for the log file. If NULL then the current working directory is used.
References CommBase_ChangeLogFile().
void CCommManager::ClearLastError (void)
Clear the error string.
Clear the comm managers error string.
References CommBase_ClearLastError().
float CCommManager::ComputeDownlinkPercent (UInt16 NetworkID)
Compute the downlink percentage for a specific network.*/.
Compute the downlink percentage for a specific network. This is the percentage of successfully received data to the amount expected. This function should only be called every 5 seconds or so, to make sure that enough data have been received to make a good computation. If no data have been received then this function will return 100%. If the network does not exist this function will return 0%. Note that this data can also be computed by the ground station and returned in groundstation telemetry.
Parameters
NetworkID is the destination address of the network.
Returns
The downlink percentage from 0 to 100.
References CommBase_ComputeDownlinkPercent().
SInt32 CCommManager::CreateNetwork (UInt16 NetworkID)
Creates a network.
Create a new network structure for the passed network address. If successful this function returns the internal index of the network structure. Else -1 is returned. If the network already exists then this function will return the current index, without creating a new network structure. This function is used internally by the communications manager, and is only made public for advanced users. Normally you rely on the communications manager to automatically create the network when a new avionics is detected. If this function is called the communications manager will NOT call the NewNetworkCallBack function when the first packet from the avionics arrives.
Parameters
NetworkID is the destination address of the network structure to be created.
Returns
The internal index of the network structure. -1 if an error.
References CommBase_CreateNetwork().
void CCommManager::DestroyAllNetworks (void)
Destroys all networks.
Find and remove all of the network data structures that are held by the communications manager. After calling this function all of the network data will be released, including any stream receive queues. If a new avionics packet is received from the ground station then the relevant network will be created anew and the new network call back function will be called again.
References CommBase_DestroyAllNetworks().
void CCommManager::DestroyNetwork (UInt16 NetworkID)
Destroys a network.
Find and remove the network data structures for the passed network address. After calling this function the network data will be released, including any stream receive queues. If a new packet for this network is received from the ground station then the network will be created anew and the new network call back function will be called again.
Parameters
NetworkID is the destination address of the network structure to be destroyed.
References CommBase_DestroyNetwork().
UInt32 CCommManager::GetFileSize (void)
Get the size of the log or replay file.
Get the number of bytes in the replay file, or in the log file if not in replay mode
Returns
The number of bytes in the replay or log file
References CommBase_GetFileSize().
SInt32 CCommManager::GetIDFromIndex (UInt32 index)
Get the network IDs that are stored by the comm manager.
Return the network address for a network structure identified by the passed index. The index refers to the internal array of network structures. This function is typically used with the GetNumNets function in order to enumerate all of the network addresses that the communications manager has.
Parameters
index is the index to the communications manager's internal array of network structures.
Returns
The network address indexed network. -1 is returned if the network doesn't exist.
References CommBase_GetIDFromIndex().
SInt32 CCommManager::GetIndexFromID (UInt16 NetworkID)
Get the index into a network from ID.
Return the internal index of a network structure identified by the passed
network address. The returned index refers to the internal array of network structures.
Parameters
NetworkID is the destination address of the network whose internal index is to be returned.
Returns
The internal index of the network structure. -1 is returned if the network doesn't exist.
References CommBase_GetIndexFromID().
const char * CCommManager::GetLastError (void)
Get the last error information.
Retrieve a string that describes the last error reported by the comm manager. If no error has occurred then NULL will be returned. The pointer returned references memory space allocated within the comm manager.
Returns
A pointer to a string containing the last error. NULL is returned if no errors have been encountered.
References CommBase_GetLastError().
BOOL CCommManager::GetNetworkClientConfiguration (std::string & ServerAddress)
Return the network client parametes.
Get the network client parametes. The parameters are returned as a string with the format "Server:Port".
Parameters
ServerAddress references space to recieve teh network client parameters.
Returns
TRUE if a network client, else FALSE, in which case ServerAddress will be empty.
References CommBase_GetNetworkClientConfiguration().
int CCommManager::GetNetworkServerConfiguration (void)
Return the network server configuration.
Return the network server configuration
Returns
the port this comm manager is listening on, or -1 if not a server.
References CommBase_GetNetworkServerConfiguration().
UInt32 CCommManager::GetNumNets (void)
Get the number of networks that exist.
Return the number of networks that the communications manager has in memory
Returns
The number of networks.
References CommBase_GetNumNets().
UInt32 CCommManager::GetNumStreamBytes (void)
Get the number of bytes read from the groundstation or from the relplay.
Get the number of bytes read from the groundstation or from the replay file
Returns
The number of bytes read from the ground station or replay file
References CommBase_GetNumStreamBytes().
BOOL CCommManager::GetReplayFileConfiguration (std::string & ReplayFile)
Return the replay file name.
Get the replay file name being used by the communications manager
Parameters
ReplayFile references space to receive the file name.
Returns
TRUE if in replay mode, else FALSE, in which case ReplayFile will be empty.
References CommBase_GetReplayFileConfiguration().
UInt32 CCommManager::GetReplayFileLocation (void)
Get the location of the file position.
Get the location of the replay file position
Returns
the replay file position
References CommBase_GetReplayFileLocation().
UInt32 CCommManager::GetReplayRate (void)
Get the replay rate.
Get the current replay rate in bytes per second
Returns
The replay rate in bytes per second.
References CommBase_GetReplayRate().
BOOL CCommManager::GetSatCommConfiguration (std::string & Number)
Return the current Iridium configuration.
Get the current satellite communications configuration
Parameters
Number references space to receive the phone number in use.
Returns
TRUE if a Iridium is enabled, else FALSE
References CommBase_GetSatCommConfiguration().
size_t CCommManager::GetSatcommErrorString (char * pString, size_t count)
Get satcomm dialer error string.
Get satcomm error string
Parameters
pString points to space to receive the string.
count is the maximum space reserved in pString.
Returns
The number of characters copied to pString.
size_t CCommManager::GetSatcommStatusString (char * pString, size_t count)
Get satcomm dialer status string.
Get satcomm status string
Parameters
pString points to space to receive the string.
count is the maximum space reserved in pString.
Returns
The number of characters copied to pString.
References CommBase_GetSatcommStatusString().
BOOL CCommManager::GetSerialPortConfiguration (UInt8 * chan, UInt32 * baud)
Return the current serial port parameters.
Get the current serial port parameters.
Parameters
chan points to space to receive the port number (0-based).
baud points to space to receive the baud rate.
Returns
TRUE if a serial port is open, else FALSE, in which case the passed parameters will not be changed.
References CommBase_GetSerialPortConfiguration().
Queue_t * CCommManager::GetStreamRxBuffer (UInt16 NetworkID, UInt8 Stream)
Get stream receive pointer.
Returns a pointer to the receive buffer for a specific stream on a specific network. The returned pointer can be used to pop data from the stream. This function is often called in response to the new network call back. The returned pointer should be stored for later use.
Parameters
NetworkID identifies the destination address of the network containing the stream of interest.
Stream identifies the stream whose receive queue should be returned
Returns
A pointer to the receive queue of the stream.
References CommBase_GetStreamRxBuffer().
Queue_t * CCommManager::GetStreamTxBuffer (UInt16 NetworkID, UInt8 Stream)
Get stream transmit pointer.
Returns a pointer to the transmit buffer for a specific stream on a specific network. The returned pointer can be used to pop data from the stream. The returned pointer can be stored for later use. This buffer is used to examine what data are being sent to upstream from this comm manager or from its clients
Parameters
NetworkID identifies the destination address of the network containing the stream of interest.
Stream identifies the stream whose transmit queue should be returned
Returns
A pointer to the transmit queue of the stream.
References CommBase_GetStreamTxBuffer().
Queue_t * CCommManager::GetUserLogBuffer (void)
Get user log buffer pointer.
Get the user log buffer pointer.
Returns
A pointer to the buffer used for custom user data logging.
References CommBase_GetUserLogBuffer().
void CCommManager::GetVersionInformation (Version_t * pVersion)
Get the version of the communications manager software.
Retreives the version of the communications library. The version includes major, minor, and sub version numbers, the release status, and the release date.
Parameters
pVersion points to a structure to receive the version information.
References CommBase_GetVersionInformation().
void CCommManager::HangUpSatcommIdle (void)
Hang up satcomm and go to an idle state.
Hang up satcomm and go to an idle state.
References CommBase_HangUpSatcommIdle().
void CCommManager::HangUpSatcommRedial (void)
Hang up satcomm and redial.
Hang up satcomm and redial.
References CommBase_HangUpSatcommRedial().
BOOL CCommManager::IsInListenOnly (void)
Return the state of listen only mode flag.
References CommBase_IsInListenOnly().
BOOL CCommManager::IsInReplay (void)
Return the state of the replay mode flag.
Returns TRUE if the communications manager is in replay mode.
Returns
TRUE for replay mode, else FALSE
References CommBase_IsInReplay().
void CCommManager::LogUserData (UInt8 * pData, UInt32 Size)
Write a block of custom user data to the telemetry file.
Write a block of custom user data to the telemetry file. This will also forward the user data to all network clients. The user data is packaged in a stream packet with source and destination addresses set to OI_ADDRESS, and the stream identifier set to USER_LOG_STREAM. If the user data size exceeds the max size of a stream packet, then multiple packets will be generated.
Parameters
pData points to the user data byte array.
Size is the number of bytes to be written.
References CommBase_LogUserData().
BOOL CCommManager::NewNetworkClientConfiguration (const char * ServerAddress, BOOL EnableLogging = TRUE, const char * pLogPath = NULL, BOOL ListenOnly = FALSE)
Change the network client configuration.
Change the network client configuration of the communications manager. This function will alter the connection mechanism between the comm manager and upstream devices (i.e. devices closer to the avionics). If the comm manager was previously conneted as a serial port then the serial port will be closed. If it was previously connected to a replay file the file will be closed, and a binary log file opened instead. This function will change nothing unless the new TCP client connection is successfully opened.
Parameters
ServerAddress is a character string describing the TCP/IP network address and port number of a communications server. The address can be in dotted decimal form ("192.168.0.1:2000"), or it can be a host name ("www.mydomain.com:Port"), or it can contain a local host name ("Server:Port"). If the communications manager succeeds in connecting to the server it will not open the serial port indicated by the first parameter. If you don't want to connect to a server pass a NULL pointer or a zero-length string ("").
EnablingLogging should be to TRUE to enable binary logging of data from the new port.
pLogPath shold be non-NULL to specify a path for the log file. If pLogPath is NULL, or if the path is the same as the previous path the logging file will not be reset.
ListenOnly flag if the connection is "listen only"; it won't send data
Returns
TRUE if the TCP connection was successful.
References CommBase_NewNetworkClientConfiguration().
BOOL CCommManager::NewNetworkServerConfiguration (int ListenPort)
Change the network server configuration.
Change the network server configuration of the communications manager. This function will change the port number that clients connect to. All currently connected clients will have their connection terminated and must reconnect. Note that this function will close down the existing server socket before opening the new one, hence if the function fails the previous server configuration will be lost
Parameters
ListenPort specifies the port number to listen on for a server. Pass a port number greater than 1023 to enable this communications manager to be a server. It will listen for incoming TCP connections on this port and establish connnections. As a server the comm manager will route data between the serial port connected to a groundstation and any of the client TCP connections.
Returns
TRUE if the function succeeds, else FALSE.
References CommBase_NewNetworkServerConfiguration().
BOOL CCommManager::NewReplayFileConfiguration (const char * ReplayFile)
Change the replay file configuration.
Change the replay file configuration of the communications manager. This function will alter the connection mechanism between the comm manager and upstream devices (i.e. devices closer to the avionics). If the comm manager was previously conneted as a serial port then the serial port will be closed. If it was previously connected as a TCP client then the TCP connection will be closed. If it was previously loging to a binary log file, the file will be closed. This function will change nothing unless the new replay file is successfully opened.
Parameters
ReplayFile is a string with the path and name of the file to open for replay.
Returns
TRUE if the replay file was opened successfully.
References CommBase_NewReplayFileConfiguration().
BOOL CCommManager::NewSerialPortConfiguration (int chan, UInt32 baud, const char * pIridiumNumber = NULL, BOOL EnableLogging = TRUE, const char * pLogPath = NULL, BOOL ListenOnly = FALSE)
Change the serial port configuration.
Change the serial port configuration of the communications manager. This function will alter the connection mechanism between the comm manager and upstream devices (i.e. devices closer to the avionics). If the comm manager was previously conneted as a TCP client then the TCP client connection will be closed. If it was previously connected to a replay file the file will be closed, and a binary log file opened instead. This function will change nothing unless the new serial connection is successfully opened. If the serial port number matches the currently open port than only the baud rate of the port will be changed.
Parameters
chan is the identifier of the serial port to use (COM1, COM2, etc).
baud is the baud rate to use for the serial port.
EnablingLogging should be to TRUE to enable binary logging of data from the new port.
pLogPath shold be non-NULL to specify a path for the log file. If pLogPath is NULL, or if the path is the same as the previous path the logging file will not be reset.
ListenOnly flag if the connection is "listen only"; it won't send data
Returns
TRUE if the serial port was reconfigued, else the previous connection mechanism remains in effect.
References CommBase_NewSerialPortConfiguration().
void CCommManager::PauseReplay (void)
Disable the replay.
Pause the replay
References CommBase_PauseReplay().
void CCommManager::RequestActuatorTablePacket (UInt16 NetworkID, UInt8 Sur)
Request the autopilot surface table calibration packet.
Request the autopilot actuator table calibration packet. The actuator calibration packet encodes the relationship between pulse width and actuator angle for a single actuator.
Parameters
NetworkID is the address of the avionics to request the packet from.
Sur is the actuator index that the table refers to.
References CommBase_RequestActuatorTablePacket().
void CCommManager::RequestAltimeterSettingPacket (UInt16 NetworkID)
Request the altimeter setting packet.
Request the altimeter setting packet.
Parameters
NetworkID is the address of the avionics to request the packet from.
References CommBase_RequestAltimeterSettingPacket().
void CCommManager::RequestBandwidthModePacket (UInt16 NetworkID, UInt8 NetID)
Request the bandwidth mode packet.
Request the bandwidth mode packet
Parameters
NetworkID is the address of the avionics to request the packet from.
NetID enumerates which link on the autopilot the data should come from, pass 0xFF to use the link this packet arrives on
References CommBase_RequestBandwidthModePacket().
void CCommManager::RequestControllerDataPacket (UInt16 NetworkID, UInt8 Controller, UInt8 Version, UInt8 Category, UInt8 DataID, UInt8 NumData)
Request some controller data.
Create and send a controller data request packet
Parameters
NetworkID is the address of the avionics to request the packet from.
Controller is the controller ID value.
Version is the controller version value.
Category is the data category.
DataID is the starting DataID.
NumData is the number of data elements to request.
References CommBase_RequestControllerDataPacket().
void CCommManager::RequestDescriptionPacket (UInt16 NetworkID)
Request the parameter description packet.
Request the parameter description packet. The parameter description is a string which can be used to identify the set of parameters stored on the autopilot.
Parameters
NetworkID is the address of the avionics to request the packet from.
References CommBase_RequestDescriptionPacket().
void CCommManager::RequestDGPSBasePacket (void)
Request the packet with DGPS base settings.
Request the DGPS setup from the groundstation
References CommBase_RequestDGPSBasePacket().
void CCommManager::RequestExternalIOSetupPacket (UInt16 NetworkID, UInt8 pin)
Request then autopilot packet with the setup parameters for a single external IO pin.
Request then autopilot packet with the setup parameters for a single external IO pin.
Parameters
NetworkID is the address of the avionics to request the packet from.
pin identifies which IO pin these setup data apply to.
References CommBase_RequestExternalIOSetupPacket().
void CCommManager::RequestExternalSerialSetupPacket (UInt16 NetworkID)
Request the autopilot packet with the external serial setup parameters.
Request then autopilot packet with the external serial setup parameters.
Parameters
NetworkID is the address of the avionics to request the packet from.
References CommBase_RequestExternalSerialSetupPacket().
void CCommManager::RequestGimbalAxisSettingsPacket (UInt16 NetworkID, BOOL Factory = FALSE)
Request a gimbal axis settings packet.
Request a gimbal axis settings packet which contains the data to setup the axis control for custom configurations.
Parameters
NetworkID is the address of the avionics to request the packet from.
Factory should be TRUE to request factory settings.
References CommBase_RequestGimbalAxisSettingsPacket().
void CCommManager::RequestGimbalCameraAlignPacket (UInt16 NetworkID, UInt8 Camera, BOOL Factory = FALSE)
Request camera alignment information.
Request a gimbal camera alignment packet.
Parameters
NetworkID is the address of the avionics to request the packet from.
Camera enumerates the camera to request alignment data for.
Factory should be TRUE to request factory settings
References CommBase_RequestGimbalCameraAlignPacket().
void CCommManager::RequestGimbalCameraCmdPacket (UInt16 NetworkID, UInt8 Camera)
Request a camera command packet.
Request a camera command packet containing the field of view, focus, and exposure settings.
Parameters
NetworkID is the address of the avionics to request the packet from.
Camera identifies which camera to request data for.
References CommBase_RequestGimbalCameraCmdPacket().
void CCommManager::RequestGimbalCameraTypesPacket (UInt16 NetworkID, BOOL Factory = FALSE)
Request gimbal camera types.
Request gimbal camera types
Parameters
NetworkID is the address of the avionics to request the packet from.
Factory should be TRUE to request factory settings.
References CommBase_RequestGimbalCameraTypesPacket().
void CCommManager::RequestGimbalLaserSetupPacket (UInt16 NetworkID, BOOL Factory = FALSE)
Request gimbal laser setup.
Request gimbal laser setup
Parameters
NetworkID is the address of the avionics to request the packet from.
Factory should be TRUE to request factory settings.
References CommBase_RequestGimbalLaserSetupPacket().
void CCommManager::RequestGimbalSPOICmdPacket (UInt16 NetworkID)
Request a sensor point of interest command packet.
Request a gimbal sensor point of interest (SPOI) cmd packet. The SPOI packet tells the gimbal where to point in LLA coordinates relative to the WGS-84 ellipsoid.
Parameters
NetworkID is the address of the avionics to request the packet from.
References CommBase_RequestGimbalSPOICmdPacket().
void CCommManager::RequestGSFirmwarePacket (void)
Request the software and hardware configuration settings from the ground station.
Request the software and hardware configuration settings from the ground station.
References CommBase_RequestGSFirmwarePacket().
void CCommManager::RequestGSRadioSettingsPacket (void)
Request ground station radio settings.
Request the autopilot radio settings packet. The radio settings packet is used to control the channel and output power of the radio.
Parameters
NetworkID is the address of the avionics to request the packet from.
References CommBase_RequestGSRadioSettingsPacket().
void CCommManager::RequestGSSpectrumSweepPacket (float StartFreq, float Spacing, UInt16 Dwell, UInt8 NumMeasurements)
Request ground station spectrum sweep, coherent frequency radio.
Request ground station spectrum sweep. This puts the coherent frequency MHX radio in a scanning mode mesureing the signal strength at each user specified frequency. If the MXH radio in the groundstation is not coherent (i.e. it is hopping) then the user settings will not apply.
Parameters
pPkt points to a stream packet to receive the formatted data.
StartFreq is the frequency to begin the sweep in MHz.
Spacing is the space between frequencies in MHz.
Dwell is the dwell time for each measurement in ms.
NumMeasurements is the number of measurements to make.
References CommBase_RequestGSCoherentSpectrumSweepPacket().
void CCommManager::RequestGSSpectrumSweepPacket (void)
Request ground station spectrum sweep, hopping radio.
Request a ground station spectrum sweep from a hopping MHX radio. If the MHX radio in the ground station is not hopping (i.e. it is coherent) then the swpecturm sweep will be performed with default user settings.
References CommBase_RequestGSHoppingSpectrumSweepPacket().
void CCommManager::RequestMagCalPacket (UInt16 NetworkID)
Request the packet with the magnetometer calibration data.
Request the packet with the magnetometer calibration data.
Parameters
NetworkID is the address of the avionics to request the packet from.
References CommBase_RequestMagCalPacket().
void CCommManager::RequestMissionLimitsPacket (UInt16 NetworkID)
Request the autopilot mission limits packet.
Request the autopilot mission limits packet. The mission limits packet contains timeouts and actions which limit are used to limit the scope of the mission.
Parameters
NetworkID is the address of the avionics to request the packet from.
References CommBase_RequestMissionLimitsPacket().
void CCommManager::RequestOrientationPacket (UInt16 NetworkID)
Request the autopilot orientation packet.
Request the autopilot orientation packet. The orientation packet describes the installed orientation of the Piccolo avionics as Euler angle rotations from the avionics frame to the vehicle frame.
Parameters
NetworkID is the address of the avionics to request the packet from.
References CommBase_RequestOrientationPacket().
void CCommManager::RequestPayloadMassPacket (UInt16 NetworkID)
Request the payload mass packet.
Request the payload mass packet
Parameters
NetworkID is the address of the avionics to request the packet from.
References CommBase_RequestPayloadMassPacket().
void CCommManager::RequestRadioSettingsPacket (UInt16 NetworkID)
Request the radio settings packet.
Request the autopilot radio settings packet. The radio settings packet is used to control the channel and output power of the radio.
Parameters
NetworkID is the address of the avionics to request the packet from.
References CommBase_RequestRadioSettingsPacket().
void CCommManager::RequestRawVibrationDataPacket (UInt16 NetworkID)
Request the raw vibration sensor data.
Request the raw vibration sensor data. The raw vibration data comes down in 96 packets, 16 for each of six sensors, and contains 1024 samples at 1kHz.
Parameters
NetworkID is the address of the avionics to request the packet from.
References CommBase_RequestRawVibrationDataPacket().
void CCommManager::RequestSensorErrorPacket (UInt16 NetworkID)
Request the packet with the sensor error data.
Request the packet with the sensor error data
Parameters
NetworkID is the address of the avionics to request the packet from.
References CommBase_RequestSensorErrorPacket().
void CCommManager::RequestSystemVersionPacket (UInt16 NetworkID)
Request system version packet.
Request the system version packet
Parameters
NetworkID is the address of the avionics to request the packet from.
References CommBase_RequestSystemVersionPacket().
void CCommManager::RequestThrottleMinPacket (UInt16 NetworkID)
Request the throttle min packet.
Request the payload mass packet
Parameters
NetworkID is the address of the avionics to request the packet from.
References CommBase_RequestThrottleMinPacket().
void CCommManager::RequestTransponderControlPacket (UInt16 NetworkID)
Request the transponder control packet.
Request the autopilot transponder control packet. The transponder control packet is used to report the squawk code of an external tranponsder.
Parameters
NetworkID is the address of the avionics to request the packet from.
References CommBase_RequestTransponderControlPacket().
void CCommManager::RequestTransponderInstallationPacket (UInt16 NetworkID)
Request the transponder installation packet.
Request the transponder installation packet
References CommBase_RequestTransponderInstallationPacket().
void CCommManager::RequestTransponderPreflightPacket (UInt16 NetworkID)
Request the transponder preflight packet.
Request the transponder preflight packet
References CommBase_RequestTransponderPreflightPacket().
void CCommManager::RequestUserSpacePacket (UInt16 NetworkID)
Request the user space packet.
Request the user space packet. The user space packet is used to write user data to nonvolatile storage on the avionics. This data space is intended to be used by third-party applications which must store information on the autopilot
Parameters
NetworkID is the address of the avionics to send the packet to.
References CommBase_RequestUserSpacePacket().
void CCommManager::ResumeReplay (void)
Enable the replay.
Resume the replay
References CommBase_ResumeReplay().
void CCommManager::RunNetwork (void)
Call periodically to service the communications.
Basic driver function for the communications manager. This function should be called periodically in order to service all of the communications ports that the communications manager is connected to. Typical period for calling this function is 10ms.
References CommBase_RunNetwork().
void CCommManager::SendActuatorTablePacket (UInt16 NetworkID, const ActuatorTable_t * pTable, UInt8 Sur, UInt8 Type, UInt8 Virtual, UInt8 Fast)
Create and send a control actuator calibration packet.
Create and send a autopilot surface table calibration packet. The surface calibration packet encodes the relationship between pulse width and surface angle for a single surface.
Parameters
NetworkID is the address of the avionics to send the packet to.
pTable points to a single surface calibration table.
Sur is the surface index that the table refers to.
Type is the actuator type data.
Virtual should be 1 if this is a virtual (CAN output only) actuator.
Fast should be 1 if this is a fast (200 Hz update rate) actuator.
References CommBase_SendActuatorTablePacket().
void CCommManager::SendActuatorTypePacket (UInt16 NetworkID, UInt8 Sur, UInt8 Type)
Create and send a packet to change actuator type.
Create and send a packet to change the type of an actuator without changing the calibration table.
Parameters
NetworkID is the address of the avionics to send the packet to.
pTable points to a single surface calibration table.
Sur is the surface index that the table refers to.
Type is the actuator type data.
References CommBase_SendActuatorTypePacket().
void CCommManager::SendAirDataZeroPacket (UInt16 NetworkID, float ActualAltitude)
Create and send the zero air data command packet.
Create and send the zero air data command packet. This commands the autopilot to zero the airspeed and altitude sensors. This packet should not be sent while the vehicle is flying.
Parameters
NetworkID is the address of the avionics to send the packet to.
ActualAltitude is current altitude in meters. It is used (along with the altimeter setting) to determine the static pressure error. If the static pressure sensor should not be zeroed then supply an ActualAltitude value which is less than -5000
References CommBase_SendAirDataZeroPacket().
void CCommManager::SendAltimeterSettingPacket (UInt16 NetworkID, UInt32 Altimeter, BOOL ControlToGPS)
Create and send an altimeter setting packet.
Create and send a altimeter setting packet
Parameters
NetworkID is the address of the avionics to send the packet to.
Altimeter is the altimeter setting in Pascals.
ControlToGPS should be TRUE to tell the autopilot to use the GPS altitude as its control target.
References CommBase_SendAltimeterSettingPacket().
void CCommManager::SendAutopilotLoopControlPacket (UInt16 NetworkID, const AutopilotLoopCmd_t * pCmd, BOOL UpdateEEPROM = TRUE)
Create and send a autopilot loop control packet.
Create and send a autopilot loop control packet. The loop control packet is used to change individual autopilot loops without changing the state of the other loops.
Parameters
NetworkID is the address of the avionics to send the packet to.
pCmd points to individual loop data to be included in the packet.
UpdateEEPROM should be TRUE to cause the autopilot to write this data to EEPROM.
References CommBase_SendAutopilotLoopControlPacket().
void CCommManager::SendAutopilotPacket (UInt16 NetworkID, const AutopilotPkt_t * pPkt)
Send a autopilot packet.
Send an autopilot stream packet
Parameters
NetworkID is the destination network address.
pPkt points to the autopilot packet to send.
References CommBase_SendAutopilotPacket().
void CCommManager::SendBandwidthModePacket (UInt16 NetworkID, BandwidthMode_t Bandwidth)
Create and send a bandwidth mode packet.
Create and send a altimeter setting packet
Parameters
NetworkID is the address of the avionics to send the packet to. Bandwidth is the data to send
References CommBase_SendBandwidthModePacket().
void CCommManager::SendBlock (UInt16 NetworkID, UInt8 Stream, UInt8 * pData, UInt32 Size)
Send a block of data in a packet.
Format a block of data into one or more stream packets and then send the packets. This function will use the new format (1.2.x) of the stream packet unless is has detected old format packets from the network in question, in which case it will format the packet in the 1.1.x format.
Parameters
NetworkID is the destination network address, 0 for the ground station.
Stream is the destination stream identifier.
pData points to a buffer of data to be sent in the packet.
Size is the amount of data in the buffer.
References CommBase_SendBlock().
void CCommManager::SendBoundaryPacket (UInt16 NetworkID, const Boundary_t * pBnd)
Create and send a airspace boundary packet.
Create and send a airspace boundary packet
Parameters
NetworkID is the address of the avionics to send the packet to.
pBnd is the boundary to send
References CommBase_SendBoundaryPacket().
void CCommManager::SendBrakesCommandPacket (UInt16 NetworkID, float Brakes)
Create and send the brakes command packet.
Create and send the brakes command packet. The brakes command asserts or deasserts the brake IO line(s), or actuates the brake servo(s). This command will have no effect if no IO lines are programmed for brake operation. The brake state is visible in the AUTOPILOT_COMMAND downlink packet.
Parameters
NetworkID is the address of the avionics to send the packet to.
Brakes gives the level of brakes actuation from 0 (brakes released) to 1 (brakes fully applied).
References CommBase_SendBrakesCommandPacket().
void CCommManager::SendConfigurationLockPacket (UInt16 NetworkID, const char Password[32] = NULL)
Create and send a configuration lock packet.
Create and send a configuration lock packet
Parameters
NetworkID is the address of the avionics to send the packet to.
Password is the pasword touse in the packet, send NULL for zero length packet.
References CommBase_SendConfigurationLockPacket().
void CCommManager::SendConfigurationUnlockPacket (UInt16 NetworkID, const char Password[32] = NULL, BOOL Silent = FALSE)
Create and send a configuration unlock packet.
Create and send a configuration unlock packet
Parameters
NetworkID is the address of the avionics to send the packet to.
Password is the pasword touse in the packet, send NULL for zero length packet.
Silent should be TRUE to use the quiet version of this packet
References CommBase_SendConfigurationUnlockPacket().
void CCommManager::SendControllerDataDefaultPacket (UInt16 NetworkID, UInt8 Controller, UInt8 Version, UInt8 Category, UInt8 DataID, UInt8 NumData)
Create and send a controller packet to default data.
Create and send a controller data packet which defaults data
Parameters
NetworkID is the address of the avionics to send the packet to.
Controller is the controller ID value.
Version is the controller version value.
Category is the data category.
DataID is the starting DataID.
NumData is the number of data elements to encode.
References CommBase_SendControllerDataDefaultPacket().
void CCommManager::SendControllerDataPacket (UInt16 NetworkID, UInt8 Controller, UInt8 Version, UInt8 Category, UInt8 DataID, UInt8 NumData, const void * pData)
Create and send a controller packet.
Create and send a controller data packet which contains 32-bit data words
Parameters
NetworkID is the address of the avionics to send the packet to.
Controller is the controller ID value.
Version is the controller version value.
Category is the data category.
DataID is the starting DataID.
NumData is the number of data elements to encode.
pData points to the data to encode.
References CommBase_SendControllerDataPacket().
void CCommManager::SendDescriptionPacket (UInt16 NetworkID, const char Description[64])
Create and send a parameter description packet.
Create and send a parameter description packet. The parameter description is a string which can be used to identify the set of parameters stored on the autopilot.
Parameters
NetworkID is the address of the avionics to send the packet to.
Description is an array of bytes to send as the description. The array should contain a NULL-terminated string.
References CommBase_SendDescriptionPacket().
void CCommManager::SendDGPSBasePacket (const DGPSParameter_t * pDGPS)
Create and send a ground station differential corrections packet.
Create and send a ground station differential corrections packet. The DGPS packet contains the information required to configure differential corrections.
Parameters
pDGPS points to the base station information to be included in the packet.
References CommBase_SendDGPSBasePacket().
void CCommManager::SendDoubletCommandPacket (UInt16 NetworkID, const DoubletCmd_t * pDoublet)
Create and send a doublet command packet.
Create and send a doublet command packet
Parameters
NetworkID is the address of the avionics to send the packet to.
pDoublet points to space containing the doublet command data
References CommBase_SendDoubletCommandPacket().
void CCommManager::SendDropCommandPacket (UInt16 NetworkID, BOOL DropOn)
Create and send the drop command packet.
Create and send the drop command packet. The drop command asserts or deasserts the drop IO line(s), or actuates the drop servo(s). This command will have no effect if no IO lines are programmed for drop operation. The drop state is visible in the AUTOPILOT_COMMAND downlink packet.
Parameters
NetworkID is the address of the avionics to send the packet to.
DropOn should be TRUE to turn the drop on, else it will be turned off.
References CommBase_SendDropCommandPacket().
void CCommManager::SendEngineKillPacket (UInt16 NetworkID, BOOL EngineKill)
Create and send the engine kill packet.
Create and send the engine kill packet
Parameters
NetworkID is the address of the avionics to send the packet to.
EngineKill should be TRUE to kill the engine, FALSE to enable the engine.
References CommBase_SendEngineKillPacket().
void CCommManager::SendExternalIOSetupPacket (UInt16 NetworkID, const ExternalIO_t * pExternalIO, UInt8 pin, UInt32 SampleTime, BOOL UpdateEEPROM = TRUE)
Create and send a external IO setup packet.
Create and send an autopilot packet with the setup parameters for a single external IO pin.
Parameters
NetworkID is the address of the avionics to send the packet to.
pExternalIO points to a structure containing the setup parameters.
pin identifies which IO pin these setup data apply to.
SampleTime is the time in milliseconds that the external IO inputs should be sampled.
UpdateEEPROM should be TRUE to cause the autopilot to write this data to EEPROM.
References CommBase_SendExternalIOSetupPacket().
void CCommManager::SendExternalSerialSetupPacket (UInt16 NetworkID, const ExternalSerial_t * pSerial)
Create and send a external serial setup packet.
Create and send an autopilot packet with the external serial setup parameters.
Parameters
NetworkID is the address of the avionics to send the packet to.
pSerial points to a structure containing the serial setup parameters.
References CommBase_SendExternalSerialSetupPacket().
void CCommManager::SendFeatureCodePacket (UInt16 NetworkID, const UInt8 Data[8])
Create and send a feature code packet.
Create and send a feature code packet.
Parameters
NetworkID is the address of the avionics to send the packet to.
Data is the 8 byte feature code.
References CommBase_SendFeatureCodePacket().
void CCommManager::SendFrequencySweepCommandPacket (UInt16 NetworkID, const FrequencySweepCmd_t * pFreqSwp)
Create and send a frequency sweep command packet.
Create and send a frequency sweep command packet
Parameters
NetworkID is the address of the avionics to send the packet to.
pFreqSwp points the the frequency sweep settings structure.
References CommBase_SendFrequencySweepCommandPacket().
void CCommManager::SendGimbalAxisSettingsPacket (UInt16 NetworkID, const float NoGoCenter[NGIMBAL_SHORT], const float NoGoRange[NGIMBAL_SHORT], const float MaxRate[NGIMBAL_SHORT], const float MaxAccel[NGIMBAL_SHORT], const float PosGain[NGIMBAL_SHORT], const float VelGain[NGIMBAL_SHORT], const float DerGain[NGIMBAL_SHORT], BOOL Temporary = FALSE, BOOL Factory = FALSE)
Create and send a gimbal axis settings packet.
Create and send a gimbal axis settings packet which contains the data to setup the axis control for custom configurations.
Parameters
NetworkID is the address of the avionics to send the packet to.
NoGoCenter is the center of the no go range in radians for all gimbal axis.
NoGoRange is the size of the no go range in radians for all gimbal axis. Zero is free-running. More than 2PI is do not change center or range.
MaxRate is the max rate in radians per second for all gimbal axis. Less than zero is do not change.
MaxAccel is the max accelerating in radians per second per second for all gimbal axis. Less than zero is do not change.
PosGain is the position gain in angle per second per angle error. Less than zero is do not change.
VelGain is the velocity feedforward gain, less than zero is do not change.
DerGain is the aceleration feedforward gain, less than zer is do not change.
Temporary should be 1 to prevent update to nonvolatile storage.
Factory should be TRUE to update factory parameters as well as main.
References CommBase_SendGimbalAxisSettingsPacket().
void CCommManager::SendGimbalCameraAlignPacket (UInt16 NetworkID, float Zoom1, const float Error1[NGIMBAL], float Zoom2, const float Error2[NGIMBAL], UInt8 Camera, BOOL Factory = FALSE)
Create and send gimbal camera alignment packet.
Create and send gimbal camera alignment packet
Parameters
NetworkID is the address of the avionics to send the packet to.
Zoom1 is the zoom ration of the first alignment.
Error1 is the pan, tilt, and roll alignemnt errors at zoom1 [rad].
Zoom2 is the zoom ration of the second alignment.
Error1 is the pan, tilt, and roll alignemnt errors at zoom2 [rad].
Camera enumerates the camera that this data apply to.
Factory should be TRUE to udpate factory settings as well as main.
References CommBase_SendGimbalCameraAlignPacket().
void CCommManager::SendGimbalCameraCmdPacket (UInt16 NetworkID, UInt8 Camera, float HFOV, UInt16 Focus, UInt8 Mode, UInt8 Shutter, UInt8 Bright, UInt8 Flags)
Create and send a camera command packet.
Create and send a camera command packet containing the field of view, focus, and exposure settings.
Parameters
NetworkID is the address of the avionics to send the packet to.
Camera identifies the camera to control.
HFOV is the horizontal field of view in radians, or (if negative) the camera zoom ratio. 0.0 is do not change.
Focus is the focus length in millimeters, 0xFFFF is do not change, 0xFFFE is infinite, 0xFFFD is trigger, 0x0000 is auto.
EMode is the exposure mode: 0 for auto, 1 for shutter priority, 2 for bright mode. 0xFF is do not change
Shutter is the shutter speed. 0xFF is do not change
Bright is the bright mode setting, 0xFF is do not change.
Flags is the camera flag settings, set MSB for do not change.
References CommBase_SendGimbalCameraCmdPacket().
void CCommManager::SendGimbalCameraTypesPacket (UInt16 NetworkID, const CameraDefinition_t Cam[NUM_CAMERAS], const BOOL Send[NUM_CAMERAS], BOOL Factory = FALSE)
Create and send gimbal camera definitions packet.
Create and send gimbal camera definitiosn packet.
Parameters
NetworkID is the address of the avionics to send the packet to.
CameraTypes is the array of camera types to send.
Factory should be TRUE to update factory definitions as well as main.
References CommBase_SendGimbalCameraTypesPacket().
void CCommManager::SendGimbalCmdPacket (UInt16 NetworkID, float Pan, float Tilt, SInt8 ZoomRate, float CamTimeout, UInt8 Flags, float ImpulseTime, SInt8 FocusRate = 0, UInt8 Flags1 = 0)
Create and send a gimbal command packet containing pan, tilt, zoom and focus rate, and mode.
Create and send a gimbal cmd packet. The command packet contains the rate or position data for pan and tilt, the camera zoom rate data, as well as the operational mode of the gimbal.
Parameters
NetworkID is the address of the avionics to send the packet to.
Pan is the pan position (or rate) in radians (per second).
Tilt is the pan position (or rate) in radians (per second).
ZoomRate is the zoom rate from -8 to 8.
CamTimeout is the time to apply the zoom or focus, in seconds.
Flags describes how to interpret the data.
ImpulseTime is the time to apply to an impulse (seconds).
FocusRate is the focus rate from -8 to 8.
Flags1 provides additional details on how to interpret the data.
References CommBase_SendGimbalCmdPacket().
void CCommManager::SendGimbalLaserArmPacket (UInt16 NetworkID, UInt8 LaserIndex, BOOL Arm)
Create and send gimbal laser arm packet.
Create and send gimbal laser arm packet
Parameters
NetworkID is the address of the avionics to send the packet to.
LaserIndex identifies the laser to arm.
Arm should be TRUE to arm the laser else it is disarmed.
References CommBase_SendGimbalLaserArmPacket().
void CCommManager::SendGimbalLaserFirePacket (UInt16 NetworkID, UInt8 LaserIndex, UInt8 Power)
Create and send gimbal laser fire packet.
Create and send gimbal laser fire packet
Parameters
NetworkID is the address of the avionics to send the packet to.
LaserIndex identifies the laser to arm.
Power is the laser power from 0 to 100 (percent)
References CommBase_SendGimbalLaserFirePacket().
void CCommManager::SendGimbalLaserSetupPacket (UInt16 NetworkID, LaserSetup_t Lasers[NUM_LASERS], BOOL Factory = FALSE)
Create and send gimbal laser setup packet.
Create and send gimbal laser setup packet
Parameters
NetworkID is the address of the avionics to send the packet to.
Lasers is the setup information to send.
Factory should be TRUE to update factory settings as well as main.
References CommBase_SendGimbalLaserSetupPacket().
void CCommManager::SendGimbalPacket (UInt16 NetworkID, const GimbalPkt_t * pPkt)
Send a gimbal packet on the gimbal stream to the autopilot.
Send a gimbal packet on the gimbal stream to the autopilot
Parameters
NetworkID is the destination network address.
pPkt points to the gimbal packet to send.
References CommBase_SendGimbalPacket().
void CCommManager::SendGimbalRetractDeployCmdPacket (UInt16 NetworkID, UInt32 Deploy)
Create and send gimbal retract/deploy command.
Create and send gimbal retract/deploy command
Parameters
NetworkID is the address of the avionics to send the packet to.
Deploy is the command, 0 for retract, 1 for deploy, 2 for halt.
References CommBase_SendGimbalRetractDeployCmdPacket().
void CCommManager::SendGimbalSerialInterfacePacket (UInt16 NetworkID, GimbalSerial_t Serial[6], BOOL Temporary)
Create and send gimbal packet rate packet.
Create and send a gimbal packet which sets the output rate for standard gimbal packets.
Parameters
NetworkID is the address of the avionics to send the packet to.
Serial contains the interface setup for the gimbal.
Temporary should be zero to make settings permanent.
References CommBase_SendGimbalSerialInterfacePacket().
void CCommManager::SendGimbalSPOICmdPacket (UInt16 NetworkID, const double Pos[NPOS], const float Vel[NDIR], UInt8 Flags)
Create and send a gimbal sensor point of interest packet containing the position of the SPOI.
Create and send a gimbal sensor point of interest (SPOI) cmd packet. The SPOI packet tells the gimbal where to point in LLA coordinates relative to the WGS-84 ellipsoid.
Parameters
NetworkID is the address of the avionics to send the packet to.
Pos is the position of the SPOI in Lat[rad], Lon[rad], Alt[m].
Vel is the velocity of the SPOI in North, East, Down [m/s].
Flags is the packet flags.
References CommBase_SendGimbalSPOICmdPacket().
void CCommManager::SendGimbalTrackCmdPacket (UInt16 NetworkID, float InitialX, float InitialY, UInt8 Algorithm, UInt8 Size, UInt8 Stamp)
Create and send gimbal track command packet.
Create and send the track command packet
Parameters
NetworkID is the address of the avionics to send the packet to.
InitialX is the initial horizontal track position in radians.
InitialY is the initial vertical track position in radians.
Algorithm is the algorithm choice enumeration.
Size is the size of the tracking window in pixels.
Stamp is the video counter stamp that goes with this track command, 255 if no stamp.
References CommBase_SendGimbalTrackCmdPacket().
void CCommManager::SendGroundStationPacket (const GroundStationPkt_t * pPkt)
Send an groundstation packet.
Send an groundstation packet
Parameters
pPkt points to the groundstation packet to send.
References CommBase_SendGroundStationPacket().
void CCommManager::SendGSAddAddressPacket (UInt16 Address)
Create and send a ground station add address packet.
Create and send a ground station add address packet. This packet is used to add an autopilot address to the ground station polling list.
Parameters
Address is the address to add. Valid addresses are 1 to 65533.
References CommBase_SendGSAddAddressPacket().
void CCommManager::SendGSAddPilotAddressPacket (UInt16 Address)
Create and send a ground station add pilot address packet.
Create and send a ground station pilot address packet. This packet is used to change the pilot address used by the ground station.
Parameters
Address is the pilot address. Valid addresses are 1 to 65533.
References CommBase_SendGSAddPilotAddressPacket().
void CCommManager::SendGSConfiguration (UInt8 ConfigEnum, UInt8 SBASDisable, UInt8 EnableGD, UInt32 PayloadBaud, UInt8 EnableMHXRelay)
Create and send a ground station configuration packet.
Create and send a ground station configuration packet.
Parameters
ConfigEnum is the ground station configuration enumeration, see GSConfigurations.
SBASDisable is the disable SBAS flag.
EnableGD is the enable guaranteed delivery flag.
PayloadBaud is the payload baud rate in bits per second.
EnableMHXRelay is the enable for microhard radio reflash relay.
References CommBase_SendGSConfiguration().
void CCommManager::SendGSDeleteAddressPacket (UInt16 DelAddress, UInt16 KeepAddress = 0)
Create and send a ground station delete address packet.
Create and send a ground station delete address packet. This packet is used to remove addresses from the polling list. The pilot address cannot be removed.
Parameters
DelAddress is the address to remove. Pass zero to remove all addresses except the pilot address.
KeepAddress is the address to keep if removing all addresses. Pass zerp to remove all addresses excepting pilot.
References CommBase_SendGSDeleteAddressPacket().
void CCommManager::SendGSDynamicEnumerationPacket (BOOL On)
Create and send a dynamic enumeration on/off packet.
Create and send a ground station dynamic enumeration on/off packet. Dynamic enumeration is a feature of the ground station that allows it to discover any active autopilots that are on its same frequency and channel.
Parameters
On should be TRUE to enable dynamic enumeration.
References CommBase_SendGSDynamicEnumerationPacket().
void CCommManager::SendGSRadioSettingsPacket (const RadioSettings_t * pSettings)
Create and a ground station radio settings packet.
Create and send a ground station radio settings packet. The radio settings packet is used to control the channel and output power of the radio.
Parameters
pSettings points to radio settings to be included in the packet.
References CommBase_SendGSRadioSettingsPacket().
void CCommManager::SendLandNowPacket (UInt16 NetworkID)
Create and send the land now command packet.
Create and send the land now command packet. This commands the autopilot to being tracking the landing flight plan as identified in the mission limits.
Parameters
NetworkID is the address of the avionics to send the packet to.
References CommBase_SendLandNowPacket().
void CCommManager::SendLaunchNowPacket (UInt16 NetworkID)
Create and send the launch now command packet.
Create and send the land now command packet. This commands the autopilot to initiate the launch sequence.
Parameters
NetworkID is the address of the avionics to send the packet to.
References CommBase_SendLaunchNowPacket().
void CCommManager::SendLegacyWaypointListPacket (UInt16 NetworkID, const FPMask_t Mask, UInt8 Flag)
Create and send a legacy waypoint list packet.
Create and send a autopilot waypoint list packet. This packet contains a flight plan mask with one bit for every possible waypoint; and a flags parameter telling the avionics how to use the mask.
Parameters
NetworkID is the address of the avionics to send the packet to.
Mask is the flight plan mask to be encoded.
Flag is the flight plan mask flags field. The flag should have one of these values:
GET_WAYPOINT_LIST: indicates that the avionics should downlink a valid waypoint list.
DELETE_WAYPOINTS: indicates that the avionics should delete each waypoint in the list.
REQUEST_WAYPOINTS: indicates that the avionics should downlink each waypoint in the list.
WAYPOINT_BLOCK: indicates that a waypoint bock transfer is beginning. The waypoints to be transferred are in the list.
References CommBase_SendLegacyWaypointListPacket().
void CCommManager::SendLegacyWaypointPacket (UInt16 NetworkID, const FPPoint_t * pPoint, UInt8 Index)
Create and send a legacy waypoint packet.
Create and send a legacy autopilot waypoint packet (prior to software 2.2.x). This packet contains all the data for a single waypoint.
Parameters
NetworkID is the address of the avionics to send the packet to.
pPoint contains the waypoint data.
Index is the waypoint index.
References CommBase_SendLegacyWaypointPacket().
void CCommManager::SendLightsCommandPacket (UInt16 NetworkID, BOOL LightsOn)
Create and send the lights command packet.
Create and send the lights command packet. The lights command asserts or deasserts the lights IO line(s). This command will have no effect if no IO lines are programmed for lights operation. The ligths state is visible in the AUTOPILOT_COMMAND downlink packet.
Parameters
NetworkID is the address of the avionics to send the packet to.
LightsOn should be TRUE to turn the lights on, else they will be turned off.
References CommBase_SendLightsCommandPacket().
void CCommManager::SendMagCalPacket (UInt16 NetworkID, const float HardIronErr[N3D], const float ScaleFactErr[N3D])
Create and send a magnetic sensor calibration packet.
Create and send a packet with the magnetometer calibration data.
Parameters
NetworkID is the address of the avionics to send the packet to.
HardIronErr is a vector of hard iron errors.
ScaleFactErr is a vector of scale factor errors.
References CommBase_SendMagCalPacket().
void CCommManager::SendManualAssistModePacket (UInt16 NetworkID, UInt8 Mode)
Create and send the manual assist mode command packet.
Create and send the manual assist mode command packet. The assist mode controls how the autopilot uses the manual control data when the autopilot is globally on. The current manual assist mode is visible in the AUTOPILOT_COMMAND downlink packet. The manual assist modes are:
MA_STANDARD: No manual assistance
MA_LATERAL: Roll control plus rudder
MA_LONGITUDINAL: Speed control plus throttle and flaps
MA_ALL: Roll, speed, rudder, throttle, and flaps
Parameters
NetworkID is the address of the avionics to send the packet to.
Mode is the mode to go to.
References CommBase_SendManualAssistModePacket().
void CCommManager::SendMissionLimitsPacket (UInt16 NetworkID, const MissionLimits_t * pMission)
Create and send a mission limits packet.
Create and send a autopilot mission limits packet. The mission limits packet contains timeouts and actions which limit are used to limit the scope of the mission.
Parameters
NetworkID is the address of the avionics to send the packet to.
pMission points to the mission limit data.
References CommBase_SendMissionLimitsPacket().
void CCommManager::SendMissionSettingsPacket (UInt16 NetworkID, SInt16 MinAltitude, SInt16 MaxAltitude, UInt32 FlightTimeout)
Create and a send a mission settings packet.
Create and send a autopilot mission settings packet which sets the altitude limits and flight timeout
Parameters
NetworkID is the address of the avionics to send the packet to.
MinAltitude is the minimum altitude in meters.
MaxAltitude is the maximum altitude in meters.
FlightTimeout is the flight timeout in seconds
References CommBase_SendMissionSettingsPacket().
void CCommManager::SendOrientationPacket (UInt16 NetworkID, const float Euler[NAXIS], const float IMUtoAnt[N3D], const float IMUtoAnt2[N3D])
Create and send a sensor orientatin packet.
Create and send a autopilot orientation packet. The orientation packet describes the installed orientation of the Piccolo avionics as Euler angle rotations from the avionics frame to the vehicle frame.
Parameters
NetworkID is the address of the avionics to send the packet to.
Euler is an array of Euler angles (ROLL, PITCH, YAW).
IMUtoAnt is an array that holds the position offset from IMU to primary GPS antenna.
IMUtoAnt2 is an array that holds the position offset from IMU to secondary GPS antenna.
References CommBase_SendOrientationPacket().
void CCommManager::SendParachuteCommandPacket (UInt16 NetworkID, BOOL ParachuteDeploy)
Create and send the parachute command packet.
Create and send the parachute command packet. The parachute command asserts or deasserts the parachute IO line(s), or actuates the parachute servo(s). This command will have no effect if no IO lines are programmed for parachute operation. The parachute state is visible in the AUTOPILOT_COMMAND downlink packet.
Parameters
NetworkID is the address of the avionics to send the packet to.
ParachuteDeploy should be TRUE to deploy the parachute, else it will be retracted.
References CommBase_SendParachuteCommandPacket().
void CCommManager::SendPayloadMassPacket (UInt16 NetworkID, float PayloadMass)
Create and send a payload mass packet.
Create and send a set fuel level packet.
Parameters
NetworkID is the address of the avionics to send the packet to.
PayloadMass is the payload mass in kilograms
References CommBase_SendPayloadMassPacket().
void CCommManager::SendPrelaunchPacket (UInt16 NetworkID)
Create and send the go to prelaunch command packet.
Create and send the prelaunch command packet. This commands the autopilot to go to prelaunch mode.
Parameters
NetworkID is the address of the avionics to send the packet to.
References CommBase_SendPrelaunchPacket().
void CCommManager::SendRadioSettingsPacket (UInt16 NetworkID, const RadioSettings_t * pSettings)
Create and send a radio settings packet.
Create and send a autopilot radio settings packet. The radio settings packet is used to control the channel and output power of the radio.
Parameters
NetworkID is the address of the avionics to send the packet to.
pSettings points to radio settings to be included in the packet.
References CommBase_SendRadioSettingsPacket().
void CCommManager::SendSensorErrorPacket (UInt16 NetworkID, const SensorErrorData_t * pSensorError)
Create and send a sensor error.
Create and send a packet with the AGL offset.
Parameters
NetworkID is the address of the avionics to send the packet to.
pSensorError is the data to send.
References CommBase_SendSensorErrorPacket().
void CCommManager::SendSetFuelIfLockedPacket (UInt16 NetworkID, float Fuel, BOOL Electric)
Create and send a set fuel level packet for fuel update while locked.
Create and send a set fuel level packet to change fuel level even if the autopilot is locked.
Parameters
NetworkID is the address of the avionics to send the packet to.
Fuel is the fuel level in kilograms or Watt-Hours.
Electric is TRUE for electric motor (fuel in Watt-Hours).
References CommBase_SendSetFuelIfLockedPacket().
void CCommManager::SendSetFuelLevelPacket (UInt16 NetworkID, float Fuel, BOOL Electric)
Create and send a set fuel level packet.
Create and send a set fuel level packet.
Parameters
NetworkID is the address of the avionics to send the packet to.
Fuel is the fuel level in kilograms or Watt-Hours.
Electric is TRUE for electric motor (fuel in Watt-Hours).
References CommBase_SendSetFuelLevelPacket().
void CCommManager::SendSimpleLandingPacket (UInt16 NetworkID, const SimpleLandingPattern_t * pLand)
Create and send a simple landing packet.
Create and send a packet containing the simple landing pattern information necessary for creating a simple landing pattern flightplan.
Parameters
NetworkID is the address of the avionics to send the packet to.
pLand points to a simple landing pattern data structure.
References CommBase_SendSimpleLandingPacket().
void CCommManager::SendStreamPacket (StreamPkt_t * pPkt)
Send a low level packet of data.
Send the passed stream packet upstream to the ground station or avionics. The packet must be complete, including header and crc. This function will use either the socket or serial interface, depending on how the comm manager was created. If the serial interface is being used, and if the connected system is using 1.1.x format packets this function will reformat the passed packet to use the old stream format before sending it. This function will also perform logging of outgoing data.
Parameters
pPkt points to a complete stream packet.
References CommBase_SendStreamPacket().
void CCommManager::SendSurfaceTestPacket (UInt16 NetworkID, float Angle, float Width, float Freq, float Dev, UInt8 Index)
Create and send a surface test packet.
Create and send a autopilot surface test packet. The surface test packet is used to send test signals to specific control surfaces.
Parameters
NetworkID is the address of the avionics to send the packet to.
Angle is the actuator angle to apply to the test, in rad. Pass more than 3.14 to disable angle test.
Width is the actuator pulse width to apply to the test, in microseconds. Pass zero to disable pulse test.
Freq is the frequency in hertz to use for sinusoidal test, pass more than 0.01 to enable.
Dev is the amplitude of the sinusoidal test in radians.
Index is the index of the control surface to apply the test to.
References CommBase_SendSurfaceTestPacket().
void CCommManager::SendTerrainElevationDataPacket (UInt16 NetworkID, UInt32 Time, float Elevations[6])
Create and send terrain elevation information.
Create and send a packet used to uplink terrain elevation data to the avionics.
Parameters
NetworkID is the address of the avionics to send the packet to.
Time is the system time at which the elevation data apply.
Elevations is the array of terrian elevations spaced 2 seconds apart, with the first element corresponding to Time.
References CommBase_SendTerrainElevationDataPacket().
void CCommManager::SendThrottleMinPacket (UInt16 NetworkID, float Throttle)
Create and send a throttle min packet.
Create and send the throttle minimum command packet. The throttle min packet sets the minimum allowable throttle position for the autopilot
Parameters
NetworkID is the address of the avionics to send the packet to.
Throttle gives the throttle min value, from 0 to 1.0.
References CommBase_SendThrottleMinPacket().
void CCommManager::SendThrottleTrimPacket (UInt16 NetworkID, float Throttle)
Create and send the throttle trim command packet.
Create and send the throttle trim command packet. The throttle trim is used to set the throttle position in prelaunch mode, and to set the autopilot throttle start point.
Parameters
NetworkID is the address of the avionics to send the packet to.
Throttle gives the throttle trim value, from 0 to 1.
References CommBase_SendThrottleTrimPacket().
void CCommManager::SendTrackCommandPacket (UInt16 NetworkID, UInt16 Waypoint, BOOL GoTo)
Create and send a track command packet.
Create and send a track command packet. The track command will tell the autopilot to track to a specific waypoint. The waypoint must already be part of a valid flight plan onboard the autopilot.
Parameters
NetworkID is the address of the avionics to send the packet to.
Waypoint is the index of the waypoint to track to.
GoTo indicates if the vehicle should fly to the waypoint along the preceding track segment, or if it should go directly to the waypoint, using its current position as the starting point. Set to TRUE to go directly to the waypoint.
References CommBase_SendTrackCommandPacket().
void CCommManager::SendTransponderControlPacket (UInt16 NetworkID, UInt16 Code, BOOL Ident, UInt8 Mode)
Create and send a transponder control packet.
Create and send a autopilot transponder control packet. The transponder control packet is used to set the squawk code and ident flag of an external transponder
Parameters
NetworkID is the address of the avionics to send the packet to.
Code is the transponder squawk code to use.
Ident should be true to cause the tranponder to Ident.
Mode is the transponder mode, 0 for standby, 1 for mode A, 2 for mode C, 3 for altitude display.
References CommBase_SendTransponderControlPacket().
void CCommManager::SendTransponderInstallationPacket (UInt16 NetworkID, UInt32 ICAOAddress, const char Registration[9])
Create and send a transponder installation packet.
Create and send a transponder installation packet
References CommBase_SendTransponderInstallationPacket().
void CCommManager::SendTransponderPreflightPacket (UInt16 NetworkID, const char FlightID[9])
Create and send a transponder preflight packet.
Create and send a transponder preflight packet
References CommBase_SendTransponderPreflightPacket().
void CCommManager::SendUserActionPacket (UInt16 NetworkID, UInt8 ActionIndex, BOOL On)
Create and send a user action command packet.
Create and send the user action command
Parameters
NetworkID is the address of the avionics to send the packet to.
ActionIndex is the index of the user action.
On should be TRUE to assert the action.
References CommBase_SendUserActionPacket().
void CCommManager::SendUserSpacePacket (UInt16 NetworkID, const UInt8 User[64])
Create and send a user space packet.
Create and send a user space packet. The user space packet is used to write user data to nonvolatile storage on the avionics. This data space is intended to be used by third-party applications which must store information on the autopilot
Parameters
NetworkID is the address of the avionics to send the packet to.
User is an array of bytes to record on the autopilot.
References CommBase_SendUserSpacePacket().
void CCommManager::SendWaypointListPacket (UInt16 NetworkID, const FPMask_t Mask, UInt8 Flag)
Create and send a waypoint list packet.
Create and send a autopilot waypoint list packet. This packet contains a flight plan mask with one bit for every possible waypoint; and a flags parameter telling the avionics how to use the mask.
Parameters
NetworkID is the address of the avionics to send the packet to.
Mask is the flight plan mask to be encoded.
Flag is the flight plan mask flags field. The flag should have one of these values:
GET_WAYPOINT_LIST: indicates that the avionics should downlink a valid waypoint list.
DELETE_WAYPOINTS: indicates that the avionics should delete each waypoint in the list.
REQUEST_WAYPOINTS: indicates that the avionics should downlink each waypoint in the list.
WAYPOINT_BLOCK: Prepare to receive waypoints (both ways).
WAYPOINT_ACK: Acknowledge receive of waypoints (both ways)
References CommBase_SendWaypointListPacket().
void CCommManager::SendWaypointListRangePacket (UInt16 NetworkID, UInt16 Start, UInt16 End, UInt8 Flag)
Create and send a waypoint list packet using a range of points.
Create and send a autopilot waypoint list packet using a range of points.
Parameters
NetworkID is the address of the avionics to send the packet to.
Start is the first waypoint index to be asserted.
End is the last waypoint index to be asserted.
Flag is the flight plan mask flags field. The flag should have one of these values:
GET_WAYPOINT_LIST: indicates that the avionics should downlink a valid waypoint list.
DELETE_WAYPOINTS: indicates that the avionics should delete each waypoint in the list.
REQUEST_WAYPOINTS: indicates that the avionics should downlink each waypoint in the list.
WAYPOINT_BLOCK: Prepare to receive waypoints (both ways).
WAYPOINT_ACK: Acknowledge receive of waypoints (both ways)
References CommBase_SendWaypointListRangePacket().
void CCommManager::SendWaypointsPacket (UInt16 NetworkID, const FPPoint_t Points[MAX_WAYPOINTS_IN_PACKET], UInt16 Num, BOOL Ack)
Create and send waypoints packet.
Create and send a autopilot waypoints packet. This packet contains all the data for a one or more waypoints, up to MAX_WAYPOINTS_IN_PACKET.
Parameters
NetworkID is the address of the avionics to send the packet to.
Point contains the waypoints data.
Num is the number of waypoints to send.
Ack should be TRUE to set the ack bit.
References CommBase_SendWaypointsPacket().
void CCommManager::SendZeroLengthAutopilotPacket (UInt16 NetworkID, UInt8 PktType)
Send a zero length autopilot packet.
Send a zero length autopilot packet.
Parameters
NetworkID is the destination network address.
PktType is the type of the autopillot packet.
References CommBase_SendZeroLengthAutopilotPacket().
void CCommManager::SendZeroLengthGroundStationPacket (UInt8 PktType)
Send a zero length ground station packet.
Send a zero length autopilot packet.
Parameters
NetworkID is the destination network address.
PktType is the type of the autopillot packet.
References CommBase_SendZeroLengthGroundStationPacket().
void CCommManager::SetNewNetworkCallBack (void(*)(UInt16 NetworkID, void *Parameter) NewNetworkCallBack, void * Parameter)
Register the call back function for new networks.
Whenever the communications manager sees a packet from a new avionics it calls a call back function to alert the application foreground that a new avionics has been found. This function is used to register the call back function that the communications manager will call. The call back function accepts two parameters, the network address of the new avionics, and another parameter which is set through this function.
Detection of a new avionics is done each time the communications manager receives a stream packet from the ground station. A new avionics is detected based on whether or not the network data structure with the corresponding network address already exists. If it does not exist the communications manger will call InitNetwork to create the network data structure and then call the registered call back function to alert the foreground.
Parameters
NewNetworkCallBack is a pointer to the call back function which will be called when a new avionics is detected. The call back function receives as its first parameter the network address of the new avionics. The second parameter is echoed from the second parameter passed to this function.
Parameter is stored and passed to the call back function as its second parameter.
References CommBase_SetNewNetworkCallBack().
void CCommManager::SetReplayFileLocation (UInt32 location)
Set the location of the file position.
Set the location of the replay file position
Parameters
location specifies the location of the replay file
References CommBase_SetReplayFileLocation().
void CCommManager::SetReplayRate (UInt32 ReplayRate)
Set the current replay rate.
Set the replay rate in bytes per second
Parameters
ReplayRate is the number of bytes that will be fetched from the replay file each second
References CommBase_SetReplayRate().
void CCommManager::SetSatcommPhoneNumber (const char * pPhoneNum)
Set/change the satcomm phone number.
Set the phone number used for Iridium sat comm
Parameters
pPhoneNum points to a string with the phone number.
References CommBase_SetSatcommPhoneNumber().
void CCommManager::StartDialingSatcomm (void)
Start the dialing sequence.
Start dialing satcomm (auto-maintain dialed state) If Iridium is not enabled than this function will enable iridium and attemp to dial with the current phone number.
References CommBase_StartDialingSatcomm().
BOOL CCommManager::WriteTextLogHeader (FILE * pFile)
Write the header for the log file.
Write the header for the text log file
Parameters
pFile points to an open stream to write the log file header to.
Returns
TRUE if the header was written successfully, else FALSE
References CommBase_WriteTextLogHeader().
BOOL CCommManager::WriteTextLogLine (FILE * pFile, const UserData_t * pData, UInt8 AckRatio, const double TrackPosition[N3D] = NULL, const float TrackVelocity[N3D] = NULL, const float ADCSample[NUM_EXTERNAL_ADC_PINS] = NULL, const ECU_t * pLeftECU = NULL, const ECU_t * pRightECU = NULL, const MovingBaseStatus_t * pMBStatus = NULL, const GPSUser_t * pGSGPS = NULL, float GSRSSI = 0.0f, float GSPilotPercentage = 0.0f, float GSPilotRate = 0.0f)
Write a single line of data for the log file.
References CommBase_WriteTextLogLine().
The documentation for this class was generated from the following files:
CommManager.h
CommManager.cpp