Communications SDK: CommBase.h File Reference
CommBase.h File Reference
The CCT communication library base module. This module implements the communication interface to the Piccolo autopilot, groundstation, and family of CCT stabilized camera gimbals.
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <math.h>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/ip.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <fcntl.h>
#include <pthread.h>
#include <errno.h>
#include <string.h>
#include "StreamPackets.h"
#include "GimbalPacket.h"
#include "GSPacket.h"
#include "Network.h"
#include "Definitions.h"
#include "AutopilotPacketGnd.h"
#include "Timer.h"
Classes
struct Client_t
struct CommBase_t
The communication interface data structure.
Macros
#define SOCKET_ERROR -1
#define closesocket close
#define MAX_CLIENTS 10
10 possible client sockets
#define MAX_NETS 100
100 possible simultaneous avionics
#define MAX_BUFFER_SIZE 1000
Number of bytes to buffer for UDP data.
Typedefs
typedef void(* NewNetworkCallBackfptr) (UInt16 NetworkID, void *Parameter)
Functions
void CommBase_OpenReplay (CommBase_t *pComm, const char *ReplayFile, int ListenPort)
Open communication interface for file replay.
void CommBase_OpenSerial (CommBase_t *pComm, int Chan, UInt32 Baud, const char *IridiumNumber, int ListenPort, BOOL EnableLogging, const char *LogPath, BOOL ListenOnly)
Open communication interface on serial port.
void CommBase_OpenDevice (CommBase_t *pComm, const char *sDevice, UInt32 Baud, const char *IridiumNumber, int ListenPort, BOOL EnableLogging, const char *LogPath, BOOL ListenOnly)
Open communication interface on device.
void CommBase_OpenSocket (CommBase_t *pComm, const char *ServerAddress, BOOL EnableLogging, const char *LogPath, BOOL ListenOnly)
Open communication interface on network socket.
void CommBase_Close (CommBase_t *pComm)
Close communication interface.
void CommBase_ChangeLogFile (CommBase_t *pComm, BOOL EnableLogging, const char *LogPath)
Change, restart, or stop the log file.
BOOL CommBase_NewSerialPortConfiguration (CommBase_t *pComm, int Chan, UInt32 Baud, const char *IridiumNumber, BOOL EnableLogging, const char *LogPath, BOOL ListenOnly)
Change the serial port configuration.
BOOL CommBase_NewNetworkClientConfiguration (CommBase_t *pComm, const char *ServerAddress, BOOL EnableLogging, const char *LogPath, BOOL ListenOnly)
Change the network client configuration.
BOOL CommBase_NewReplayFileConfiguration (CommBase_t *pComm, const char *ReplayFile)
Change the replay file configuration.
BOOL CommBase_NewNetworkServerConfiguration (CommBase_t *pComm, int ListenPort)
Change the network server configuration.
BOOL CommBase_GetSerialPortConfiguration (CommBase_t *pComm, UInt8 *Chan, UInt32 *Baud)
Return the current serial port parameters.
BOOL CommBase_GetSatCommConfiguration (const CommBase_t *pComm, char *IridiumNumber)
Return the current Iridium configuration.
BOOL CommBase_GetNetworkClientConfiguration (const CommBase_t *pComm, char *ServerAddress)
Return the network client parametes.
BOOL CommBase_GetReplayFileConfiguration (const CommBase_t *pComm, char *ReplayFile)
Return the replay file name.
int CommBase_GetNetworkServerConfiguration (const CommBase_t *pComm)
Return the network server configuration.
void CommBase_GetVersionInformation (Version_t *pVersion)
Get the version of the communications manager software.
Queue_t * CommBase_GetStreamRxBuffer (const CommBase_t *pComm, UInt16 NetworkID, UInt8 Stream)
Get stream receive pointer.
Queue_t * CommBase_GetStreamTxBuffer (const CommBase_t *pComm, UInt16 NetworkID, UInt8 Stream)
Get stream transmit pointer.
Queue_t * CommBase_GetUserLogBuffer (const CommBase_t *pComm)
Get user log buffer pointer.
void CommBase_RunNetwork (CommBase_t *pComm)
Call periodically to service the communications.
void CommBase_SetNewNetworkCallBack (CommBase_t *pComm, void(*NewNetworkCallBack)(UInt16 NetworkID, void *Parameter), void *Parameter)
Register the call back function for new networks.
void CommBase_SendBlock (CommBase_t *pComm, UInt16 NetworkID, UInt8 Stream, UInt8 *pData, UInt32 Size)
Send a block of data in a packet.
void CommBase_SendStreamPacket (CommBase_t *pComm, StreamPkt_t *pPkt)
Send a low level packet of data.
void CommBase_LogUserData (CommBase_t *pComm, UInt8 *pData, UInt32 Size)
Write a block of custom user data to the telemetry file.
SInt32 CommBase_CreateNetwork (CommBase_t *pComm, UInt16 NetworkID)
Creates a network.
void CommBase_DestroyNetwork (CommBase_t *pComm, UInt16 NetworkID)
Destroys a network.
void CommBase_DestroyAllNetworks (CommBase_t *pComm)
Destroys all networks.
UInt32 CommBase_GetNumNets (const CommBase_t *pComm)
Get the number of networks that exist.
SInt32 CommBase_GetIDFromIndex (const CommBase_t *pComm, UInt32 index)
Get the network IDs that are stored by the comm manager.
SInt32 CommBase_GetIndexFromID (const CommBase_t *pComm, UInt16 NetworkID)
Get the index into a network from ID.
void CommBase_PauseReplay (CommBase_t *pComm)
Disable the replay.
void CommBase_ResumeReplay (CommBase_t *pComm)
Enable the replay.
BOOL CommBase_IsInReplay (const CommBase_t *pComm)
Return the state of the replay mode flag.
BOOL CommBase_IsInListenOnly (const CommBase_t *pComm)
Return the state of the listen only mode flag.
UInt32 CommBase_GetNumStreamBytes (const CommBase_t *pComm)
Get the number of bytes read from the groundstation or from the relplay.
UInt32 CommBase_GetFileSize (const CommBase_t *pComm)
Get the size of the log or replay file.
UInt32 CommBase_GetReplayFileLocation (const CommBase_t *pComm)
Get the location of the file position.
void CommBase_SetReplayFileLocation (CommBase_t *pComm, UInt32 location)
Set the location of the file position.
void CommBase_SetReplayRate (CommBase_t *pComm, UInt32 ReplayRate)
Set the current replay rate.
UInt32 CommBase_GetReplayRate (const CommBase_t *pComm)
Get the replay rate.
const char * CommBase_GetLastError (const CommBase_t *pComm)
Get the last error information.
void CommBase_ClearLastError (CommBase_t *pComm)
Clear the error string.
float CommBase_ComputeDownlinkPercent (CommBase_t *pComm, UInt16 NetworkID)
Compute the downlink percentage for a specific network.*/.
size_t CommBase_GetSatcommStatusString (char *String, size_t count)
Get satcomm dialer status string.
size_t CommBase_GetSatcommErrorString (char *String, size_t count)
void CommBase_HangUpSatcommRedial (void)
Hang up satcomm and redial.
void CommBase_HangUpSatcommIdle (void)
Hang up satcomm and go to an idle state.
void CommBase_StartDialingSatcomm (CommBase_t *pComm)
Start the dialing sequence.
void CommBase_SetSatcommPhoneNumber (const char *PhoneNum)
Set/change the satcomm phone number.
void CommBase_SendAutopilotPacket (CommBase_t *pComm, UInt16 NetworkID, const AutopilotPkt_t *pPkt)
Send a autopilot packet.
void CommBase_SendZeroLengthAutopilotPacket (CommBase_t *pComm, UInt16 NetworkID, UInt8 PktType)
Send a zero length autopilot packet.
void CommBase_SendUserActionPacket (CommBase_t *pComm, UInt16 NetworkID, UInt8 ActionIndex, BOOL On)
Create and send a user action command packet.
void CommBase_SendConfigurationLockPacket (CommBase_t *pComm, UInt16 NetworkID, const char Password[32])
Create and send a configuration lock packet.
void CommBase_SendConfigurationUnlockPacket (CommBase_t *pComm, UInt16 NetworkID, const char Password[32], BOOL Silent)
Create and send a configuration unlock packet.
void CommBase_SendControllerDataPacket (CommBase_t *pComm, UInt16 NetworkID, UInt8 Controller, UInt8 Version, UInt8 Category, UInt8 DataID, UInt8 NumData, const void *pData)
Create and send a controller packet.
void CommBase_SendControllerDataDefaultPacket (CommBase_t *pComm, UInt16 NetworkID, UInt8 Controller, UInt8 Version, UInt8 Category, UInt8 DataID, UInt8 NumData)
Create and send a controller packet to default data.
void CommBase_SendTransponderControlPacket (CommBase_t *pComm, UInt16 NetworkID, UInt16 Code, BOOL Ident, UInt8 Mode)
Create and send a transponder control packet.
void CommBase_SendTransponderPreflightPacket (CommBase_t *pComm, UInt16 NetworkID, const char FlightID[9])
Create and send a transponder preflight packet.
void CommBase_SendTransponderInstallationPacket (CommBase_t *pComm, UInt16 NetworkID, UInt32 ICAOAddress, const char Registration[9])
Create and send a transponder installation packet.
void CommBase_SendRadioSettingsPacket (CommBase_t *pComm, UInt16 NetworkID, const RadioSettings_t *pSettings)
Create and send a radio settings packet.
void CommBase_SendAutopilotLoopControlPacket (CommBase_t *pComm, UInt16 NetworkID, const AutopilotLoopCmd_t *pCmd, BOOL UpdateEEPROM)
Create and send a autopilot loop control packet.
void CommBase_SendActuatorTablePacket (CommBase_t *pComm, UInt16 NetworkID, const ActuatorTable_t *pTable, UInt8 Sur, UInt8 Type, UInt8 Virtual, UInt8 Fast)
Create and send a control actuator calibration packet.
void CommBase_SendActuatorTypePacket (CommBase_t *pComm, UInt16 NetworkID, UInt8 Sur, UInt8 Type)
Create and send a packet to change actuator type.
void CommBase_SendOrientationPacket (CommBase_t *pComm, UInt16 NetworkID, const float Euler[NAXIS], const float IMUtoAnt[N3D], const float IMUtoAnt2[N3D])
Create and send a sensor orientatin packet.
void CommBase_SendWaypointsPacket (CommBase_t *pComm, UInt16 NetworkID, const FPPoint_t Points[MAX_WAYPOINTS_IN_PACKET], UInt16 Num, BOOL Ack)
Create and send waypoints packet.
void CommBase_SendWaypointListPacket (CommBase_t *pComm, UInt16 NetworkID, const FPMask_t Mask, UInt8 Flag)
Create and send a waypoint list packet.
void CommBase_SendWaypointListRangePacket (CommBase_t *pComm, UInt16 NetworkID, UInt16 Start, UInt16 End, UInt8 Flag)
Create and send a waypoint list packet using a range of points.
void CommBase_SendLegacyWaypointPacket (CommBase_t *pComm, UInt16 NetworkID, const FPPoint_t *pPoint, UInt8 Index)
Create and send a legacy waypoint packet.
void CommBase_SendLegacyWaypointListPacket (CommBase_t *pComm, UInt16 NetworkID, const FPMask_t Mask, UInt8 Flag)
Create and send a legacy waypoint list packet.
void CommBase_SendSurfaceTestPacket (CommBase_t *pComm, UInt16 NetworkID, float Angle, float Width, float Freq, float Dev, UInt8 Index)
Create and send a surface test packet.
void CommBase_SendMissionLimitsPacket (CommBase_t *pComm, UInt16 NetworkID, const MissionLimits_t *pMission)
Create and send a mission limits packet.
void CommBase_SendMissionSettingsPacket (CommBase_t *pComm, UInt16 NetworkID, SInt16 MinAltitude, SInt16 MaxAltitude, UInt32 FlightTimeout)
Create and a send a mission settings packet.
void CommBase_SendBoundaryPacket (CommBase_t *pComm, UInt16 NetworkID, const Boundary_t *pBnd)
Create and send a airspace boundary packet.
void CommBase_SendMagCalPacket (CommBase_t *pComm, UInt16 NetworkID, const float HardIronErr[N3D], const float ScaleFactErr[N3D])
Create and send a magnetic sensor calibration packet.
void CommBase_SendSensorErrorPacket (CommBase_t *pComm, UInt16 NetworkID, const SensorErrorData_t *pSensorError)
Create and send a sensor error.
void CommBase_SendExternalSerialSetupPacket (CommBase_t *pComm, UInt16 NetworkID, const ExternalSerial_t *pSerial)
Create and send a external serial setup packet.
void CommBase_SendExternalIOSetupPacket (CommBase_t *pComm, UInt16 NetworkID, const ExternalIO_t *pExternalIO, UInt8 pin, UInt32 SampleTime, BOOL UpdateEEPROM)
Create and send a external IO setup packet.
void CommBase_SendSimpleLandingPacket (CommBase_t *pComm, UInt16 NetworkID, const SimpleLandingPattern_t *pLand)
Create and send a simple landing packet.
void CommBase_SendAltimeterSettingPacket (CommBase_t *pComm, UInt16 NetworkID, UInt32 Altimeter, BOOL ControlToGPS)
Create and send an altimeter setting packet.
void CommBase_SendBandwidthModePacket (CommBase_t *pComm, UInt16 NetworkID, BandwidthMode_t Bandwidth)
Create and send a bandwidth mode packet.
void CommBase_SendEngineKillPacket (CommBase_t *pComm, UInt16 NetworkID, BOOL EngineKill)
Create and send the engine kill packet.
void CommBase_SendLandNowPacket (CommBase_t *pComm, UInt16 NetworkID)
Create and send the land now command packet.
void CommBase_SendLaunchNowPacket (CommBase_t *pComm, UInt16 NetworkID)
Create and send the launch now command packet.
void CommBase_SendPrelaunchPacket (CommBase_t *pComm, UInt16 NetworkID)
Create and send the go to prelaunch command packet.
void CommBase_SendAirDataZeroPacket (CommBase_t *pComm, UInt16 NetworkID, float ActualAltitude)
Create and send the zero air data command packet.
void CommBase_SendManualAssistModePacket (CommBase_t *pComm, UInt16 NetworkID, UInt8 Mode)
Create and send the manual assist mode command packet.
void CommBase_SendLightsCommandPacket (CommBase_t *pComm, UInt16 NetworkID, BOOL LightsOn)
Create and send the lights command packet.
void CommBase_SendDropCommandPacket (CommBase_t *pComm, UInt16 NetworkID, BOOL DropOn)
Create and send the drop command packet.
void CommBase_SendParachuteCommandPacket (CommBase_t *pComm, UInt16 NetworkID, BOOL ParachuteDeploy)
Create and send the parachute command packet.
void CommBase_SendBrakesCommandPacket (CommBase_t *pComm, UInt16 NetworkID, float Brakes)
Create and send the brakes command packet.
void CommBase_SendThrottleTrimPacket (CommBase_t *pComm, UInt16 NetworkID, float Throttle)
Create and send the throttle trim command packet.
void CommBase_SendTrackCommandPacket (CommBase_t *pComm, UInt16 NetworkID, UInt16 Waypoint, BOOL GoTo)
Create and send a track command packet.
void CommBase_SendDescriptionPacket (CommBase_t *pComm, UInt16 NetworkID, const char Description[64])
Create and send a parameter description packet.
void CommBase_SendUserSpacePacket (CommBase_t *pComm, UInt16 NetworkID, const UInt8 User[64])
Create and send a user space packet.
void CommBase_SendDoubletCommandPacket (CommBase_t *pComm, UInt16 NetworkID, const DoubletCmd_t *pDoublet)
Create and send a doublet command packet.
void CommBase_SendFrequencySweepCommandPacket (CommBase_t *pComm, UInt16 NetworkID, const FrequencySweepCmd_t *pFreqSwp)
Create and send a frequency sweep command packet.
void CommBase_SendSetFuelLevelPacket (CommBase_t *pComm, UInt16 NetworkID, float Fuel, BOOL Electric)
Create and send a set fuel level packet.
void CommBase_SendSetFuelIfLockedPacket (CommBase_t *pComm, UInt16 NetworkID, float Fuel, BOOL Electric)
Create and send a set fuel level packet for fuel update while locked.
void CommBase_SendPayloadMassPacket (CommBase_t *pComm, UInt16 NetworkID, float PayloadMass)
Create and send a payload mass packet.
void CommBase_SendThrottleMinPacket (CommBase_t *pComm, UInt16 NetworkID, float Throttle)
Create and send a throttle min packet.
void CommBase_SendFeatureCodePacket (CommBase_t *pComm, UInt16 NetworkID, const UInt8 Data[8])
Create and send a feature code packet.
void CommBase_SendTerrainElevationDataPacket (CommBase_t *pComm, UInt16 NetworkID, UInt32 Time, float Elevations[6])
Create and send terrain elevation information.
void CommBase_RequestControllerDataPacket (CommBase_t *pComm, UInt16 NetworkID, UInt8 Controller, UInt8 Version, UInt8 Category, UInt8 DataID, UInt8 NumData)
Request some controller data.
void CommBase_RequestTransponderControlPacket (CommBase_t *pComm, UInt16 NetworkID)
Request the transponder control packet.
void CommBase_RequestTransponderPreflightPacket (CommBase_t *pComm, UInt16 NetworkID)
Request the transponder preflight packet.
void CommBase_RequestTransponderInstallationPacket (CommBase_t *pComm, UInt16 NetworkID)
Request the transponder installation packet.
void CommBase_RequestRadioSettingsPacket (CommBase_t *pComm, UInt16 NetworkID)
Request the radio settings packet.
void CommBase_RequestActuatorTablePacket (CommBase_t *pComm, UInt16 NetworkID, UInt8 Sur)
Request the autopilot surface table calibration packet.
void CommBase_RequestOrientationPacket (CommBase_t *pComm, UInt16 NetworkID)
Request the autopilot orientation packet.
void CommBase_RequestMissionLimitsPacket (CommBase_t *pComm, UInt16 NetworkID)
Request the autopilot mission limits packet.
void CommBase_RequestMagCalPacket (CommBase_t *pComm, UInt16 NetworkID)
Request the packet with the magnetometer calibration data.
void CommBase_RequestSensorErrorPacket (CommBase_t *pComm, UInt16 NetworkID)
Request the packet with the sensor error data.
void CommBase_RequestExternalSerialSetupPacket (CommBase_t *pComm, UInt16 NetworkID)
Request the autopilot packet with the external serial setup parameters.
void CommBase_RequestExternalIOSetupPacket (CommBase_t *pComm, UInt16 NetworkID, UInt8 pin)
Request then autopilot packet with the setup parameters for a single external IO pin.
void CommBase_RequestDescriptionPacket (CommBase_t *pComm, UInt16 NetworkID)
Request the parameter description packet.
void CommBase_RequestUserSpacePacket (CommBase_t *pComm, UInt16 NetworkID)
Request the user space packet.
void CommBase_RequestAltimeterSettingPacket (CommBase_t *pComm, UInt16 NetworkID)
Request the altimeter setting packet.
void CommBase_RequestBandwidthModePacket (CommBase_t *pComm, UInt16 NetworkID, UInt8 NetID)
Request the bandwidth mode packet.
void CommBase_RequestSystemVersionPacket (CommBase_t *pComm, UInt16 NetworkID)
Request system version packet.
void CommBase_RequestRawVibrationDataPacket (CommBase_t *pComm, UInt16 NetworkID)
Request the raw vibration sensor data.
void CommBase_RequestPayloadMassPacket (CommBase_t *pComm, UInt16 NetworkID)
Request the payload mass packet.
void CommBase_RequestThrottleMinPacket (CommBase_t *pComm, UInt16 NetworkID)
Request the throttle min packet.
BOOL CommBase_WriteTextLogHeader (FILE *pFile)
Write the header for the log file.
BOOL CommBase_WriteTextLogLine (FILE *pFile, const UserData_t *pData, UInt8 AckRatio, const double TrackPosition[N3D], const float TrackVelocity[N3D], const float ADCSample[NUM_EXTERNAL_ADC_PINS], const ECU_t *pLeftECU, const ECU_t *pRightECU, const MovingBaseStatus_t *pMBStatus, const GPSUser_t *pGSGPS, float GSRSSI, float GSPilotPercentage, float GSPilotRate)
Write a single line of data for the log file.
void CommBase_SendGroundStationPacket (CommBase_t *pComm, const GroundStationPkt_t *pPkt)
Send an groundstation packet.
void CommBase_SendZeroLengthGroundStationPacket (CommBase_t *pComm, UInt8 PktType)
Send a zero length ground station packet.
void CommBase_SendGSAddAddressPacket (CommBase_t *pComm, UInt16 Address)
Create and send a ground station add address packet.
void CommBase_SendGSAddPilotAddressPacket (CommBase_t *pComm, UInt16 Pilot)
Create and send a ground station add pilot address packet.
void CommBase_SendGSDeleteAddressPacket (CommBase_t *pComm, UInt16 DelAddress, UInt16 KeepAddress)
Create and send a ground station delete address packet.
void CommBase_SendGSRadioSettingsPacket (CommBase_t *pComm, const RadioSettings_t *pSettings)
Create and a ground station radio settings packet.
void CommBase_SendDGPSBasePacket (CommBase_t *pComm, const DGPSParameter_t *pDGPS)
Create and send a ground station differential corrections packet.
void CommBase_SendGSDynamicEnumerationPacket (CommBase_t *pComm, BOOL On)
Create and send a dynamic enumeration on/off packet.
void CommBase_SendGSConfiguration (CommBase_t *pComm, UInt8 ConfigEnum, UInt8 SBASDisable, UInt8 EnableGD, UInt32 Baud, UInt8 EnableMHXRelay)
Create and send a ground station configuration packet.
void CommBase_RequestGSRadioSettingsPacket (CommBase_t *pComm)
Request ground station radio settings.
void CommBase_RequestGSCoherentSpectrumSweepPacket (CommBase_t *pComm, float StartFreq, float Spacing, UInt16 Dwell, UInt8 NumMeasurements)
Request ground station spectrum sweep, coherent frequency radio.
void CommBase_RequestGSHoppingSpectrumSweepPacket (CommBase_t *pComm)
Request ground station spectrum sweep, hopping radio.
void CommBase_RequestGSFirmwarePacket (CommBase_t *pComm)
Request the software and hardware configuration settings from the ground station.
void CommBase_RequestDGPSBasePacket (CommBase_t *pComm)
Request the packet with DGPS base settings.
void CommBase_SendGimbalPacket (CommBase_t *pComm, UInt16 NetworkID, const GimbalPkt_t *pPkt)
Send a gimbal packet on the gimbal stream to the autopilot.
void CommBase_SendGimbalCmdPacket (CommBase_t *pComm, UInt16 NetworkID, float Pan, float Tilt, SInt8 ZoomRate, float CamTimeout, UInt8 Flags, float ImpulseTime, SInt8 FocusRate, UInt8 Flags1)
Create and send a gimbal command packet containing pan, tilt, zoom and focus rate, and mode.
void CommBase_SendGimbalSPOICmdPacket (CommBase_t *pComm, UInt16 NetworkID, const double Pos[NPOS], const float Vel[NDIR], UInt8 Flags)
Create and send a gimbal sensor point of interest packet containing the position of the SPOI.
void CommBase_SendGimbalCameraCmdPacket (CommBase_t *pComm, UInt16 NetworkID, UInt8 Camera, float HFOV, UInt16 Focus, UInt8 Mode, UInt8 Shutter, UInt8 Bright, UInt8 Flags)
Create and send a camera command packet.
void CommBase_SendGimbalAxisSettingsPacket (CommBase_t *pComm, UInt16 NetworkID, const float NoGoCenter[NGIMBAL_SHORT], const float NoGoRange[NGIMBAL_SHORT], const float MaxRate[NGIMBAL_SHORT], const float MaxAccel[NGIMBAL_SHORT], const float PosGain[NGIMBAL_SHORT], const float VelGain[NGIMBAL_SHORT], const float DerGain[NGIMBAL_SHORT], BOOL Temporary, BOOL Factory)
Create and send a gimbal axis settings packet.
void CommBase_SendGimbalSerialInterfacePacket (CommBase_t *pComm, UInt16 NetworkID, GimbalSerial_t Serial[6], BOOL Temporary)
Create and send gimbal packet rate packet.
void CommBase_SendGimbalCameraAlignPacket (CommBase_t *pComm, UInt16 NetworkID, float Zoom1, const float Error1[NGIMBAL], float Zoom2, const float Error2[NGIMBAL], UInt8 Camera, BOOL Factory)
Create and send gimbal camera alignment packet.
void CommBase_SendGimbalCameraTypesPacket (CommBase_t *pComm, UInt16 NetworkID, const CameraDefinition_t Cam[NUM_CAMERAS], const BOOL Send[NUM_CAMERAS], BOOL Factory)
Create and send gimbal camera definitions packet.
void CommBase_SendGimbalLaserSetupPacket (CommBase_t *pComm, UInt16 NetworkID, LaserSetup_t Lasers[NUM_LASERS], BOOL Factory)
Create and send gimbal laser setup packet.
void CommBase_SendGimbalLaserArmPacket (CommBase_t *pComm, UInt16 NetworkID, UInt8 LaserIndex, BOOL Arm)
Create and send gimbal laser arm packet.
void CommBase_SendGimbalLaserFirePacket (CommBase_t *pComm, UInt16 NetworkID, UInt8 LaserIndex, UInt8 Power)
Create and send gimbal laser fire packet.
void CommBase_SendGimbalRetractDeployCmdPacket (CommBase_t *pComm, UInt16 NetworkID, UInt32 Deploy)
Create and send gimbal retract/deploy command.
void CommBase_SendGimbalTrackCmdPacket (CommBase_t *pComm, UInt16 NetworkID, float InitialX, float InitialY, UInt8 Algorithm, UInt8 Size, UInt8 Stamp)
Create and send gimbal track command packet.
void CommBase_RequestGimbalSPOICmdPacket (CommBase_t *pComm, UInt16 NetworkID)
Request a sensor point of interest command packet.
void CommBase_RequestGimbalCameraCmdPacket (CommBase_t *pComm, UInt16 NetworkID, UInt8 Camera)
Request a camera command packet.
void CommBase_RequestGimbalAxisSettingsPacket (CommBase_t *pComm, UInt16 NetworkID, BOOL Factory)
Request a gimbal axis settings packet.
void CommBase_RequestGimbalCameraAlignPacket (CommBase_t *pComm, UInt16 NetworkID, UInt8 Camera, BOOL Factory)
Request camera alignment information.
void CommBase_RequestGimbalCameraTypesPacket (CommBase_t *pComm, UInt16 NetworkID, BOOL Factory)
Request gimbal camera types.
void CommBase_RequestGimbalLaserSetupPacket (CommBase_t *pComm, UInt16 NetworkID, BOOL Factory)
Request gimbal laser setup.
Detailed Description
The CCT communication library base module. This module implements the communication interface to the Piccolo autopilot, groundstation, and family of CCT stabilized camera gimbals.
Macro Definition Documentation
#define MAX_BUFFER_SIZE 1000
Number of bytes to buffer for UDP data.
#define MAX_CLIENTS 10
10 possible client sockets
#define MAX_NETS 100
100 possible simultaneous avionics
Typedef Documentation
typedef void(* NewNetworkCallBackfptr) (UInt16 NetworkID, void *Parameter)
New network callback function pointer type
Function Documentation
void CommBase_ChangeLogFile (CommBase_t * pComm, BOOL EnableLogging, const char * LogPath)
Change, restart, or stop the log file.
Referenced by CCommManager::ChangeLogFile().
void CommBase_ClearLastError (CommBase_t * pComm)
Clear the error string.
Referenced by CCommManager::ClearLastError().
void CommBase_Close (CommBase_t * pComm)
Close communication interface.
Referenced by CCommManager::~CCommManager().
float CommBase_ComputeDownlinkPercent (CommBase_t * pComm, UInt16 NetworkID)
Compute the downlink percentage for a specific network.*/.
Referenced by CCommManager::ComputeDownlinkPercent().
SInt32 CommBase_CreateNetwork (CommBase_t * pComm, UInt16 NetworkID)
Creates a network.
Referenced by CCommManager::CreateNetwork().
void CommBase_DestroyAllNetworks (CommBase_t * pComm)
Destroys all networks.
Referenced by CCommManager::DestroyAllNetworks().
void CommBase_DestroyNetwork (CommBase_t * pComm, UInt16 NetworkID)
Destroys a network.
Referenced by CCommManager::DestroyNetwork().
UInt32 CommBase_GetFileSize (const CommBase_t * pComm)
Get the size of the log or replay file.
Referenced by CCommManager::GetFileSize().
SInt32 CommBase_GetIDFromIndex (const CommBase_t * pComm, UInt32 index)
Get the network IDs that are stored by the comm manager.
Referenced by CCommManager::GetIDFromIndex().
SInt32 CommBase_GetIndexFromID (const CommBase_t * pComm, UInt16 NetworkID)
Get the index into a network from ID.
Referenced by CCommManager::GetIndexFromID().
const char* CommBase_GetLastError (const CommBase_t * pComm)
Get the last error information.
Referenced by CCommManager::GetLastError().
BOOL CommBase_GetNetworkClientConfiguration (const CommBase_t * pComm, char * ServerAddress)
Return the network client parametes.
Referenced by CCommManager::GetNetworkClientConfiguration().
int CommBase_GetNetworkServerConfiguration (const CommBase_t * pComm)
Return the network server configuration.
Referenced by CCommManager::GetNetworkServerConfiguration().
UInt32 CommBase_GetNumNets (const CommBase_t * pComm)
Get the number of networks that exist.
Referenced by CCommManager::GetNumNets().
UInt32 CommBase_GetNumStreamBytes (const CommBase_t * pComm)
Get the number of bytes read from the groundstation or from the relplay.
Referenced by CCommManager::GetNumStreamBytes().
BOOL CommBase_GetReplayFileConfiguration (const CommBase_t * pComm, char * ReplayFile)
Return the replay file name.
Referenced by CCommManager::GetReplayFileConfiguration().
UInt32 CommBase_GetReplayFileLocation (const CommBase_t * pComm)
Get the location of the file position.
Referenced by CCommManager::GetReplayFileLocation().
UInt32 CommBase_GetReplayRate (const CommBase_t * pComm)
Get the replay rate.
Referenced by CCommManager::GetReplayRate().
BOOL CommBase_GetSatCommConfiguration (const CommBase_t * pComm, char * IridiumNumber)
Return the current Iridium configuration.
Referenced by CCommManager::GetSatCommConfiguration().
size_t CommBase_GetSatcommStatusString (char * String, size_t count)
Get satcomm dialer status string.
Referenced by CCommManager::GetSatcommStatusString().
BOOL CommBase_GetSerialPortConfiguration (CommBase_t * pComm, UInt8 * Chan, UInt32 * Baud)
Return the current serial port parameters.
Referenced by CCommManager::GetSerialPortConfiguration().
Queue_t* CommBase_GetStreamRxBuffer (const CommBase_t * pComm, UInt16 NetworkID, UInt8 Stream)
Get stream receive pointer.
Referenced by CCommManager::GetStreamRxBuffer().
Queue_t* CommBase_GetStreamTxBuffer (const CommBase_t * pComm, UInt16 NetworkID, UInt8 Stream)
Get stream transmit pointer.
Referenced by CCommManager::GetStreamTxBuffer().
Queue_t* CommBase_GetUserLogBuffer (const CommBase_t * pComm)
Get user log buffer pointer.
Referenced by CCommManager::GetUserLogBuffer().
void CommBase_GetVersionInformation (Version_t * pVersion)
Get the version of the communications manager software.
Referenced by CCommManager::GetVersionInformation().
void CommBase_HangUpSatcommIdle (void)
Hang up satcomm and go to an idle state.
Referenced by CCommManager::HangUpSatcommIdle().
void CommBase_HangUpSatcommRedial (void)
Hang up satcomm and redial.
Referenced by CCommManager::HangUpSatcommRedial().
BOOL CommBase_IsInListenOnly (const CommBase_t * pComm)
Return the state of the listen only mode flag.
Referenced by CCommManager::IsInListenOnly().
BOOL CommBase_IsInReplay (const CommBase_t * pComm)
Return the state of the replay mode flag.
Referenced by CCommManager::IsInReplay().
void CommBase_LogUserData (CommBase_t * pComm, UInt8 * pData, UInt32 Size)
Write a block of custom user data to the telemetry file.
Referenced by CCommManager::LogUserData().
BOOL CommBase_NewNetworkClientConfiguration (CommBase_t * pComm, const char * ServerAddress, BOOL EnableLogging, const char * LogPath, BOOL ListenOnly)
Change the network client configuration.
Referenced by CCommManager::NewNetworkClientConfiguration().
BOOL CommBase_NewNetworkServerConfiguration (CommBase_t * pComm, int ListenPort)
Change the network server configuration.
Referenced by CCommManager::NewNetworkServerConfiguration().
BOOL CommBase_NewReplayFileConfiguration (CommBase_t * pComm, const char * ReplayFile)
Change the replay file configuration.
Referenced by CCommManager::NewReplayFileConfiguration().
BOOL CommBase_NewSerialPortConfiguration (CommBase_t * pComm, int Chan, UInt32 Baud, const char * IridiumNumber, BOOL EnableLogging, const char * LogPath, BOOL ListenOnly)
Change the serial port configuration.
Referenced by CCommManager::NewSerialPortConfiguration().
void CommBase_OpenDevice (CommBase_t * pComm, const char * sDevice, UInt32 Baud, const char * IridiumNumber, int ListenPort, BOOL EnableLogging, const char * LogPath, BOOL ListenOnly)
Open communication interface on device.
void CommBase_OpenReplay (CommBase_t * pComm, const char * ReplayFile, int ListenPort)
Open communication interface for file replay.
Referenced by CCommManager::CCommManager().
void CommBase_OpenSerial (CommBase_t * pComm, int Chan, UInt32 Baud, const char * IridiumNumber, int ListenPort, BOOL EnableLogging, const char * LogPath, BOOL ListenOnly)
Open communication interface on serial port.
Referenced by CCommManager::CCommManager().
void CommBase_OpenSocket (CommBase_t * pComm, const char * ServerAddress, BOOL EnableLogging, const char * LogPath, BOOL ListenOnly)
Open communication interface on network socket.
Referenced by CCommManager::CCommManager().
void CommBase_PauseReplay (CommBase_t * pComm)
Disable the replay.
Referenced by CCommManager::PauseReplay().
void CommBase_RequestActuatorTablePacket (CommBase_t * pComm, UInt16 NetworkID, UInt8 Sur)
Request the autopilot surface table calibration packet.
Request the autopilot actuator table calibration packet. The actuator calibration packet encodes the relationship between pulse width and actuator angle for a single actuator.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
Sur is the actuator index that the table refers to.
References ACTUATOR_TABLE, CommBase_SendAutopilotPacket(), SimplePkt_t::Data, and MakeAutopilotPacket().
Referenced by CCommManager::RequestActuatorTablePacket().
void CommBase_RequestAltimeterSettingPacket (CommBase_t * pComm, UInt16 NetworkID)
Request the altimeter setting packet.
Request the altimeter setting packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References ALTIMETER_SETTING, and CommBase_SendZeroLengthAutopilotPacket().
Referenced by CCommManager::RequestAltimeterSettingPacket().
void CommBase_RequestBandwidthModePacket (CommBase_t * pComm, UInt16 NetworkID, UInt8 NetID)
Request the bandwidth mode packet.
Request the bandwidth mode packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
NetID enumerates which link on the autopilot the data should come from, pass 0xFF to use the link this packet arrives on
References BANDWIDTH_MODE, CommBase_SendAutopilotPacket(), SimplePkt_t::Data, and MakeAutopilotPacket().
Referenced by CCommManager::RequestBandwidthModePacket().
void CommBase_RequestControllerDataPacket (CommBase_t * pComm, UInt16 NetworkID, UInt8 Controller, UInt8 Version, UInt8 Category, UInt8 DataID, UInt8 NumData)
Request some controller data.
Create and send a controller data request packet
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
Controller is the controller ID value.
Version is the controller version value.
Category is the data category.
DataID is the starting DataID.
NumData is the number of data elements to request.
References CommBase_SendAutopilotPacket(), and FormControllerDataRequestPacket().
Referenced by CCommManager::RequestControllerDataPacket().
void CommBase_RequestDescriptionPacket (CommBase_t * pComm, UInt16 NetworkID)
Request the parameter description packet.
Request the parameter description packet. The parameter description is a string which can be used to identify the set of parameters stored on the autopilot.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References CommBase_SendZeroLengthAutopilotPacket(), and DESCRIPTION.
Referenced by CCommManager::RequestDescriptionPacket().
void CommBase_RequestDGPSBasePacket (CommBase_t * pComm)
Request the packet with DGPS base settings.
Request the DGPS setup from the groundstation.
Parameters
pComm points to the communication interface data.
References CommBase_SendZeroLengthGroundStationPacket(), and DGPS_SETTINGS.
Referenced by CCommManager::RequestDGPSBasePacket().
void CommBase_RequestExternalIOSetupPacket (CommBase_t * pComm, UInt16 NetworkID, UInt8 pin)
Request then autopilot packet with the setup parameters for a single external IO pin.
Request then autopilot packet with the setup parameters for a single external IO pin.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
pin identifies which IO pin these setup data apply to.
References CommBase_SendAutopilotPacket(), SimplePkt_t::Data, EXTERNAL_IO_SETUP, and MakeAutopilotPacket().
Referenced by CCommManager::RequestExternalIOSetupPacket().
void CommBase_RequestExternalSerialSetupPacket (CommBase_t * pComm, UInt16 NetworkID)
Request the autopilot packet with the external serial setup parameters.
Request then autopilot packet with the external serial setup parameters.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References CommBase_SendZeroLengthAutopilotPacket(), and EXTERNAL_SERIAL_SETUP.
Referenced by CCommManager::RequestExternalSerialSetupPacket().
void CommBase_RequestGimbalAxisSettingsPacket (CommBase_t * pComm, UInt16 NetworkID, BOOL Factory)
Request a gimbal axis settings packet.
Request a gimbal axis settings packet which contains the data to setup the axis control for custom configurations.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
Factory should be TRUE to request factory settings.
References AXIS_SETTINGS_GIMBAL_PKTTYPE, CommBase_SendGimbalPacket(), FACTORY_AXIS_SETTINGS_GIMBAL_PKTTYPE, GIMBAL_SETUP_GROUP, and MakeGimbalPacket().
Referenced by CCommManager::RequestGimbalAxisSettingsPacket().
void CommBase_RequestGimbalCameraAlignPacket (CommBase_t * pComm, UInt16 NetworkID, UInt8 Camera, BOOL Factory)
Request camera alignment information.
Request a gimbal camera alignment packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
Camera enumerates the camera to request alignment data for.
Factory should be TRUE to request factory settings
References CAMERA_ALIGN_GIMBAL_PKTTYPE, ChecksumGimbalPacket(), CommBase_SendGimbalPacket(), GimbalPkt_t::Data, FACTORY_CAMERA_ALIGN_GIMBAL_PKTTYPE, GIMBAL_SETUP_GROUP, and MakeGimbalPacketHeader().
Referenced by CCommManager::RequestGimbalCameraAlignPacket().
void CommBase_RequestGimbalCameraCmdPacket (CommBase_t * pComm, UInt16 NetworkID, UInt8 Camera)
Request a camera command packet.
Request a camera command packet containing the field of view, focus, and exposure settings.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
Camera identifies which camera to request data for.
References CAMERA_CMD_GIMBAL_PKTTYPE, ChecksumGimbalPacket(), CommBase_SendGimbalPacket(), GimbalPkt_t::Data, GIMBAL_COMMAND_AND_CONTROL_GROUP, and MakeGimbalPacketHeader().
Referenced by CCommManager::RequestGimbalCameraCmdPacket().
void CommBase_RequestGimbalCameraTypesPacket (CommBase_t * pComm, UInt16 NetworkID, BOOL Factory)
Request gimbal camera types.
Request gimbal camera types.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
Factory should be TRUE to request factory settings.
References CAMERA_DEFINITION_GIMBAL_PKTTYPE, CommBase_SendGimbalPacket(), FACTORY_CAMERA_DEFINITION_GIMBAL_PKTTYPE, GIMBAL_SETUP_GROUP, and MakeGimbalPacket().
Referenced by CCommManager::RequestGimbalCameraTypesPacket().
void CommBase_RequestGimbalLaserSetupPacket (CommBase_t * pComm, UInt16 NetworkID, BOOL Factory)
Request gimbal laser setup.
Request gimbal laser setup.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
Factory should be TRUE to request factory settings.
References CommBase_SendGimbalPacket(), FACTORY_LASERS_INSTALLED_GIMBAL_PKTTYPE, GIMBAL_SETUP_GROUP, LASERS_INSTALLED_GIMBAL_PKTTYPE, and MakeGimbalPacket().
Referenced by CCommManager::RequestGimbalLaserSetupPacket().
void CommBase_RequestGimbalSPOICmdPacket (CommBase_t * pComm, UInt16 NetworkID)
Request a sensor point of interest command packet.
Request a gimbal sensor point of interest (SPOI) cmd packet. The SPOI packet tells the gimbal where to point in LLA coordinates relative to the WGS-84 ellipsoid.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References CommBase_SendGimbalPacket(), GIMBAL_POSITION_INFORMATION_GROUP, MakeGimbalPacket(), and SPOI_CMD_GIMBAL_PKTTYPE.
Referenced by CCommManager::RequestGimbalSPOICmdPacket().
void CommBase_RequestGSCoherentSpectrumSweepPacket (CommBase_t * pComm, float StartFreq, float Spacing, UInt16 Dwell, UInt8 NumMeasurements)
Request ground station spectrum sweep, coherent frequency radio.
Request ground station spectrum sweep. This puts the coherent frequency MHX radio in a scanning mode mesureing the signal strength at each user specified frequency. If the MXH radio in the groundstation is not coherent (i.e. it is hopping) then the user settings will not apply.
Parameters
pComm points to the communication interface data.
pPkt points to a stream packet to receive the formatted data.
StartFreq is the frequency to begin the sweep in MHz.
Spacing is the space between frequencies in MHz.
Dwell is the dwell time for each measurement in ms.
NumMeasurements is the number of measurements to make.
References CommBase_SendGroundStationPacket(), FormGSSpectrumSweepDetails(), GS_SPECTRUM2, and MakeGroundStationPacket().
Referenced by CCommManager::RequestGSSpectrumSweepPacket().
void CommBase_RequestGSFirmwarePacket (CommBase_t * pComm)
Request the software and hardware configuration settings from the ground station.
Request the software and hardware configuration settings from the ground station.
Parameters
pComm points to the communication interface data.
References CommBase_SendZeroLengthGroundStationPacket(), and GS_VERSION.
Referenced by CCommManager::RequestGSFirmwarePacket().
void CommBase_RequestGSHoppingSpectrumSweepPacket (CommBase_t * pComm)
Request ground station spectrum sweep, hopping radio.
Request a ground station spectrum sweep from a hopping MHX radio. If the MHX radio in the ground station is not hopping (i.e. it is coherent) then the swpecturm sweep will be performed with default user settings.
Parameters
pComm points to the communication interface data.
References CommBase_SendZeroLengthGroundStationPacket(), and GS_SPECTRUM.
Referenced by CCommManager::RequestGSSpectrumSweepPacket().
void CommBase_RequestGSRadioSettingsPacket (CommBase_t * pComm)
Request ground station radio settings.
Request the groundstation radio settings packet. The radio settings packet is used to control the channel and output power of the radio.
Parameters
pComm points to the communication interface data.
References CommBase_SendZeroLengthGroundStationPacket(), and GS_RADIO_SETTINGS.
Referenced by CCommManager::RequestGSRadioSettingsPacket().
void CommBase_RequestMagCalPacket (CommBase_t * pComm, UInt16 NetworkID)
Request the packet with the magnetometer calibration data.
Request the packet with the magnetometer calibration data.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References CommBase_SendZeroLengthAutopilotPacket(), and MAG_CALIBRATION.
Referenced by CCommManager::RequestMagCalPacket().
void CommBase_RequestMissionLimitsPacket (CommBase_t * pComm, UInt16 NetworkID)
Request the autopilot mission limits packet.
Request the autopilot mission limits packet. The mission limits packet contains timeouts and actions which limit are used to limit the scope of the mission.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References CommBase_SendZeroLengthAutopilotPacket(), and MISSION_LIMITS.
Referenced by CCommManager::RequestMissionLimitsPacket().
void CommBase_RequestOrientationPacket (CommBase_t * pComm, UInt16 NetworkID)
Request the autopilot orientation packet.
Request the autopilot orientation packet. The orientation packet describes the installed orientation of the Piccolo avionics as Euler angle rotations from the avionics frame to the vehicle frame.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References CommBase_SendZeroLengthAutopilotPacket(), and SENSOR_ORIENTATION.
Referenced by CCommManager::RequestOrientationPacket().
void CommBase_RequestPayloadMassPacket (CommBase_t * pComm, UInt16 NetworkID)
Request the payload mass packet.
Request the payload mass packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References CommBase_SendZeroLengthAutopilotPacket(), and PAYLOAD_MASS.
Referenced by CCommManager::RequestPayloadMassPacket().
void CommBase_RequestRadioSettingsPacket (CommBase_t * pComm, UInt16 NetworkID)
Request the radio settings packet.
Request the autopilot radio settings packet. The radio settings packet is used to control the channel and output power of the radio.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References CommBase_SendZeroLengthAutopilotPacket(), and RADIO_SETTINGS.
Referenced by CCommManager::RequestRadioSettingsPacket().
void CommBase_RequestRawVibrationDataPacket (CommBase_t * pComm, UInt16 NetworkID)
Request the raw vibration sensor data.
Request the raw vibration sensor data. The raw vibration data comes down in 96 packets, 16 for each of six sensors, and contains 1024 samples at 1kHz.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References CommBase_SendZeroLengthAutopilotPacket(), and RAW_VIBRATION_DATA.
Referenced by CCommManager::RequestRawVibrationDataPacket().
void CommBase_RequestSensorErrorPacket (CommBase_t * pComm, UInt16 NetworkID)
Request the packet with the sensor error data.
Request the packet with the sensor error data.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References CommBase_SendZeroLengthAutopilotPacket(), and SENSOR_ERROR.
Referenced by CCommManager::RequestSensorErrorPacket().
void CommBase_RequestSystemVersionPacket (CommBase_t * pComm, UInt16 NetworkID)
Request system version packet.
Request the system version packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References CommBase_SendZeroLengthAutopilotPacket(), and SYSTEM_VERSION.
Referenced by CCommManager::RequestSystemVersionPacket().
void CommBase_RequestThrottleMinPacket (CommBase_t * pComm, UInt16 NetworkID)
Request the throttle min packet.
Request the payload mass packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References CommBase_SendZeroLengthAutopilotPacket(), and THROTTLE_MIN.
Referenced by CCommManager::RequestThrottleMinPacket().
void CommBase_RequestTransponderControlPacket (CommBase_t * pComm, UInt16 NetworkID)
Request the transponder control packet.
Request the autopilot transponder control packet. The transponder control packet is used to report the squawk code of an external tranponsder.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References CommBase_SendZeroLengthAutopilotPacket(), and TRANSPONDER_CONTROL.
Referenced by CCommManager::RequestTransponderControlPacket().
void CommBase_RequestTransponderInstallationPacket (CommBase_t * pComm, UInt16 NetworkID)
Request the transponder installation packet.
Request the transponder installation packet. The transponder installation packet is used to set/request the ICAO address and the aircraft registration.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References CommBase_SendZeroLengthAutopilotPacket(), and TRANSPONDER_INSTALLATION.
Referenced by CCommManager::RequestTransponderInstallationPacket().
void CommBase_RequestTransponderPreflightPacket (CommBase_t * pComm, UInt16 NetworkID)
Request the transponder preflight packet.
Request the transponder preflight packet. The transponder preflight packet is used to set/request the aircraft call sign.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References CommBase_SendZeroLengthAutopilotPacket(), and TRANSPONDER_PREFLIGHT.
Referenced by CCommManager::RequestTransponderPreflightPacket().
void CommBase_RequestUserSpacePacket (CommBase_t * pComm, UInt16 NetworkID)
Request the user space packet.
Request the user space packet. The user space packet is used to write user data to nonvolatile storage on the avionics. This data space is intended to be used by third-party applications which must store information on the autopilot.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
References CommBase_SendZeroLengthAutopilotPacket(), and USER_SPACE.
Referenced by CCommManager::RequestUserSpacePacket().
void CommBase_ResumeReplay (CommBase_t * pComm)
Enable the replay.
Referenced by CCommManager::ResumeReplay().
void CommBase_RunNetwork (CommBase_t * pComm)
Call periodically to service the communications.
Referenced by CCommManager::RunNetwork().
void CommBase_SendActuatorTablePacket (CommBase_t * pComm, UInt16 NetworkID, const ActuatorTable_t * pTable, UInt8 Sur, UInt8 Type, UInt8 Virtual, UInt8 Fast)
Create and send a control actuator calibration packet.
Create and send a autopilot surface table calibration packet. The surface calibration packet encodes the relationship between pulse width and surface angle for a single surface.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
pTable points to a single surface calibration table.
Sur is the surface index that the table refers to.
Type is the actuator type data.
Virtual should be 1 if this is a virtual (CAN output only) actuator.
Fast should be 1 if this is a fast (200 Hz update rate) actuator.
References CommBase_SendAutopilotPacket(), and FormActuatorTablePacket().
Referenced by CCommManager::SendActuatorTablePacket().
void CommBase_SendActuatorTypePacket (CommBase_t * pComm, UInt16 NetworkID, UInt8 Sur, UInt8 Type)
Create and send a packet to change actuator type.
Create and send a packet to change the type of an actuator without changing the calibration table.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
pTable points to a single surface calibration table.
Sur is the surface index that the table refers to.
Type is the actuator type data.
References ACTUATOR_TABLE, CommBase_SendAutopilotPacket(), SimplePkt_t::Data, and MakeAutopilotPacket().
Referenced by CCommManager::SendActuatorTypePacket().
void CommBase_SendAirDataZeroPacket (CommBase_t * pComm, UInt16 NetworkID, float ActualAltitude)
Create and send the zero air data command packet.
Create and send the zero air data command packet. This commands the autopilot to zero the airspeed and altitude sensors. This packet should not be sent while the vehicle is flying.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
ActualAltitude is current altitude in meters. It is used (along with the altimeter setting) to determine the static pressure error. If the static pressure sensor should not be zeroed then supply an ActualAltitude value which is less than -5000
References AIR_DATA_ZERO, CommBase_SendAutopilotPacket(), SimplePkt_t::Data, MakeAutopilotPacket(), and SInt32ToData().
Referenced by CCommManager::SendAirDataZeroPacket().
void CommBase_SendAltimeterSettingPacket (CommBase_t * pComm, UInt16 NetworkID, UInt32 Altimeter, BOOL ControlToGPS)
Create and send an altimeter setting packet.
Create and send a altimeter setting packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Altimeter is the altimeter setting in Pascals.
ControlToGPS should be TRUE to tell the autopilot to use the GPS altitude as its control target.
References CommBase_SendAutopilotPacket(), and FormAltimeterSettingPacket().
Referenced by CCommManager::SendAltimeterSettingPacket().
void CommBase_SendAutopilotLoopControlPacket (CommBase_t * pComm, UInt16 NetworkID, const AutopilotLoopCmd_t * pCmd, BOOL UpdateEEPROM)
Create and send a autopilot loop control packet.
Create and send a autopilot loop control packet. The loop control packet is used to change individual autopilot loops without changing the state of the other loops.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
pCmd points to individual loop data to be included in the packet.
UpdateEEPROM should be TRUE to cause the autopilot to write this data to EEPROM.
References CommBase_SendAutopilotPacket(), and FormAutopilotLoopControlPacketEx().
Referenced by CCommManager::SendAutopilotLoopControlPacket().
void CommBase_SendAutopilotPacket (CommBase_t * pComm, UInt16 NetworkID, const AutopilotPkt_t * pPkt)
Send a autopilot packet.
Send an autopilot stream packet.
Parameters
pComm points to the communication interface data.
NetworkID is the destination network address.
pPkt points to the autopilot packet to send.
References AUTOPILOT_STREAM, CommBase_SendBlock(), and SimplePkt_t::Size.
Referenced by CommBase_RequestActuatorTablePacket(), CommBase_RequestBandwidthModePacket(), CommBase_RequestControllerDataPacket(), CommBase_RequestExternalIOSetupPacket(), CommBase_SendActuatorTablePacket(), CommBase_SendActuatorTypePacket(), CommBase_SendAirDataZeroPacket(), CommBase_SendAltimeterSettingPacket(), CommBase_SendAutopilotLoopControlPacket(), CommBase_SendBandwidthModePacket(), CommBase_SendBoundaryPacket(), CommBase_SendBrakesCommandPacket(), CommBase_SendConfigurationLockPacket(), CommBase_SendConfigurationUnlockPacket(), CommBase_SendControllerDataDefaultPacket(), CommBase_SendControllerDataPacket(), CommBase_SendDescriptionPacket(), CommBase_SendDoubletCommandPacket(), CommBase_SendDropCommandPacket(), CommBase_SendEngineKillPacket(), CommBase_SendExternalIOSetupPacket(), CommBase_SendExternalSerialSetupPacket(), CommBase_SendFeatureCodePacket(), CommBase_SendFrequencySweepCommandPacket(), CommBase_SendLandNowPacket(), CommBase_SendLaunchNowPacket(), CommBase_SendLegacyWaypointListPacket(), CommBase_SendLegacyWaypointPacket(), CommBase_SendLightsCommandPacket(), CommBase_SendMagCalPacket(), CommBase_SendManualAssistModePacket(), CommBase_SendMissionLimitsPacket(), CommBase_SendMissionSettingsPacket(), CommBase_SendOrientationPacket(), CommBase_SendParachuteCommandPacket(), CommBase_SendPayloadMassPacket(), CommBase_SendPrelaunchPacket(), CommBase_SendRadioSettingsPacket(), CommBase_SendSensorErrorPacket(), CommBase_SendSetFuelIfLockedPacket(), CommBase_SendSetFuelLevelPacket(), CommBase_SendSimpleLandingPacket(), CommBase_SendSurfaceTestPacket(), CommBase_SendTerrainElevationDataPacket(), CommBase_SendThrottleMinPacket(), CommBase_SendThrottleTrimPacket(), CommBase_SendTrackCommandPacket(), CommBase_SendTransponderControlPacket(), CommBase_SendTransponderInstallationPacket(), CommBase_SendTransponderPreflightPacket(), CommBase_SendUserActionPacket(), CommBase_SendUserSpacePacket(), CommBase_SendWaypointListPacket(), CommBase_SendWaypointListRangePacket(), CommBase_SendWaypointsPacket(), CommBase_SendZeroLengthAutopilotPacket(), and CCommManager::SendAutopilotPacket().
void CommBase_SendBandwidthModePacket (CommBase_t * pComm, UInt16 NetworkID, BandwidthMode_t Bandwidth)
Create and send a bandwidth mode packet.
Create and send a altimeter setting packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to. Bandwidth is the data to send
References CommBase_SendAutopilotPacket(), and FormBandwidthModePacket().
Referenced by CCommManager::SendBandwidthModePacket().
void CommBase_SendBlock (CommBase_t * pComm, UInt16 NetworkID, UInt8 Stream, UInt8 * pData, UInt32 Size)
Send a block of data in a packet.
Referenced by CommBase_SendAutopilotPacket(), CommBase_SendGimbalPacket(), CommBase_SendGroundStationPacket(), and CCommManager::SendBlock().
void CommBase_SendBoundaryPacket (CommBase_t * pComm, UInt16 NetworkID, const Boundary_t * pBnd)
Create and send a airspace boundary packet.
Create and send a airspace boundary packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
pBnd is the boundary to send
References CommBase_SendAutopilotPacket(), and FormBoundaryPacket().
Referenced by CCommManager::SendBoundaryPacket().
void CommBase_SendBrakesCommandPacket (CommBase_t * pComm, UInt16 NetworkID, float Brakes)
Create and send the brakes command packet.
Create and send the brakes command packet. The brakes command asserts or deasserts the brake IO line(s), or actuates the brake servo(s). This command will have no effect if no IO lines are programmed for brake operation. The brake state is visible in the AUTOPILOT_COMMAND downlink packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Brakes gives the level of brakes actuation from 0 (brakes released) to 1 (brakes fully applied).
References BRAKES_CMD, CommBase_SendAutopilotPacket(), SimplePkt_t::Data, MakeAutopilotPacket(), and UInt16ToData().
Referenced by CCommManager::SendBrakesCommandPacket().
void CommBase_SendConfigurationLockPacket (CommBase_t * pComm, UInt16 NetworkID, const char Password[32])
Create and send a configuration lock packet.
Create and send a configuration lock packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Password is the pasword touse in the packet, send NULL for zero length packet.
References CommBase_SendAutopilotPacket(), and FormConfigurationLockPacket().
Referenced by CCommManager::SendConfigurationLockPacket().
void CommBase_SendConfigurationUnlockPacket (CommBase_t * pComm, UInt16 NetworkID, const char Password[32], BOOL Silent)
Create and send a configuration unlock packet.
Create and send a configuration unlock packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Password is the pasword touse in the packet, send NULL for zero length packet.
Silent should be TRUE to use the quiet version of this packet
References CommBase_SendAutopilotPacket(), and FormConfigurationUnlockPacket().
Referenced by CCommManager::SendConfigurationUnlockPacket().
void CommBase_SendControllerDataDefaultPacket (CommBase_t * pComm, UInt16 NetworkID, UInt8 Controller, UInt8 Version, UInt8 Category, UInt8 DataID, UInt8 NumData)
Create and send a controller packet to default data.
Create and send a controller data packet which defaults data.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Controller is the controller ID value.
Version is the controller version value.
Category is the data category.
DataID is the starting DataID.
NumData is the number of data elements to encode.
References CommBase_SendAutopilotPacket(), and FormControllerDataDefaultPacket().
Referenced by CCommManager::SendControllerDataDefaultPacket().
void CommBase_SendControllerDataPacket (CommBase_t * pComm, UInt16 NetworkID, UInt8 Controller, UInt8 Version, UInt8 Category, UInt8 DataID, UInt8 NumData, const void * pData)
Create and send a controller packet.
Create and send a controller data packet which contains 32-bit data words.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Controller is the controller ID value.
Version is the controller version value.
Category is the data category.
DataID is the starting DataID.
NumData is the number of data elements to encode.
pData points to the data to encode.
References CommBase_SendAutopilotPacket(), and FormControllerDataPacket().
Referenced by CCommManager::SendControllerDataPacket().
void CommBase_SendDescriptionPacket (CommBase_t * pComm, UInt16 NetworkID, const char Description[64])
Create and send a parameter description packet.
Create and send a parameter description packet. The parameter description is a string which can be used to identify the set of parameters stored on the autopilot.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Description is an array of bytes to send as the description. The array should contain a NULL-terminated string.
References CommBase_SendAutopilotPacket(), SimplePkt_t::Data, DESCRIPTION, and MakeAutopilotPacket().
Referenced by CCommManager::SendDescriptionPacket().
void CommBase_SendDGPSBasePacket (CommBase_t * pComm, const DGPSParameter_t * pDGPS)
Create and send a ground station differential corrections packet.
Create and send a ground station differential corrections packet. The DGPS packet contains the information required to configure differential corrections.
Parameters
pComm points to the communication interface data.
pDGPS points to the base station information to be included in the packet.
References CommBase_SendGroundStationPacket(), and FormDGPSBasePacket().
Referenced by CCommManager::SendDGPSBasePacket().
void CommBase_SendDoubletCommandPacket (CommBase_t * pComm, UInt16 NetworkID, const DoubletCmd_t * pDoublet)
Create and send a doublet command packet.
Create and send a doublet command packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
pDoublet points to space containing the doublet command data
References CommBase_SendAutopilotPacket(), and FormDoubletCommandPacket().
Referenced by CCommManager::SendDoubletCommandPacket().
void CommBase_SendDropCommandPacket (CommBase_t * pComm, UInt16 NetworkID, BOOL DropOn)
Create and send the drop command packet.
Create and send the drop command packet. The drop command asserts or deasserts the drop IO line(s), or actuates the drop servo(s). This command will have no effect if no IO lines are programmed for drop operation. The drop state is visible in the AUTOPILOT_COMMAND downlink packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
DropOn should be TRUE to turn the drop on, else it will be turned off.
References CommBase_SendAutopilotPacket(), SimplePkt_t::Data, DROP_CMD, and MakeAutopilotPacket().
Referenced by CCommManager::SendDropCommandPacket().
void CommBase_SendEngineKillPacket (CommBase_t * pComm, UInt16 NetworkID, BOOL EngineKill)
Create and send the engine kill packet.
Create and send the engine kill packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
EngineKill should be TRUE to kill the engine, FALSE to enable the engine.
References CommBase_SendAutopilotPacket(), SimplePkt_t::Data, ENGINE_KILL, and MakeAutopilotPacket().
Referenced by CCommManager::SendEngineKillPacket().
void CommBase_SendExternalIOSetupPacket (CommBase_t * pComm, UInt16 NetworkID, const ExternalIO_t * pExternalIO, UInt8 pin, UInt32 SampleTime, BOOL UpdateEEPROM)
Create and send a external IO setup packet.
Create and send an autopilot packet with the setup parameters for a single external IO pin.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
pExternalIO points to a structure containing the setup parameters.
pin identifies which IO pin these setup data apply to.
SampleTime is the time in milliseconds that the external IO inputs should be sampled.
UpdateEEPROM should be TRUE to cause the autopilot to write this data to EEPROM.
References CommBase_SendAutopilotPacket(), and FormExternalIOSetupPacketEx().
Referenced by CCommManager::SendExternalIOSetupPacket().
void CommBase_SendExternalSerialSetupPacket (CommBase_t * pComm, UInt16 NetworkID, const ExternalSerial_t * pSerial)
Create and send a external serial setup packet.
Create and send an autopilot packet with the external serial setup parameters.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
pSerial points to a structure containing the serial setup parameters.
References CommBase_SendAutopilotPacket(), and FormExternalSerialSetupPacket().
Referenced by CCommManager::SendExternalSerialSetupPacket().
void CommBase_SendFeatureCodePacket (CommBase_t * pComm, UInt16 NetworkID, const UInt8 Data[8])
Create and send a feature code packet.
Create and send a feature code packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Data is the 8 byte feature code.
References CommBase_SendAutopilotPacket(), and FormFeatureCodePacket().
Referenced by CCommManager::SendFeatureCodePacket().
void CommBase_SendFrequencySweepCommandPacket (CommBase_t * pComm, UInt16 NetworkID, const FrequencySweepCmd_t * pFreqSwp)
Create and send a frequency sweep command packet.
Create and send a frequency sweep command packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
pFreqSwp points the the frequency sweep settings structure.
References CommBase_SendAutopilotPacket(), and FormFrequencySweepCommandPacket().
Referenced by CCommManager::SendFrequencySweepCommandPacket().
void CommBase_SendGimbalAxisSettingsPacket (CommBase_t * pComm, UInt16 NetworkID, const float NoGoCenter[NGIMBAL_SHORT], const float NoGoRange[NGIMBAL_SHORT], const float MaxRate[NGIMBAL_SHORT], const float MaxAccel[NGIMBAL_SHORT], const float PosGain[NGIMBAL_SHORT], const float VelGain[NGIMBAL_SHORT], const float DerGain[NGIMBAL_SHORT], BOOL Temporary, BOOL Factory)
Create and send a gimbal axis settings packet.
Create and send a gimbal axis settings packet which contains the data to setup the axis control for custom configurations.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
NoGoCenter is the center of the no go range in radians for all gimbal axis.
NoGoRange is the size of the no go range in radians for all gimbal axis. Zero is free-running. More than 2PI is do not change center or range.
MaxRate is the max rate in radians per second for all gimbal axis. Less than zero is do not change.
MaxAccel is the max accelerating in radians per second per second for all gimbal axis. Less than zero is do not change.
PosGain is the position gain in angle per second per angle error. Less than zero is do not change.
VelGain is the velocity feedforward gain, less than zero is do not change.
DerGain is the aceleration feedforward gain, less than zer is do not change.
Temporary should be 1 to prevent update to nonvolatile storage.
Factory should be TRUE to update factory parameters as well as main.
References CommBase_SendGimbalPacket(), and FormGimbalAxisSettingsPacket().
Referenced by CCommManager::SendGimbalAxisSettingsPacket().
void CommBase_SendGimbalCameraAlignPacket (CommBase_t * pComm, UInt16 NetworkID, float Zoom1, const float Error1[NGIMBAL], float Zoom2, const float Error2[NGIMBAL], UInt8 Camera, BOOL Factory)
Create and send gimbal camera alignment packet.
Create and send gimbal camera alignment packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Zoom1 is the zoom ration of the first alignment.
Error1 is the pan, tilt, and roll alignemnt errors at zoom1 [rad].
Zoom2 is the zoom ration of the second alignment.
Error1 is the pan, tilt, and roll alignemnt errors at zoom2 [rad].
Camera enumerates the camera that this data apply to.
Factory should be TRUE to udpate factory settings as well as main.
References CommBase_SendGimbalPacket(), and FormGimbalCameraAlignPacket().
Referenced by CCommManager::SendGimbalCameraAlignPacket().
void CommBase_SendGimbalCameraCmdPacket (CommBase_t * pComm, UInt16 NetworkID, UInt8 Camera, float HFOV, UInt16 Focus, UInt8 Mode, UInt8 Shutter, UInt8 Bright, UInt8 Flags)
Create and send a camera command packet.
Create and send a camera command packet containing the field of view, focus, and exposure settings.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Camera identifies the camera to control.
HFOV is the horizontal field of view in radians, or (if negative) the camera zoom ratio. 0.0 is do not change.
Focus is the focus length in millimeters, 0xFFFF is do not change, 0xFFFE is infinite, 0xFFFD is trigger, 0x0000 is auto.
EMode is the exposure mode: 0 for auto, 1 for shutter priority, 2 for bright mode. 0xFF is do not change
Shutter is the shutter speed. 0xFF is do not change
Bright is the bright mode setting, 0xFF is do not change.
Flags is the camera flag settings, set MSB for do not change.
References CommBase_SendGimbalPacket(), and FormGimbalCameraCmdPacket().
Referenced by CCommManager::SendGimbalCameraCmdPacket().
void CommBase_SendGimbalCameraTypesPacket (CommBase_t * pComm, UInt16 NetworkID, const CameraDefinition_t Cam[NUM_CAMERAS], const BOOL Send[NUM_CAMERAS], BOOL Factory)
Create and send gimbal camera definitions packet.
Create and send gimbal camera definitions packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Cam is the array of camera definitions to send.
Send is an array of boolean flags set to TRUE for the cameras we want to send.
Factory should be TRUE to update factory definitions as well as main.
References CommBase_SendGimbalPacket(), and FormCameraDefinitionsPacket().
Referenced by CCommManager::SendGimbalCameraTypesPacket().
void CommBase_SendGimbalCmdPacket (CommBase_t * pComm, UInt16 NetworkID, float Pan, float Tilt, SInt8 ZoomRate, float CamTimeout, UInt8 Flags, float ImpulseTime, SInt8 FocusRate, UInt8 Flags1)
Create and send a gimbal command packet containing pan, tilt, zoom and focus rate, and mode.
Create and send a gimbal cmd packet. The command packet contains the rate or position data for pan and tilt, the camera zoom rate data, as well as the operational mode of the gimbal.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Pan is the pan position (or rate) in radians (per second).
Tilt is the pan position (or rate) in radians (per second).
ZoomRate is the zoom rate from -8 to 8.
CamTimeout is the time to apply the zoom or focus, in seconds.
Flags describes how to interpret the data.
ImpulseTime is the time to apply to an impulse (seconds).
FocusRate is the focus rate from -8 to 8.
Flags1 provides additional details on how to interpret the data.
References CommBase_SendGimbalPacket(), and FormGimbalCmdPacket().
Referenced by CCommManager::SendGimbalCmdPacket().
void CommBase_SendGimbalLaserArmPacket (CommBase_t * pComm, UInt16 NetworkID, UInt8 LaserIndex, BOOL Arm)
Create and send gimbal laser arm packet.
Create and send gimbal laser arm packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
LaserIndex identifies the laser to arm.
Arm should be TRUE to arm the laser else it is disarmed.
References CommBase_SendGimbalPacket(), and FormGimbalLaserArmCmdPacket().
Referenced by CCommManager::SendGimbalLaserArmPacket().
void CommBase_SendGimbalLaserFirePacket (CommBase_t * pComm, UInt16 NetworkID, UInt8 LaserIndex, UInt8 Power)
Create and send gimbal laser fire packet.
Create and send gimbal laser fire packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
LaserIndex identifies the laser to arm.
Power is the laser power from 0 to 100 (percent)
References CommBase_SendGimbalPacket(), and FormGimbalLaserFireCmdPacket().
Referenced by CCommManager::SendGimbalLaserFirePacket().
void CommBase_SendGimbalLaserSetupPacket (CommBase_t * pComm, UInt16 NetworkID, LaserSetup_t Lasers[NUM_LASERS], BOOL Factory)
Create and send gimbal laser setup packet.
Create and send gimbal laser setup packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Lasers is the setup information to send.
Factory should be TRUE to update factory settings as well as main.
References CommBase_SendGimbalPacket(), and FormGimbalLasersInstalledPacket().
Referenced by CCommManager::SendGimbalLaserSetupPacket().
void CommBase_SendGimbalPacket (CommBase_t * pComm, UInt16 NetworkID, const GimbalPkt_t * pPkt)
Send a gimbal packet on the gimbal stream to the autopilot.
Send a gimbal packet on the gimbal stream to the autopilot.
Parameters
pComm points to the communication interface data.
NetworkID is the destination network address.
pPkt points to the gimbal packet to send.
References CommBase_SendBlock(), GIMBAL_STREAM, and GimbalPkt_t::Size.
Referenced by CommBase_RequestGimbalAxisSettingsPacket(), CommBase_RequestGimbalCameraAlignPacket(), CommBase_RequestGimbalCameraCmdPacket(), CommBase_RequestGimbalCameraTypesPacket(), CommBase_RequestGimbalLaserSetupPacket(), CommBase_RequestGimbalSPOICmdPacket(), CommBase_SendGimbalAxisSettingsPacket(), CommBase_SendGimbalCameraAlignPacket(), CommBase_SendGimbalCameraCmdPacket(), CommBase_SendGimbalCameraTypesPacket(), CommBase_SendGimbalCmdPacket(), CommBase_SendGimbalLaserArmPacket(), CommBase_SendGimbalLaserFirePacket(), CommBase_SendGimbalLaserSetupPacket(), CommBase_SendGimbalRetractDeployCmdPacket(), CommBase_SendGimbalSerialInterfacePacket(), CommBase_SendGimbalSPOICmdPacket(), CommBase_SendGimbalTrackCmdPacket(), and CCommManager::SendGimbalPacket().
void CommBase_SendGimbalRetractDeployCmdPacket (CommBase_t * pComm, UInt16 NetworkID, UInt32 Deploy)
Create and send gimbal retract/deploy command.
Create and send gimbal retract/deploy command.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Deploy is the command, 0 for retract, 1 for deploy, 2 for halt.
References CommBase_SendGimbalPacket(), and FormGimbalRetractDeployCmdPacket().
Referenced by CCommManager::SendGimbalRetractDeployCmdPacket().
void CommBase_SendGimbalSerialInterfacePacket (CommBase_t * pComm, UInt16 NetworkID, GimbalSerial_t Serial[6], BOOL Temporary)
Create and send gimbal packet rate packet.
Create and send a gimbal packet which sets the output rate for standard gimbal packets.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Serial contains the interface setup for the gimbal.
Temporary should be zero to make settings permanent.
References CommBase_SendGimbalPacket(), and FormGimbalSerialInterfacePacket().
Referenced by CCommManager::SendGimbalSerialInterfacePacket().
void CommBase_SendGimbalSPOICmdPacket (CommBase_t * pComm, UInt16 NetworkID, const double Pos[NPOS], const float Vel[NDIR], UInt8 Flags)
Create and send a gimbal sensor point of interest packet containing the position of the SPOI.
Create and send a gimbal sensor point of interest (SPOI) cmd packet. The SPOI packet tells the gimbal where to point in LLA coordinates relative to the WGS-84 ellipsoid.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Pos is the position of the SPOI in Lat[rad], Lon[rad], Alt[m].
Vel is the velocity of the SPOI in North, East, Down [m/s].
Flags is the packet flags.
References CommBase_SendGimbalPacket(), and FormGimbalSPOICmdPacket().
Referenced by CCommManager::SendGimbalSPOICmdPacket().
void CommBase_SendGimbalTrackCmdPacket (CommBase_t * pComm, UInt16 NetworkID, float InitialX, float InitialY, UInt8 Algorithm, UInt8 Size, UInt8 Stamp)
Create and send gimbal track command packet.
Create and send the track command packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
InitialX is the initial horizontal track position in radians.
InitialY is the initial vertical track position in radians.
Algorithm is the algorithm choice enumeration.
Size is the size of the tracking window in pixels.
Stamp is the video counter stamp that goes with this track command, 255 if no stamp.
References CommBase_SendGimbalPacket(), and FormGimbalTrackCommand().
Referenced by CCommManager::SendGimbalTrackCmdPacket().
void CommBase_SendGroundStationPacket (CommBase_t * pComm, const GroundStationPkt_t * pPkt)
Send an groundstation packet.
Send an groundstation packet
Parameters
pComm points to the communication interface data.
pPkt points to the groundstation packet to send.
References CommBase_SendBlock(), GS_ADDRESS, GS_PKT_OVERHEAD, GS_STREAM, and SimplePkt_t::Size.
Referenced by CommBase_RequestGSCoherentSpectrumSweepPacket(), CommBase_SendDGPSBasePacket(), CommBase_SendGSAddAddressPacket(), CommBase_SendGSAddPilotAddressPacket(), CommBase_SendGSConfiguration(), CommBase_SendGSDeleteAddressPacket(), CommBase_SendGSDynamicEnumerationPacket(), CommBase_SendGSRadioSettingsPacket(), CommBase_SendZeroLengthGroundStationPacket(), and CCommManager::SendGroundStationPacket().
void CommBase_SendGSAddAddressPacket (CommBase_t * pComm, UInt16 Address)
Create and send a ground station add address packet.
Create and send a ground station add address packet. This packet is used to add an autopilot address to the ground station polling list.
Parameters
pComm points to the communication interface data.
Address is the address to add. Valid addresses are 1 to 65533.
References ADD_ADDRESS, CommBase_SendGroundStationPacket(), SimplePkt_t::Data, and MakeGroundStationPacket().
Referenced by CCommManager::SendGSAddAddressPacket().
void CommBase_SendGSAddPilotAddressPacket (CommBase_t * pComm, UInt16 Address)
Create and send a ground station add pilot address packet.
Create and send a ground station pilot address packet. This packet is used to change the pilot address used by the ground station.
Parameters
pComm points to the communication interface data.
Address is the pilot address. Valid addresses are 1 to 65533.
References CommBase_SendGroundStationPacket(), SimplePkt_t::Data, MakeGroundStationPacket(), and PILOT_ADDRESS.
Referenced by CCommManager::SendGSAddPilotAddressPacket().
void CommBase_SendGSConfiguration (CommBase_t * pComm, UInt8 ConfigEnum, UInt8 SBASDisable, UInt8 EnableGD, UInt32 PayloadBaud, UInt8 EnableMHXRelay)
Create and send a ground station configuration packet.
Create and send a ground station configuration packet.
Parameters
pComm points to the communication interface data.
ConfigEnum is the ground station configuration enumeration, see GSConfigurations.
SBASDisable is the disable SBAS flag.
EnableGD is the enable guaranteed delivery flag.
PayloadBaud is the payload baud rate in bits per second.
EnableMHXRelay is the enable for microhard radio reflash relay.
References CommBase_SendGroundStationPacket(), and FormGroundStationConfigurationPacket().
Referenced by CCommManager::SendGSConfiguration().
void CommBase_SendGSDeleteAddressPacket (CommBase_t * pComm, UInt16 DelAddress, UInt16 KeepAddress)
Create and send a ground station delete address packet.
Create and send a ground station delete address packet. This packet is used to remove addresses from the polling list. The pilot address cannot be removed.
Parameters
pComm points to the communication interface data.
DelAddress is the address to remove. Pass zero to remove all addresses except the pilot address.
KeepAddress is the address to keep if removing all addresses. Pass zerp to remove all addresses excepting pilot.
References CommBase_SendGroundStationPacket(), SimplePkt_t::Data, DEL_ADDRESS, and MakeGroundStationPacket().
Referenced by CCommManager::SendGSDeleteAddressPacket().
void CommBase_SendGSDynamicEnumerationPacket (CommBase_t * pComm, BOOL On)
Create and send a dynamic enumeration on/off packet.
Create and send a ground station dynamic enumeration on/off packet. Dynamic enumeration is a feature of the ground station that allows it to discover any active autopilots that are on its same frequency and channel.
Parameters
pComm points to the communication interface data.
On should be TRUE to enable dynamic enumeration.
References CommBase_SendGroundStationPacket(), SimplePkt_t::Data, DYNAMIC_ENUMERATION, and MakeGroundStationPacket().
Referenced by CCommManager::SendGSDynamicEnumerationPacket().
void CommBase_SendGSRadioSettingsPacket (CommBase_t * pComm, const RadioSettings_t * pSettings)
Create and a ground station radio settings packet.
Create and send a ground station radio settings packet. The radio settings packet is used to control the channel and output power of the radio.
Parameters
pComm points to the communication interface data.
pSettings points to radio settings to be included in the packet.
References CommBase_SendGroundStationPacket(), and FormGSRadioSettingsPacket().
Referenced by CCommManager::SendGSRadioSettingsPacket().
void CommBase_SendLandNowPacket (CommBase_t * pComm, UInt16 NetworkID)
Create and send the land now command packet.
Create and send the land now command packet. This commands the autopilot to being tracking the landing flight plan as identified in the mission limits.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
References CommBase_SendAutopilotPacket(), LAND_NOW, and MakeAutopilotPacket().
Referenced by CCommManager::SendLandNowPacket().
void CommBase_SendLaunchNowPacket (CommBase_t * pComm, UInt16 NetworkID)
Create and send the launch now command packet.
Create and send the land now command packet. This commands the autopilot to initiate the launch sequence.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
References CommBase_SendAutopilotPacket(), LAUNCH_NOW, and MakeAutopilotPacket().
Referenced by CCommManager::SendLaunchNowPacket().
void CommBase_SendLegacyWaypointListPacket (CommBase_t * pComm, UInt16 NetworkID, const FPMask_t Mask, UInt8 Flag)
Create and send a legacy waypoint list packet.
Create and send a autopilot waypoint list packet. This packet contains a flight plan mask with one bit for every possible waypoint; and a flags parameter telling the avionics how to use the mask.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Mask is the flight plan mask to be encoded.
Flag is the flight plan mask flags field. The flag should have one of these values:
GET_WAYPOINT_LIST: indicates that the avionics should downlink a valid waypoint list.
DELETE_WAYPOINTS: indicates that the avionics should delete each waypoint in the list.
REQUEST_WAYPOINTS: indicates that the avionics should downlink each waypoint in the list.
WAYPOINT_BLOCK: indicates that a waypoint bock transfer is beginning. The waypoints to be transferred are in the list.
References CommBase_SendAutopilotPacket(), and FormLegacyWaypointListPacket().
Referenced by CCommManager::SendLegacyWaypointListPacket().
void CommBase_SendLegacyWaypointPacket (CommBase_t * pComm, UInt16 NetworkID, const FPPoint_t * pPoint, UInt8 Index)
Create and send a legacy waypoint packet.
Create and send a legacy autopilot waypoint packet (prior to software 2.2.x). This packet contains all the data for a single waypoint.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
pPoint contains the waypoint data.
Index is the waypoint index.
References CommBase_SendAutopilotPacket(), and FormLegacyWaypointPacket().
Referenced by CCommManager::SendLegacyWaypointPacket().
void CommBase_SendLightsCommandPacket (CommBase_t * pComm, UInt16 NetworkID, BOOL LightsOn)
Create and send the lights command packet.
Create and send the lights command packet. The lights command asserts or deasserts the lights IO line(s). This command will have no effect if no IO lines are programmed for lights operation. The ligths state is visible in the AUTOPILOT_COMMAND downlink packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
LightsOn should be TRUE to turn the lights on, else they will be turned off.
References CommBase_SendAutopilotPacket(), SimplePkt_t::Data, LIGHTS_CMD, and MakeAutopilotPacket().
Referenced by CCommManager::SendLightsCommandPacket().
void CommBase_SendMagCalPacket (CommBase_t * pComm, UInt16 NetworkID, const float HardIronErr[N3D], const float ScaleFactErr[N3D])
Create and send a magnetic sensor calibration packet.
Create and send a packet with the magnetometer calibration data.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
HardIronErr is a vector of hard iron errors.
ScaleFactErr is a vector of scale factor errors.
References CommBase_SendAutopilotPacket(), and FormMagCalPacket().
Referenced by CCommManager::SendMagCalPacket().
void CommBase_SendManualAssistModePacket (CommBase_t * pComm, UInt16 NetworkID, UInt8 Mode)
Create and send the manual assist mode command packet.
Create and send the manual assist mode command packet. The assist mode controls how the autopilot uses the manual control data when the autopilot is globally on. The current manual assist mode is visible in the AUTOPILOT_COMMAND downlink packet. The manual assist modes are:
MA_STANDARD: No manual assistance
MA_LATERAL: Roll control plus rudder
MA_LONGITUDINAL: Speed control plus throttle and flaps
MA_ALL: Roll, speed, rudder, throttle, and flaps
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Mode is the mode to go to.
References CommBase_SendAutopilotPacket(), SimplePkt_t::Data, MakeAutopilotPacket(), and NEW_MANUAL_ASSIST_MODE.
Referenced by CCommManager::SendManualAssistModePacket().
void CommBase_SendMissionLimitsPacket (CommBase_t * pComm, UInt16 NetworkID, const MissionLimits_t * pMission)
Create and send a mission limits packet.
Create and send a autopilot mission limits packet. The mission limits packet contains timeouts and actions which limit are used to limit the scope of the mission.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
pMission points to the mission limit data.
References CommBase_SendAutopilotPacket(), and FormMissionLimitsPacket().
Referenced by CCommManager::SendMissionLimitsPacket().
void CommBase_SendMissionSettingsPacket (CommBase_t * pComm, UInt16 NetworkID, SInt16 MinAltitude, SInt16 MaxAltitude, UInt32 FlightTimeout)
Create and a send a mission settings packet.
Create and send a autopilot mission settings packet which sets the altitude limits and flight timeout.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
MinAltitude is the minimum altitude in meters.
MaxAltitude is the maximum altitude in meters.
FlightTimeout is the flight timeout in seconds
References CommBase_SendAutopilotPacket(), and FormMissionSettingsPacket().
Referenced by CCommManager::SendMissionSettingsPacket().
void CommBase_SendOrientationPacket (CommBase_t * pComm, UInt16 NetworkID, const float Euler[NAXIS], const float IMUtoAnt[N3D], const float IMUtoAnt2[N3D])
Create and send a sensor orientatin packet.
Create and send a autopilot orientation packet. The orientation packet describes the installed orientation of the Piccolo avionics as Euler angle rotations from the avionics frame to the vehicle frame.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Euler is an array of Euler angles (ROLL, PITCH, YAW).
IMUtoAnt is an array that holds the position offset from IMU to primary GPS antenna.
IMUtoAnt2 is an array that holds the position offset from IMU to secondary GPS antenna.
References CommBase_SendAutopilotPacket(), and FormOrientationPacket().
Referenced by CCommManager::SendOrientationPacket().
void CommBase_SendParachuteCommandPacket (CommBase_t * pComm, UInt16 NetworkID, BOOL ParachuteDeploy)
Create and send the parachute command packet.
Create and send the parachute command packet. The parachute command asserts or deasserts the parachute IO line(s), or actuates the parachute servo(s). This command will have no effect if no IO lines are programmed for parachute operation. The parachute state is visible in the AUTOPILOT_COMMAND downlink packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
ParachuteDeploy should be TRUE to deploy the parachute, else it will be retracted.
References CommBase_SendAutopilotPacket(), SimplePkt_t::Data, MakeAutopilotPacket(), and PARACHUTE_CMD.
Referenced by CCommManager::SendParachuteCommandPacket().
void CommBase_SendPayloadMassPacket (CommBase_t * pComm, UInt16 NetworkID, float PayloadMass)
Create and send a payload mass packet.
Create and send a set fuel level packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
PayloadMass is the payload mass in kilograms
References CommBase_SendAutopilotPacket(), and FormPayloadMassPacket().
Referenced by CCommManager::SendPayloadMassPacket().
void CommBase_SendPrelaunchPacket (CommBase_t * pComm, UInt16 NetworkID)
Create and send the go to prelaunch command packet.
Create and send the prelaunch command packet. This commands the autopilot to go to prelaunch mode.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
References CommBase_SendAutopilotPacket(), MakeAutopilotPacket(), and PRE_LAUNCH_MODE.
Referenced by CCommManager::SendPrelaunchPacket().
void CommBase_SendRadioSettingsPacket (CommBase_t * pComm, UInt16 NetworkID, const RadioSettings_t * pSettings)
Create and send a radio settings packet.
Create and send a autopilot radio settings packet. The radio settings packet is used to control the channel and output power of the radio.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
pSettings points to radio settings to be included in the packet.
References CommBase_SendAutopilotPacket(), and FormRadioSettingsPacket().
Referenced by CCommManager::SendRadioSettingsPacket().
void CommBase_SendSensorErrorPacket (CommBase_t * pComm, UInt16 NetworkID, const SensorErrorData_t * pSensorError)
Create and send a sensor error.
Create and send a packet with the AGL offset.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
pSensorError is the data to send.
References CommBase_SendAutopilotPacket(), and FormSensorErrorPacket().
Referenced by CCommManager::SendSensorErrorPacket().
void CommBase_SendSetFuelIfLockedPacket (CommBase_t * pComm, UInt16 NetworkID, float Fuel, BOOL Electric)
Create and send a set fuel level packet for fuel update while locked.
Create and send a set fuel level packet to change fuel level even if the autopilot is locked.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Fuel is the fuel level in kilograms or Watt-Hours.
Electric is TRUE for electric motor (fuel in Watt-Hours).
References CommBase_SendAutopilotPacket(), and FormSetFuelIfLockedPacket().
Referenced by CCommManager::SendSetFuelIfLockedPacket().
void CommBase_SendSetFuelLevelPacket (CommBase_t * pComm, UInt16 NetworkID, float Fuel, BOOL Electric)
Create and send a set fuel level packet.
Create and send a set fuel level packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Fuel is the fuel level in kilograms or Watt-Hours.
Electric is TRUE for electric motor (fuel in Watt-Hours).
References CommBase_SendAutopilotPacket(), and FormSetFuelLevelPacket().
Referenced by CCommManager::SendSetFuelLevelPacket().
void CommBase_SendSimpleLandingPacket (CommBase_t * pComm, UInt16 NetworkID, const SimpleLandingPattern_t * pLand)
Create and send a simple landing packet.
Create and send a packet containing the simple landing pattern information necessary for creating a simple landing pattern flightplan.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
pLand points to a simple landing pattern data structure.
References CommBase_SendAutopilotPacket(), and FormSimpleLandingPacket().
Referenced by CCommManager::SendSimpleLandingPacket().
void CommBase_SendStreamPacket (CommBase_t * pComm, StreamPkt_t * pPkt)
Send a low level packet of data.
Referenced by CCommManager::SendStreamPacket().
void CommBase_SendSurfaceTestPacket (CommBase_t * pComm, UInt16 NetworkID, float Angle, float Width, float Freq, float Dev, UInt8 Index)
Create and send a surface test packet.
Create and send a autopilot surface test packet. The surface test packet is used to send test signals to specific control surfaces.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Angle is the actuator angle to apply to the test, in rad. Pass more than 3.14 to disable angle test.
Width is the actuator pulse width to apply to the test, in microseconds. Pass zero to disable pulse test.
Freq is the frequency in hertz to use for sinusoidal test, pass more than 0.01 to enable.
Dev is the amplitude of the sinusoidal test in radians.
Index is the index of the control surface to apply the test to.
References CommBase_SendAutopilotPacket(), and FormActuatorTestPacket().
Referenced by CCommManager::SendSurfaceTestPacket().
void CommBase_SendTerrainElevationDataPacket (CommBase_t * pComm, UInt16 NetworkID, UInt32 Time, float Elevations[6])
Create and send terrain elevation information.
Create and send a packet used to uplink terrain elevation data to the avionics.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Time is the system time at which the elevation data apply.
Elevations is the array of terrian elevations spaced 2 seconds apart, with the first element corresponding to Time.
References CommBase_SendAutopilotPacket(), and FormTerrainElevationDataPacket().
Referenced by CCommManager::SendTerrainElevationDataPacket().
void CommBase_SendThrottleMinPacket (CommBase_t * pComm, UInt16 NetworkID, float Throttle)
Create and send a throttle min packet.
Create and send the throttle minimum command packet. The throttle min packet sets the minimum allowable throttle position for the autopilot.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Throttle gives the throttle min value, from 0 to 1.0.
References CommBase_SendAutopilotPacket(), and FormThrottleMinPacket().
Referenced by CCommManager::SendThrottleMinPacket().
void CommBase_SendThrottleTrimPacket (CommBase_t * pComm, UInt16 NetworkID, float Throttle)
Create and send the throttle trim command packet.
Create and send the throttle trim command packet. The throttle trim is used to set the throttle position in prelaunch mode, and to set the autopilot throttle start point.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Throttle gives the throttle trim value, from 0 to 1.
References CommBase_SendAutopilotPacket(), SimplePkt_t::Data, MakeAutopilotPacket(), RoundToUInt16(), THROTTLE_TRIM, and UInt16ToData().
Referenced by CCommManager::SendThrottleTrimPacket().
void CommBase_SendTrackCommandPacket (CommBase_t * pComm, UInt16 NetworkID, UInt16 Waypoint, BOOL GoTo)
Create and send a track command packet.
Create and send a track command packet. The track command will tell the autopilot to track to a specific waypoint. The waypoint must already be part of a valid flight plan onboard the autopilot.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Waypoint is the index of the waypoint to track to.
GoTo indicates if the vehicle should fly to the waypoint along the preceding track segment, or if it should go directly to the waypoint, using its current position as the starting point. Set to TRUE to go directly to the waypoint.
References CommBase_SendAutopilotPacket(), SimplePkt_t::Data, MakeAutopilotPacket(), TRACK, and UInt16ToData().
Referenced by CCommManager::SendTrackCommandPacket().
void CommBase_SendTransponderControlPacket (CommBase_t * pComm, UInt16 NetworkID, UInt16 Code, BOOL Ident, UInt8 Mode)
Create and send a transponder control packet.
Create and send a autopilot transponder control packet. The transponder control packet is used to set the squawk code and ident flag of an external transponder.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Code is the transponder squawk code to use.
Ident should be true to cause the tranponder to Ident.
Mode is the transponder mode, 0 for standby, 1 for mode A, 2 for mode C, 3 for altitude display.
References CommBase_SendAutopilotPacket(), and FormTransponderControlPacket().
Referenced by CCommManager::SendTransponderControlPacket().
void CommBase_SendTransponderInstallationPacket (CommBase_t * pComm, UInt16 NetworkID, UInt32 ICAOAddress, const char Registration[9])
Create and send a transponder installation packet.
Create and send a transponder installation packet. This is used to set/request the ICAO address and aircraft registration, and it applies only to Mode S transponders.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
ICAOAddress is a 3-byte number representing the new ICAO address, to be set into the Mode S transponder.
Registration is a string containing the new alphanumeric aircraft registration to be set into the Mode S transponder.
References CommBase_SendAutopilotPacket(), and FormTransponderInstallationPacket().
Referenced by CCommManager::SendTransponderInstallationPacket().
void CommBase_SendTransponderPreflightPacket (CommBase_t * pComm, UInt16 NetworkID, const char FlightID[9])
Create and send a transponder preflight packet.
Create and send a transponder preflight packet. The transponder preflight packet is used to set/request the aircraft call sign, and applies only to Mode S transponders.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
FlightID is a string containing the new alphanumeric call sign to be set into the Mode S transponder.
References CommBase_SendAutopilotPacket(), and FormTransponderPreflightPacket().
Referenced by CCommManager::SendTransponderPreflightPacket().
void CommBase_SendUserActionPacket (CommBase_t * pComm, UInt16 NetworkID, UInt8 ActionIndex, BOOL On)
Create and send a user action command packet.
Create and send the user action command.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
ActionIndex is the index of the user action.
On should be TRUE to assert the action.
References CommBase_SendAutopilotPacket(), and FormUserActionPacket().
Referenced by CCommManager::SendUserActionPacket().
void CommBase_SendUserSpacePacket (CommBase_t * pComm, UInt16 NetworkID, const UInt8 User[64])
Create and send a user space packet.
Create and send a user space packet. The user space packet is used to write user data to nonvolatile storage on the avionics. This data space is intended to be used by third-party applications which must store information on the autopilot.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
User is an array of bytes to record on the autopilot.
References CommBase_SendAutopilotPacket(), SimplePkt_t::Data, MakeAutopilotPacket(), and USER_SPACE.
Referenced by CCommManager::SendUserSpacePacket().
void CommBase_SendWaypointListPacket (CommBase_t * pComm, UInt16 NetworkID, const FPMask_t Mask, UInt8 Flag)
Create and send a waypoint list packet.
Create and send a autopilot waypoint list packet. This packet contains a flight plan mask with one bit for every possible waypoint; and a flags parameter telling the avionics how to use the mask.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Mask is the flight plan mask to be encoded.
Flag is the flight plan mask flags field. The flag should have one of these values:
GET_WAYPOINT_LIST: indicates that the avionics should downlink a valid waypoint list.
DELETE_WAYPOINTS: indicates that the avionics should delete each waypoint in the list.
REQUEST_WAYPOINTS: indicates that the avionics should downlink each waypoint in the list.
WAYPOINT_BLOCK: Prepare to receive waypoints (both ways).
WAYPOINT_ACK: Acknowledge receive of waypoints (both ways)
References CommBase_SendAutopilotPacket(), and FormWaypointListPacket().
Referenced by CCommManager::SendWaypointListPacket().
void CommBase_SendWaypointListRangePacket (CommBase_t * pComm, UInt16 NetworkID, UInt16 Start, UInt16 End, UInt8 Flag)
Create and send a waypoint list packet using a range of points.
Create and send a autopilot waypoint list packet using a range of points.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Start is the first waypoint index to be asserted.
End is the last waypoint index to be asserted.
Flag is the flight plan mask flags field. The flag should have one of these values:
GET_WAYPOINT_LIST: indicates that the avionics should downlink a valid waypoint list.
DELETE_WAYPOINTS: indicates that the avionics should delete each waypoint in the list.
REQUEST_WAYPOINTS: indicates that the avionics should downlink each waypoint in the list.
WAYPOINT_BLOCK: Prepare to receive waypoints (both ways).
WAYPOINT_ACK: Acknowledge receive of waypoints (both ways)
References CommBase_SendAutopilotPacket(), and FormWaypointListRangePacket().
Referenced by CCommManager::SendWaypointListRangePacket().
void CommBase_SendWaypointsPacket (CommBase_t * pComm, UInt16 NetworkID, const FPPoint_t Points[MAX_WAYPOINTS_IN_PACKET], UInt16 Num, BOOL Ack)
Create and send waypoints packet.
Create and send a autopilot waypoints packet. This packet contains all the data for a one or more waypoints, up to MAX_WAYPOINTS_IN_PACKET.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Point contains the waypoints data.
Num is the number of waypoints to send.
Ack should be TRUE to set the ack bit.
References CommBase_SendAutopilotPacket(), and FormWaypointsPacket().
Referenced by CCommManager::SendWaypointsPacket().
void CommBase_SendZeroLengthAutopilotPacket (CommBase_t * pComm, UInt16 NetworkID, UInt8 PktType)
Send a zero length autopilot packet.
Send a zero length autopilot packet.
Parameters
NetworkID is the destination network address.
PktType is the type of the autopillot packet.
References CommBase_SendAutopilotPacket(), and MakeAutopilotPacket().
Referenced by CommBase_RequestAltimeterSettingPacket(), CommBase_RequestDescriptionPacket(), CommBase_RequestExternalSerialSetupPacket(), CommBase_RequestMagCalPacket(), CommBase_RequestMissionLimitsPacket(), CommBase_RequestOrientationPacket(), CommBase_RequestPayloadMassPacket(), CommBase_RequestRadioSettingsPacket(), CommBase_RequestRawVibrationDataPacket(), CommBase_RequestSensorErrorPacket(), CommBase_RequestSystemVersionPacket(), CommBase_RequestThrottleMinPacket(), CommBase_RequestTransponderControlPacket(), CommBase_RequestTransponderInstallationPacket(), CommBase_RequestTransponderPreflightPacket(), CommBase_RequestUserSpacePacket(), and CCommManager::SendZeroLengthAutopilotPacket().
void CommBase_SendZeroLengthGroundStationPacket (CommBase_t * pComm, UInt8 PktType)
Send a zero length ground station packet.
Send a zero length autopilot packet.
Parameters
pComm points to the communication interface data.
NetworkID is the destination network address.
PktType is the type of the autopillot packet.
References CommBase_SendGroundStationPacket(), and MakeGroundStationPacket().
Referenced by CommBase_RequestDGPSBasePacket(), CommBase_RequestGSFirmwarePacket(), CommBase_RequestGSHoppingSpectrumSweepPacket(), CommBase_RequestGSRadioSettingsPacket(), and CCommManager::SendZeroLengthGroundStationPacket().
void CommBase_SetNewNetworkCallBack (CommBase_t * pComm, void(*)(UInt16 NetworkID, void *Parameter) NewNetworkCallBack, void * Parameter)
Register the call back function for new networks.
Referenced by CCommManager::SetNewNetworkCallBack().
void CommBase_SetReplayFileLocation (CommBase_t * pComm, UInt32 location)
Set the location of the file position.
Referenced by CCommManager::SetReplayFileLocation().
void CommBase_SetReplayRate (CommBase_t * pComm, UInt32 ReplayRate)
Set the current replay rate.
Referenced by CCommManager::SetReplayRate().
void CommBase_SetSatcommPhoneNumber (const char * PhoneNum)
Set/change the satcomm phone number.
Referenced by CCommManager::SetSatcommPhoneNumber().
void CommBase_StartDialingSatcomm (CommBase_t * pComm)
Start the dialing sequence.
Referenced by CCommManager::StartDialingSatcomm().
BOOL CommBase_WriteTextLogHeader (FILE * pFile)
Write the header for the log file.
Write the header for the text log file
Parameters
pFile points to an open stream to write the log file header to.
Returns
TRUE if the header was written successfully, else FALSE
References NUM_ACTUATORS, and NUM_EXTERNAL_ADC_PINS.
Referenced by CCommManager::WriteTextLogHeader().
BOOL CommBase_WriteTextLogLine (FILE * pFile, const UserData_t * pData, UInt8 AckRatio, const double TrackPosition[N3D], const float TrackVelocity[N3D], const float ADCSample[NUM_EXTERNAL_ADC_PINS], const ECU_t * pLeftECU, const ECU_t * pRightECU, const MovingBaseStatus_t * pMBStatus, const GPSUser_t * pGSGPS, float GSRSSI, float GSPilotPercent, float GSPilotRate)
Write a single line of data for the log file.
Write a data line into the autopilot log file.
Parameters
pFile points to the autopilot log file, assumed open for writing.
pData points to the user telemetry data.
AckRatio is the autopilot acknowledgement ratio.
TrackPosition is the aircraft relative position in the track frame, in m.
TrackVelocity is the aircraft velocity in the track frame, in m/s.
ADCSample is the array of analog input samples.
pLeftECU points to the left side ECU status data.
pRightECU points to the right side ECU status data.
pMBStatus points to the DGPS moving base solution status.
pGSGPS points to the groundstation GPS data.
GSRRSI is the RSSI reported by the groundstation radio.
GSPilotPercent is the acknowledgement ration for manual pilot data, reported by the groundstation.
GSPilotRate is the frame rate for the manual pilot data, in Hz, reported by the groundstation.
< No solution
< Fixed position solution
< Fixed height solution (i.e. 2D)
< Velocity from doppler
< Single point solution
< Pseudo range differential solution
< Satellite based augmentation system solution
< Solution propagated by receiver
< Omnistar VBS solution
< L1 only floating RTK solution
< No ionospheric corrections
< L1/L2 floating RTK solution
< L1 integer (high performance) RTK solution
< L1/L2 narrow lane integer RTK solution (the best!)
< Ominstar HP solution
< Ominstar XP solution
References NavStatus_t::AccBiasGood, UserData_t::Accel, NavDiagnostic_t::AccelBias, GenericActionBits_t::Action0, GenericActionBits_t::Action1, GenericActionBits_t::Action2, GenericActionBits_t::Action3, GenericActionBits_t::Action4, GenericActionBits_t::Action5, GenericActionBits_t::Action6, GenericActionBits_t::Action7, AutopilotStatus_t::ActionStates, UserData_t::Actuators, ActionBits_t::AeroTermination, ECU_t::AFR, ECUFlags_t::AFRandComp_included, ECU_t::AFRcomp, UserData_t::AGL, NavStatus_t::AGLGood, UserData_t::AlignHeading, UserData_t::AlignHeadingSigma, UserData_t::AlignSolnType, ALT, DataSource_t::AltControlType, GPSUser_t::Altitude, UserData_t::AltUsed, UserData_t::AP, AP_AUTO, AP_ON, AutopilotStatus_t::APMode, AutopilotStatus_t::AssistMode, NavStatus_t::AttitudeGood, UserData_t::AvailableData, UserData_t::BaroAlt, NavStatus_t::BaroGood, MovingBaseStatus_t::Baseline, MovingBaseStatus_t::BelowTrack, SystemDiagnostic_t::BoardTemp, AutopilotStatus_t::BoundaryIsViolated, ActionBits_t::Brakes, ECU_t::CHT_A, ECUFlags_t::CHT_A_included, ECU_t::CHT_B, ECUFlags_t::CHT_B_included, AutopilotStatus_t::CommTimeout, SystemDiagnostic_t::CPULoad, SystemDiagnostic_t::CPUVoltageBIT, MovingBaseStatus_t::CrossTrack, GPSUser_t::day, AutopilotStatus_t::Deadman, GPSUser_t::Direction, DOPPLER_VELOCITY_PVTYPE, DOWN, ActionBits_t::Drop, EAST, ECUFlags_t::ECU_volt_included, ECU_t::EGT_A, ECUFlags_t::EGT_A_included, ECU_t::EGT_B, ECUFlags_t::EGT_B_included, ActionBits_t::EngineKill, ECU_t::EngineTime, ECUFlags_t::EngineTime_included, ECU_t::ErrorBits, ECUFlags_t::ErrorBits_A_included, ECUFlags_t::ErrorBits_B_included, MovingBaseStatus_t::ETA, UserData_t::Euler, FILTER_AHRS, FILTER_ALIGN, FILTER_BOUND_VEL, FILTER_BUFFERING, FILTER_INIT, FILTER_NORMAL, SystemDiagnostic_t::FirstStageBIT, SystemDiagnostic_t::FiveAnalogBIT, SystemDiagnostic_t::FiveDigitalBIT, FIXEDHEIGHT_PVTYPE, FIXEDPOS_PVTYPE, ECU_t::Flags, AutopilotStatus_t::FlightTermination, AutopilotStatus_t::FlightTimerElapsed, UserData_t::Fuel, UserData_t::FuelFlow, ECU_t::FuelPress, ECUFlags_t::FuelPress_included, AutopilotStatus_t::GlobalOn, UserData_t::GPS, AvailableData_t::GPSResiduals, AutopilotStatus_t::GPSTimeout, SystemDiagnostic_t::GPSVoltageBIT, UserData_t::Gyro, NavDiagnostic_t::GyroBias, NavStatus_t::GyroBiasGood, MovingBaseStatus_t::Heading, NavStatus_t::HeadingGood, GPSUser_t::hours, ECU_t::IAT, ECUFlags_t::IAT_included, ECU_t::InjectAngle, ECUFlags_t::InjectAngle_included, ECU_t::InjectTime, ECUFlags_t::InjectTime_included, SystemDiagnostic_t::InputCurrent, SystemDiagnostic_t::InputVoltage, IONOFREE_FLOAT_PVTYPE, GPSUser_t::ITOW, L1_FLOAT_PVTYPE, L1_INTEGER_PVTYPE, MovingBaseStatus_t::Lag, LAT, GPSUser_t::Latitude, UserData_t::LeftRPM, ActionBits_t::Lights, LON, GPSUser_t::Longitude, AutopilotStatus_t::LoopStatus0, AutopilotStatus_t::LoopStatus1, AutopilotStatus_t::LoopStatus2, AutopilotStatus_t::LoopStatus3, AutopilotStatus_t::LoopStatus4, AutopilotStatus_t::LoopStatus5, AutopilotStatus_t::LoopStatus6, AutopilotStatus_t::LoopStatus7, AutopilotStatus_t::LoopTargets, NavStatus_t::MagBiasGood, UserData_t::MagField, NavStatus_t::MagGood, UserData_t::MagHeading, ECU_t::MAP, ECUFlags_t::MAP_included, GPSUser_t::minutes, NavStatus_t::Mode, ECUFlags_t::Mode, GPSUser_t::month, NARROW_FLOAT_PVTYPE, NARROW_INTEGER_PVTYPE, UserData_t::Nav, NavDiagnostic_t::NavStatus, NONE_PVTYPE, NORTH, NUM_ACTUATORS, NUM_EXTERNAL_ADC_PINS, UserData_t::OAT, OMNISTAR_HP_PVTYPE, OMNISTAR_VBS_PVTYPE, OMNISTAR_XP_PVTYPE, AutopilotStatus_t::Orbit, ActionBits_t::Parachute, AutopilotStatus_t::ParachutePendingRPM, GPSUser_t::PDOP, UserData_t::Pdynamic, AutopilotStatus_t::PilotPercentage, AutopilotStatus_t::PilotRate, PITCH_AXIS, NavStatus_t::PositionGood, UserData_t::PRes, PROPAGATED_PVTYPE, PSRDIFF_PVTYPE, UserData_t::Pstatic, UserData_t::RightRPM, ROLL_AXIS, SystemDiagnostic_t::RSSI, SBAS_PVTYPE, GPSUser_t::seconds, ECU_t::SerialNum, ECUFlags_t::SerialNumber_included, SystemDiagnostic_t::ServoCurrent, SystemDiagnostic_t::ServoVoltage, SINGLE_PVTYPE, MovingBaseStatus_t::SolnType, NavDiagnostic_t::Source, GPSUser_t::Speed, MovingBaseStatus_t::State, GPSUser_t::Status, UserData_t::System, UserData_t::SystemTime, MovingBaseStatus_t::SystemTime, UserData_t::TAS, NavStatus_t::TASGood, MovingBaseStatus_t::TDPos, ECU_t::TPS, ECUFlags_t::TPS_included, GPSUser_t::TrackedSats, AutopilotStatus_t::TrackerStatus, SystemDiagnostic_t::UplinkRatio, ActionBits_t::User, GPSUser_t::VDown, GPSUser_t::VEast, NavStatus_t::VelocityGood, GPSUser_t::VisibleSats, GPSUser_t::VNorth, ECU_t::Volts, UserData_t::VRes, AutopilotStatus_t::WaypointTo, GPSUser_t::Week, UserData_t::WeightOnWheel, NavStatus_t::WindGood, UserData_t::WindSouth, UserData_t::WindWest, X_AXIS, Y_AXIS, YAW_AXIS, GPSUser_t::year, and Z_AXIS.
Referenced by CCommManager::WriteTextLogLine().