Communications SDK: CommBaseAutopilot.c File Reference
CommBaseAutopilot.c File Reference
The CCT communication library base module, autopilot packet processing. This module provides functions to send and request autopilot-specific packets.
#include "CommBase.h"
#include "ByteOrder.h"
#include <math.h>
Functions
void CommBase_SendAutopilotPacket (CommBase_t *pComm, UInt16 NetworkID, const AutopilotPkt_t *pPkt)
Send a autopilot packet.
void CommBase_SendZeroLengthAutopilotPacket (CommBase_t *pComm, UInt16 NetworkID, UInt8 PktType)
Send a zero length autopilot packet.
void CommBase_SendUserActionPacket (CommBase_t *pComm, UInt16 NetworkID, UInt8 ActionIndex, BOOL On)
Create and send a user action command packet.
void CommBase_SendConfigurationLockPacket (CommBase_t *pComm, UInt16 NetworkID, const char Password[32])
Create and send a configuration lock packet.
void CommBase_SendConfigurationUnlockPacket (CommBase_t *pComm, UInt16 NetworkID, const char Password[32], BOOL Silent)
Create and send a configuration unlock packet.
void CommBase_SendControllerDataPacket (CommBase_t *pComm, UInt16 NetworkID, UInt8 Controller, UInt8 Version, UInt8 Category, UInt8 DataID, UInt8 NumData, const void *pData)
Create and send a controller packet.
void CommBase_SendControllerDataDefaultPacket (CommBase_t *pComm, UInt16 NetworkID, UInt8 Controller, UInt8 Version, UInt8 Category, UInt8 DataID, UInt8 NumData)
Create and send a controller packet to default data.
void CommBase_SendTransponderControlPacket (CommBase_t *pComm, UInt16 NetworkID, UInt16 Code, BOOL Ident, UInt8 Mode)
Create and send a transponder control packet.
void CommBase_SendTransponderPreflightPacket (CommBase_t *pComm, UInt16 NetworkID, const char FlightID[9])
Create and send a transponder preflight packet.
void CommBase_SendTransponderInstallationPacket (CommBase_t *pComm, UInt16 NetworkID, UInt32 ICAOAddress, const char Registration[9])
Create and send a transponder installation packet.
void CommBase_SendRadioSettingsPacket (CommBase_t *pComm, UInt16 NetworkID, const RadioSettings_t *pSettings)
Create and send a radio settings packet.
void CommBase_SendAutopilotLoopControlPacket (CommBase_t *pComm, UInt16 NetworkID, const AutopilotLoopCmd_t *pCmd, BOOL UpdateEEPROM)
Create and send a autopilot loop control packet.
void CommBase_SendActuatorTablePacket (CommBase_t *pComm, UInt16 NetworkID, const ActuatorTable_t *pTable, UInt8 Sur, UInt8 Type, UInt8 Virtual, UInt8 Fast)
Create and send a control actuator calibration packet.
void CommBase_SendActuatorTypePacket (CommBase_t *pComm, UInt16 NetworkID, UInt8 Sur, UInt8 Type)
Create and send a packet to change actuator type.
void CommBase_SendOrientationPacket (CommBase_t *pComm, UInt16 NetworkID, const float Euler[NAXIS], const float IMUtoAnt[N3D], const float IMUtoAnt2[N3D])
Create and send a sensor orientatin packet.
void CommBase_SendWaypointsPacket (CommBase_t *pComm, UInt16 NetworkID, const FPPoint_t Points[MAX_WAYPOINTS_IN_PACKET], UInt16 Num, BOOL Ack)
Create and send waypoints packet.
void CommBase_SendWaypointListPacket (CommBase_t *pComm, UInt16 NetworkID, const FPMask_t Mask, UInt8 Flag)
Create and send a waypoint list packet.
void CommBase_SendWaypointListRangePacket (CommBase_t *pComm, UInt16 NetworkID, UInt16 Start, UInt16 End, UInt8 Flag)
Create and send a waypoint list packet using a range of points.
void CommBase_SendLegacyWaypointPacket (CommBase_t *pComm, UInt16 NetworkID, const FPPoint_t *pPoint, UInt8 Index)
Create and send a legacy waypoint packet.
void CommBase_SendLegacyWaypointListPacket (CommBase_t *pComm, UInt16 NetworkID, const FPMask_t Mask, UInt8 Flag)
Create and send a legacy waypoint list packet.
void CommBase_SendTrackCommandPacket (CommBase_t *pComm, UInt16 NetworkID, UInt16 Waypoint, BOOL GoTo)
Create and send a track command packet.
void CommBase_SendSurfaceTestPacket (CommBase_t *pComm, UInt16 NetworkID, float Angle, float Width, float Freq, float Dev, UInt8 Index)
Create and send a surface test packet.
void CommBase_SendMissionLimitsPacket (CommBase_t *pComm, UInt16 NetworkID, const MissionLimits_t *pMission)
Create and send a mission limits packet.
void CommBase_SendBoundaryPacket (CommBase_t *pComm, UInt16 NetworkID, const Boundary_t *pBnd)
Create and send a airspace boundary packet.
void CommBase_SendMissionSettingsPacket (CommBase_t *pComm, UInt16 NetworkID, SInt16 MinAltitude, SInt16 MaxAltitude, UInt32 FlightTimeout)
Create and a send a mission settings packet.
void CommBase_SendMagCalPacket (CommBase_t *pComm, UInt16 NetworkID, const float HardIronErr[N3D], const float ScaleFactErr[N3D])
Create and send a magnetic sensor calibration packet.
void CommBase_SendSensorErrorPacket (CommBase_t *pComm, UInt16 NetworkID, const SensorErrorData_t *pSensorError)
Create and send a sensor error.
void CommBase_SendEngineKillPacket (CommBase_t *pComm, UInt16 NetworkID, BOOL EngineKill)
Create and send the engine kill packet.
void CommBase_SendPrelaunchPacket (CommBase_t *pComm, UInt16 NetworkID)
Create and send the go to prelaunch command packet.
void CommBase_SendLaunchNowPacket (CommBase_t *pComm, UInt16 NetworkID)
Create and send the launch now command packet.
void CommBase_SendLandNowPacket (CommBase_t *pComm, UInt16 NetworkID)
Create and send the land now command packet.
void CommBase_SendAirDataZeroPacket (CommBase_t *pComm, UInt16 NetworkID, float ActualAltitude)
Create and send the zero air data command packet.
void CommBase_SendManualAssistModePacket (CommBase_t *pComm, UInt16 NetworkID, UInt8 Mode)
Create and send the manual assist mode command packet.
void CommBase_SendLightsCommandPacket (CommBase_t *pComm, UInt16 NetworkID, BOOL LightsOn)
Create and send the lights command packet.
void CommBase_SendDropCommandPacket (CommBase_t *pComm, UInt16 NetworkID, BOOL DropOn)
Create and send the drop command packet.
void CommBase_SendParachuteCommandPacket (CommBase_t *pComm, UInt16 NetworkID, BOOL ParachuteDeploy)
Create and send the parachute command packet.
void CommBase_SendBrakesCommandPacket (CommBase_t *pComm, UInt16 NetworkID, float Brakes)
Create and send the brakes command packet.
void CommBase_SendThrottleTrimPacket (CommBase_t *pComm, UInt16 NetworkID, float Throttle)
Create and send the throttle trim command packet.
void CommBase_SendThrottleMinPacket (CommBase_t *pComm, UInt16 NetworkID, float Throttle)
Create and send a throttle min packet.
void CommBase_SendExternalSerialSetupPacket (CommBase_t *pComm, UInt16 NetworkID, const ExternalSerial_t *pSerial)
Create and send a external serial setup packet.
void CommBase_SendExternalIOSetupPacket (CommBase_t *pComm, UInt16 NetworkID, const ExternalIO_t *pExternalIO, UInt8 pin, UInt32 SampleTime, BOOL UpdateEEPROM)
Create and send a external IO setup packet.
void CommBase_SendSimpleLandingPacket (CommBase_t *pComm, UInt16 NetworkID, const SimpleLandingPattern_t *pLand)
Create and send a simple landing packet.
void CommBase_SendDescriptionPacket (CommBase_t *pComm, UInt16 NetworkID, const char Description[64])
Create and send a parameter description packet.
void CommBase_SendUserSpacePacket (CommBase_t *pComm, UInt16 NetworkID, const UInt8 User[64])
Create and send a user space packet.
void CommBase_SendAltimeterSettingPacket (CommBase_t *pComm, UInt16 NetworkID, UInt32 Altimeter, BOOL ControlToGPS)
Create and send an altimeter setting packet.
void CommBase_SendBandwidthModePacket (CommBase_t *pComm, UInt16 NetworkID, BandwidthMode_t Bandwidth)
Create and send a bandwidth mode packet.
void CommBase_SendDoubletCommandPacket (CommBase_t *pComm, UInt16 NetworkID, const DoubletCmd_t *pDoublet)
Create and send a doublet command packet.
void CommBase_SendFrequencySweepCommandPacket (CommBase_t *pComm, UInt16 NetworkID, const FrequencySweepCmd_t *pFreqSwp)
Create and send a frequency sweep command packet.
void CommBase_SendSetFuelLevelPacket (CommBase_t *pComm, UInt16 NetworkID, float Fuel, BOOL Electric)
Create and send a set fuel level packet.
void CommBase_SendSetFuelIfLockedPacket (CommBase_t *pComm, UInt16 NetworkID, float Fuel, BOOL Electric)
Create and send a set fuel level packet for fuel update while locked.
void CommBase_SendPayloadMassPacket (CommBase_t *pComm, UInt16 NetworkID, float PayloadMass)
Create and send a payload mass packet.
void CommBase_SendFeatureCodePacket (CommBase_t *pComm, UInt16 NetworkID, const UInt8 Data[8])
Create and send a feature code packet.
void CommBase_SendTerrainElevationDataPacket (CommBase_t *pComm, UInt16 NetworkID, UInt32 Time, float Elevations[6])
Create and send terrain elevation information.
void CommBase_RequestControllerDataPacket (CommBase_t *pComm, UInt16 NetworkID, UInt8 Controller, UInt8 Version, UInt8 Category, UInt8 DataID, UInt8 NumData)
Request some controller data.
void CommBase_RequestTransponderControlPacket (CommBase_t *pComm, UInt16 NetworkID)
Request the transponder control packet.
void CommBase_RequestTransponderPreflightPacket (CommBase_t *pComm, UInt16 NetworkID)
Request the transponder preflight packet.
void CommBase_RequestTransponderInstallationPacket (CommBase_t *pComm, UInt16 NetworkID)
Request the transponder installation packet.
void CommBase_RequestRadioSettingsPacket (CommBase_t *pComm, UInt16 NetworkID)
Request the radio settings packet.
void CommBase_RequestActuatorTablePacket (CommBase_t *pComm, UInt16 NetworkID, UInt8 Sur)
Request the autopilot surface table calibration packet.
void CommBase_RequestOrientationPacket (CommBase_t *pComm, UInt16 NetworkID)
Request the autopilot orientation packet.
void CommBase_RequestMissionLimitsPacket (CommBase_t *pComm, UInt16 NetworkID)
Request the autopilot mission limits packet.
void CommBase_RequestMagCalPacket (CommBase_t *pComm, UInt16 NetworkID)
Request the packet with the magnetometer calibration data.
void CommBase_RequestSensorErrorPacket (CommBase_t *pComm, UInt16 NetworkID)
Request the packet with the sensor error data.
void CommBase_RequestExternalSerialSetupPacket (CommBase_t *pComm, UInt16 NetworkID)
Request the autopilot packet with the external serial setup parameters.
void CommBase_RequestExternalIOSetupPacket (CommBase_t *pComm, UInt16 NetworkID, UInt8 pin)
Request then autopilot packet with the setup parameters for a single external IO pin.
void CommBase_RequestDescriptionPacket (CommBase_t *pComm, UInt16 NetworkID)
Request the parameter description packet.
void CommBase_RequestUserSpacePacket (CommBase_t *pComm, UInt16 NetworkID)
Request the user space packet.
void CommBase_RequestAltimeterSettingPacket (CommBase_t *pComm, UInt16 NetworkID)
Request the altimeter setting packet.
void CommBase_RequestBandwidthModePacket (CommBase_t *pComm, UInt16 NetworkID, UInt8 NetID)
Request the bandwidth mode packet.
void CommBase_RequestSystemVersionPacket (CommBase_t *pComm, UInt16 NetworkID)
Request system version packet.
void CommBase_RequestPayloadMassPacket (CommBase_t *pComm, UInt16 NetworkID)
Request the payload mass packet.
void CommBase_RequestThrottleMinPacket (CommBase_t *pComm, UInt16 NetworkID)
Request the throttle min packet.
void CommBase_RequestRawVibrationDataPacket (CommBase_t *pComm, UInt16 NetworkID)
Request the raw vibration sensor data.
BOOL CommBase_WriteTextLogHeader (FILE *pFile)
Write the header for the log file.
BOOL CommBase_WriteTextLogLine (FILE *pFile, const UserData_t *pData, UInt8 AckRatio, const double TrackPosition[N3D], const float TrackVelocity[N3D], const float ADCSample[NUM_EXTERNAL_ADC_PINS], const ECU_t *pLeftECU, const ECU_t *pRightECU, const MovingBaseStatus_t *pMBStatus, const GPSUser_t *pGSGPS, float GSRSSI, float GSPilotPercent, float GSPilotRate)
Write a single line of data for the log file.
Detailed Description
The CCT communication library base module, autopilot packet processing. This module provides functions to send and request autopilot-specific packets.
Function Documentation
void CommBase_RequestActuatorTablePacket (CommBase_t * pComm, UInt16 NetworkID, UInt8 Sur)
Request the autopilot surface table calibration packet.
Request the autopilot actuator table calibration packet. The actuator calibration packet encodes the relationship between pulse width and actuator angle for a single actuator.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
Sur is the actuator index that the table refers to.
References ACTUATOR_TABLE, CommBase_SendAutopilotPacket(), SimplePkt_t::Data, and MakeAutopilotPacket().
Referenced by CCommManager::RequestActuatorTablePacket().
void CommBase_RequestAltimeterSettingPacket (CommBase_t * pComm, UInt16 NetworkID)
Request the altimeter setting packet.
Request the altimeter setting packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References ALTIMETER_SETTING, and CommBase_SendZeroLengthAutopilotPacket().
Referenced by CCommManager::RequestAltimeterSettingPacket().
void CommBase_RequestBandwidthModePacket (CommBase_t * pComm, UInt16 NetworkID, UInt8 NetID)
Request the bandwidth mode packet.
Request the bandwidth mode packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
NetID enumerates which link on the autopilot the data should come from, pass 0xFF to use the link this packet arrives on
References BANDWIDTH_MODE, CommBase_SendAutopilotPacket(), SimplePkt_t::Data, and MakeAutopilotPacket().
Referenced by CCommManager::RequestBandwidthModePacket().
void CommBase_RequestControllerDataPacket (CommBase_t * pComm, UInt16 NetworkID, UInt8 Controller, UInt8 Version, UInt8 Category, UInt8 DataID, UInt8 NumData)
Request some controller data.
Create and send a controller data request packet
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
Controller is the controller ID value.
Version is the controller version value.
Category is the data category.
DataID is the starting DataID.
NumData is the number of data elements to request.
References CommBase_SendAutopilotPacket(), and FormControllerDataRequestPacket().
Referenced by CCommManager::RequestControllerDataPacket().
void CommBase_RequestDescriptionPacket (CommBase_t * pComm, UInt16 NetworkID)
Request the parameter description packet.
Request the parameter description packet. The parameter description is a string which can be used to identify the set of parameters stored on the autopilot.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References CommBase_SendZeroLengthAutopilotPacket(), and DESCRIPTION.
Referenced by CCommManager::RequestDescriptionPacket().
void CommBase_RequestExternalIOSetupPacket (CommBase_t * pComm, UInt16 NetworkID, UInt8 pin)
Request then autopilot packet with the setup parameters for a single external IO pin.
Request then autopilot packet with the setup parameters for a single external IO pin.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
pin identifies which IO pin these setup data apply to.
References CommBase_SendAutopilotPacket(), SimplePkt_t::Data, EXTERNAL_IO_SETUP, and MakeAutopilotPacket().
Referenced by CCommManager::RequestExternalIOSetupPacket().
void CommBase_RequestExternalSerialSetupPacket (CommBase_t * pComm, UInt16 NetworkID)
Request the autopilot packet with the external serial setup parameters.
Request then autopilot packet with the external serial setup parameters.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References CommBase_SendZeroLengthAutopilotPacket(), and EXTERNAL_SERIAL_SETUP.
Referenced by CCommManager::RequestExternalSerialSetupPacket().
void CommBase_RequestMagCalPacket (CommBase_t * pComm, UInt16 NetworkID)
Request the packet with the magnetometer calibration data.
Request the packet with the magnetometer calibration data.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References CommBase_SendZeroLengthAutopilotPacket(), and MAG_CALIBRATION.
Referenced by CCommManager::RequestMagCalPacket().
void CommBase_RequestMissionLimitsPacket (CommBase_t * pComm, UInt16 NetworkID)
Request the autopilot mission limits packet.
Request the autopilot mission limits packet. The mission limits packet contains timeouts and actions which limit are used to limit the scope of the mission.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References CommBase_SendZeroLengthAutopilotPacket(), and MISSION_LIMITS.
Referenced by CCommManager::RequestMissionLimitsPacket().
void CommBase_RequestOrientationPacket (CommBase_t * pComm, UInt16 NetworkID)
Request the autopilot orientation packet.
Request the autopilot orientation packet. The orientation packet describes the installed orientation of the Piccolo avionics as Euler angle rotations from the avionics frame to the vehicle frame.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References CommBase_SendZeroLengthAutopilotPacket(), and SENSOR_ORIENTATION.
Referenced by CCommManager::RequestOrientationPacket().
void CommBase_RequestPayloadMassPacket (CommBase_t * pComm, UInt16 NetworkID)
Request the payload mass packet.
Request the payload mass packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References CommBase_SendZeroLengthAutopilotPacket(), and PAYLOAD_MASS.
Referenced by CCommManager::RequestPayloadMassPacket().
void CommBase_RequestRadioSettingsPacket (CommBase_t * pComm, UInt16 NetworkID)
Request the radio settings packet.
Request the autopilot radio settings packet. The radio settings packet is used to control the channel and output power of the radio.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References CommBase_SendZeroLengthAutopilotPacket(), and RADIO_SETTINGS.
Referenced by CCommManager::RequestRadioSettingsPacket().
void CommBase_RequestRawVibrationDataPacket (CommBase_t * pComm, UInt16 NetworkID)
Request the raw vibration sensor data.
Request the raw vibration sensor data. The raw vibration data comes down in 96 packets, 16 for each of six sensors, and contains 1024 samples at 1kHz.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References CommBase_SendZeroLengthAutopilotPacket(), and RAW_VIBRATION_DATA.
Referenced by CCommManager::RequestRawVibrationDataPacket().
void CommBase_RequestSensorErrorPacket (CommBase_t * pComm, UInt16 NetworkID)
Request the packet with the sensor error data.
Request the packet with the sensor error data.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References CommBase_SendZeroLengthAutopilotPacket(), and SENSOR_ERROR.
Referenced by CCommManager::RequestSensorErrorPacket().
void CommBase_RequestSystemVersionPacket (CommBase_t * pComm, UInt16 NetworkID)
Request system version packet.
Request the system version packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References CommBase_SendZeroLengthAutopilotPacket(), and SYSTEM_VERSION.
Referenced by CCommManager::RequestSystemVersionPacket().
void CommBase_RequestThrottleMinPacket (CommBase_t * pComm, UInt16 NetworkID)
Request the throttle min packet.
Request the payload mass packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References CommBase_SendZeroLengthAutopilotPacket(), and THROTTLE_MIN.
Referenced by CCommManager::RequestThrottleMinPacket().
void CommBase_RequestTransponderControlPacket (CommBase_t * pComm, UInt16 NetworkID)
Request the transponder control packet.
Request the autopilot transponder control packet. The transponder control packet is used to report the squawk code of an external tranponsder.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References CommBase_SendZeroLengthAutopilotPacket(), and TRANSPONDER_CONTROL.
Referenced by CCommManager::RequestTransponderControlPacket().
void CommBase_RequestTransponderInstallationPacket (CommBase_t * pComm, UInt16 NetworkID)
Request the transponder installation packet.
Request the transponder installation packet. The transponder installation packet is used to set/request the ICAO address and the aircraft registration.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References CommBase_SendZeroLengthAutopilotPacket(), and TRANSPONDER_INSTALLATION.
Referenced by CCommManager::RequestTransponderInstallationPacket().
void CommBase_RequestTransponderPreflightPacket (CommBase_t * pComm, UInt16 NetworkID)
Request the transponder preflight packet.
Request the transponder preflight packet. The transponder preflight packet is used to set/request the aircraft call sign.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References CommBase_SendZeroLengthAutopilotPacket(), and TRANSPONDER_PREFLIGHT.
Referenced by CCommManager::RequestTransponderPreflightPacket().
void CommBase_RequestUserSpacePacket (CommBase_t * pComm, UInt16 NetworkID)
Request the user space packet.
Request the user space packet. The user space packet is used to write user data to nonvolatile storage on the avionics. This data space is intended to be used by third-party applications which must store information on the autopilot.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
References CommBase_SendZeroLengthAutopilotPacket(), and USER_SPACE.
Referenced by CCommManager::RequestUserSpacePacket().
void CommBase_SendActuatorTablePacket (CommBase_t * pComm, UInt16 NetworkID, const ActuatorTable_t * pTable, UInt8 Sur, UInt8 Type, UInt8 Virtual, UInt8 Fast)
Create and send a control actuator calibration packet.
Create and send a autopilot surface table calibration packet. The surface calibration packet encodes the relationship between pulse width and surface angle for a single surface.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
pTable points to a single surface calibration table.
Sur is the surface index that the table refers to.
Type is the actuator type data.
Virtual should be 1 if this is a virtual (CAN output only) actuator.
Fast should be 1 if this is a fast (200 Hz update rate) actuator.
References CommBase_SendAutopilotPacket(), and FormActuatorTablePacket().
Referenced by CCommManager::SendActuatorTablePacket().
void CommBase_SendActuatorTypePacket (CommBase_t * pComm, UInt16 NetworkID, UInt8 Sur, UInt8 Type)
Create and send a packet to change actuator type.
Create and send a packet to change the type of an actuator without changing the calibration table.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
pTable points to a single surface calibration table.
Sur is the surface index that the table refers to.
Type is the actuator type data.
References ACTUATOR_TABLE, CommBase_SendAutopilotPacket(), SimplePkt_t::Data, and MakeAutopilotPacket().
Referenced by CCommManager::SendActuatorTypePacket().
void CommBase_SendAirDataZeroPacket (CommBase_t * pComm, UInt16 NetworkID, float ActualAltitude)
Create and send the zero air data command packet.
Create and send the zero air data command packet. This commands the autopilot to zero the airspeed and altitude sensors. This packet should not be sent while the vehicle is flying.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
ActualAltitude is current altitude in meters. It is used (along with the altimeter setting) to determine the static pressure error. If the static pressure sensor should not be zeroed then supply an ActualAltitude value which is less than -5000
References AIR_DATA_ZERO, CommBase_SendAutopilotPacket(), SimplePkt_t::Data, MakeAutopilotPacket(), and SInt32ToData().
Referenced by CCommManager::SendAirDataZeroPacket().
void CommBase_SendAltimeterSettingPacket (CommBase_t * pComm, UInt16 NetworkID, UInt32 Altimeter, BOOL ControlToGPS)
Create and send an altimeter setting packet.
Create and send a altimeter setting packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Altimeter is the altimeter setting in Pascals.
ControlToGPS should be TRUE to tell the autopilot to use the GPS altitude as its control target.
References CommBase_SendAutopilotPacket(), and FormAltimeterSettingPacket().
Referenced by CCommManager::SendAltimeterSettingPacket().
void CommBase_SendAutopilotLoopControlPacket (CommBase_t * pComm, UInt16 NetworkID, const AutopilotLoopCmd_t * pCmd, BOOL UpdateEEPROM)
Create and send a autopilot loop control packet.
Create and send a autopilot loop control packet. The loop control packet is used to change individual autopilot loops without changing the state of the other loops.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
pCmd points to individual loop data to be included in the packet.
UpdateEEPROM should be TRUE to cause the autopilot to write this data to EEPROM.
References CommBase_SendAutopilotPacket(), and FormAutopilotLoopControlPacketEx().
Referenced by CCommManager::SendAutopilotLoopControlPacket().
void CommBase_SendAutopilotPacket (CommBase_t * pComm, UInt16 NetworkID, const AutopilotPkt_t * pPkt)
Send a autopilot packet.
Send an autopilot stream packet.
Parameters
pComm points to the communication interface data.
NetworkID is the destination network address.
pPkt points to the autopilot packet to send.
References AUTOPILOT_STREAM, CommBase_SendBlock(), and SimplePkt_t::Size.
Referenced by CommBase_RequestActuatorTablePacket(), CommBase_RequestBandwidthModePacket(), CommBase_RequestControllerDataPacket(), CommBase_RequestExternalIOSetupPacket(), CommBase_SendActuatorTablePacket(), CommBase_SendActuatorTypePacket(), CommBase_SendAirDataZeroPacket(), CommBase_SendAltimeterSettingPacket(), CommBase_SendAutopilotLoopControlPacket(), CommBase_SendBandwidthModePacket(), CommBase_SendBoundaryPacket(), CommBase_SendBrakesCommandPacket(), CommBase_SendConfigurationLockPacket(), CommBase_SendConfigurationUnlockPacket(), CommBase_SendControllerDataDefaultPacket(), CommBase_SendControllerDataPacket(), CommBase_SendDescriptionPacket(), CommBase_SendDoubletCommandPacket(), CommBase_SendDropCommandPacket(), CommBase_SendEngineKillPacket(), CommBase_SendExternalIOSetupPacket(), CommBase_SendExternalSerialSetupPacket(), CommBase_SendFeatureCodePacket(), CommBase_SendFrequencySweepCommandPacket(), CommBase_SendLandNowPacket(), CommBase_SendLaunchNowPacket(), CommBase_SendLegacyWaypointListPacket(), CommBase_SendLegacyWaypointPacket(), CommBase_SendLightsCommandPacket(), CommBase_SendMagCalPacket(), CommBase_SendManualAssistModePacket(), CommBase_SendMissionLimitsPacket(), CommBase_SendMissionSettingsPacket(), CommBase_SendOrientationPacket(), CommBase_SendParachuteCommandPacket(), CommBase_SendPayloadMassPacket(), CommBase_SendPrelaunchPacket(), CommBase_SendRadioSettingsPacket(), CommBase_SendSensorErrorPacket(), CommBase_SendSetFuelIfLockedPacket(), CommBase_SendSetFuelLevelPacket(), CommBase_SendSimpleLandingPacket(), CommBase_SendSurfaceTestPacket(), CommBase_SendTerrainElevationDataPacket(), CommBase_SendThrottleMinPacket(), CommBase_SendThrottleTrimPacket(), CommBase_SendTrackCommandPacket(), CommBase_SendTransponderControlPacket(), CommBase_SendTransponderInstallationPacket(), CommBase_SendTransponderPreflightPacket(), CommBase_SendUserActionPacket(), CommBase_SendUserSpacePacket(), CommBase_SendWaypointListPacket(), CommBase_SendWaypointListRangePacket(), CommBase_SendWaypointsPacket(), CommBase_SendZeroLengthAutopilotPacket(), and CCommManager::SendAutopilotPacket().
void CommBase_SendBandwidthModePacket (CommBase_t * pComm, UInt16 NetworkID, BandwidthMode_t Bandwidth)
Create and send a bandwidth mode packet.
Create and send a altimeter setting packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to. Bandwidth is the data to send
References CommBase_SendAutopilotPacket(), and FormBandwidthModePacket().
Referenced by CCommManager::SendBandwidthModePacket().
void CommBase_SendBoundaryPacket (CommBase_t * pComm, UInt16 NetworkID, const Boundary_t * pBnd)
Create and send a airspace boundary packet.
Create and send a airspace boundary packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
pBnd is the boundary to send
References CommBase_SendAutopilotPacket(), and FormBoundaryPacket().
Referenced by CCommManager::SendBoundaryPacket().
void CommBase_SendBrakesCommandPacket (CommBase_t * pComm, UInt16 NetworkID, float Brakes)
Create and send the brakes command packet.
Create and send the brakes command packet. The brakes command asserts or deasserts the brake IO line(s), or actuates the brake servo(s). This command will have no effect if no IO lines are programmed for brake operation. The brake state is visible in the AUTOPILOT_COMMAND downlink packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Brakes gives the level of brakes actuation from 0 (brakes released) to 1 (brakes fully applied).
References BRAKES_CMD, CommBase_SendAutopilotPacket(), SimplePkt_t::Data, MakeAutopilotPacket(), and UInt16ToData().
Referenced by CCommManager::SendBrakesCommandPacket().
void CommBase_SendConfigurationLockPacket (CommBase_t * pComm, UInt16 NetworkID, const char Password[32])
Create and send a configuration lock packet.
Create and send a configuration lock packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Password is the pasword touse in the packet, send NULL for zero length packet.
References CommBase_SendAutopilotPacket(), and FormConfigurationLockPacket().
Referenced by CCommManager::SendConfigurationLockPacket().
void CommBase_SendConfigurationUnlockPacket (CommBase_t * pComm, UInt16 NetworkID, const char Password[32], BOOL Silent)
Create and send a configuration unlock packet.
Create and send a configuration unlock packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Password is the pasword touse in the packet, send NULL for zero length packet.
Silent should be TRUE to use the quiet version of this packet
References CommBase_SendAutopilotPacket(), and FormConfigurationUnlockPacket().
Referenced by CCommManager::SendConfigurationUnlockPacket().
void CommBase_SendControllerDataDefaultPacket (CommBase_t * pComm, UInt16 NetworkID, UInt8 Controller, UInt8 Version, UInt8 Category, UInt8 DataID, UInt8 NumData)
Create and send a controller packet to default data.
Create and send a controller data packet which defaults data.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Controller is the controller ID value.
Version is the controller version value.
Category is the data category.
DataID is the starting DataID.
NumData is the number of data elements to encode.
References CommBase_SendAutopilotPacket(), and FormControllerDataDefaultPacket().
Referenced by CCommManager::SendControllerDataDefaultPacket().
void CommBase_SendControllerDataPacket (CommBase_t * pComm, UInt16 NetworkID, UInt8 Controller, UInt8 Version, UInt8 Category, UInt8 DataID, UInt8 NumData, const void * pData)
Create and send a controller packet.
Create and send a controller data packet which contains 32-bit data words.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Controller is the controller ID value.
Version is the controller version value.
Category is the data category.
DataID is the starting DataID.
NumData is the number of data elements to encode.
pData points to the data to encode.
References CommBase_SendAutopilotPacket(), and FormControllerDataPacket().
Referenced by CCommManager::SendControllerDataPacket().
void CommBase_SendDescriptionPacket (CommBase_t * pComm, UInt16 NetworkID, const char Description[64])
Create and send a parameter description packet.
Create and send a parameter description packet. The parameter description is a string which can be used to identify the set of parameters stored on the autopilot.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Description is an array of bytes to send as the description. The array should contain a NULL-terminated string.
References CommBase_SendAutopilotPacket(), SimplePkt_t::Data, DESCRIPTION, and MakeAutopilotPacket().
Referenced by CCommManager::SendDescriptionPacket().
void CommBase_SendDoubletCommandPacket (CommBase_t * pComm, UInt16 NetworkID, const DoubletCmd_t * pDoublet)
Create and send a doublet command packet.
Create and send a doublet command packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
pDoublet points to space containing the doublet command data
References CommBase_SendAutopilotPacket(), and FormDoubletCommandPacket().
Referenced by CCommManager::SendDoubletCommandPacket().
void CommBase_SendDropCommandPacket (CommBase_t * pComm, UInt16 NetworkID, BOOL DropOn)
Create and send the drop command packet.
Create and send the drop command packet. The drop command asserts or deasserts the drop IO line(s), or actuates the drop servo(s). This command will have no effect if no IO lines are programmed for drop operation. The drop state is visible in the AUTOPILOT_COMMAND downlink packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
DropOn should be TRUE to turn the drop on, else it will be turned off.
References CommBase_SendAutopilotPacket(), SimplePkt_t::Data, DROP_CMD, and MakeAutopilotPacket().
Referenced by CCommManager::SendDropCommandPacket().
void CommBase_SendEngineKillPacket (CommBase_t * pComm, UInt16 NetworkID, BOOL EngineKill)
Create and send the engine kill packet.
Create and send the engine kill packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
EngineKill should be TRUE to kill the engine, FALSE to enable the engine.
References CommBase_SendAutopilotPacket(), SimplePkt_t::Data, ENGINE_KILL, and MakeAutopilotPacket().
Referenced by CCommManager::SendEngineKillPacket().
void CommBase_SendExternalIOSetupPacket (CommBase_t * pComm, UInt16 NetworkID, const ExternalIO_t * pExternalIO, UInt8 pin, UInt32 SampleTime, BOOL UpdateEEPROM)
Create and send a external IO setup packet.
Create and send an autopilot packet with the setup parameters for a single external IO pin.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
pExternalIO points to a structure containing the setup parameters.
pin identifies which IO pin these setup data apply to.
SampleTime is the time in milliseconds that the external IO inputs should be sampled.
UpdateEEPROM should be TRUE to cause the autopilot to write this data to EEPROM.
References CommBase_SendAutopilotPacket(), and FormExternalIOSetupPacketEx().
Referenced by CCommManager::SendExternalIOSetupPacket().
void CommBase_SendExternalSerialSetupPacket (CommBase_t * pComm, UInt16 NetworkID, const ExternalSerial_t * pSerial)
Create and send a external serial setup packet.
Create and send an autopilot packet with the external serial setup parameters.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
pSerial points to a structure containing the serial setup parameters.
References CommBase_SendAutopilotPacket(), and FormExternalSerialSetupPacket().
Referenced by CCommManager::SendExternalSerialSetupPacket().
void CommBase_SendFeatureCodePacket (CommBase_t * pComm, UInt16 NetworkID, const UInt8 Data[8])
Create and send a feature code packet.
Create and send a feature code packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Data is the 8 byte feature code.
References CommBase_SendAutopilotPacket(), and FormFeatureCodePacket().
Referenced by CCommManager::SendFeatureCodePacket().
void CommBase_SendFrequencySweepCommandPacket (CommBase_t * pComm, UInt16 NetworkID, const FrequencySweepCmd_t * pFreqSwp)
Create and send a frequency sweep command packet.
Create and send a frequency sweep command packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
pFreqSwp points the the frequency sweep settings structure.
References CommBase_SendAutopilotPacket(), and FormFrequencySweepCommandPacket().
Referenced by CCommManager::SendFrequencySweepCommandPacket().
void CommBase_SendLandNowPacket (CommBase_t * pComm, UInt16 NetworkID)
Create and send the land now command packet.
Create and send the land now command packet. This commands the autopilot to being tracking the landing flight plan as identified in the mission limits.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
References CommBase_SendAutopilotPacket(), LAND_NOW, and MakeAutopilotPacket().
Referenced by CCommManager::SendLandNowPacket().
void CommBase_SendLaunchNowPacket (CommBase_t * pComm, UInt16 NetworkID)
Create and send the launch now command packet.
Create and send the land now command packet. This commands the autopilot to initiate the launch sequence.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
References CommBase_SendAutopilotPacket(), LAUNCH_NOW, and MakeAutopilotPacket().
Referenced by CCommManager::SendLaunchNowPacket().
void CommBase_SendLegacyWaypointListPacket (CommBase_t * pComm, UInt16 NetworkID, const FPMask_t Mask, UInt8 Flag)
Create and send a legacy waypoint list packet.
Create and send a autopilot waypoint list packet. This packet contains a flight plan mask with one bit for every possible waypoint; and a flags parameter telling the avionics how to use the mask.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Mask is the flight plan mask to be encoded.
Flag is the flight plan mask flags field. The flag should have one of these values:
GET_WAYPOINT_LIST: indicates that the avionics should downlink a valid waypoint list.
DELETE_WAYPOINTS: indicates that the avionics should delete each waypoint in the list.
REQUEST_WAYPOINTS: indicates that the avionics should downlink each waypoint in the list.
WAYPOINT_BLOCK: indicates that a waypoint bock transfer is beginning. The waypoints to be transferred are in the list.
References CommBase_SendAutopilotPacket(), and FormLegacyWaypointListPacket().
Referenced by CCommManager::SendLegacyWaypointListPacket().
void CommBase_SendLegacyWaypointPacket (CommBase_t * pComm, UInt16 NetworkID, const FPPoint_t * pPoint, UInt8 Index)
Create and send a legacy waypoint packet.
Create and send a legacy autopilot waypoint packet (prior to software 2.2.x). This packet contains all the data for a single waypoint.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
pPoint contains the waypoint data.
Index is the waypoint index.
References CommBase_SendAutopilotPacket(), and FormLegacyWaypointPacket().
Referenced by CCommManager::SendLegacyWaypointPacket().
void CommBase_SendLightsCommandPacket (CommBase_t * pComm, UInt16 NetworkID, BOOL LightsOn)
Create and send the lights command packet.
Create and send the lights command packet. The lights command asserts or deasserts the lights IO line(s). This command will have no effect if no IO lines are programmed for lights operation. The ligths state is visible in the AUTOPILOT_COMMAND downlink packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
LightsOn should be TRUE to turn the lights on, else they will be turned off.
References CommBase_SendAutopilotPacket(), SimplePkt_t::Data, LIGHTS_CMD, and MakeAutopilotPacket().
Referenced by CCommManager::SendLightsCommandPacket().
void CommBase_SendMagCalPacket (CommBase_t * pComm, UInt16 NetworkID, const float HardIronErr[N3D], const float ScaleFactErr[N3D])
Create and send a magnetic sensor calibration packet.
Create and send a packet with the magnetometer calibration data.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
HardIronErr is a vector of hard iron errors.
ScaleFactErr is a vector of scale factor errors.
References CommBase_SendAutopilotPacket(), and FormMagCalPacket().
Referenced by CCommManager::SendMagCalPacket().
void CommBase_SendManualAssistModePacket (CommBase_t * pComm, UInt16 NetworkID, UInt8 Mode)
Create and send the manual assist mode command packet.
Create and send the manual assist mode command packet. The assist mode controls how the autopilot uses the manual control data when the autopilot is globally on. The current manual assist mode is visible in the AUTOPILOT_COMMAND downlink packet. The manual assist modes are:
MA_STANDARD: No manual assistance
MA_LATERAL: Roll control plus rudder
MA_LONGITUDINAL: Speed control plus throttle and flaps
MA_ALL: Roll, speed, rudder, throttle, and flaps
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Mode is the mode to go to.
References CommBase_SendAutopilotPacket(), SimplePkt_t::Data, MakeAutopilotPacket(), and NEW_MANUAL_ASSIST_MODE.
Referenced by CCommManager::SendManualAssistModePacket().
void CommBase_SendMissionLimitsPacket (CommBase_t * pComm, UInt16 NetworkID, const MissionLimits_t * pMission)
Create and send a mission limits packet.
Create and send a autopilot mission limits packet. The mission limits packet contains timeouts and actions which limit are used to limit the scope of the mission.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
pMission points to the mission limit data.
References CommBase_SendAutopilotPacket(), and FormMissionLimitsPacket().
Referenced by CCommManager::SendMissionLimitsPacket().
void CommBase_SendMissionSettingsPacket (CommBase_t * pComm, UInt16 NetworkID, SInt16 MinAltitude, SInt16 MaxAltitude, UInt32 FlightTimeout)
Create and a send a mission settings packet.
Create and send a autopilot mission settings packet which sets the altitude limits and flight timeout.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
MinAltitude is the minimum altitude in meters.
MaxAltitude is the maximum altitude in meters.
FlightTimeout is the flight timeout in seconds
References CommBase_SendAutopilotPacket(), and FormMissionSettingsPacket().
Referenced by CCommManager::SendMissionSettingsPacket().
void CommBase_SendOrientationPacket (CommBase_t * pComm, UInt16 NetworkID, const float Euler[NAXIS], const float IMUtoAnt[N3D], const float IMUtoAnt2[N3D])
Create and send a sensor orientatin packet.
Create and send a autopilot orientation packet. The orientation packet describes the installed orientation of the Piccolo avionics as Euler angle rotations from the avionics frame to the vehicle frame.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Euler is an array of Euler angles (ROLL, PITCH, YAW).
IMUtoAnt is an array that holds the position offset from IMU to primary GPS antenna.
IMUtoAnt2 is an array that holds the position offset from IMU to secondary GPS antenna.
References CommBase_SendAutopilotPacket(), and FormOrientationPacket().
Referenced by CCommManager::SendOrientationPacket().
void CommBase_SendParachuteCommandPacket (CommBase_t * pComm, UInt16 NetworkID, BOOL ParachuteDeploy)
Create and send the parachute command packet.
Create and send the parachute command packet. The parachute command asserts or deasserts the parachute IO line(s), or actuates the parachute servo(s). This command will have no effect if no IO lines are programmed for parachute operation. The parachute state is visible in the AUTOPILOT_COMMAND downlink packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
ParachuteDeploy should be TRUE to deploy the parachute, else it will be retracted.
References CommBase_SendAutopilotPacket(), SimplePkt_t::Data, MakeAutopilotPacket(), and PARACHUTE_CMD.
Referenced by CCommManager::SendParachuteCommandPacket().
void CommBase_SendPayloadMassPacket (CommBase_t * pComm, UInt16 NetworkID, float PayloadMass)
Create and send a payload mass packet.
Create and send a set fuel level packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
PayloadMass is the payload mass in kilograms
References CommBase_SendAutopilotPacket(), and FormPayloadMassPacket().
Referenced by CCommManager::SendPayloadMassPacket().
void CommBase_SendPrelaunchPacket (CommBase_t * pComm, UInt16 NetworkID)
Create and send the go to prelaunch command packet.
Create and send the prelaunch command packet. This commands the autopilot to go to prelaunch mode.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
References CommBase_SendAutopilotPacket(), MakeAutopilotPacket(), and PRE_LAUNCH_MODE.
Referenced by CCommManager::SendPrelaunchPacket().
void CommBase_SendRadioSettingsPacket (CommBase_t * pComm, UInt16 NetworkID, const RadioSettings_t * pSettings)
Create and send a radio settings packet.
Create and send a autopilot radio settings packet. The radio settings packet is used to control the channel and output power of the radio.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
pSettings points to radio settings to be included in the packet.
References CommBase_SendAutopilotPacket(), and FormRadioSettingsPacket().
Referenced by CCommManager::SendRadioSettingsPacket().
void CommBase_SendSensorErrorPacket (CommBase_t * pComm, UInt16 NetworkID, const SensorErrorData_t * pSensorError)
Create and send a sensor error.
Create and send a packet with the AGL offset.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
pSensorError is the data to send.
References CommBase_SendAutopilotPacket(), and FormSensorErrorPacket().
Referenced by CCommManager::SendSensorErrorPacket().
void CommBase_SendSetFuelIfLockedPacket (CommBase_t * pComm, UInt16 NetworkID, float Fuel, BOOL Electric)
Create and send a set fuel level packet for fuel update while locked.
Create and send a set fuel level packet to change fuel level even if the autopilot is locked.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Fuel is the fuel level in kilograms or Watt-Hours.
Electric is TRUE for electric motor (fuel in Watt-Hours).
References CommBase_SendAutopilotPacket(), and FormSetFuelIfLockedPacket().
Referenced by CCommManager::SendSetFuelIfLockedPacket().
void CommBase_SendSetFuelLevelPacket (CommBase_t * pComm, UInt16 NetworkID, float Fuel, BOOL Electric)
Create and send a set fuel level packet.
Create and send a set fuel level packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Fuel is the fuel level in kilograms or Watt-Hours.
Electric is TRUE for electric motor (fuel in Watt-Hours).
References CommBase_SendAutopilotPacket(), and FormSetFuelLevelPacket().
Referenced by CCommManager::SendSetFuelLevelPacket().
void CommBase_SendSimpleLandingPacket (CommBase_t * pComm, UInt16 NetworkID, const SimpleLandingPattern_t * pLand)
Create and send a simple landing packet.
Create and send a packet containing the simple landing pattern information necessary for creating a simple landing pattern flightplan.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
pLand points to a simple landing pattern data structure.
References CommBase_SendAutopilotPacket(), and FormSimpleLandingPacket().
Referenced by CCommManager::SendSimpleLandingPacket().
void CommBase_SendSurfaceTestPacket (CommBase_t * pComm, UInt16 NetworkID, float Angle, float Width, float Freq, float Dev, UInt8 Index)
Create and send a surface test packet.
Create and send a autopilot surface test packet. The surface test packet is used to send test signals to specific control surfaces.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Angle is the actuator angle to apply to the test, in rad. Pass more than 3.14 to disable angle test.
Width is the actuator pulse width to apply to the test, in microseconds. Pass zero to disable pulse test.
Freq is the frequency in hertz to use for sinusoidal test, pass more than 0.01 to enable.
Dev is the amplitude of the sinusoidal test in radians.
Index is the index of the control surface to apply the test to.
References CommBase_SendAutopilotPacket(), and FormActuatorTestPacket().
Referenced by CCommManager::SendSurfaceTestPacket().
void CommBase_SendTerrainElevationDataPacket (CommBase_t * pComm, UInt16 NetworkID, UInt32 Time, float Elevations[6])
Create and send terrain elevation information.
Create and send a packet used to uplink terrain elevation data to the avionics.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Time is the system time at which the elevation data apply.
Elevations is the array of terrian elevations spaced 2 seconds apart, with the first element corresponding to Time.
References CommBase_SendAutopilotPacket(), and FormTerrainElevationDataPacket().
Referenced by CCommManager::SendTerrainElevationDataPacket().
void CommBase_SendThrottleMinPacket (CommBase_t * pComm, UInt16 NetworkID, float Throttle)
Create and send a throttle min packet.
Create and send the throttle minimum command packet. The throttle min packet sets the minimum allowable throttle position for the autopilot.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Throttle gives the throttle min value, from 0 to 1.0.
References CommBase_SendAutopilotPacket(), and FormThrottleMinPacket().
Referenced by CCommManager::SendThrottleMinPacket().
void CommBase_SendThrottleTrimPacket (CommBase_t * pComm, UInt16 NetworkID, float Throttle)
Create and send the throttle trim command packet.
Create and send the throttle trim command packet. The throttle trim is used to set the throttle position in prelaunch mode, and to set the autopilot throttle start point.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Throttle gives the throttle trim value, from 0 to 1.
References CommBase_SendAutopilotPacket(), SimplePkt_t::Data, MakeAutopilotPacket(), RoundToUInt16(), THROTTLE_TRIM, and UInt16ToData().
Referenced by CCommManager::SendThrottleTrimPacket().
void CommBase_SendTrackCommandPacket (CommBase_t * pComm, UInt16 NetworkID, UInt16 Waypoint, BOOL GoTo)
Create and send a track command packet.
Create and send a track command packet. The track command will tell the autopilot to track to a specific waypoint. The waypoint must already be part of a valid flight plan onboard the autopilot.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Waypoint is the index of the waypoint to track to.
GoTo indicates if the vehicle should fly to the waypoint along the preceding track segment, or if it should go directly to the waypoint, using its current position as the starting point. Set to TRUE to go directly to the waypoint.
References CommBase_SendAutopilotPacket(), SimplePkt_t::Data, MakeAutopilotPacket(), TRACK, and UInt16ToData().
Referenced by CCommManager::SendTrackCommandPacket().
void CommBase_SendTransponderControlPacket (CommBase_t * pComm, UInt16 NetworkID, UInt16 Code, BOOL Ident, UInt8 Mode)
Create and send a transponder control packet.
Create and send a autopilot transponder control packet. The transponder control packet is used to set the squawk code and ident flag of an external transponder.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Code is the transponder squawk code to use.
Ident should be true to cause the tranponder to Ident.
Mode is the transponder mode, 0 for standby, 1 for mode A, 2 for mode C, 3 for altitude display.
References CommBase_SendAutopilotPacket(), and FormTransponderControlPacket().
Referenced by CCommManager::SendTransponderControlPacket().
void CommBase_SendTransponderInstallationPacket (CommBase_t * pComm, UInt16 NetworkID, UInt32 ICAOAddress, const char Registration[9])
Create and send a transponder installation packet.
Create and send a transponder installation packet. This is used to set/request the ICAO address and aircraft registration, and it applies only to Mode S transponders.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
ICAOAddress is a 3-byte number representing the new ICAO address, to be set into the Mode S transponder.
Registration is a string containing the new alphanumeric aircraft registration to be set into the Mode S transponder.
References CommBase_SendAutopilotPacket(), and FormTransponderInstallationPacket().
Referenced by CCommManager::SendTransponderInstallationPacket().
void CommBase_SendTransponderPreflightPacket (CommBase_t * pComm, UInt16 NetworkID, const char FlightID[9])
Create and send a transponder preflight packet.
Create and send a transponder preflight packet. The transponder preflight packet is used to set/request the aircraft call sign, and applies only to Mode S transponders.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
FlightID is a string containing the new alphanumeric call sign to be set into the Mode S transponder.
References CommBase_SendAutopilotPacket(), and FormTransponderPreflightPacket().
Referenced by CCommManager::SendTransponderPreflightPacket().
void CommBase_SendUserActionPacket (CommBase_t * pComm, UInt16 NetworkID, UInt8 ActionIndex, BOOL On)
Create and send a user action command packet.
Create and send the user action command.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
ActionIndex is the index of the user action.
On should be TRUE to assert the action.
References CommBase_SendAutopilotPacket(), and FormUserActionPacket().
Referenced by CCommManager::SendUserActionPacket().
void CommBase_SendUserSpacePacket (CommBase_t * pComm, UInt16 NetworkID, const UInt8 User[64])
Create and send a user space packet.
Create and send a user space packet. The user space packet is used to write user data to nonvolatile storage on the avionics. This data space is intended to be used by third-party applications which must store information on the autopilot.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
User is an array of bytes to record on the autopilot.
References CommBase_SendAutopilotPacket(), SimplePkt_t::Data, MakeAutopilotPacket(), and USER_SPACE.
Referenced by CCommManager::SendUserSpacePacket().
void CommBase_SendWaypointListPacket (CommBase_t * pComm, UInt16 NetworkID, const FPMask_t Mask, UInt8 Flag)
Create and send a waypoint list packet.
Create and send a autopilot waypoint list packet. This packet contains a flight plan mask with one bit for every possible waypoint; and a flags parameter telling the avionics how to use the mask.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Mask is the flight plan mask to be encoded.
Flag is the flight plan mask flags field. The flag should have one of these values:
GET_WAYPOINT_LIST: indicates that the avionics should downlink a valid waypoint list.
DELETE_WAYPOINTS: indicates that the avionics should delete each waypoint in the list.
REQUEST_WAYPOINTS: indicates that the avionics should downlink each waypoint in the list.
WAYPOINT_BLOCK: Prepare to receive waypoints (both ways).
WAYPOINT_ACK: Acknowledge receive of waypoints (both ways)
References CommBase_SendAutopilotPacket(), and FormWaypointListPacket().
Referenced by CCommManager::SendWaypointListPacket().
void CommBase_SendWaypointListRangePacket (CommBase_t * pComm, UInt16 NetworkID, UInt16 Start, UInt16 End, UInt8 Flag)
Create and send a waypoint list packet using a range of points.
Create and send a autopilot waypoint list packet using a range of points.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Start is the first waypoint index to be asserted.
End is the last waypoint index to be asserted.
Flag is the flight plan mask flags field. The flag should have one of these values:
GET_WAYPOINT_LIST: indicates that the avionics should downlink a valid waypoint list.
DELETE_WAYPOINTS: indicates that the avionics should delete each waypoint in the list.
REQUEST_WAYPOINTS: indicates that the avionics should downlink each waypoint in the list.
WAYPOINT_BLOCK: Prepare to receive waypoints (both ways).
WAYPOINT_ACK: Acknowledge receive of waypoints (both ways)
References CommBase_SendAutopilotPacket(), and FormWaypointListRangePacket().
Referenced by CCommManager::SendWaypointListRangePacket().
void CommBase_SendWaypointsPacket (CommBase_t * pComm, UInt16 NetworkID, const FPPoint_t Points[MAX_WAYPOINTS_IN_PACKET], UInt16 Num, BOOL Ack)
Create and send waypoints packet.
Create and send a autopilot waypoints packet. This packet contains all the data for a one or more waypoints, up to MAX_WAYPOINTS_IN_PACKET.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Point contains the waypoints data.
Num is the number of waypoints to send.
Ack should be TRUE to set the ack bit.
References CommBase_SendAutopilotPacket(), and FormWaypointsPacket().
Referenced by CCommManager::SendWaypointsPacket().
void CommBase_SendZeroLengthAutopilotPacket (CommBase_t * pComm, UInt16 NetworkID, UInt8 PktType)
Send a zero length autopilot packet.
Send a zero length autopilot packet.
Parameters
NetworkID is the destination network address.
PktType is the type of the autopillot packet.
References CommBase_SendAutopilotPacket(), and MakeAutopilotPacket().
Referenced by CommBase_RequestAltimeterSettingPacket(), CommBase_RequestDescriptionPacket(), CommBase_RequestExternalSerialSetupPacket(), CommBase_RequestMagCalPacket(), CommBase_RequestMissionLimitsPacket(), CommBase_RequestOrientationPacket(), CommBase_RequestPayloadMassPacket(), CommBase_RequestRadioSettingsPacket(), CommBase_RequestRawVibrationDataPacket(), CommBase_RequestSensorErrorPacket(), CommBase_RequestSystemVersionPacket(), CommBase_RequestThrottleMinPacket(), CommBase_RequestTransponderControlPacket(), CommBase_RequestTransponderInstallationPacket(), CommBase_RequestTransponderPreflightPacket(), CommBase_RequestUserSpacePacket(), and CCommManager::SendZeroLengthAutopilotPacket().
BOOL CommBase_WriteTextLogHeader (FILE * pFile)
Write the header for the log file.
Write the header for the text log file
Parameters
pFile points to an open stream to write the log file header to.
Returns
TRUE if the header was written successfully, else FALSE
References NUM_ACTUATORS, and NUM_EXTERNAL_ADC_PINS.
Referenced by CCommManager::WriteTextLogHeader().
BOOL CommBase_WriteTextLogLine (FILE * pFile, const UserData_t * pData, UInt8 AckRatio, const double TrackPosition[N3D], const float TrackVelocity[N3D], const float ADCSample[NUM_EXTERNAL_ADC_PINS], const ECU_t * pLeftECU, const ECU_t * pRightECU, const MovingBaseStatus_t * pMBStatus, const GPSUser_t * pGSGPS, float GSRSSI, float GSPilotPercent, float GSPilotRate)
Write a single line of data for the log file.
Write a data line into the autopilot log file.
Parameters
pFile points to the autopilot log file, assumed open for writing.
pData points to the user telemetry data.
AckRatio is the autopilot acknowledgement ratio.
TrackPosition is the aircraft relative position in the track frame, in m.
TrackVelocity is the aircraft velocity in the track frame, in m/s.
ADCSample is the array of analog input samples.
pLeftECU points to the left side ECU status data.
pRightECU points to the right side ECU status data.
pMBStatus points to the DGPS moving base solution status.
pGSGPS points to the groundstation GPS data.
GSRRSI is the RSSI reported by the groundstation radio.
GSPilotPercent is the acknowledgement ration for manual pilot data, reported by the groundstation.
GSPilotRate is the frame rate for the manual pilot data, in Hz, reported by the groundstation.
< No solution
< Fixed position solution
< Fixed height solution (i.e. 2D)
< Velocity from doppler
< Single point solution
< Pseudo range differential solution
< Satellite based augmentation system solution
< Solution propagated by receiver
< Omnistar VBS solution
< L1 only floating RTK solution
< No ionospheric corrections
< L1/L2 floating RTK solution
< L1 integer (high performance) RTK solution
< L1/L2 narrow lane integer RTK solution (the best!)
< Ominstar HP solution
< Ominstar XP solution
References NavStatus_t::AccBiasGood, UserData_t::Accel, NavDiagnostic_t::AccelBias, GenericActionBits_t::Action0, GenericActionBits_t::Action1, GenericActionBits_t::Action2, GenericActionBits_t::Action3, GenericActionBits_t::Action4, GenericActionBits_t::Action5, GenericActionBits_t::Action6, GenericActionBits_t::Action7, AutopilotStatus_t::ActionStates, UserData_t::Actuators, ActionBits_t::AeroTermination, ECU_t::AFR, ECUFlags_t::AFRandComp_included, ECU_t::AFRcomp, UserData_t::AGL, NavStatus_t::AGLGood, UserData_t::AlignHeading, UserData_t::AlignHeadingSigma, UserData_t::AlignSolnType, ALT, DataSource_t::AltControlType, GPSUser_t::Altitude, UserData_t::AltUsed, UserData_t::AP, AP_AUTO, AP_ON, AutopilotStatus_t::APMode, AutopilotStatus_t::AssistMode, NavStatus_t::AttitudeGood, UserData_t::AvailableData, UserData_t::BaroAlt, NavStatus_t::BaroGood, MovingBaseStatus_t::Baseline, MovingBaseStatus_t::BelowTrack, SystemDiagnostic_t::BoardTemp, AutopilotStatus_t::BoundaryIsViolated, ActionBits_t::Brakes, ECU_t::CHT_A, ECUFlags_t::CHT_A_included, ECU_t::CHT_B, ECUFlags_t::CHT_B_included, AutopilotStatus_t::CommTimeout, SystemDiagnostic_t::CPULoad, SystemDiagnostic_t::CPUVoltageBIT, MovingBaseStatus_t::CrossTrack, GPSUser_t::day, AutopilotStatus_t::Deadman, GPSUser_t::Direction, DOPPLER_VELOCITY_PVTYPE, DOWN, ActionBits_t::Drop, EAST, ECUFlags_t::ECU_volt_included, ECU_t::EGT_A, ECUFlags_t::EGT_A_included, ECU_t::EGT_B, ECUFlags_t::EGT_B_included, ActionBits_t::EngineKill, ECU_t::EngineTime, ECUFlags_t::EngineTime_included, ECU_t::ErrorBits, ECUFlags_t::ErrorBits_A_included, ECUFlags_t::ErrorBits_B_included, MovingBaseStatus_t::ETA, UserData_t::Euler, FILTER_AHRS, FILTER_ALIGN, FILTER_BOUND_VEL, FILTER_BUFFERING, FILTER_INIT, FILTER_NORMAL, SystemDiagnostic_t::FirstStageBIT, SystemDiagnostic_t::FiveAnalogBIT, SystemDiagnostic_t::FiveDigitalBIT, FIXEDHEIGHT_PVTYPE, FIXEDPOS_PVTYPE, ECU_t::Flags, AutopilotStatus_t::FlightTermination, AutopilotStatus_t::FlightTimerElapsed, UserData_t::Fuel, UserData_t::FuelFlow, ECU_t::FuelPress, ECUFlags_t::FuelPress_included, AutopilotStatus_t::GlobalOn, UserData_t::GPS, AvailableData_t::GPSResiduals, AutopilotStatus_t::GPSTimeout, SystemDiagnostic_t::GPSVoltageBIT, UserData_t::Gyro, NavDiagnostic_t::GyroBias, NavStatus_t::GyroBiasGood, MovingBaseStatus_t::Heading, NavStatus_t::HeadingGood, GPSUser_t::hours, ECU_t::IAT, ECUFlags_t::IAT_included, ECU_t::InjectAngle, ECUFlags_t::InjectAngle_included, ECU_t::InjectTime, ECUFlags_t::InjectTime_included, SystemDiagnostic_t::InputCurrent, SystemDiagnostic_t::InputVoltage, IONOFREE_FLOAT_PVTYPE, GPSUser_t::ITOW, L1_FLOAT_PVTYPE, L1_INTEGER_PVTYPE, MovingBaseStatus_t::Lag, LAT, GPSUser_t::Latitude, UserData_t::LeftRPM, ActionBits_t::Lights, LON, GPSUser_t::Longitude, AutopilotStatus_t::LoopStatus0, AutopilotStatus_t::LoopStatus1, AutopilotStatus_t::LoopStatus2, AutopilotStatus_t::LoopStatus3, AutopilotStatus_t::LoopStatus4, AutopilotStatus_t::LoopStatus5, AutopilotStatus_t::LoopStatus6, AutopilotStatus_t::LoopStatus7, AutopilotStatus_t::LoopTargets, NavStatus_t::MagBiasGood, UserData_t::MagField, NavStatus_t::MagGood, UserData_t::MagHeading, ECU_t::MAP, ECUFlags_t::MAP_included, GPSUser_t::minutes, NavStatus_t::Mode, ECUFlags_t::Mode, GPSUser_t::month, NARROW_FLOAT_PVTYPE, NARROW_INTEGER_PVTYPE, UserData_t::Nav, NavDiagnostic_t::NavStatus, NONE_PVTYPE, NORTH, NUM_ACTUATORS, NUM_EXTERNAL_ADC_PINS, UserData_t::OAT, OMNISTAR_HP_PVTYPE, OMNISTAR_VBS_PVTYPE, OMNISTAR_XP_PVTYPE, AutopilotStatus_t::Orbit, ActionBits_t::Parachute, AutopilotStatus_t::ParachutePendingRPM, GPSUser_t::PDOP, UserData_t::Pdynamic, AutopilotStatus_t::PilotPercentage, AutopilotStatus_t::PilotRate, PITCH_AXIS, NavStatus_t::PositionGood, UserData_t::PRes, PROPAGATED_PVTYPE, PSRDIFF_PVTYPE, UserData_t::Pstatic, UserData_t::RightRPM, ROLL_AXIS, SystemDiagnostic_t::RSSI, SBAS_PVTYPE, GPSUser_t::seconds, ECU_t::SerialNum, ECUFlags_t::SerialNumber_included, SystemDiagnostic_t::ServoCurrent, SystemDiagnostic_t::ServoVoltage, SINGLE_PVTYPE, MovingBaseStatus_t::SolnType, NavDiagnostic_t::Source, GPSUser_t::Speed, MovingBaseStatus_t::State, GPSUser_t::Status, UserData_t::System, UserData_t::SystemTime, MovingBaseStatus_t::SystemTime, UserData_t::TAS, NavStatus_t::TASGood, MovingBaseStatus_t::TDPos, ECU_t::TPS, ECUFlags_t::TPS_included, GPSUser_t::TrackedSats, AutopilotStatus_t::TrackerStatus, SystemDiagnostic_t::UplinkRatio, ActionBits_t::User, GPSUser_t::VDown, GPSUser_t::VEast, NavStatus_t::VelocityGood, GPSUser_t::VisibleSats, GPSUser_t::VNorth, ECU_t::Volts, UserData_t::VRes, AutopilotStatus_t::WaypointTo, GPSUser_t::Week, UserData_t::WeightOnWheel, NavStatus_t::WindGood, UserData_t::WindSouth, UserData_t::WindWest, X_AXIS, Y_AXIS, YAW_AXIS, GPSUser_t::year, and Z_AXIS.
Referenced by CCommManager::WriteTextLogLine().