Communications SDK: CommBaseGndStation.c File Reference
CommBaseGndStation.c File Reference
The CCT communication library base module, groundstation packet processing. This module provides functions to send and request groundstation-specific packets.
#include "CommBase.h"
Functions
void CommBase_SendGroundStationPacket (CommBase_t *pComm, const GroundStationPkt_t *pPkt)
Send an groundstation packet.
void CommBase_SendZeroLengthGroundStationPacket (CommBase_t *pComm, UInt8 PktType)
Send a zero length ground station packet.
void CommBase_SendGSAddAddressPacket (CommBase_t *pComm, UInt16 Address)
Create and send a ground station add address packet.
void CommBase_SendGSAddPilotAddressPacket (CommBase_t *pComm, UInt16 Address)
Create and send a ground station add pilot address packet.
void CommBase_SendGSDeleteAddressPacket (CommBase_t *pComm, UInt16 DelAddress, UInt16 KeepAddress)
Create and send a ground station delete address packet.
void CommBase_SendGSRadioSettingsPacket (CommBase_t *pComm, const RadioSettings_t *pSettings)
Create and a ground station radio settings packet.
void CommBase_SendDGPSBasePacket (CommBase_t *pComm, const DGPSParameter_t *pDGPS)
Create and send a ground station differential corrections packet.
void CommBase_SendGSDynamicEnumerationPacket (CommBase_t *pComm, BOOL On)
Create and send a dynamic enumeration on/off packet.
void CommBase_SendGSConfiguration (CommBase_t *pComm, UInt8 ConfigEnum, UInt8 SBASDisable, UInt8 EnableGD, UInt32 PayloadBaud, UInt8 EnableMHXRelay)
Create and send a ground station configuration packet.
void CommBase_RequestGSRadioSettingsPacket (CommBase_t *pComm)
Request ground station radio settings.
void CommBase_RequestGSCoherentSpectrumSweepPacket (CommBase_t *pComm, float StartFreq, float Spacing, UInt16 Dwell, UInt8 NumMeasurements)
Request ground station spectrum sweep, coherent frequency radio.
void CommBase_RequestGSHoppingSpectrumSweepPacket (CommBase_t *pComm)
Request ground station spectrum sweep, hopping radio.
void CommBase_RequestGSFirmwarePacket (CommBase_t *pComm)
Request the software and hardware configuration settings from the ground station.
void CommBase_RequestDGPSBasePacket (CommBase_t *pComm)
Request the packet with DGPS base settings.
Detailed Description
The CCT communication library base module, groundstation packet processing. This module provides functions to send and request groundstation-specific packets.
Function Documentation
void CommBase_RequestDGPSBasePacket (CommBase_t * pComm)
Request the packet with DGPS base settings.
Request the DGPS setup from the groundstation.
Parameters
pComm points to the communication interface data.
References CommBase_SendZeroLengthGroundStationPacket(), and DGPS_SETTINGS.
Referenced by CCommManager::RequestDGPSBasePacket().
void CommBase_RequestGSCoherentSpectrumSweepPacket (CommBase_t * pComm, float StartFreq, float Spacing, UInt16 Dwell, UInt8 NumMeasurements)
Request ground station spectrum sweep, coherent frequency radio.
Request ground station spectrum sweep. This puts the coherent frequency MHX radio in a scanning mode mesureing the signal strength at each user specified frequency. If the MXH radio in the groundstation is not coherent (i.e. it is hopping) then the user settings will not apply.
Parameters
pComm points to the communication interface data.
pPkt points to a stream packet to receive the formatted data.
StartFreq is the frequency to begin the sweep in MHz.
Spacing is the space between frequencies in MHz.
Dwell is the dwell time for each measurement in ms.
NumMeasurements is the number of measurements to make.
References CommBase_SendGroundStationPacket(), FormGSSpectrumSweepDetails(), GS_SPECTRUM2, and MakeGroundStationPacket().
Referenced by CCommManager::RequestGSSpectrumSweepPacket().
void CommBase_RequestGSFirmwarePacket (CommBase_t * pComm)
Request the software and hardware configuration settings from the ground station.
Request the software and hardware configuration settings from the ground station.
Parameters
pComm points to the communication interface data.
References CommBase_SendZeroLengthGroundStationPacket(), and GS_VERSION.
Referenced by CCommManager::RequestGSFirmwarePacket().
void CommBase_RequestGSHoppingSpectrumSweepPacket (CommBase_t * pComm)
Request ground station spectrum sweep, hopping radio.
Request a ground station spectrum sweep from a hopping MHX radio. If the MHX radio in the ground station is not hopping (i.e. it is coherent) then the swpecturm sweep will be performed with default user settings.
Parameters
pComm points to the communication interface data.
References CommBase_SendZeroLengthGroundStationPacket(), and GS_SPECTRUM.
Referenced by CCommManager::RequestGSSpectrumSweepPacket().
void CommBase_RequestGSRadioSettingsPacket (CommBase_t * pComm)
Request ground station radio settings.
Request the groundstation radio settings packet. The radio settings packet is used to control the channel and output power of the radio.
Parameters
pComm points to the communication interface data.
References CommBase_SendZeroLengthGroundStationPacket(), and GS_RADIO_SETTINGS.
Referenced by CCommManager::RequestGSRadioSettingsPacket().
void CommBase_SendDGPSBasePacket (CommBase_t * pComm, const DGPSParameter_t * pDGPS)
Create and send a ground station differential corrections packet.
Create and send a ground station differential corrections packet. The DGPS packet contains the information required to configure differential corrections.
Parameters
pComm points to the communication interface data.
pDGPS points to the base station information to be included in the packet.
References CommBase_SendGroundStationPacket(), and FormDGPSBasePacket().
Referenced by CCommManager::SendDGPSBasePacket().
void CommBase_SendGroundStationPacket (CommBase_t * pComm, const GroundStationPkt_t * pPkt)
Send an groundstation packet.
Send an groundstation packet
Parameters
pComm points to the communication interface data.
pPkt points to the groundstation packet to send.
References CommBase_SendBlock(), GS_ADDRESS, GS_PKT_OVERHEAD, GS_STREAM, and SimplePkt_t::Size.
Referenced by CommBase_RequestGSCoherentSpectrumSweepPacket(), CommBase_SendDGPSBasePacket(), CommBase_SendGSAddAddressPacket(), CommBase_SendGSAddPilotAddressPacket(), CommBase_SendGSConfiguration(), CommBase_SendGSDeleteAddressPacket(), CommBase_SendGSDynamicEnumerationPacket(), CommBase_SendGSRadioSettingsPacket(), CommBase_SendZeroLengthGroundStationPacket(), and CCommManager::SendGroundStationPacket().
void CommBase_SendGSAddAddressPacket (CommBase_t * pComm, UInt16 Address)
Create and send a ground station add address packet.
Create and send a ground station add address packet. This packet is used to add an autopilot address to the ground station polling list.
Parameters
pComm points to the communication interface data.
Address is the address to add. Valid addresses are 1 to 65533.
References ADD_ADDRESS, CommBase_SendGroundStationPacket(), SimplePkt_t::Data, and MakeGroundStationPacket().
Referenced by CCommManager::SendGSAddAddressPacket().
void CommBase_SendGSAddPilotAddressPacket (CommBase_t * pComm, UInt16 Address)
Create and send a ground station add pilot address packet.
Create and send a ground station pilot address packet. This packet is used to change the pilot address used by the ground station.
Parameters
pComm points to the communication interface data.
Address is the pilot address. Valid addresses are 1 to 65533.
References CommBase_SendGroundStationPacket(), SimplePkt_t::Data, MakeGroundStationPacket(), and PILOT_ADDRESS.
Referenced by CCommManager::SendGSAddPilotAddressPacket().
void CommBase_SendGSConfiguration (CommBase_t * pComm, UInt8 ConfigEnum, UInt8 SBASDisable, UInt8 EnableGD, UInt32 PayloadBaud, UInt8 EnableMHXRelay)
Create and send a ground station configuration packet.
Create and send a ground station configuration packet.
Parameters
pComm points to the communication interface data.
ConfigEnum is the ground station configuration enumeration, see GSConfigurations.
SBASDisable is the disable SBAS flag.
EnableGD is the enable guaranteed delivery flag.
PayloadBaud is the payload baud rate in bits per second.
EnableMHXRelay is the enable for microhard radio reflash relay.
References CommBase_SendGroundStationPacket(), and FormGroundStationConfigurationPacket().
Referenced by CCommManager::SendGSConfiguration().
void CommBase_SendGSDeleteAddressPacket (CommBase_t * pComm, UInt16 DelAddress, UInt16 KeepAddress)
Create and send a ground station delete address packet.
Create and send a ground station delete address packet. This packet is used to remove addresses from the polling list. The pilot address cannot be removed.
Parameters
pComm points to the communication interface data.
DelAddress is the address to remove. Pass zero to remove all addresses except the pilot address.
KeepAddress is the address to keep if removing all addresses. Pass zerp to remove all addresses excepting pilot.
References CommBase_SendGroundStationPacket(), SimplePkt_t::Data, DEL_ADDRESS, and MakeGroundStationPacket().
Referenced by CCommManager::SendGSDeleteAddressPacket().
void CommBase_SendGSDynamicEnumerationPacket (CommBase_t * pComm, BOOL On)
Create and send a dynamic enumeration on/off packet.
Create and send a ground station dynamic enumeration on/off packet. Dynamic enumeration is a feature of the ground station that allows it to discover any active autopilots that are on its same frequency and channel.
Parameters
pComm points to the communication interface data.
On should be TRUE to enable dynamic enumeration.
References CommBase_SendGroundStationPacket(), SimplePkt_t::Data, DYNAMIC_ENUMERATION, and MakeGroundStationPacket().
Referenced by CCommManager::SendGSDynamicEnumerationPacket().
void CommBase_SendGSRadioSettingsPacket (CommBase_t * pComm, const RadioSettings_t * pSettings)
Create and a ground station radio settings packet.
Create and send a ground station radio settings packet. The radio settings packet is used to control the channel and output power of the radio.
Parameters
pComm points to the communication interface data.
pSettings points to radio settings to be included in the packet.
References CommBase_SendGroundStationPacket(), and FormGSRadioSettingsPacket().
Referenced by CCommManager::SendGSRadioSettingsPacket().
void CommBase_SendZeroLengthGroundStationPacket (CommBase_t * pComm, UInt8 PktType)
Send a zero length ground station packet.
Send a zero length autopilot packet.
Parameters
pComm points to the communication interface data.
NetworkID is the destination network address.
PktType is the type of the autopillot packet.
References CommBase_SendGroundStationPacket(), and MakeGroundStationPacket().
Referenced by CommBase_RequestDGPSBasePacket(), CommBase_RequestGSFirmwarePacket(), CommBase_RequestGSHoppingSpectrumSweepPacket(), CommBase_RequestGSRadioSettingsPacket(), and CCommManager::SendZeroLengthGroundStationPacket().