Communications SDK: CommBaseGimbal.c File Reference
CommBaseGimbal.c File Reference
The CCT communication library base module, gimbal packet processing. This module provides functions to send and request gimbal-specific packets.
#include "CommBase.h"
#include "GimbalPacketUser.h"
Functions
void CommBase_SendGimbalPacket (CommBase_t *pComm, UInt16 NetworkID, const GimbalPkt_t *pPkt)
Send a gimbal packet on the gimbal stream to the autopilot.
void CommBase_RequestGimbalSPOICmdPacket (CommBase_t *pComm, UInt16 NetworkID)
Request a sensor point of interest command packet.
void CommBase_RequestGimbalCameraCmdPacket (CommBase_t *pComm, UInt16 NetworkID, UInt8 Camera)
Request a camera command packet.
void CommBase_RequestGimbalAxisSettingsPacket (CommBase_t *pComm, UInt16 NetworkID, BOOL Factory)
Request a gimbal axis settings packet.
void CommBase_RequestGimbalCameraAlignPacket (CommBase_t *pComm, UInt16 NetworkID, UInt8 Camera, BOOL Factory)
Request camera alignment information.
void CommBase_RequestGimbalCameraTypesPacket (CommBase_t *pComm, UInt16 NetworkID, BOOL Factory)
Request gimbal camera types.
void CommBase_RequestGimbalLaserSetupPacket (CommBase_t *pComm, UInt16 NetworkID, BOOL Factory)
Request gimbal laser setup.
void CommBase_SendGimbalCmdPacket (CommBase_t *pComm, UInt16 NetworkID, float Pan, float Tilt, SInt8 ZoomRate, float CamTimeout, UInt8 Flags, float ImpulseTime, SInt8 FocusRate, UInt8 Flags1)
Create and send a gimbal command packet containing pan, tilt, zoom and focus rate, and mode.
void CommBase_SendGimbalSPOICmdPacket (CommBase_t *pComm, UInt16 NetworkID, const double Pos[NPOS], const float Vel[NDIR], UInt8 Flags)
Create and send a gimbal sensor point of interest packet containing the position of the SPOI.
void CommBase_SendGimbalCameraCmdPacket (CommBase_t *pComm, UInt16 NetworkID, UInt8 Camera, float HFOV, UInt16 Focus, UInt8 Mode, UInt8 Shutter, UInt8 Bright, UInt8 Flags)
Create and send a camera command packet.
void CommBase_SendGimbalAxisSettingsPacket (CommBase_t *pComm, UInt16 NetworkID, const float NoGoCenter[NGIMBAL_SHORT], const float NoGoRange[NGIMBAL_SHORT], const float MaxRate[NGIMBAL_SHORT], const float MaxAccel[NGIMBAL_SHORT], const float PosGain[NGIMBAL_SHORT], const float VelGain[NGIMBAL_SHORT], const float DerGain[NGIMBAL_SHORT], BOOL Temporary, BOOL Factory)
Create and send a gimbal axis settings packet.
void CommBase_SendGimbalSerialInterfacePacket (CommBase_t *pComm, UInt16 NetworkID, GimbalSerial_t Serial[6], BOOL Temporary)
Create and send gimbal packet rate packet.
void CommBase_SendGimbalCameraAlignPacket (CommBase_t *pComm, UInt16 NetworkID, float Zoom1, const float Error1[NGIMBAL], float Zoom2, const float Error2[NGIMBAL], UInt8 Camera, BOOL Factory)
Create and send gimbal camera alignment packet.
void CommBase_SendGimbalCameraTypesPacket (CommBase_t *pComm, UInt16 NetworkID, const CameraDefinition_t Cam[NUM_CAMERAS], const BOOL Send[NUM_CAMERAS], BOOL Factory)
Create and send gimbal camera definitions packet.
void CommBase_SendGimbalLaserSetupPacket (CommBase_t *pComm, UInt16 NetworkID, LaserSetup_t Lasers[NUM_LASERS], BOOL Factory)
Create and send gimbal laser setup packet.
void CommBase_SendGimbalLaserArmPacket (CommBase_t *pComm, UInt16 NetworkID, UInt8 LaserIndex, BOOL Arm)
Create and send gimbal laser arm packet.
void CommBase_SendGimbalLaserFirePacket (CommBase_t *pComm, UInt16 NetworkID, UInt8 LaserIndex, UInt8 Power)
Create and send gimbal laser fire packet.
void CommBase_SendGimbalRetractDeployCmdPacket (CommBase_t *pComm, UInt16 NetworkID, UInt32 Deploy)
Create and send gimbal retract/deploy command.
void CommBase_SendGimbalTrackCmdPacket (CommBase_t *pComm, UInt16 NetworkID, float InitialX, float InitialY, UInt8 Algorithm, UInt8 Size, UInt8 Stamp)
Create and send gimbal track command packet.
Detailed Description
The CCT communication library base module, gimbal packet processing. This module provides functions to send and request gimbal-specific packets.
Function Documentation
void CommBase_RequestGimbalAxisSettingsPacket (CommBase_t * pComm, UInt16 NetworkID, BOOL Factory)
Request a gimbal axis settings packet.
Request a gimbal axis settings packet which contains the data to setup the axis control for custom configurations.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
Factory should be TRUE to request factory settings.
References AXIS_SETTINGS_GIMBAL_PKTTYPE, CommBase_SendGimbalPacket(), FACTORY_AXIS_SETTINGS_GIMBAL_PKTTYPE, GIMBAL_SETUP_GROUP, and MakeGimbalPacket().
Referenced by CCommManager::RequestGimbalAxisSettingsPacket().
void CommBase_RequestGimbalCameraAlignPacket (CommBase_t * pComm, UInt16 NetworkID, UInt8 Camera, BOOL Factory)
Request camera alignment information.
Request a gimbal camera alignment packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
Camera enumerates the camera to request alignment data for.
Factory should be TRUE to request factory settings
References CAMERA_ALIGN_GIMBAL_PKTTYPE, ChecksumGimbalPacket(), CommBase_SendGimbalPacket(), GimbalPkt_t::Data, FACTORY_CAMERA_ALIGN_GIMBAL_PKTTYPE, GIMBAL_SETUP_GROUP, and MakeGimbalPacketHeader().
Referenced by CCommManager::RequestGimbalCameraAlignPacket().
void CommBase_RequestGimbalCameraCmdPacket (CommBase_t * pComm, UInt16 NetworkID, UInt8 Camera)
Request a camera command packet.
Request a camera command packet containing the field of view, focus, and exposure settings.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
Camera identifies which camera to request data for.
References CAMERA_CMD_GIMBAL_PKTTYPE, ChecksumGimbalPacket(), CommBase_SendGimbalPacket(), GimbalPkt_t::Data, GIMBAL_COMMAND_AND_CONTROL_GROUP, and MakeGimbalPacketHeader().
Referenced by CCommManager::RequestGimbalCameraCmdPacket().
void CommBase_RequestGimbalCameraTypesPacket (CommBase_t * pComm, UInt16 NetworkID, BOOL Factory)
Request gimbal camera types.
Request gimbal camera types.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
Factory should be TRUE to request factory settings.
References CAMERA_DEFINITION_GIMBAL_PKTTYPE, CommBase_SendGimbalPacket(), FACTORY_CAMERA_DEFINITION_GIMBAL_PKTTYPE, GIMBAL_SETUP_GROUP, and MakeGimbalPacket().
Referenced by CCommManager::RequestGimbalCameraTypesPacket().
void CommBase_RequestGimbalLaserSetupPacket (CommBase_t * pComm, UInt16 NetworkID, BOOL Factory)
Request gimbal laser setup.
Request gimbal laser setup.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
Factory should be TRUE to request factory settings.
References CommBase_SendGimbalPacket(), FACTORY_LASERS_INSTALLED_GIMBAL_PKTTYPE, GIMBAL_SETUP_GROUP, LASERS_INSTALLED_GIMBAL_PKTTYPE, and MakeGimbalPacket().
Referenced by CCommManager::RequestGimbalLaserSetupPacket().
void CommBase_RequestGimbalSPOICmdPacket (CommBase_t * pComm, UInt16 NetworkID)
Request a sensor point of interest command packet.
Request a gimbal sensor point of interest (SPOI) cmd packet. The SPOI packet tells the gimbal where to point in LLA coordinates relative to the WGS-84 ellipsoid.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to request the packet from.
References CommBase_SendGimbalPacket(), GIMBAL_POSITION_INFORMATION_GROUP, MakeGimbalPacket(), and SPOI_CMD_GIMBAL_PKTTYPE.
Referenced by CCommManager::RequestGimbalSPOICmdPacket().
void CommBase_SendGimbalAxisSettingsPacket (CommBase_t * pComm, UInt16 NetworkID, const float NoGoCenter[NGIMBAL_SHORT], const float NoGoRange[NGIMBAL_SHORT], const float MaxRate[NGIMBAL_SHORT], const float MaxAccel[NGIMBAL_SHORT], const float PosGain[NGIMBAL_SHORT], const float VelGain[NGIMBAL_SHORT], const float DerGain[NGIMBAL_SHORT], BOOL Temporary, BOOL Factory)
Create and send a gimbal axis settings packet.
Create and send a gimbal axis settings packet which contains the data to setup the axis control for custom configurations.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
NoGoCenter is the center of the no go range in radians for all gimbal axis.
NoGoRange is the size of the no go range in radians for all gimbal axis. Zero is free-running. More than 2PI is do not change center or range.
MaxRate is the max rate in radians per second for all gimbal axis. Less than zero is do not change.
MaxAccel is the max accelerating in radians per second per second for all gimbal axis. Less than zero is do not change.
PosGain is the position gain in angle per second per angle error. Less than zero is do not change.
VelGain is the velocity feedforward gain, less than zero is do not change.
DerGain is the aceleration feedforward gain, less than zer is do not change.
Temporary should be 1 to prevent update to nonvolatile storage.
Factory should be TRUE to update factory parameters as well as main.
References CommBase_SendGimbalPacket(), and FormGimbalAxisSettingsPacket().
Referenced by CCommManager::SendGimbalAxisSettingsPacket().
void CommBase_SendGimbalCameraAlignPacket (CommBase_t * pComm, UInt16 NetworkID, float Zoom1, const float Error1[NGIMBAL], float Zoom2, const float Error2[NGIMBAL], UInt8 Camera, BOOL Factory)
Create and send gimbal camera alignment packet.
Create and send gimbal camera alignment packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Zoom1 is the zoom ration of the first alignment.
Error1 is the pan, tilt, and roll alignemnt errors at zoom1 [rad].
Zoom2 is the zoom ration of the second alignment.
Error1 is the pan, tilt, and roll alignemnt errors at zoom2 [rad].
Camera enumerates the camera that this data apply to.
Factory should be TRUE to udpate factory settings as well as main.
References CommBase_SendGimbalPacket(), and FormGimbalCameraAlignPacket().
Referenced by CCommManager::SendGimbalCameraAlignPacket().
void CommBase_SendGimbalCameraCmdPacket (CommBase_t * pComm, UInt16 NetworkID, UInt8 Camera, float HFOV, UInt16 Focus, UInt8 Mode, UInt8 Shutter, UInt8 Bright, UInt8 Flags)
Create and send a camera command packet.
Create and send a camera command packet containing the field of view, focus, and exposure settings.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Camera identifies the camera to control.
HFOV is the horizontal field of view in radians, or (if negative) the camera zoom ratio. 0.0 is do not change.
Focus is the focus length in millimeters, 0xFFFF is do not change, 0xFFFE is infinite, 0xFFFD is trigger, 0x0000 is auto.
EMode is the exposure mode: 0 for auto, 1 for shutter priority, 2 for bright mode. 0xFF is do not change
Shutter is the shutter speed. 0xFF is do not change
Bright is the bright mode setting, 0xFF is do not change.
Flags is the camera flag settings, set MSB for do not change.
References CommBase_SendGimbalPacket(), and FormGimbalCameraCmdPacket().
Referenced by CCommManager::SendGimbalCameraCmdPacket().
void CommBase_SendGimbalCameraTypesPacket (CommBase_t * pComm, UInt16 NetworkID, const CameraDefinition_t Cam[NUM_CAMERAS], const BOOL Send[NUM_CAMERAS], BOOL Factory)
Create and send gimbal camera definitions packet.
Create and send gimbal camera definitions packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Cam is the array of camera definitions to send.
Send is an array of boolean flags set to TRUE for the cameras we want to send.
Factory should be TRUE to update factory definitions as well as main.
References CommBase_SendGimbalPacket(), and FormCameraDefinitionsPacket().
Referenced by CCommManager::SendGimbalCameraTypesPacket().
void CommBase_SendGimbalCmdPacket (CommBase_t * pComm, UInt16 NetworkID, float Pan, float Tilt, SInt8 ZoomRate, float CamTimeout, UInt8 Flags, float ImpulseTime, SInt8 FocusRate, UInt8 Flags1)
Create and send a gimbal command packet containing pan, tilt, zoom and focus rate, and mode.
Create and send a gimbal cmd packet. The command packet contains the rate or position data for pan and tilt, the camera zoom rate data, as well as the operational mode of the gimbal.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Pan is the pan position (or rate) in radians (per second).
Tilt is the pan position (or rate) in radians (per second).
ZoomRate is the zoom rate from -8 to 8.
CamTimeout is the time to apply the zoom or focus, in seconds.
Flags describes how to interpret the data.
ImpulseTime is the time to apply to an impulse (seconds).
FocusRate is the focus rate from -8 to 8.
Flags1 provides additional details on how to interpret the data.
References CommBase_SendGimbalPacket(), and FormGimbalCmdPacket().
Referenced by CCommManager::SendGimbalCmdPacket().
void CommBase_SendGimbalLaserArmPacket (CommBase_t * pComm, UInt16 NetworkID, UInt8 LaserIndex, BOOL Arm)
Create and send gimbal laser arm packet.
Create and send gimbal laser arm packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
LaserIndex identifies the laser to arm.
Arm should be TRUE to arm the laser else it is disarmed.
References CommBase_SendGimbalPacket(), and FormGimbalLaserArmCmdPacket().
Referenced by CCommManager::SendGimbalLaserArmPacket().
void CommBase_SendGimbalLaserFirePacket (CommBase_t * pComm, UInt16 NetworkID, UInt8 LaserIndex, UInt8 Power)
Create and send gimbal laser fire packet.
Create and send gimbal laser fire packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
LaserIndex identifies the laser to arm.
Power is the laser power from 0 to 100 (percent)
References CommBase_SendGimbalPacket(), and FormGimbalLaserFireCmdPacket().
Referenced by CCommManager::SendGimbalLaserFirePacket().
void CommBase_SendGimbalLaserSetupPacket (CommBase_t * pComm, UInt16 NetworkID, LaserSetup_t Lasers[NUM_LASERS], BOOL Factory)
Create and send gimbal laser setup packet.
Create and send gimbal laser setup packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Lasers is the setup information to send.
Factory should be TRUE to update factory settings as well as main.
References CommBase_SendGimbalPacket(), and FormGimbalLasersInstalledPacket().
Referenced by CCommManager::SendGimbalLaserSetupPacket().
void CommBase_SendGimbalPacket (CommBase_t * pComm, UInt16 NetworkID, const GimbalPkt_t * pPkt)
Send a gimbal packet on the gimbal stream to the autopilot.
Send a gimbal packet on the gimbal stream to the autopilot.
Parameters
pComm points to the communication interface data.
NetworkID is the destination network address.
pPkt points to the gimbal packet to send.
References CommBase_SendBlock(), GIMBAL_STREAM, and GimbalPkt_t::Size.
Referenced by CommBase_RequestGimbalAxisSettingsPacket(), CommBase_RequestGimbalCameraAlignPacket(), CommBase_RequestGimbalCameraCmdPacket(), CommBase_RequestGimbalCameraTypesPacket(), CommBase_RequestGimbalLaserSetupPacket(), CommBase_RequestGimbalSPOICmdPacket(), CommBase_SendGimbalAxisSettingsPacket(), CommBase_SendGimbalCameraAlignPacket(), CommBase_SendGimbalCameraCmdPacket(), CommBase_SendGimbalCameraTypesPacket(), CommBase_SendGimbalCmdPacket(), CommBase_SendGimbalLaserArmPacket(), CommBase_SendGimbalLaserFirePacket(), CommBase_SendGimbalLaserSetupPacket(), CommBase_SendGimbalRetractDeployCmdPacket(), CommBase_SendGimbalSerialInterfacePacket(), CommBase_SendGimbalSPOICmdPacket(), CommBase_SendGimbalTrackCmdPacket(), and CCommManager::SendGimbalPacket().
void CommBase_SendGimbalRetractDeployCmdPacket (CommBase_t * pComm, UInt16 NetworkID, UInt32 Deploy)
Create and send gimbal retract/deploy command.
Create and send gimbal retract/deploy command.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Deploy is the command, 0 for retract, 1 for deploy, 2 for halt.
References CommBase_SendGimbalPacket(), and FormGimbalRetractDeployCmdPacket().
Referenced by CCommManager::SendGimbalRetractDeployCmdPacket().
void CommBase_SendGimbalSerialInterfacePacket (CommBase_t * pComm, UInt16 NetworkID, GimbalSerial_t Serial[6], BOOL Temporary)
Create and send gimbal packet rate packet.
Create and send a gimbal packet which sets the output rate for standard gimbal packets.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Serial contains the interface setup for the gimbal.
Temporary should be zero to make settings permanent.
References CommBase_SendGimbalPacket(), and FormGimbalSerialInterfacePacket().
Referenced by CCommManager::SendGimbalSerialInterfacePacket().
void CommBase_SendGimbalSPOICmdPacket (CommBase_t * pComm, UInt16 NetworkID, const double Pos[NPOS], const float Vel[NDIR], UInt8 Flags)
Create and send a gimbal sensor point of interest packet containing the position of the SPOI.
Create and send a gimbal sensor point of interest (SPOI) cmd packet. The SPOI packet tells the gimbal where to point in LLA coordinates relative to the WGS-84 ellipsoid.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
Pos is the position of the SPOI in Lat[rad], Lon[rad], Alt[m].
Vel is the velocity of the SPOI in North, East, Down [m/s].
Flags is the packet flags.
References CommBase_SendGimbalPacket(), and FormGimbalSPOICmdPacket().
Referenced by CCommManager::SendGimbalSPOICmdPacket().
void CommBase_SendGimbalTrackCmdPacket (CommBase_t * pComm, UInt16 NetworkID, float InitialX, float InitialY, UInt8 Algorithm, UInt8 Size, UInt8 Stamp)
Create and send gimbal track command packet.
Create and send the track command packet.
Parameters
pComm points to the communication interface data.
NetworkID is the address of the avionics to send the packet to.
InitialX is the initial horizontal track position in radians.
InitialY is the initial vertical track position in radians.
Algorithm is the algorithm choice enumeration.
Size is the size of the tracking window in pixels.
Stamp is the video counter stamp that goes with this track command, 255 if no stamp.
References CommBase_SendGimbalPacket(), and FormGimbalTrackCommand().
Referenced by CCommManager::SendGimbalTrackCmdPacket().