Communications SDK: CRC.h File Reference
CRC.h File Reference
ARC 16-bit cyclic redundancy check.
#include "Types.h"
Functions
UInt16 CRC16 (const UInt8 *pBuf, UInt32 len)
UInt16 CRC16OneByte (UInt8 Byte, UInt16 crc)
Variables
const UInt16 crctable [256]
Detailed Description
ARC 16-bit cyclic redundancy check.
ARC 16-bit cyclic redundancy check for blocks of 8-bit data of arbitrary length. Note that this is a reflected CRC on both the input bytes and output. Useful CRC websites: http://www.ross.net/crc/download/crc_v3.txt and http://reveng.sourceforge.net/crc-catalogue/all.htm. The check value is based upon the following ASCII 9 bytes input: "123456789"
Parameters: width=16 poly=0x8005 init=0x0000 refin=true refout=true xorout=0x0000 check=0xbb3d name="ARC"
Alias: CRC-16, CRC-IBM, CRC-16/ARC, CRC-16/LHA
Function Documentation
UInt16 CRC16 (const UInt8 * pBuf, UInt32 len)
Calculates a 16-bit cyclic redundancy check on blocks of 8-bit data of arbitrary length.
Parameters
pBuf points to a buffer of data.
len is the size of the buffer in bytes.
Returns
The 16-bit crc of the buffer.
Referenced by CRCPacket(), LookForCANPacket(), LookForCANPacketInByte(), LookForSimplePacket(), LookForStreamPacketInByte(), MakeCANPacket(), and MakeSimplePacket().
UInt16 CRC16OneByte (UInt8 Byte, UInt16 crc)
Calculate the new 16-bit cyclic redundancy check that results from adding a byte to an existing crc.
Parameters
Byte is the new byte.
crc is the existing crc value.
Returns
The new crc value