Communications SDK: FlightPlan.h File Reference
FlightPlan.h File Reference
Flight plan manipulation.
#include "PiccoloDefinitions.h"
Typedefs
typedef FPPoint_t FPlan_t[NUM_FP_POINTS]
Functions
BOOL IsFPPointValid (const FPPoint_t *pFPPoint)
Return TRUE if the flight plan point is valid.
UInt16 GetPointsInPlan (const FPlan_t Plan, FPMask_t Mask, UInt16 Next)
Get all the points in the closed flight plan.
UInt16 NumPointsInFPMask (const FPMask_t Mask)
Add up all the points in this fligth plan mask.
void ClearPointsFromPlan (FPlan_t Plan, FPMask_t Mask)
Clear points from the flight plan.
BOOL CheckFlightPlanClosure (FPlan_t Plan, UInt16 Start)
Check closure rules for a flight plan.
BOOL CheckFlightPlanClosureEx (FPlan_t Plan, UInt16 Start, float Radius, BOOL Right)
Check closure rules for a flight plan and auto-close if needed.
SInt32 FindFirstFPMaskBitSet (const FPMask_t Mask)
Find the first set bit in the flight plan mask.
SInt32 FindNextFPMaskBitSet (const FPMask_t Mask, UInt32 i)
Find the next set bit in the flight plan mask.
SInt32 FindFirstFPMaskBitSetAndClear (FPMask_t Mask)
Find the first set bit in the flight plan mask.
SInt32 FindNextFPMaskBitSetAndClear (FPMask_t Mask, UInt32 i)
Find the next set bit in the flight plan mask.
void SetFPMaskBit (FPMask_t Mask, UInt32 Point)
Set a bit in the flight plan mask.
void ClearFPMaskBit (FPMask_t Mask, UInt32 Point)
Clear a bit in the flight plan mask.
BOOL GetFPMaskBit (const FPMask_t Mask, UInt32 Point)
Get the status for a bit in the flight plan mask.
void ClearAllFPMaskBits (FPMask_t Mask)
Clear all bits in the flight plan mask.
void SetAllFPMaskBits (FPMask_t Mask)
Set all bits in the flight plan mask.
void InvertAllFPMaskBits (FPMask_t Mask)
Invert all bits in the flight plan mask.
void InvertAllFPmaskBits_Ex (FPMask_t Dest, const FPMask_t Source)
Invert all bits in the flight plan mask.
void FPMaskOR (FPMask_t Mask1, const FPMask_t Mask2)
OR all bits in two flight plan masks.
void FPMaskOR_Ex (FPMask_t Return, const FPMask_t Mask1, const FPMask_t Mask2)
OR all bits in two flight plan masks.
void FPMaskAND (FPMask_t Mask1, const FPMask_t Mask2)
AND all bits in two flight plan masks.
void FPMaskAND_Ex (FPMask_t Return, const FPMask_t Mask1, const FPMask_t Mask2)
AND all bits in two flight plan masks.
void FPMaskSubtract (FPMask_t Return, const FPMask_t Mask1, const FPMask_t Mask2)
Subtract two flight plan masks to find the difference.
SInt32 CompareFPMask (const FPMask_t First, const FPMask_t Second)
Compare two flight plan masks.
void CopyFPMask (const FPMask_t Source, FPMask_t Destination)
Copy a flight plan mask.
BOOL IsFPMaskClear (const FPMask_t Mask)
Determine if the mas is clear.
Detailed Description
Flight plan manipulation.
The flight plan module provides definitions and routines for working on flight plans. Flight plans are made of linked lists of waypoints. Each waypoint encodes latitude, longitude, altitude, and the index of the next waypoint to be used. The avionics has storage for 1000 waypoints. These waypoints can be used to make one flight plan which is 1000 waypoints long, or 1000 flight plans with one waypoint each, or any combination between. The key concept is that all flight plans must close. This means that at some point the next waypoint must point to a waypoint which was previously in the list, or must point to itself and be an indefinite orbit.
Since an entire flight plan might occupy up to 1000 waypoints, with each taking approximately 16 bytes of data, a whole flight plan cannot fit into a single autopilot packet. Hence information about waypoints is often sent in compressed lists, called masks, which have 1 bit for each waypoint. The flight plan module has functions for working with these masks.
Function Documentation
BOOL CheckFlightPlanClosure (FPlan_t Plan, UInt16 Start)
Check closure rules for a flight plan.
Verify the flight plan closes and all points are valid.
Parameters
Plan is an array of waypoints NUM_FP_POINTS long.
Start is an index of a waypoit in the flight plan.
Returns
TRUE if the plan closes, else FALSE.
References CheckFlightPlanClosureEx().
BOOL CheckFlightPlanClosureEx (FPlan_t Plan, UInt16 Start, float Radius, BOOL Right)
Check closure rules for a flight plan and auto-close if needed.
Verify the flight plan closes and all points are valid. Optionally close the plan with a self-referencing orbit
Parameters
Plan is an array of waypoints NUM_FP_POINTS long.
Start is an index of a waypoit in the flight plan.
Radius is the orbit of the last waypoint if the plan needs to be be closed by this function. Must be greater than 1 to auto-close the plan
Right should be TRUE to make the self close point orbit to the right.
Returns
TRUE if the plan closes, else FALSE.
References ClearAllFPMaskBits(), GetFPMaskBit(), FPPoint_t::Hover, NUM_FP_POINTS, FPPoint_t::OrbitAboveAlt, FPPoint_t::OrbitBelowAlt, FPPoint_t::OrbitRadius, FPPoint_t::OrbitTime, and SetFPMaskBit().
Referenced by CheckFlightPlanClosure().
void ClearAllFPMaskBits (FPMask_t Mask)
Clear all bits in the flight plan mask.
Clear all the bits in the passed flight plan mask.
Parameters
Mask to be cleared.
Referenced by CheckFlightPlanClosureEx(), DecodeWaypointListPacket(), and GetPointsInPlan().
void ClearFPMaskBit (FPMask_t Mask, UInt32 Point)
Clear a bit in the flight plan mask.
Clear the bit in the mask corresponding to the passed waypoint index.
Parameters
Mask contains a bit for each waypoint to be cleared.
Point is the index of the bit to clear.
References FP_MASK_BYTES.
Referenced by InvertAllFPMaskBits(), InvertAllFPmaskBits_Ex(), and SetAllFPMaskBits().
void ClearPointsFromPlan (FPlan_t Plan, FPMask_t Mask)
Clear points from the flight plan.
Clear the requested waypoints from the flight plan array. For every bit set in the Mask the corresponding waypoint is cleared from the passed array.
Parameters
Plan is an array of waypoints.
Mask contains a bit for each waypoint to be cleared.
References FindFirstFPMaskBitSet(), and FindNextFPMaskBitSet().
SInt32 CompareFPMask (const FPMask_t First, const FPMask_t Second)
Compare two flight plan masks.
Compare two flight plan masks.
Parameters
First is the first mask to compare.
Second is the second mask to compare.
Returns
0 if the masks are identical. If the first mask is a superset of the second (i.e. all bits in the second are also set in the first) 1 is returned. Else -1 is returned.
References FP_MASK_BYTES.
void CopyFPMask (const FPMask_t Source, FPMask_t Destination)
Copy a flight plan mask.
Copy the flight plan mask from the source to the destination.
Parameters
Source is the source mask.
Destination is the destination mask.
References FP_MASK_BYTES.
SInt32 FindFirstFPMaskBitSet (const FPMask_t Mask)
Find the first set bit in the flight plan mask.
Search throught the flight plan mask, starting at index 0, looking for the first set bit.
Parameters
Mask to be searched.
Returns
The index of the first bit which is set. If no bits are set the return value is -1.
References FindNextFPMaskBitSet().
Referenced by ClearPointsFromPlan().
SInt32 FindFirstFPMaskBitSetAndClear (FPMask_t Mask)
Find the first set bit in the flight plan mask.
Search throught the flight plan mask, starting at index 0, looking for the first set bit. Clear the bit from the mask
Parameters
Mask to be searched.
Returns
The index of the first bit which is set. If no bits are set the return value is -1.
References FindNextFPMaskBitSetAndClear().
SInt32 FindNextFPMaskBitSet (const FPMask_t Mask, UInt32 Index)
Find the next set bit in the flight plan mask.
Search throught the flight plan mask, starting at one past the passed index, looking for the first set bit.
Parameters
Mask to be searched.
The last index searched. This function will search after that index.
Returns
The index of the lowest bit following Index which is set. If no bits are set the return value is -1.
References FP_MASK_BYTES, and NUM_FP_POINTS.
Referenced by ClearPointsFromPlan(), and FindFirstFPMaskBitSet().
SInt32 FindNextFPMaskBitSetAndClear (FPMask_t Mask, UInt32 Index)
Find the next set bit in the flight plan mask.
Search throught the flight plan mask, starting at one past the passed index, looking for the first set bit. Clear the bit from the mask
Parameters
Mask to be searched.
The last index searched. This function will search after that index.
Returns
The index of the lowest bit following Index which is set. If no bits are set the return value is -1.
References FP_MASK_BYTES, and NUM_FP_POINTS.
Referenced by FindFirstFPMaskBitSetAndClear().
void FPMaskAND (FPMask_t Mask1, const FPMask_t Mask2)
AND all bits in two flight plan masks.
Bitwise AND all of the bits of the two flight plan masks. The new mask is return in Mask1
Parameters
Mask1 is the first of the source masks, and also the return mask
Mask2 is the second of the sANDuce masks, it will be unchanged.
References FP_MASK_BYTES.
void FPMaskAND_Ex (FPMask_t Return, const FPMask_t Mask1, const FPMask_t Mask2)
AND all bits in two flight plan masks.
Bitwise AND all of the bits of the two flight plan masks. The source masks are not changed.
Parameters
Return is the mask that contains the new data.
Mask1 is the first of the source masks.
Mask2 is the second of the sANDuce masks.
References FP_MASK_BYTES.
Referenced by FPMaskSubtract().
void FPMaskOR (FPMask_t Mask1, const FPMask_t Mask2)
OR all bits in two flight plan masks.
Bitwise OR all of the bits of the two flight plan masks. The new mask is return in Mask1
Parameters
Mask1 is the first of the source masks, and also the return mask
Mask2 is the second of the soruce masks, it will be unchanged.
References FP_MASK_BYTES.
void FPMaskOR_Ex (FPMask_t Return, const FPMask_t Mask1, const FPMask_t Mask2)
OR all bits in two flight plan masks.
Bitwise OR all of the bits of the two flight plan masks. The source masks are not changed.
Parameters
Return is the mask that contains the new data.
Mask1 is the first of the source masks.
Mask2 is the second of the soruce masks.
References FP_MASK_BYTES.
void FPMaskSubtract (FPMask_t Return, const FPMask_t Mask1, const FPMask_t Mask2)
Subtract two flight plan masks to find the difference.
Bitwise subtraction of all of the bits of the two flight plan masks. The subtraction is done as Mask1 - Mask2. The source masks are not changed.
Parameters
Return is the mask that contains the new data.
Mask1 is the first of the source masks.
Mask2 is the second of the source masks.
References FPMaskAND_Ex(), and InvertAllFPmaskBits_Ex().
BOOL GetFPMaskBit (const FPMask_t Mask, UInt32 Point)
Get the status for a bit in the flight plan mask.
Return the status of the requested bit in the flight plan mask.
Parameters
Mask is a flight plan mask containing status bits.
Point is the index of the bit whose status will be returned.
Returns
TRUE if the bit is set, else FALSE.
References NUM_FP_POINTS.
Referenced by CheckFlightPlanClosureEx(), and GetPointsInPlan().
UInt16 GetPointsInPlan (const FPlan_t Plan, FPMask_t Mask, UInt16 Point)
Get all the points in the closed flight plan.
Get all the points that are on the flight plan which includes the Next waypoint and return them as bits in a mask. This function will find all the points which link to this one, no matter their arrangement
Parameters
Plan points to a flight plan array.
Mask is the bit mask to receive a bit for each point.
Point is the index of the seed waypoint to start the search.
Returns
The total number of points found.
References ClearAllFPMaskBits(), GetFPMaskBit(), NUM_FP_POINTS, and SetFPMaskBit().
void InvertAllFPMaskBits (FPMask_t Mask)
Invert all bits in the flight plan mask.
Invert all bits in the flight plan mask. Any bits which were set will be clear, and any bits which were clear will be set.
Parameters
Mask to be inverted.
References ClearFPMaskBit(), EXTRA_FP_MASK_BITS, FP_MASK_BYTES, and NUM_FP_POINTS.
void InvertAllFPmaskBits_Ex (FPMask_t Dest, const FPMask_t Source)
Invert all bits in the flight plan mask.
Fill out the destination flight plan mask by inverting all bits in the source flight plan mask. Any bits which were set will be clear, and any bits which were clear will be set.
Parameters
Dest is the new mask with inverted bits.
Source is the source data that will remain unchanged.
References ClearFPMaskBit(), EXTRA_FP_MASK_BITS, FP_MASK_BYTES, and NUM_FP_POINTS.
Referenced by FPMaskSubtract().
BOOL IsFPMaskClear (const FPMask_t Mask)
Determine if the mas is clear.
Determine if the flight plan mask is empty of points
Parameters
Mask is the flight plan mask to search.
Returns
TRUE if the mask is clear
References FP_MASK_BYTES.
BOOL IsFPPointValid (const FPPoint_t * pFPPoint)
Return TRUE if the flight plan point is valid.
Determine if the passed flight plan point is valid. This is based upon the index of the next waypoint.
Parameters
pFPPoint points to the flight plan point to evaluate. TRUE if the point is valid, else FALSE.
References FPPoint_t::Next, and NUM_FP_POINTS.
UInt16 NumPointsInFPMask (const FPMask_t Mask)
Add up all the points in this fligth plan mask.
Return the number of points in a flight plan mask.
Parameters
Mask is the flight plan mask to search.
Returns
The number points set in the mask.
References FP_MASK_WORDS.
void SetAllFPMaskBits (FPMask_t Mask)
Set all bits in the flight plan mask.
Set all the bits in the passed flight plan mask.
Parameters
Mask to be set.
References ClearFPMaskBit(), EXTRA_FP_MASK_BITS, and NUM_FP_POINTS.
void SetFPMaskBit (FPMask_t Mask, UInt32 Point)
Set a bit in the flight plan mask.
Set the bit in the mask corresponding to the passed waypoint index.
Parameters
Mask contains a bit for each waypoint to be cleared.
Point is the index of the bit to set.
References NUM_FP_POINTS.
Referenced by CheckFlightPlanClosureEx(), DecodeWaypointListPacket(), and GetPointsInPlan().