Communications SDK: GimbalPacketGeneric.h File Reference
GimbalPacketGeneric.h File Reference
Gimbal packet encode and decode functionality.
#include "Types.h"
#include "Indices.h"
#include "Definitions.h"
Classes
struct GimbalPkt_t
struct CameraDefinition_1_t
OLD - Camera definition structure.
struct CameraDefinition_t
Camera definition structure.
struct LaserSetup_t
struct LaserStatus_t
Laser status information.
struct GimbalSerial_t
struct GimbalSensorFlags_t
Gimbal sensor configuration bit flags.
struct GimbalTelemetryFlags_t
Flags that go along with gimbal telemetry data.
struct GimbalTelemetryData_t
Primary data set from the gimbal.
struct VGSTelemetryData_t
Telemetry information from the video ground station.
struct KLVDetails_t
struct FLIRConfig_t
struct IRCamFlags_t
struct IRCamConfig_t
struct SuCsxCamFlags_t
struct SuCsxCamConfig_t
struct SonyXCLConfig_t
struct MISBConfig_t
struct GimbalScanControlConfig_t
struct GimbalDiagnosticsFlags_t
Flags that go along with gimbal diagnostic data.
struct GimbalDiagnostics_t
Gimbal diagnostic data.
struct Vps3Diagnostics_t
T500 VPS diagnostic data.
struct MotionCtrlDiagnostics_t
T500 motion control diagnostic data.
struct MicroblazeDiagnostics_t
T500 Microblaze diagnostic data.
struct VideoTrackDiagnostics_t
Video track control diagnostics.
struct Retractor_t
Retractor configuration data.
struct LensCtrlType_t
Lens controller type.
struct LensDiagnostics_t
Lens diagnostic information.
struct CameraData_t
Camera data.
struct VPS3SymbolFlags_t
VPS3 symbology flags.
struct VPS3Symbology_t
VPS3 symbology settings.
Macros
#define MAX_GIMBAL_PACKET_DATA_SIZE 253
#define MAX_CUSTOM_STR_LEN 80
#define LASER_WD_TIMEOUT 300
#define LASER_REMINDER_TIMEOUT 270
#define LASER_TIMEOUT_INDEFINITE 0xFFFFFFFFFFFFFFF
#define CSX_MSG_MAX_CHAR 32
#define MAX_SPOI_PATH_PTS 39
Max number of points that can be stored in RAM.
Gimbal group identifiers
#define GIMBAL_COMMAND_AND_CONTROL_GROUP 0x00
Group number for all gimbal command and control packets.
#define GIMBAL_DYNAMICS_INFORMATION_GROUP 0x08
Group number for all dynamics packets (rates, attitudes)
#define GIMBAL_POSITION_INFORMATION_GROUP 0x10
Group number for all position packets (GPS, SPOI)
#define GIMBAL_STATUS_INFORMATION_GROUP 0x28
Group number for status packets.
#define GIMBAL_SETUP_GROUP 0x48
Group number for setup packets.
#define GIMBAL_DEVELOPMENT_GROUP 0xE8
Group number for development packets.
#define INTER_PROCESSOR_GROUP 0xE0
Group number for packets between processor in the gimbal.
#define VGS_COMMAND_AND_CONTROL_GROUP 0xF0
Group number for video ground station packets.
#define VPS_PROGRAMMING_GROUP 0xFD
Group number for VPS programming packets.
#define VPS_GROUP_DEPRECATED 0xFE
Group number for VPS work - deprecated in 2.2.3.
#define VPS_DEVELOPMENT_GROUP 0xFF
Group number for VPS development work (flash programming)
#define MICROBLAZE_DEVELOPMENT_GROUP 0xF7
Group number for Microblaze development work.
#define MICROBLAZE_PROGRAMMING_GROUP 0xF8
Group number for Microblaze flash programming.
#define MC_PROGRAMMING_AND_DEV_GROUP 0xF9
Group number for Motion Control programming and dev packets.
Command and control group packet types
#define GYRO_ZERO_CMD_GIMBAL_PKTTYPE 0x40
Packet type for gyro zero command.
#define CAMERA_CMD_GIMBAL_PKTTYPE 0x41
Packet type for camera control.
#define CAMERA_PASS_THROUGH_GIMBAL_PKTTYPE 0x42
Camera pass through packet type.
#define RETRACT_DEPLOY_CMD_GIMBAL_PKTTYPE 0x43
Command retract or deploy of 3AX.
#define LASER_ARM_CMD_GIMBAL_PKTTYPE 0x44
Command to arm a laser.
#define LASER_FIRE_CMD_GIMBAL_PKTTYPE 0x45
Command to fire a laser.
#define SPOI_PATH_CMD_PKTTYPE 0x46
Command SPOI path following.
#define SPOI_PATH_NEAREST_CMD_PKTTYPE 0x47
Command SPOI to nearest point on the current path.
#define CAMERA_ZOOM_GIMBAL_PKTTYPE 0x48
Continuous camera zoom command.
#define LASER_SAFETY_STATUS_PKTTYPE 0x49
Laser safety and safety status.
#define FFC_CMD_GIMBAL_PKTTYPE 0x4A
Command to perform FFC.
#define LASER_WATCHDOG_PKTTYPE 0x4B
Laser watchdog reminder to user.
#define LASER_PASSWORD_ENABLER_PKTTYPE 0x4C
Overall Laser ops enabler - pswd is the S/N of the gimbal.
#define TRACKER_CMD_GIMBAL_PKTTYPE 0x50
Command to control the video tracker.
#define SYMBOLOGY_CMD_GIMBAL_PKTTYPE 0x51
Command to control the video symbology.
#define ENHANCEMENT_CMD_GIMBAL_PKTTYPE 0x52
Command to control image enhancement (deprecated)
#define RADIO_SETUP_GIMBAL_PKTTYPE 0x60
Command to control the radio setup.
#define MOTOR_DRIVE_ENABLE_GIMBAL_PKTTYPE 0x70
Command to enable/disable the motor drive.
#define DO_MOTION_CALIBRATION 0x71
Command the gimbal to do a motio.
#define GIMBAL_CMD_GIMBAL_PKTTYPE 0x80
Packet type for basic gimbal commands.
#define LEGACY_CAMERA_CMD_GIMBAL_PKTTYPE 0x81
Legacy camera command packet type.
#define GIMBAL_AGL_PKTTYPE 0x82
Letting the Gimbal know what its Altitude AGL is.
#define GIMBAL_SCAN_CONTROL_PKTTYPE 0x83
Command and configure gimbal scan mode.
#define RIG_TEST_CMD_GIMBAL_PKTTYPE 0xFE
Rig test command.
Dynamics information group packet types
#define GIMBAL_ANGLE_GIMBAL_PKTTYPE 0x10
Packet type for gimbal angle data.
#define GIMBAL_RATE_GIMBAL_PKTTYPE 0x40
Packet type for gimbal angle and mount rate data.
#define HOST_SENSOR_GIMBAL_PKTTYPE 0x41
Packet type for host supplied gimbal mount body rates.
#define HOST_ATTITUDE_GIMBAL_PKTTYPE 0x42
Packet type for host supplied gimbal mount attitude data.
#define VIBRATION_DATA_GIMBAL_PKTTYPE 0x80
Packet type for vibration data from gimbal.
#define INITIAL_HEADING_GIMBAL_PKTTYPE 0x90
Packet type for initializaing INS heading.
#define TRACKING_DATA_GIMBAL_PKTTYPE 0xA0
Packet type for tracking data to an autopilot.
#define FRAME_SHIFTS_GIMBAL_PKTTYPE 0xB0
Packet type for receiving image frame shifts from VPS or Tracker.
Position information group packet types
#define HOST_GPS_DATA_GIMBAL_PKTTYPE 0x10
Packet type for host supplied GPS data.
#define SPOI_CMD_GIMBAL_PKTTYPE 0x40
Packet type for sensor point of interest command.
#define GEOREFERENCE_DATA_GIMBAL_PKTTYPE 0x41
Packet type for the geo referencing meta data, deprecated.
#define TARGET_LOCATION_DATA_GIMBAL_PKTTYPE 0x42
Target location (from gimbal)
#define TARGET_LOCATION_ESTIMATE_GIMBAL_PKTTYPE 0x43
Estimate of target location (to gimbal)
#define SPOI_PATH_POINT_DATA_PKTTYPE 0x45
SPOI path points data.
#define GIMBAL_TELEMETRY_GIMBAL_PKTTYPE 0x47
Gimbal telemetry packet type.
#define GIMBAL_TELEMETRY_2_GIMBAL_PKTTYPE 0x48
Expanded gimbal telemetry packet as of 230.
Status group packet types
#define USER_WARNING_GIMBAL_PKTTYPE 0x00
Packet type for sending a human readable warning message.
#define RESET_REPORT_GIMBAL_PKTTYPE 0x01
Packet type for sending a gimbal reset report.
#define DIAGNOSTIC_GIMBAL_PKTTYPE 0x02
Packet type for sending diagnostic information from the gimbal.
#define MICROBLAZE_WARN_USER 0x10
Packet type for sending a human readable warning message from the MB.
#define MICROBLAZE_RESET_REPORT 0x11
Packet type for sending a MB reset report.
#define MICROBLAZE_DIAGNOSTIC_PKTTYPE 0x12
Packet type for sending a MB Diagnostics packet.
#define VPS_USER_WARNING_PKTTYPE 0x20
Packet type for sending a human readable warning message from the VPS.
#define VPS_RESET_REPORT_PKTTYPE 0x21
Packet type for sending a vps reset report.
#define VPS_DIAGNOSTIC_PKTTYPE 0x22
Packet type for sending a VPS Diagnostics packet.
#define MC_DIAGNOSTIC_PKTTYPE 0x32
Packet type for sending a Motion Control Diagnostics packet.
Setup group packet types
#define SERIAL_INTERFACE_GIMBAL_PKTTYPE 0x00
Packet type for changing serial interface setup.
#define SENSOR_FILTER_GIMBAL_PKTTYPE 0x01
Packet type for changing sensor filter settings.
#define AXIS_SETTINGS_GIMBAL_PKTTYPE 0x02
Packet type for changing axis settings.
#define SYSTEM_VERSION_GIMBAL_PKTTYPE 0x03
Packet type for system version information (deprecated in 230)
#define SYSTEM_VERSION_2_GIMBAL_PKTTYPE 0x04
Packet type for newer system version information.
#define CAMERA_DEFINITION_GIMBAL_PKTTYPE 0x05
Packet type for camera definitions.
#define GPS_LEVER_ARM_GIMBAL_PKTTYPE 0x06
Packet type for GPS lever arm.
#define CAMERA_ALIGN_GIMBAL_PKTTYPE 0x07
Packet type for camera alignment.
#define LASERS_INSTALLED_GIMBAL_PKTTYPE 0x08
Packet type for setup/query of installed lasers.
#define TRACKER_ADV_CMD_GIMBAL_PKTTYPE 0x09
Packet type for setup of tracker (advanced settings)
#define SPOI_PATH_PARAM_PKTTYPE 0x0A
Packet type for configuring the SPOI Path Navigator.
#define EXTERNAL_STABILIZER_GIMBAL_PKTTYPE 0x0B
Packet type for setup of external stabilizer.
#define MAG_CAL_GIMBAL_PKTTYPE 0x0C
Packet type for magnetometer calibration data.
#define FACTORY_AXIS_SETTINGS_GIMBAL_PKTTYPE 0x0D
Packet type for changing factory axis settings.
#define FACTORY_CAMERA_DEFINITION_GIMBAL_PKTTYPE 0x0E
Packet type for factory camera definitions.
#define FACTORY_CAMERA_ALIGN_GIMBAL_PKTTYPE 0x0F
Packet type for factory camera alignment.
#define FACTORY_LASERS_INSTALLED_GIMBAL_PKTTYPE 0x10
Packet type for setup/query of factory installed lasers.
#define SENSOR_CONFIGURATION_GIMBAL_PKTTYPE 0x11
Packet type for sensor configuration data.
#define KLV_DETAILS_GIMBAL_PKTTYPE 0x12
Packet type for configuration KLV data.
#define FLIR_CONFIGURATION_GIMBAL_PKTTYPE 0x13
Packet type for configuring the FLIR camera.
#define FLIR_SAVE_CONFIGURATION_GIMBAL_PKTTYPE 0x14
Packet type for saving FLIR camera configuration as startup settings.
#define FLIR_DEFAULT_CONFIGURATION_GIMBAL_PKTTYPE 0x15
Packet type for commanding FLIR camera to default configuration.
#define LENS_PREFOCUS_CONFIGURATION 0x16
Packet type for setup/query of lens pre-focus data.
#define FACTORY_EXTERNAL_STABILIZER_GIMBAL_PKTTYPE 0x17
Packet for sending/querying factory stabilizer board settings.
#define EXTERNAL_STABILIZER_VERSION_GIMBAL_PKTTYPE 0x18
Packet for stabilizer board version info.
#define LENS_CONTROL_VERSION_PKTTYPE 0x19
Packet type for the lens controller version information.
#define CAN_PASSTHROUGH_GIMBAL_PKTTYPE 0x20
Packet type for setup/query of CANbus passthrough IDs.
#define RETRACTOR_CONFIG_GIMBAL_PKTTYPE 0x21
Packet type for setup/query of retractor configuration.
#define IRCAM_CONFIGURATION_GIMBAL_PKTTYPE 0x22
Packet type for configuring a T500 IR camera.
#define IRCAM_SAVE_RESTORE_GIMBAL_PKTTYPE 0x23
Packet type for saving/restoring the T500 IR startup configuration.
#define FACTORY_TRACKER_ADV_CMD_GIMBAL_PKTTYPE 0x24
Packet type for factory advanced tracker settings.
#define SUCSX_CONFIGURATION_GIMBAL_PKTTYPE 0x25
Packet type for configuring a SU CSX Camera.
#define SUCSX_SAVE_RESTORE_GIMBAL_PKTTYPE 0x26
Packet type for saving/restoring the SU CSX camera startup configuration.
#define LENS_CAL_ZOOM_CONFIGURATION 0x27
Packet type for setup/query of lens cal table zoom positions.
#define LENS_CAL_FOCUS_CONFIGURATION 0x28
Packet type for setup/query of lens cal table temperature and focus positions.
#define VPS3_VERSION_PKTTYPE 0x40
Packet type for the VPS3 version information.
#define HD_CONTROL_SETTINGS_PKTTYPE 0x41
Packet type for the HD control modes of the VPS.
#define OVERLAY_SETTINGS_PKTTYPE 0x42
Packet type for the overlay settings.
#define PICTURE_IN_PICTURE_SETTINGS_PKTTYPE 0x43
Packet type for the picture in picture settings.
#define ELECTRONIC_STAB_SETTINGS_PKTTYPE 0x44
Packet type for the electronic stabilization settings.
#define FACTORY_HD_CONTROL_SETTINGS_PKTTYPE 0x4A
Packet type for the factory HD control modes of the VPS.
#define FACTORY_OVERLAY_SETTINGS_PKTTYPE 0x4B
Packet type for the factory overlay settings.
#define FACTORY_PICTURE_IN_PICTURE_SETTINGS_PKTTYPE 0x4C
Packet type for the factory picture in picture settings.
#define FACTORY_ELECTRONIC_STAB_SETTINGS_PKTTYPE 0x4D
Packet type for the factory electronic stabilization settings.
#define CAMERA_SAVE_CONFIGURATION_GIMBAL_PKTTYPE 0x50
Packet type for saving camera configuration as startup settings.
#define CAMERA_DEFAULT_CONFIGURATION_GIMBAL_PKTTYPE 0x51
Packet type for commanding a camera to its default configuration.
#define MISB_SETTINGS_PKTTYPE 0x52
Packet type for the MISB settings.
#define FACTORY_MISB_SETTINGS_PKTTYPE 0x53
Packet type for the factory MISB settings.
#define FPGA_BIT_VERSION_PKTTYPE 0x56
Packet type for the FPGA bit file version information.
#define MICROBLAZE_APP_VERSION_PKTTYPE 0x57
Packet type for the MB application version information.
#define VIDEO_ENHANCEMENT_SETTINGS_PKTTYPE 0x58
Packet type for the video enhancement settings.
#define FACTORY_VIDEO_ENHANCEMENT_SETTINGS_PKTTYPE 0x59
Packet type for the factory video enhancement settings.
#define GIMBAL_WATERMARK_DATA_PKTTYPE 0x5A
Packet type for the vps watermark data.
#define MOTION_CONTROLLER_BOOTLOADER_VERSION 0xA0
Packet type for motion controller bootloader version information.
#define MOTION_CONTROLLER_VERSION 0xA1
Packet type for motion controller version information.
#define MOTION_CONTROL_PARAMS 0xA2
Packet type for motion control settings.
#define MOTION_CONTROL_PARAMS_FACTORY 0xA3
Packet type for motion control factory settings.
#define MOTION_CALIBRATION_PARAMS 0xA4
Packet type for motion control calibration settings.
#define MOTION_CALIBRATION_PARAMS_FACTORY 0xA5
Packet type for motion control factory calibration settings.
#define AXIS_PARAMS 0xA6
Packet type for motion control axes settings.
#define AXIS_PARAMS_FACTORY 0xA7
Packet type for motion control factory axes settings.
#define AXIS_LIMITS 0xA8
Packet type for motion control limit settings.
#define AXIS_LIMITS_FACTORY 0xA9
Packet type for motion control factory limit settings.
#define SENSOR_ACQ_PARAMS 0xAA
Packet type for motion control acq settings.
#define SENSOR_ACQ_PARAMS_FACTORY 0xAB
Packet type for motion control acq factory settings.
Inter-Processor Group
#define MICROBLAZE_BUILT_IN_TEST_PKTTYPE 0x01
Packet type for starting built-in tests.
#define MICROBLAZE_TO_VPS_DIGITAL_ZOOM_PKTTYPE 0x02
Packet type for commanding digital zoom.
#define MICROBLAZE_TO_VPS_STROBE_PKTTYPE 0x04
Packet type for providing data to VPS.
#define VPS_TO_MICROBLAZE_STROBE_PKTTYPE 0x05
Packet type for getting data from VPS.
#define CAMERA_FFC_COMMAND_PKTTYPE 0x06
Packet type for commanding flat-field correction.
#define LASER_STATUS_MB_TO_565_PKTTYPE 0x07
Packet type for reporting laser status.
#define LASER_KEEP_ALIVE_565_TO_MB_PKTTYPE 0x08
Packet type for laser heartbeat message.
#define LASER_ARM_565_TO_MB_PKTTYPE 0x09
Packet type for laser arming.
#define LASER_FIRE_565_TO_MB_PKTTYPE 0x0A
Packet type for laser firing.
#define LASER_RF_DATA_MB_TO_565 0x0B
Packet type for laser range fider data.
#define MOTION_CONTROL_MODE 0xA1
Packet type for setting/reporting motion control mode.
#define SET_AXIS_POS_RATE 0xA2
Packet type for commanding motion control position or rate.
#define AXIS_STATUS 0xA3
Packet type for reporting motion control axes status.
#define MC_BIST_STATUS 0xA4
Packet type for reporting BIST status.
Video ground station group packet types
#define SET_ANTENNA_YAW_VGS_PKTTYPE 0x00
Packet type for changing the antenna yaw offset.
#define DIRECT_CONTROL_VGS_PKTTYPE 0x01
Packet type for direct control of VGS.
#define RADIO_SETUP_VGS_PKTTYPE 0x02
Packet type for changing radio setup of VGS.
#define TELEMETRY_VGS_PKTTYPE 0x03
Packet type for video grund station telemetry.
VPS Programming group packet types
#define VPS_DSP_LICENSE_KEY_PKTTYPE 0x4D
Development group packet types
#define ENABLE_NAV_DEV_PKTTYPE 0x01
Packet type for enabling or disabling navigation data.
#define STAB_TELEM_DEV_PKTTYPE 0x10
Packet type for development telemetry for stabilization analysis.
#define STAB_T2_SET_DEV_PKTTYPE 0x18
Packet type for commanding changes to stabilization settings.
#define CURRENT_DEV_PKTTYPE 0x20
Packet type for motor current data output.
#define STABILITY_DEV_PKTTYPE 0x30
Packet type for sending FOG board stability data.
#define VIDEO_TRK_DEV_PKTTYPE 0x40
Packet type for sending out video track diagnostic data.
VPS Development group packet types
#define VPS_PROGRAM_IN_PKTTYPE 0x00
Packet type for sending programming data from host through TASE and into VPS.
#define VPS_PROGRAM_OUT_PKTTYPE 0x01
Packet type for sending programming data from VPS through TASE and into host.
Microblaze Development Group
#define MB_LENS_REGISTER_PKTTYPE 0x00
Command to read/write a register for a lens controlled through the Microblaze.
#define MB_LENS_COMMAND_PKTTYPE 0x01
Command the lens position or a re-initialization.
#define MB_ENABLE_LENS_DIAGNOSTICS 0x02
Used to command the Microblaze to enable diagnostic outputs for a specifed lens.
#define MB_LENS_DIAGNOSTIC_PKTTYPE 0x03
Report of Microblaze lens diagnostic data (when enabled).
Microblaze Programming Group
#define MICROBLAZE_FLASH_DOWNLOAD_START 0x40
Inform the MB FFB that image packets are forthcoming. If received in the application sends to FFB.
#define MICROBLAZE_FLASH_DOWNLOAD_NO_ACK 0x41
Identify an image data packet that does not require an ack.
#define MICROBLAZE_FLASH_DOWNLOAD_AND_ACK 0x42
Identify an image data packet that expects an ack.
#define MICROBLAZE_FLASH_RESPONSE 0x43
Identify a response packet from the FFB. This packet includes a null terminated data message.
#define MICROBLAZE_FLASH_DOWNLOAD_END 0x44
Inform the MB FFB that the entire image has been sent.
#define MICROBLAZE_FLASH_ERASE 0x45
Command the MB to begin the erase process.
#define MICROBLAZE_FLASH_STROBE 0x46
Identify an FFB strobe packet. This packet includes FFB version info as a null terminated data message.
Motion Control Programming and Dev Group
#define MC_DSP_FLASH_DOWNLOAD_START 0x40
Inform the MC FFB that image packets are forthcoming. If received in the application goes to FFB.
#define MC_DSP_FLASH_DATA_NO_ACK 0x41
Identify an image data packet that does not require an ack.
#define MC_DSP_FLASH_DATA_ACK 0x42
Identify an image data packet that expects an ack.
#define MC_DSP_FLASH_RESPONSE 0x43
Identify a response packet from the FFB. This packet includes a null terminated data message.
#define MC_DSP_FLASH_DOWNLOAD_END 0x44
Inform the MC FFB that the entire image has been sent.
#define MC_DSP_FLASH_ERASE 0x45
Command the MC to begin the erase process.
#define MC_DSP_FLASH_STROBE 0x46
Identify an FFB strobe packet. This packet includes FFB version info as a null terminated data message.
#define MC_BIQUAD_PARAMS 0x50
Development/test packet.
#define MC_DEBUG_PARAMS 0x51
Development/test packet.
Enumerations
enum {
STEP_SPOI_OFF, STEP_SPOI_BY_DIST, STEP_SPOI_BY_POINTS, STEP_SPOI_BY_TIME,
STEP_RESERVED0, STEP_SPOI_JOYSTICK, STEP_SPOI_AUTO_SCAN, NUM_SPOI_STEP_MODES
}
Discrete SPOI stepping modes.
enum LaserTypes {
NO_LASER, LASER_POINTER, LASER_ILLUMINATOR, LASER_RANGER,
LASER_DESIGNATOR, NUM_LASER_TYPES
}
Types of lasers.
enum LaserClasses {
LASER_NA_CLASS, LASER_CLASS1, LASER_CLASS1M, LASER_CLASS2,
LASER_CLASS2M, LASER_CLASS3R, LASER_CLASS3B, LASER_CLASS4,
NUM_LASER_CLASS
}
Laser classifications.
enum LaserProtocol { LASER_TYPE_DUMB_LASER, LASER_TYPE_FLIR_CLI_30 = 10 }
Laser protocols.
enum LaserSafetyFlags {
LOST_COMMS_AP = 0, LOST_COMMS_GND, ON_GROUND, POS_ELEV_ANGLE,
WATCHDOG_TIMER, MIN_AGL, GLOBAL_PSWD, AGL_INVALID,
NUM_LASER_SAFETY_FLAGS
}
Laser Safety Flags.
enum LaserRangeFinderStatus {
LRF_STATUS_STANDBYE = 0, LRF_STATUS_FIRING, LRF_STATUS_BORE_SIGHTING, LRF_STATUS_ERROR_ACCURACY,
LRF_STATUS_ERROR_TEMP, LRF_STATUS_ERROR_ACC_TEMP, LRF_STATUS_ERROR_RANGE, LRF_STATUS_ERROR_CHECKSUM
}
Laser rangefinder status.
enum GimbalProtocolTypes {
NO_GIMBAL_PROTOCOL, GIMBAL_COMM, GIMBAL_KLV, GIMBAL_VPS,
GIMBAL_HMR_2300, GIMBAL_HMR_3400, GIMBAL_NOVATEL, NUM_GIMBAL_PROTOCOLS
}
Types of communications protocols.
enum GimbalINSAidingtypes {
NO_GIMBAL_INS_AID, MAG_HEADING_GIMBAL_INS_AID, EXT_HEADING_GIMBAL_INS_AID, VPS_HEADING_GIMBAL_INS_AID,
EXT_ATTITUDE_GIMBAL_INS_AID, NOVATEL_ALIGN_INS_AID, NUM_GIMBAL_INS_AID
}
Types of aiding that can be applied to a gimbal INS.
enum FocusMode_t {
AUTO_FOCUS, FOCUS_ONCE, INFINITE_FOCUS, MANUAL_FOCUS,
NUM_FOCUS_MODE
}
Focus enumerations for GimbalTelemetryData_t.FocusMode.
enum ExposureMode_t {
EXPOSURE_FULL_AUTO = 0, EXPOSURE_SHUTTER_PRIORITY = 1, EXPOSURE_BRIGHT = 2, NUM_EXPOSURE_MODES,
EXPOSURE_NO_CHANGE = 0xFF
}
Exposure mode enumerations.
enum {
NO_RETRACTOR, THREEAX_RETRACTOR, ACR_RETRACTOR, ARCTURUS_RETRACTOR,
VTRACT1_RETRACTOR, VTRACT2_RETRACTOR, NUM_RETRACTORS
}
Retractor enumerations.
enum Vps3Reset_t { VPS3_RESET_POWER = 0, VPS3_RESET_WATCHDOG, VPS3_RESET_UNKNOWN = 0xFF }
VPS3 reset source data.
enum HDControlSettings_t { HD_MODE_NATIVE = 0, HD_MODE_CENTER_WINDOW = 1, HD_MODE_SHRINK_TO_FIT = 2 }
HD control modes on VPS3.
enum EStabModes_t { ESTAB_ENABLED = 0x00, ESTAB_DISABLED = 0x01, ESTAB_DONT_CHANGE = 0xFF }
Estab settings.
enum VPS3PosFormat_t {
VPS_POS_FORMAT_MGRS_10 = 1, VPS_POS_FORMAT_UTM_HEMI, VPS_POS_FORMAT_RESERVED_0, VPS_POS_FORMAT_DEG,
VPS_POS_FORMAT_DMS, VPS_POS_FORMAT_DMM, VPS_POS_FORMAT_NO_CHANGE = 0xFF
}
VPS3 position format.
enum VPSLenFormat_t { LEN_FORMAT_METERS = 0, LEN_FORMAT_FEET, NUM_LEN_FORMATS, LEN_FORMAT_NO_CHANGE = 0xFF }
enum VPSAngleFormat_t { ANGLE_FORMAT_PAN_TILT = 0, ANGLE_FORMAT_AZIM_ELEV, NUM_ANGLE_FORMATS, ANGLE_FORMAT_NO_CHANGE = 0xFF }
enum MbReset_t { MB_RESET_POWER = 0, MB_RESET_WATCHDOG, MB_RESET_UNKNOWN = 0xFF }
Microblaze reset source data.
States of the gimbal packet receive state machine
enum {
GIMBAL_PKT_SYNC1_STATE, GIMBAL_PKT_SYNC2_STATE, GIMBAL_PKT_SYNC3_STATE, GIMBAL_PKT_SIZE_STATE,
GIMBAL_PKT_GROUP_STATE, GIMBAL_PKT_PKTTYPE_STATE, GIMBAL_PKT_DATA_STATE, GIMBAL_PKT_CHECK1_STATE,
GIMBAL_PKT_CHECK2_STATE
}
Gimbal mode enumeration
enum GimbalModes {
GIMBAL_VELOCITY_FEEDBACK, GIMBAL_POSITION_FEEDBACK, GIMBAL_SPOI_FEEDBACK, GIMBAL_VIDEO_ST_RATE_FEEDBACK,
GIMBAL_VIDEO_TT_RATE_FEEDBACK, GIMBAL_VIDEO_ST_SPOI_FEEDBACK, GIMBAL_VIDEO_TT_SPOI_FEEDBACK, GIMBAL_SPOI_PATH_MODE,
GIMBAL_SCAN_ELLIPSE_MODE, GIMBAL_RIG_TEST_MODE, GIMBAL_PAN_INIT_MODE, GIMBAL_TILT_MAX_INIT_MODE,
GIMBAL_TILT_MIN_INIT_MODE, GIMBAL_POS_INIT_MODE, GIMBAL_DETECT_RETRACT_MODE, GIMBAL_WAIT_FOR_DEPLOY_MODE,
NUM_GIMBAL_MODES
}
Camera protocol enumeration
enum CameraProtocolTypes {
CAMERA_TYPE_NO_CAMERA, CAMERA_TYPE_DUMB_CAMERA, CAMERA_TYPE_SONY = 10, CAMERA_TYPE_SONY_XCL = 15,
CAMERA_TYPE_PHOTON = 20, CAMERA_TYPE_TAU, CAMERA_TYPE_HRC, CAMERA_TYPE_SWIRTAU = 25,
CAMERA_TYPE_THERMO = 30, CAMERA_TYPE_PROSILICA = 40, CAMERA_TYPE_320_KTX = 50, CAMERA_TYPE_640_KTX,
CAMERA_TYPE_SU_JSX, CAMERA_TYPE_IRCAM, CAMERA_TYPE_640_CSX, CAMERA_TYPE_VPS_MIN = 100,
CAMERA_TYPE_VPS_FLEA3C, CAMERA_TYPE_VPS_BLACKFLY_345, CAMERA_TYPE_VPS_BLACKFLY_220, CAMERA_TYPE_VPS_MAX
}
Lens type enumeration
enum LensTypes {
LENS_TYPE_NO_LENS, LENS_TYPE_GENERIC_FIXED, LENS_TYPE_GENERIC_CZOOM, LENS_TYPE_LENS_DOUBLER,
LENS_TYPE_CAMERA_SPECIFIED, LENS_TYPE_CCT_MWIR_CZOOM, LENS_TYPE_CCT_LWIR_DZOOM, LENS_TYPE_CCT_SWIR_CAT,
LENS_TYPE_SPOTTER, LENS_TYPE_SUPER_SPOTTER, LENS_TYPE_CCT_HD_MWIR_CZOOM, LENS_TYPE_CCT_HD_VIS_SWIR_CZOOM,
LENS_TYPE_CCT_SWIR_FIXED
}
Type of sensor enumeration
enum TypeOfSensor {
NO_SENSOR, SENSOR_EO, SENSOR_LWIR_WHITE, SENSOR_LWIR_BLACK,
SENSOR_MWIR_WHITE, SENSOR_MWIR_BLACK, SENSOR_SWIR, SENSOR_EO_NO_ZOOM,
SENSOR_EO_SPOTTER, NUM_SENSOR_TYPES
}
Video output type enumeration
enum OutputTypes {
VIDEO_OUTPUT_NONE, VIDEO_OUTPUT_NTSC, VIDEO_OUTPUT_PAL, VIDEO_OUTPUT_HD_720I,
VIDEO_OUTPUT_HD_720P, VIDEO_OUTPUT_HD_1080I, VIDEO_OUTPUT_HD_1080P, VIDEO_OUTPUT_CUSTOM,
VIDEO_OUTPUT_NTSC_GIGE
}
Sony Camera type enumeration
enum SonyCameraTypes {
SONY_FCB_EX480B = 0x24, SONY_FCB_EX480BP, SONY_FCB_EX48B, SONY_FCB_EX48BP,
SONY_FCB_IX11 = 0x2E, SONY_FCB_IX11P, SONY_FCB_EX980 = 0x30, SONY_FCB_EX980P,
SONY_FCB_EX980S, SONY_FCB_EX980SP, SONY_FCB_EX480C, SONY_FCB_EX480CP,
SONY_FCB_EX45MC = 0x3A, SONY_FCB_EX45MCC, SONY_FCB_EX1000 = 0x42, SONY_FCB_EX1000P,
SONY_FCB_EX1010, SONY_FCB_EX1010P, SONY_FCB_H10 = 0x4A, SONY_FCB_H11,
SONY_FCB_EX1020 = 0x50, SONY_FCB_EX1020P, SONY_FCB_EH4300 = 0x5C, SONY_FCB_EH6300 = 0x5F,
SONY_FCB_EH6500 = 0x66, SONY_FCB_EV7500, SONY_FCB_EV7100
}
Lens control type configuration enumerations
enum LensControlConfig {
LENS_CONFIG_T300_LWIR_4680, LENS_CONFIG_T300_NG_LWIR_4680, LENS_CONFIG_T400_MWIR_4680, LENS_CONFIG_T400_MWIR_66K80,
LENS_CONFIG_T350_LWIR_66K80, LENS_CONFIG_T400_LRS_66K80, LENS_CONFIG_T400_DXR_66K80, LENS_CONFIG_T400_DNXR_4680,
LENS_CONFIG_NONE = 0x7F
}
Gains enumeration for Accel Net (T2)
enum {
AC_PAN_POS_P, AC_PAN_POS_VF, AC_PAN_POS_AF, AC_PAN_VEL_P,
AC_PAN_VEL_I, AC_PAN_CUR_P, AC_PAN_CUR_I, AC_PAN_FREQ,
AC_TILT_POS_P, AC_TILT_POS_VF, AC_TILT_POS_AF, AC_TILT_VEL_P,
AC_TILT_VEL_I, AC_TILT_CUR_P, AC_TILT_CUR_I, AC_TILT_FREQ,
AC_NUM_GAINS
}
Functions
SInt32 GetCameraStringName (const CameraDefinition_t *pCam, char *pName, UInt32 MaxSize)
Return a string description of the camera.
SInt32 GetLensStringName (const CameraDefinition_t *pCam, char *pName, UInt32 MaxSize)
Return a string description of the lens.
void MakeGimbalPacketHeader (GimbalPkt_t *pPkt, UInt8 Frame, UInt8 SubFrame, UInt8 Size)
Fill out a gimbal packet header.
void FinishGimbalPacket (GimbalPkt_t *pPkt, UInt8 Frame, UInt8 SubFrame, UInt8 Size)
Fill out a gimbal packet header and checksum.
void ChecksumGimbalPacket (GimbalPkt_t *pPkt)
Calculate and fill out a gimbal packet checksum.
UInt16 CalcGimbalPacketChecksum (const GimbalPkt_t *pPkt)
Calculate a gimbal packet checksum.
void MakeGimbalPacket (GimbalPkt_t *pPkt, UInt8 Frame, UInt8 SubFrame, const UInt8 *pData, UInt8 Size)
Build a gimbal packet from passed data.
BOOL LookForGimbalPacketInByte (GimbalPkt_t *pPkt, UInt8 Byte)
Look for a gimbal packet in a series of bytes.
BOOL DecodeGimbalRetractorConfigurationPacket (const GimbalPkt_t *pPkt, Retractor_t *pRetractor)
Decode a packet with the retractor configuration data.
void FormGimbalRetractorConfigurationPacket (GimbalPkt_t *pPkt, const Retractor_t *pRetractor)
Form a packet with the retractor configuration data.
BOOL DecodeGimbalFLIRConfigurationPacket (const GimbalPkt_t *pPkt, FLIRConfig_t *pConfig)
Decode a packet with FLIR configuration information.
void FormGimbalFLIRConfigurationPacket (GimbalPkt_t *pPkt, const FLIRConfig_t *pConfig)
Form a packet with FLIR configuration information.
BOOL DecodeGimbalIRCamConfigurationPacket (const GimbalPkt_t *pPkt, IRCamConfig_t *pConfig)
Decode a packet with IRCam configuration information.
void FormGimbalIRCamConfigurationPacket (GimbalPkt_t *pPkt, const IRCamConfig_t *pConfig)
Form a packet with IRCam IR configuration information.
BOOL DecodeGimbalIRCamSaveRestorePacket (const GimbalPkt_t *pPkt, UInt8 *pConfigAction)
Decode a packet to save/restore IRCam IR configuration information.
void FormGimbalIRCamSaveRestorePacket (GimbalPkt_t *pPkt, UInt8 ConfigAction)
Form a packet to save/restore IRCam IR configuration information.
BOOL DecodeSuCsxConfigurationPacket (const GimbalPkt_t *pPkt, SuCsxCamConfig_t *pConfig)
Decode a packet with SU CSX configuration information.
void FormSuCsxConfigurationPacket (GimbalPkt_t *pPkt, const SuCsxCamConfig_t *pConfig)
Form a packet with SU CSX configuration information.
BOOL DecodeSuCsxSaveRestorePacket (const GimbalPkt_t *pPkt, UInt8 *pConfigAction)
Decode a packet to save/restore SU CSX configuration information.
void FormSuCsxSaveRestorePacket (GimbalPkt_t *pPkt, UInt8 ConfigAction)
Form a packet to save/restore SU CSX configuration information.
BOOL DecodeGimbalKLVDetailsPacket (const GimbalPkt_t *pPkt, KLVDetails_t *pKLV)
Decode a packet with KLV settings information.
void FormGimbalKLVDetailsPacket (GimbalPkt_t *pPkt, const KLVDetails_t *pKLV)
Form a packet with the KLV details.
BOOL DecodeGimbalSensorConfigPacket (const GimbalPkt_t *pPkt, float Rotation[N3D], GimbalSensorFlags_t *pFlags)
Decode a packet with sensor configuration data.
void FormGimbalSensorConfigPacket (GimbalPkt_t *pPkt, const float Rotation[N3D], GimbalSensorFlags_t Flags)
Form a packet with the sensor configuration data.
BOOL DecodeGimbalMagCalPacket (const GimbalPkt_t *pPkt, float HardIronErr[N3D], float ScaleFactErr[N3D])
Decode a packet with magnetometer calibration data.
void FormGimbalMagCalPacket (GimbalPkt_t *pPkt, const float HardIronErr[N3D], const float ScaleFactErr[N3D])
Form a packet with the magnetometer calibration data.
BOOL DecodeGimbalSerialInterfacePacket (const GimbalPkt_t *pPkt, GimbalSerial_t Interface[6], BOOL *pTemporary)
Interpret a serial interface setup packet.
void FormGimbalSerialInterfacePacket (GimbalPkt_t *pPkt, const GimbalSerial_t Interface[6], BOOL Temporary)
Create a serial interface setup packet.
BOOL DecodeCameraDefinitionsPacket (const GimbalPkt_t *pPkt, CameraDefinition_t Cam[NUM_CAMERAS], BOOL Received[NUM_CAMERAS])
Interpret a camera definitions packet.
void FormCameraDefinitionsPacket (GimbalPkt_t *pPkt, const CameraDefinition_t Cam[NUM_CAMERAS], const BOOL Send[NUM_CAMERAS], BOOL Factory)
Createa a camera definitions packet.
BOOL DecodeGimbalCameraCmdPacket (const GimbalPkt_t *pPkt, UInt8 *Camera, float *pHFOV, UInt16 *pFocus, UInt8 *pEMode, UInt8 *pShutter, UInt8 *pBright, UInt8 *pFlags)
Interpret a camera command packet containing the field of view and focus.
void FormGimbalCameraCmdPacket (GimbalPkt_t *pPkt, UInt8 Camera, float HFOV, UInt16 Focus, UInt8 Mode, UInt8 Shutter, UInt8 Bright, UInt8 Flags)
Create a camera command packet containing the field of view and focus.
BOOL DecodeGimbalSPOICmdPacket (const GimbalPkt_t *pPkt, double Pos[NPOS], float Vel[NDIR], UInt8 *pFlags)
Interpret a gimbal sensor point of interest packet containing the position of the SPOI.
void FormGimbalSPOICmdPacket (GimbalPkt_t *pPkt, const double Pos[NPOS], const float Vel[NDIR], UInt8 Flags)
Create a gimbal sensor point of interest packet containing the position of the SPOI.
BOOL DecodeGimbalAxisSettingsPacket (const GimbalPkt_t *pPkt, float NoGoCenter[NGIMBAL_SHORT], float NoGoRange[NGIMBAL_SHORT], float MaxRate[NGIMBAL_SHORT], float MaxAccel[NGIMBAL_SHORT], float PosGain[NGIMBAL_SHORT], float VelGain[NGIMBAL_SHORT], float DerGain[NGIMBAL_SHORT], BOOL *pTemporary)
Interpret a gimbal axis control packet.
void FormGimbalAxisSettingsPacket (GimbalPkt_t *pPkt, const float NoGoCenter[NGIMBAL_SHORT], const float NoGoRange[NGIMBAL_SHORT], const float MaxRate[NGIMBAL_SHORT], const float MaxAccel[NGIMBAL_SHORT], const float PosGain[NGIMBAL_SHORT], const float VelGain[NGIMBAL_SHORT], const float DerGain[NGIMBAL_SHORT], BOOL Temporary, BOOL Factory)
Create a gimbal axis control packet.
BOOL DecodeGimbalFilterPacket (const GimbalPkt_t *pPkt, float *pCutoff, float *pDeadband)
Interpret a gimbal filter packet.
void FormGimbalFilterPacket (GimbalPkt_t *pPkt, float Cutoff, float Deadband)
Create a gimbal filter packet.
BOOL DecodeGimbalGPSLeverArmPacket (const GimbalPkt_t *pPkt, float Arm[N3D])
Interpret a gimbal GPS lever arm packet.
void FormGimbalGPSLeverArmPacket (GimbalPkt_t *pPkt, const float Arm[N3D])
Create a gimbal GPS lever arm packet.
BOOL DecodeGimbalCameraAlignPacket (const GimbalPkt_t *pPkt, float *pZoom1, float Error1[NGIMBAL], float *pZoom2, float Error2[NGIMBAL], UInt8 *pCamera)
Interpret a gimbal camera alignment packet.
void FormGimbalCameraAlignPacket (GimbalPkt_t *pPkt, float Zoom1, const float Error1[NGIMBAL], float Zoom2, const float Error2[NGIMBAL], UInt8 Camera, BOOL Factory)
Create a gimbal camera alignment packet.
void FormGimbalCameraZoomPacket (GimbalPkt_t *pPkt, UInt8 Camera, SInt8 Rate, float Timeout)
Create the gimbal camera zoom packet.
BOOL DecodeGimbalCameraZoomPacket (const GimbalPkt_t *pPkt, UInt8 *pCamera, SInt8 *pRate, float *pTimeout)
Decode the gimbal camera zoom packet.
BOOL DecodeGimbalRetractDeployCmdPacket (const GimbalPkt_t *pPkt, UInt32 *pDeploy)
Interpret a 3AX retract or deploy command packet.
void FormGimbalRetractDeployCmdPacket (GimbalPkt_t *pPkt, UInt32 Deploy)
Create a 3AX retract or deploy command packet.
BOOL DecodeGimbalRigTestCmdPacket (const GimbalPkt_t *pPkt, float *pMaxSpeed, float *pMaxAccel, UInt16 *pTime)
Interpret a gimbal rig test command packet.
void FormGimbalRigTestCmdPacket (GimbalPkt_t *pPkt, float MaxSpeed, float MaxAccel, UInt16 Time)
Create a gimbal rig test packet.
BOOL DecodeGimbalLaserArmCmdPacket (const GimbalPkt_t *pPkt, UInt8 *pLaserIndex, BOOL *pArm)
Interpret a laser arm command.
void FormGimbalLaserArmCmdPacket (GimbalPkt_t *pPkt, UInt8 LaserIndex, BOOL Arm)
Create a laser arm command.
BOOL DecodeGimbalLaserFireCmdPacket (const GimbalPkt_t *pPkt, UInt8 *pLaserIndex, UInt8 *pPower)
Interpret a laser fire command.
void FormGimbalLaserFireCmdPacket (GimbalPkt_t *pPkt, UInt8 LaserIndex, UInt8 Power)
Create a laser fire command.
BOOL DecodeGimbalLasersInstalledPacket (const GimbalPkt_t *pPkt, LaserSetup_t Lasers[NUM_LASERS])
Interpret a lasers installed packet.
void FormGimbalLasersInstalledPacket (GimbalPkt_t *pPkt, const LaserSetup_t Lasers[NUM_LASERS], BOOL Factory)
Create a lasers installed packet.
void FormLaserSafetyStatus (GimbalPkt_t *pPkt, BOOL BypassSafety, UInt8 flags)
Create a laser status and safety packet.
BOOL DecodeLaserSafetyStatus (const GimbalPkt_t *pPkt, BOOL *BypassSafety, UInt8 *pFlags)
Interpret a laser status and safety packet.
void FormLaserWatchdogPacket (GimbalPkt_t *pPkt, UInt8 LaserIndex)
Form a laser watchdog packet for the laser with index LaserIndex;.
BOOL DecodeLaserWatchdogPacket (const GimbalPkt_t *pPkt, UInt8 *LaserIndex)
Interpret a laser watchdog packet. The relevent laser index is returned if successful.
void FormLaserEnablePswdPacket (GimbalPkt_t *pPkt, UInt16 pswd, BOOL ByPassAgl)
Form a packet with the password to enable laser operations.
BOOL DecodeLaserEnablePswdPacket (const GimbalPkt_t *pPkt, UInt16 *pswd, BOOL *pByPassAgl)
Decode a laser password packet.
void FormGimbalAglPacket (GimbalPkt_t *pPkt, UInt16 AglMeters, BOOL AglValid)
Tell the gimbal what its AGL altitude is.
BOOL DecodeGimbalAglPacket (const GimbalPkt_t *pPkt, UInt16 *pAglMeters, BOOL *pAglValid)
Decode a AGL altitude packet for the gimbal.
BOOL DecodeGimbalRadioSettings (const GimbalPkt_t *pPkt, RadioSettings_t *pSettings)
Decode a radio settings packet for the gimbal.
void FormGimbalRadioSettings (GimbalPkt_t *pPkt, const RadioSettings_t *pSettings)
Form a radio settings packet for the gimbal.
BOOL DecodeGimbalTrackCommand (const GimbalPkt_t *pPkt, float *pInitialX, float *pInitialY, UInt8 *pAlgorithm, UInt8 *pSize, UInt8 *pStamp)
Decode the track command packet.
void FormGimbalTrackCommand (GimbalPkt_t *pPkt, float InitialX, float InitialY, UInt8 Algorithm, UInt8 Size, UInt8 Stamp)
Form the track command packet.
BOOL DecodeGimbalEnhancementCommand (const GimbalPkt_t *pPkt, BOOL *pEnabled, UInt8 *pIntensity, UInt8 *pLimit)
Decode the image enhancement command packet.
void FormGimbalEnhancementCommand (GimbalPkt_t *pPkt, BOOL Enabled, UInt8 Intensity, UInt8 Limit)
Form the image enhancement command packet.
BOOL DecodeGimbalTrackerSettingsAdvancedCommand (const GimbalPkt_t *pPkt, float *pGainP, float *pGainI, float *pGainD, float *pRateLimit, float *pDeadband)
Decode the advanced settings packet.
void FormGimbalTrackerSettingsAdvancedCommand (GimbalPkt_t *pPkt, float GainP, float GainI, float GainD, float RateLimit, float Deadband, BOOL Factory)
Form the advanced settings packet.
BOOL DecodeVGSRadioSettings (const GimbalPkt_t *pPkt, RadioSettings_t *pSettings)
Decode a radio settings packet for the video ground station.
void FormVGSRadioSettings (GimbalPkt_t *pPkt, const RadioSettings_t *pSettings)
Form a radio settings packet for the video ground station.
BOOL DecodeVGSAntennaYaw (const GimbalPkt_t *pPkt, float *pYaw)
Decode a packet that sets the current yaw angle of the antenna.
void FormVGSAntennaYaw (GimbalPkt_t *pPkt, float Yaw)
Form a packet that sets the current yaw angle of the antenna.
BOOL DecodeStabDevT2Settings (const GimbalPkt_t *pPkt, SInt16 Gains[AC_NUM_GAINS])
Decode a T2 development settings packet with motor controller gains.
void FormStabDevT2Settings (GimbalPkt_t *pPkt, const SInt16 Gains[AC_NUM_GAINS])
Create a T2 development settings packet with motor controller gains.
BOOL DecodeGimbalTrackingData (const GimbalPkt_t *pPkt, float GimbalAngles[NGIMBAL], float CameraAngles[NAXIS], float *pHFOV, float *pRange, UInt8 *pMode)
Decode a packet that has the gimbal tracking data in it.
void FormGimbalTrackingData (GimbalPkt_t *pPkt, const float GimbalAngles[NGIMBAL], const float CameraAngles[NAXIS], float HFOV, float Range, UInt8 Mode)
Create a packet that has the gimbal tracking data in it.
void FormSPOIPathSettings (GimbalPkt_t *pPkt, UInt8 StepMode, float MaxVel, float ActiveRange, float ConvDist, float StepDist, UInt32 StepTime, float ScanRate)
Create a SPOI path navigator settings packet.
BOOL DecodeSPOIPathSettings (const GimbalPkt_t *pPkt, UInt8 *pStepMode, float *pMaxVel, float *pActiveRange, float *pConvDist, float *pStepDist, UInt32 *pStepTime, float *pScanRate)
Decode a SPOI path navigator settings packet.
BOOL FormSPOIPathPointData (GimbalPkt_t *pPkt, const double PosECEF[MAX_SPOI_PATH_PTS][NPOS], UInt8 NumPoints)
Create a SPOI path point data packet.
BOOL DecodeSPOIPathPointData (const GimbalPkt_t *pPkt, double PosECEF[MAX_SPOI_PATH_PTS][NPOS], UInt8 *pNumPoints)
Decode a SPOI path point data packet.
void FormFrameShiftPacket (GimbalPkt_t *pPkt, UInt8 Source, float FrameShiftH, float FrameShiftV, UInt16 NumFrames, UInt16 DeltaT)
Form a packet that contains the image frame shifts.
BOOL DecodeFrameShiftPacket (const GimbalPkt_t *pPkt, UInt8 *pSource, float *pFrameShiftH, float *pFrameShiftV, UInt16 *pNumFrames, UInt16 *pDeltaT)
Decode a packet that contains the image frame shifts.
void FormLensPrefocusPacket (GimbalPkt_t *pPkt, UInt8 CameraIndex, UInt8 LensType, const float Zooms[10], const UInt16 Focuses[10], UInt8 NumEntries)
Form a packet that specifies the pre-focus calibration table.
BOOL DecodeLensPrefocusPacket (const GimbalPkt_t *pPkt, UInt8 *pCameraIndex, UInt8 *pLensType, float Zooms[10], UInt16 Focuses[10], UInt8 *pNumEntries)
Decode a packet that specifies the pre-focus calibration table.
void FormLensCalZoomPacket (GimbalPkt_t *pPkt, UInt8 CameraIndex, const SInt16 Zooms[26], UInt8 NumEntries)
Form a packet that specifies the zoom points of a pre-focus calibration table.
BOOL DecodeLensCalZoomPacket (const GimbalPkt_t *pPkt, UInt8 *pCameraIndex, SInt16 Zooms[26], UInt8 *pNumEntries)
Decode a packet that specifies the zoom points of a pre-focus calibration table.
void FormLensCalFocusPacket (GimbalPkt_t *pPkt, UInt8 CameraIndex, UInt8 RowIndex, float Temperature, const SInt16 Focuses[AF_CAL_POINTS], UInt8 NumEntries)
Form a packet that specifies the temperature and focus points of a pre-focus calibration table.
BOOL DecodeLensCalFocusPacket (const GimbalPkt_t *pPkt, UInt8 *pCameraIndex, UInt8 *pRowIndex, float *pTemperature, SInt16 Focuses[AF_CAL_POINTS], UInt8 *pNumEntries)
Decode a packet that specifies the temperature and focus points of a pre-focus calibration table.
void FormCanPassthroughPacket (GimbalPkt_t *pPkt, UInt16 ID, const UInt8 Data[8], UInt8 Length)
Form a packet containing a CAN frame received from or to be sent to CAN-B.
BOOL DecodeCanPassthroughPacket (const GimbalPkt_t *pPkt, UInt16 *pID, UInt8 Data[8], UInt8 *pLength)
Decode a packet containing a CAN frame received from or to be sent to CAN-B.
void SetLaserFixedParams (LaserSetup_t *pLaser)
Set laser parameters that are fixed based on laser type.
BOOL DecodeHdControlSettings (const GimbalPkt_t *pPkt, HDControlSettings_t *pSettings)
Decode the HD control settings.
void FormHdControlSettings (GimbalPkt_t *pPkt, HDControlSettings_t Settings, BOOL Factory)
BOOL DecodeVps3OverlaySettings (const GimbalPkt_t *pPkt, BOOL *pEnabled, VPS3Symbology_t *pSettings, float *localTimeOffsetHours, BOOL *localTimeDST)
Decode the VPS3 overlay settings.
void FormVps3OverlaySettings (GimbalPkt_t *pPkt, BOOL Enabled, VPS3Symbology_t *pSettings, float localTimeOffsetHours, BOOL localTimeDST, BOOL Factory)
BOOL DecodeVps3PiPSettings (const GimbalPkt_t *pPkt, BOOL *pEnabled)
Decode the VPS3 picture in picture settings.
void FormVps3PiPSettings (GimbalPkt_t *pPkt, BOOL enabled, BOOL factory)
BOOL DecodeEstabSettings (const GimbalPkt_t *pPkt, EStabModes_t *pMode)
Decode the estab control settings.
void FormEstabSettings (GimbalPkt_t *pPkt, EStabModes_t Mode, BOOL Factory)
BOOL DecodeMISBSettingsPacket (const GimbalPkt_t *pPkt, MISBConfig_t *pData)
Decode a video settings packet.
void FormMISBSettingsPacket (GimbalPkt_t *pPkt, const MISBConfig_t Data, BOOL Factory)
Form a video settings packet.
BOOL DecodeGimbalTargetLocationEstimate (const GimbalPkt_t *pPkt, double PosLLA[NPOS], UInt32 *pGPSTOW, UInt8 *pSource, UInt8 *pError)
Decode the estimate of the target location position coming from the user.
void FormGimbalTargetLocationEstimate (GimbalPkt_t *pPkt, const double PosLLA[NPOS], UInt32 GPSTOW, UInt8 source, UInt8 error)
Create a target location estimate packet.
void FormMC_DoMotionCalibrationPacket (GimbalPkt_t *pPkt, UInt16 Flags, UInt16 Type)
Form a motion control do calibration packet.
BOOL DecodeMC_MotionCalibrationParamPacket (const GimbalPkt_t *pPkt, float Offsets[3], float GainMatrix[9])
Decode a motion control parameter packet.
void FormMC_MotionCalibrationParamPacket (GimbalPkt_t *pPkt, const float Offsets[3], const float GainMatrix[9], BOOL Factory)
Form a motion control parameter packet.
BOOL DecodeMC_AxisParamPacket (const GimbalPkt_t *pPkt, float *pInPanKp, float *pInPanKi, float *pInPanKd, float *pInTiltKp, float *pInTiltKi, float *pInTiltKd, float *pOutPanKp, float *pOutPanKi, float *pOutPanKd, float *pOutTiltKp, float *pOutTiltKi, float *pOutTiltKd)
Decode a motion control axis parameter packet.
void FormMC_AxisParamPacket (GimbalPkt_t *pPkt, float InPanKp, float InPanKi, float InPanKd, float InTiltKp, float InTiltKi, float InTiltKd, float OutPanKp, float OutPanKi, float OutPanKd, float OutTiltKp, float OutTiltKi, float OutTiltKd, BOOL Factory)
Form a motion control axis parameter packet.
BOOL DecodeMC_LimitsPacket (const GimbalPkt_t *pPkt, float *pPanMin, float *pPanMax, float *pTiltMin, float *pTiltMax, float *pPanRateMax, float *pTiltRateMax, float *pPanAccelMax, float *pTiltAccelMax)
Decode a motion control limits packet.
void FormMC_LimitsPacket (GimbalPkt_t *pPkt, float PanMin, float PanMax, float TiltMin, float TiltMax, float PanRateMax, float TiltRateMax, float PanAccelMax, float TiltAccelMax, BOOL Factory)
Form a motion control limits packet.
void FormLensRegisterPacket (GimbalPkt_t *pPkt, UInt8 CameraId, UInt8 ControlType, UInt16 Address, UInt32 Value, BOOL Write)
Form a packet to set a lens register value.
BOOL DecodeLensRegisterPacket (const GimbalPkt_t *pPkt, UInt8 *pCameraId, UInt8 *pControlType, UInt16 *pAddress, UInt32 *pValue, BOOL *pWrite)
Decode a packet to set a lens register value.
void FormLensDevCommandPacket (GimbalPkt_t *pPkt, UInt8 CameraId, UInt8 ControlType, UInt8 InitFlag, SInt16 Position)
Form a packet to directly command a Microblaze controlled lens.
BOOL DecodeLensDevCommandPacket (const GimbalPkt_t *pPkt, UInt8 *pCameraId, UInt8 *pControlType, UInt8 *pInitFlag, SInt16 *pPosition)
Decode a packet to directly command a Microblaze controlled lens.
void FormSetLensDiagnosticsPacket (GimbalPkt_t *pPkt, UInt8 CameraId, BOOL Enabled)
Form a packet to enable/disable lens diagnostic reporting.
BOOL DecodeLensDiagnosticsPacket (const GimbalPkt_t *pPkt, LensDiagnostics_t *pData)
Decode a lens diagnostic packet.
void FormScanModeControlPacket (GimbalPkt_t *pPkt, const GimbalScanControlConfig_t *pData)
Form a packet to enable and configure gimbal scan mode control.
BOOL DecodeScanModeControlPacket (const GimbalPkt_t *pPkt, GimbalScanControlConfig_t *pData)
Decode a gimbal scan mode configuration packet.
void FormGimbalWaterMarkPacket (GimbalPkt_t *pPkt, UInt8 Format, UInt8 Status, UInt32 Sequence, const UInt8 *pImageData, UInt8 Size)
Form a packet to send watermark payload data.
BOOL DecodeGimbalWaterMarkPacket (const GimbalPkt_t *pPkt, UInt8 *pFormat, UInt8 *pStatus, UInt32 *pSequence, UInt8 *pImageData, UInt8 *pSize)
Decode a packet with watermark payload data.
Detailed Description
Gimbal packet encode and decode functionality.
Macro Definition Documentation
#define AXIS_LIMITS 0xA8
Packet type for motion control limit settings.
Referenced by DecodeMC_LimitsPacket(), and FormMC_LimitsPacket().
#define AXIS_LIMITS_FACTORY 0xA9
Packet type for motion control factory limit settings.
Referenced by DecodeMC_LimitsPacket(), and FormMC_LimitsPacket().
#define AXIS_PARAMS 0xA6
Packet type for motion control axes settings.
Referenced by DecodeMC_AxisParamPacket(), and FormMC_AxisParamPacket().
#define AXIS_PARAMS_FACTORY 0xA7
Packet type for motion control factory axes settings.
Referenced by DecodeMC_AxisParamPacket(), and FormMC_AxisParamPacket().
#define AXIS_SETTINGS_GIMBAL_PKTTYPE 0x02
Packet type for changing axis settings.
Referenced by CommBase_RequestGimbalAxisSettingsPacket(), DecodeGimbalAxisSettingsPacket(), and FormGimbalAxisSettingsPacket().
#define AXIS_STATUS 0xA3
Packet type for reporting motion control axes status.
#define CAMERA_ALIGN_GIMBAL_PKTTYPE 0x07
Packet type for camera alignment.
Referenced by CommBase_RequestGimbalCameraAlignPacket(), DecodeGimbalCameraAlignPacket(), and FormGimbalCameraAlignPacket().
#define CAMERA_CMD_GIMBAL_PKTTYPE 0x41
Packet type for camera control.
Referenced by CommBase_RequestGimbalCameraCmdPacket(), DecodeGimbalCameraCmdPacket(), and FormGimbalCameraCmdPacket().
#define CAMERA_DEFAULT_CONFIGURATION_GIMBAL_PKTTYPE 0x51
Packet type for commanding a camera to its default configuration.
#define CAMERA_DEFINITION_GIMBAL_PKTTYPE 0x05
Packet type for camera definitions.
Referenced by CommBase_RequestGimbalCameraTypesPacket(), DecodeCameraDefinitionsPacket(), and FormCameraDefinitionsPacket().
#define CAMERA_FFC_COMMAND_PKTTYPE 0x06
Packet type for commanding flat-field correction.
#define CAMERA_PASS_THROUGH_GIMBAL_PKTTYPE 0x42
Camera pass through packet type.
#define CAMERA_SAVE_CONFIGURATION_GIMBAL_PKTTYPE 0x50
Packet type for saving camera configuration as startup settings.
#define CAMERA_ZOOM_GIMBAL_PKTTYPE 0x48
Continuous camera zoom command.
Referenced by DecodeGimbalCameraZoomPacket(), and FormGimbalCameraZoomPacket().
#define CAN_PASSTHROUGH_GIMBAL_PKTTYPE 0x20
Packet type for setup/query of CANbus passthrough IDs.
Referenced by DecodeCanPassthroughPacket(), and FormCanPassthroughPacket().
#define CURRENT_DEV_PKTTYPE 0x20
Packet type for motor current data output.
Referenced by DecodeGimbalCurrentPacket().
#define DIAGNOSTIC_GIMBAL_PKTTYPE 0x02
Packet type for sending diagnostic information from the gimbal.
Referenced by DecodeGimbalDiagnosticsPacket().
#define DIRECT_CONTROL_VGS_PKTTYPE 0x01
Packet type for direct control of VGS.
Referenced by FormVGSAntennaCommand().
#define DO_MOTION_CALIBRATION 0x71
Command the gimbal to do a motio.
Referenced by FormMC_DoMotionCalibrationPacket().
#define ELECTRONIC_STAB_SETTINGS_PKTTYPE 0x44
Packet type for the electronic stabilization settings.
Referenced by DecodeEstabSettings(), and FormEstabSettings().
#define ENABLE_NAV_DEV_PKTTYPE 0x01
Packet type for enabling or disabling navigation data.
#define ENHANCEMENT_CMD_GIMBAL_PKTTYPE 0x52
Command to control image enhancement (deprecated)
Referenced by FormGimbalEnhancementCommand().
#define EXTERNAL_STABILIZER_GIMBAL_PKTTYPE 0x0B
Packet type for setup of external stabilizer.
#define EXTERNAL_STABILIZER_VERSION_GIMBAL_PKTTYPE 0x18
Packet for stabilizer board version info.
#define FACTORY_AXIS_SETTINGS_GIMBAL_PKTTYPE 0x0D
Packet type for changing factory axis settings.
Referenced by CommBase_RequestGimbalAxisSettingsPacket(), DecodeGimbalAxisSettingsPacket(), and FormGimbalAxisSettingsPacket().
#define FACTORY_CAMERA_ALIGN_GIMBAL_PKTTYPE 0x0F
Packet type for factory camera alignment.
Referenced by CommBase_RequestGimbalCameraAlignPacket(), DecodeGimbalCameraAlignPacket(), and FormGimbalCameraAlignPacket().
#define FACTORY_CAMERA_DEFINITION_GIMBAL_PKTTYPE 0x0E
Packet type for factory camera definitions.
Referenced by CommBase_RequestGimbalCameraTypesPacket(), DecodeCameraDefinitionsPacket(), and FormCameraDefinitionsPacket().
#define FACTORY_ELECTRONIC_STAB_SETTINGS_PKTTYPE 0x4D
Packet type for the factory electronic stabilization settings.
Referenced by DecodeEstabSettings(), and FormEstabSettings().
#define FACTORY_EXTERNAL_STABILIZER_GIMBAL_PKTTYPE 0x17
Packet for sending/querying factory stabilizer board settings.
#define FACTORY_HD_CONTROL_SETTINGS_PKTTYPE 0x4A
Packet type for the factory HD control modes of the VPS.
Referenced by DecodeHdControlSettings(), and FormHdControlSettings().
#define FACTORY_LASERS_INSTALLED_GIMBAL_PKTTYPE 0x10
Packet type for setup/query of factory installed lasers.
Referenced by CommBase_RequestGimbalLaserSetupPacket(), DecodeGimbalLasersInstalledPacket(), and FormGimbalLasersInstalledPacket().
#define FACTORY_MISB_SETTINGS_PKTTYPE 0x53
Packet type for the factory MISB settings.
Referenced by DecodeMISBSettingsPacket(), and FormMISBSettingsPacket().
#define FACTORY_OVERLAY_SETTINGS_PKTTYPE 0x4B
Packet type for the factory overlay settings.
Referenced by DecodeVps3OverlaySettings(), and FormVps3OverlaySettings().
#define FACTORY_PICTURE_IN_PICTURE_SETTINGS_PKTTYPE 0x4C
Packet type for the factory picture in picture settings.
Referenced by DecodeVps3PiPSettings(), and FormVps3PiPSettings().
#define FACTORY_TRACKER_ADV_CMD_GIMBAL_PKTTYPE 0x24
Packet type for factory advanced tracker settings.
Referenced by DecodeGimbalTrackerSettingsAdvancedCommand(), and FormGimbalTrackerSettingsAdvancedCommand().
#define FACTORY_VIDEO_ENHANCEMENT_SETTINGS_PKTTYPE 0x59
Packet type for the factory video enhancement settings.
#define FFC_CMD_GIMBAL_PKTTYPE 0x4A
Command to perform FFC.
#define FLIR_CONFIGURATION_GIMBAL_PKTTYPE 0x13
Packet type for configuring the FLIR camera.
Referenced by DecodeGimbalFLIRConfigurationPacket(), and FormGimbalFLIRConfigurationPacket().
#define FLIR_DEFAULT_CONFIGURATION_GIMBAL_PKTTYPE 0x15
Packet type for commanding FLIR camera to default configuration.
#define FLIR_SAVE_CONFIGURATION_GIMBAL_PKTTYPE 0x14
Packet type for saving FLIR camera configuration as startup settings.
#define FPGA_BIT_VERSION_PKTTYPE 0x56
Packet type for the FPGA bit file version information.
Referenced by DecodeFpgaBitVersionPacket().
#define FRAME_SHIFTS_GIMBAL_PKTTYPE 0xB0
Packet type for receiving image frame shifts from VPS or Tracker.
Referenced by DecodeFrameShiftPacket(), and FormFrameShiftPacket().
#define GEOREFERENCE_DATA_GIMBAL_PKTTYPE 0x41
Packet type for the geo referencing meta data, deprecated.
Referenced by DecodeGimbalGeoreferencePacket().
#define GIMBAL_AGL_PKTTYPE 0x82
Letting the Gimbal know what its Altitude AGL is.
Referenced by DecodeGimbalAglPacket(), and FormGimbalAglPacket().
#define GIMBAL_ANGLE_GIMBAL_PKTTYPE 0x10
Packet type for gimbal angle data.
Referenced by DecodeGimbalAnglePacket().
#define GIMBAL_CMD_GIMBAL_PKTTYPE 0x80
Packet type for basic gimbal commands.
Referenced by FormGimbalCmdPacket().
#define GIMBAL_COMMAND_AND_CONTROL_GROUP 0x00
Group number for all gimbal command and control packets.
Referenced by CommBase_RequestGimbalCameraCmdPacket(), DecodeGimbalAglPacket(), DecodeGimbalCameraCmdPacket(), DecodeGimbalCameraZoomPacket(), DecodeGimbalLaserArmCmdPacket(), DecodeGimbalLaserFireCmdPacket(), DecodeGimbalRadioSettings(), DecodeGimbalRetractDeployCmdPacket(), DecodeGimbalRigTestCmdPacket(), DecodeGimbalTrackCommand(), DecodeLaserEnablePswdPacket(), DecodeLaserSafetyStatus(), DecodeLaserWatchdogPacket(), DecodeScanModeControlPacket(), FormGimbalAglPacket(), FormGimbalCameraCmdPacket(), FormGimbalCameraZoomPacket(), FormGimbalCmdPacket(), FormGimbalEnhancementCommand(), FormGimbalLaserArmCmdPacket(), FormGimbalLaserFireCmdPacket(), FormGimbalRadioSettings(), FormGimbalRetractDeployCmdPacket(), FormGimbalRigTestCmdPacket(), FormGimbalTrackCommand(), FormLaserEnablePswdPacket(), FormLaserSafetyStatus(), FormLaserWatchdogPacket(), FormMC_DoMotionCalibrationPacket(), and FormScanModeControlPacket().
#define GIMBAL_DEVELOPMENT_GROUP 0xE8
Group number for development packets.
Referenced by DecodeGimbalCurrentPacket(), DecodeGimbalStabDevTelemetry(), DecodeStabDevT2Settings(), and FormStabDevT2Settings().
#define GIMBAL_DYNAMICS_INFORMATION_GROUP 0x08
Group number for all dynamics packets (rates, attitudes)
Referenced by DecodeFrameShiftPacket(), DecodeGimbalAnglePacket(), DecodeGimbalRatePacket(), DecodeGimbalRawVibrationPacket(), DecodeGimbalTrackingData(), FormFrameShiftPacket(), FormGimbalHostAttitudePacket(), FormGimbalHostSensorPacket(), FormGimbalInitialHeadingPacket(), and FormGimbalTrackingData().
#define GIMBAL_POSITION_INFORMATION_GROUP 0x10
Group number for all position packets (GPS, SPOI)
Referenced by CommBase_RequestGimbalSPOICmdPacket(), DecodeGimbalGeoreferencePacket(), DecodeGimbalSPOICmdPacket(), DecodeGimbalTargetLocationEstimate(), DecodeGimbalTelemetryPacket(), DecodeSPOIPathPointData(), FormGimbalHostGPSPacket(), FormGimbalSPOICmdPacket(), FormGimbalTargetLocationEstimate(), and FormSPOIPathPointData().
#define GIMBAL_RATE_GIMBAL_PKTTYPE 0x40
Packet type for gimbal angle and mount rate data.
Referenced by DecodeGimbalRatePacket().
#define GIMBAL_SCAN_CONTROL_PKTTYPE 0x83
Command and configure gimbal scan mode.
Referenced by DecodeScanModeControlPacket(), and FormScanModeControlPacket().
#define GIMBAL_SETUP_GROUP 0x48
Group number for setup packets.
Referenced by CommBase_RequestGimbalAxisSettingsPacket(), CommBase_RequestGimbalCameraAlignPacket(), CommBase_RequestGimbalCameraTypesPacket(), CommBase_RequestGimbalLaserSetupPacket(), DecodeCameraDefinitionsPacket(), DecodeCanPassthroughPacket(), DecodeEstabSettings(), DecodeFpgaBitVersionPacket(), DecodeGimbalAxisSettingsPacket(), DecodeGimbalCameraAlignPacket(), DecodeGimbalFilterPacket(), DecodeGimbalFLIRConfigurationPacket(), DecodeGimbalGPSLeverArmPacket(), DecodeGimbalIRCamConfigurationPacket(), DecodeGimbalIRCamSaveRestorePacket(), DecodeGimbalKLVDetailsPacket(), DecodeGimbalLasersInstalledPacket(), DecodeGimbalMagCalPacket(), DecodeGimbalRetractorConfigurationPacket(), DecodeGimbalSensorConfigPacket(), DecodeGimbalSerialInterfacePacket(), DecodeGimbalTrackerSettingsAdvancedCommand(), DecodeGimbalVersion2Packet(), DecodeGimbalVersionPacket(), DecodeGimbalWaterMarkPacket(), DecodeHdControlSettings(), DecodeLensCalFocusPacket(), DecodeLensControlVersionPacket(), DecodeLensPrefocusPacket(), DecodeMbAppVersionPacket(), DecodeMISBSettingsPacket(), DecodeMotionCtrlVersionPacket(), DecodeSPOIPathSettings(), DecodeSuCsxConfigurationPacket(), DecodeSuCsxSaveRestorePacket(), DecodeVps3OverlaySettings(), DecodeVps3PiPSettings(), DecodeVps3VersionPacket(), FormCameraDefinitionsPacket(), FormCanPassthroughPacket(), FormEstabSettings(), FormGimbalAxisSettingsPacket(), FormGimbalCameraAlignPacket(), FormGimbalFilterPacket(), FormGimbalFLIRConfigurationPacket(), FormGimbalGPSLeverArmPacket(), FormGimbalIRCamConfigurationPacket(), FormGimbalIRCamSaveRestorePacket(), FormGimbalKLVDetailsPacket(), FormGimbalLasersInstalledPacket(), FormGimbalMagCalPacket(), FormGimbalRetractorConfigurationPacket(), FormGimbalSensorConfigPacket(), FormGimbalSerialInterfacePacket(), FormGimbalTrackerSettingsAdvancedCommand(), FormGimbalWaterMarkPacket(), FormHdControlSettings(), FormLensCalFocusPacket(), FormLensPrefocusPacket(), FormMC_AxisParamPacket(), FormMC_LimitsPacket(), FormMC_MotionCalibrationParamPacket(), FormMISBSettingsPacket(), FormSPOIPathSettings(), FormSuCsxConfigurationPacket(), FormSuCsxSaveRestorePacket(), FormVps3OverlaySettings(), and FormVps3PiPSettings().
#define GIMBAL_STATUS_INFORMATION_GROUP 0x28
Group number for status packets.
Referenced by DecodeGimbalDiagnosticsPacket(), DecodeGimbalResetReportPacket(), DecodeGimbalUserWarningPacket(), DecodeMbResetReportPacket(), DecodeMbUserWarningPacket(), DecodeMicroblazeDiagnosticsPacket(), DecodeMotionCtrlDiagnosticsPacket(), DecodeVps3DiagnosticsPacket(), DecodeVps3ResetReportPacket(), and DecodeVps3UserWarningPacket().
#define GIMBAL_TELEMETRY_2_GIMBAL_PKTTYPE 0x48
Expanded gimbal telemetry packet as of 230.
Referenced by DecodeGimbalTelemetryPacket().
#define GIMBAL_TELEMETRY_GIMBAL_PKTTYPE 0x47
Gimbal telemetry packet type.
Referenced by DecodeGimbalTelemetryPacket().
#define GIMBAL_WATERMARK_DATA_PKTTYPE 0x5A
Packet type for the vps watermark data.
Referenced by DecodeGimbalWaterMarkPacket(), and FormGimbalWaterMarkPacket().
#define GPS_LEVER_ARM_GIMBAL_PKTTYPE 0x06
Packet type for GPS lever arm.
Referenced by DecodeGimbalGPSLeverArmPacket(), and FormGimbalGPSLeverArmPacket().
#define GYRO_ZERO_CMD_GIMBAL_PKTTYPE 0x40
Packet type for gyro zero command.
#define HD_CONTROL_SETTINGS_PKTTYPE 0x41
Packet type for the HD control modes of the VPS.
Referenced by DecodeHdControlSettings(), and FormHdControlSettings().
#define HOST_ATTITUDE_GIMBAL_PKTTYPE 0x42
Packet type for host supplied gimbal mount attitude data.
Referenced by FormGimbalHostAttitudePacket().
#define HOST_GPS_DATA_GIMBAL_PKTTYPE 0x10
Packet type for host supplied GPS data.
Referenced by FormGimbalHostGPSPacket().
#define HOST_SENSOR_GIMBAL_PKTTYPE 0x41
Packet type for host supplied gimbal mount body rates.
Referenced by FormGimbalHostSensorPacket().
#define INITIAL_HEADING_GIMBAL_PKTTYPE 0x90
Packet type for initializaing INS heading.
Referenced by FormGimbalInitialHeadingPacket().
#define INTER_PROCESSOR_GROUP 0xE0
Group number for packets between processor in the gimbal.
#define IRCAM_CONFIGURATION_GIMBAL_PKTTYPE 0x22
Packet type for configuring a T500 IR camera.
Referenced by DecodeGimbalIRCamConfigurationPacket(), and FormGimbalIRCamConfigurationPacket().
#define IRCAM_SAVE_RESTORE_GIMBAL_PKTTYPE 0x23
Packet type for saving/restoring the T500 IR startup configuration.
Referenced by DecodeGimbalIRCamSaveRestorePacket(), and FormGimbalIRCamSaveRestorePacket().
#define KLV_DETAILS_GIMBAL_PKTTYPE 0x12
Packet type for configuration KLV data.
Referenced by DecodeGimbalKLVDetailsPacket(), and FormGimbalKLVDetailsPacket().
#define LASER_ARM_565_TO_MB_PKTTYPE 0x09
Packet type for laser arming.
#define LASER_ARM_CMD_GIMBAL_PKTTYPE 0x44
Command to arm a laser.
Referenced by DecodeGimbalLaserArmCmdPacket(), and FormGimbalLaserArmCmdPacket().
#define LASER_FIRE_565_TO_MB_PKTTYPE 0x0A
Packet type for laser firing.
#define LASER_FIRE_CMD_GIMBAL_PKTTYPE 0x45
Command to fire a laser.
Referenced by DecodeGimbalLaserFireCmdPacket(), and FormGimbalLaserFireCmdPacket().
#define LASER_KEEP_ALIVE_565_TO_MB_PKTTYPE 0x08
Packet type for laser heartbeat message.
#define LASER_PASSWORD_ENABLER_PKTTYPE 0x4C
Overall Laser ops enabler - pswd is the S/N of the gimbal.
Referenced by DecodeLaserEnablePswdPacket(), and FormLaserEnablePswdPacket().
#define LASER_RF_DATA_MB_TO_565 0x0B
Packet type for laser range fider data.
#define LASER_SAFETY_STATUS_PKTTYPE 0x49
Laser safety and safety status.
Referenced by DecodeLaserSafetyStatus(), and FormLaserSafetyStatus().
#define LASER_STATUS_MB_TO_565_PKTTYPE 0x07
Packet type for reporting laser status.
#define LASER_WATCHDOG_PKTTYPE 0x4B
Laser watchdog reminder to user.
Referenced by DecodeLaserWatchdogPacket(), and FormLaserWatchdogPacket().
#define LASERS_INSTALLED_GIMBAL_PKTTYPE 0x08
Packet type for setup/query of installed lasers.
Referenced by CommBase_RequestGimbalLaserSetupPacket(), DecodeGimbalLasersInstalledPacket(), and FormGimbalLasersInstalledPacket().
#define LEGACY_CAMERA_CMD_GIMBAL_PKTTYPE 0x81
Legacy camera command packet type.
#define LENS_CAL_FOCUS_CONFIGURATION 0x28
Packet type for setup/query of lens cal table temperature and focus positions.
Referenced by DecodeLensCalFocusPacket(), and FormLensCalFocusPacket().
#define LENS_CAL_ZOOM_CONFIGURATION 0x27
Packet type for setup/query of lens cal table zoom positions.
Referenced by DecodeLensPrefocusPacket().
#define LENS_CONTROL_VERSION_PKTTYPE 0x19
Packet type for the lens controller version information.
Referenced by DecodeLensControlVersionPacket().
#define LENS_PREFOCUS_CONFIGURATION 0x16
Packet type for setup/query of lens pre-focus data.
Referenced by DecodeLensPrefocusPacket(), and FormLensPrefocusPacket().
#define MAG_CAL_GIMBAL_PKTTYPE 0x0C
Packet type for magnetometer calibration data.
Referenced by DecodeGimbalMagCalPacket(), and FormGimbalMagCalPacket().
#define MAX_SPOI_PATH_PTS 39
Max number of points that can be stored in RAM.
Referenced by DecodeSPOIPathPointData(), and FormSPOIPathPointData().
#define MB_ENABLE_LENS_DIAGNOSTICS 0x02
Used to command the Microblaze to enable diagnostic outputs for a specifed lens.
Referenced by FormSetLensDiagnosticsPacket().
#define MB_LENS_COMMAND_PKTTYPE 0x01
Command the lens position or a re-initialization.
Referenced by DecodeLensDevCommandPacket(), and FormLensDevCommandPacket().
#define MB_LENS_DIAGNOSTIC_PKTTYPE 0x03
Report of Microblaze lens diagnostic data (when enabled).
Referenced by DecodeLensDiagnosticsPacket().
#define MB_LENS_REGISTER_PKTTYPE 0x00
Command to read/write a register for a lens controlled through the Microblaze.
Referenced by DecodeLensRegisterPacket(), and FormLensRegisterPacket().
#define MC_BIQUAD_PARAMS 0x50
Development/test packet.
#define MC_BIST_STATUS 0xA4
Packet type for reporting BIST status.
#define MC_DEBUG_PARAMS 0x51
Development/test packet.
#define MC_DIAGNOSTIC_PKTTYPE 0x32
Packet type for sending a Motion Control Diagnostics packet.
Referenced by DecodeMotionCtrlDiagnosticsPacket().
#define MC_DSP_FLASH_DATA_ACK 0x42
Identify an image data packet that expects an ack.
#define MC_DSP_FLASH_DATA_NO_ACK 0x41
Identify an image data packet that does not require an ack.
#define MC_DSP_FLASH_DOWNLOAD_END 0x44
Inform the MC FFB that the entire image has been sent.
#define MC_DSP_FLASH_DOWNLOAD_START 0x40
Inform the MC FFB that image packets are forthcoming. If received in the application goes to FFB.
#define MC_DSP_FLASH_ERASE 0x45
Command the MC to begin the erase process.
#define MC_DSP_FLASH_RESPONSE 0x43
Identify a response packet from the FFB. This packet includes a null terminated data message.
#define MC_DSP_FLASH_STROBE 0x46
Identify an FFB strobe packet. This packet includes FFB version info as a null terminated data message.
#define MC_PROGRAMMING_AND_DEV_GROUP 0xF9
Group number for Motion Control programming and dev packets.
#define MICROBLAZE_APP_VERSION_PKTTYPE 0x57
Packet type for the MB application version information.
Referenced by DecodeMbAppVersionPacket().
#define MICROBLAZE_BUILT_IN_TEST_PKTTYPE 0x01
Packet type for starting built-in tests.
#define MICROBLAZE_DEVELOPMENT_GROUP 0xF7
Group number for Microblaze development work.
Referenced by DecodeLensDevCommandPacket(), DecodeLensDiagnosticsPacket(), DecodeLensRegisterPacket(), FormLensDevCommandPacket(), FormLensRegisterPacket(), and FormSetLensDiagnosticsPacket().
#define MICROBLAZE_DIAGNOSTIC_PKTTYPE 0x12
Packet type for sending a MB Diagnostics packet.
Referenced by DecodeMicroblazeDiagnosticsPacket().
#define MICROBLAZE_FLASH_DOWNLOAD_AND_ACK 0x42
Identify an image data packet that expects an ack.
#define MICROBLAZE_FLASH_DOWNLOAD_END 0x44
Inform the MB FFB that the entire image has been sent.
#define MICROBLAZE_FLASH_DOWNLOAD_NO_ACK 0x41
Identify an image data packet that does not require an ack.
#define MICROBLAZE_FLASH_DOWNLOAD_START 0x40
Inform the MB FFB that image packets are forthcoming. If received in the application sends to FFB.
#define MICROBLAZE_FLASH_ERASE 0x45
Command the MB to begin the erase process.
#define MICROBLAZE_FLASH_RESPONSE 0x43
Identify a response packet from the FFB. This packet includes a null terminated data message.
#define MICROBLAZE_FLASH_STROBE 0x46
Identify an FFB strobe packet. This packet includes FFB version info as a null terminated data message.
#define MICROBLAZE_PROGRAMMING_GROUP 0xF8
Group number for Microblaze flash programming.
#define MICROBLAZE_RESET_REPORT 0x11
Packet type for sending a MB reset report.
Referenced by DecodeMbResetReportPacket().
#define MICROBLAZE_TO_VPS_DIGITAL_ZOOM_PKTTYPE 0x02
Packet type for commanding digital zoom.
#define MICROBLAZE_TO_VPS_STROBE_PKTTYPE 0x04
Packet type for providing data to VPS.
#define MICROBLAZE_WARN_USER 0x10
Packet type for sending a human readable warning message from the MB.
Referenced by DecodeMbUserWarningPacket().
#define MISB_SETTINGS_PKTTYPE 0x52
Packet type for the MISB settings.
Referenced by DecodeMISBSettingsPacket(), and FormMISBSettingsPacket().
#define MOTION_CALIBRATION_PARAMS 0xA4
Packet type for motion control calibration settings.
Referenced by DecodeMC_MotionCalibrationParamPacket(), and FormMC_MotionCalibrationParamPacket().
#define MOTION_CALIBRATION_PARAMS_FACTORY 0xA5
Packet type for motion control factory calibration settings.
Referenced by DecodeMC_MotionCalibrationParamPacket(), and FormMC_MotionCalibrationParamPacket().
#define MOTION_CONTROL_MODE 0xA1
Packet type for setting/reporting motion control mode.
#define MOTION_CONTROL_PARAMS 0xA2
Packet type for motion control settings.
#define MOTION_CONTROL_PARAMS_FACTORY 0xA3
Packet type for motion control factory settings.
#define MOTION_CONTROLLER_BOOTLOADER_VERSION 0xA0
Packet type for motion controller bootloader version information.
Referenced by DecodeMotionCtrlVersionPacket().
#define MOTION_CONTROLLER_VERSION 0xA1
Packet type for motion controller version information.
Referenced by DecodeMotionCtrlVersionPacket().
#define MOTOR_DRIVE_ENABLE_GIMBAL_PKTTYPE 0x70
Command to enable/disable the motor drive.
#define OVERLAY_SETTINGS_PKTTYPE 0x42
Packet type for the overlay settings.
Referenced by DecodeVps3OverlaySettings(), and FormVps3OverlaySettings().
#define PICTURE_IN_PICTURE_SETTINGS_PKTTYPE 0x43
Packet type for the picture in picture settings.
Referenced by DecodeVps3PiPSettings(), and FormVps3PiPSettings().
#define RADIO_SETUP_GIMBAL_PKTTYPE 0x60
Command to control the radio setup.
Referenced by DecodeGimbalRadioSettings(), and FormGimbalRadioSettings().
#define RADIO_SETUP_VGS_PKTTYPE 0x02
Packet type for changing radio setup of VGS.
Referenced by DecodeVGSRadioSettings(), and FormVGSRadioSettings().
#define RESET_REPORT_GIMBAL_PKTTYPE 0x01
Packet type for sending a gimbal reset report.
Referenced by DecodeGimbalResetReportPacket().
#define RETRACT_DEPLOY_CMD_GIMBAL_PKTTYPE 0x43
Command retract or deploy of 3AX.
Referenced by DecodeGimbalRetractDeployCmdPacket(), and FormGimbalRetractDeployCmdPacket().
#define RETRACTOR_CONFIG_GIMBAL_PKTTYPE 0x21
Packet type for setup/query of retractor configuration.
Referenced by DecodeGimbalRetractorConfigurationPacket(), and FormGimbalRetractorConfigurationPacket().
#define RIG_TEST_CMD_GIMBAL_PKTTYPE 0xFE
Rig test command.
Referenced by DecodeGimbalRigTestCmdPacket(), and FormGimbalRigTestCmdPacket().
#define SENSOR_ACQ_PARAMS 0xAA
Packet type for motion control acq settings.
#define SENSOR_ACQ_PARAMS_FACTORY 0xAB
Packet type for motion control acq factory settings.
#define SENSOR_CONFIGURATION_GIMBAL_PKTTYPE 0x11
Packet type for sensor configuration data.
Referenced by DecodeGimbalSensorConfigPacket(), and FormGimbalSensorConfigPacket().
#define SENSOR_FILTER_GIMBAL_PKTTYPE 0x01
Packet type for changing sensor filter settings.
Referenced by DecodeGimbalFilterPacket(), and FormGimbalFilterPacket().
#define SERIAL_INTERFACE_GIMBAL_PKTTYPE 0x00
Packet type for changing serial interface setup.
Referenced by DecodeGimbalSerialInterfacePacket(), and FormGimbalSerialInterfacePacket().
#define SET_ANTENNA_YAW_VGS_PKTTYPE 0x00
Packet type for changing the antenna yaw offset.
Referenced by DecodeVGSAntennaYaw(), and FormVGSAntennaYaw().
#define SET_AXIS_POS_RATE 0xA2
Packet type for commanding motion control position or rate.
#define SPOI_CMD_GIMBAL_PKTTYPE 0x40
Packet type for sensor point of interest command.
Referenced by CommBase_RequestGimbalSPOICmdPacket(), DecodeGimbalSPOICmdPacket(), and FormGimbalSPOICmdPacket().
#define SPOI_PATH_CMD_PKTTYPE 0x46
Command SPOI path following.
#define SPOI_PATH_NEAREST_CMD_PKTTYPE 0x47
Command SPOI to nearest point on the current path.
#define SPOI_PATH_PARAM_PKTTYPE 0x0A
Packet type for configuring the SPOI Path Navigator.
Referenced by DecodeSPOIPathSettings(), and FormSPOIPathSettings().
#define SPOI_PATH_POINT_DATA_PKTTYPE 0x45
SPOI path points data.
Referenced by DecodeSPOIPathPointData(), and FormSPOIPathPointData().
#define STAB_T2_SET_DEV_PKTTYPE 0x18
Packet type for commanding changes to stabilization settings.
Referenced by DecodeStabDevT2Settings(), and FormStabDevT2Settings().
#define STAB_TELEM_DEV_PKTTYPE 0x10
Packet type for development telemetry for stabilization analysis.
Referenced by DecodeGimbalStabDevTelemetry().
#define STABILITY_DEV_PKTTYPE 0x30
Packet type for sending FOG board stability data.
#define SUCSX_CONFIGURATION_GIMBAL_PKTTYPE 0x25
Packet type for configuring a SU CSX Camera.
Referenced by DecodeSuCsxConfigurationPacket(), and FormSuCsxConfigurationPacket().
#define SUCSX_SAVE_RESTORE_GIMBAL_PKTTYPE 0x26
Packet type for saving/restoring the SU CSX camera startup configuration.
Referenced by DecodeSuCsxSaveRestorePacket(), and FormSuCsxSaveRestorePacket().
#define SYMBOLOGY_CMD_GIMBAL_PKTTYPE 0x51
Command to control the video symbology.
#define SYSTEM_VERSION_2_GIMBAL_PKTTYPE 0x04
Packet type for newer system version information.
Referenced by DecodeGimbalVersion2Packet().
#define SYSTEM_VERSION_GIMBAL_PKTTYPE 0x03
Packet type for system version information (deprecated in 230)
Referenced by DecodeGimbalVersionPacket().
#define TARGET_LOCATION_DATA_GIMBAL_PKTTYPE 0x42
Target location (from gimbal)
#define TARGET_LOCATION_ESTIMATE_GIMBAL_PKTTYPE 0x43
Estimate of target location (to gimbal)
Referenced by DecodeGimbalTargetLocationEstimate(), and FormGimbalTargetLocationEstimate().
#define TELEMETRY_VGS_PKTTYPE 0x03
Packet type for video grund station telemetry.
Referenced by DecodeVGSTelemetry().
#define TRACKER_ADV_CMD_GIMBAL_PKTTYPE 0x09
Packet type for setup of tracker (advanced settings)
Referenced by DecodeGimbalTrackerSettingsAdvancedCommand(), and FormGimbalTrackerSettingsAdvancedCommand().
#define TRACKER_CMD_GIMBAL_PKTTYPE 0x50
Command to control the video tracker.
Referenced by DecodeGimbalTrackCommand(), and FormGimbalTrackCommand().
#define TRACKING_DATA_GIMBAL_PKTTYPE 0xA0
Packet type for tracking data to an autopilot.
Referenced by DecodeGimbalTrackingData(), and FormGimbalTrackingData().
#define USER_WARNING_GIMBAL_PKTTYPE 0x00
Packet type for sending a human readable warning message.
Referenced by DecodeGimbalUserWarningPacket().
#define VGS_COMMAND_AND_CONTROL_GROUP 0xF0
Group number for video ground station packets.
Referenced by DecodeVGSAntennaYaw(), DecodeVGSRadioSettings(), DecodeVGSTelemetry(), FormVGSAntennaCommand(), FormVGSAntennaYaw(), and FormVGSRadioSettings().
#define VIBRATION_DATA_GIMBAL_PKTTYPE 0x80
Packet type for vibration data from gimbal.
Referenced by DecodeGimbalRawVibrationPacket().
#define VIDEO_ENHANCEMENT_SETTINGS_PKTTYPE 0x58
Packet type for the video enhancement settings.
#define VIDEO_TRK_DEV_PKTTYPE 0x40
Packet type for sending out video track diagnostic data.
#define VPS3_VERSION_PKTTYPE 0x40
Packet type for the VPS3 version information.
Referenced by DecodeVps3VersionPacket().
#define VPS_DEVELOPMENT_GROUP 0xFF
Group number for VPS development work (flash programming)
#define VPS_DIAGNOSTIC_PKTTYPE 0x22
Packet type for sending a VPS Diagnostics packet.
Referenced by DecodeVps3DiagnosticsPacket().
#define VPS_GROUP_DEPRECATED 0xFE
Group number for VPS work - deprecated in 2.2.3.
#define VPS_PROGRAM_IN_PKTTYPE 0x00
Packet type for sending programming data from host through TASE and into VPS.
#define VPS_PROGRAM_OUT_PKTTYPE 0x01
Packet type for sending programming data from VPS through TASE and into host.
#define VPS_PROGRAMMING_GROUP 0xFD
Group number for VPS programming packets.
#define VPS_RESET_REPORT_PKTTYPE 0x21
Packet type for sending a vps reset report.
Referenced by DecodeVps3ResetReportPacket().
#define VPS_TO_MICROBLAZE_STROBE_PKTTYPE 0x05
Packet type for getting data from VPS.
#define VPS_USER_WARNING_PKTTYPE 0x20
Packet type for sending a human readable warning message from the VPS.
Referenced by DecodeVps3UserWarningPacket().
Enumeration Type Documentation
anonymous enum
Discrete SPOI stepping modes.
Enumerator
STEP_SPOI_BY_DIST
Discrete SPOI steps at fixed distance intervals.
STEP_SPOI_BY_POINTS
Discrete SPOI steps at the path points.
STEP_SPOI_BY_TIME
Discrete SPOI steps at fixed time intervals.
STEP_RESERVED0
Not yet implemented for BY_TIME_WITH_POINTS.
STEP_SPOI_JOYSTICK
Joystick controlled stepping.
STEP_SPOI_AUTO_SCAN
Stepping by specified rate scaled by the FOV.
anonymous enum
Retractor enumerations.
Enumerator
NO_RETRACTOR
No retractor installed.
THREEAX_RETRACTOR
3AX retractor for TASE150 or TASE200
ACR_RETRACTOR
ACR retractor for TASE150 or TASE200.
ARCTURUS_RETRACTOR
Arcturus sensor safe retractor.
VTRACT1_RETRACTOR
VTRACT1 retractor for TASE300 or TASE400.
VTRACT2_RETRACTOR
VTRACT2 retractor for TASE300 or TASE400.
enum CameraProtocolTypes
Enumerator
CAMERA_TYPE_NO_CAMERA
No camera installed.
CAMERA_TYPE_DUMB_CAMERA
A camera with no protocol to talk to.
CAMERA_TYPE_SONY
Block cameras from Sony that use the VISCA protocol.
CAMERA_TYPE_SONY_XCL
Camera Link camera from Sony XCL-C130C Narrow Angle.
CAMERA_TYPE_PHOTON
LWIR camera from FLIR that uses photon protocol.
CAMERA_TYPE_TAU
LWIR camera from FLIR that uses tau protocol (similar to photon)
CAMERA_TYPE_HRC
MWIR camera from FLIR that similar to photon/tau protocol.
CAMERA_TYPE_SWIRTAU
SWIR camera from FLIR that uses a totally different protocol (#&!)
CAMERA_TYPE_THERMO
LWIR camera from thermoteknix.
CAMERA_TYPE_PROSILICA
Prosilica camera.
CAMERA_TYPE_320_KTX
Sensors unlimited SWIR camera.
CAMERA_TYPE_640_KTX
Sensors unlimited SWIR camera, 640.
CAMERA_TYPE_SU_JSX
Sensors unlimited SWIR camera, High Resolution, Mil-Rugged, InGaAs.
CAMERA_TYPE_IRCAM
MWIR Camera with AgileCore Controller from IR CAMERA.
CAMERA_TYPE_640_CSX
Sensors unlimited SWIR camera, High Sensitivity, Mil-Rugged, Small SWap, InGaAs.
CAMERA_TYPE_VPS_MIN
First index of camera controlled by the VPS.
CAMERA_TYPE_VPS_FLEA3C
Point Grey or Baumer GigE color cam.
CAMERA_TYPE_VPS_BLACKFLY_345
Point Grey BlackFly GigE color cam 3.45 um pixel size.
CAMERA_TYPE_VPS_BLACKFLY_220
Point Grey BlackFly GigE color cam 2.20 um pixel size.
enum EStabModes_t
Estab settings.
enum ExposureMode_t
Exposure mode enumerations.
Enumerator
EXPOSURE_FULL_AUTO
Automatic exposure mode.
EXPOSURE_SHUTTER_PRIORITY
Shutter priority exposure mode.
EXPOSURE_BRIGHT
Bright exposure mode.
NUM_EXPOSURE_MODES
Number of exposure modes.
EXPOSURE_NO_CHANGE
No change to exposure mode.
enum FocusMode_t
Focus enumerations for GimbalTelemetryData_t.FocusMode.
Enumerator
AUTO_FOCUS
Automatic focus.
FOCUS_ONCE
Automatic focus and then stop auto-focus.
INFINITE_FOCUS
Infinite focus.
MANUAL_FOCUS
manual focus
enum GimbalINSAidingtypes
Types of aiding that can be applied to a gimbal INS.
Enumerator
NO_GIMBAL_INS_AID
No aiding, pure GPS/INS.
MAG_HEADING_GIMBAL_INS_AID
Magnetometer supplied heading as an aid to INS.
EXT_HEADING_GIMBAL_INS_AID
Externally supplied heading as an aid to INS.
VPS_HEADING_GIMBAL_INS_AID
VPS computed heading as an aid to INS.
EXT_ATTITUDE_GIMBAL_INS_AID
Externally supplied attitude as an aid to INS.
NOVATEL_ALIGN_INS_AID
Novatel Align suppplied heading as an aid to INS.
enum GimbalModes
Enumerator
GIMBAL_VELOCITY_FEEDBACK
Holding a fixed gimbal rate.
GIMBAL_POSITION_FEEDBACK
Holding a fixed gimbal angle.
GIMBAL_SPOI_FEEDBACK
Holding a fixed ground location.
GIMBAL_VIDEO_ST_RATE_FEEDBACK
Holding a fixed video scene with rate mode.
GIMBAL_VIDEO_TT_RATE_FEEDBACK
Holding a fixed video target with rate mode.
GIMBAL_VIDEO_ST_SPOI_FEEDBACK
Holding a fixed video scene with SPOI mode.
GIMBAL_VIDEO_TT_SPOI_FEEDBACK
Holding a fixed video target with SPOI mode.
GIMBAL_SPOI_PATH_MODE
The SPOI is following a fixed path in the inertial space.
GIMBAL_SCAN_ELLIPSE_MODE
Holding a rate around an elliptical path.
GIMBAL_RIG_TEST_MODE
Performing rig test.
GIMBAL_PAN_INIT_MODE
Driving pan axis to find pan sync.
GIMBAL_TILT_MAX_INIT_MODE
Driving tilt axis to find min limit.
GIMBAL_TILT_MIN_INIT_MODE
Driving tilt axis to find max limit.
GIMBAL_POS_INIT_MODE
Driving pan and tilt to the initial position.
GIMBAL_DETECT_RETRACT_MODE
Looking for the retract at powerup.
GIMBAL_WAIT_FOR_DEPLOY_MODE
Waiting to move until retractor says OK.
enum GimbalProtocolTypes
Types of communications protocols.
Enumerator
NO_GIMBAL_PROTOCOL
No communications.
GIMBAL_COMM
Standard gimbal communications.
GIMBAL_KLV
KLV meta data output.
GIMBAL_VPS
Video processing communications.
GIMBAL_HMR_2300
Connection to Honeywell HMR2300.
GIMBAL_HMR_3400
Connection to Honeywell HMR3400.
GIMBAL_NOVATEL
Connection to Novatel GPS.
enum HDControlSettings_t
HD control modes on VPS3.
enum LaserClasses
Laser classifications.
enum LaserProtocol
Laser protocols.
Enumerator
LASER_TYPE_DUMB_LASER
A laser with no protocol to talk to or the default when no laser is installed.
LASER_TYPE_FLIR_CLI_30
FLIR CLI-30 laser communication protocol.
enum LaserRangeFinderStatus
Laser rangefinder status.
Enumerator
LRF_STATUS_STANDBYE
The laser range finder is in standby and not firing.
LRF_STATUS_FIRING
The laser range finder is firing for range with no measurement errors.
LRF_STATUS_BORE_SIGHTING
The laser range finder is in continuous output mode for bore sighting.
LRF_STATUS_ERROR_ACCURACY
The laser range finder is firing for range with error code A: running out of distance accuracy.
LRF_STATUS_ERROR_TEMP
The laser range finder is firing for range with error code T: running out of temperature spec.
LRF_STATUS_ERROR_ACC_TEMP
The laser range finder is firing for range with error code C: running out of distance accuracy and temp spec.
LRF_STATUS_ERROR_RANGE
The laser range finder is firing for range with error code R: a range error occurred and result is invalid.
LRF_STATUS_ERROR_CHECKSUM
The laser range finder is firing for range but all measurements failed their checksum.
enum LaserSafetyFlags
Laser Safety Flags.
Enumerator
LOST_COMMS_AP
Lost comms between gimbal & autopilot.
LOST_COMMS_GND
Lost comms between autopilot & ground.
ON_GROUND
Aircraft on ground.
POS_ELEV_ANGLE
Positive elevation angle.
WATCHDOG_TIMER
Laser been firing continuously with no power change from user.
MIN_AGL
Laser minimum AGL restriction not met (gimbal too low).
GLOBAL_PSWD
Correct Laser global password not received at gimbal (gimbal serial number).
AGL_INVALID
for some reason, we could not calculate the gimbal's AGL.
enum LaserTypes
Types of lasers.
Enumerator
NO_LASER
No laser installed.
LASER_POINTER
Laser is a pointer. BUT: call them illuminators as well.
LASER_ILLUMINATOR
Laser is an illuminator.
LASER_RANGER
Laser is a range finder.
LASER_DESIGNATOR
Laser is a designator.
enum LensControlConfig
Enumerator
LENS_CONFIG_T300_LWIR_4680
T300 Delta Payload (obsolete)
LENS_CONFIG_T300_NG_LWIR_4680
T300 Next Gen Delta Payload (obsolete)
LENS_CONFIG_T400_MWIR_4680
T400 MWIR PIC18F4680.
LENS_CONFIG_T400_MWIR_66K80
T400 MWIR PIC18F66K80(never produced)
LENS_CONFIG_T350_LWIR_66K80
T350 LWIR PIC18F66K80.
LENS_CONFIG_T400_LRS_66K80
T400 MWIR and LRS PIC18F66K80.
LENS_CONFIG_T400_DXR_66K80
T400 DXR PIC18F66K80.
LENS_CONFIG_T400_DNXR_4680
T400 DNXR PIC18F4680.
LENS_CONFIG_NONE
No lens control exists for the hardware (e.g. T100, T150, T200)
enum LensTypes
Enumerator
LENS_TYPE_NO_LENS
No lens.
LENS_TYPE_GENERIC_FIXED
Generic fixed focal length lens.
LENS_TYPE_GENERIC_CZOOM
Generic continuous zoom.
LENS_TYPE_LENS_DOUBLER
Lens doubler optic.
LENS_TYPE_CAMERA_SPECIFIED
Lens integrated with camera (a al Sony)
LENS_TYPE_CCT_MWIR_CZOOM
MWIR continuous zoom lens.
LENS_TYPE_CCT_LWIR_DZOOM
LWIR discrete zoom lens.
LENS_TYPE_CCT_SWIR_CAT
SWIR catadioptric lens.
LENS_TYPE_SPOTTER
3rd bay spotter lens (LRS)
LENS_TYPE_SUPER_SPOTTER
super spotter lens (DXR)
LENS_TYPE_CCT_HD_MWIR_CZOOM
MWIR lens.
LENS_TYPE_CCT_HD_VIS_SWIR_CZOOM
SWIR/NFOV VIS dual aperture lens.
LENS_TYPE_CCT_SWIR_FIXED
SWIR fixed lens.
enum MbReset_t
Microblaze reset source data.
Enumerator
MB_RESET_POWER
Power-on reset.
MB_RESET_WATCHDOG
Watchdog reset.
MB_RESET_UNKNOWN
Unknown source.
enum OutputTypes
Enumerator
VIDEO_OUTPUT_NONE
No video output.
VIDEO_OUTPUT_NTSC
NTSC analog output.
VIDEO_OUTPUT_PAL
PAL analog output.
VIDEO_OUTPUT_HD_720I
720i
VIDEO_OUTPUT_HD_720P
720p
VIDEO_OUTPUT_HD_1080I
1080i
VIDEO_OUTPUT_HD_1080P
1080p
VIDEO_OUTPUT_CUSTOM
Not a standard output type.
VIDEO_OUTPUT_NTSC_GIGE
NTSC GigE output to VPS FPGA daughtercard.
enum SonyCameraTypes
Enumerator
SONY_FCB_EX480B
18x optical zoom, NTSC 0x24
SONY_FCB_EX480BP
18x optical zoom, PAL 0x25
SONY_FCB_EX48B
18x optical zoom, NTSC 0x26
SONY_FCB_EX48BP
18x optical zoom, PAL 0x27
SONY_FCB_IX11
10x optical zoom, NTSC
SONY_FCB_IX11P
10x optical zoom, PAL
SONY_FCB_EX980
26x optical zoom, NTSC 0x30
SONY_FCB_EX980P
26x optical zoom, PAL 0x31
SONY_FCB_EX980S
26x optical zoom, Stabilized, NTSC 0x32
SONY_FCB_EX980SP
26x optical zoom, Stabilized, PAL 0x33
SONY_FCB_EX480C
18x optical zoom, NTSC 0x34
SONY_FCB_EX480CP
18x optical zoom, PAL 0x35
SONY_FCB_EX45MC
18x optical zoom, NTSC 0x3A
SONY_FCB_EX45MCC
18x optical zoom, NTSC 0x3B
SONY_FCB_EX1000
36x optical zoom, NTSC 0x42
SONY_FCB_EX1000P
36x optical zoom, PAL 0x43
SONY_FCB_EX1010
36x optical zoom, NTSC 0x44
SONY_FCB_EX1010P
36x optical zoom, PAL 0x45
SONY_FCB_H10
10x optical zoom, high definition video selectable
SONY_FCB_H11
10x optical zoom, high definition video selectable
SONY_FCB_EX1020
36x optical zoom, NTSC progressive 0x50
SONY_FCB_EX1020P
36x optical zoom, PAL progressive 0x51
SONY_FCB_EH4300
20x optical zoom, CMOS HD
SONY_FCB_EH6300
20x optical zoom, CMOS HD
SONY_FCB_EH6500
30x optical zoom, CMOS HD
SONY_FCB_EV7500
30x optical zoom, CMOS HD
SONY_FCB_EV7100
10x optical zoom, CMOS HD
enum TypeOfSensor
Enumerator
NO_SENSOR
No sensor on this channel/index.
SENSOR_EO
An E/O sensor (daylight)
SENSOR_LWIR_WHITE
Long wave infrared in white-hot mode.
SENSOR_LWIR_BLACK
Long wave infrared in black-hot mode.
SENSOR_MWIR_WHITE
Mid wave infrared in white-hot mode.
SENSOR_MWIR_BLACK
Mid wave infrared in black-hot mode.
SENSOR_SWIR
Short wave infrared.
SENSOR_EO_NO_ZOOM
An E/O w/o zoom.
SENSOR_EO_SPOTTER
An E/O spotter sensor.
NUM_SENSOR_TYPES
Total number of sensor types.
enum VPS3PosFormat_t
VPS3 position format.
enum Vps3Reset_t
VPS3 reset source data.
Enumerator
VPS3_RESET_POWER
Power-on reset.
VPS3_RESET_WATCHDOG
Watchdog reset.
VPS3_RESET_UNKNOWN
Unknown source.
Function Documentation
UInt16 CalcGimbalPacketChecksum (const GimbalPkt_t * pPkt)
Calculate a gimbal packet checksum.
Calculate the check sum for the passed gimbal packet. The checksum is is based upon an unsigned 16-bit accumulation of all bytes in the packet, excluding the checksum bytes.
Parameters
pPkt points to a gimbal packet structure.
Returns
The checksum for the packet.
References GimbalPkt_t::Group, GimbalPkt_t::Size, GimbalPkt_t::Sync1, GimbalPkt_t::Sync2, and GimbalPkt_t::Sync3.
Referenced by ChecksumGimbalPacket(), LookForGimbalPacket(), LookForGimbalPacketInByte(), and LookForGimbalPacketInQueue().
void ChecksumGimbalPacket (GimbalPkt_t * pPkt)
Calculate and fill out a gimbal packet checksum.
Form the check sum for the passed gimbal packet
Parameters
pPkt points to a gimbal packet structure which is complete except for the checksum.
References CalcGimbalPacketChecksum(), GimbalPkt_t::Data, and GimbalPkt_t::Size.
Referenced by CommBase_RequestGimbalCameraAlignPacket(), CommBase_RequestGimbalCameraCmdPacket(), and FinishGimbalPacket().
BOOL DecodeCameraDefinitionsPacket (const GimbalPkt_t * pPkt, CameraDefinition_t Cam[NUM_CAMERAS], BOOL Received[NUM_CAMERAS])
Interpret a camera definitions packet.
Interpret a camera definition packet, which has up to three cameras defined in it.
Parameters
pPkt is the packet to interpret.
Cam receives the camera definitions.
Received receives TRUE for each camera that was defined (0, 1, 2, etc)
Returns
TRUE if the packet is valid and contained at least one camera.
References CAMERA_DEFINITION_GIMBAL_PKTTYPE, ConvertFromLegacyCameraType(), GimbalPkt_t::Data, DataToUInt16(), FACTORY_CAMERA_DEFINITION_GIMBAL_PKTTYPE, GIMBAL_SETUP_GROUP, GimbalPkt_t::Group, NUM_CAMERAS, GimbalPkt_t::PktType, and GimbalPkt_t::Size.
BOOL DecodeCanPassthroughPacket (const GimbalPkt_t * pPkt, UInt16 * pID, UInt8 Data[8], UInt8 * pLength)
Decode a packet containing a CAN frame received from or to be sent to CAN-B.
Form a CAN-B passthrough packet.
Parameters
pPkt Pointer to the packet data space
pID Space to receive an 11-bit standard CAN frame identifier.
Data CAN frame data payload bytes, up to eight.
pLength Space to receive the number of valid bytes contained in Data.
References CAN_PASSTHROUGH_GIMBAL_PKTTYPE, GimbalPkt_t::Data, DataToUInt16(), GIMBAL_SETUP_GROUP, GimbalPkt_t::Group, GimbalPkt_t::PktType, and GimbalPkt_t::Size.
BOOL DecodeEstabSettings (const GimbalPkt_t * pPkt, EStabModes_t * pMode)
Decode the estab control settings.
Decode an estab settings packet which defines how the electronic stabilization works
Parameters
pPkt Pointer to the packet data space
pMode The estab mode
Returns
TRUE if the incoming packet was decoded successfully.
References GimbalPkt_t::Data, ELECTRONIC_STAB_SETTINGS_PKTTYPE, FACTORY_ELECTRONIC_STAB_SETTINGS_PKTTYPE, GIMBAL_SETUP_GROUP, GimbalPkt_t::Group, GimbalPkt_t::PktType, and GimbalPkt_t::Size.
BOOL DecodeFrameShiftPacket (const GimbalPkt_t * pPkt, UInt8 * pSource, float * pFrameShiftH, float * pFrameShiftV, UInt16 * pNumFrames, UInt16 * pDeltaT)
Decode a packet that contains the image frame shifts.
Decode a packet that contains the image frame shifts.
Parameters
pPkt is the incoming gimbal packet.
pSource receives the frame shift source identifier (0x00=VPS, 0x01=Tracker Plugin).
pFrameShiftH receives the horizontal image frame shift in radians.
pFrameShiftV receives the vertical image frame shift in radians.
pNumFrames receives the number of frames over which these frame shifts were accumulated.
pDeltaT receives the timer interval in milliseconds over which these frame shifts were accumulated.
Returns
TRUE if the incoming packet was decoded successfully.
References GimbalPkt_t::Data, DataToSInt16(), DataToUInt16(), FRAME_SHIFTS_GIMBAL_PKTTYPE, GIMBAL_DYNAMICS_INFORMATION_GROUP, GimbalPkt_t::Group, GimbalPkt_t::PktType, and GimbalPkt_t::Size.
BOOL DecodeGimbalAglPacket (const GimbalPkt_t * pPkt, UInt16 * pAglMeters, BOOL * pAglValid)
Decode a AGL altitude packet for the gimbal.
Decode a AGL altitude packet for the gimbal
Parameters
pPkt is the packet to decode.
pAglMeters receives the AGL altitude in meters.
pAglValid receives the AGL altitude validity.
Returns
TRUE if the packet decoded successfully.
References GimbalPkt_t::Data, DataToUInt16(), GIMBAL_AGL_PKTTYPE, GIMBAL_COMMAND_AND_CONTROL_GROUP, GimbalPkt_t::Group, and GimbalPkt_t::PktType.
BOOL DecodeGimbalAxisSettingsPacket (const GimbalPkt_t * pPkt, float NoGoCenter[NGIMBAL_SHORT], float NoGoRange[NGIMBAL_SHORT], float MaxRate[NGIMBAL_SHORT], float MaxAccel[NGIMBAL_SHORT], float PosGain[NGIMBAL_SHORT], float VelGain[NGIMBAL_SHORT], float DerGain[NGIMBAL_SHORT], BOOL * pTemporary)
Interpret a gimbal axis control packet.
Decode a gimbal axis settings packet which contains the data to setup the axis control for custom configurations.
Parameters
pPkt points to a gimbal packet containing the data to be decoded.
NoGoCenter receives the center of the no go range in radians for all gimbal axis.
NoGoRange receives the size of the no go range in radians for all gimbal axis. Zero is free-running. More than 2PI is do not change center or range.
MaxRate receives the max rate in radians per second for all gimbal axis. Less than zero is do not change.
MaxAccel receives the max accelerating in radians per second per second for all gimbal axis. Less than zero is do not change.
PosGain receives the position gain in angle per second per angle error. Less than zero is do not change.
VelGain receives the dimensionless velocity gain. Less than zero is do not change.
DerGain receives the gain from the gyro acceleration to the velocity command. Less than zero is do not change.
pTemporary will be set to TRUE if this packets data should not be stored non-volatilely.
Returns
TRUE if the packet is OK, FALSE if it is bad.
References AXIS_SETTINGS_GIMBAL_PKTTYPE, GimbalPkt_t::Data, DataToSInt16(), DataToUInt16(), FACTORY_AXIS_SETTINGS_GIMBAL_PKTTYPE, GIMBAL_PAN, GIMBAL_SETUP_GROUP, GIMBAL_TILT, GimbalPkt_t::Group, NGIMBAL_SHORT, GimbalPkt_t::PktType, and GimbalPkt_t::Size.
BOOL DecodeGimbalCameraAlignPacket (const GimbalPkt_t * pPkt, float * pZoom1, float Error1[NGIMBAL], float * pZoom2, float Error2[NGIMBAL], UInt8 * pCamera)
Interpret a gimbal camera alignment packet.
Interpret a gimbal camera alignment packet
Parameters
pPkt contains the formatted packet.
pZoom1 receives the first zoom ratio of the alignment.
Error1 receives the pan, tilt, roll alignment errors at the first zoom ratio [rad].
pZoom2 receives the second zoom ratio of the alignment.
Error2 receives the pan, tilt, roll alignment errors at the second zoom ratio [rad].
pCamera receives the camera that this data apply to.
Returns
TRUE if the packet cotains valid data, else FALSE
References CAMERA_ALIGN_GIMBAL_PKTTYPE, GimbalPkt_t::Data, DataToSInt16(), DataToUInt16(), FACTORY_CAMERA_ALIGN_GIMBAL_PKTTYPE, GIMBAL_SETUP_GROUP, GimbalPkt_t::Group, N3D, GimbalPkt_t::PktType, and GimbalPkt_t::Size.
BOOL DecodeGimbalCameraCmdPacket (const GimbalPkt_t * pPkt, UInt8 * pCamera, float * pHFOV, UInt16 * pFocus, UInt8 * pEMode, UInt8 * pShutter, UInt8 * pBright, UInt8 * pFlags)
Interpret a camera command packet containing the field of view and focus.
Interpret a camera command packet containing the field of view and focus.
Parameters
pPkt points to a gimbal packet containing the data to be decoded.
pCamera receives the target camera enumeration.
pHFOV receives the horizontal field of view in radians.
pFocus receives the focus length in millimeters.
pEMode receives exposure mode: 0 for auto, 1 for shutter priority, 3 for bright, else don't change.
pShutter receives the VISCA shutter speed.
pBright receives the bright setting.
pFlags receives the camera flags.
Returns
TRUE if the packet is OK, FALSE if it is bad.
References CAMERA_CMD_GIMBAL_PKTTYPE, GimbalPkt_t::Data, DataToSInt16(), DataToUInt16(), GIMBAL_COMMAND_AND_CONTROL_GROUP, GimbalPkt_t::Group, GimbalPkt_t::PktType, and GimbalPkt_t::Size.
BOOL DecodeGimbalCameraZoomPacket (const GimbalPkt_t * pPkt, UInt8 * pCamera, SInt8 * pRate, float * pTimeout)
Decode the gimbal camera zoom packet.
Decode the gimbal camera zoom packet which provides continuous zoom or focus control.
Parameters
pPkt is the packet to decode.
pCamera recieves the camera index that this command applies to.
pRate receives the desired zoom rate from -8 to 8.
pTimeout receives the timeout to apply to this packet.
References CAMERA_ZOOM_GIMBAL_PKTTYPE, GimbalPkt_t::Data, GIMBAL_COMMAND_AND_CONTROL_GROUP, GimbalPkt_t::Group, GimbalPkt_t::PktType, and GimbalPkt_t::Size.
BOOL DecodeGimbalEnhancementCommand (const GimbalPkt_t * pPkt, BOOL * pEnabled, UInt8 * pIntensity, UInt8 * pLimit)
Decode the image enhancement command packet.
BOOL DecodeGimbalFilterPacket (const GimbalPkt_t * pPkt, float * pCutoff, float * pDeadband)
Interpret a gimbal filter packet.
Interpret a gimbal filter packet
Parameters
pPkt points to a gimbal packet containing the data to be decoded.
pCutoff receives the gyro cutoff frequency in Hertz.
pDeadband receives the gyro deadband in radians per second.
Returns
TRUE if the packet is OK, FALSE if it is bad.
References GimbalPkt_t::Data, GIMBAL_SETUP_GROUP, GimbalPkt_t::Group, GimbalPkt_t::PktType, SENSOR_FILTER_GIMBAL_PKTTYPE, and GimbalPkt_t::Size.
BOOL DecodeGimbalFLIRConfigurationPacket (const GimbalPkt_t * pPkt, FLIRConfig_t * pConfig)
Decode a packet with FLIR configuration information.
Decode a packet with the FLIR specific camera configuration data.
Parameters
pPkt points to the packet to decode;
pConfig receives the configuration details.
Returns
TRUE if the packet is valid, else FALSE.
References FLIRConfig_t::AGCMaxGain, FLIRConfig_t::AgcRoiPercent, FLIRConfig_t::AGCType, FLIRConfig_t::BrightBias, FLIRConfig_t::Brightness, FLIRConfig_t::ColorLUT, FLIRConfig_t::Constrast, GimbalPkt_t::Data, DataToSInt16(), DataToUInt16(), FLIR_CONFIGURATION_GIMBAL_PKTTYPE, GIMBAL_SETUP_GROUP, GimbalPkt_t::Group, FLIRConfig_t::IntegrationTime, FLIRConfig_t::ITTMean, GimbalPkt_t::PktType, FLIRConfig_t::PlateauLevel, and GimbalPkt_t::Size.
BOOL DecodeGimbalGPSLeverArmPacket (const GimbalPkt_t * pPkt, float Arm[N3D])
Interpret a gimbal GPS lever arm packet.
Interpret a gimbal GPS lever arm packet
Parameters
pPkt contains the formatted packet.
Arm receives the GPS lever arm vector, in meters.
Returns
TRUE if the packet cotains valid data, else FALSE
References GimbalPkt_t::Data, DataToSInt16(), GIMBAL_SETUP_GROUP, GPS_LEVER_ARM_GIMBAL_PKTTYPE, GimbalPkt_t::Group, N3D, GimbalPkt_t::PktType, and GimbalPkt_t::Size.
BOOL DecodeGimbalIRCamConfigurationPacket (const GimbalPkt_t * pPkt, IRCamConfig_t * pConfig)
Decode a packet with IRCam configuration information.
Decode a Gimbal packet with the IRCam specific camera configuration data.
Parameters
pPkt points to the packet to decode;
pConfig receives the configuration details.
Returns
TRUE if the packet is valid, else FALSE.
References IRCamConfig_t::AGLCMode, IRCamConfig_t::AGLCRoi, IRCamConfig_t::Background, IRCamConfig_t::Brightness, IRCamConfig_t::Contrast, GimbalPkt_t::Data, DataToSInt16(), DataToUInt16(), IRCamConfig_t::Flags, IRCamConfig_t::Foreground, GIMBAL_SETUP_GROUP, GimbalPkt_t::Group, IRCAM_CONFIGURATION_GIMBAL_PKTTYPE, IRCamFlags_t::LAPState, IRCamFlags_t::NRFState, IRCamConfig_t::OperationMode, GimbalPkt_t::PktType, IRCamFlags_t::ResetAGLC, IRCamFlags_t::ResetLAP, and GimbalPkt_t::Size.
BOOL DecodeGimbalIRCamSaveRestorePacket (const GimbalPkt_t * pPkt, UInt8 * pConfigAction)
Decode a packet to save/restore IRCam IR configuration information.
Decode a packet to save/restore T500 IR configuration information.
Parameters
pPkt points to the packet to decode;
pConfigAction receives the action identifier.
Returns
TRUE if the packet is valid, else FALSE.
References GimbalPkt_t::Data, GIMBAL_SETUP_GROUP, GimbalPkt_t::Group, IRCAM_SAVE_RESTORE_GIMBAL_PKTTYPE, GimbalPkt_t::PktType, and GimbalPkt_t::Size.
BOOL DecodeGimbalKLVDetailsPacket (const GimbalPkt_t * pPkt, KLVDetails_t * pKLV)
Decode a packet with KLV settings information.
Decode a packet with the KLV details
Parameters
pPkt points to the packet to decode;
pKLV receives the KLV details.
Returns
TRUE if the packet is valid, else FALSE.
References KLVDetails_t::Caveats, KLVDetails_t::Classification, KLVDetails_t::ClassifyingCountry, KLVDetails_t::ClassifyingCountryCodeMethod, GimbalPkt_t::Data, GIMBAL_SETUP_GROUP, GimbalPkt_t::Group, KLV_DETAILS_GIMBAL_PKTTYPE, KLVDetails_t::MissionID, KLVDetails_t::ObjectCountryCodeMethod, KLVDetails_t::ObjectCountryCodes, GimbalPkt_t::PktType, KLVDetails_t::PlatformDesignation, KLVDetails_t::ReleasingInstructions, KLVDetails_t::SCI_SCH, and GimbalPkt_t::Size.
BOOL DecodeGimbalLaserArmCmdPacket (const GimbalPkt_t * pPkt, UInt8 * pLaserIndex, BOOL * pArm)
Interpret a laser arm command.
Interpret a laser arm command
Parameters
pPkt is the packet to interpret.
pLaserIndex receives the index of the laser being commanded.
pArm receives the arm status.
Returns
TRUE if the packet is valid.
References GimbalPkt_t::Data, GIMBAL_COMMAND_AND_CONTROL_GROUP, GimbalPkt_t::Group, LASER_ARM_CMD_GIMBAL_PKTTYPE, GimbalPkt_t::PktType, and GimbalPkt_t::Size.
BOOL DecodeGimbalLaserFireCmdPacket (const GimbalPkt_t * pPkt, UInt8 * pLaserIndex, UInt8 * pPower)
Interpret a laser fire command.
Interpret a laser fire command
Parameters
pPkt is the packet to interpret.
pLaserIndex receives the index of the laser being commanded.
pPower receives the desired power in % from 0 to 100.
Returns
TRUE if the packet is valid.
References GimbalPkt_t::Data, GIMBAL_COMMAND_AND_CONTROL_GROUP, GimbalPkt_t::Group, LASER_FIRE_CMD_GIMBAL_PKTTYPE, GimbalPkt_t::PktType, and GimbalPkt_t::Size.
BOOL DecodeGimbalLasersInstalledPacket (const GimbalPkt_t * pPkt, LaserSetup_t Lasers[NUM_LASERS])
Interpret a lasers installed packet.
Interpret a lasers installed packet
Parameters
pPkt is the packet to interpret.
Lasers receives the laser setup information.
Returns
TRUE if the packet is valid.
References GimbalPkt_t::Data, DataToUInt16(), FACTORY_LASERS_INSTALLED_GIMBAL_PKTTYPE, GIMBAL_SETUP_GROUP, GimbalPkt_t::Group, LASER_TYPE_DUMB_LASER, LASERS_INSTALLED_GIMBAL_PKTTYPE, NUM_LASERS, GimbalPkt_t::PktType, SetLaserFixedParams(), and GimbalPkt_t::Size.
BOOL DecodeGimbalMagCalPacket (const GimbalPkt_t * pPkt, float HardIronErr[N3D], float ScaleFactErr[N3D])
Decode a packet with magnetometer calibration data.
Decode a packet with magnetometer calibration data.
Parameters
pPkt points to the packet to decode;
HardIronErr is a vector of hard iron errors;
ScaleFactErr is a vector of scale factor errors.
Returns
TRUE if the packet is valid, else FALSE.
References GimbalPkt_t::Data, DataToFloat(), GIMBAL_SETUP_GROUP, GimbalPkt_t::Group, MAG_CAL_GIMBAL_PKTTYPE, N3D, GimbalPkt_t::PktType, and GimbalPkt_t::Size.
BOOL DecodeGimbalRadioSettings (const GimbalPkt_t * pPkt, RadioSettings_t * pSettings)
Decode a radio settings packet for the gimbal.
Decode a radio settings packet for the gimbal
Parameters
pPkt is the packet to decode.
pSettings receives the radio settings.
Returns
TRUE if the packet decoded successfully.
References GIMBAL_COMMAND_AND_CONTROL_GROUP, GimbalPkt_t::Group, GimbalPkt_t::PktType, and RADIO_SETUP_GIMBAL_PKTTYPE.
BOOL DecodeGimbalRetractDeployCmdPacket (const GimbalPkt_t * pPkt, UInt32 * pDeploy)
Interpret a 3AX retract or deploy command packet.
Interpret a 3AX retract or deploy command packet.
Parameters
pPkt contains the formatted packet.
pDeploy receives the deploy command, 0 for retract, 1 for deploy, 2 for halt
Returns
TRUE if the packet cotains valid data, else FALSE.
References GimbalPkt_t::Data, GIMBAL_COMMAND_AND_CONTROL_GROUP, GimbalPkt_t::Group, GimbalPkt_t::PktType, RETRACT_DEPLOY_CMD_GIMBAL_PKTTYPE, and GimbalPkt_t::Size.
BOOL DecodeGimbalRetractorConfigurationPacket (const GimbalPkt_t * pPkt, Retractor_t * pRetractor)
Decode a packet with the retractor configuration data.
Decode a packet with the retractor configuration data.
Parameters
pPkt points to the packet to decode
pRetractor is the configuration details.
Returns
TRUE if the packet decoded OK.
References GimbalPkt_t::Data, DataToSInt16(), DataToUInt16(), Retractor_t::DeployAtStart, Retractor_t::DesiredDeploy, Retractor_t::DoorClosePWM, Retractor_t::DoorOpenPWM, GIMBAL_SETUP_GROUP, GimbalPkt_t::Group, Retractor_t::LockPWM, GimbalPkt_t::PktType, Retractor_t::RetractAtStart, Retractor_t::RetractDownPWM, Retractor_t::RetractNeutralPWM, RETRACTOR_CONFIG_GIMBAL_PKTTYPE, Retractor_t::RetractorType, Retractor_t::RetractPan, Retractor_t::RetractTilt, Retractor_t::RetractUpPWM, Retractor_t::SafeToMove, GimbalPkt_t::Size, and Retractor_t::UnlockPWM.
BOOL DecodeGimbalRigTestCmdPacket (const GimbalPkt_t * pPkt, float * pMaxSpeed, float * pMaxAccel, UInt16 * pTime)
Interpret a gimbal rig test command packet.
Interpret a gimbal rig test command packet
Parameters
pPkt points to the packet to interpret.
pMaxSpeed receives the maximum rig test speed (rad/s).
pMaxAccel receives the maximum rig test acceleration (rad/s/s).
pTime receives the rig test time in seconds.
Returns
TRUE if the packet is valid, else FALSE;
References GimbalPkt_t::Data, DataToUInt16(), GIMBAL_COMMAND_AND_CONTROL_GROUP, GimbalPkt_t::Group, GimbalPkt_t::PktType, RIG_TEST_CMD_GIMBAL_PKTTYPE, and GimbalPkt_t::Size.
BOOL DecodeGimbalSensorConfigPacket (const GimbalPkt_t * pPkt, float Rotation[N3D], GimbalSensorFlags_t * pFlags)
Decode a packet with sensor configuration data.
Decode a packet with sensor configuration data
Parameters
pPkt points to the packet to decode;
Rotation receives the rotations in radians from gimbal to vehicle.
pFlags receives the sensor configuration flags..
Returns
TRUE if the packet is valid, else FALSE.
References GimbalPkt_t::Data, DataToSInt16(), DataToUInt32(), GimbalSensorFlags_t::DisableuBloxSBAS, GIMBAL_SETUP_GROUP, GimbalPkt_t::Group, N3D, GimbalPkt_t::PktType, SENSOR_CONFIGURATION_GIMBAL_PKTTYPE, GimbalPkt_t::Size, GimbalSensorFlags_t::UseExtAttitude, GimbalSensorFlags_t::UseExtHeading, GimbalSensorFlags_t::UseInternalMag, GimbalSensorFlags_t::UseNovatelAlign, and GimbalSensorFlags_t::UseVPSHeading.
BOOL DecodeGimbalSerialInterfacePacket (const GimbalPkt_t * pPkt, GimbalSerial_t Interface[6], BOOL * pTemporary)
Interpret a serial interface setup packet.
Interpret a gimbal serial interface packet
Parameters
pPkt contains the formatted packet.
Interface recevies the serial interface descriptions.
pTemporary will be set to TRUE if this packets data should not be stored non-volatilely.
Returns
TRUE if the packet cotains valid data, else FALSE
References GimbalSerial_t::Angle, GimbalSerial_t::Baud, GimbalPkt_t::Data, GimbalSerial_t::Georef, GIMBAL_SETUP_GROUP, GimbalPkt_t::Group, GimbalPkt_t::PktType, GimbalSerial_t::Protocol, GimbalSerial_t::Rate, GimbalSerial_t::Reserved, SERIAL_INTERFACE_GIMBAL_PKTTYPE, and GimbalPkt_t::Size.
BOOL DecodeGimbalSPOICmdPacket (const GimbalPkt_t * pPkt, double Pos[NPOS], float Vel[NDIR], UInt8 * pFlags)
Interpret a gimbal sensor point of interest packet containing the position of the SPOI.
Decode a gimbal sensor point of interest (SPOI) cmd packet. The SPOI packet tells the gimbal where to point in LLA coordinates relative to the WGS-84 ellipsoid.
Parameters
pPkt points to a gimbal packet containing the data to be decoded.
Pos receives the sensor point of interest position in latitude (rad), longitude (rad), altitude (m) with respect to the WGS-84 ellipsoid.
Vel receives the sensor point of interest velocity in North, East, Down meters per second.
pFlags receives the packet flags.
Returns
TRUE if the packet is OK, FALSE if it is bad.
References ALT, GimbalPkt_t::Data, DataToSInt16(), DataToSInt32(), DOWN, EAST, GIMBAL_POSITION_INFORMATION_GROUP, GimbalPkt_t::Group, LAT, LON, NORTH, GimbalPkt_t::PktType, GimbalPkt_t::Size, and SPOI_CMD_GIMBAL_PKTTYPE.
BOOL DecodeGimbalTargetLocationEstimate (const GimbalPkt_t * pPkt, double PosLLA[NPOS], UInt32 * pGPSTOW, UInt8 * pSource, UInt8 * pError)
Decode the estimate of the target location position coming from the user.
Interpret a target location estimate packet coming from the user.
Parameters
pPkt is the packet to decode.
PosLLA is the position in latitude[rad], longitude[rad], altitude [m].
pGPSTOW is the GPS time of week in milliseconds that applies to this position.
pSource is the source code for the target location data.
pError is the associated error code for the target location data.
Returns
TRUE if the packet is valid, else FALSE.
References ALT, GimbalPkt_t::Data, DataToSInt32(), DataToUInt32(), GIMBAL_POSITION_INFORMATION_GROUP, GimbalPkt_t::Group, LAT, LON, GimbalPkt_t::PktType, GimbalPkt_t::Size, and TARGET_LOCATION_ESTIMATE_GIMBAL_PKTTYPE.
BOOL DecodeGimbalTrackCommand (const GimbalPkt_t * pPkt, float * pInitialX, float * pInitialY, UInt8 * pAlgorithm, UInt8 * pSize, UInt8 * pStamp)
Decode the track command packet.
Decode the track command packet
Parameters
pPkt points to the packet to decode.
pInitialX is the initial X position of the track in radians.
pInitialY is the initial Y position of the track in radians.
pAlgorithm receives the desired track algorithm.
pSize receives the desired track box size.
pStamp receives the video stamp, 255 if no stamp.
Returns
TRUE if the packet is valid, else FALSE.
References GimbalPkt_t::Data, DataToSInt16(), GIMBAL_COMMAND_AND_CONTROL_GROUP, GimbalPkt_t::Group, GimbalPkt_t::PktType, GimbalPkt_t::Size, and TRACKER_CMD_GIMBAL_PKTTYPE.
BOOL DecodeGimbalTrackerSettingsAdvancedCommand (const GimbalPkt_t * pPkt, float * pGainP, float * pGainI, float * pGainD, float * pRateLimit, float * pDeadband)
Decode the advanced settings packet.
Decode the tracker settings (advanced) packet
Parameters
pPkt points to the packet to decode.
pGainP receives the PID Controller P-Term
pGainI receives the PID Controller I-Term
pGainD receives the PID Controller D-Term
pRateLimit receives the Maximum Rate (Radians / Second) to command
pDeadband receives the Deadband, expressed as a percent of current FOV
Returns
TRUE if the packet is valid, else FALSE.
References GimbalPkt_t::Data, DataToUInt16(), FACTORY_TRACKER_ADV_CMD_GIMBAL_PKTTYPE, GIMBAL_SETUP_GROUP, GimbalPkt_t::Group, GimbalPkt_t::PktType, GimbalPkt_t::Size, and TRACKER_ADV_CMD_GIMBAL_PKTTYPE.
BOOL DecodeGimbalTrackingData (const GimbalPkt_t * pPkt, float GimbalAngles[NGIMBAL], float CameraAngles[NAXIS], float * pHFOV, float * pRange, UInt8 * pMode)
Decode a packet that has the gimbal tracking data in it.
Decode a packet that has the gimbal tracking data in it
Parameters
pPkt is the packet to decode
GimbalAngles receives the pan and tilt in raidans w.r.t the mount
CameraAngles receives the yaw and pitch in radians w.r.t the inertial reference frame.
pHFOV receieves the horizontal field of view in radians.
pRange receives the range from the laser range finder, or -1 if none.
pMode receives the gimbal mode.
Returns
TRUE if the packet decodes OK.
References GimbalPkt_t::Data, DataToSInt16(), DataToUInt24(), GIMBAL_DYNAMICS_INFORMATION_GROUP, GIMBAL_PAN, GIMBAL_ROLL, GIMBAL_TILT, GimbalPkt_t::Group, PITCH_AXIS, GimbalPkt_t::PktType, ROLL_AXIS, GimbalPkt_t::Size, TRACKING_DATA_GIMBAL_PKTTYPE, and YAW_AXIS.
BOOL DecodeGimbalWaterMarkPacket (const GimbalPkt_t * pPkt, UInt8 * pFormat, UInt8 * pStatus, UInt32 * pSequence, UInt8 * pImageData, UInt8 * pSize)
Decode a packet with watermark payload data.
Decode a packet with vps watermark payload data, copies data to the start of the pImageData buffer.
Parameters
pPkt receives the formatted packet.
pFormat receives the format of the watermark image data.
pStatus receives the status of the watermark image data.
pSequence receives the sequence number of the watermark image data.
pImageData receives the the watermark image data when not NULL;
pSize receives the number of bytes of watermark image data.
Returns
TRUE if a packet is found, else FALSE.
References GimbalPkt_t::Data, DataToUInt24(), GIMBAL_SETUP_GROUP, GIMBAL_WATERMARK_DATA_PKTTYPE, GimbalPkt_t::Group, GimbalPkt_t::PktType, and GimbalPkt_t::Size.
BOOL DecodeHdControlSettings (const GimbalPkt_t * pPkt, HDControlSettings_t * pSettings)
Decode the HD control settings.
Decode an HD control settings packet which defines how the gimbal will process HD video.
Parameters
pPkt Pointer to the packet data space
pSettings The HD control settings
Returns
TRUE if the incoming packet was decoded successfully.
References GimbalPkt_t::Data, FACTORY_HD_CONTROL_SETTINGS_PKTTYPE, GIMBAL_SETUP_GROUP, GimbalPkt_t::Group, HD_CONTROL_SETTINGS_PKTTYPE, GimbalPkt_t::PktType, and GimbalPkt_t::Size.
BOOL DecodeLaserEnablePswdPacket (const GimbalPkt_t * pPkt, UInt16 * pswd, BOOL * pByPassAgl)
Decode a laser password packet.
References GimbalPkt_t::Data, DataToUInt16(), GIMBAL_COMMAND_AND_CONTROL_GROUP, GimbalPkt_t::Group, LASER_PASSWORD_ENABLER_PKTTYPE, and GimbalPkt_t::PktType.
BOOL DecodeLaserSafetyStatus (const GimbalPkt_t * pPkt, BOOL * BypassSafety, UInt8 * pFlags)
Interpret a laser status and safety packet.
Decode a laser status and safety packet
Parameters
pPkt is the packet to decodet
BypassSafety recieves the status of bypassing(TRUE) or invoking(FALSE) safety rules at the auto pilot
pFlags contains the safety flags that are violated, if any, in packets adressed to the host, otherwise these flags are ignored.
References GimbalPkt_t::Data, GIMBAL_COMMAND_AND_CONTROL_GROUP, GimbalPkt_t::Group, LASER_SAFETY_STATUS_PKTTYPE, and GimbalPkt_t::PktType.
BOOL DecodeLaserWatchdogPacket (const GimbalPkt_t * pPkt, UInt8 * LaserIndex)
Interpret a laser watchdog packet. The relevent laser index is returned if successful.
Interpret a laser watchdog packet. The relevent laser index is returned if successful.
References GimbalPkt_t::Data, GIMBAL_COMMAND_AND_CONTROL_GROUP, GimbalPkt_t::Group, LASER_WATCHDOG_PKTTYPE, and GimbalPkt_t::PktType.
BOOL DecodeLensCalFocusPacket (const GimbalPkt_t * pPkt, UInt8 * pCameraIndex, UInt8 * pRowIndex, float * pTemperature, SInt16 Focuses[AF_CAL_POINTS], UInt8 * pNumEntries)
Decode a packet that specifies the temperature and focus points of a pre-focus calibration table.
Decode a packet that specifies the temperature and focus points of a pre-focus calibration table
Parameters
pPkt is the packet to decode
pCameraIndex is the index of the camera/lens being updated.
pRowIndex is the index of the table row being updated.
pTemperature is the calibration temperature in degrees Celcius for the designated row.
Focuses is the array of focus encoder positions in the table.
pNumEntries is number of entries in the table, up to AF_CAL_POINTS.
References AF_CAL_POINTS, GimbalPkt_t::Data, DataToSInt16(), GIMBAL_SETUP_GROUP, GimbalPkt_t::Group, LENS_CAL_FOCUS_CONFIGURATION, GimbalPkt_t::PktType, and GimbalPkt_t::Size.
BOOL DecodeLensCalZoomPacket (const GimbalPkt_t * pPkt, UInt8 * pCameraIndex, SInt16 Zooms[26], UInt8 * pNumEntries)
Decode a packet that specifies the zoom points of a pre-focus calibration table.
Referenced by DecodeLensPrefocusPacket().
BOOL DecodeLensDevCommandPacket (const GimbalPkt_t * pPkt, UInt8 * pCameraId, UInt8 * pControlType, UInt8 * pInitFlag, SInt16 * pPosition)
Decode a packet to directly command a Microblaze controlled lens.
Decode a packet to directly command a Microblaze controlled lens.
Parameters
pPkt receives the formatted packet.
pCameraId is the identifier of the camera with the lens that this command applies.
pControlType indicates which lens control this command applies, i.e. zoom, focus.
pInitFlag is a indicator if the lens should perform a high or low init.
pPosition is the commanded encoder position, 0x7FFF for do not change.
References GimbalPkt_t::Data, DataToSInt16(), GimbalPkt_t::Group, MB_LENS_COMMAND_PKTTYPE, MICROBLAZE_DEVELOPMENT_GROUP, GimbalPkt_t::PktType, and GimbalPkt_t::Size.
BOOL DecodeLensDiagnosticsPacket (const GimbalPkt_t * pPkt, LensDiagnostics_t * pData)
Decode a lens diagnostic packet.
Decode a lens diagnostic packet
Parameters
pPkt receives the formatted packet.
pData is the lens diagnostic data structure.
References LensDiagnostics_t::ActualPos, LensDiagnostics_t::ActualVelocity, LensDiagnostics_t::CameraId, LensDiagnostics_t::CommandedPos, LensDiagnostics_t::CommandedVelocity, LensDiagnostics_t::ControlId, GimbalPkt_t::Data, DataToFloat(), DataToSInt16(), DataToUInt16(), LensDiagnostics_t::EncoderErrCount, GimbalPkt_t::Group, LensDiagnostics_t::InitState, LensDiagnostics_t::LimitSwitch, LensDiagnostics_t::MaxPosition, MB_LENS_DIAGNOSTIC_PKTTYPE, LensDiagnostics_t::Metric, MICROBLAZE_DEVELOPMENT_GROUP, LensDiagnostics_t::MinPosition, GimbalPkt_t::PktType, LensDiagnostics_t::Reserved, GimbalPkt_t::Size, and LensDiagnostics_t::Temperature.
BOOL DecodeLensPrefocusPacket (const GimbalPkt_t * pPkt, UInt8 * pCameraIndex, UInt8 * pLensType, float Zooms[10], UInt16 Focuses[10], UInt8 * pNumEntries)
Decode a packet that specifies the pre-focus calibration table.
Decode a packet that specifies the pre-focus calibration table
Parameters
pPkt is the packet to decode
pCameraIndex is the index of the camera/lens being updated.
pLensType is the type of lens.
Zooms is the array of zoom ratios in the table.
Focuses is the array of focus values in the table.
pNumEntries is number of entries in the table, up to 10.
References AF_CAL_POINTS, GimbalPkt_t::Data, DataToSInt16(), DataToUInt16(), DecodeLensCalZoomPacket(), FinishGimbalPacket(), FormLensCalZoomPacket(), GIMBAL_SETUP_GROUP, GimbalPkt_t::Group, LENS_CAL_ZOOM_CONFIGURATION, LENS_PREFOCUS_CONFIGURATION, GimbalPkt_t::PktType, SInt16ToData(), and GimbalPkt_t::Size.
BOOL DecodeLensRegisterPacket (const GimbalPkt_t * pPkt, UInt8 * pCameraId, UInt8 * pControlType, UInt16 * pAddress, UInt32 * pValue, BOOL * pWrite)
Decode a packet to set a lens register value.
Decode a packet to read/write a lens register value.
Parameters
pPkt receives the formatted packet.
pCameraId is the identifier of the camera with the lens that this command applies.
pControlType is the control type of this packet, i.e. Focus or Zoom
pAddress is the address of which to set the value for.
pValue is the value to set at the designated register.
pWrite is TRUE if this is a register write, otherwise a read operation.
References GimbalPkt_t::Data, DataToUInt16(), DataToUInt32(), GimbalPkt_t::Group, MB_LENS_REGISTER_PKTTYPE, MICROBLAZE_DEVELOPMENT_GROUP, GimbalPkt_t::PktType, and GimbalPkt_t::Size.
BOOL DecodeMC_AxisParamPacket (const GimbalPkt_t * pPkt, float * pInPanKp, float * pInPanKi, float * pInPanKd, float * pInTiltKp, float * pInTiltKi, float * pInTiltKd, float * pOutPanKp, float * pOutPanKi, float * pOutPanKd, float * pOutTiltKp, float * pOutTiltKi, float * pOutTiltKd)
Decode a motion control axis parameter packet.
Decode a motion control axis parameter packet
Parameters
pPkt receives the formatted packet.
pInPanKp Inner pan Kp value.
pInPanKi Inner pan Ki value.
pInPanKd Inner pan Kd value.
pInTiltKp Inner tilt Kp value.
pInTiltKi Inner tilt Ki value.
pInTiltKd Inner tilt Kd value.
pOutPanKp Outer pan Kp value.
pOutPanKi Outer pan Ki value.
pOutPanKd Outer pan Kd value.
pOutTiltKp Outer tilt Kp value.
pOutTiltKi Outer tilt Ki value.
pOutTiltKd Outer tilt Kd value.
Returns
TRUE if the packet is valid, else FALSE.
References AXIS_PARAMS, AXIS_PARAMS_FACTORY, GimbalPkt_t::Data, DataToFloat(), GimbalPkt_t::PktType, and GimbalPkt_t::Size.
BOOL DecodeMC_LimitsPacket (const GimbalPkt_t * pPkt, float * pPanMin, float * pPanMax, float * pTiltMin, float * pTiltMax, float * pPanRateMax, float * pTiltRateMax, float * pPanAccelMax, float * pTiltAccelMax)
Decode a motion control limits packet.
Decode a motion control axis limits packet
Parameters
pPkt receives the formatted packet.
pPanMin The pan axis lower limit.
pPanMax The pan axis upper limit.
pTiltMin The tilt axis lower limit.
pTiltMax The tilt axis upper limit.
pPanRateMax The pan axis rate limit.
pTiltRateMax The tilt axis rate limit.
pPanAccelMax The pan axis acceleration limit.
pTiltAccelMax The tilt axis acceleration limit.
Returns
TRUE if the packet is valid, else FALSE.
References AXIS_LIMITS, AXIS_LIMITS_FACTORY, GimbalPkt_t::Data, DataToFloat(), GimbalPkt_t::PktType, and GimbalPkt_t::Size.
BOOL DecodeMC_MotionCalibrationParamPacket (const GimbalPkt_t * pPkt, float Offsets[3], float GainMatrix[9])
Decode a motion control parameter packet.
Decode a motion control parameter packet
Parameters
pPkt receives the formatted packet.
Offsets Gyro offsets in ADC counts aligned to gimbal indices
GainMatrix Cross-axis alignment data
Returns
TRUE if the packet is valid, else FALSE.
References GimbalPkt_t::Data, DataToFloat(), MOTION_CALIBRATION_PARAMS, MOTION_CALIBRATION_PARAMS_FACTORY, GimbalPkt_t::PktType, and GimbalPkt_t::Size.
BOOL DecodeMISBSettingsPacket (const GimbalPkt_t * pPkt, MISBConfig_t * pData)
Decode a video settings packet.
Decode a MISB settings packet
Parameters
pPkt the packet data to decode.
pData receives the data.
Returns
TRUE if the packet is valid, else FALSE.
References MISBConfig_t::BitRate, GimbalPkt_t::Data, DataToUInt16(), DataToUInt32(), FACTORY_MISB_SETTINGS_PKTTYPE, GIMBAL_SETUP_GROUP, MISBConfig_t::GOPSize, GimbalPkt_t::Group, MISBConfig_t::IpAddress, MISB_SETTINGS_PKTTYPE, GimbalPkt_t::PktType, MISBConfig_t::Port, and GimbalPkt_t::Size.
BOOL DecodeScanModeControlPacket (const GimbalPkt_t * pPkt, GimbalScanControlConfig_t * pData)
Decode a gimbal scan mode configuration packet.
Decode a gimbal scan mode configuration packet.
Parameters
pPkt receives the formatted packet.
pData is the gimbal scan control configuration data structure.
Returns
TRUE if a packet is found, else FALSE.
References GimbalScanControlConfig_t::AxisRadius, GimbalScanControlConfig_t::CenterPosition, GimbalPkt_t::Data, DataToSInt16(), GimbalScanControlConfig_t::Enabled, GIMBAL_COMMAND_AND_CONTROL_GROUP, GIMBAL_PAN, GIMBAL_SCAN_CONTROL_PKTTYPE, GIMBAL_TILT, GimbalPkt_t::Group, GimbalPkt_t::PktType, GimbalScanControlConfig_t::RevPerSec, and GimbalPkt_t::Size.
BOOL DecodeSPOIPathPointData (const GimbalPkt_t * pPkt, double PosECEF[MAX_SPOI_PATH_PTS][NPOS], UInt8 * pNumPoints)
Decode a SPOI path point data packet.
Decode a SPOI path point data packet.
Parameters
pPkt points to a gimbal packet.
PosECEF receives the array of points.
pNumPoints receives the number of points in the array.
Returns
TRUE if the packet was successfully decoded, or FALSE otherwise.
References GimbalPkt_t::Data, DataToUInt16(), DataToUInt24(), GIMBAL_POSITION_INFORMATION_GROUP, GimbalPkt_t::Group, MAX_SPOI_PATH_PTS, N3D, GimbalPkt_t::PktType, GimbalPkt_t::Size, and SPOI_PATH_POINT_DATA_PKTTYPE.
BOOL DecodeSPOIPathSettings (const GimbalPkt_t * pPkt, UInt8 * pStepMode, float * pMaxVel, float * pActiveRange, float * pConvDist, float * pStepDist, UInt32 * pStepTime, float * pScanRate)
Decode a SPOI path navigator settings packet.
Decode a SPOI path navigator settings packet.
Parameters
pPkt points to a gimbal packet.
pStepMode receives the SPOI step stare mode, 0=no stepping, 1=distance stepping, 2=time stepping.
pMaxVel receives the maximum SPOI velocity along the path, in m/s.
pActiveRange receives the maximum range at which the SPOI position will be updated, in m.
pConvDist receives the distance ahead of nearest point on the curve to which the SPOI will converge, in m.
pStepDist receives the stepping distance interval, if distance step-stare is enabled, in m.
pStepTime receives the stepping time interval, if time step-stare is enabled, in ms.
pScanRate receives the Scan Rate, in 1/100th Deg/s
Returns
TRUE if the packet was successfully decoded, or FALSE otherwise.
References GimbalPkt_t::Data, DataToFloat(), DataToSInt16(), DataToUInt32(), GIMBAL_SETUP_GROUP, GimbalPkt_t::Group, GimbalPkt_t::PktType, GimbalPkt_t::Size, and SPOI_PATH_PARAM_PKTTYPE.
BOOL DecodeStabDevT2Settings (const GimbalPkt_t * pPkt, SInt16 Gains[AC_NUM_GAINS])
Decode a T2 development settings packet with motor controller gains.
Decode a T2 development settings packet with motor controller gains.
Parameters
pPkt is the packet to decode
Gains contains the gains.
Returns
TRUE if the packet decodes OK.
References GimbalPkt_t::Data, DataToSInt16(), GIMBAL_DEVELOPMENT_GROUP, GimbalPkt_t::Group, GimbalPkt_t::PktType, GimbalPkt_t::Size, and STAB_T2_SET_DEV_PKTTYPE.
BOOL DecodeSuCsxConfigurationPacket (const GimbalPkt_t * pPkt, SuCsxCamConfig_t * pConfig)
Decode a packet with SU CSX configuration information.
Decode a packet with SU CSX configuration information.
Parameters
pPkt points to the packet to decode;
pConfig receives the configuration details.
Returns
TRUE if the packet is valid, else FALSE.
References SuCsxCamConfig_t::AgcCurVal, SuCsxCamConfig_t::AgcGain, SuCsxCamConfig_t::AgcHigh, SuCsxCamConfig_t::AgcLow, SuCsxCamFlags_t::AgcMode, SuCsxCamConfig_t::AgcStart, SuCsxCamFlags_t::CamMessage, SuCsxCamConfig_t::CamMessage, GimbalPkt_t::Data, DataToUInt16(), SuCsxCamConfig_t::EnhanceAverage, SuCsxCamFlags_t::EnhanceMode, SuCsxCamConfig_t::EnhancePower, SuCsxCamConfig_t::Flags, GIMBAL_SETUP_GROUP, GimbalPkt_t::Group, SuCsxCamFlags_t::OpMode, GimbalPkt_t::PktType, GimbalPkt_t::Size, and SUCSX_CONFIGURATION_GIMBAL_PKTTYPE.
BOOL DecodeSuCsxSaveRestorePacket (const GimbalPkt_t * pPkt, UInt8 * pConfigAction)
Decode a packet to save/restore SU CSX configuration information.
Decode a packet to save/restore SU CSX configuration information.
Parameters
pPkt points to the packet to decode;
pConfigAction receives the action identifier.
Returns
TRUE if the packet is valid, else FALSE.
References GimbalPkt_t::Data, GIMBAL_SETUP_GROUP, GimbalPkt_t::Group, GimbalPkt_t::PktType, GimbalPkt_t::Size, and SUCSX_SAVE_RESTORE_GIMBAL_PKTTYPE.
BOOL DecodeVGSAntennaYaw (const GimbalPkt_t * pPkt, float * pYaw)
Decode a packet that sets the current yaw angle of the antenna.
Decode a packet that sets the current yaw angle of the antenna. This is used by the VGS to set the pan offset value.
Parameters
pPkt is the packet to decode.
pYaw receives the true yaw angle in radians.
Returns
TRUE is returned if the packet is valid.
References GimbalPkt_t::Data, DataToSInt16(), GimbalPkt_t::Group, GimbalPkt_t::PktType, SET_ANTENNA_YAW_VGS_PKTTYPE, GimbalPkt_t::Size, and VGS_COMMAND_AND_CONTROL_GROUP.
BOOL DecodeVGSRadioSettings (const GimbalPkt_t * pPkt, RadioSettings_t * pSettings)
Decode a radio settings packet for the video ground station.
Decode a radio settings packet for the video ground station
Parameters
pPkt is the packet to decode.
pSettings receives the radio settings.
Returns
TRUE if the packet decoded successfully.
References GimbalPkt_t::Group, GimbalPkt_t::PktType, RADIO_SETUP_VGS_PKTTYPE, and VGS_COMMAND_AND_CONTROL_GROUP.
BOOL DecodeVps3OverlaySettings (const GimbalPkt_t * pPkt, BOOL * pEnabled, VPS3Symbology_t * pSettings, float * localTimeOffsetHours, BOOL * localTimeDST)
Decode the VPS3 overlay settings.
Decode VPS3 overlay settings packet which sets up all the on screen VPS overlays.
Parameters
pPkt Pointer to the packet data space
pEnabled The global enabled flag
pSettings The overlay settings
Returns
TRUE if the incoming packet was decoded successfully.
References VPS3SymbolFlags_t::AltFromBaro, VPS3SymbolFlags_t::AltLayout, VPS3SymbolFlags_t::AltSrcInUse, VPS3SymbolFlags_t::BitStatus, VPS3SymbolFlags_t::Brackets, VPS3SymbolFlags_t::Compass, VPS3SymbolFlags_t::Crosshair, GimbalPkt_t::Data, DataToFloat(), DataToUInt64(), VPS3SymbolFlags_t::DateAndTime, VPS3SymbolFlags_t::DebugInfo, FACTORY_OVERLAY_SETTINGS_PKTTYPE, VPS3SymbolFlags_t::FaultStatus, GIMBAL_SETUP_GROUP, VPS3SymbolFlags_t::GimbalAngles, VPS3SymbolFlags_t::GimbalHFov, VPS3SymbolFlags_t::GimbalPos, GimbalPkt_t::Group, VPS3SymbolFlags_t::LocalTime, OVERLAY_SETTINGS_PKTTYPE, GimbalPkt_t::PktType, VPS3SymbolFlags_t::Scale, GimbalPkt_t::Size, VPS3SymbolFlags_t::TargetPos, VPS3SymbolFlags_t::TargetRange, VPS3SymbolFlags_t::TitleString, and VPS3SymbolFlags_t::TrackBox.
BOOL DecodeVps3PiPSettings (const GimbalPkt_t * pPkt, BOOL * pEnabled)
Decode the VPS3 picture in picture settings.
Decode VPS3 PiP settings packet which sets up PiP.
Parameters
pPkt Pointer to the packet data space
pEnabled The global enabled flag
Returns
TRUE if the incoming packet was decoded successfully.
References GimbalPkt_t::Data, FACTORY_PICTURE_IN_PICTURE_SETTINGS_PKTTYPE, GIMBAL_SETUP_GROUP, GimbalPkt_t::Group, PICTURE_IN_PICTURE_SETTINGS_PKTTYPE, GimbalPkt_t::PktType, and GimbalPkt_t::Size.
void FinishGimbalPacket (GimbalPkt_t * pPkt, UInt8 Group, UInt8 PktType, UInt8 Size)
Fill out a gimbal packet header and checksum.
Finish a gimbal packet by forming the header of a packet from the passed parameters and then calculating the checksum.
Parameters
pPkt points to a gimbal packet structure which will be formatted.
Group is the packet group field.
PktType is the packet packet type field.
Size is the amount of data to be included in the packet, not including the group and packet type bytes.
References ChecksumGimbalPacket(), and MakeGimbalPacketHeader().
Referenced by DecodeLensPrefocusPacket(), FormCameraDefinitionsPacket(), FormCanPassthroughPacket(), FormEstabSettings(), FormFrameShiftPacket(), FormGimbalAglPacket(), FormGimbalAxisSettingsPacket(), FormGimbalCameraAlignPacket(), FormGimbalCameraCmdPacket(), FormGimbalCameraZoomPacket(), FormGimbalCmdPacket(), FormGimbalEnhancementCommand(), FormGimbalFilterPacket(), FormGimbalFLIRConfigurationPacket(), FormGimbalGPSLeverArmPacket(), FormGimbalHostAttitudePacket(), FormGimbalHostGPSPacket(), FormGimbalHostSensorPacket(), FormGimbalInitialHeadingPacket(), FormGimbalIRCamConfigurationPacket(), FormGimbalIRCamSaveRestorePacket(), FormGimbalKLVDetailsPacket(), FormGimbalLaserArmCmdPacket(), FormGimbalLaserFireCmdPacket(), FormGimbalLasersInstalledPacket(), FormGimbalMagCalPacket(), FormGimbalRetractDeployCmdPacket(), FormGimbalRetractorConfigurationPacket(), FormGimbalRigTestCmdPacket(), FormGimbalSensorConfigPacket(), FormGimbalSerialInterfacePacket(), FormGimbalSPOICmdPacket(), FormGimbalTargetLocationEstimate(), FormGimbalTrackCommand(), FormGimbalTrackerSettingsAdvancedCommand(), FormGimbalTrackingData(), FormGimbalWaterMarkPacket(), FormHdControlSettings(), FormLaserEnablePswdPacket(), FormLaserSafetyStatus(), FormLaserWatchdogPacket(), FormLensCalFocusPacket(), FormLensDevCommandPacket(), FormLensPrefocusPacket(), FormLensRegisterPacket(), FormMC_AxisParamPacket(), FormMC_DoMotionCalibrationPacket(), FormMC_LimitsPacket(), FormMC_MotionCalibrationParamPacket(), FormMISBSettingsPacket(), FormScanModeControlPacket(), FormSetLensDiagnosticsPacket(), FormSPOIPathPointData(), FormSPOIPathSettings(), FormStabDevT2Settings(), FormSuCsxConfigurationPacket(), FormSuCsxSaveRestorePacket(), FormVGSAntennaCommand(), FormVGSAntennaYaw(), FormVGSRadioSettings(), FormVps3OverlaySettings(), FormVps3PiPSettings(), and MakeGimbalPacket().
void FormCameraDefinitionsPacket (GimbalPkt_t * pPkt, const CameraDefinition_t Cam[NUM_CAMERAS], const BOOL Send[NUM_CAMERAS], BOOL Factory)
Createa a camera definitions packet.
Form a camera definition packet, which has up to three cameras defined in it.
Parameters
pPkt is the packet to interpret.
Cam are the camera definitions.
Send should be TRUE for each camera to send (0, 1, 2, etc).
Factory should be TRUE to send the factory definitions, instead of the user definitions.
References CAMERA_DEFINITION_GIMBAL_PKTTYPE, GimbalPkt_t::Data, FACTORY_CAMERA_DEFINITION_GIMBAL_PKTTYPE, FinishGimbalPacket(), GIMBAL_SETUP_GROUP, NUM_CAMERAS, RoundToUInt16(), and UInt16ToData().
Referenced by CommBase_SendGimbalCameraTypesPacket().
void FormCanPassthroughPacket (GimbalPkt_t * pPkt, UInt16 ID, const UInt8 Data[8], UInt8 Length)
Form a packet containing a CAN frame received from or to be sent to CAN-B.
Form a CAN-B passthrough packet.
Parameters
pPkt Pointer to the packet data space
ID The 11-bit standard CAN frame identifier.
Data CAN frame data payload bytes, up to eight.
Length The number of valid bytes contained in Data.
References CAN_PASSTHROUGH_GIMBAL_PKTTYPE, GimbalPkt_t::Data, FinishGimbalPacket(), GIMBAL_SETUP_GROUP, and UInt16ToData().
void FormEstabSettings (GimbalPkt_t * pPkt, EStabModes_t Mode, BOOL Factory)
Encode an estab settings packet which defines how the electronic stabilization works
Parameters
pPkt Pointer to the packet to form
Mode The estab mode
Factory should be TRUE to send the factory definitions, instead of the user definitions.
References GimbalPkt_t::Data, ELECTRONIC_STAB_SETTINGS_PKTTYPE, FACTORY_ELECTRONIC_STAB_SETTINGS_PKTTYPE, FinishGimbalPacket(), and GIMBAL_SETUP_GROUP.
void FormFrameShiftPacket (GimbalPkt_t * pPkt, UInt8 Source, float FrameShiftH, float FrameShiftV, UInt16 NumFrames, UInt16 DeltaT)
Form a packet that contains the image frame shifts.
Form a packet that contains the image frame shifts.
Parameters
pPkt receives the resulting gimbal packet.
Source identifies the source of frame shift information (0x00=VPS, 0x01=Tracker Plugin).
FrameShiftH is the horizontal image frame shift in radians.
FrameShiftV is the vertical image frame shift in radians.
NumFrames is the number of frames over which these frame shifts were accumulated.
DeltaT is the time interval in milliseconds over which these frame shifts were accumulated.
References GimbalPkt_t::Data, FinishGimbalPacket(), FRAME_SHIFTS_GIMBAL_PKTTYPE, GIMBAL_DYNAMICS_INFORMATION_GROUP, RoundFloatToSInt16(), SInt16ToData(), and UInt16ToData().
void FormGimbalAglPacket (GimbalPkt_t * pPkt, UInt16 AglMeters, BOOL AglValid)
Tell the gimbal what its AGL altitude is.
References GimbalPkt_t::Data, FinishGimbalPacket(), GIMBAL_AGL_PKTTYPE, GIMBAL_COMMAND_AND_CONTROL_GROUP, and UInt16ToData().
void FormGimbalAxisSettingsPacket (GimbalPkt_t * pPkt, const float NoGoCenter[NGIMBAL_SHORT], const float NoGoRange[NGIMBAL_SHORT], const float MaxRate[NGIMBAL_SHORT], const float MaxAccel[NGIMBAL_SHORT], const float PosGain[NGIMBAL_SHORT], const float VelGain[NGIMBAL_SHORT], const float DerGain[NGIMBAL_SHORT], BOOL Temporary, BOOL Factory)
Create a gimbal axis control packet.
Create a gimbal axis settings packet which contains the data to setup the axis control for custom configurations.
Parameters
pPkt points to a gimbal packet to be formatted.
NoGoCenter is the center of the no go range in radians for all gimbal axis.
NoGoRange is the size of the no go range in radians for all gimbal axis. Zero is free-running. More than 2PI is do not change center or range.
MaxRate is the max rate in radians per second for all gimbal axis. Less than zero is do not change.
MaxAccel is the max accelerating in radians per second per second for all gimbal axis. Less than zero is do not change.
PosGain is the position gain in angle per second per angle error. Less than zero is do not change.
VelGain is the velocity feedforward gain, less than zero is do not change.
DerGain is the aceleration feedforward gain, less than zer is do not change.
Temporary should be zero to make settings permanent.
Factory should be set to TRUE to send the factory settings instead of the user settings.
References AXIS_SETTINGS_GIMBAL_PKTTYPE, GimbalPkt_t::Data, FACTORY_AXIS_SETTINGS_GIMBAL_PKTTYPE, FinishGimbalPacket(), GIMBAL_SETUP_GROUP, NGIMBAL_SHORT, RoundToSInt16(), RoundToUInt16(), RoundToUInt8(), SInt16ToData(), and UInt16ToData().
Referenced by CommBase_SendGimbalAxisSettingsPacket().
void FormGimbalCameraAlignPacket (GimbalPkt_t * pPkt, float Zoom1, const float Error1[NGIMBAL], float Zoom2, const float Error2[NGIMBAL], UInt8 Camera, BOOL Factory)
Create a gimbal camera alignment packet.
Form a gimbal packet which sets the camera alignment numbers.
Parameters
pPkt receives the formatted packet.
Zoom1 is the zoom ration of the first alignment.
Error1 is the pan, tilt, and roll alignemnt errors at zoom1 [rad].
Zoom2 is the zoom ration of the second alignment.
Error2 is the pan, tilt, and roll alignemnt errors at zoom2 [rad].
Camera enumerates the camera that this data apply to.
Factory should be TRUE to send the facotry settings.
References CAMERA_ALIGN_GIMBAL_PKTTYPE, GimbalPkt_t::Data, FACTORY_CAMERA_ALIGN_GIMBAL_PKTTYPE, FinishGimbalPacket(), GIMBAL_SETUP_GROUP, N3D, RoundToSInt16(), RoundToUInt16(), SInt16ToData(), and UInt16ToData().
Referenced by CommBase_SendGimbalCameraAlignPacket().
void FormGimbalCameraCmdPacket (GimbalPkt_t * pPkt, UInt8 Camera, float HFOV, UInt16 Focus, UInt8 Mode, UInt8 Shutter, UInt8 Bright, UInt8 Flags)
Create a camera command packet containing the field of view and focus.
Create a camera command packet containing the field of view and focus.
Parameters
pPkt receives the formated gimbal packet.
Camera identifies the camera to control.
HFOV is the horizontal field of view in radians, or (if negative) the camera zoom ratio. 0.0 is do not change.
Focus is the focus length in millimeters, 0xFFFF is do not change, 0xFFFE is infinite, 0xFFFD is trigger, 0x0000 is auto.
Mode is the exposure mode: 0 for auto, 1 for shutter priority, 2 for bright mode. 0xFF is do not change
Shutter is the shutter speed. 0xFF is do not change
Bright is the bright mode setting, 0xFF is do not change.
Flags is the camera flag settings, set MSB for do not change.
References CAMERA_CMD_GIMBAL_PKTTYPE, GimbalPkt_t::Data, FinishGimbalPacket(), GIMBAL_COMMAND_AND_CONTROL_GROUP, RoundToSInt16(), SInt16ToData(), and UInt16ToData().
Referenced by CommBase_SendGimbalCameraCmdPacket().
void FormGimbalCameraZoomPacket (GimbalPkt_t * pPkt, UInt8 Camera, SInt8 Rate, float Timeout)
Create the gimbal camera zoom packet.
Create the gimbal camera zoom packet which provides continuous zoom control.
Parameters
pPkt receives the formatted packet.
Camera designates the camera to command, 0xFF to use the current active camera.
Rate is the zoom rate from -8 to 8.
Timeout is the time to apply the zoom, in seconds.
References CAMERA_ZOOM_GIMBAL_PKTTYPE, GimbalPkt_t::Data, FinishGimbalPacket(), GIMBAL_COMMAND_AND_CONTROL_GROUP, and RoundToUInt8().
void FormGimbalEnhancementCommand (GimbalPkt_t * pPkt, BOOL Enabled, UInt8 Intensity, UInt8 Limit)
Form the image enhancement command packet.
References GimbalPkt_t::Data, ENHANCEMENT_CMD_GIMBAL_PKTTYPE, FinishGimbalPacket(), and GIMBAL_COMMAND_AND_CONTROL_GROUP.
void FormGimbalFilterPacket (GimbalPkt_t * pPkt, float Cutoff, float Deadband)
Create a gimbal filter packet.
Create a gimbal filter packet
Parameters
pPkt receives the formatted packet
Cutoff is the gyro cutoff frequency in Hertz.
Deadband is the gyro deadband in radians per second.
References GimbalPkt_t::Data, FinishGimbalPacket(), GIMBAL_SETUP_GROUP, RoundToUInt8(), and SENSOR_FILTER_GIMBAL_PKTTYPE.
void FormGimbalFLIRConfigurationPacket (GimbalPkt_t * pPkt, const FLIRConfig_t * pConfig)
Form a packet with FLIR configuration information.
Form a packet with the FLIR specific camera configuration data.
Parameters
pPkt points to the packet to form
pConfig is the configuration details.
References FLIRConfig_t::AGCMaxGain, FLIRConfig_t::AgcRoiPercent, FLIRConfig_t::AGCType, FLIRConfig_t::BrightBias, FLIRConfig_t::Brightness, FLIRConfig_t::ColorLUT, FLIRConfig_t::Constrast, GimbalPkt_t::Data, FinishGimbalPacket(), FLIR_CONFIGURATION_GIMBAL_PKTTYPE, GIMBAL_SETUP_GROUP, FLIRConfig_t::IntegrationTime, FLIRConfig_t::ITTMean, FLIRConfig_t::PlateauLevel, SInt16ToData(), and UInt16ToData().
void FormGimbalGPSLeverArmPacket (GimbalPkt_t * pPkt, const float Arm[N3D])
Create a gimbal GPS lever arm packet.
Form a gimbal packet which sets the GPS lever arm, the distance from the IMU to the GPS antenna.
Parameters
pPkt receives the formatted packet.
Arm contains the X, Y, and Z lever distances in meters.
References GimbalPkt_t::Data, FinishGimbalPacket(), GIMBAL_SETUP_GROUP, GPS_LEVER_ARM_GIMBAL_PKTTYPE, N3D, RoundToSInt16(), and SInt16ToData().
void FormGimbalIRCamConfigurationPacket (GimbalPkt_t * pPkt, const IRCamConfig_t * pConfig)
Form a packet with IRCam IR configuration information.
Form a packet with the T500 IR specific camera configuration data.
Parameters
pPkt points to the packet to form
pConfig is the configuration details.
References IRCamConfig_t::AGLCMode, IRCamConfig_t::AGLCRoi, IRCamConfig_t::Background, IRCamConfig_t::Brightness, IRCamConfig_t::Contrast, GimbalPkt_t::Data, FinishGimbalPacket(), IRCamConfig_t::Flags, IRCamConfig_t::Foreground, GIMBAL_SETUP_GROUP, IRCAM_CONFIGURATION_GIMBAL_PKTTYPE, IRCamFlags_t::LAPState, IRCamFlags_t::NRFState, IRCamConfig_t::OperationMode, IRCamFlags_t::ResetAGLC, IRCamFlags_t::ResetLAP, SInt16ToData(), and UInt16ToData().
void FormGimbalIRCamSaveRestorePacket (GimbalPkt_t * pPkt, UInt8 ConfigAction)
Form a packet to save/restore IRCam IR configuration information.
Form a packet to save/restore T500 IR configuration information.
Parameters
pPkt points to the packet to form.
ConfigAction is the configuration action identifier.
References GimbalPkt_t::Data, FinishGimbalPacket(), GIMBAL_SETUP_GROUP, and IRCAM_SAVE_RESTORE_GIMBAL_PKTTYPE.
void FormGimbalKLVDetailsPacket (GimbalPkt_t * pPkt, const KLVDetails_t * pKLV)
Form a packet with the KLV details.
Form a packet with the KLV details
Parameters
pPkt points to a autopilot packet.
pKLV are the KLV details.
References KLVDetails_t::Caveats, KLVDetails_t::Classification, KLVDetails_t::ClassifyingCountry, KLVDetails_t::ClassifyingCountryCodeMethod, GimbalPkt_t::Data, FinishGimbalPacket(), GIMBAL_SETUP_GROUP, KLV_DETAILS_GIMBAL_PKTTYPE, KLVDetails_t::MissionID, KLVDetails_t::ObjectCountryCodeMethod, KLVDetails_t::ObjectCountryCodes, KLVDetails_t::PlatformDesignation, KLVDetails_t::ReleasingInstructions, and KLVDetails_t::SCI_SCH.
void FormGimbalLaserArmCmdPacket (GimbalPkt_t * pPkt, UInt8 LaserIndex, BOOL Arm)
Create a laser arm command.
Create a laser arm command packet.
Parameters
pPkt receives the formatted packet.
LaserIndex identifies the laser to command.
Arm should be TRUE to arm the laser.
References GimbalPkt_t::Data, FinishGimbalPacket(), GIMBAL_COMMAND_AND_CONTROL_GROUP, and LASER_ARM_CMD_GIMBAL_PKTTYPE.
Referenced by CommBase_SendGimbalLaserArmPacket().
void FormGimbalLaserFireCmdPacket (GimbalPkt_t * pPkt, UInt8 LaserIndex, UInt8 Power)
Create a laser fire command.
Create a laser fire command packet.
Parameters
pPkt receives the formatted packet.
LaserIndex identifies the laser to command.
Power gives the percent of full power from 0 to 100 with which to fire.
References GimbalPkt_t::Data, FinishGimbalPacket(), GIMBAL_COMMAND_AND_CONTROL_GROUP, and LASER_FIRE_CMD_GIMBAL_PKTTYPE.
Referenced by CommBase_SendGimbalLaserFirePacket().
void FormGimbalLasersInstalledPacket (GimbalPkt_t * pPkt, const LaserSetup_t Lasers[NUM_LASERS], BOOL Factory)
Create a lasers installed packet.
Create a lasers installed packet
Parameters
pPkt receives the formatted packet.
Lasers contains the laser setup information to put in the packet.
Factory should be TRUE to change the factory settings as well as the live settings.
References GimbalPkt_t::Data, FACTORY_LASERS_INSTALLED_GIMBAL_PKTTYPE, FinishGimbalPacket(), GIMBAL_SETUP_GROUP, LASERS_INSTALLED_GIMBAL_PKTTYPE, NUM_LASERS, RoundToUInt16(), RoundToUInt8(), and UInt16ToData().
Referenced by CommBase_SendGimbalLaserSetupPacket().
void FormGimbalMagCalPacket (GimbalPkt_t * pPkt, const float HardIronErr[N3D], const float ScaleFactErr[N3D])
Form a packet with the magnetometer calibration data.
Form a packet with the magnetometer calibration data.
Parameters
pPkt points to a autopilot packet;
HardIronErr is a vector of hard iron errors;
ScaleFactErr is a vector of scale factor errors.
References GimbalPkt_t::Data, FinishGimbalPacket(), FloatToData(), GIMBAL_SETUP_GROUP, MAG_CAL_GIMBAL_PKTTYPE, and N3D.
void FormGimbalRadioSettings (GimbalPkt_t * pPkt, const RadioSettings_t * pSettings)
Form a radio settings packet for the gimbal.
Form a radio settings packet for the gimbal
Parameters
pPkt receives the formatted packet.
pSettings are the settings to put in the packet.
References GIMBAL_COMMAND_AND_CONTROL_GROUP, and RADIO_SETUP_GIMBAL_PKTTYPE.
void FormGimbalRetractDeployCmdPacket (GimbalPkt_t * pPkt, UInt32 Deploy)
Create a 3AX retract or deploy command packet.
Create a 3AX retract or deploy command packet.
Parameters
pPkt receives the formatted packet.
Deploy is the command, 0 for retract, 1 for deploy, 2 for halt.
References GimbalPkt_t::Data, FinishGimbalPacket(), GIMBAL_COMMAND_AND_CONTROL_GROUP, and RETRACT_DEPLOY_CMD_GIMBAL_PKTTYPE.
Referenced by CommBase_SendGimbalRetractDeployCmdPacket().
void FormGimbalRetractorConfigurationPacket (GimbalPkt_t * pPkt, const Retractor_t * pRetractor)
Form a packet with the retractor configuration data.
Form a packet with the retractor configuration data.
Parameters
pPkt points to the packet to form
pRetractor is the configuration details.
References GimbalPkt_t::Data, Retractor_t::DeployAtStart, Retractor_t::DesiredDeploy, Retractor_t::DoorClosePWM, Retractor_t::DoorOpenPWM, FinishGimbalPacket(), GIMBAL_SETUP_GROUP, Retractor_t::LockPWM, Retractor_t::RetractAtStart, Retractor_t::RetractDownPWM, Retractor_t::RetractNeutralPWM, RETRACTOR_CONFIG_GIMBAL_PKTTYPE, Retractor_t::RetractorType, Retractor_t::RetractPan, Retractor_t::RetractTilt, Retractor_t::RetractUpPWM, RoundToSInt16(), Retractor_t::SafeToMove, SInt16ToData(), UInt16ToData(), and Retractor_t::UnlockPWM.
void FormGimbalRigTestCmdPacket (GimbalPkt_t * pPkt, float MaxSpeed, float MaxAccel, UInt16 Time)
Create a gimbal rig test packet.
Create a gimbal rig test packet.
Parameters
pPkt points to the packet to format
MaxSpeed is the maximum rate of the rig test should run (rad/s).
MaxAccel is the maximum acceleration of the rig test (rad/s/s).
Time is the number of seconds to run the rig test for.
References GimbalPkt_t::Data, FinishGimbalPacket(), GIMBAL_COMMAND_AND_CONTROL_GROUP, RIG_TEST_CMD_GIMBAL_PKTTYPE, RoundToUInt16(), and UInt16ToData().
void FormGimbalSensorConfigPacket (GimbalPkt_t * pPkt, const float Rotation[N3D], GimbalSensorFlags_t Flags)
Form a packet with the sensor configuration data.
Form a packet with the sensor configuration data
Parameters
pPkt points to a autopilot packet.
Rotation is a vector of rotations in radians
Flags are the sensor configuration falgs.
References GimbalPkt_t::Data, GimbalSensorFlags_t::DisableuBloxSBAS, FinishGimbalPacket(), GIMBAL_SETUP_GROUP, N3D, RoundToSInt16(), SENSOR_CONFIGURATION_GIMBAL_PKTTYPE, SInt16ToData(), UInt32ToData(), GimbalSensorFlags_t::UseExtAttitude, GimbalSensorFlags_t::UseExtHeading, GimbalSensorFlags_t::UseInternalMag, GimbalSensorFlags_t::UseNovatelAlign, and GimbalSensorFlags_t::UseVPSHeading.
void FormGimbalSerialInterfacePacket (GimbalPkt_t * pPkt, const GimbalSerial_t Interface[6], BOOL Temporary)
Create a serial interface setup packet.
Form a gimbal packet configures the serial interfaces
Parameters
pPkt receives the formatted packet.
Interface is the interface data to encode.
Temporary should be zero to make settings permanent.
References GimbalSerial_t::Angle, GimbalSerial_t::Baud, GimbalPkt_t::Data, FinishGimbalPacket(), GimbalSerial_t::Georef, GIMBAL_SETUP_GROUP, GimbalSerial_t::Protocol, GimbalSerial_t::Rate, and SERIAL_INTERFACE_GIMBAL_PKTTYPE.
Referenced by CommBase_SendGimbalSerialInterfacePacket().
void FormGimbalSPOICmdPacket (GimbalPkt_t * pPkt, const double Pos[NPOS], const float Vel[NDIR], UInt8 Flags)
Create a gimbal sensor point of interest packet containing the position of the SPOI.
Form a gimbal sensor point of interest (SPOI) cmd packet. The SPOI packet tells the gimbal where to point in LLA coordinates relative to the WGS-84 ellipsoid.
Parameters
pPkt points to a gimbal packet to be formatted.
Pos is the position of the SPOI in Lat[rad], Lon[rad], Alt[m].
Vel is the velocity of the SPOI in North, East, Down [m/s].
Flags are the packet flags
References ALT, GimbalPkt_t::Data, DOWN, EAST, FinishGimbalPacket(), GIMBAL_POSITION_INFORMATION_GROUP, LAT, LON, NORTH, RoundToSInt16(), RoundToSInt32(), SInt16ToData(), SInt32ToData(), and SPOI_CMD_GIMBAL_PKTTYPE.
Referenced by CommBase_SendGimbalSPOICmdPacket().
void FormGimbalTargetLocationEstimate (GimbalPkt_t * pPkt, const double PosLLA[NPOS], UInt32 GPSTOW, UInt8 source, UInt8 error)
Create a target location estimate packet.
Create a target location estimate packet for sending to the gimbal.
Parameters
pPkt receives the formatted packet.
PosLLA is the position estimate in latitude [rad], longitude [rad], altitude [m].
GPSTOW is the GPS time of week in milliseconds at which this position applies.
source is a bitfield that specifies source of data.
error is a bitfield that specifies error flags.
References ALT, GimbalPkt_t::Data, FinishGimbalPacket(), GIMBAL_POSITION_INFORMATION_GROUP, LAT, LON, RoundToSInt32(), SInt32ToData(), TARGET_LOCATION_ESTIMATE_GIMBAL_PKTTYPE, and UInt32ToData().
void FormGimbalTrackCommand (GimbalPkt_t * pPkt, float InitialX, float InitialY, UInt8 Algorithm, UInt8 Size, UInt8 Stamp)
Form the track command packet.
Form the track command packet
Parameters
pPkt receives the formatted packet.
InitialX is the initial horizontal track position in radians.
InitialY is the initial vertical track position in radians.
Algorithm is the algorithm choice enumeration.
Size is the size of the tracking window in pixels.
Stamp is the video counter stamp that goes with this track command, 255 if no stamp.
References GimbalPkt_t::Data, FinishGimbalPacket(), GIMBAL_COMMAND_AND_CONTROL_GROUP, RoundToSInt16(), SInt16ToData(), and TRACKER_CMD_GIMBAL_PKTTYPE.
Referenced by CommBase_SendGimbalTrackCmdPacket().
void FormGimbalTrackerSettingsAdvancedCommand (GimbalPkt_t * pPkt, float GainP, float GainI, float GainD, float RateLimit, float Deadband, BOOL Factory)
Form the advanced settings packet.
Form the tracker settings (advanced) packet.
Parameters
pPkt is the packet to format.
GainP is the PID Controller P-Term
GainI is the PID Controller I-Term
GainD is the PID Controller D-Term
RateLimit is the Maximum Rate (Radians / Second) to command
Deadband is the Deadband, expressed as a percent of current FOV
Factory is whether this is a user or factory packet.
References GimbalPkt_t::Data, FACTORY_TRACKER_ADV_CMD_GIMBAL_PKTTYPE, FinishGimbalPacket(), GIMBAL_SETUP_GROUP, RoundToUInt16(), RoundToUInt8(), TRACKER_ADV_CMD_GIMBAL_PKTTYPE, and UInt16ToData().
void FormGimbalTrackingData (GimbalPkt_t * pPkt, const float GimbalAngles[NGIMBAL], const float CameraAngles[NAXIS], float HFOV, float Range, UInt8 Mode)
Create a packet that has the gimbal tracking data in it.
Create a packet that has the gimbal tracking data in it
Parameters
pPkt receives the fully formed packet.
GimbalAngles are the pan and tilt w.r.t the gimbal in radians.
CameraAngles are the yaw and pitch w.r.t inertial space in radians.
HFOV is the horizotnal field on view in radians.
Range is the laser range, -1 for no range.
Mode is the gimbal mode of operation.
References GimbalPkt_t::Data, FinishGimbalPacket(), GIMBAL_DYNAMICS_INFORMATION_GROUP, GIMBAL_PAN, GIMBAL_TILT, PITCH_AXIS, RoundToSInt16(), RoundToUInt24(), SInt16ToData(), TRACKING_DATA_GIMBAL_PKTTYPE, UInt24ToData(), and YAW_AXIS.
void FormGimbalWaterMarkPacket (GimbalPkt_t * pPkt, UInt8 Format, UInt8 Status, UInt32 Sequence, const UInt8 * pImageData, UInt8 Size)
Form a packet to send watermark payload data.
Form a packet to send watermark payload data.
Parameters
pPkt receives the formatted packet.
Format is the format of the watermark image data.
Status is the status of the watermark image data.
Sequence is the sequence number of the watermark image data.
pImageData points to the the watermark image data.
Size is the number of bytes of watermark image data.
References GimbalPkt_t::Data, FinishGimbalPacket(), GIMBAL_SETUP_GROUP, GIMBAL_WATERMARK_DATA_PKTTYPE, and UInt24ToData().
void FormHdControlSettings (GimbalPkt_t * pPkt, HDControlSettings_t Settings, BOOL Factory)
Encode an HD control settings packet which defines how the gimbal will process HD video.
Parameters
pPkt Pointer to the packet to form
Settings The HD control settings
Factory should be TRUE to send the factory definitions, instead of the user definitions.
References GimbalPkt_t::Data, FACTORY_HD_CONTROL_SETTINGS_PKTTYPE, FinishGimbalPacket(), GIMBAL_SETUP_GROUP, and HD_CONTROL_SETTINGS_PKTTYPE.
void FormLaserEnablePswdPacket (GimbalPkt_t * pPkt, UInt16 pswd, BOOL ByPassAgl)
Form a packet with the password to enable laser operations.
References GimbalPkt_t::Data, FinishGimbalPacket(), GIMBAL_COMMAND_AND_CONTROL_GROUP, LASER_PASSWORD_ENABLER_PKTTYPE, and UInt16ToData().
void FormLaserSafetyStatus (GimbalPkt_t * pPkt, BOOL BypassSafety, UInt8 flags)
Create a laser status and safety packet.
Create a laser status and safety packet
Parameters
pPkt is the packet to decode.
BypassSafety contains the status of bypassing(TRUE) or invoking(FALSE) safety rules at the auto pilot
flags contains the safety flags that are violated, if any, in packets adressed to the host, otherwise these flags are ignored.
References GimbalPkt_t::Data, FinishGimbalPacket(), GIMBAL_COMMAND_AND_CONTROL_GROUP, and LASER_SAFETY_STATUS_PKTTYPE.
void FormLaserWatchdogPacket (GimbalPkt_t * pPkt, UInt8 LaserIndex)
Form a laser watchdog packet for the laser with index LaserIndex;.
Form a laser watchdog packet for the laser with index LaserIndex;.
References GimbalPkt_t::Data, FinishGimbalPacket(), GIMBAL_COMMAND_AND_CONTROL_GROUP, and LASER_WATCHDOG_PKTTYPE.
void FormLensCalFocusPacket (GimbalPkt_t * pPkt, UInt8 CameraIndex, UInt8 RowIndex, float Temperature, const SInt16 Focuses[AF_CAL_POINTS], UInt8 NumEntries)
Form a packet that specifies the temperature and focus points of a pre-focus calibration table.
Form a packet that specifies the temperature and focus points of a pre-focus calibration table.
Parameters
pPkt receives the formatted packet.
CameraIndex is the index of the camera/lens being updated.
RowIndex is the index of the table row being updated.
Temperature is the calibration temperature in degrees Celcius for the designated row.
Focuses is the array of focus encoder positions in the table.
NumEntries is number of entries in the table, up to AF_CAL_POINTS.
References AF_CAL_POINTS, GimbalPkt_t::Data, FinishGimbalPacket(), GIMBAL_SETUP_GROUP, LENS_CAL_FOCUS_CONFIGURATION, RoundFloatToSInt16(), and SInt16ToData().
void FormLensCalZoomPacket (GimbalPkt_t * pPkt, UInt8 CameraIndex, const SInt16 Zooms[26], UInt8 NumEntries)
Form a packet that specifies the zoom points of a pre-focus calibration table.
Referenced by DecodeLensPrefocusPacket().
void FormLensDevCommandPacket (GimbalPkt_t * pPkt, UInt8 CameraId, UInt8 ControlType, UInt8 InitFlag, SInt16 Position)
Form a packet to directly command a Microblaze controlled lens.
Form a packet to directly command a Microblaze controlled lens.
Parameters
pPkt receives the formatted packet.
CameraId is the identifier of the camera with the lens that this command applies.
ControlType indicates which lens control this command applies, i.e. zoom, focus.
InitFlag is a indicator if the lens should perform a high, low, or reinit.
Position is the commanded encoder position, 0x7FFF for do not change.
References GimbalPkt_t::Data, FinishGimbalPacket(), MB_LENS_COMMAND_PKTTYPE, MICROBLAZE_DEVELOPMENT_GROUP, and SInt16ToData().
void FormLensPrefocusPacket (GimbalPkt_t * pPkt, UInt8 CameraIndex, UInt8 LensType, const float Zooms[10], const UInt16 Focuses[10], UInt8 NumEntries)
Form a packet that specifies the pre-focus calibration table.
Form a packet that specifies the pre-focus calibration table.
Parameters
pPkt receives the formatted packet.
CameraIndex is the index of the camera/lens being updated.
LensType is the type of lens.
Zooms is the array of zoom ratios in the table.
Focuses is the array of focus values in the table.
NumEntries is number of entries in the table, up to 10.
References GimbalPkt_t::Data, FinishGimbalPacket(), GIMBAL_SETUP_GROUP, LENS_PREFOCUS_CONFIGURATION, RoundFloatToUInt16(), and UInt16ToData().
void FormLensRegisterPacket (GimbalPkt_t * pPkt, UInt8 CameraId, UInt8 ControlType, UInt16 Address, UInt32 Value, BOOL Write)
Form a packet to set a lens register value.
Form a packet to read/write a lens register value.
Parameters
pPkt receives the formatted packet.
CameraId is the identifier of the camera with the lens that this command applies.
ControlType indicates which lens control this command applies, i.e. zoom, focus.
Address is the address of which to set the value for.
Value is the value to set at the designated register.
Write is TRUE if this is a register write, otherwise a read request.
References GimbalPkt_t::Data, FinishGimbalPacket(), MB_LENS_REGISTER_PKTTYPE, MICROBLAZE_DEVELOPMENT_GROUP, UInt16ToData(), and UInt32ToData().
void FormMC_AxisParamPacket (GimbalPkt_t * pPkt, float InPanKp, float InPanKi, float InPanKd, float InTiltKp, float InTiltKi, float InTiltKd, float OutPanKp, float OutPanKi, float OutPanKd, float OutTiltKp, float OutTiltKi, float OutTiltKd, BOOL Factory)
Form a motion control axis parameter packet.
Form a motion control axis parameter packet.
Parameters
pPkt receives the formatted packet.
InPanKp Inner pan Kp value.
InPanKi Inner pan Ki value.
InPanKd Inner pan Kd value.
InTiltKp Inner tilt Kp value.
InTiltKi Inner tilt Ki value.
InTiltKd Inner tilt Kd value.
OutPanKp Outer pan Kp value.
OutPanKi Outer pan Ki value.
OutPanKd Outer pan Kd value.
OutTiltKp Outer tilt Kp value.
OutTiltKi Outer tilt Ki value.
OutTiltKd Outer tilt Kd value.
Factory Flags if this is a factory definition
References AXIS_PARAMS, AXIS_PARAMS_FACTORY, GimbalPkt_t::Data, FinishGimbalPacket(), FloatToData(), and GIMBAL_SETUP_GROUP.
void FormMC_DoMotionCalibrationPacket (GimbalPkt_t * pPkt, UInt16 Flags, UInt16 Type)
Form a motion control do calibration packet.
Form a motion control do calibration packet
Parameters
pPkt receives the formatted packet.
Flags Flags to define the do calibration command.
Type Type to define the do calibration command.
References GimbalPkt_t::Data, DO_MOTION_CALIBRATION, FinishGimbalPacket(), GIMBAL_COMMAND_AND_CONTROL_GROUP, and UInt16ToData().
void FormMC_LimitsPacket (GimbalPkt_t * pPkt, float PanMin, float PanMax, float TiltMin, float TiltMax, float PanRateMax, float TiltRateMax, float PanAccelMax, float TiltAccelMax, BOOL Factory)
Form a motion control limits packet.
Form a motion control axis limits packet
Parameters
pPkt receives the formatted packet.
PanMin The pan axis lower limit.
PanMax The pan axis upper limit.
TiltMin The tilt axis lower limit.
TiltMax The tilt axis upper limit.
PanRateMax The pan axis rate limit.
TiltRateMax The tilt axis rate limit.
PanAccelMax The pan axis acceleration limit.
TiltAccelMax The tilt axis acceleration limit.
Factory Flags if this is a factory definition
References AXIS_LIMITS, AXIS_LIMITS_FACTORY, GimbalPkt_t::Data, FinishGimbalPacket(), FloatToData(), and GIMBAL_SETUP_GROUP.
void FormMC_MotionCalibrationParamPacket (GimbalPkt_t * pPkt, const float Offsets[3], const float GainMatrix[9], BOOL Factory)
Form a motion control parameter packet.
Form a motion control parameter packet
Parameters
pPkt receives the formatted packet.
Offsets Gyro offsets in ADC counts aligned to gimbal indices
GainMatrix Cross-axis alignment data
Factory Flags if this is a factory definition
References GimbalPkt_t::Data, FinishGimbalPacket(), FloatToData(), GIMBAL_SETUP_GROUP, MOTION_CALIBRATION_PARAMS, and MOTION_CALIBRATION_PARAMS_FACTORY.
void FormMISBSettingsPacket (GimbalPkt_t * pPkt, const MISBConfig_t Data, BOOL Factory)
Form a video settings packet.
Form a MISB settings packet
Parameters
pPkt receives the formatted data.
Data the MISB settings data.
Factory indicates the user or factory version
References MISBConfig_t::BitRate, GimbalPkt_t::Data, FACTORY_MISB_SETTINGS_PKTTYPE, FinishGimbalPacket(), GIMBAL_SETUP_GROUP, MISBConfig_t::GOPSize, MISBConfig_t::IpAddress, MISB_SETTINGS_PKTTYPE, MISBConfig_t::Port, RoundFloatToUInt8(), UInt16ToData(), and UInt32ToData().
void FormScanModeControlPacket (GimbalPkt_t * pPkt, const GimbalScanControlConfig_t * pData)
Form a packet to enable and configure gimbal scan mode control.
Form a packet to enable and configure gimbal scan mode control.
Parameters
pPkt receives the formatted packet.
pData is the gimbal scan control configuration data structure.
References GimbalScanControlConfig_t::AxisRadius, GimbalScanControlConfig_t::CenterPosition, GimbalPkt_t::Data, GimbalScanControlConfig_t::Enabled, FinishGimbalPacket(), GIMBAL_COMMAND_AND_CONTROL_GROUP, GIMBAL_PAN, GIMBAL_SCAN_CONTROL_PKTTYPE, GIMBAL_TILT, GimbalScanControlConfig_t::RevPerSec, RoundFloatToSInt16(), RoundFloatToUInt8(), and SInt16ToData().
void FormSetLensDiagnosticsPacket (GimbalPkt_t * pPkt, UInt8 CameraId, BOOL Enabled)
Form a packet to enable/disable lens diagnostic reporting.
Form a packet to enable/diable lens diagnostic reporting
Parameters
pPkt receives the formatted packet.
CameraId is the identifier of the camera with the lens that this command applies.
Enabled is set to enable or disable diagnostics.
References GimbalPkt_t::Data, FinishGimbalPacket(), MB_ENABLE_LENS_DIAGNOSTICS, and MICROBLAZE_DEVELOPMENT_GROUP.
BOOL FormSPOIPathPointData (GimbalPkt_t * pPkt, const double PosECEF[MAX_SPOI_PATH_PTS][NPOS], UInt8 NumPoints)
Create a SPOI path point data packet.
Create a SPOI path point command data packet
Parameters
pPkt receives the fully formed packet.
PosECEF is the array of points
NumPoints is the number of points in the array.
Returns
TRUE if the encoding was successful, else FALSE if the path cannot be encoded, which could occur if the path is too long.
References GimbalPkt_t::Data, FinishGimbalPacket(), GIMBAL_POSITION_INFORMATION_GROUP, MAX_SPOI_PATH_PTS, N3D, RoundToUInt16(), RoundToUInt24(), SPOI_PATH_POINT_DATA_PKTTYPE, UInt16ToData(), and UInt24ToData().
void FormSPOIPathSettings (GimbalPkt_t * pPkt, UInt8 StepMode, float MaxVel, float ActiveRange, float ConvDist, float StepDist, UInt32 StepTime, float ScanRate)
Create a SPOI path navigator settings packet.
Create a SPOI path navigator settings packet.
Parameters
pPkt receives the fully formed packet.
StepMode is the SPOI step stare mode, 0=no stepping, 1=distance stepping, 2=time stepping.
MaxVel is the maximum SPOI velocity along the path, in m/s.
ActiveRange is the maximum range at which the SPOI position will be updated, in m.
ConvDist is the distance ahead of nearest point on the curve to which the SPOI will converge, in m.
StepDist is the stepping distance interval, if distance step-stare is enabled, in m.
StepTime is the stepping time interval, if time step-stare is enabled, in ms.
ScanRate is the scanning rate, if AutoScan is enabled, in radians.
References GimbalPkt_t::Data, FinishGimbalPacket(), FloatToData(), GIMBAL_SETUP_GROUP, RoundToSInt16(), SInt16ToData(), SPOI_PATH_PARAM_PKTTYPE, and UInt32ToData().
void FormStabDevT2Settings (GimbalPkt_t * pPkt, const SInt16 Gains[AC_NUM_GAINS])
Create a T2 development settings packet with motor controller gains.
Create a T2 development settings packet with motor controller gains.
Parameters
pPkt receives the formatted packet.
Gains contains the gains.
References GimbalPkt_t::Data, FinishGimbalPacket(), GIMBAL_DEVELOPMENT_GROUP, SInt16ToData(), and STAB_T2_SET_DEV_PKTTYPE.
void FormSuCsxConfigurationPacket (GimbalPkt_t * pPkt, const SuCsxCamConfig_t * pConfig)
Form a packet with SU CSX configuration information.
Form a packet with SU CSX configuration information.
Parameters
pPkt points to the packet to form
pConfig is the configuration details.
References SuCsxCamConfig_t::AgcCurVal, SuCsxCamConfig_t::AgcGain, SuCsxCamConfig_t::AgcHigh, SuCsxCamConfig_t::AgcLow, SuCsxCamFlags_t::AgcMode, SuCsxCamConfig_t::AgcStart, SuCsxCamFlags_t::CamMessage, SuCsxCamConfig_t::CamMessage, GimbalPkt_t::Data, SuCsxCamConfig_t::EnhanceAverage, SuCsxCamFlags_t::EnhanceMode, SuCsxCamConfig_t::EnhancePower, FinishGimbalPacket(), SuCsxCamConfig_t::Flags, GIMBAL_SETUP_GROUP, SuCsxCamFlags_t::OpMode, SUCSX_CONFIGURATION_GIMBAL_PKTTYPE, and UInt16ToData().
void FormSuCsxSaveRestorePacket (GimbalPkt_t * pPkt, UInt8 ConfigAction)
Form a packet to save/restore SU CSX configuration information.
Form a packet to save/restore SU CSX configuration information.
Parameters
pPkt points to the packet to form.
ConfigAction is the configuration action identifier.
References GimbalPkt_t::Data, FinishGimbalPacket(), GIMBAL_SETUP_GROUP, and SUCSX_SAVE_RESTORE_GIMBAL_PKTTYPE.
void FormVGSAntennaYaw (GimbalPkt_t * pPkt, float Yaw)
Form a packet that sets the current yaw angle of the antenna.
Form a packet that sets the current yaw angle of the antenna. This is used by the VGS to set the pan offset value.
Parameters
pPkt receives the formatted packet.
Yaw is the current true yaw angle of the antenna in radians.
References GimbalPkt_t::Data, FinishGimbalPacket(), RoundToSInt16(), SET_ANTENNA_YAW_VGS_PKTTYPE, SInt16ToData(), and VGS_COMMAND_AND_CONTROL_GROUP.
void FormVGSRadioSettings (GimbalPkt_t * pPkt, const RadioSettings_t * pSettings)
Form a radio settings packet for the video ground station.
Form a radio settings packet for the video ground station
Parameters
pPkt receives the formatted packet.
pSettings are the settings to put in the packet.
References RadioSettings_t::Channel, GimbalPkt_t::Data, DataToFloat(), FinishGimbalPacket(), FloatToData(), RadioSettings_t::Freq, RadioSettings_t::Power, RADIO_SETUP_VGS_PKTTYPE, RoundToUInt8(), GimbalPkt_t::Size, RadioSettings_t::Speed, RadioSettings_t::Type, and VGS_COMMAND_AND_CONTROL_GROUP.
void FormVps3OverlaySettings (GimbalPkt_t * pPkt, BOOL Enabled, VPS3Symbology_t * pSettings, float localTimeOffsetHours, BOOL localTimeDST, BOOL factory)
Encode VPS3 overlay settings packet which sets up all the on screen VPS overlays.
Parameters
pPkt Pointer to the packet to form
Enabled Global enabled flag
pSettings The overlay settings
factory should be TRUE to send the factory definitions, instead of the user definitions.
References VPS3SymbolFlags_t::AltFromBaro, VPS3SymbolFlags_t::AltLayout, VPS3SymbolFlags_t::AltSrcInUse, VPS3SymbolFlags_t::BitStatus, VPS3SymbolFlags_t::Brackets, VPS3SymbolFlags_t::Compass, VPS3SymbolFlags_t::Crosshair, GimbalPkt_t::Data, VPS3SymbolFlags_t::DateAndTime, VPS3SymbolFlags_t::DebugInfo, FACTORY_OVERLAY_SETTINGS_PKTTYPE, VPS3SymbolFlags_t::FaultStatus, FinishGimbalPacket(), FloatToData(), GIMBAL_SETUP_GROUP, VPS3SymbolFlags_t::GimbalAngles, VPS3SymbolFlags_t::GimbalHFov, VPS3SymbolFlags_t::GimbalPos, VPS3SymbolFlags_t::LocalTime, VPS3SymbolFlags_t::NoChange, OVERLAY_SETTINGS_PKTTYPE, VPS3SymbolFlags_t::Scale, VPS3SymbolFlags_t::TargetPos, VPS3SymbolFlags_t::TargetRange, VPS3SymbolFlags_t::TitleString, VPS3SymbolFlags_t::TrackBox, and UInt64ToData().
void FormVps3PiPSettings (GimbalPkt_t * pPkt, BOOL enabled, BOOL factory)
Encode VPS3 PiP settings packet which sets up PiP.
Parameters
pPkt Pointer to the packet to form
enabled Global enabled flag
factory should be TRUE to send the factory definitions, instead of the user definitions.
References GimbalPkt_t::Data, FACTORY_PICTURE_IN_PICTURE_SETTINGS_PKTTYPE, FinishGimbalPacket(), GIMBAL_SETUP_GROUP, and PICTURE_IN_PICTURE_SETTINGS_PKTTYPE.
SInt32 GetCameraStringName (const CameraDefinition_t * pCam, char * pName, UInt32 MaxSize)
Return a string description of the camera.
Get a ASCII text formatted string that includes the type of camera and lens information.
Parameters
pCam is the camera definitions.
pName receives the string.
MaxSize is the maximum number of string characters to encode.
Returns
The number of characters encoded or -1 if an error.
References CameraDefinition_t::AutoCameraType, CAMERA_TYPE_320_KTX, CAMERA_TYPE_640_CSX, CAMERA_TYPE_640_KTX, CAMERA_TYPE_DUMB_CAMERA, CAMERA_TYPE_HRC, CAMERA_TYPE_IRCAM, CAMERA_TYPE_NO_CAMERA, CAMERA_TYPE_PHOTON, CAMERA_TYPE_PROSILICA, CAMERA_TYPE_SONY, CAMERA_TYPE_SONY_XCL, CAMERA_TYPE_SU_JSX, CAMERA_TYPE_SWIRTAU, CAMERA_TYPE_TAU, CAMERA_TYPE_THERMO, CAMERA_TYPE_VPS_BLACKFLY_220, CAMERA_TYPE_VPS_BLACKFLY_345, CAMERA_TYPE_VPS_FLEA3C, CameraDefinition_t::ProtocolType, SONY_FCB_EH4300, SONY_FCB_EH6300, SONY_FCB_EH6500, SONY_FCB_EV7100, SONY_FCB_EV7500, SONY_FCB_EX1000, SONY_FCB_EX1000P, SONY_FCB_EX1010, SONY_FCB_EX1010P, SONY_FCB_EX1020, SONY_FCB_EX1020P, SONY_FCB_EX45MC, SONY_FCB_EX45MCC, SONY_FCB_EX480B, SONY_FCB_EX480BP, SONY_FCB_EX480C, SONY_FCB_EX480CP, SONY_FCB_EX48B, SONY_FCB_EX48BP, SONY_FCB_EX980, SONY_FCB_EX980P, SONY_FCB_EX980S, SONY_FCB_EX980SP, SONY_FCB_H10, SONY_FCB_H11, SONY_FCB_IX11, and SONY_FCB_IX11P.
SInt32 GetLensStringName (const CameraDefinition_t * pCam, char * pName, UInt32 MaxSize)
Return a string description of the lens.
Get a ASCII text formatted string that includes the type of camera and lens information.
Parameters
pCam is the camera definitions.
pName receives the string.
MaxSize is the maximum number of string characters to encode.
Returns
The number of characters encoded or -1 if an error.
References LENS_TYPE_CAMERA_SPECIFIED, LENS_TYPE_CCT_LWIR_DZOOM, LENS_TYPE_CCT_MWIR_CZOOM, LENS_TYPE_CCT_SWIR_CAT, LENS_TYPE_CCT_SWIR_FIXED, LENS_TYPE_GENERIC_CZOOM, LENS_TYPE_GENERIC_FIXED, LENS_TYPE_LENS_DOUBLER, LENS_TYPE_NO_LENS, CameraDefinition_t::LensType, CameraDefinition_t::MaxFocalLength, and CameraDefinition_t::MinFocalLength.
BOOL LookForGimbalPacketInByte (GimbalPkt_t * pPkt, UInt8 Byte)
Look for a gimbal packet in a series of bytes.
Search for a gimbal packet contained in a series of single bytes passed to this function on multiple calls. The packet storage provided by the caller MUST persist between calls, since this function will partially complete a packet and then return FALSE while waiting for more data to arrive.
Parameters
Byte contains the next piece of receive data.
pPkt points to a gimbal packet structure which must persist between calls.
Returns
TRUE if a packet is found, else FALSE.
References CalcGimbalPacketChecksum(), GimbalPkt_t::Data, GimbalPkt_t::Group, GimbalPkt_t::i, GimbalPkt_t::PktType, GimbalPkt_t::Size, GimbalPkt_t::State, GimbalPkt_t::Sync1, GimbalPkt_t::Sync2, and GimbalPkt_t::Sync3.
Referenced by LookForGimbalPacket(), and LookForGimbalPacketInQueue().
void MakeGimbalPacket (GimbalPkt_t * pPkt, UInt8 Group, UInt8 PktType, const UInt8 * pData, UInt8 Size)
Build a gimbal packet from passed data.
Form a gimbal packet from the passed parameters. The resulting packet will be ready to transmit.
Parameters
pPkt points to a gimbal packet structure which will be formatted.
Size is the amount of data to be included in the packet, not including the frame and subframe bytes.
Group is the packet group field.
PktType is the packet packet type field.
pData points to a buffer of data to be included in the packet.
Size is the amount of data to be included in the packet, not counting the group and packet type bytes.
References GimbalPkt_t::Data, and FinishGimbalPacket().
Referenced by CommBase_RequestGimbalAxisSettingsPacket(), CommBase_RequestGimbalCameraTypesPacket(), CommBase_RequestGimbalLaserSetupPacket(), and CommBase_RequestGimbalSPOICmdPacket().
void MakeGimbalPacketHeader (GimbalPkt_t * pPkt, UInt8 Group, UInt8 PktType, UInt8 Size)
Fill out a gimbal packet header.
Form the header of a packet from the passed parameters. The resulting packet will still need the data copied into it, and the checksum.
Parameters
pPkt points to a gimbal packet structure which will be formatted.
Group is the packet group field.
PktType is the packet packet type field.
Size is the amount of data to be included in the packet, not including the group and packet type bytes.
References GimbalPkt_t::Group, GimbalPkt_t::PktType, GimbalPkt_t::Size, GimbalPkt_t::Sync1, GimbalPkt_t::Sync2, and GimbalPkt_t::Sync3.
Referenced by CommBase_RequestGimbalCameraAlignPacket(), CommBase_RequestGimbalCameraCmdPacket(), and FinishGimbalPacket().
void SetLaserFixedParams (LaserSetup_t * pLaser)
Set laser parameters that are fixed based on laser type.
Set the fixed parameters for a laser.
Parameters
pLaser points to the laser to service.
References LaserSetup_t::Class, LaserSetup_t::Divergence, LASER_DESIGNATOR, LASER_ILLUMINATOR, LASER_POINTER, LASER_RANGER, LASER_TYPE_FLIR_CLI_30, LaserSetup_t::MinSafetyAGL, NO_LASER, LaserSetup_t::Power, LaserSetup_t::Protocol, LaserSetup_t::Type, and LaserSetup_t::Wavelength.
Referenced by DecodeGimbalLasersInstalledPacket().