Communications SDK: GimbalPacketUser.h File Reference
GimbalPacketUser.h File Reference
Gimbal packet encode and decode functionality.
#include "GimbalPacketGeneric.h"
Functions
BOOL DecodeGimbalVersionPacket (const GimbalPkt_t *pPkt, Version_t *pVersion, Board_t *pBoard, UInt8 LegacyTypes[NUM_CAMERAS], UInt8 ProtocolTypes[NUM_CAMERAS], float MaxHFOV[NUM_CAMERAS], float MinHFOV[NUM_CAMERAS], Version_t *pLensVersion, LensCtrlType_t *pLensType)
Interpret a gimbal system version packet.
BOOL DecodeGimbalVersion2Packet (const GimbalPkt_t *pPkt, Version_t *pVersion, Board_t *pBoard, UInt8 LegacyTypes[NUM_CAMERAS], UInt8 ProtocolTypes[NUM_CAMERAS], float MaxHFOV[NUM_CAMERAS], float MinHFOV[NUM_CAMERAS])
Interpret a newer gimbal system version packet.
BOOL DecodeLensControlVersionPacket (const GimbalPkt_t *pPkt, Version_t *pLensVersion, LensCtrlType_t *pLensType)
Interpret a gimbal lens control version packet.
void FormGimbalCmdPacket (GimbalPkt_t *pPkt, float Pan, float Tilt, SInt8 ZoomRate, float CamTimeout, UInt8 Flags, float ImpulseTime, SInt8 FocusRate, UInt8 Flags1)
Create a gimbal command packet containing pan, tilt, zoom, and mode.
BOOL DecodeGimbalAnglePacket (const GimbalPkt_t *pPkt, float *pPan, float *pTilt, float *pRoll)
Interpret a gimbal angle packet containing the pan, tilt, and roll positions.
BOOL DecodeGimbalRatePacket (const GimbalPkt_t *pPkt, float AxisRates[NGIMBAL], float MountRates[NGIMBAL], UInt32 *pTime, UInt8 *pMode)
Interpret a gimbal rate packet containing the position rate and inertial data.
void FormGimbalHostSensorPacket (GimbalPkt_t *pPkt, const float Rates[NAXIS], const float Accel[NAXIS], float TAS, UInt32 Time, UInt8 SampleRate, UInt8 Flags)
Create a gimbal host sensor packet which contains gimbal mount body rates from the host.
void FormGimbalHostAttitudePacket (GimbalPkt_t *pPkt, const float Attitude[NAXIS], UInt32 Time, UInt8 SampleRate, UInt8 Flags, float Baro)
Create a gimbal host attitude packets which contains the euler angles of the gimbal mount.
void FormGimbalHostGPSPacket (GimbalPkt_t *pPkt, const GPSData_t *pGPS, UInt32 Time, UInt8 Valid)
Create a gimbal host gps packet which contains GPS information from the host.
BOOL DecodeGimbalGeoreferencePacket (const GimbalPkt_t *pPkt, GimbalTelemetryData_t *pData)
Interpret a gimbal geo reference packet which contains the GPS and camera data from the gimbal.
BOOL DecodeGimbalTelemetryPacket (const GimbalPkt_t *pPkt, GimbalTelemetryData_t *pData)
Interpret a gimbal telemetry packet which contains the GPS and camera data from the gimbal.
BOOL DecodeGimbalRawVibrationPacket (const GimbalPkt_t *pPkt, UInt8 *pSensor, UInt16 *pSampleIndex, UInt16 Data[64], UInt16 *pOffset, float *pGain)
Decode the vibration data packet.
void FormVGSAntennaCommand (GimbalPkt_t *pPkt, float Pan, float Tilt, UInt8 Mode)
Decode the video ground station antenna control packet.
BOOL DecodeVGSTelemetry (const GimbalPkt_t *pPkt, VGSTelemetryData_t *pData)
Decode a telemetry packet for the video ground station.
BOOL DecodeGimbalStabDevTelemetry (const GimbalPkt_t *pPkt, UInt32 *uTime, float *Ref, float EncoderAngles[2], float CmdAngles[2], float EncoderRates[2], float CmdRates[2], float GyroRates[2], float Currents[2], float CmdCurrents[2])
Decode special stabilizer telemetry packet.
void FormGimbalInitialHeadingPacket (GimbalPkt_t *pPkt, float Heading)
Create the initial heading packet.
BOOL DecodeGimbalCurrentPacket (const GimbalPkt_t *pPkt, UInt32 *pTimeMs, float *pPanCur, float *pTiltCur, float *pPanCurCmd, float *pTiltCurCmd)
Create a packet containing current debugging info.
const char * DecodeGimbalUserWarningPacket (GimbalPkt_t *pPkt, UInt8 *pGroup, UInt8 *pType, UInt8 *pSeverity)
Decode the gimbal user warning packet.
BOOL DecodeGimbalResetReportPacket (const GimbalPkt_t *pPkt, UInt16 *pRSR, UInt16 *pVec, UInt32 *pPC, UInt32 *pMSR, UInt32 *pLink, UInt32 *pFPSCR)
Extract the data from a reset report packet.
BOOL DecodeGimbalDiagnosticsPacket (const GimbalPkt_t *pPkt, GimbalDiagnostics_t *pData)
Extract the data from a gimbal diagnostics packet.
const char * DecodeVps3UserWarningPacket (const GimbalPkt_t *pPkt, UInt8 *pGroup, UInt8 *pType, UInt8 *pSeverity, UInt16 *pWarnId)
Decode the VPS user warning packet.
BOOL DecodeVps3ResetReportPacket (const GimbalPkt_t *pPkt, Vps3Reset_t *pType, UInt32 *pAddress, UInt32 *pInfo)
Extract the data from a reset report packet.
BOOL DecodeVps3DiagnosticsPacket (const GimbalPkt_t *pPkt, Vps3Diagnostics_t *pVpsDiagnostics)
Extract the diagnostics data from the packet.
BOOL DecodeVps3VersionPacket (const GimbalPkt_t *pPkt, Version_t *pVersion)
Decode the VPS3 version packet.
const char * DecodeMbUserWarningPacket (const GimbalPkt_t *pPkt, UInt8 *pGroup, UInt8 *pType, UInt8 *pSeverity, UInt16 *pWarnId)
Decode a MB user warning packet.
BOOL DecodeMbResetReportPacket (const GimbalPkt_t *pPkt, MbReset_t *pType, UInt32 *pAddress, UInt32 *pInfo)
Decode a MB reset report packet.
BOOL DecodeMbAppVersionPacket (const GimbalPkt_t *pPkt, Version_t *pVersion)
Decode a MB app version packet.
BOOL DecodeFpgaBitVersionPacket (const GimbalPkt_t *pPkt, Version_t *pVersion)
Decode an FPGA bit version packet.
BOOL DecodeMotionCtrlVersionPacket (const GimbalPkt_t *pPkt, Version_t *pVersion)
Decode the motion control version packet.
BOOL DecodeMotionCtrlDiagnosticsPacket (const GimbalPkt_t *pPkt, MotionCtrlDiagnostics_t *pDiagnostics)
Extract the diagnostics data from the packet.
BOOL DecodeMicroblazeDiagnosticsPacket (const GimbalPkt_t *pPkt, MicroblazeDiagnostics_t *pDiagnostics)
Extract the diagnostics data from the packet.
Detailed Description
Gimbal packet encode and decode functionality.
Function Documentation
BOOL DecodeFpgaBitVersionPacket (const GimbalPkt_t * pPkt, Version_t * pVersion)
Decode an FPGA bit version packet.
Decode an FPGA reset report packet
Parameters
pPkt points to a packet containing the data.
pVersion points to a version struct for filling in with the packet's data.
Returns
TRUE if the packet is valid, else FALSE.
References GimbalPkt_t::Data, DataToUInt16(), Version_t::Date, Date_t::day, FPGA_BIT_VERSION_PKTTYPE, GIMBAL_SETUP_GROUP, GimbalPkt_t::Group, Version_t::MajorVersion, Version_t::MinorVersion, Date_t::month, Version_t::PatchNum, GimbalPkt_t::PktType, Version_t::Released, Version_t::Revision, GimbalPkt_t::Size, Version_t::SubVersion, and Date_t::year.
BOOL DecodeGimbalAnglePacket (const GimbalPkt_t * pPkt, float * pPan, float * pTilt, float * pRoll)
Interpret a gimbal angle packet containing the pan, tilt, and roll positions.
Decode a gimbal angle packet. The angle packet contains the position data for each gimbal axis, relative to the gimbal mount.
Parameters
pPkt points to a gimbal packet containing the data to be decoded.
pPan receives the pan axis position in radians.
pTilt receives the tilt axis position in radians.
pRoll receives the roll axis position in radians.
Returns
TRUE if the packet is OK, FALSE if it is bad.
References GimbalPkt_t::Data, DataToSInt16(), GIMBAL_ANGLE_GIMBAL_PKTTYPE, GIMBAL_DYNAMICS_INFORMATION_GROUP, GimbalPkt_t::Group, GimbalPkt_t::PktType, and GimbalPkt_t::Size.
BOOL DecodeGimbalCurrentPacket (const GimbalPkt_t * pPkt, UInt32 * pTimeMs, float * pPanCur, float * pTiltCur, float * pPanCurCmd, float * pTiltCurCmd)
Create a packet containing current debugging info.
Decode gimbal development packet reporting motor current.
Parameters
pPkt is th packet ot decode.
pTimeMs receives the system time in milliseconds.
pPanCur receives the pan current in Amps.
pTiltCur receives the tilt current in Amps.
pPanCurCmd receives the pan commanded current in Amps.
pTiltCurCmd receives the tilt commanded current in Amps.
Returns
TRUE if the packet was decoded, else FALSE if the packet is bad.
References CURRENT_DEV_PKTTYPE, GimbalPkt_t::Data, DataToSInt16(), DataToUInt32(), GIMBAL_DEVELOPMENT_GROUP, GimbalPkt_t::Group, GimbalPkt_t::PktType, and GimbalPkt_t::Size.
BOOL DecodeGimbalDiagnosticsPacket (const GimbalPkt_t * pPkt, GimbalDiagnostics_t * pData)
Extract the data from a gimbal diagnostics packet.
Extract the data from a gimbal diagnostics packet
Parameters
pPkt points to a packet containing the data.
pData receives the data from the packet.
Returns
TRUE if the packet is valid, else FALSE.
References GimbalDiagnostics_t::AvgPanMotorC, GimbalDiagnostics_t::AvgPanMotorV, GimbalDiagnostics_t::AvgTiltMotorC, GimbalDiagnostics_t::AvgTiltMotorV, GimbalDiagnostics_t::CameraCaseTemp, GimbalDiagnosticsFlags_t::CameraCaseTempIncluded, GimbalPkt_t::Data, DataToUInt16(), DataToUInt24(), DIAGNOSTIC_GIMBAL_PKTTYPE, GimbalDiagnostics_t::Flags, GIMBAL_STATUS_INFORMATION_GROUP, GimbalPkt_t::Group, GimbalDiagnostics_t::InputC, GimbalDiagnosticsFlags_t::InputPowerIncluded, GimbalDiagnostics_t::InputV, GimbalDiagnosticsFlags_t::InternalVPSPowerIncluded, GimbalDiagnostics_t::IntVPSBoardC, GimbalDiagnostics_t::IntVPSBoardV, GimbalDiagnosticsFlags_t::LaserDataIncluded, GimbalDiagnostics_t::LaserPointerTemp, GimbalDiagnostics_t::LogicBoardC, GimbalDiagnostics_t::LogicBoardCPU, GimbalDiagnostics_t::LogicBoardFault, GimbalDiagnostics_t::LogicBoardV, GimbalDiagnostics_t::LogicTemp, GimbalDiagnosticsFlags_t::MotorStatisticsIncluded, GimbalDiagnosticsFlags_t::MotorVoltageIncluded, GimbalDiagnostics_t::PanMotorCErr, GimbalDiagnostics_t::PanMotorVDev, GimbalDiagnostics_t::PayloadC, GimbalDiagnosticsFlags_t::PayloadDataIncluded, GimbalDiagnostics_t::PayloadHumidity, GimbalDiagnostics_t::PayloadTemp, GimbalDiagnostics_t::PayloadV, GimbalDiagnostics_t::PeakPanMotorC, GimbalDiagnostics_t::PeakTiltMotorC, GimbalPkt_t::PktType, GimbalPkt_t::Size, GimbalDiagnostics_t::TiltMotorCErr, GimbalDiagnostics_t::TiltMotorVDev, GimbalDiagnosticsFlags_t::VibrationDataIncluded, GimbalDiagnostics_t::VibrationP, GimbalDiagnostics_t::VibrationQ, GimbalDiagnostics_t::VibrationR, GimbalDiagnostics_t::VibrationX, GimbalDiagnostics_t::VibrationY, GimbalDiagnostics_t::VibrationZ, GimbalDiagnostics_t::VPSCPU, and GimbalDiagnosticsFlags_t::VPSCPUIncluded.
BOOL DecodeGimbalGeoreferencePacket (const GimbalPkt_t * pPkt, GimbalTelemetryData_t * pData)
Interpret a gimbal geo reference packet which contains the GPS and camera data from the gimbal.
Decode a gimbal geo reference packet which contains the GPS and camera data needed to georeference an image. Data is relative to the WGS-84 ellipsoid. This packet is deprecated and should only arrive from older gimbals
Parameters
pPkt points to a gimbal packet containing the data to be decoded.
pData receives the data.
Returns
TRUE if the packet is OK, FALSE if it is bad.
References NavStatus_t::AccBiasGood, NavStatus_t::AGLGood, GPSData_t::Alt, NavStatus_t::AttitudeGood, AUTO_FOCUS, NavStatus_t::BaroGood, GimbalTelemetryData_t::BoardTemp, LaserStatus_t::BypassSafety, GimbalTelemetryData_t::Camera, GimbalTelemetryData_t::CameraAttitude, GimbalPkt_t::Data, DataToSInt16(), DataToSInt32(), DataToUInt16(), DataToUInt24(), DataToUInt32(), GPSData_t::day, LaserStatus_t::DisableFlags, FOCUS_ONCE, GimbalTelemetryData_t::FocusMode, GimbalTelemetryData_t::FocusPos, GimbalTelemetryData_t::FPATemp, GEOREFERENCE_DATA_GIMBAL_PKTTYPE, GIMBAL_POSITION_INFORMATION_GROUP, GimbalTelemetryData_t::GimbalAngles, GimbalTelemetryData_t::GimbalAttitude, GimbalTelemetryData_t::GPS, GimbalPkt_t::Group, NavStatus_t::GyroBiasGood, NavStatus_t::HeadingGood, GimbalTelemetryData_t::HFOV, GPSData_t::hours, INFINITE_FOCUS, GimbalTelemetryData_t::Laser, LaserStatus_t::Laser0Armed, LaserStatus_t::Laser0Power, LaserStatus_t::Laser0PowerLimited, LaserStatus_t::Laser1Armed, LaserStatus_t::Laser1Power, LaserStatus_t::Laser1PowerLimited, LaserStatus_t::Laser2Armed, LaserStatus_t::Laser2Power, LaserStatus_t::Laser2PowerLimited, LaserStatus_t::Laser3Armed, LaserStatus_t::Laser3Power, LaserStatus_t::Laser3PowerLimited, GimbalTelemetryData_t::LaserRange, GPSData_t::Lat, GPSData_t::Lon, NavStatus_t::MagBiasGood, NavStatus_t::MagGood, MANUAL_FOCUS, GPSData_t::minutes, NavStatus_t::Mode, GimbalTelemetryData_t::Mode, GPSData_t::month, GimbalTelemetryData_t::NavStatus, NAXIS, GimbalTelemetryData_t::NumCameras, GPSData_t::PDOP, GimbalPkt_t::PktType, NavStatus_t::PositionGood, GPSData_t::seconds, GimbalPkt_t::Size, GPSData_t::Status, NavStatus_t::TASGood, GimbalTelemetryData_t::Time, GPSData_t::TrackedSats, GPSData_t::VDown, GPSData_t::VEast, NavStatus_t::VelocityGood, GimbalTelemetryData_t::VFOV, GimbalTelemetryData_t::VideoStamp, GPSData_t::VNorth, NavStatus_t::WindGood, and GPSData_t::year.
BOOL DecodeGimbalRatePacket (const GimbalPkt_t * pPkt, float AxisRates[NGIMBAL], float MountRates[NGIMBAL], UInt32 * pTime, UInt8 * pMode)
Interpret a gimbal rate packet containing the position rate and inertial data.
Decode a gimbal telemetry packet. This packet contains the gimbal angles, gimbal angel rates, and gimbal inertial rates.
Parameters
pPkt points to a gimbal packet containing the data to be extracted.
AxisRates receives the gimbal axis rates in radians/s, relative to the gimbal mount.
MountRates receives the gimbal mount rates in radians/s, which are inertially sensed.
pTime receives the gimbal system time in milliseconds.
pMode receives the gimbal mode.
Returns
TRUE if the packet is OK, FALSE if it is bad.
References GimbalPkt_t::Data, DataToSInt16(), DataToUInt32(), GIMBAL_DYNAMICS_INFORMATION_GROUP, GIMBAL_PAN, GIMBAL_RATE_GIMBAL_PKTTYPE, GIMBAL_ROLL, GIMBAL_TILT, GimbalPkt_t::Group, PITCH_AXIS, GimbalPkt_t::PktType, ROLL_AXIS, GimbalPkt_t::Size, and YAW_AXIS.
BOOL DecodeGimbalRawVibrationPacket (const GimbalPkt_t * pPkt, UInt8 * pSensor, UInt16 * pSampleIndex, UInt16 Data[64], UInt16 * pOffset, float * pGain)
Decode the vibration data packet.
Decode a gimbal raw vibration data packet. The raw vibration data packet contains 64 samples of raw sensor data sampled at high right.
Parameters
pPkt points to a autopilot packet containing the data to be decoded.
pSensor receives the sensor enumerator.
pSampleIndex receives the sample index, which which identifies where in the buffer of 1024 samples this data belong.
Data receives the samples.
pOffset receives the offset in counts of the data.
pGain receives the gain, in engineering units per count, of the data.
Returns
TRUE if the packet is valid, else FALSE.
References GimbalPkt_t::Data, DataToUInt16(), Float16ToFloat(), GIMBAL_DYNAMICS_INFORMATION_GROUP, GimbalPkt_t::Group, GimbalPkt_t::PktType, GimbalPkt_t::Size, and VIBRATION_DATA_GIMBAL_PKTTYPE.
BOOL DecodeGimbalResetReportPacket (const GimbalPkt_t * pPkt, UInt16 * pRSR, UInt16 * pVec, UInt32 * pPC, UInt32 * pMSR, UInt32 * pLink, UInt32 * pFPSCR)
Extract the data from a reset report packet.
Extract the data from a reset report packet
Parameters
pPkt points to a packet containing the data.
pRSR points to space receive the contents of the reset status register.
pVec points to space to receive the exception vector (if any).
pPC points to space to receive the exception program counter (if any).
pMSR points to space to receive the exception machine state register (if any).
pLink points to space to receive the link register (if any).
pFPSCR points to space to receive the floating point status and control register (if any).
Returns
TRUE if the packet is valid, else FALSE.
References GimbalPkt_t::Data, DataToUInt16(), DataToUInt32(), GIMBAL_STATUS_INFORMATION_GROUP, GimbalPkt_t::Group, GimbalPkt_t::PktType, RESET_REPORT_GIMBAL_PKTTYPE, and GimbalPkt_t::Size.
BOOL DecodeGimbalStabDevTelemetry (const GimbalPkt_t * pPkt, UInt32 * uTime, float * Ref, float EncoderAngles[2], float CmdAngles[2], float EncoderRates[2], float CmdRates[2], float GyroRates[2], float Currents[2], float CmdCurrents[2])
Decode special stabilizer telemetry packet.
Decode a telemetry packet for the stabilization development system
Parameters
pPkt is the packet to decode.
uTime is the system time in microseconds.
Ref is the reference angle in radians.
EncoderAngles are the pan and tilt angles measured by the encoders in radians.
CmdAngles are the commanded pan and tilt angles in radians.
EncoderRates are the pan and tilt rates measured by the encoders in radians per second.
CmdRates are the commanded pan and tilt rates in radians per second.
GyroRates are the measured pan and tilt rates in inerial space in radians per second.
Currents are the measured pan and tilt motor currents in Amps.
CmdCurrents are the command pan and tilt motor current in Amps.
References GimbalPkt_t::Data, DataToSInt16(), DataToUInt32(), GIMBAL_DEVELOPMENT_GROUP, GimbalPkt_t::Group, GimbalPkt_t::PktType, GimbalPkt_t::Size, and STAB_TELEM_DEV_PKTTYPE.
BOOL DecodeGimbalTelemetryPacket (const GimbalPkt_t * pPkt, GimbalTelemetryData_t * pData)
Interpret a gimbal telemetry packet which contains the GPS and camera data from the gimbal.
Decode a gimbal telemetry packet which contains the GPS and camera data needed to georeference an image. Data is relative to the WGS-84 ellipsoid.
Parameters
pPkt points to a gimbal packet containing the data to be decoded.
pData receives the data.
Returns
TRUE if the packet is OK, FALSE if it is bad.
References NavStatus_t::AccBiasGood, NavStatus_t::AGLGood, GimbalTelemetryData_t::AlignHeading, GimbalTelemetryData_t::AlignHeadingSigma, GimbalTelemetryData_t::AlignSolnType, GimbalTelemetryData_t::AlignTrackedSats, GimbalTelemetryData_t::AlignVisibleSats, GPSData_t::Alt, NavStatus_t::AttitudeGood, AUTO_FOCUS, GimbalTelemetryData_t::Baro, NavStatus_t::BaroGood, GimbalTelemetryFlags_t::BaroIncluded, GimbalTelemetryFlags_t::BaroInUse, GimbalTelemetryData_t::BoardTemp, LaserStatus_t::BypassSafety, GimbalTelemetryData_t::Camera, GimbalTelemetryData_t::CameraAttitude, GimbalTelemetryData_t::CameraIsInterlaced, GimbalPkt_t::Data, DataToSInt16(), DataToSInt32(), DataToUInt16(), DataToUInt24(), DataToUInt32(), GPSData_t::day, LaserStatus_t::DisableFlags, Euler2Quatf(), GimbalTelemetryFlags_t::ExtHdgIncluded, GimbalTelemetryData_t::ExtHeading, GimbalTelemetryData_t::Flags, FOCUS_ONCE, GimbalTelemetryData_t::FocusMode, GimbalTelemetryFlags_t::FocusModeIncluded, GimbalTelemetryData_t::FocusPos, GimbalTelemetryData_t::FPATemp, GimbalTelemetryFlags_t::FPATempIncluded, GIMBAL_PAN, GIMBAL_POSITION_INFORMATION_GROUP, GIMBAL_TELEMETRY_2_GIMBAL_PKTTYPE, GIMBAL_TELEMETRY_GIMBAL_PKTTYPE, GIMBAL_TILT, GimbalTelemetryData_t::GimbalAngles, GimbalTelemetryData_t::GimbalAttitude, GimbalTelemetryData_t::GimbalOnTime, GimbalTelemetryFlags_t::GimbalOnTimeIncluded, GimbalTelemetryData_t::GPS, gps_to_ymdhms(), GimbalTelemetryFlags_t::GPSExternal, GimbalPkt_t::Group, NavStatus_t::GyroBiasGood, NavStatus_t::HeadingGood, GimbalTelemetryData_t::HFOV, GPSData_t::hours, INFINITE_FOCUS, GimbalTelemetryFlags_t::INSAid, GPSData_t::ITOW, GimbalTelemetryData_t::Laser, LaserStatus_t::Laser0Armed, LaserStatus_t::Laser0Power, LaserStatus_t::Laser0PowerLimited, LaserStatus_t::Laser1Armed, LaserStatus_t::Laser1Power, LaserStatus_t::Laser1PowerLimited, LaserStatus_t::Laser2Armed, LaserStatus_t::Laser2Power, LaserStatus_t::Laser2PowerLimited, LaserStatus_t::Laser3Armed, LaserStatus_t::Laser3Power, LaserStatus_t::Laser3PowerLimited, GimbalTelemetryFlags_t::LaserIncluded, GimbalTelemetryData_t::LaserRange, GPSData_t::Lat, GPSData_t::Lon, NavStatus_t::MagBiasGood, GimbalTelemetryData_t::MagField, NavStatus_t::MagGood, GimbalTelemetryFlags_t::MagIncluded, MANUAL_FOCUS, GPSData_t::minutes, NavStatus_t::Mode, GimbalTelemetryData_t::Mode, GPSData_t::month, N3D, N_QUAT, GimbalTelemetryData_t::NavStatus, NAXIS, NOVATEL_ALIGN_INS_AID, GimbalTelemetryData_t::NumCameras, GimbalTelemetryData_t::PathTrackPos, GimbalTelemetryFlags_t::PathTrackPosIncluded, GimbalTelemetryData_t::PayloadHumidity, GimbalTelemetryData_t::PayloadTemp, GimbalTelemetryFlags_t::PayloadTempAndHumidityIncluded, GPSData_t::PDOP, GimbalPkt_t::PktType, NavStatus_t::PositionGood, Quat2Eulerf(), QuatForTrackingf(), QuatProductf(), GimbalTelemetryFlags_t::RangeIncluded, GimbalTelemetryData_t::SceneIntensity, GimbalTelemetryFlags_t::SceneIntensityIncluded, GPSData_t::seconds, GimbalPkt_t::Size, GPSData_t::Status, NavStatus_t::TASGood, GimbalTelemetryData_t::Time, GPSData_t::TrackedSats, GPSData_t::VDown, GPSData_t::VEast, NavStatus_t::VelocityGood, GimbalTelemetryData_t::VFOV, GimbalTelemetryData_t::VideoStamp, GPSData_t::VisibleSats, GPSData_t::VNorth, GPSData_t::Week, NavStatus_t::WindGood, GPSData_t::year, GimbalTelemetryData_t::Zoom, and GimbalTelemetryFlags_t::ZoomIncluded.
const char* DecodeGimbalUserWarningPacket (GimbalPkt_t * pPkt, UInt8 * pGroup, UInt8 * pType, UInt8 * pSeverity)
Decode the gimbal user warning packet.
Decode a gimbal user warning packet. This packet contains an ASCII string which can be displayed to the user as a warning.
Parameters
pPkt points to a gimbal packet containing the data.
pGroup receives the group info in the packet
pType receives the type info in the pakcet.
pSeverity receives the severity info in the packet.
Returns
A null terminated string pointer containing the error, or NULL if the packet is invalid.
References GimbalPkt_t::Data, GIMBAL_STATUS_INFORMATION_GROUP, GimbalPkt_t::Group, GimbalPkt_t::PktType, GimbalPkt_t::Size, and USER_WARNING_GIMBAL_PKTTYPE.
BOOL DecodeGimbalVersion2Packet (const GimbalPkt_t * pPkt, Version_t * pVersion, Board_t * pBoard, UInt8 LegacyTypes[NUM_CAMERAS], UInt8 ProtocolTypes[NUM_CAMERAS], float MaxHFOV[NUM_CAMERAS], float MinHFOV[NUM_CAMERAS])
Interpret a newer gimbal system version packet.
Decode a gimbal system version packet 2. This packet contains the version of hardware and software in the gimbal.
Parameters
pPkt points to a gimbal packet containing the data to be decoded.
pVersion receives the software version data.
pBoard receives the hardware version data.
LegacyTypes receives the list of legacy camera identifiers.
ProtocolTypes receives the list of camera protcol identifiers.
MaxHFOV receives the list of maximum horizontal field of view (radians).
MinHFOV receives the list of minimum horizontal field of view (radians).
Returns
TRUE if the packet is OK, FALSE if it is bad.
References Board_t::BoardSN, Board_t::Config, ConvertFromLegacyCameraType(), GimbalPkt_t::Data, DataToSInt16(), DataToUInt16(), DataToUInt32(), Version_t::Date, Board_t::Date, Date_t::day, Version_t::Description, GIMBAL_SETUP_GROUP, GimbalPkt_t::Group, Version_t::MajorVersion, Version_t::MinorVersion, Date_t::month, NUM_CAMERAS, Version_t::PatchNum, GimbalPkt_t::PktType, Board_t::ProductSN, CameraDefinition_t::ProtocolType, Version_t::Released, Board_t::Rev, Version_t::Revision, GimbalPkt_t::Size, Version_t::SubVersion, SYSTEM_VERSION_2_GIMBAL_PKTTYPE, and Date_t::year.
BOOL DecodeGimbalVersionPacket (const GimbalPkt_t * pPkt, Version_t * pVersion, Board_t * pBoard, UInt8 LegacyTypes[NUM_CAMERAS], UInt8 ProtocolTypes[NUM_CAMERAS], float MaxHFOV[NUM_CAMERAS], float MinHFOV[NUM_CAMERAS], Version_t * pLensVersion, LensCtrlType_t * pLensType)
Interpret a gimbal system version packet.
Decode a gimbal system version packet. This packet contains the version of hardware and software in the gimbal
Parameters
pPkt points to a gimbal packet containing the data to be decoded.
pVersion receives the software version data.
pBoard receives the hardware version data.
LegacyTypes receives the list of legacy camera identifiers.
ProtocolTypes receives the list of camera protcol identifiers.
MaxHFOV receives the list of maximum horizontal field of view (radians).
MinHFOV receives the list of minimum horizontal field of view (radians).
pLensVersion receives the software version of the lens controller. All fields will be zero if no version data are available.
pLensType receives the hardware type of the lens controller board.
Returns
TRUE if the packet is OK, FALSE if it is bad.
References Board_t::BoardSN, Board_t::Config, ConvertFromLegacyCameraType(), GimbalPkt_t::Data, DataToSInt16(), DataToUInt16(), DataToUInt32(), Version_t::Date, Board_t::Date, Date_t::day, Version_t::Description, GIMBAL_SETUP_GROUP, GimbalPkt_t::Group, LensCtrlType_t::HasType, Version_t::MajorVersion, Version_t::MinorVersion, Date_t::month, Version_t::PatchNum, GimbalPkt_t::PktType, Board_t::ProductSN, CameraDefinition_t::ProtocolType, Version_t::Released, Board_t::Rev, Version_t::Revision, GimbalPkt_t::Size, Version_t::SubVersion, SYSTEM_VERSION_GIMBAL_PKTTYPE, LensCtrlType_t::Type, and Date_t::year.
BOOL DecodeLensControlVersionPacket (const GimbalPkt_t * pPkt, Version_t * pLensVersion, LensCtrlType_t * pLensType)
Interpret a gimbal lens control version packet.
Decode a lens control version packet.
Parameters
pPkt points to a gimbal packet containing the data to be decoded.
pLensVersion receives the software version of the lens controller.
pLensType receives the hardware configuration of the lens controller board.
Returns
TRUE if the packet is OK, FALSE if it is bad.
References GimbalPkt_t::Data, DataToUInt16(), Version_t::Date, Date_t::day, Version_t::Description, GIMBAL_SETUP_GROUP, GimbalPkt_t::Group, LensCtrlType_t::HasType, LENS_CONFIG_NONE, LENS_CONTROL_VERSION_PKTTYPE, Version_t::MajorVersion, Version_t::MinorVersion, Date_t::month, Version_t::PatchNum, GimbalPkt_t::PktType, Version_t::Released, Version_t::Revision, GimbalPkt_t::Size, Version_t::SubVersion, LensCtrlType_t::Type, and Date_t::year.
BOOL DecodeMbAppVersionPacket (const GimbalPkt_t * pPkt, Version_t * pVersion)
Decode a MB app version packet.
Decode a MB reset report packet
Parameters
pPkt points to a packet containing the data.
pVersion points to a version struct for filling in with the packet's data.
Returns
TRUE if the packet is valid, else FALSE.
References GimbalPkt_t::Data, DataToUInt16(), Version_t::Date, Date_t::day, Version_t::Description, GIMBAL_SETUP_GROUP, GimbalPkt_t::Group, Version_t::MajorVersion, MICROBLAZE_APP_VERSION_PKTTYPE, Version_t::MinorVersion, Date_t::month, Version_t::PatchNum, GimbalPkt_t::PktType, Version_t::Released, Version_t::Revision, GimbalPkt_t::Size, Version_t::SubVersion, and Date_t::year.
BOOL DecodeMbResetReportPacket (const GimbalPkt_t * pPkt, MbReset_t * pType, UInt32 * pAddress, UInt32 * pInfo)
Decode a MB reset report packet.
Decode a MB reset report packet
Parameters
pPkt points to a packet containing the data.
pType points to the reset type.
pAddress points to address of the program counter when reset occurred (if any).
pInfo points to additional info about the reset source (if any).
Returns
TRUE if the packet is valid, else FALSE.
References GimbalPkt_t::Data, DataToUInt32(), GIMBAL_STATUS_INFORMATION_GROUP, GimbalPkt_t::Group, MICROBLAZE_RESET_REPORT, GimbalPkt_t::PktType, and GimbalPkt_t::Size.
const char* DecodeMbUserWarningPacket (const GimbalPkt_t * pPkt, UInt8 * pGroup, UInt8 * pType, UInt8 * pSeverity, UInt16 * pWarnId)
Decode a MB user warning packet.
Decode a MB user warning packet. This packet contains an ASCII string which can be displayed to the user as a warning.
Parameters
pPkt points to a gimbal packet containing the data.
pGroup receives the group info in the packet
pType receives the type info in the pakcet.
pSeverity receives the severity info in the packet.
pWarnId receives a unique ID for the warning.
Returns
A null terminated string pointer containing the error, or NULL if the packet is invalid.
References GimbalPkt_t::Data, DataToUInt16(), GIMBAL_STATUS_INFORMATION_GROUP, GimbalPkt_t::Group, MICROBLAZE_WARN_USER, GimbalPkt_t::PktType, and GimbalPkt_t::Size.
BOOL DecodeMicroblazeDiagnosticsPacket (const GimbalPkt_t * pPkt, MicroblazeDiagnostics_t * pDiagnostics)
Extract the diagnostics data from the packet.
Extract the data from a microblaze diagnostics packet
Parameters
pPkt points to a packet containing the data.
pDiagnostics receives the data from the packet.
Returns
TRUE if the packet is valid, else FALSE.
References GimbalPkt_t::Data, DataToUInt16(), DataToUInt32(), GIMBAL_STATUS_INFORMATION_GROUP, GimbalPkt_t::Group, MICROBLAZE_DIAGNOSTIC_PKTTYPE, MicroblazeDiagnostics_t::PacketRx, MicroblazeDiagnostics_t::PacketTx, GimbalPkt_t::PktType, and GimbalPkt_t::Size.
BOOL DecodeMotionCtrlDiagnosticsPacket (const GimbalPkt_t * pPkt, MotionCtrlDiagnostics_t * pDiagnostics)
Extract the diagnostics data from the packet.
Extract the data from a motion control diagnostics packet
Parameters
pPkt points to a packet containing the data.
pDiagnostics receives the data from the packet.
Returns
TRUE if the packet is valid, else FALSE.
References MotionCtrlDiagnostics_t::AvgClevisTemp, MotionCtrlDiagnostics_t::AvgCur, MotionCtrlDiagnostics_t::AvgPkPk, MotionCtrlDiagnostics_t::AvgStab, MotionCtrlDiagnostics_t::AvgVoltage, GimbalPkt_t::Data, DataToSInt16(), DataToUInt16(), GIMBAL_INNER_PAN, GIMBAL_INNER_TILT, GIMBAL_OUTER_PAN, GIMBAL_OUTER_TILT, GIMBAL_PAN, GIMBAL_STATUS_INFORMATION_GROUP, GIMBAL_TILT, GimbalPkt_t::Group, MC_DIAGNOSTIC_PKTTYPE, GimbalPkt_t::PktType, and GimbalPkt_t::Size.
BOOL DecodeMotionCtrlVersionPacket (const GimbalPkt_t * pPkt, Version_t * pVersion)
Decode the motion control version packet.
Decode the motion controller version information.
Parameters
pPkt points to a packet containing the data.
pVersion holds all the version information
Returns
TRUE if the packet is valid, else FALSE.
References GimbalPkt_t::Data, DataToUInt16(), Version_t::Date, Date_t::day, Version_t::Description, GIMBAL_SETUP_GROUP, GimbalPkt_t::Group, Version_t::MajorVersion, Version_t::MinorVersion, Date_t::month, MOTION_CONTROLLER_BOOTLOADER_VERSION, MOTION_CONTROLLER_VERSION, Version_t::PatchNum, GimbalPkt_t::PktType, Version_t::Released, GimbalPkt_t::Size, Version_t::SubVersion, and Date_t::year.
BOOL DecodeVGSTelemetry (const GimbalPkt_t * pPkt, VGSTelemetryData_t * pData)
Decode a telemetry packet for the video ground station.
Decode a telemetry packet for the video ground station.
Parameters
pPkt is the packet to decode.
pData receives the VGS telemetry.
References GPSData_t::Alt, GimbalPkt_t::Data, DataToSInt16(), DataToSInt32(), DataToUInt16(), DataToUInt32(), GPSData_t::day, VGSTelemetryData_t::GPS, GimbalPkt_t::Group, GPSData_t::hours, GPSData_t::Lat, GPSData_t::Lon, GPSData_t::minutes, GPSData_t::month, VGSTelemetryData_t::Pan, VGSTelemetryData_t::PanCmd, GPSData_t::PDOP, GimbalPkt_t::PktType, VGSTelemetryData_t::RSSI, GPSData_t::seconds, GimbalPkt_t::Size, GPSData_t::Status, TELEMETRY_VGS_PKTTYPE, VGSTelemetryData_t::Tilt, VGSTelemetryData_t::TiltCmd, VGSTelemetryData_t::Time, GPSData_t::TrackedSats, GPSData_t::VDown, GPSData_t::VEast, VGS_COMMAND_AND_CONTROL_GROUP, GPSData_t::VNorth, and GPSData_t::year.
BOOL DecodeVps3DiagnosticsPacket (const GimbalPkt_t * pPkt, Vps3Diagnostics_t * pVpsDiagnostics)
Extract the diagnostics data from the packet.
Extract the diagnostics data for a VPS
Parameters
pPkt points to a packet containing the data.
pVpsDiagnostics points to the VPS3 diagnostic structure to populate.
Returns
TRUE if the packet is valid, else FALSE.
References Vps3Diagnostics_t::BoardTemp, Vps3Diagnostics_t::CpuFreq, Vps3Diagnostics_t::CpuLoad, Vps3Diagnostics_t::CpuTemp, GimbalPkt_t::Data, DataToUInt32(), Vps3Diagnostics_t::FpgaTemp, GIMBAL_STATUS_INFORMATION_GROUP, GimbalPkt_t::Group, GimbalPkt_t::PktType, GimbalPkt_t::Size, and VPS_DIAGNOSTIC_PKTTYPE.
BOOL DecodeVps3ResetReportPacket (const GimbalPkt_t * pPkt, Vps3Reset_t * pType, UInt32 * pAddress, UInt32 * pInfo)
Extract the data from a reset report packet.
Extract the data from a VPS reset report packet
Parameters
pPkt points to a packet containing the data.
pType points to the reset type.
pAddress points to address of the program counter when reset occurred (if any).
pInfo points to additional info about the reset source (if any).
Returns
TRUE if the packet is valid, else FALSE.
References GimbalPkt_t::Data, DataToUInt32(), GIMBAL_STATUS_INFORMATION_GROUP, GimbalPkt_t::Group, GimbalPkt_t::PktType, GimbalPkt_t::Size, and VPS_RESET_REPORT_PKTTYPE.
const char* DecodeVps3UserWarningPacket (const GimbalPkt_t * pPkt, UInt8 * pGroup, UInt8 * pType, UInt8 * pSeverity, UInt16 * pWarnId)
Decode the VPS user warning packet.
Decode a VPS user warning packet. This packet contains an ASCII string which can be displayed to the user as a warning.
Parameters
pPkt points to a gimbal packet containing the data.
pGroup receives the group info in the packet
pType receives the type info in the pakcet.
pSeverity receives the severity info in the packet.
pWarnId receives a unique ID for the warning.
Returns
A null terminated string pointer containing the error, or NULL if the packet is invalid.
References GimbalPkt_t::Data, DataToUInt16(), GIMBAL_STATUS_INFORMATION_GROUP, GimbalPkt_t::Group, GimbalPkt_t::PktType, GimbalPkt_t::Size, and VPS_USER_WARNING_PKTTYPE.
BOOL DecodeVps3VersionPacket (const GimbalPkt_t * pPkt, Version_t * pVersion)
Decode the VPS3 version packet.
Decode the VPS3 version information.
Parameters
pPkt points to a packet containing the data.
pVersion holds all the version information
Returns
TRUE if the packet is valid, else FALSE.
References GimbalPkt_t::Data, DataToUInt16(), Version_t::Date, Date_t::day, Version_t::Description, GIMBAL_SETUP_GROUP, GimbalPkt_t::Group, Version_t::MajorVersion, Version_t::MinorVersion, Date_t::month, Version_t::PatchNum, GimbalPkt_t::PktType, Version_t::Released, Version_t::Revision, GimbalPkt_t::Size, Version_t::SubVersion, VPS3_VERSION_PKTTYPE, and Date_t::year.
void FormGimbalCmdPacket (GimbalPkt_t * pPkt, float Pan, float Tilt, SInt8 ZoomRate, float CamTimeout, UInt8 Flags, float ImpulseTime, SInt8 FocusRate, UInt8 Flags1)
Create a gimbal command packet containing pan, tilt, zoom, and mode.
Form a gimbal cmd packet. The command packet contains the rate or position data for pan and tilt, the camera zoom rate data, as well as the operational mode of the gimbal.
Parameters
pPkt receives the formated gimbal packet
Pan is the pan position (or rate) in radians (per second).
Tilt is the pan position (or rate) in radians (per second).
ZoomRate is the zoom rate from -8 to 8.
CamTimeout is the time to apply the zoom and focus rates, in seconds.
Flags describes how to interpret the data.
ImpulseTime is the time to apply to an impulse (seconds).
FocusRate is the focus rate from -8 to 8.
Flags1 provides additional details on how to interpret the data.
References GimbalPkt_t::Data, FinishGimbalPacket(), GIMBAL_CMD_GIMBAL_PKTTYPE, GIMBAL_COMMAND_AND_CONTROL_GROUP, RoundToSInt16(), RoundToUInt8(), and SInt16ToData().
Referenced by CommBase_SendGimbalCmdPacket().
void FormGimbalHostAttitudePacket (GimbalPkt_t * pPkt, const float Attitude[NAXIS], UInt32 Time, UInt8 SampleRate, UInt8 Flags, float Baro)
Create a gimbal host attitude packets which contains the euler angles of the gimbal mount.
Create a gimbal host attitude packets which contains the euler angles of the gimbal mount with respect to inerial space as estimated by the host platform.
Parameters
pPkt points to a gimbal packet to be formatted.
Attitude points to the the attitude data in radians.
Time is the host system time in milliseconds.
SampleRate is the expected rate at which the host will sedn the data in packets per second.
Flags is the flags variable in the packet.
Baro is the host barometric altitude in meters. Use -250.0f or less for no baro altitude.
References GimbalPkt_t::Data, FinishGimbalPacket(), GIMBAL_DYNAMICS_INFORMATION_GROUP, HOST_ATTITUDE_GIMBAL_PKTTYPE, PITCH_AXIS, ROLL_AXIS, RoundToSInt16(), RoundToUInt24(), SInt16ToData(), UInt24ToData(), UInt32ToData(), and YAW_AXIS.
void FormGimbalHostGPSPacket (GimbalPkt_t * pPkt, const GPSData_t * pGPS, UInt32 Time, UInt8 Valid)
Create a gimbal host gps packet which contains GPS information from the host.
Create a gimbal host gps packet which contains GPS information from the host platform.
Parameters
pPkt points to a gimbal packet to be formatted.
pGPS points to the GPS data.
Time is the host system time in milliseconds since reset.
Valid is the host estimation of whether the GPS data is valid. Zero indicates invalid.
References GPSData_t::Alt, GimbalPkt_t::Data, GPSData_t::day, FinishGimbalPacket(), GPSData_t::GeoidUndulation, GIMBAL_POSITION_INFORMATION_GROUP, GPSData_t::HasVDown, HOST_GPS_DATA_GIMBAL_PKTTYPE, GPSData_t::hours, GPSData_t::Lat, GPSData_t::Lon, GPSData_t::minutes, GPSData_t::month, GPSData_t::PDOP, RoundToSInt16(), RoundToSInt32(), RoundToUInt16(), RoundToUInt8(), GPSData_t::SampleTime, GPSData_t::seconds, SInt16ToData(), SInt32ToData(), GPSData_t::SolnType, GPSData_t::TrackedSats, UInt16ToData(), UInt32ToData(), GPSData_t::VDown, GPSData_t::VEast, GPSData_t::VelocityLag, GPSData_t::VisibleSats, GPSData_t::VNorth, and GPSData_t::year.
void FormGimbalHostSensorPacket (GimbalPkt_t * pPkt, const float Rates[NAXIS], const float Accel[NAXIS], float TAS, UInt32 Time, UInt8 SampleRate, UInt8 Flags)
Create a gimbal host sensor packet which contains gimbal mount body rates from the host.
Create a gimbal host body rate packet which contains gimbal mount body rates from the host. The host body rates must be in the gimbal mount coordinate frame.
Parameters
pPkt points to a gimbal packet to be formatted.
Rates points to the host body rates in radians.
Accel points to the host body accelerations in m/s/s.
TAS is the host true air speed in m/s.
Time is the host system time in milliseconds.
SampleRate is the expected rate at which the host will sedn the data in packets per second.
Flags is the rate flag information.
References GimbalPkt_t::Data, FinishGimbalPacket(), GIMBAL_DYNAMICS_INFORMATION_GROUP, HOST_SENSOR_GIMBAL_PKTTYPE, PITCH_AXIS, ROLL_AXIS, RoundToSInt16(), SInt16ToData(), UInt16ToData(), UInt32ToData(), X_AXIS, Y_AXIS, YAW_AXIS, and Z_AXIS.
void FormGimbalInitialHeadingPacket (GimbalPkt_t * pPkt, float Heading)
Create the initial heading packet.
Create the initial heading packet.
Parameters
pPkt points to the packet to create.
Heading is the heading in radians.
References GimbalPkt_t::Data, FinishGimbalPacket(), GIMBAL_DYNAMICS_INFORMATION_GROUP, INITIAL_HEADING_GIMBAL_PKTTYPE, RoundToSInt16(), and SInt16ToData().
void FormVGSAntennaCommand (GimbalPkt_t * pPkt, float Pan, float Tilt, UInt8 Mode)
Decode the video ground station antenna control packet.
Form the video ground station antenna control packet, which is used to take direct control of the pointing antenna.
Parameters
pPkt receives the formatted packet.
Pan is the pan angle command in radians.
Tilt is the titl angle command in radians.
Mode is the mode, which must be non-zero to command the antenna.
References GimbalPkt_t::Data, DIRECT_CONTROL_VGS_PKTTYPE, FinishGimbalPacket(), RoundToSInt16(), SInt16ToData(), and VGS_COMMAND_AND_CONTROL_GROUP.