Communications SDK: GimbalPacket.h File Reference
GimbalPacket.h File Reference
Gimbal packet encode and decode functionality.
#include "Queue.h"
#include "Serial.h"
#include "GimbalPacketGeneric.h"
Functions
BOOL LookForGimbalPacket (GimbalPkt_t *pPkt, Serial_t *pPort)
Look for a gimbal packet arriving over a serial port.
BOOL LookForGimbalPacketInQueue (GimbalPkt_t *pPkt, Queue_t *pQ)
Look for a gimbal packet in a ring buffer.
void SendGimbalPacket (const GimbalPkt_t *pPkt, Serial_t *pPort)
Send a gimbal packet over a serial port.
Detailed Description
Gimbal packet encode and decode functionality.
Function Documentation
BOOL LookForGimbalPacket (GimbalPkt_t * pPkt, Serial_t * pPort)
Look for a gimbal packet arriving over a serial port.
Search for a gimbal packet coming over a physical serial channel. If a gimbal packet is found this function returns TRUE. The packet storage provided by the caller MUST persist between calls, since this function may partially complete a packet and then return FALSE while waiting for more data to arrive.
Parameters
pPkt points to a packet structure which must persist between calls.
pPort identifies a previously opened serial port.
Returns
TRUE if a packet is found, else FALSE.
References CalcGimbalPacketChecksum(), GimbalPkt_t::Group, GimbalPkt_t::i, LookForGimbalPacketInByte(), ReadBlockQuick(), ReadByteQuick(), GimbalPkt_t::Size, and GimbalPkt_t::State.
BOOL LookForGimbalPacketInQueue (GimbalPkt_t * pPkt, Queue_t * pQ)
Look for a gimbal packet in a ring buffer.
Search for a gimbal packet contained in a ring buffer. The packet storage provided by the caller MUST persist between calls, since this function will partially complete a packet and then return FALSE while waiting for more data to arrive.
Parameters
Byte contains the next piece of receive data.
pPkt points to a gimbal packet structure which must persist between calls.
Returns
TRUE if a packet is found, else FALSE.
References BlockDeQFast(), CalcGimbalPacketChecksum(), DeQFast(), GimbalPkt_t::Group, GimbalPkt_t::i, LookForGimbalPacketInByte(), GimbalPkt_t::Size, and GimbalPkt_t::State.
void SendGimbalPacket (const GimbalPkt_t * pPkt, Serial_t * pPort)
Send a gimbal packet over a serial port.
Send a gimbal packet out a serial port.
Parameters
pPkt points to a completed gimbal packet to send.
pPort identifies a previously opened serial port.
References GimbalPkt_t::Size, and WriteBlockQuick().