Communications SDK: GPSTimeConvert.c File Reference
GPSTimeConvert.c File Reference
GPS Time conversion utilties.
#include "Types.h"
#include "GPSTimeConvert.h"
Macros
#define MILLISECONDS_PER_DAY (24*60*60*1000)
#define MILLISECONDS_PER_WEEK (7*MILLISECONDS_PER_DAY)
#define JAN1_2000 7300
Functions
void gps_to_ymdhms (UInt32 gps_week, UInt32 ITOW, UInt16 *year, UInt8 *month, UInt8 *day, UInt8 *hours, UInt8 *minutes, float *seconds)
Convert gps time (ITOW and week) to year month, day, hours, minutes,.
void GPSITOW_to_hms (UInt32 ITOW, UInt8 *hours, UInt8 *minutes, float *seconds)
Calculate hours minutes seconds from GPS time of week.
void ymdhms_to_gps (UInt32 year, UInt32 month, UInt32 day, UInt32 hour, UInt32 minute, float second, UInt16 *gps_week, UInt32 *ITOW)
Convert calendar year month day hours minutes seconds to GPS time.
void yearday_to_gps (UInt32 year, UInt32 Days, UInt16 *gps_week, UInt32 *ITOW)
Convert year and day of year to gps time.
void GPS_to_UTC_WeekITOW (UInt16 GPSWeek, UInt32 GPSITOW, UInt32 LeapMilliseconds, UInt16 *pUTCWeek, UInt32 *pUTCITOW)
Calculate UTC week and ITOW from GPS week and ITOW. UTC time is leap.
UInt64 UnixTime (UInt32 Week, UInt32 ITOW)
Get time in microseconds since midnight Jan 1 1970.
Detailed Description
GPS Time conversion utilties.
Code for converting between GPS Week & Seconds of week to y,m,d,h,m,s format. Note this code does not currently handle leap seconds.
Function Documentation
void GPS_to_UTC_WeekITOW (UInt16 GPSWeek, UInt32 GPSITOW, UInt32 LeapMilliseconds, UInt16 * pUTCWeek, UInt32 * pUTCITOW)
Calculate UTC week and ITOW from GPS week and ITOW. UTC time is leap.
Calculate UTC week and ITOW from GPS week and ITOW.
Parameters
GPSWeek is the GPS week number.
GPSITOW is time of week in milliseconds.
LeapMilliseconds is the is the difference (GPSTime - UTCTime) in milliseconds.
pUTCWeek receives the UTC week number.
pUTCWeek receives the UTC time of week in milliseconds.
void gps_to_ymdhms (UInt32 gps_week, UInt32 ITOW, UInt16 * year, UInt8 * month, UInt8 * day, UInt8 * hours, UInt8 * minutes, float * seconds)
Convert gps time (ITOW and week) to year month, day, hours, minutes,.
Convert gps time (ITOW and week) to year month, day, hours, minutes, seconds calendar time.
Parameters
gps_week is the GPS week number
ITOW is the GPS time of week in milliseconds.
year receives the year number.
month receives the month of the year (1-12).
day receives the day of the month (1-31).
hours receives the hours of the day (0-23).
minutes receives the minutes of the hour (0-59).
seconds receives the seconds of the minute (0-59.999).
References GPSITOW_to_hms().
Referenced by DecodeGimbalTelemetryPacket(), DecodeGSTelemetryPacket(), DecodeTelemetryHiResPacket(), and DecodeTelemetryLoResPacket().
void GPSITOW_to_hms (UInt32 ITOW, UInt8 * hours, UInt8 * minutes, float * seconds)
Calculate hours minutes seconds from GPS time of week.
Calculate hours minutes seconds from GPS time of week.
Parameters
ITOW is the time of week in milliseconds.
hours receives the hours of the day (0-23).
minutes receives the minutes of the hour (0-59).
seconds receives the seconds of the minute (0-59.999)
Referenced by gps_to_ymdhms().
UInt64 UnixTime (UInt32 Week, UInt32 ITOW)
Get time in microseconds since midnight Jan 1 1970.
Calculate time in microseconds since Midnight Jan 1 1970.
Parameters
Week is the GPS or UTC week number
ITOW is the GPS or UTC time of week in milliseconds
Returns
The time in microseconds.
void yearday_to_gps (UInt32 year, UInt32 Days, UInt16 * gps_week, UInt32 * ITOW)
Convert year and day of year to gps time.
Convert year and day of year to gps time.
Parameters
year is the year (e.g. 2012).
Days is the day of the year, form 0 to 365 (if leap year).
gps_week receives the week number.
ITOW receives the time of week in milliseconds.
void ymdhms_to_gps (UInt32 year, UInt32 month, UInt32 day, UInt32 hour, UInt32 minute, float second, UInt16 * gps_week, UInt32 * ITOW)
Convert calendar year month day hours minutes seconds to GPS time.
Convert calendar year month day hours minutes seconds to GPS time.
Parameters
year is the year.
month is the month of the year (1-12).
day is the day of the month (1-31).
hour is the hour of the day (0-23).
minute is the minute of the hour (0-59).
second is the seconds of the minute (0-59.999).
gps_week receives the week number.
ITOW receives the time of week in milliseconds.
Referenced by DecodeGSTelemetryPacket().