Communications SDK: GreatCircle.h File Reference
GreatCircle.h File Reference
Great circle utilties.
#include "Definitions.h"
#include "Indices.h"
Functions
void LLAandNEDtoECEF (const double PosLLA[NPOS], double PosECEF[NPOS], const float VelNED[N3D], float VelECEF[N3D])
Convert LLA position and NED velocity to ECEF.
void ECEFtoLLAandNED (const double PosECEF[NPOS], double PosLLA[NPOS], const float VelECEF[N3D], float VelNED[N3D])
Convert ECEF position and velocity to LLA and NED.
void LLAtoECEF (const double LLA[NPOS], double ECEF[NPOS])
Convert from LLA to ECEF position.
void ECEFtoLLA (const double ECEF[NPOS], double LLA[NPOS])
Convert from ECEF to LLA position.
void ECEFtoNED (const double LLA[NPOS], const double ECEF[N3D], double NED[N3D])
Convert from ECEF vector to NED vector.
void NEDtoECEF (const double LLA[NPOS], const double NED[N3D], double ECEF[N3D])
Convert from NED vector to ECEF vector.
void NEDtoECEFf (const double LLA[NPOS], const float Vel[N3D], float ECEF[N3D])
Convert from float NED vector to ECEF vector.
void ECEFtoNEDf (const double LLA[NPOS], const float ECEF[N3D], float Vel[N3D])
Convert from float ECEF vector to NED vector.
void LLAtoECEFEx (double Alt, double PosECEF[NPOS], double sinLat, double sinLon, double cosLat, double cosLon)
Convert LLA position to ECEF position, using previously calculated trig.
void ECEFtoLLAEx (const double PosECEF[NPOS], double PosLLA[NPOS], double *sinLat, double *cosLat)
Convert ECEF position to LLA position, returning calculated trig.
void NEDtoECEFEx (const double NED[N3D], double ECEF[N3D], double sinLat, double sinLon, double cosLat, double cosLon)
Convert NED vector to ECEF vector, using previously calculated trig.
void ECEFtoNEDEx (const double ECEF[N3D], double NED[N3D], double sinLat, double sinLon, double cosLat, double cosLon)
Convert ECEF vector to NED vector, using previously calculated trig.
void NEDtoECEFExf (const float NED[N3D], float ECEF[N3D], double sinLat, double sinLon, double cosLat, double cosLon)
Convert float NED vector to float ECEF vector, using previously calculated trig.
void ECEFtoNEDExf (const float ECEF[N3D], float NED[N3D], double sinLat, double sinLon, double cosLat, double cosLon)
Convert float ECEF vector to float NED vector, using previously calculated trig.
double ECEFHeading (const double ECEF[N3D], double sinLat, double sinLon, double cosLat, double cosLon)
Compute the heading (with respect to true North) of a vector given in ECEF.
double DistanceBetweenECEFCircle (const double Start[N3D], const double End[N3D])
Calcualte arc distance between two ECEF positions.
double DistanceBetweenECEF (const double Start[N3D], const double End[N3D])
Calcualte stright distance between two ECEF positions.
void TrackCoordinatePositionECEF (const double Pos[N3D], const double Start[N3D], const double End[N3D], double Track[N3D])
Calculate track relative position.
void TrackCoordinateVelocityECEF (const float Vel[N3D], const double Start[N3D], const double End[N3D], float TrackVelocity[N3D])
Calculate track relative velocity.
void TrackCoordinateParametersECEF (const double Pos[N3D], const float Vel[N3D], const float Vel2[N3D], const double Start[N3D], const double End[N3D], double TrackPosition[N3D], float TrackVel1[N3D], float TrackVel2[N3D])
Calculate track relative position and velocity.
void TrackCoordinatePositionECEFEx (const double Pos[N3D], const double AlongTrackUnit[N3D], const double CrossTrackUnit[N3D], const double End[N3D], double TrackPosition[N3D])
Calculate track-relative position knowing the track-frame unit vectors.
void TrackCoordinateVelocityECEFEx (const float Vel[N3D], const double AlongTrackUnit[N3D], const double CrossTrackUnit[N3D], float TrackVelocity[N3D])
Calculate track-relative velocity knowing the track-frame unit vectors.
void TrackRelativeVectors (const double Start[N3D], const double End[N3D], double AlongTrackUnit[N3D], double CrossTrackUnit[N3D])
Calculate the track-frame unit vectors.
void TrackCoordinateParametersECEF3D (const double Pos[N3D], const float Vel[N3D], const double Start[N3D], const double End[N3D], double TrackPosition[N3D], float TrackVel[N3D])
Calculate the track relative position and velocity parameters including z.
Detailed Description
Great circle utilties.
The great circle module provides utilities for doing great circle calculations and transferring between LLA and ECEF formats
Function Documentation
double DistanceBetweenECEF (const double Start[N3D], const double End[N3D])
Calcualte stright distance between two ECEF positions.
Calculate the distance between two waypoints in earth centered earth fixed format. The calculation is based on a straight line between the two points.
Parameters
Start is an Earth-Centered-Earth-Fixed vector of the first waypoint.
End is an Earth-Centered-Earth-Fixed vector of the second waypoint.
Returns
The distance in meters between the two waypoints
References N3D, SubtractVectors3D(), and VectorLength3D().
double DistanceBetweenECEFCircle (const double Start[N3D], const double End[N3D])
Calcualte arc distance between two ECEF positions.
Calculate the arc distance between two waypoints in earth centered earth fixed format. The calculation assumes the points are on a sphere.
Parameters
Start is an Earth-Centered-Earth-Fixed vector of the first waypoint.
End is an Earth-Centered-Earth-Fixed vector of the second waypoint.
Returns
The distance in meters between the two waypoints
References DotProduct3D(), lim(), and VectorLength3D().
double ECEFHeading (const double ECEF[N3D], double sinLat, double sinLon, double cosLat, double cosLon)
Compute the heading (with respect to true North) of a vector given in ECEF.
Compute the heading (with respect to true North) of a vector given in ECEF reference frame
Parameters
ECEF is the vector.
sinLat is the sin of the latitude.
sinLon is the sin of the longitude.
cosLat is the cos of the latitude.
cosLon is the cos of the longitude.
Returns
The heading from -PI to PI.
References X_AXIS, Y_AXIS, and Z_AXIS.
void ECEFtoLLA (const double ECEF[NPOS], double LLA[NPOS])
Convert from ECEF to LLA position.
Convert the ECEF (earth centered, earth fixed) position to LLA (latitude, longitude, altitude) position
Parameters
ECEF is the X, Y, Z ECEF position in meters.
LLA receives the LLA position in radians, radians, meters.
References ECEFtoLLAandNED().
void ECEFtoLLAandNED (const double PosECEF[NPOS], double PosLLA[NPOS], const float VelECEF[N3D], float VelNED[N3D])
Convert ECEF position and velocity to LLA and NED.
Convert the ECEF (earth centered, earth fixed) position and velocity to LLA (latitude, longitude, altitude) position and NED (North, East, Down) velocity equivalents. This is more efficient then calling separate velocity and position functions. Pass NULL for velocity if that output is not desired.
Parameters
PosECEF is the X, Y, Z ECEF position in meters.
PosLLA receives the LLA position in radians, radians, meters.
VelECEF is the X, Y, Z ECEF velocity in meters per second.
VelNED receives the NED velocity in meters per second.
References ECEFtoLLAEx(), ECEFtoNEDExf(), and LON.
Referenced by ECEFtoLLA().
void ECEFtoLLAEx (const double PosECEF[NPOS], double PosLLA[NPOS], double * sinLat, double * cosLat)
Convert ECEF position to LLA position, returning calculated trig.
Convert the ECEF (earth centered, earth fixed) position to LLA (latitude, longitude, altitude) position.
Parameters
PosECEF is the X, Y, Z ECEF position in meters.
PosLLA receives the LLA position in radians, radians, meters.
sinLat receives the sin of the LLA latitude.
cosLat receives the cosine of the LLA latitude.
References ALT, LAT, LON, X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by ECEFtoLLAandNED().
void ECEFtoNED (const double LLA[NPOS], const double ECEF[N3D], double NED[N3D])
Convert from ECEF vector to NED vector.
Convert the ECEF (earth centered, earth fixed) vector to NED (North, East, Down).
Parameters
LLA is the LLA position in radians, radians, meters.
ECEF is the X, Y, Z ECEF vector in meters.
NED receives the NED vector in meters.
References ECEFtoNEDEx(), LAT, and LON.
void ECEFtoNEDEx (const double ECEF[N3D], double NED[N3D], double sinLat, double sinLon, double cosLat, double cosLon)
Convert ECEF vector to NED vector, using previously calculated trig.
Convert the ECEF (earth centered, earth fixed) vector to NED (North, East, Down) vector equivalents.
Parameters
ECEF is the X, Y, Z ECEF vector.
NED receives the NED vector.
sinLat is the sin of the latitude.
sinLon is the sin of the longitude.
cosLat is the cos of the latitude.
cosLon is the cos of the longitude.
References DOWN, EAST, NORTH, X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by ECEFtoNED().
void ECEFtoNEDExf (const float ECEF[N3D], float NED[N3D], double sinLat, double sinLon, double cosLat, double cosLon)
Convert float ECEF vector to float NED vector, using previously calculated trig.
Convert the ECEF (earth centered, earth fixed) vector to NED (North, East, Down) vector equivalents.
Parameters
ECEF is the X, Y, Z ECEF vector.
NED receives the NED vector.
sinLat is the sin of the latitude.
sinLon is the sin of the longitude.
cosLat is the cos of the latitude.
cosLon is the cos of the longitude.
References DOWN, EAST, NORTH, X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by ECEFtoLLAandNED(), and ECEFtoNEDf().
void ECEFtoNEDf (const double LLA[NPOS], const float ECEF[N3D], float NED[N3D])
Convert from float ECEF vector to NED vector.
Convert the ECEF (earth centered, earth fixed) vector to NED (North, East, Down).
Parameters
LLA receives the LLA position in radians, radians, meters.
ECEF is the X, Y, Z ECEF velocity in meters per second.
NED receives the NED velocity in meters per second.
References ECEFtoNEDExf(), LAT, and LON.
void LLAandNEDtoECEF (const double PosLLA[NPOS], double PosECEF[NPOS], const float VelNED[N3D], float VelECEF[N3D])
Convert LLA position and NED velocity to ECEF.
Convert the LLA (latitude, longitude, altitude) position and NED (North, East, Down) velocity to ECEF (earth centered, earth fixed) equivalents. This is more efficient then calling separate velocity and position functions. Pass NULL for position or velocity if those outputs are not desired.
Parameters
PosLLA is the LLA position in radians, radians, meters.
PosECEF receives the X, Y, Z ECEF position in meters.
VelNED is the NED velocity in meters per second.
VelECEF receives the X, Y, Z ECEF velocity in meters per second.
References ALT, LAT, LLAtoECEFEx(), LON, and NEDtoECEFExf().
Referenced by DecodeGPSHealth(), DecodeGSGPSHealth(), DecodeGSTelemetryPacket(), DecodeTelemetryHiResPacket(), and LLAtoECEF().
void LLAtoECEF (const double LLA[NPOS], double ECEF[NPOS])
Convert from LLA to ECEF position.
Convert the LLA (latitude, longitude, altitude) position to ECEF (earth centered, earth fixed).
Parameters
LLA is the LLA position in radians, radians, meters.
ECEF receives the X, Y, Z ECEF position in meters.
References LLAandNEDtoECEF().
void LLAtoECEFEx (double Alt, double PosECEF[NPOS], double sinLat, double sinLon, double cosLat, double cosLon)
Convert LLA position to ECEF position, using previously calculated trig.
Convert the LLA (latitude, longitude, altitude) position to ECEF (earth centered, earth fixed), using precomputed trigonmetric functions.
Parameters
Alt is the LLA altitude in meters.
PosECEF receives the X, Y, Z ECEF position in meters.
sinLat is the sin of the latitude.
sinLon is the sin of the longitude.
cosLat is the cos of the latitude.
cosLon is the cos of the longitude.
References X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by LLAandNEDtoECEF().
void NEDtoECEF (const double LLA[NPOS], const double NED[N3D], double ECEF[N3D])
Convert from NED vector to ECEF vector.
Convert the NED (North, East, Down) vecotor to ECEF (earth centered, earth fixed).
Parameters
LLA is the LLA position in radians, radians, meters.
NED is the NED vector in meters.
ECEF receives the X, Y, Z ECEF vector in meters.
References LAT, LON, and NEDtoECEFEx().
void NEDtoECEFEx (const double NED[N3D], double ECEF[N3D], double sinLat, double sinLon, double cosLat, double cosLon)
Convert NED vector to ECEF vector, using previously calculated trig.
Convert the NED (North, East, Down) vecotor to ECEF (earth centered, earth fixed), using previously calculated trig data.
Parameters
NED is the NED vector in meters.
ECEF receives the X, Y, Z ECEF vector in meters.
sinLat is the sin of the latitude.
sinLon is the sin of the longitude.
cosLat is the cos of the latitude.
cosLon is the cos of the longitude.
References DOWN, EAST, NORTH, X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by NEDtoECEF().
void NEDtoECEFExf (const float NED[N3D], float ECEF[N3D], double sinLat, double sinLon, double cosLat, double cosLon)
Convert float NED vector to float ECEF vector, using previously calculated trig.
Convert the NED (North, East, Down) vecotor to ECEF (earth centered, earth fixed), using previously calculated trig data.
Parameters
NED is the NED vector in meters.
ECEF receives the X, Y, Z ECEF vector in meters.
sinLat is the sin of the latitude.
sinLon is the sin of the longitude.
cosLat is the cos of the latitude.
cosLon is the cos of the longitude.
References DOWN, EAST, NORTH, X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by LLAandNEDtoECEF(), and NEDtoECEFf().
void NEDtoECEFf (const double LLA[NPOS], const float NED[N3D], float ECEF[N3D])
Convert from float NED vector to ECEF vector.
Convert the NED (North, East, Down) vecotor to ECEF (earth centered, earth fixed).
Parameters
LLA is the LLA position in radians, radians, meters.
NED is the NED vector in meters.
ECEF receives the X, Y, Z ECEF vector in meters.
References LAT, LON, and NEDtoECEFExf().
void TrackCoordinateParametersECEF (const double Pos[N3D], const float Vel1[N3D], const float Vel2[N3D], const double Start[N3D], const double End[N3D], double TrackPosition[N3D], float TrackVel1[N3D], float TrackVel2[N3D])
Calculate track relative position and velocity.
Calculate the 2D track relative position and velocity parameters. This is more efficient than calling individual position and velocity functions. The calculation accounts for great circle effects.
Parameters
Pos is an Earth-Centered-Earth-Fixed vector of the current position.
Vel1 is an Earth-Centered-Earth-Fixed velocity vector.
Vel2 is another Earth-Centered-Earth-Fixed velocity vector.
Start is an Earth-Centered-Earth-Fixed vector of the starting waypoint.
End is an Earth-Centered-Earth-Fixed vector of the ending waypoint.
TrackPosition is an array to receive the X, Y, and Z (zero) track values.
TrackVel1 is an array to receive the X, Y, and Z (zero) track relative velocities for Vel1.
TrackVel2 is an array to receive the X, Y, and Z (zero) track relative velocities for Vel2. Pass NULL to not perform this calculation.
References N3D, TrackCoordinatePositionECEFEx(), TrackCoordinateVelocityECEFEx(), and TrackRelativeVectors().
void TrackCoordinateParametersECEF3D (const double Pos[N3D], const float Vel[N3D], const double Start[N3D], const double End[N3D], double TrackPosition[N3D], float TrackVel[N3D])
Calculate the track relative position and velocity parameters including z.
Calculate the track relative position and velocity parameters. This is more efficient than calling individual position and velocity functions. The calculation accounts for great circle effects.
Parameters
Pos is an Earth-Centered-Earth-Fixed vector of the current position.
Vel is an Earth-Centered-Earth-Fixed velocity vector.
Start is an Earth-Centered-Earth-Fixed vector of the starting waypoint.
End is an Earth-Centered-Earth-Fixed vector of the ending waypoint.
TrackPosition is an array to receive the X, Y, and Z track values.
TrackVel is an array to receive the X, Y, and Z track relative velocities.
References CrossProduct3D(), DotProduct3D(), N3D, SubtractVectors3D(), TrackRelativeVectors(), UnitVector3D(), X_AXIS, Y_AXIS, and Z_AXIS.
void TrackCoordinatePositionECEF (const double Pos[N3D], const double Start[N3D], const double End[N3D], double TrackPosition[N3D])
Calculate track relative position.
Calculate X and Y track values relative to the end if the track. The calculation accounts for great circle effects.
Parameters
Pos is an ECEF vector of the current position.
Start is an ECEF vector of the starting waypoint.
End is an ECEF vector of the ending waypoint.
TrackPosition receives the X, Y, and Z (zero) track values.
References N3D, TrackCoordinatePositionECEFEx(), and TrackRelativeVectors().
void TrackCoordinatePositionECEFEx (const double Pos[N3D], const double AlongTrackUnit[N3D], const double CrossTrackUnit[N3D], const double End[N3D], double TrackPosition[N3D])
Calculate track-relative position knowing the track-frame unit vectors.
Calculate X and Y track values relative to the end if the track. The Z term will be set to 0.0. The calculation accounts for great circle effects.
Parameters
Pos is an ECEF vector of the current position.
AlongTrackUnit is the ECEF along track unit vector.
CrossTrackUnit is the ECEF cross track unit vector
End is an ECEF vector of the ending waypoint.
TrackPosition receives the X, Y, and Z (zero) track values.
References DotProduct3D(), N3D, SubtractVectors3D(), X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by TrackCoordinateParametersECEF(), and TrackCoordinatePositionECEF().
void TrackCoordinateVelocityECEF (const float Vel[N3D], const double Start[N3D], const double End[N3D], float TrackVelocity[N3D])
Calculate track relative velocity.
Calculate X and Y track values. The calculation accounts for great circle effects.
Parameters
Vel is an Earth-Centered-Earth-Fixed vector of the current velocity.
Start is an Earth-Centered-Earth-Fixed vector of the starting waypoint.
End is an Earth-Centered-Earth-Fixed vector of the ending waypoint.
TrackVelocity is an array to receive the X, Y, and Z (zero) track values.
References N3D, TrackCoordinateVelocityECEFEx(), and TrackRelativeVectors().
void TrackCoordinateVelocityECEFEx (const float Vel[N3D], const double AlongTrackUnit[N3D], const double CrossTrackUnit[N3D], float TrackVelocity[N3D])
Calculate track-relative velocity knowing the track-frame unit vectors.
Calculate X and Y track velocity values. The Z term will be set to zero. The calculation accounts for great circle effects.
Parameters
Vel is an Earth-Centered-Earth-Fixed vector of the current velocity.
AlongTrackUnit is the ECEF along track unit vector.
CrossTrackUnit is the ECEF cross track unit vector
TrackVelocity is an array to receive the X, Y, and Z (zero) track values.
References DotProduct3D(), N3D, X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by TrackCoordinateParametersECEF(), and TrackCoordinateVelocityECEF().
void TrackRelativeVectors (const double Start[N3D], const double End[N3D], double AlongTrackUnit[N3D], double CrossTrackUnit[N3D])
Calculate the track-frame unit vectors.
Calculate the track relative units vectors for along and cross track.
Parameters
Start is an Earth-Centered-Earth-Fixed vector of the starting waypoint.
End is an Earth-Centered-Earth-Fixed vector of the ending waypoint.
AlongTrackUnit receives the along track unit vector in meters
CrossTrackUnit receives the cross track unit vector in meters.
References CrossProduct3D(), SubtractVectors3D(), UnitVector3D(), X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by TrackCoordinateParametersECEF(), TrackCoordinateParametersECEF3D(), TrackCoordinatePositionECEF(), and TrackCoordinateVelocityECEF().