Communications SDK: GSPacket.h File Reference
GSPacket.h File Reference
Ground station packet utilities.
#include "StreamPackets.h"
#include "GSDefinitions.h"
Classes
struct GSUserData_t
Macros
#define NUM_GROUP_ADDRESS 100
#define GS_PKT_OVERHEAD SIMPLE_PKT_OVERHEAD
Enumerations
enum GSPacketTypes {
ADD_ADDRESS, DEL_ADDRESS, PILOT_ADDRESS, DGPS_SETTINGS,
GS_VERSION, REQUEST_CONFIG, TRANSMITTER_CON, GS_OLD_TELEMETRY,
GROUP_ADDRESS, GS_RADIO_SETTINGS, GS_SPECTRUM, DYNAMIC_ENUMERATION,
GS_SPECTRUM2, GS_USER_WARNING, GS_RESET_REPORT, REQ_GPSHOTSTART,
DUAL_ANT_STATUS, GS_CONFIGURATION, GS_NAME, GS_NEW_TELEMETRY,
GS_DEVICE_DETAILS, GS_GPS_HEALTH, GS_SIMULATION_CONTROL, NUM_GS_MSGS
}
enum GSConfigurations {
GS_CONFIG_NORMAL, GS_CONFIG_BAI, GS_CONFIG_FREE_WAVE_FULL_DUPLEX, GS_CONFIG_TELEDESIGN_HALF_DUPLEX,
GS_CONFIG_MHX_EXTERNAL_HALF_DUPLEX, GS_CONFIG_AGIG_C2, NUM_GS_CONFIG
}
Functions
BOOL DecodeGSGPSHealth (const GroundStationPkt_t *pPkt, GPSUser_t *pGPS, UInt8 *pIndex, UInt8 *pNum)
Decode GPS health information for a single GPS.
void FormGSGPSHealthPacket (GroundStationPkt_t *pPkt, const GPS_t *pGPS, UInt8 Index, UInt8 Num)
Form a packet that describes the GPS health information, including satellite data.
const char * DecodeGSDeviceDetails (GroundStationPkt_t *pPkt, UInt8 *pIndex, UInt8 *pDevice, BOOL *pComplete)
Decode device details packet.
const char * FormGSDeviceDetailsPacket (GroundStationPkt_t *pPkt, const char *pDetails, UInt8 IndexThis, UInt8 Device, BOOL FinalDevice)
Form the radio details packet.
BOOL DecodeGroupAddressPacketNew (const GroundStationPkt_t *pPkt, GSUserData_t *pData)
Decode the ground station group address packet in a GSUserData_t structure.
void FormGSRadioSettingsPacket (GroundStationPkt_t *pPkt, const RadioSettings_t *pSettings)
Form a ground station radio settings packet.
BOOL DecodeGSRadioSettingsPacket (const GroundStationPkt_t *pPkt, RadioSettings_t *pSettings)
Deocde a ground station radio settings packet.
void FormGSTelemetryPacket (GroundStationPkt_t *pPkt, UInt32 SystemTime, const GPS_t *pGPS, const SystemDiagnostic_t *pSystem, float PilotSamplePercentage, float PilotUplinkRate)
Form a ground station telemetry packet.
BOOL DecodeGSTelemetryPacket (const GroundStationPkt_t *pPkt, GSUserData_t *pData)
Decode a ground station telemetry packet, either the old packet or the new, in a GSUserData_t structure.
void FormDGPSBasePacket (GroundStationPkt_t *pPkt, const DGPSParameter_t *pDGPS)
Form a DGPS base station packet.
BOOL DecodeDGPSBasePacket (const GroundStationPkt_t *pPkt, DGPSParameter_t *pData)
Decode a DGPS base station packet.
void FormGSVersionPacket (GroundStationPkt_t *pPkt, const Version_t *pVersion, const Board_t *pBoard)
Form a ground station version packet.
BOOL DecodeGSVersionPacket (const GroundStationPkt_t *pPkt, Version_t *pVersion, Board_t *pBoard)
Decode a ground station version packet.
void FormGroupAddressPacket (GroundStationPkt_t *pPkt, const UInt16 Addresses[], const UInt8 AckRatio[], UInt8 NumAddresses, UInt16 PilotAddress, GSNetworkFlags_t Flags)
Form a ground station group address packet.
UInt8 DecodeGroupAddressPacket (const GroundStationPkt_t *pPkt, UInt16 Addresses[], UInt8 AckRatio[], UInt8 MaxAddresses, UInt16 *pPilotAddress, GSNetworkFlags_t *Flags)
Decode a ground station group address packet.
void FormGSSpectrumSweepPacket (GroundStationPkt_t *pPkt, const SpectrumSweep_t *pSpec)
Form a ground station spectrun sweep packet which contains the results of spectrum analysis run on a coherent MHX radio.
UInt32 FormGSSpectrumSweepDetails (GroundStationPkt_t *pPkt, float StartFreq, float Spacing, UInt16 Dwell, UInt8 NumMeasurements)
From a ground station specturm sweep command packet.
BOOL DecodeGSSpectrumSweepPacket (const GroundStationPkt_t *pPkt, SpectrumSweep_t *pSpec)
Decode a ground station radio spectrum sweep report packet.
BOOL DecodeGSSpectrumSweepDetails (const GroundStationPkt_t *pPkt, float *pStartFreq, float *pSpacing, UInt16 *pDwell, UInt8 *pNumMeasurements)
Decode a ground station spectrum sweep command packet.
void FormGSSpectrumPacket (GroundStationPkt_t *pPkt, const SpectrumAnalyzer_t *pSpec, UInt32 *pIdx)
Form a ground station radio spectrum packet.
BOOL DecodeGSSpectrumPacket (const GroundStationPkt_t *pPkt, SpectrumAnalyzer_t *pSpec, UInt32 *pSeqNum)
Decode a ground station radio spectrum packet.
const GroundStationPkt_t * FormGSUserWarningPacket (GroundStationPkt_t *pPkt, UInt8 Type, UInt8 Code, const char *pWarning)
Form a ground station user warning packet.
const GroundStationPkt_t * FormGSUserWarningPacketEx (GroundStationPkt_t *pPkt, UInt8 Type, UInt8 Code)
Form a ground station user warning packet in place.
char * DecodeGSUserWarningPacket (GroundStationPkt_t *pPkt, UInt8 *pType, UInt8 *pCode)
Decode the ground station user warning packet.
void FormGSResetReportPacket (GroundStationPkt_t *pPkt, UInt16 RSR, UInt16 Vec, UInt32 PC, UInt32 MSR, UInt32 Link, UInt32 FPSCR)
Form the ground station reset report packet.
BOOL DecodeGSResetReportPacket (const GroundStationPkt_t *pPkt, UInt16 *pRSR, UInt16 *pVec, UInt32 *pPC, UInt32 *pMSR, UInt32 *pLink, UInt32 *pFPSCR)
Decode the ground station reset report packet.
void FormDualAntStatusPacket (GroundStationPkt_t *pPkt, const DualAntStatus_t *pData)
Form the dual antenna status packet.
BOOL DecodeDualAntStatusPacket (const GroundStationPkt_t *pPkt, DualAntStatus_t *pData)
Decode the dual antenna status packet.
void FormGroundStationConfigurationPacket (GroundStationPkt_t *pPkt, UInt8 ConfigEnum, UInt8 SBASDisable, UInt8 EnableGD, UInt32 PayloadBaud, UInt8 EnableMHXRelay)
Form the ground station configuration packet.
BOOL DecodeGroundStationConfigurationPacket (const GroundStationPkt_t *pPkt, UInt8 *pConfigEnum, UInt8 *pSBASDisable, UInt8 *pEnableGD, UInt32 *pPayloadBaud, UInt8 *pEnableMHXRelay)
Decode the ground station configuration packet.
void FormGSNamePacket (GroundStationPkt_t *pPkt, const char *pName)
Form a groundstation name packet.
char * DecodeGSNamePacket (GroundStationPkt_t *pPkt)
Decode a groundstation name packet.
void DecodeGroundStationSimControlPacket (const GroundStationPkt_t *pPkt)
Detailed Description
Ground station packet utilities.
This module provides functions for encoding and decoding ground station packets to and from network representation as documented in "Piccolo Communications"
Macro Definition Documentation
#define GS_PKT_OVERHEAD SIMPLE_PKT_OVERHEAD
Amount of overhead in a ground station packet
Referenced by CommBase_SendGroundStationPacket().
Enumeration Type Documentation
enum GSConfigurations
Ground station configuration enumerations
Enumerator
GS_CONFIG_NORMAL
Normal (single internal radio) ground station configuration.
GS_CONFIG_BAI
BAI configured groundstation (secondary 9600 link, split on two ports)
GS_CONFIG_FREE_WAVE_FULL_DUPLEX
Notional free wave configuration (secondary full duplex 57600 link)
GS_CONFIG_TELEDESIGN_HALF_DUPLEX
Teledesign half duplex configuration (secondary half duplex 19200 link with specific timing)
GS_CONFIG_MHX_EXTERNAL_HALF_DUPLEX
Notional MHX external radio (secondary half duplex 57600 link)
GS_CONFIG_AGIG_C2
AGIG C2 link.
enum GSPacketTypes
Ground station message types
Enumerator
ADD_ADDRESS
Add an address to the polling list.
DEL_ADDRESS
Delete an address from the polling list.
PILOT_ADDRESS
Add/change the pilot address.
DGPS_SETTINGS
Differential corrections base station setup.
GS_VERSION
Firmware version of the ground station.
REQUEST_CONFIG
Request complete configuration data.
TRANSMITTER_CON
Reserved.
GS_OLD_TELEMETRY
Old format ground station telemetry.
GROUP_ADDRESS
Gives the entire network configuration.
GS_RADIO_SETTINGS
Radio settings.
GS_SPECTRUM
Spectrum analyzer function and resulting data for up to 127 channels.
DYNAMIC_ENUMERATION
Dynamic enumeration for the network.
GS_SPECTRUM2
Spectrum analyzer function for coherent MHX radios.
GS_USER_WARNING
Warning about user mistakes.
GS_RESET_REPORT
Reset report for the groundstation.
REQ_GPSHOTSTART
Request GPS hotstart.
DUAL_ANT_STATUS
Status report for dual antenna moving reference RTK system.
GS_CONFIGURATION
Change or request ground station configuration settting.
GS_NAME
Groundstation name.
GS_NEW_TELEMETRY
New format ground station telemetry message.
GS_DEVICE_DETAILS
Device details.
GS_GPS_HEALTH
Health information for ground station GPSs.
GS_SIMULATION_CONTROL
Control packet for simulated ground station.
NUM_GS_MSGS
Number of ground station packet types.
Function Documentation
BOOL DecodeDGPSBasePacket (const GroundStationPkt_t * pPkt, DGPSParameter_t * pDGPS)
Decode a DGPS base station packet.
Decode a ground differential corrections packet.
Parameters
pPkt points to the stream packet containing the packet data.
pDGPS points to space to receive the DGPS data.
Returns
TRUE if the packet is valid, else FALSE.
References DGPSParameter_t::AbsoluteHeading, DGPSParameter_t::Align, DGPSParameter_t::BaseHeight, DGPSParameter_t::BaseLat, DGPSParameter_t::BaseLon, SimplePkt_t::Data, DataToSInt32(), DataToUInt16(), DGPS_SETTINGS, DGPSParameter_t::EnableDGPS, Float16ToFloat(), DGPSParameter_t::Heading, DGPSParameter_t::MovingBase, N3D, DGPSParameter_t::Offset, DGPSParameter_t::OutputFormat, SimplePkt_t::PktType, DGPSParameter_t::RightHand, SimplePkt_t::Size, and DGPSParameter_t::UplinkRate.
BOOL DecodeDualAntStatusPacket (const GroundStationPkt_t * pPkt, DualAntStatus_t * pData)
Decode the dual antenna status packet.
Decode a dual antenna stauts report packet
Parameters
pPkt is the packet to decode.
pData receives the data in the packet.
Returns
TRUE if the packet is valid.
References DualAntStatus_t::Baseline, DualAntStatus_t::BaselineSigma, SimplePkt_t::Data, DataToSInt16(), DataToUInt16(), DataToUInt32(), DOWN, DUAL_ANT_STATUS, EAST, DualAntStatus_t::ITOW, DualAntStatus_t::Lag, DualAntStatus_t::LeverArm, DualAntStatus_t::NetHeading, DualAntStatus_t::NetRoll, NORTH, DualAntStatus_t::NumSats, SimplePkt_t::PktType, SimplePkt_t::Size, and DualAntStatus_t::SolnType.
BOOL DecodeGroundStationConfigurationPacket (const GroundStationPkt_t * pPkt, UInt8 * pConfigEnum, UInt8 * pSBASDisable, UInt8 * pEnableGD, UInt32 * pPayloadBaud, UInt8 * pEnableMHXRelay)
Decode the ground station configuration packet.
Decode a ground station configuration packet.
Parameters
pPkt is the packet to decode.
pConfigEnum receives the configuration enumeration, see GSConfigurations.
pSBASDisable receives the SBAS disable flag.
pEnableGD receives the guaranteed delivery enable flag.
pPayloadBaud receives the baud rate in bits per second.
pEnableMHXRelay receives the flag to enable relay reflashing of the microhard radio.
Returns
TRUE if the packet is valid.
References SimplePkt_t::Data, GS_CONFIGURATION, SimplePkt_t::PktType, and SimplePkt_t::Size.
UInt8 DecodeGroupAddressPacket (const GroundStationPkt_t * pPkt, UInt16 Addresses[], UInt8 AckRatio[], UInt8 MaxAddresses, UInt16 * pPilotAddress, GSNetworkFlags_t * Flags)
Decode a ground station group address packet.
Decode a ground station group address packet
Parameters
pPkt points to the stream packet containing the packet data.
Addresses points to an array to hold the addresses from the packet.
AckRatio points to an array to hold the acknowledgement ratios from the packet.
MaxAddresses is the maximum number of addresses and ackratios the arrays can hold.
pPilotAddress points to space to receive the pilot address. If no pilot address is included then zero will be passed.
pDynamic points to space to receive the dynamic enumeration status of the ground station
Returns
The number of addresses decoded from the packet, 0xFF if the packet is invalid.
References GSNetworkFlags_t::AckRatioExcluded, GSNetworkFlags_t::AGIG_C2_GS, GSNetworkFlags_t::BAIFullDuplexGS, SimplePkt_t::Data, GSNetworkFlags_t::Dynamic, GSNetworkFlags_t::ExtMHXHalfDuplexGS, GSNetworkFlags_t::FreeWaveFullDuplexGS, GROUP_ADDRESS, GSNetworkFlags_t::OIPortExternalRadio, SimplePkt_t::PktType, GSNetworkFlags_t::RadioType, SimplePkt_t::Size, and GSNetworkFlags_t::TeledesignHalfDuplexGS.
Referenced by DecodeGroupAddressPacketNew().
BOOL DecodeGroupAddressPacketNew (const GroundStationPkt_t * pPkt, GSUserData_t * pData)
Decode the ground station group address packet in a GSUserData_t structure.
Decode a ground station group address packet
Parameters
pPkt points to the stream packet containing the packet data.
pData receives the packet data.
Returns
TRUE if the packet is decoded correctly.
References GSUserData_t::AckRatio, GSUserData_t::Addresses, DecodeGroupAddressPacket(), GSUserData_t::Flags, GSUserData_t::NumAddresses, and GSUserData_t::PilotAddress.
const char* DecodeGSDeviceDetails (GroundStationPkt_t * pPkt, UInt8 * pIndex, UInt8 * pDevice, BOOL * pComplete)
Decode device details packet.
Decode device details packet.
Parameters
pPkt is the radio to decode.
pIndex receives the packet order index.
pDevice is the device enumerator, reserved (0), internal radio (1), ublox GPS (2), Novatel (3)
pComplete will be TRUE if this is the last radio details packet in the report, else FALSE if more packets are coming.
Returns
a pointer to the null-terminated radio details string in this packet, or NULL if there was a problem with the packet, in which case pComplete will be FALSE.
References SimplePkt_t::Data, GS_DEVICE_DETAILS, MAX_SIMPLE_DATA, SimplePkt_t::PktType, and SimplePkt_t::Size.
BOOL DecodeGSGPSHealth (const GroundStationPkt_t * pPkt, GPSUser_t * pGPS, UInt8 * pIndex, UInt8 * pNum)
Decode GPS health information for a single GPS.
Decode GPS health information for a single GPS.
Parameters
pPkt contains the data to decode.
pGPS receives the GPS health information.
pIndex is the index of this GPS.
pNum is the number of GPSs being reported on.
References GPSUser_t::Accuracy, GPSUser_t::Altitude, SatStatus_t::Azimuth, SimplePkt_t::Data, DataToSInt16(), DataToSInt32(), DataToUInt16(), DataToUInt24(), DGPS_FIX, GPSUser_t::Direction, SatStatus_t::Elevation, FIX3D, FIXEDHEIGHT_PVTYPE, FIXEDPOS_PVTYPE, SatStatus_t::Geometry, GPSUser_t::GPSType, GS_GPS_HEALTH, IONOFREE_FLOAT_PVTYPE, L1_FLOAT_PVTYPE, L1_INTEGER_PVTYPE, SatStatus_t::L1CNo, SatStatus_t::L1TimeOfLock, SatStatus_t::L2CNo, SatStatus_t::L2TimeOfLock, GPSUser_t::Latitude, LLAandNEDtoECEF(), GPSUser_t::Longitude, NARROW_FLOAT_PVTYPE, NARROW_INTEGER_PVTYPE, NO_SATS, NONE_PVTYPE, NUM_SATS, OMNISTAR_HP_PVTYPE, OMNISTAR_VBS_PVTYPE, OMNISTAR_XP_PVTYPE, GPSUser_t::PDOP, SimplePkt_t::PktType, POS_LOCK, GPSUser_t::PosECEF, PROPAGATED_PVTYPE, PSRDIFF_PVTYPE, GPSUser_t::Sat, SBAS_FIX, SBAS_PVTYPE, SINGLE_PVTYPE, SimplePkt_t::Size, GPSUser_t::SolnType, GPSUser_t::Speed, GPSUser_t::Status, SatStatus_t::SVID, GPSUser_t::TrackedSats, SatStatus_t::Used, GPSUser_t::UsedInINS, GPSUser_t::VDown, GPSUser_t::VEast, GPSUser_t::VelECEF, GPSUser_t::VisibleSats, and GPSUser_t::VNorth.
char* DecodeGSNamePacket (GroundStationPkt_t * pPkt)
Decode a groundstation name packet.
Decode a groundstation name packet
Parameters
pPkt A pointer to the packet to decode.
Returns
A pointer to the groundstation name string, or NULL if the packet was not successfully decoded.
References SimplePkt_t::Data, GS_NAME, GS_SIMULATION_CONTROL, MAX_SIMPLE_DATA, SimplePkt_t::PktType, and SimplePkt_t::Size.
Referenced by UdpAutoDetector::checkForNewServers().
BOOL DecodeGSRadioSettingsPacket (const GroundStationPkt_t * pPkt, RadioSettings_t * pSettings)
Deocde a ground station radio settings packet.
Decode a ground station radio settings packet. The radio settings packet is used to control the channel and output power of the radio.
Parameters
pPkt points to a ground station packet to be decoded.
pSettings points to a radio settings structure to receive the data.
Returns
TRUE if the packet is valid, else FALSE.
References RadioSettings_t::AESMode, RadioSettings_t::Channel, SimplePkt_t::Data, DataToFloat(), RadioSettings_t::Freq, GS_RADIO_SETTINGS, RadioSettings_t::Key, SimplePkt_t::PktType, RadioSettings_t::Power, SimplePkt_t::Size, RadioSettings_t::Speed, and RadioSettings_t::Type.
BOOL DecodeGSResetReportPacket (const GroundStationPkt_t * pPkt, UInt16 * pRSR, UInt16 * pVec, UInt32 * pPC, UInt32 * pMSR, UInt32 * pLink, UInt32 * pFPSCR)
Decode the ground station reset report packet.
Extract the data from a reset report packet
Parameters
pPkt points to a packet containing the data.
pSRS points to space receive the contents of the reset status register.
pVec points to space to receive the exception vector (if any).
pPC points to space to receive the exception program counter (if any).
pMSR points to space to receive the exception machine state register (if any).
pLink points to space to receive the link register (if any).
pFPSCR points to space to receive the floating point status and control register (if any).
TRUE if the packet is valid, else FALSE.
References SimplePkt_t::Data, DataToUInt16(), DataToUInt32(), GS_RESET_REPORT, SimplePkt_t::PktType, and SimplePkt_t::Size.
BOOL DecodeGSSpectrumPacket (const GroundStationPkt_t * pPkt, SpectrumAnalyzer_t * pSpec, UInt32 * pSeqNum)
Decode a ground station radio spectrum packet.
Decode a ground station spectrum analyzer packet. This packet contains the results of a spectrum analysis on a frequency hopping radio (i.e. MHX910).
Parameters
pPkt points to a packet to decode.
pSpec points to space to receive the data.
pSeqNum is the packet sequence number, since there may be multiple packets sent if the number of radio channels exceeds 127.
Returns
TRUE if the packet is OK, else FALSE.
References SignalStrength_t::Average, SimplePkt_t::Data, GS_SPECTRUM, SignalStrength_t::Max, SpectrumAnalyzer_t::NumSamples, SimplePkt_t::PktType, SpectrumAnalyzer_t::Signal, and SimplePkt_t::Size.
BOOL DecodeGSSpectrumSweepDetails (const GroundStationPkt_t * pPkt, float * pStartFreq, float * pSpacing, UInt16 * pDwell, UInt8 * pNumMeasurements)
Decode a ground station spectrum sweep command packet.
Decode the frequency, spacing, and dwell time details from a ground station spectrum sweep packet. This packet contains the results of a spectrum analysis on a coherent MHX radio (i.e. MHX420). It may also be used as a request for spectrum in which case only the details listed above are included
Parameters
pPkt points to a packet to decode.
pStartFreq points to space to receive the start frequency in MHz.
pSpace poings to space to receive the measurement spacing in Mhz.
pDwell points to space to receive measurement dwell time in ms.
pNumMeasurements points to space to receive the number of measurents made (or to make).
Returns
TRUE if the packet is OK, else FALSE.
References SimplePkt_t::Data, DataToFloat(), DataToUInt16(), GS_SPECTRUM2, SimplePkt_t::PktType, and SimplePkt_t::Size.
Referenced by DecodeGSSpectrumSweepPacket().
BOOL DecodeGSSpectrumSweepPacket (const GroundStationPkt_t * pPkt, SpectrumSweep_t * pSpec)
Decode a ground station radio spectrum sweep report packet.
Decode a ground station spectrum sweep packet. This packet contains the results of a spectrum analysis on a coherent MHX radio (i.e. MHX420).
Parameters
pPkt points to a packet to decode.
pSpec points to space to receive the data.
Returns
TRUE if the packet is OK, else FALSE.
References SimplePkt_t::Data, DecodeGSSpectrumSweepDetails(), SpectrumSweep_t::Dwell, NUM_SPECTRUM_SWEEP, SpectrumSweep_t::NumMeasurements, SimplePkt_t::Size, SpectrumSweep_t::Spacing, and SpectrumSweep_t::StartFreq.
BOOL DecodeGSTelemetryPacket (const GroundStationPkt_t * pPkt, GSUserData_t * pData)
Decode a ground station telemetry packet, either the old packet or the new, in a GSUserData_t structure.
Decode a ground station telemetry packet, either old or new format.
Parameters
pPkt points to the stream packet containing the packet data.
pData receives the packet information.
Returns
TRUE if the packet decoded correctly.
References GPSUser_t::Altitude, SystemDiagnostic_t::BoardTemp, SystemDiagnostic_t::CPULoad, SystemDiagnostic_t::CPUVoltageBIT, SimplePkt_t::Data, DataToSInt16(), DataToSInt32(), DataToUInt16(), DataToUInt24(), DataToUInt32(), GPSUser_t::day, GPSUser_t::Direction, SystemDiagnostic_t::FirstStageBIT, SystemDiagnostic_t::FiveAnalogBIT, SystemDiagnostic_t::FiveDigitalBIT, GSUserData_t::GPS, gps_to_ymdhms(), SystemDiagnostic_t::GPSVoltageBIT, GS_NEW_TELEMETRY, GS_OLD_TELEMETRY, GPSUser_t::hours, SystemDiagnostic_t::InputCurrent, SystemDiagnostic_t::InputVoltage, GPSUser_t::ITOW, GPSUser_t::Latitude, LLAandNEDtoECEF(), GPSUser_t::Longitude, GPSUser_t::minutes, GPSUser_t::month, SystemDiagnostic_t::NoInternalGPS, GPSUser_t::PDOP, GSUserData_t::PilotSamplePercentage, GSUserData_t::PilotUplinkRate, SimplePkt_t::PktType, GPSUser_t::PosECEF, SystemDiagnostic_t::RadioVoltageBIT, SystemDiagnostic_t::RSSI, GPSUser_t::seconds, SimplePkt_t::Size, GPSUser_t::SolnType, GPSUser_t::Speed, GPSUser_t::Status, GSUserData_t::System, GSUserData_t::SystemTime, SystemDiagnostic_t::TempBIT, SystemDiagnostic_t::TempDisagreeBIT, GPSUser_t::TrackedSats, GPSUser_t::VDown, GPSUser_t::VEast, GPSUser_t::VelECEF, GPSUser_t::VisibleSats, GPSUser_t::VNorth, SystemDiagnostic_t::VSWR, GPSUser_t::Week, GPSUser_t::year, and ymdhms_to_gps().
char* DecodeGSUserWarningPacket (GroundStationPkt_t * pPkt, UInt8 * pType, UInt8 * pCode)
Decode the ground station user warning packet.
Decode a user warning packet. This packet contains an ASCII string which can be displayed to the user as a warning.
Parameters
pPkt points to a packet containing the data.
pType receives the type info in the pakcet.
pCode receives the code info in the packet.
Returns
A null terminated string pointer containing the error, or NULL if the packet is invalid.
References SimplePkt_t::Data, GS_USER_WARNING, MAX_SIMPLE_DATA, SimplePkt_t::PktType, and SimplePkt_t::Size.
BOOL DecodeGSVersionPacket (const GroundStationPkt_t * pPkt, Version_t * pVersion, Board_t * pBoard)
Decode a ground station version packet.
Decode a ground hardware and firmware version packet.
Parameters
pPkt points to the stream packet containing the packet data.
pVersion points to space to receive the firmware version data. If NULL the version data aren't decoded.
pBoard points to space to receive the hardware verions data. If NULL the version data data aren't decoded.
Returns
TRUE if the packet is valid, else FALSE
References Board_t::BoardSN, Board_t::Config, SimplePkt_t::Data, DataToUInt16(), DataToUInt32(), Version_t::Date, Board_t::Date, Date_t::day, Version_t::Description, GS_VERSION, Version_t::MajorVersion, Version_t::MinorVersion, Date_t::month, Version_t::PatchNum, SimplePkt_t::PktType, Board_t::ProductSN, Version_t::Released, Board_t::Rev, Version_t::Revision, SimplePkt_t::Size, Version_t::SubVersion, and Date_t::year.
void FormDGPSBasePacket (GroundStationPkt_t * pPkt, const DGPSParameter_t * pDGPS)
Form a DGPS base station packet.
Form a ground station DGPS packet including the packet header and crc.
Parameters
pPkt points to a stream packet to receive the formatted data.
pDGPS points to DGPS data to be included in the packet.
References DGPSParameter_t::AbsoluteHeading, DGPSParameter_t::Align, DGPSParameter_t::BaseHeight, DGPSParameter_t::BaseLat, DGPSParameter_t::BaseLon, SimplePkt_t::Data, DGPS_SETTINGS, DGPSParameter_t::EnableDGPS, FloatToFloat16(), DGPSParameter_t::Heading, MakeGroundStationPacket(), DGPSParameter_t::MovingBase, N3D, DGPSParameter_t::Offset, DGPSParameter_t::OutputFormat, DGPSParameter_t::RightHand, RoundToSInt32(), RoundToUInt16(), SInt32ToData(), UInt16ToData(), and DGPSParameter_t::UplinkRate.
Referenced by CommBase_SendDGPSBasePacket().
void FormDualAntStatusPacket (GroundStationPkt_t * pPkt, const DualAntStatus_t * pData)
Form the dual antenna status packet.
Create a dual antenna stauts report packet
Parameters
pPkt points to space to receive the formated packet.
pData contains the data to put in the packet
References DualAntStatus_t::Baseline, DualAntStatus_t::BaselineSigma, SimplePkt_t::Data, DOWN, DUAL_ANT_STATUS, EAST, DualAntStatus_t::ITOW, DualAntStatus_t::Lag, DualAntStatus_t::LeverArm, MakeGroundStationPacket(), DualAntStatus_t::NetHeading, DualAntStatus_t::NetRoll, NORTH, DualAntStatus_t::NumSats, RoundToSInt16(), RoundToUInt16(), RoundToUInt8(), SInt16ToData(), DualAntStatus_t::SolnType, UInt16ToData(), and UInt32ToData().
void FormGroundStationConfigurationPacket (GroundStationPkt_t * pPkt, UInt8 ConfigEnum, UInt8 SBASDisable, UInt8 EnableGD, UInt32 PayloadBaud, UInt8 EnableMHXRelay)
Form the ground station configuration packet.
Create a ground station configuration packet
Parameters
pPkt points to space to receive the formatted packet.
ConfigEnum is the ground station configuration enumeration, see GSConfigurations.
SBASDisable is the disable SBAS flag.
EnableGD is the enable guaranteed delivery flag.
PayloadBaud is the payload baud rate in bits per second.
EnableMHXRelay should be true to enable relay reflashing of the microhard radio.
References SimplePkt_t::Data, GS_CONFIGURATION, and MakeGroundStationPacket().
Referenced by CommBase_SendGSConfiguration().
void FormGroupAddressPacket (GroundStationPkt_t * pPkt, const UInt16 Addresses[], const UInt8 AckRatio[], UInt8 NumAddresses, UInt16 PilotAddress, GSNetworkFlags_t Flags)
Form a ground station group address packet.
Form a ground station group address packet which includes the entire network configuration; as well as the packet header and crc.
Parameters
pPkt points to a stream packet to receive the formatted data.
Addresses points to an array of addresses to be included in the packet.
AckRatio points to an array of acknowledgment ratios to be included in the packet
NumAddresses is the number of addresses contained in the array.
PilotAddress identifies the address which is tagged to receive pilot data
Flags gives the datalink flag bits
References GSNetworkFlags_t::AckRatioExcluded, GSNetworkFlags_t::AGIG_C2_GS, GSNetworkFlags_t::BAIFullDuplexGS, SimplePkt_t::Data, GSNetworkFlags_t::Dynamic, GSNetworkFlags_t::ExtMHXHalfDuplexGS, GSNetworkFlags_t::FreeWaveFullDuplexGS, GROUP_ADDRESS, MakeGroundStationPacket(), GSNetworkFlags_t::OIPortExternalRadio, GSNetworkFlags_t::RadioType, and GSNetworkFlags_t::TeledesignHalfDuplexGS.
const char* FormGSDeviceDetailsPacket (GroundStationPkt_t * pPkt, const char * pDetails, UInt8 IndexThis, UInt8 Device, BOOL FinalDevice)
Form the radio details packet.
Form the device details packet
Parameters
pPkt points to a autopilot packet to receive the formatted data.
IndexThis is the index of this detail report packet.
Device is the device enumerator, reserved (0), internal radio (1), ublox GPS (2), Reference Novatel (3), Rover Novatel (4)
FinalDevice should be TRUE if this is the last device to report on.
Returns
A pointer to the next chunk of string to send, or NULL if finished.
References SimplePkt_t::Data, GS_DEVICE_DETAILS, and MakeGroundStationPacket().
void FormGSGPSHealthPacket (GroundStationPkt_t * pPkt, const GPS_t * pGPS, UInt8 Index, UInt8 Num)
Form a packet that describes the GPS health information, including satellite data.
Form a packet that describes the GPS health information, including satellite data.
Parameters
pPkt receives the formatted packet.
pGPS contains the data to encode
Index is the index of this GPS.
Num is the number of GPSs being reported on.
References GPS_t::Altitude, SatStatus_t::Azimuth, SimplePkt_t::Data, SatStatus_t::Elevation, SatStatus_t::Geometry, GPS_t::GPSType, GS_GPS_HEALTH, GPS_t::HortAccuracy, SatStatus_t::L1CNo, SatStatus_t::L1TimeOfLock, SatStatus_t::L2CNo, SatStatus_t::L2TimeOfLock, GPS_t::Latitude, GPS_t::Longitude, MakeGroundStationPacket(), MAX_SIMPLE_DATA, NUM_SATS, GPS_t::PDOP, RoundToSInt16(), RoundToSInt32(), RoundToUInt16(), RoundToUInt24(), GPS_t::Sat, SInt16ToData(), SInt32ToData(), GPS_t::SolnType, GPS_t::Status, SatStatus_t::SVID, GPS_t::TrackedSats, UInt16ToData(), UInt24ToData(), SatStatus_t::Used, GPS_t::UsedInINS, GPS_t::VDown, GPS_t::VEast, GPS_t::VertAccuracy, GPS_t::VisibleSats, and GPS_t::VNorth.
void FormGSNamePacket (GroundStationPkt_t * pPkt, const char * pName)
Form a groundstation name packet.
Form a groundstation name packet.
Parameters
pPkt Points to space to receive the formatted packet.
pName A pointer to a string containing the name of the groundstation.
References SimplePkt_t::Data, GS_NAME, and MakeGroundStationPacket().
void FormGSRadioSettingsPacket (GroundStationPkt_t * pPkt, const RadioSettings_t * pSettings)
Form a ground station radio settings packet.
Form a ground station radio settings packet including the packet header and crc. The radio settings packet is used to control the channel and output power of the radio.
Parameters
pPkt points to a ground station packet to receive the formatted data.
pSettings points to radio settings to be included in the packet.
References RadioSettings_t::AESMode, RadioSettings_t::Channel, SimplePkt_t::Data, FloatToData(), RadioSettings_t::Freq, GS_RADIO_SETTINGS, RadioSettings_t::Key, MakeGroundStationPacket(), RadioSettings_t::Power, RoundToUInt8(), RadioSettings_t::Speed, and RadioSettings_t::Type.
Referenced by CommBase_SendGSRadioSettingsPacket().
void FormGSResetReportPacket (GroundStationPkt_t * pPkt, UInt16 RSR, UInt16 Vec, UInt32 PC, UInt32 MSR, UInt32 Link, UInt32 FPSCR)
Form the ground station reset report packet.
Create a reset report packet
Parameters
pPkt points to space to receive the formated packet.
RSR is the reset satus register contents.
Vec is the exception vector (if any).
PC is the exception program counter (if any).
MSR is the exception machine state register (if any).
Link is the link register (if any).
FPSCR is the floating point status and control register (if any).
References SimplePkt_t::Data, GS_RESET_REPORT, MakeGroundStationPacket(), UInt16ToData(), and UInt32ToData().
void FormGSSpectrumPacket (GroundStationPkt_t * pPkt, const SpectrumAnalyzer_t * pSpec, UInt32 * pIdx)
Form a ground station radio spectrum packet.
Form a ground station spectrum sweep packet. This packet contains the results of a spectrum analysis on a frequency hopping radio (i.e. MHX910). The packet can fit only 127 radio channels. If the radio has more channels, multiple packets of this type should be sent. The starting index pointer can be used for this, since it is updated by this function.
Parameters
pPkt is the resulting groundstation packet.
pSpec to the the spectrum data.
pIdx points to the starting index in the channel data array. This index is incremented for each channel that is sent in this packet.
References SignalStrength_t::Average, SimplePkt_t::Data, GS_SPECTRUM, MakeGroundStationPacket(), SignalStrength_t::Max, SpectrumAnalyzer_t::NumSamples, and SpectrumAnalyzer_t::Signal.
UInt32 FormGSSpectrumSweepDetails (GroundStationPkt_t * pPkt, float StartFreq, float Spacing, UInt16 Dwell, UInt8 NumMeasurements)
From a ground station specturm sweep command packet.
Form the frequency, spacing, and dwell time details of a ground station spectrum sweep packet. This function will not complete the packet formation, MakeGroundStationPacket() must still be called
Parameters
pPkt points to a stream packet to receive the formatted data.
StartFreq is the frequency to begin the sweep in MHz.
Spacing is the space between frequencies in MHz.
Dwell is the dwell time for each measurement in ms.
NumMeasurements is the number of measurements made (or to make).
Returns
The number of bytes used to encode the data.
References SimplePkt_t::Data, FloatToData(), SimplePkt_t::Size, and UInt16ToData().
Referenced by CommBase_RequestGSCoherentSpectrumSweepPacket(), and FormGSSpectrumSweepPacket().
void FormGSSpectrumSweepPacket (GroundStationPkt_t * pPkt, const SpectrumSweep_t * pSpec)
Form a ground station spectrun sweep packet which contains the results of spectrum analysis run on a coherent MHX radio.
Form a ground station spectrum sweep packet. This packet contains the results of spectrum analysis run on a coherent MHX radio (i.e. MHX420)
Parameters
pPkt points to a stream packet to receive the formatted data.
pSpec to the the spectrum sweep data.
References SimplePkt_t::Data, SpectrumSweep_t::Dwell, FormGSSpectrumSweepDetails(), GS_SPECTRUM2, MakeGroundStationPacket(), NUM_SPECTRUM_SWEEP, SpectrumSweep_t::NumMeasurements, SpectrumSweep_t::Spacing, and SpectrumSweep_t::StartFreq.
void FormGSTelemetryPacket (GroundStationPkt_t * pPkt, UInt32 Time, const GPS_t * pGPS, const SystemDiagnostic_t * pSystem, float PilotSamplePercentage, float PilotUplinkRate)
Form a ground station telemetry packet.
Form a ground station telemetry packet including the packet header and crc.
Parameters
pPkt points to a stream packet to receive the formatted data.
Time is the system time since reset in milliseconds.
pGPS points to GPS data to be included in the packet.
pSystem points to system diagnostic data to be included in the packet.
PilotSamplePercentage is percentage of good pilot data measured by the groundstation.
PilotUplinkRate is the rate (in Herz) of pilot uplink data.
References GPS_t::Altitude, SystemDiagnostic_t::BoardTemp, SystemDiagnostic_t::CPULoad, SystemDiagnostic_t::CPUVoltageBIT, SimplePkt_t::Data, SystemDiagnostic_t::FirstStageBIT, SystemDiagnostic_t::FiveAnalogBIT, SystemDiagnostic_t::FiveDigitalBIT, SystemDiagnostic_t::GPSVoltageBIT, GS_NEW_TELEMETRY, SystemDiagnostic_t::InputCurrent, SystemDiagnostic_t::InputVoltage, GPS_t::ITOW, GPS_t::Latitude, GPS_t::Leapmilliseconds, GPS_t::Longitude, MakeGroundStationPacket(), SystemDiagnostic_t::NoInternalGPS, GPS_t::PDOP, SystemDiagnostic_t::RadioVoltageBIT, RoundToSInt16(), RoundToSInt32(), RoundToSInt8(), RoundToUInt16(), RoundToUInt24(), RoundToUInt32(), RoundToUInt8(), SystemDiagnostic_t::RSSI, SInt16ToData(), SInt32ToData(), GPS_t::SolnType, GPS_t::Status, SystemDiagnostic_t::TempBIT, SystemDiagnostic_t::TempDisagreeBIT, GPS_t::TrackedSats, UInt16ToData(), UInt24ToData(), UInt32ToData(), GPS_t::VDown, GPS_t::VEast, GPS_t::VisibleSats, GPS_t::VNorth, SystemDiagnostic_t::VSWR, and GPS_t::Week.
const GroundStationPkt_t* FormGSUserWarningPacket (GroundStationPkt_t * pPkt, UInt8 Type, UInt8 Code, const char * pWarning)
Form a ground station user warning packet.
Encode the warning string in the packet.
Parameters
pPkt receives the formatted data.
Type is the packet type to include.
Code is the error code to include.
pWarning points to the null-terminated warning to encode.
Returns
A pointer to the autopilot packet (pPkt).
References SimplePkt_t::Data, GS_USER_WARNING, and MakeGroundStationPacket().
Referenced by FormGSUserWarningPacketEx().
const GroundStationPkt_t* FormGSUserWarningPacketEx (GroundStationPkt_t * pPkt, UInt8 Type, UInt8 Code)
Form a ground station user warning packet in place.
Encode a packet with a warning string. In this case the string is already placed in the packet.
Parameters
pPkt receives the formatted data.
Type is the packet type to include.
Code is the error code to include.
Returns
A pointer to the autopilot packet (pPkt).
References SimplePkt_t::Data, and FormGSUserWarningPacket().
void FormGSVersionPacket (GroundStationPkt_t * pPkt, const Version_t * pVersion, const Board_t * pBoard)
Form a ground station version packet.
Form a ground station hardware and firmware version packet including the packet header and crc.
Parameters
pPkt points to a stream packet to receive the formatted data.
pVersion points to firmware version data to be included in the packet.
pBoard points to system diagnostic data to be included in the packet.
References Board_t::BoardSN, Board_t::Config, SimplePkt_t::Data, Version_t::Date, Board_t::Date, Date_t::day, Version_t::Description, GS_VERSION, Version_t::MajorVersion, MakeGroundStationPacket(), Version_t::MinorVersion, Date_t::month, Version_t::PatchNum, Board_t::ProductSN, Version_t::Released, Board_t::Rev, Version_t::Revision, Version_t::SubVersion, UInt16ToData(), UInt32ToData(), and Date_t::year.