Communications SDK: Iridium.h File Reference
Iridium.h File Reference
Platform Independent Iridium functions.
#include "Types.h"
#include "Serial.h"
#include <stdlib.h>
Macros
#define IRIDIUM_REFRESH_SEC 90
#define IRIDIUM_BAUD 2400
#define IRIDIUM_STATEMACHINE_ENABLED
Enumerations
enum IridiumDefaultModes {
HANGUP_OFF_MODE, HANGUP_MODE, DIAL_MODE, AUTOANSWER_MODE,
CONNECTED_MODE
}
Enumerate the Iridium modes.
Functions
void EnableIridiumPower (void)
Enable Iridium power.
void DisableIridiumPower (void)
Disable Iridium power.
BOOL IridiumIsConnected (void)
Returns TRUE if the Iridium is enabled and the link is currently connected.
BOOL IridiumIsEnabled (void)
void SetIridiumPhoneNumber (const char *pPhoneNumber)
BOOL bIridiumLostCarrier (Serial_t *pPort)
BOOL InitIridium (UInt8 chan, UInt32 QSize, int DefaultMode, const char *pNumber, Serial_t *pPort)
void InitIridiumExternalComm (Serial_t *pPort, int DefaultMode, const char *pNumber)
BOOL IridiumStateDriver (Serial_t *pPort, char *pNumber)
size_t GetIridiumStatusString (char *pString, size_t count)
size_t GetLastIridiumErrorString (char *pString, size_t count)
BOOL bIridiumCarrierDetectIsActive (Serial_t *pPort)
void SetIridiumDTRActive (Serial_t *pPort)
void SetIridiumDTRInactive (Serial_t *pPort)
void HangUpIridiumRedial (void)
Change Iridium state: Hang up Iridium but redial.
void HangUpIridium (void)
Change Iridium state: Hang up Iridium (continue to redial or autoanswer states)
void HangUpIridiumIdle (void)
Change Iridium state: Hang up Iridium and go to an idle state.
void StartDialingIridium (void)
Change Iridium state: Start the dialout state.
BOOL IridiumTimeoutHasExpired (void)
void RefreshIridiumTimeout (void)
Refresh the Iridium state machine timeout.
Detailed Description
Platform Independent Iridium functions.
Hardware independent Iridium software
Enumeration Type Documentation
enum IridiumDefaultModes
Enumerate the Iridium modes.
Enumerator
HANGUP_OFF_MODE
Hangup to an idle state.
HANGUP_MODE
Hangup and resume dial or answer mode.
DIAL_MODE
Start out in dial mode.
AUTOANSWER_MODE
Start out in autoanswer mode.
CONNECTED_MODE
Start out connected (and resume dial/answer mode as necessary)
Function Documentation
BOOL bIridiumCarrierDetectIsActive (Serial_t * pPort)
Returns TRUE if the carrier detect line is active.
Parameters
pPort is the serial channel
Returns
TRUE if carrier detect is active.
References bCarrierDetectIsActive().
Referenced by bIridiumLostCarrier().
BOOL bIridiumLostCarrier (Serial_t * pPort)
Returns whether Iridium carrier detect has been lost.
Parameters
pPort is the Iridium pPortnel in question
Returns
Returns TRUE if Carrier has been lost (i.e. carrier detect is not active)
References bIridiumCarrierDetectIsActive().
Referenced by IridiumStateDriver().
void DisableIridiumPower (void)
Disable Iridium power.
Referenced by IridiumStateDriver().
void EnableIridiumPower (void)
Enable Iridium power.
Referenced by InitIridiumExternalComm(), and IridiumStateDriver().
size_t GetIridiumStatusString (char * pString, size_t count)
Return a status string which a human user can use to understand what's going on with the Iridium machine
Parameters
pString is the status string to write to.
count is the maximum number of characters to write (not always obeyed).
Returns
returns the number of characters written to.
size_t GetLastIridiumErrorString (char * pString, size_t count)
Return an error string which a human user can use to understand what's going on with the Iridium machine
Parameters
pString is the string
count is the maximum number of characters to write.
Returns
returns the number of characters written to.
void HangUpIridium (void)
Change Iridium state: Hang up Iridium (continue to redial or autoanswer states)
Referenced by IridiumStateDriver().
void HangUpIridiumIdle (void)
Change Iridium state: Hang up Iridium and go to an idle state.
Referenced by DeinitIridiumExternalComm().
void HangUpIridiumRedial (void)
Change Iridium state: Hang up Iridium but redial.
BOOL InitIridium (UInt8 chan, UInt32 QSize, int DefaultMode, const char * pNumber, Serial_t * pPort)
Initialize the Iridium unit connected to the serial channel chan
Parameters
chan is the Iridium serial channel
QSize is the size of the serial queue to use
DefaultMode is the default mode of the Iridium state machine, enumerated by IridiumDefaultModes in Iridium.h: HANGUP_OFF_MODE,HANGUP_MODE,DIAL_MODE,AUTOANSWER_MODE,CONNECTED_MODE
pNumber is the phone to use. If NULL than the default number is used.
pPort receives the open serial port.
Returns
TRUE if the serial port opened correctly
References BOTH_DIR, FLOW_NONE, InitIridiumExternalComm(), NO_PARITY, and OpenCOMM().
void InitIridiumExternalComm (Serial_t * pPort, int DefaultMode, const char * pNumber)
Initialize the Iridium unit connected to the serial channel chan
Parameters
pPort is the Iridium serial channel
QSize is the size of the serial queue to use
DefaultMode is the default mode of the Iridium state machine, enumerated by IridiumDefaultModes in Iridium.h: HANGUP_OFF_MODE,HANGUP_MODE,DIAL_MODE,AUTOANSWER_MODE,CONNECTED_MODE
pNumber is the phone to use. If NULL than the default number is used.
Returns
TRUE if the serial port opened correctly
References AUTOANSWER_MODE, CONNECTED_MODE, DIAL_MODE, EnableIridiumPower(), HANGUP_MODE, HANGUP_OFF_MODE, RefreshIridiumTimeout(), SetIridiumDTRActive(), and SetIridiumPhoneNumber().
Referenced by InitIridium().
BOOL IridiumIsConnected (void)
Returns TRUE if the Iridium is enabled and the link is currently connected.
Referenced by DeinitIridiumExternalComm().
BOOL IridiumIsEnabled (void)
Return TRUE if the iridium state machine is enabled
Referenced by DeinitIridiumExternalComm().
BOOL IridiumStateDriver (Serial_t * pPort, char * pNumber)
Basic state machine which must be called periodically to service the dial and answer sequence
Parameters
pPort is the serial port pPortnel
pNumber is the phone number (if necessary)
Returns
Returns TRUE if connected, FALSE otherwise.
References bIridiumLostCarrier(), ChangeBaud(), CheckForResponse(), DisableIridiumPower(), EnableIridiumPower(), HangUpIridium(), IridiumTimeoutHasExpired(), PurgeRxQ(), PurgeTxQ(), RefreshIridiumTimeout(), SetIridiumDTRActive(), SetIridiumDTRInactive(), and WriteStringQuick().
Referenced by DeinitIridiumExternalComm().
BOOL IridiumTimeoutHasExpired (void)
Check to see if Iridium timeout has expired.
Returns
Returns TRUE if the Iridium timeout has expired (or has not been refreshed yet).
Referenced by IridiumStateDriver().
void RefreshIridiumTimeout (void)
Refresh the Iridium state machine timeout.
Referenced by InitIridiumExternalComm(), and IridiumStateDriver().
void SetIridiumDTRActive (Serial_t * pPort)
Set the DTR line active.
Parameters
pPort is the serial channel
References SetDTRActive().
Referenced by InitIridiumExternalComm(), and IridiumStateDriver().
void SetIridiumDTRInactive (Serial_t * pPort)
Set the DTR line inactive.
Parameters
pPort is the serial channel
References SetDTRInactive().
Referenced by IridiumStateDriver().
void SetIridiumPhoneNumber (const char * pPhoneNumber)
Saves the Iridium phone number to reserved storage
Parameters
The phone number string
Referenced by InitIridiumExternalComm().
void StartDialingIridium (void)
Change Iridium state: Start the dialout state.