Communications SDK: IridiumGround.h File Reference
IridiumGround.h File Reference
Iridium Ground utils.
#include "Serial.h"
Enumerations
enum IridiumCommModes {
DIRECT_SERIAL_MODE, CLIENT_MODE, SERVER_MODE, IRIDIUM_DIRECT_DIAL_MODE,
IRIDIUM_DIRECT_AUTOANSWER_MODE, IRIDIUM_TELNET_DIAL_MODE, N_MAX_COMM_MODES
}
Functions
void DeinitIridium (Serial_t *pPort)
void DeinitIridiumExternalComm (Serial_t *pPort)
char * GetIridiumPhoneNumberPtr (void)
Detailed Description
Iridium Ground utils.
This module provides utilities for the Iridium state machine for ground based systems
Function Documentation
void DeinitIridium (Serial_t * pPort)
Close down the iridium link. If Iridium is connected this will actually hang up the modem before closing the serial port
Parameters
chan is the serial port the Iridium modem is connected to.
References CloseCOMM(), and DeinitIridiumExternalComm().
void DeinitIridiumExternalComm (Serial_t * pPort)
Close down the iridium link. If Iridium is connected this will actually hang up the modem. The comm port will remain open for manipulation by external caller.
Parameters
pPort is the serial port the Iridium modem is connected to.
References HangUpIridiumIdle(), IridiumIsConnected(), IridiumIsEnabled(), and IridiumStateDriver().
Referenced by DeinitIridium().
char* GetIridiumPhoneNumberPtr (void)
Returns
Returns a pointer to the Iridium phone number