Communications SDK: LegacyCamera.h File Reference
LegacyCamera.h File Reference
Routines for converting from legacy to new camera defintions.
#include "GimbalPacketGeneric.h"
Enumerations
Legacy Camera type enumeration
enum LegacyCameraTypes {
FLIR_HRC_CZOOM = 0x58, FLIR_640_TAU_32 = 0x5D, FLIR_640_TAU_25, FLIR_320_PHOTON_14,
FLIR_320_PHOTON_20, FLIR_320_PHOTON_23, FLIR_320_PHOTON_36, FLIR_320_PHOTON_50,
FLIR_320_PHOTON_20P, FLIR_320_PHOTON_14P, FLIR_640_PHOTON_15, FLIR_640_PHOTON_26,
FLIR_640_PHOTON_DELTA, FLIR_640_PHOTON_DELTA_P, FLIR_640_TAU_10, FLIR_640_TAU_10_P,
FLIR_640_TAU_DELTA, FLIR_640_TAU_DELTA_P, THERMOTEKNIX_MIRICLE_110_41 = 0x70, THERMOTEKNIX_MIRICLE_110_24,
THERMOTEKNIX_MIRICLE_110_15, THERMOTEKNIX_MIRICLE_110_10, THERMOTEKNIX_MIRICLE_307_48 = 0x78, THERMOTEKNIX_MIRICLE_307_28,
THERMOTEKNIX_MIRICLE_307_18, THERMOTEKNIX_MIRICLE_307_12, THERMOTEKNIX_MIRICLE_307_DELTA, THERMOTEKNIX_MIRICLE_307_26,
THERMOTEKNIX_MIRICLE_307_DELTA_P, SANYO_VCC_ZM300 = 0x80, BEMEYERS_NAVAIR = 0x90, SKU_320_KTX_29 = 0xA0,
SKU_640_KTSX, SKU_320_KTX_18, SKU_640_KTSTING, SKU_320_KTX_15,
PROSILICA_2450_56 = 0xB0, PROSILICA_2450_39, PROSILICA_2450_28, PROSILICA_2450_21,
PROSILICA_2450_14, PROSILICA_2450_10
}
Functions
BOOL ConvertFromLegacyTypeToLegacyCameraDef (CameraDefinition_1_t *pCamera, UInt8 LegacyType)
Convert from legacy camera description to old style camera definitions type.
BOOL ConvertFromLegacyCameraType (CameraDefinition_t *pCamera, UInt8 LegacyType)
Convert from legacy camera description to new camera definitions type.
void ConvertLegacyToNewCameraDef (const CameraDefinition_1_t *pOld, CameraDefinition_t *pNew)
Convert old style camera definitions to the new style camera definitions.
UInt8 ConvertToLegacyCamera (const CameraDefinition_t *pCamera)
Convert from a new camera description to the legacy type.
const char * GetLegacyCameraStringName (UInt8 LegacyType)
Take the old legacy type and return a string description.
BOOL IsLegacyProsilicaCamera (UInt8 LegacyType)
Return true if the passed legacy camera type is a prosilica camera.
BOOL IsLegacyTypeSUCamera (UInt8 LegacyType)
Return TRUE if the passed legacy camera type is a goodrich SU camera.
BOOL IsLegacyTypeThermoCamera (UInt8 LegacyType)
Return true if the passed legacy camera type is a Thermoteknix camera.
BOOL IsLegacyTypeIndigoCamera (UInt8 LegacyType)
Return true if the passed legacy camera type is a FLIR/Indigo camera.
BOOL IsLegacyTypeTauCamera (UInt8 LegacyType)
Return true if the passed legacy camera type is FLIR Tau camera.
BOOL IsLegacyTypeSonyCamera (UInt8 LegacyType)
Return true if the passed legacy camera type is a sony camera.
Detailed Description
Routines for converting from legacy to new camera defintions.
Enumeration Type Documentation
enum LegacyCameraTypes
Enumerator
FLIR_HRC_CZOOM
Continuous zoom from 2 to 20.
FLIR_640_TAU_32
31.954 deg HFOV, 19mm lens
FLIR_640_TAU_25
24.552 deg HFOV, 25mm lens
FLIR_320_PHOTON_14
14 deg HFOV, 0x5f
FLIR_320_PHOTON_20
20 deg HFOV, 0x60
FLIR_320_PHOTON_23
23 deg HFOV, 0x61
FLIR_320_PHOTON_36
36 deg HFOV, 0x62
FLIR_320_PHOTON_50
50 deg HFOV, 0x63
FLIR_320_PHOTON_20P
20 deg HFOV, PAL, 0x64
FLIR_320_PHOTON_14P
14 deg HFOV, PAL, 0x65
FLIR_640_PHOTON_15
15.2 deg HFOV, 0x66
FLIR_640_PHOTON_26
26 deg HFOV, 067
FLIR_640_PHOTON_DELTA
Bi-field of view 22.5 and 9, 40mm - 100mm, 0x68.
FLIR_640_PHOTON_DELTA_P
PAL version of the Photon Delta, 0x69.
FLIR_640_TAU_10
10.5 deg HFOV, 0x6A
FLIR_640_TAU_10_P
12.5 deg HFOV, 0x6B
FLIR_640_TAU_DELTA
Bi-field of view 15.2 and 6.2, 40mm - 100mm, 0x6C.
FLIR_640_TAU_DELTA_P
PAL version of the tau Delta, 0x6D.
THERMOTEKNIX_MIRICLE_110_41
40.9 deg HFOV, 18mm focal length, 0x70
THERMOTEKNIX_MIRICLE_110_24
23.7 deg HFOV, 32mm focal length, 0x71
THERMOTEKNIX_MIRICLE_110_15
15.3 deg HFOV, 50mm focal length, 0x72
THERMOTEKNIX_MIRICLE_110_10
10.2 deg HFOV, 75mm focal length, 0x73
THERMOTEKNIX_MIRICLE_307_48
47.9 deg HFOV, 18mm focal length, 0x78
THERMOTEKNIX_MIRICLE_307_28
28.1 deg HFOV, 32mm focal length, 0x79
THERMOTEKNIX_MIRICLE_307_18
18.2 deg HFOV, 50mm focal length, 0x7A
THERMOTEKNIX_MIRICLE_307_12
12.2 deg HFOV, 75mm focal length, 0x7B
THERMOTEKNIX_MIRICLE_307_DELTA
Bi-field of view 22.5 and 9, 40mm - 100mm, 0x7C.
THERMOTEKNIX_MIRICLE_307_26
25.8 deg HFOV, 35mm focal length, 0x7D
THERMOTEKNIX_MIRICLE_307_DELTA_P
PAL version of the thermoteknix Delta.
BEMEYERS_NAVAIR
BE Meyers camera ????
SKU_320_KTX_29
28.7 deg HFOV
SKU_640_KTSX
10.4 deg HFOV
SKU_320_KTX_18
18.2 deg HFOV
SKU_640_KTSTING
Dual field of view 12.2/6.1 deg HFOV.
SKU_320_KTX_15
14.6 deg HFOV, 50 mm
PROSILICA_2450_56
Prosilica GC2450 with 8 mm, 56 deg FOV lens.
PROSILICA_2450_39
Prosilica GC2450 with 12 mm, 39 deg FOV lens.
PROSILICA_2450_28
Prosilica GC2450 with 17 mm, 28 deg FOV lens.
PROSILICA_2450_21
Prosilica GC2450 with 23 mm, 21 deg FOV lens.
PROSILICA_2450_14
Prosilica GC2450 with 35 mm, 14 deg FOV lens.
PROSILICA_2450_10
Prosilica GC2450 with 50 mm, 10 deg FOV lens.
Function Documentation
BOOL ConvertFromLegacyCameraType (CameraDefinition_t * pCamera, UInt8 LegacyType)
Convert from legacy camera description to new camera definitions type.
Convert from legacy camera description to new camera definitions type
Parameters
pCamera is the new camera definitions.
LegacyType is the legacy camera enumerator.
References ConvertFromLegacyTypeToLegacyCameraDef(), and ConvertLegacyToNewCameraDef().
Referenced by DecodeCameraDefinitionsPacket(), DecodeGimbalVersion2Packet(), and DecodeGimbalVersionPacket().
BOOL ConvertFromLegacyTypeToLegacyCameraDef (CameraDefinition_1_t * pCamera, UInt8 LegacyType)
Convert from legacy camera description to old style camera definitions type.
Convert from legacy camera description to new camera definitions type
Parameters
pCamera is the new camera definitions.
LegacyType is the legacy camera enumerator.
References CameraDefinition_1_t::AutoCameraType, CAMERA_TYPE_320_KTX, CAMERA_TYPE_640_KTX, CAMERA_TYPE_DUMB_CAMERA, CAMERA_TYPE_HRC, CAMERA_TYPE_PHOTON, CAMERA_TYPE_SONY, CAMERA_TYPE_TAU, CAMERA_TYPE_THERMO, CameraDefinition_1_t::DeInterlace, CameraDefinition_1_t::DigitalZoomLimit, FLIR_320_PHOTON_14, FLIR_320_PHOTON_14P, FLIR_320_PHOTON_20, FLIR_320_PHOTON_20P, FLIR_320_PHOTON_23, FLIR_320_PHOTON_36, FLIR_320_PHOTON_50, FLIR_640_PHOTON_15, FLIR_640_PHOTON_26, FLIR_640_PHOTON_DELTA, FLIR_640_PHOTON_DELTA_P, FLIR_640_TAU_10, FLIR_640_TAU_10_P, FLIR_640_TAU_25, FLIR_640_TAU_32, FLIR_640_TAU_DELTA, FLIR_640_TAU_DELTA_P, FLIR_HRC_CZOOM, CameraDefinition_1_t::HorFpaSize, IsLegacyProsilicaCamera(), IsLegacyTypeIndigoCamera(), IsLegacyTypeSonyCamera(), IsLegacyTypeSUCamera(), IsLegacyTypeThermoCamera(), CameraDefinition_1_t::LegacyType, LENS_TYPE_CAMERA_SPECIFIED, LENS_TYPE_CCT_LWIR_DZOOM, LENS_TYPE_CCT_MWIR_CZOOM, LENS_TYPE_CCT_SWIR_CAT, LENS_TYPE_GENERIC_FIXED, CameraDefinition_1_t::LensType, CameraDefinition_1_t::MaxFocalLength, CameraDefinition_1_t::MinFocalLength, CameraDefinition_1_t::OutputFormat, PROSILICA_2450_10, PROSILICA_2450_14, PROSILICA_2450_21, PROSILICA_2450_28, PROSILICA_2450_39, PROSILICA_2450_56, CameraDefinition_1_t::ProtocolType, RoundToUInt16(), SKU_320_KTX_15, SKU_320_KTX_18, SKU_320_KTX_29, SKU_640_KTSTING, SKU_640_KTSX, THERMOTEKNIX_MIRICLE_110_10, THERMOTEKNIX_MIRICLE_110_15, THERMOTEKNIX_MIRICLE_110_24, THERMOTEKNIX_MIRICLE_110_41, THERMOTEKNIX_MIRICLE_307_12, THERMOTEKNIX_MIRICLE_307_18, THERMOTEKNIX_MIRICLE_307_26, THERMOTEKNIX_MIRICLE_307_28, THERMOTEKNIX_MIRICLE_307_48, THERMOTEKNIX_MIRICLE_307_DELTA, THERMOTEKNIX_MIRICLE_307_DELTA_P, CameraDefinition_1_t::VerFpaSize, VIDEO_OUTPUT_CUSTOM, VIDEO_OUTPUT_NTSC, and VIDEO_OUTPUT_PAL.
Referenced by ConvertFromLegacyCameraType().
void ConvertLegacyToNewCameraDef (const CameraDefinition_1_t * pOld, CameraDefinition_t * pNew)
Convert old style camera definitions to the new style camera definitions.
References CameraDefinition_1_t::AutoCameraType, CameraDefinition_t::AutoCameraType, CameraDefinition_1_t::DeInterlace, CameraDefinition_t::DeInterlace, CameraDefinition_1_t::DigitalZoomLimit, CameraDefinition_t::DigitalZoomLimit, CameraDefinition_t::GainBlue, CameraDefinition_t::GainRed, CameraDefinition_1_t::HorFpaSize, CameraDefinition_t::HorFpaSize, CameraDefinition_1_t::Invert, CameraDefinition_t::Invert, CameraDefinition_1_t::InvertHoriz, CameraDefinition_t::InvertHoriz, CameraDefinition_1_t::InvertVert, CameraDefinition_t::InvertVert, CameraDefinition_1_t::LegacyType, CameraDefinition_t::LegacyType, CameraDefinition_1_t::LensType, CameraDefinition_t::LensType, CameraDefinition_1_t::MaxFocalLength, CameraDefinition_t::MaxFocalLength, CameraDefinition_1_t::MinFocalLength, CameraDefinition_t::MinFocalLength, CameraDefinition_1_t::NoFfcShutter, CameraDefinition_t::NoFfcShutter, CameraDefinition_1_t::NoFOVMatch, CameraDefinition_t::NoFOVMatch, CameraDefinition_1_t::OutputFormat, CameraDefinition_t::OutputFormat, CameraDefinition_1_t::ProtocolType, CameraDefinition_t::ProtocolType, CameraDefinition_1_t::Reserved2, CameraDefinition_t::Reserved2, CameraDefinition_1_t::Reserved3, CameraDefinition_t::Reserved3, CameraDefinition_1_t::VerFpaSize, CameraDefinition_t::VerFpaSize, and CameraDefinition_t::WhiteBalance.
Referenced by ConvertFromLegacyCameraType().
UInt8 ConvertToLegacyCamera (const CameraDefinition_t * pCamera)
Convert from a new camera description to the legacy type.
Convert a CameraDefinition_t to an old style enumerated type. If the CameraDefinition_t includes the legacy type then that will be returned, otherwise the type will be guessed using the protocol and lens information.
Parameters
pCamera is the new camera definition information.
Returns
the Legacy enumerated type.
References CAMERA_TYPE_320_KTX, CAMERA_TYPE_640_KTX, CAMERA_TYPE_HRC, CAMERA_TYPE_PHOTON, CAMERA_TYPE_SONY, CAMERA_TYPE_TAU, CAMERA_TYPE_THERMO, FLIR_320_PHOTON_14, FLIR_320_PHOTON_14P, FLIR_320_PHOTON_20, FLIR_320_PHOTON_20P, FLIR_320_PHOTON_23, FLIR_320_PHOTON_36, FLIR_320_PHOTON_50, FLIR_640_PHOTON_15, FLIR_640_PHOTON_26, FLIR_640_PHOTON_DELTA, FLIR_640_PHOTON_DELTA_P, FLIR_640_TAU_10, FLIR_640_TAU_10_P, FLIR_640_TAU_25, FLIR_640_TAU_32, FLIR_640_TAU_DELTA, FLIR_640_TAU_DELTA_P, FLIR_HRC_CZOOM, CameraDefinition_t::HorFpaSize, CameraDefinition_t::LegacyType, LENS_TYPE_CCT_LWIR_DZOOM, LENS_TYPE_CCT_SWIR_CAT, CameraDefinition_t::LensType, CameraDefinition_t::MinFocalLength, CameraDefinition_t::OutputFormat, CameraDefinition_t::ProtocolType, SKU_320_KTX_15, SKU_320_KTX_18, SKU_320_KTX_29, SKU_640_KTSTING, SKU_640_KTSX, SONY_FCB_EX1010, SONY_FCB_EX1010P, SONY_FCB_EX480C, SONY_FCB_EX480CP, SONY_FCB_EX980, SONY_FCB_EX980P, SONY_FCB_H11, SONY_FCB_IX11, SONY_FCB_IX11P, THERMOTEKNIX_MIRICLE_110_10, THERMOTEKNIX_MIRICLE_110_15, THERMOTEKNIX_MIRICLE_110_24, THERMOTEKNIX_MIRICLE_110_41, THERMOTEKNIX_MIRICLE_307_12, THERMOTEKNIX_MIRICLE_307_18, THERMOTEKNIX_MIRICLE_307_26, THERMOTEKNIX_MIRICLE_307_28, THERMOTEKNIX_MIRICLE_307_48, THERMOTEKNIX_MIRICLE_307_DELTA, THERMOTEKNIX_MIRICLE_307_DELTA_P, and VIDEO_OUTPUT_PAL.
const char* GetLegacyCameraStringName (UInt8 LegacyType)
Take the old legacy type and return a string description.
Return a pointer to a constant ASCII string which identifies a legacy camera enumeration.
Parameters
LegacyType is the legacy camera enumeration.
Returns
A constant pointer to the camera string name
References BEMEYERS_NAVAIR, FLIR_320_PHOTON_14, FLIR_320_PHOTON_14P, FLIR_320_PHOTON_20, FLIR_320_PHOTON_20P, FLIR_320_PHOTON_23, FLIR_320_PHOTON_36, FLIR_320_PHOTON_50, FLIR_640_PHOTON_15, FLIR_640_PHOTON_26, FLIR_640_PHOTON_DELTA, FLIR_640_PHOTON_DELTA_P, FLIR_640_TAU_10, FLIR_640_TAU_10_P, FLIR_640_TAU_25, FLIR_640_TAU_32, FLIR_640_TAU_DELTA, FLIR_640_TAU_DELTA_P, FLIR_HRC_CZOOM, PROSILICA_2450_10, PROSILICA_2450_14, PROSILICA_2450_21, PROSILICA_2450_28, PROSILICA_2450_39, PROSILICA_2450_56, SKU_320_KTX_15, SKU_320_KTX_18, SKU_320_KTX_29, SKU_640_KTSTING, SKU_640_KTSX, SONY_FCB_EX1000, SONY_FCB_EX1000P, SONY_FCB_EX1010, SONY_FCB_EX1010P, SONY_FCB_EX1020, SONY_FCB_EX1020P, SONY_FCB_EX45MC, SONY_FCB_EX45MCC, SONY_FCB_EX480B, SONY_FCB_EX480BP, SONY_FCB_EX480C, SONY_FCB_EX480CP, SONY_FCB_EX48B, SONY_FCB_EX48BP, SONY_FCB_EX980, SONY_FCB_EX980P, SONY_FCB_EX980S, SONY_FCB_EX980SP, SONY_FCB_H10, SONY_FCB_H11, SONY_FCB_IX11, SONY_FCB_IX11P, THERMOTEKNIX_MIRICLE_110_10, THERMOTEKNIX_MIRICLE_110_15, THERMOTEKNIX_MIRICLE_110_24, THERMOTEKNIX_MIRICLE_110_41, THERMOTEKNIX_MIRICLE_307_12, THERMOTEKNIX_MIRICLE_307_18, THERMOTEKNIX_MIRICLE_307_26, THERMOTEKNIX_MIRICLE_307_28, THERMOTEKNIX_MIRICLE_307_48, THERMOTEKNIX_MIRICLE_307_DELTA, and THERMOTEKNIX_MIRICLE_307_DELTA_P.
BOOL IsLegacyProsilicaCamera (UInt8 LegacyType)
Return true if the passed legacy camera type is a prosilica camera.
Return true if the passed legacy camera type is a prosilica camera.
Parameters
LegacyType is the legacy camera type to evaluate.
Returns
TRUE if this type is a prosilica camera.
References PROSILICA_2450_10, PROSILICA_2450_14, PROSILICA_2450_21, PROSILICA_2450_28, PROSILICA_2450_39, and PROSILICA_2450_56.
Referenced by ConvertFromLegacyTypeToLegacyCameraDef().
BOOL IsLegacyTypeIndigoCamera (UInt8 LegacyType)
Return true if the passed legacy camera type is a FLIR/Indigo camera.
Return true if the passed legacy camera type is a FLIR/Indigo camera. A Tau camera counts as an indigo camera
Parameters
LegacyType is the camera type to evaluate.
Returns
TRUE if this type is a FLIR/Indigo.
References FLIR_320_PHOTON_14, FLIR_320_PHOTON_14P, FLIR_320_PHOTON_20, FLIR_320_PHOTON_20P, FLIR_320_PHOTON_23, FLIR_320_PHOTON_36, FLIR_320_PHOTON_50, FLIR_640_PHOTON_15, FLIR_640_PHOTON_26, FLIR_640_PHOTON_DELTA, FLIR_640_PHOTON_DELTA_P, FLIR_HRC_CZOOM, and IsLegacyTypeTauCamera().
Referenced by ConvertFromLegacyTypeToLegacyCameraDef().
BOOL IsLegacyTypeSonyCamera (UInt8 LegacyType)
Return true if the passed legacy camera type is a sony camera.
Return true if the passed legacy camera type is a sony camera.
Parameters
LegacyType is the camera type to evaluate.
Returns
TRUE if this type is a sony camera (VISCA controlled).
References BEMEYERS_NAVAIR, FLIR_320_PHOTON_14P, FLIR_320_PHOTON_20P, FLIR_640_PHOTON_DELTA_P, FLIR_640_TAU_10_P, FLIR_640_TAU_DELTA_P, SONY_FCB_EX1000, SONY_FCB_EX1000P, SONY_FCB_EX1010, SONY_FCB_EX1010P, SONY_FCB_EX1020, SONY_FCB_EX1020P, SONY_FCB_EX45MC, SONY_FCB_EX45MCC, SONY_FCB_EX480B, SONY_FCB_EX480BP, SONY_FCB_EX480C, SONY_FCB_EX480CP, SONY_FCB_EX48B, SONY_FCB_EX48BP, SONY_FCB_EX980, SONY_FCB_EX980P, SONY_FCB_EX980S, SONY_FCB_EX980SP, SONY_FCB_H10, SONY_FCB_H11, SONY_FCB_IX11, SONY_FCB_IX11P, and THERMOTEKNIX_MIRICLE_307_DELTA_P.
Referenced by ConvertFromLegacyTypeToLegacyCameraDef().
BOOL IsLegacyTypeSUCamera (UInt8 LegacyType)
Return TRUE if the passed legacy camera type is a goodrich SU camera.
Return TRUE if the passed legacy camera type is a goodrich SU camera
Parameters
LegacyType is the legacy camera type to evaluate.
Returns
TRUE if this type is a SU godrich.
References SKU_320_KTX_15, SKU_320_KTX_18, SKU_320_KTX_29, SKU_640_KTSTING, and SKU_640_KTSX.
Referenced by ConvertFromLegacyTypeToLegacyCameraDef().
BOOL IsLegacyTypeTauCamera (UInt8 LegacyType)
Return true if the passed legacy camera type is FLIR Tau camera.
Return true if the passed legacy camera type is a FLIR Tau camera.
Parameters
LegacyType is the camera type to evaluate.
Returns
TRUE if this type is a FLIR/Indigo.
References FLIR_320_PHOTON_14, FLIR_320_PHOTON_14P, FLIR_320_PHOTON_20, FLIR_320_PHOTON_20P, FLIR_320_PHOTON_23, FLIR_320_PHOTON_36, FLIR_320_PHOTON_50, FLIR_640_PHOTON_15, FLIR_640_PHOTON_26, FLIR_640_PHOTON_DELTA, FLIR_640_PHOTON_DELTA_P, FLIR_640_TAU_10, FLIR_640_TAU_10_P, FLIR_640_TAU_25, FLIR_640_TAU_32, FLIR_640_TAU_DELTA, FLIR_640_TAU_DELTA_P, and FLIR_HRC_CZOOM.
Referenced by IsLegacyTypeIndigoCamera().
BOOL IsLegacyTypeThermoCamera (UInt8 LegacyType)
Return true if the passed legacy camera type is a Thermoteknix camera.
Return true if the passed legacy camera type is a Thermoteknix camera.
Parameters
LegacyType is the legacy camera type to evaluate.
Returns
TRUE if this type is a Thermoteknix.
References THERMOTEKNIX_MIRICLE_110_10, THERMOTEKNIX_MIRICLE_110_15, THERMOTEKNIX_MIRICLE_110_24, THERMOTEKNIX_MIRICLE_110_41, THERMOTEKNIX_MIRICLE_307_12, THERMOTEKNIX_MIRICLE_307_18, THERMOTEKNIX_MIRICLE_307_26, THERMOTEKNIX_MIRICLE_307_28, THERMOTEKNIX_MIRICLE_307_48, THERMOTEKNIX_MIRICLE_307_DELTA, and THERMOTEKNIX_MIRICLE_307_DELTA_P.
Referenced by ConvertFromLegacyTypeToLegacyCameraDef().