Communications SDK: MathUtil.h File Reference
MathUtil.h File Reference
Math utilities used in the robotics development kit.
#include "Types.h"
#include "Indices.h"
Macros
#define SQR(x) ((x)*(x))
#define CUB(x) ((x)*(x)*(x))
#define max(a, b) (((a)>(b))?(a):(b))
#define min(a, b) (((a)<(b))?(a):(b))
Functions
double sqr (double x)
double cub (double x)
double sign (double x)
float signf (float x)
double minimum (double x1, double x2)
double maximum (double x1, double x2)
float minimumf (float x1, float x2)
float maximumf (float x1, float x2)
float MedianOfTriple (const float Value[3])
return the middle of three numbers in an array
float MedianOfTripleEx (float Value0, float Value1, float Value2)
return the middle of three numbers
double lim (double x, double xmin, double xmax)
float limf (float x, float xmin, float xmax)
int limi (int x, int xmin, int xmax)
double SubtractAngles (double First, double Second)
float SubtractAnglesf (float First, float Second)
double AddAngles (double First, double Second)
float AddAnglesf (float First, float Second)
double LimitAngle (double Angle)
float LimitAnglef (float Angle)
double LimitAngleEx (double Angle, double Wrap)
float LimitAngleExf (float Angle, float Wrap)
double VectorLength3D (const double Vector[N3D])
double VectorLengthSquared3D (const double Vector[N3D])
double DotProduct3D (const double Vector1[N3D], const double Vector2[N3D])
void CrossProduct3D (const double Vector1[N3D], const double Vector2[N3D], double Result[N3D])
void SubtractVectors3D (const double Vector1[N3D], const double Vector2[N3D], double Result[N3D])
void AddVectors3D (const double Vector1[N3D], const double Vector2[N3D], double Result[N3D])
void MultiplyVectorByScaler3D (double Scaler, const double Vector[N3D], double Result[N3D])
double UnitVector3D (double Vector[N3D])
double ChangeVectorSize3D (double Size, double Vector[N3D])
double CosInteriorAngle3D (const double Vector1[N3D], const double Vector2[N3D])
double InteriorAngle3D (const double Vector1[N3D], const double Vector2[N3D])
double VectorLength2D (const double Vector[2])
double VectorLengthSquared2D (const double Vector[2])
double DotProduct2D (const double Vector1[2], const double Vector2[2])
void SubtractVectors2D (const double Vector1[2], const double Vector2[2], double Result[2])
void AddVectors2D (const double Vector1[2], const double Vector2[2], double Result[2])
void MultiplyVectorByScaler2D (double Scaler, const double Vector[2], double Result[2])
double UnitVector2D (double Vector[2])
double ChangeVectorSize2D (double Size, double Vector[2])
double InteriorAngle2D (const double Vector1[2], const double Vector2[2])
float VectorLength3Df (const float Vector[N3D])
float VectorLengthSquared3Df (const float Vector[N3D])
float DotProduct3Df (const float Vector1[N3D], const float Vector2[N3D])
void CrossProduct3Df (const float Vector1[N3D], const float Vector2[N3D], float Result[N3D])
void SubtractVectors3Df (const float Vector1[N3D], const float Vector2[N3D], float Result[N3D])
void AddVectors3Df (const float Vector1[N3D], const float Vector2[N3D], float Result[N3D])
void MultiplyVectorByScaler3Df (float Scaler, const float Vector[N3D], float Result[N3D])
float UnitVector3Df (float Vector[N3D])
float ChangeVectorSize3Df (float Size, float Vector[N3D])
float CosInteriorAngle3Df (const float Vector1[N3D], const float Vector2[N3D])
float InteriorAngle3Df (const float Vector1[N3D], const float Vector2[N3D])
float VectorLength2Df (const float Vector[2])
float VectorLengthSquared2Df (const float Vector[2])
float DotProduct2Df (const float Vector1[2], const float Vector2[2])
void SubtractVectors2Df (const float Vector1[2], const float Vector2[2], float Result[2])
void AddVectors2Df (const float Vector1[2], const float Vector2[2], float Result[2])
void MultiplyVectorByScaler2Df (float Scaler, const float Vector[2], float Result[2])
float UnitVector2Df (float Vector[2])
float ChangeVectorSize2Df (float Size, float Vector[2])
float InteriorAngle2Df (const float Vector1[2], const float Vector2[2])
double LookUpValue (double Ind, const double IndependentAxis[], const double DependentAxis[], int NumPoints)
float LookUpValuef (float Ind, const float IndependentAxis[], const float DependentAxis[], int NumPoints)
double Interpolate (double Ind, double IndHigh, double IndLow, double DepHigh, double DepLow)
float Interpolatef (float Ind, float IndHigh, float IndLow, float DepHigh, float DepLow)
SInt16 InterpolateSInt16 (SInt16 Ind, SInt16 IndHigh, SInt16 IndLow, SInt16 DepHigh, SInt16 DepLow)
int BinarySearch (double key, const double Array[], int n)
int BinarySearchIncreasing (double key, const double Array[], int n)
int BinarySearchDecreasing (double key, const double Array[], int n)
int BinarySearchf (float key, const float Array[], int n)
int BinarySearchIncreasingf (float key, const float Array[], int n)
int BinarySearchDecreasingf (float key, const float Array[], int n)
int BinarySearchUInt16 (UInt16 key, const UInt16 Array[], int n)
int BinarySearchIncreasingUInt16 (UInt16 key, const UInt16 Array[], int n)
int BinarySearchDecreasingUInt16 (UInt16 key, const UInt16 Array[], int n)
Search through an array of 16-bit numbers to find the index of the key.
int StringToSInt32Base10 (const char *pString, int MaxCount, SInt32 *pValue)
Convert a string of ASCII decimal digits to a 32-bit signed integer.
int StringToDoubleBase10 (const char *pString, int MaxCount, double *pValue)
Convert a string of ASCII decimal digits to a 64-bit double.
int StringToFloatBase10 (const char *pString, int MaxCount, float *pValue)
Convert a string of ASCII decimal digits to a 32-bit float.
int StringToUInt32Base16 (const char *pString, int MaxCount, UInt32 *pValue)
Convert a string of ASCII hex digits to a 32-bit integer.
UInt8 ASCIItoHex1 (char UpperNibble, char LowerNibble)
Return an 8-bit value containing the value indicated by the two passed ASCII hex digits.
UInt8 NibbleValue (char Nibble)
Convert an ASCII character interpreted as a hex nibble to the correct value in memory.
BOOL LimitVector2D (double *pX, double *pY, double Limit)
Limit the magnitude of a 2-D vector while preserving its direction.
BOOL LimitVector2Df (float *pX, float *pY, float Limit)
Limit the magnitude of a 2-D vector while preserving its direction. Single precision implementation.
Detailed Description
Math utilities used in the robotics development kit.
Function Documentation
double AddAngles (double First, double Second)
Add two angles to return a result. The input angles are assumed to wrap in a single circle (2PI). The output angle will range from -PI to +PI radians, and will account for circle wrappoint.
Parameters
First is the first input angle in radians.
Second is the second input angle in radians.
Returns
First+Second, accounting for circle wrap
References LimitAngle().
float AddAnglesf (float First, float Second)
Add two angles to return a result. The input angles are assumed to wrap in a single circle (2PI). The output angle will range from -PI to +PI radians, and will account for circle wrappoint.
Parameters
First is the first input angle in radians.
Second is the second input angle in radians.
Returns
First+Second, accounting for circle wrap
References LimitAnglef().
void AddVectors2D (const double Vector1[2], const double Vector2[2], double Result[2])
Calculate the sum of two two-dimensional vectors
Parameters
Vector1 points to a 2-D vector array.
Vector2 points to a 2-D vector array.
Result points to space to receive the cross product.
References X_AXIS, and Y_AXIS.
void AddVectors2Df (const float Vector1[2], const float Vector2[2], float Result[2])
Calculate the sum of two two-dimensional vectors
Parameters
Vector1 points to a 2-D vector array.
Vector2 points to a 2-D vector array.
Result points to space to receive the cross product.
References X_AXIS, and Y_AXIS.
void AddVectors3D (const double Vector1[N3D], const double Vector2[N3D], double Result[N3D])
Calculate the sum of two three-dimensional vectors
Parameters
Vector1 points to a 3-D vector array.
Vector2 points to a 3-D vector array.
Result points to space to receive the vector product.
References X_AXIS, Y_AXIS, and Z_AXIS.
void AddVectors3Df (const float Vector1[N3D], const float Vector2[N3D], float Result[N3D])
Calculate the sum of two three-dimensional vectors
Parameters
Vector1 points to a 3-D vector array.
Vector2 points to a 3-D vector array.
Result points to space to receive the cross product.
References X_AXIS, Y_AXIS, and Z_AXIS.
UInt8 ASCIItoHex1 (char UpperNibble, char LowerNibble)
Return an 8-bit value containing the value indicated by the two passed ASCII hex digits.
Return an 8-bit value containing the value indicated by the two passed ASCII hex digits.
Parameters
UpperNibble is the most significant ASCII hex digit.
LowerNibble is the least significant ASCII hex digit.
References NibbleValue().
int BinarySearch (double key, const double Array[], int n)
Search an array which contains increasing or decreasing values to find the index of an element. If the array is increasing find the index of the element which is less than or equal to the key value. If the array is decreasing find the index of the element which is more than the key value.
Parameters
key is the value to search for
n is the size of the array
Array is the array to search.
Returns
The index of the element which is less than or equal to the key. if the returned value is -1 than key is below the array. If the returned value is n-1 the key is above the array.
References BinarySearchDecreasing(), and BinarySearchIncreasing().
Referenced by LookUpValue().
int BinarySearchDecreasing (double key, const double Array[], int n)
Search an array which contains decreasing values, finding the index of the element which is more than the key value.
Parameters
key is the value to search for
n is the size of the array
Array is the array to search.
Returns
The index of the element which is more than or equal to the key. if the returned value is -1 than key is lower than the lowest value in the array. If the returned value is n-1 then key is higher than or equal to the highest value in the array.
Referenced by BinarySearch().
int BinarySearchDecreasingf (float key, const float Array[], int n)
Search an array which contains decreasing values, finding the index of the element which is more than the key value.
Parameters
key is the value to search for
n is the size of the array
Array is the array to search.
Returns
The index of the element which is more than or equal to the key. if the returned value is -1 than key is lower than the lowest value in the array. If the returned value is n-1 then key is higher than or equal to the highest value in the array.
Referenced by BinarySearchf().
int BinarySearchDecreasingUInt16 (UInt16 key, const UInt16 Array[], int n)
Search through an array of 16-bit numbers to find the index of the key.
Search an array which contains decreasing values, finding the index of the element which is more than the key value.
Parameters
key is the value to search for
n is the size of the array
Array is the array to search.
Returns
The index of the element which is more than or equal to the key. if the returned value is -1 than key is lower than the lowest value in the array. If the returned value is n-1 then key is higher than or equal to the highest value in the array.
Referenced by BinarySearchUInt16().
int BinarySearchf (float key, const float Array[], int n)
Search an array which contains increasing or decreasing values to find the index of an element. If the array is increasing find the index of the element which is less than or equal to the key value. If the array is decreasing find the index of the element which is more than the key value.
Parameters
key is the value to search for
n is the size of the array
Array is the array to search.
Returns
The index of the element which is less than or equal to the key. if the returned value is -1 than key is below the array. If the returned value is n-1 the key is above the array.
References BinarySearchDecreasingf(), and BinarySearchIncreasingf().
Referenced by LookUpValuef().
int BinarySearchIncreasing (double key, const double Array[], int n)
Search an array which contains increasing values, finding the index of the element which is less than or equal to the key value.
Parameters
key is the value to search for
n is the size of the array
Array is the array to search.
Returns
The index of the element which is less than or equal to the key. if the returned value is -1 than key is lower than the lowest value in the array. If the returned value is n-1 then key is higher than or equal to the highest value in the array.
Referenced by BinarySearch().
int BinarySearchIncreasingf (float key, const float Array[], int n)
Search an array which contains increasing values, finding the index of the element which is less than or equal to the key value.
Parameters
key is the value to search for
n is the size of the array
Array is the array to search.
Returns
The index of the element which is less than or equal to the key. if the returned value is -1 than key is lower than the lowest value in the array. If the returned value is n-1 then key is higher than or equal to the highest value in the array.
Referenced by BinarySearchf().
int BinarySearchIncreasingUInt16 (UInt16 key, const UInt16 Array[], int n)
Search an array which contains increasing values, finding the index of the element which is less than or equal to the key value.
Parameters
key is the value to search for
n is the size of the array
Array is the array to search.
Returns
The index of the element which is less than or equal to the key. if the returned value is -1 than key is lower than the lowest value in the array. If the returned value is n-1 then key is higher than or equal to the highest value in the array.
Referenced by BinarySearchUInt16().
int BinarySearchUInt16 (UInt16 key, const UInt16 Array[], int n)
Search an array which contains increasing or decreasing values to find the index of an element. If the array is increasing find the index of the element which is less than or equal to the key value. If the array is decreasing find the index of the element which is more than the key value.
Parameters
key is the value to search for
n is the size of the array
Array is the array to search.
Returns
The index of the element which is less than or equal to the key. if the returned value is -1 than key is below the array. If the returned value is n-1 the key is above the array.
References BinarySearchDecreasingUInt16(), and BinarySearchIncreasingUInt16().
double ChangeVectorSize2D (double Size, double Vector[2])
Change the passed vector to be the size requested
Parameters
Size is the desired size of the vector
Vector points to a 2-D vector array.
Returns
The previous vector length.
References MultiplyVectorByScaler2D(), and VectorLength2D().
Referenced by UnitVector2D().
float ChangeVectorSize2Df (float Size, float Vector[2])
Change the passed vector to be the size requested
Parameters
Size is the desired size of the vector
Vector points to a 2-D vector array.
Returns
The previous vector length.
References MultiplyVectorByScaler2Df(), and VectorLength2Df().
Referenced by UnitVector2Df().
double ChangeVectorSize3D (double Size, double Vector[N3D])
Change the passed vector to be the size requested
Parameters
Size is the desired size of the vector
Vector points to a 3-D vector array.
Returns
The previous vector length.
References MultiplyVectorByScaler3D(), and VectorLength3D().
Referenced by UnitVector3D().
float ChangeVectorSize3Df (float Size, float Vector[N3D])
Change the passed vector to be the size requested
Parameters
Size is the desired size of the vector
Vector points to a 3-D vector array.
Returns
The previous vector length.
References MultiplyVectorByScaler3Df(), and VectorLength3Df().
Referenced by UnitVector3Df().
double CosInteriorAngle3D (const double Vector1[N3D], const double Vector2[N3D])
Calculate the cosine of the interior angle of two three-dimensional vectors
Parameters
Vector1 points to a 3-D vector array
Vector2 points to a 3-D vector array
Returns
The cosine of the interior angle of the two vectors.
References DotProduct3D(), lim(), and VectorLength3D().
Referenced by InteriorAngle3D().
float CosInteriorAngle3Df (const float Vector1[N3D], const float Vector2[N3D])
Calculate the cosine of the interior angle of two three-dimensional vectors
Parameters
Vector1 points to a 3-D vector array
Vector2 points to a 3-D vector array
Returns
The cosine of the interior angle of the two vectors.
References DotProduct3Df(), limf(), and VectorLength3Df().
Referenced by InteriorAngle3Df().
void CrossProduct3D (const double Vector1[N3D], const double Vector2[N3D], double Result[N3D])
Calculate the cross poduct of two three-dimensional vectors
Parameters
Vector1 points to a 3-D vector array.
Vector2 points to a 3-D vector array.
Result points to space to receive the cross product.
References X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by GetCurveTriad(), GetNavToBodyMatFromVec(), TrackCoordinateParametersECEF3D(), and TrackRelativeVectors().
void CrossProduct3Df (const float Vector1[N3D], const float Vector2[N3D], float Result[N3D])
Calculate the cross poduct of two three-dimensional vectors
Parameters
Vector1 points to a 3-D vector array.
Vector2 points to a 3-D vector array.
Result points to space to receive the cross product.
References X_AXIS, Y_AXIS, and Z_AXIS.
double cub (double x)
Cube a passed double precision number
Parameters
x is the number to cube.
Returns
x*x*x.
double DotProduct2D (const double Vector1[2], const double Vector2[2])
Calculate the dot poduct of two two-dimensional vectors
Parameters
Vector1 points to a 2-D vector array
Vector2 points to a 2-D vector array
Returns
The dot product of the two vectors.
Referenced by InteriorAngle2D().
float DotProduct2Df (const float Vector1[2], const float Vector2[2])
Calculate the dot poduct of two two-dimensional vectors
Parameters
Vector1 points to a 2-D vector array
Vector2 points to a 2-D vector array
Returns
The dot product of the two vectors.
Referenced by InteriorAngle2Df().
double DotProduct3D (const double Vector1[N3D], const double Vector2[N3D])
Calculate the dot poduct of two three-dimensional vectors
Parameters
Vector1 points to a 3-D vector array
Vector2 points to a 3-D vector array
Returns
The dot product of the two vectors.
References X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by CosInteriorAngle3D(), DistanceBetweenECEFCircle(), GetNavToBodyMatFromVec(), MaxErrorInterpolateBsplineCurve(), MinDistanceToBsplineCurve(), TrackCoordinateParametersECEF3D(), TrackCoordinatePositionECEFEx(), and TrackCoordinateVelocityECEFEx().
float DotProduct3Df (const float Vector1[N3D], const float Vector2[N3D])
Calculate the dot poduct of two three-dimensional vectors
Parameters
Vector1 points to a 3-D vector array
Vector2 points to a 3-D vector array
Returns
The dot product of the two vectors.
References X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by CosInteriorAngle3Df().
double InteriorAngle2D (const double Vector1[2], const double Vector2[2])
Calculate the interior angle of two two-dimensional vectors
Parameters
Vector1 points to a 2-D vector array
Vector2 points to a 2-D vector array
Returns
The interior angle of the two vectors.
References DotProduct2D(), lim(), and VectorLength2D().
float InteriorAngle2Df (const float Vector1[2], const float Vector2[2])
Calculate the interior angle of two two-dimensional vectors
Parameters
Vector1 points to a 2-D vector array
Vector2 points to a 2-D vector array
Returns
The interior angle of the two vectors.
References DotProduct2Df(), limf(), and VectorLength2Df().
double InteriorAngle3D (const double Vector1[N3D], const double Vector2[N3D])
Calculate the interior angle of two three-dimensional vectors
Parameters
Vector1 points to a 3-D vector array
Vector2 points to a 3-D vector array
Returns
The interior angle of the two vectors.
References CosInteriorAngle3D().
float InteriorAngle3Df (const float Vector1[N3D], const float Vector2[N3D])
Calculate the interior angle of two three-dimensional vectors
Parameters
Vector1 points to a 3-D vector array
Vector2 points to a 3-D vector array
Returns
The interior angle of the two vectors.
References CosInteriorAngle3Df().
double Interpolate (double Ind, double IndHigh, double IndLow, double DepHigh, double DepLow)
Perform linear interpolation between two points.
Parameters
Ind is the independent variable.
IndHigh is the high side value of the independent axis.
IndLow is the low side value of the independent axis.
DepHigh is the high side value of the dependent axis.
DepLow is the low side value of the dependent axis.
Returns
The interplated dependent axis value that corresponds to the independent vairable.
Referenced by LookUpValue().
float Interpolatef (float Ind, float IndHigh, float IndLow, float DepHigh, float DepLow)
Perform linear interpolation between two points.
Parameters
Ind is the independent variable.
IndHigh is the high side value of the independent axis.
IndLow is the low side value of the independent axis.
DepHigh is the high side value of the dependent axis.
DepLow is the low side value of the dependent axis.
Returns
The interplated dependent axis value that corresponds to the independent vairable.
Referenced by LookUpValuef().
SInt16 InterpolateSInt16 (SInt16 Ind, SInt16 IndHigh, SInt16 IndLow, SInt16 DepHigh, SInt16 DepLow)
Perform linear interpolation between two points.
Parameters
Ind is the independent variable.
IndHigh is the high side value of the independent axis.
IndLow is the low side value of the independent axis.
DepHigh is the high side value of the dependent axis.
DepLow is the low side value of the dependent axis.
Returns
The interplated dependent axis value that corresponds to the independent vairable.
double lim (double x, double xmin, double xmax)
Bounds the number x to the interval [xmin, xmax].
Parameters
x is the variable to be bounded
xmin is the lower bound.
xmax is the upper bound.
Returns
The limited value
Referenced by CosInteriorAngle3D(), DistanceBetweenECEFCircle(), and InteriorAngle2D().
float limf (float x, float xmin, float xmax)
Bounds the number x to the interval [xmin, xmax].
Parameters
x is the variable to be bounded
xmin is the lower bound.
xmax is the upper bound.
Returns
The limited value
Referenced by CosInteriorAngle3Df(), and InteriorAngle2Df().
int limi (int x, int xmin, int xmax)
Bounds the number x to the interval [xmin, xmax].
Parameters
x is the variable to be bounded
xmin is the lower bound.
xmax is the upper bound.
Returns
The limited value
double LimitAngle (double Angle)
Limit an angle to the range +/- PI. It is assumed that the passed angle is no more than one revolution away from this range.
Parameters
Angle is the angle to limit.
Returns
the Limited angle.
Referenced by AddAngles(), and SubtractAngles().
double LimitAngleEx (double Angle, double Wrap)
Limit an angle to account for going past the wrap point. The wrap point is the location where the full circle output switches, for example the wrap point could be 180, 360, 90, etc. Note! the wrap angle must be specified as a positive angle (from 0 to 360). It is assumed that the passed angle is no more than one revolution away from the correct location
Parameters
Angle is the angle to limit in radians.
Wrap is the wrap angle in radians (from 0 to 2PI).
Returns
the Limited angle in radians
float LimitAngleExf (float Angle, float Wrap)
Limit an angle to account for going past the wrap point. The wrap point is the location where the full circle output switches, for example the wrap point could be 180, 360, 90, etc. Note! the wrap angle must be specified as a positive angle (from 0 to 360). It is assumed that the passed angle is no more than one revolution away from the correct location
Parameters
Angle is the angle to limit in radians.
Wrap is the wrap angle in radians (from 0 to 2PI).
Returns
the Limited angle in radians
float LimitAnglef (float Angle)
Limit an angle to the range +/- PI. It is assumed that the passed angle is no more than one revolution away from this range.
Parameters
Angle is the angle to limit.
Returns
the Limited angle.
Referenced by AddAnglesf(), and SubtractAnglesf().
BOOL LimitVector2D (double * pX, double * pY, double Limit)
Limit the magnitude of a 2-D vector while preserving its direction.
Limit the magnitude of a 2-D vector while preserving its direction.
Parameters
pX is the vector X-axis value.
pY is the vector Y-axis value.
Limit is the vector magnitude limit.
Returns
TRUE if the vector magnitude was limited
BOOL LimitVector2Df (float * pX, float * pY, float Limit)
Limit the magnitude of a 2-D vector while preserving its direction. Single precision implementation.
Limit the magnitude of a 2-D vector while preserving its direction.
Parameters
pX is the vector X-axis value.
pY is the vector Y-axis value.
Limit is the vector magnitude limit.
Returns
TRUE if the vector magnitude was limited
double LookUpValue (double Ind, const double IndependentAxis[], const double DependentAxis[], int NumPoints)
Perform table look up using linear interpolation. The independent axis must be monotonically increasing or decreasing. If the independent variable is outside the range of the table then the appropriate extreme value is returned.
Parameters
Ind is the independent variable.
IndependentAxis is the independent axis of the look up table.
DependentAxis is the dependent axis of the look up table.
NumPoints is the number of points in the table.
Returns
The dependent variable which corresponds to Ind.
References BinarySearch(), and Interpolate().
float LookUpValuef (float Ind, const float IndependentAxis[], const float DependentAxis[], int NumPoints)
Perform table look up using linear interpolation. The independent axis must be monotonically increasing or decreasing. If the independent variable is outside the range of the table then the appropriate extreme value is returned.
Parameters
Ind is the independent variable.
IndependentAxis is the independent axis of the look up table.
DependentAxis is the dependent axis of the look up table.
NumPoints is the number of points in the table.
Returns
The dependent variable which corresponds to Ind.
References BinarySearchf(), and Interpolatef().
double maximum (double x1, double x2)
Return the larger of x1 or x2.
Parameters
x1 is first value to compare.
x2 is the second value to compare.
Returns
the larger of x1 or x2.
Referenced by MatrixNormInf().
float maximumf (float x1, float x2)
Return the larger of x1 or x2.
Parameters
x1 is first value to compare.
x2 is the second value to compare.
Returns
the larger of x1 or x2.
float MedianOfTriple (const float Value[3])
return the middle of three numbers in an array
Return the middle of three numbers, defined as the number whose value is between the other two.
Parameters
Value is an array of three numbers to sort through.
Returns
The median value
References MedianOfTripleEx().
float MedianOfTripleEx (float Value0, float Value1, float Value2)
return the middle of three numbers
Return the middle of three numbers, defined as the number whose value is between the other two.
Parameters
Value0 is the first of three numbers to sort through.
Value1 is the second of three numbers to sort through.
Value2 is the third of three numbers to sort through.
Returns
The median value
Referenced by MedianOfTriple().
double minimum (double x1, double x2)
Return the smaller of x1 or x2.
Parameters
x1 is first value to compare.
x2 is the second value to compare.
Returns
the smaller of x1 or x2.
float minimumf (float x1, float x2)
Return the smaller of x1 or x2.
Parameters
x1 is first value to compare.
x2 is the second value to compare.
Returns
the smaller of x1 or x2.
void MultiplyVectorByScaler2D (double Scaler, const double Vector[2], double Result[2])
Calculate the result of a vector multiplied by a scaler
Parameters
Scaler is the scale factor to apply to the vector
Vector points to a 2-D vector array to be multiplied.
Result points to space to receive the result.
References X_AXIS, and Y_AXIS.
Referenced by ChangeVectorSize2D().
void MultiplyVectorByScaler2Df (float Scaler, const float Vector[2], float Result[2])
Calculate the result of a vector multiplied by a scaler
Parameters
Scaler is the scale factor to apply to the vector
Vector points to a 2-D vector array to be multiplied.
Result points to space to receive the result.
References X_AXIS, and Y_AXIS.
Referenced by ChangeVectorSize2Df().
void MultiplyVectorByScaler3D (double Scaler, const double Vector[N3D], double Result[N3D])
Calculate the result of a vector multiplied by a scaler
Parameters
Scaler is the scale factor to apply to the vector
Vector points to a 3-D vector array to be multiplied.
Result points to space to receive the result.
References X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by ChangeVectorSize3D(), and GetNavToBodyMatFromVec().
void MultiplyVectorByScaler3Df (float Scaler, const float Vector[N3D], float Result[N3D])
Calculate the result of a vector multiplied by a scaler
Parameters
Scaler is the scale factor to apply to the vector
Vector points to a 3-D vector array to be multiplied.
Result points to space to receive the result.
References X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by ChangeVectorSize3Df().
UInt8 NibbleValue (char Nibble)
Convert an ASCII character interpreted as a hex nibble to the correct value in memory.
Convert an ASCII character interpreted as a hex nibble to the correct value in memory.
Parameters
Nibble is the ASCII character.
Returns
the hex value in memory.
Referenced by ASCIItoHex1(), and StringToUInt32Base16().
double sign (double x)
Sign of a double precision number
Parameters
x is the number
Returns
-1, or 1
Referenced by CholUpdate(), MatrixGetUpperTriangular(), and srotg().
float signf (float x)
Sign of a single precision number
Parameters
x is the number
Returns
-1, or 1
double sqr (double x)
Square a passed double precision number
Parameters
x is the number to square.
Returns
x*x.
Referenced by schdd().
int StringToDoubleBase10 (const char * pString, int MaxCount, double * pValue)
Convert a string of ASCII decimal digits to a 64-bit double.
Convert a string to a double precision number, assuming the string is ASCII and represents a number expressed in base 10. The string may be null terminated or terminated by MaxCount.
Parameters
pString is the string to convert.
MaxCount is the maximum number of characters to examine.
pValue receives the result.
Returns
The number of characters consumed from the string to produce the result. 0 if no number was found before string termination.
Referenced by StringToFloatBase10().
int StringToFloatBase10 (const char * pString, int MaxCount, float * pValue)
Convert a string of ASCII decimal digits to a 32-bit float.
Convert a string to a single precision number, assuming the string is ASCII and represents a number expressed in base 10. The string may be null terminated or terminated by MaxCount.
Parameters
pString is the string to convert.
MaxCount is the maximum number of characters to examine.
pValue receives the result.
Returns
The number of characters consumed from the string to produce the result. 0 if no number was found before string termination.
References StringToDoubleBase10().
int StringToSInt32Base10 (const char * pString, int MaxCount, SInt32 * pValue)
Convert a string of ASCII decimal digits to a 32-bit signed integer.
Convert a string to a 32-bit signed integer, assuming the string is ASCII and represents a number expressed in base 10. The string may be null terminated or terminated by MaxCount.
Parameters
pString is the string to convert.
MaxCount is the maximum number of characters to examine.
pValue receives the result.
Returns
The number of characters consumed from the string to produce the result. 0 if no number was found before string termination.
int StringToUInt32Base16 (const char * pString, int MaxCount, UInt32 * pValue)
Convert a string of ASCII hex digits to a 32-bit integer.
Convert a string of ASCII hex digits to a 32-bit integer. The string may be null terminated or terminated by MaxCount. The string may not have any non-numeric characters.
Parameters
pString is the string to convert.
MaxCount is the maximum number of characters to examine.
pValue receives the result.
Returns
The number of characters consumed from the string to produce the result. 0 if no number was found before string termination.
References NibbleValue().
double SubtractAngles (double First, double Second)
Subtract two angles to return a result. The input angles are assumed to wrap in a single circle (2PI). The output angle will range from -PI to +PI radians, and will account for circle wrappoint.
Parameters
First is the first input angle in radians.
Second is the second input angle in radians.
Returns
First-Second, accounting for circle wrap
References LimitAngle().
Referenced by GetXMLEuler(), and QuatErrLim().
float SubtractAnglesf (float First, float Second)
Subtract two angles to return a result. The input angles are assumed to wrap in a single circle (2PI). The output angle will range from -PI to +PI radians, and will account for circle wrappoint.
Parameters
First is the first input angle in radians.
Second is the second input angle in radians.
Returns
First-Second, accounting for circle wrap
References LimitAnglef().
Referenced by QuatErrLimf().
void SubtractVectors2D (const double Vector1[2], const double Vector2[2], double Result[2])
Calculate the difference between two two-dimensional vectors
Parameters
Vector1 points to a 2-D vector array.
Vector2 points to a 2-D vector array.
Result points to space to receive the cross product.
References X_AXIS, and Y_AXIS.
void SubtractVectors2Df (const float Vector1[2], const float Vector2[2], float Result[2])
Calculate the difference between two two-dimensional vectors
Parameters
Vector1 points to a 2-D vector array.
Vector2 points to a 2-D vector array.
Result points to space to receive the cross product.
References X_AXIS, and Y_AXIS.
void SubtractVectors3D (const double Vector1[N3D], const double Vector2[N3D], double Result[N3D])
Calculate the difference between two three-dimensional vectors
Parameters
Vector1 points to a 3-D vector array.
Vector2 points to a 3-D vector array.
Result points to space to receive the vector difference (vector1 - vector2).
References X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by DistanceBetweenECEF(), MaxErrorInterpolateBsplineCurve(), MinDistanceToBsplineCurve(), TrackCoordinateParametersECEF3D(), TrackCoordinatePositionECEFEx(), and TrackRelativeVectors().
void SubtractVectors3Df (const float Vector1[N3D], const float Vector2[N3D], float Result[N3D])
Calculate the difference between two three-dimensional vectors
Parameters
Vector1 points to a 3-D vector array.
Vector2 points to a 3-D vector array.
Result points to space to receive the cross product.
References X_AXIS, Y_AXIS, and Z_AXIS.
double UnitVector2D (double Vector[2])
Change the passed vector into a unit vector
Parameters
Vector points to a 3-D vector array.
Returns
The vector length.
References ChangeVectorSize2D().
float UnitVector2Df (float Vector[2])
Change the passed vector into a unit vector
Parameters
Vector points to a 3-D vector array.
Returns
The vector length.
References ChangeVectorSize2Df().
double UnitVector3D (double Vector[N3D])
Change the passed vector into a unit vector
Parameters
Vector points to a 3-D vector array.
Returns
The vector length.
References ChangeVectorSize3D().
Referenced by GetCurveTriad(), MaxErrorInterpolateBsplineCurve(), MinDistanceToBsplineCurve(), TrackCoordinateParametersECEF3D(), and TrackRelativeVectors().
float UnitVector3Df (float Vector[N3D])
Change the passed vector into a unit vector
Parameters
Vector points to a 3-D vector array.
Returns
The vector length.
References ChangeVectorSize3Df().
double VectorLength2D (const double Vector[2])
Calculate the length of the two dimensional vector
Parameters
Vector points to a 2-D vector array
Returns
The length of the passed vector.
References VectorLengthSquared2D().
Referenced by ChangeVectorSize2D(), and InteriorAngle2D().
float VectorLength2Df (const float Vector[2])
Calculate the length of the two dimensional vector
Parameters
Vector points to a 2-D vector array
Returns
The length of the passed vector.
References VectorLengthSquared2Df().
Referenced by ChangeVectorSize2Df(), and InteriorAngle2Df().
double VectorLength3D (const double Vector[N3D])
Calculate the length of the three dimensional vector
Parameters
Vector points to a 3-D vector array
Returns
The length of the passed vector.
References VectorLengthSquared3D().
Referenced by ChangeVectorSize3D(), CosInteriorAngle3D(), DistanceAlongBsplineCurve(), DistanceBetweenECEF(), DistanceBetweenECEFCircle(), MaxErrorInterpolateBsplineCurve(), and MinDistanceToBsplineCurve().
float VectorLength3Df (const float Vector[N3D])
Calculate the length of the three dimensional vector
Parameters
Vector points to a 3-D vector array
Returns
The length of the passed vector.
References VectorLengthSquared3Df().
Referenced by ChangeVectorSize3Df(), and CosInteriorAngle3Df().
double VectorLengthSquared2D (const double Vector[2])
Calculate the squared length of the two dimensional vector. This is faster than calculating the actual length because it avoids the square root computation
Parameters
Vector points to a 2-D vector array
Returns
The square of the length of the passed vector.
References X_AXIS, and Y_AXIS.
Referenced by VectorLength2D().
float VectorLengthSquared2Df (const float Vector[2])
Calculate the squared length of the two dimensional vector. This is faster than calculating the actual length because it avoids the square root computation
Parameters
Vector points to a 2-D vector array
Returns
The square of the length of the passed vector.
Referenced by VectorLength2Df().
double VectorLengthSquared3D (const double Vector[N3D])
Calculate the squared length of the three dimensional vector. This is faster than calculating the actual length because it avoids the square root computation
Parameters
Vector points to a 3-D vector array
Returns
The square of the length of the passed vector.
References X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by VectorLength3D().
float VectorLengthSquared3Df (const float Vector[N3D])
Calculate the squared length of the three dimensional vector. This is faster than calculating the actual length because it avoids the square root computation
Parameters
Vector points to a 3-D vector array
Returns
The square of the length of the passed vector.
References X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by VectorLength3Df().