Communications SDK: Matrix.h File Reference
Matrix.h File Reference
Matrix operations.
Functions
int SolveAugmentedMatrix (double *pA, double *pb, double *px, int n)
void TransposeGeneral (const double *pA, int rows, int cols, double *pB)
void TransposeSquare (double *pA, int n)
void TransposeSquaref (float *pA, int n)
int MatrixMultiply (const double *pA, int rowsA, int innerD, const double *pB, int colsB, double *pC)
int MatrixMultiplyf (const float *pA, int rowsA, int innerD, const float *pB, int colsB, float *pC)
void MatrixAdd (const double *pA, const double *pB, int rows, int cols, double *pC)
void MatrixAddf (const float *pA, const float *pB, int rows, int cols, float *pC)
void MatrixMulScalar (double a, const double *pA, int rows, int cols, double *pB)
void MatrixEye (int rows, int cols, double *pA)
void MatrixZeros (int rows, int cols, double *pA)
void MatrixCopy (const double *pA, int rows, int cols, double *pB)
void MatrixDiag (const double *pV, int dim, double *pA)
void MatrixGetDiag (const double *pA, int dim, double *pV)
void ModChol (const double *pP, int dim, double *pU, double *pD)
void ModCholInv (const double *pU, const double *pD, int dim, double *pP)
double VectorMagnitude (const double *pV, int size)
void VectorNormalize (const double *pV, int size, double *pVn)
void SubtractVectors (const double Vector1[], const double Vector2[], double Result[], int size)
void AddVectors (const double Vector1[], const double Vector2[], double Result[], int size)
void MultiplyVectorByScaler (double Scaler, const double Vector[], double Result[], int size)
void MatrixConcatenateV (const double *pA, int rowsA, const double *pB, int rowsB, int cols, double *pC)
void MatrixConcatenateH (const double *pA, int colsA, const double *pB, int colsB, int rows, double *pC)
void MatrixUpperTriangular (const double *pV, int dim, double *pA)
void MatrixGetUpperTriangular (const double *pA, int dim, double *pV)
void HouseQR (const double *A, int rows, int cols, double *Q, double *R)
void Chol (const double *A, int size, double *R)
void CholEx (const double *A, int size, double *R, double *ATemp)
double MatrixDet2 (const double A[4])
void MatrixInv2 (const double A[4], double Ainv[4])
double MatrixDet3 (const double A[9])
float MatrixDet3f (const float A[9])
void MatrixInv3 (const double A[9], double Ainv[9])
void MatrixInv3f (const float A[9], float Ainv[9])
double MatrixDet4 (const double A[16])
void MatrixInv4 (const double A[16], double Ainv[16])
void MatrixInverse (const double *A, int n, double *Ainv)
int MatrixLUInverse (const double *A, int n, double *Ainv)
Invert a matrix by LU factorization.
int MatrixLU (const double *A, int n, double *LU, int *indx)
Factorize a square matrix into a lower-triangular and an upper-triangular matrix.
int MatrixLUInPlace (double *LU, int n, int *indx)
Factorize a square matrix into LU form, in place.
void BacksubLU (const double *LU, const double *b, double *x, int *indx, int n)
Solve a linear system by back-substitution, for a system matrix given in LU form.
void MatrixSumCols (const double *A, int nRows, int nCols, double *v)
void srotg (double *sa, double *sb, double *c, double *s)
double sdot (const double *a, const double *b, int n)
void schud (const double *R, int n, const double *X, double *R1)
void schdd (const double *R, int n, const double *X, double *R1)
void CholUpdate (const double *R, int nR, const double *X, int mX, double u, double *R1)
void SkewSymmetric3 (const double vec[3], double mat[9])
Create a 3x3 skew-symmetric matrix from a 3-element vector.
void EigQR (const double *A, int n, double *lambda, double *V)
Compute the eigenvalues and eigenvectors of a square matrix using QR algorithm.
double MatrixNormInf (const double *A, int rows, int cols)
Get the infinity norm of a matrix.
void MatrixSqr (const double *A, int nRows, int nCols, double *sqrA)
Calculate a matrix product of the form A'*A.
int SVDcmpf (float **A, int m, int n, float *W, float **V)
Singular value decomposition.
int MatrixInverseSVDf (float **A, int m, int n, float **Ainv)
Pseudo-inverse for non-square and singular matricies.
Detailed Description
Matrix operations.
This module provides matrix functions such as multiplication, addition, transpose, etc.
Function Documentation
void AddVectors (const double Vector1[], const double Vector2[], double Result[], int size)
Calculate the sum of two vectors
Parameters
Vector1 points to a vector array.
Vector2 points to a vector array.
Result points to space to receive the result.
size is the number of elements in each vector
void BacksubLU (const double * LU, const double * b, double * x, int * indx, int n)
Solve a linear system by back-substitution, for a system matrix given in LU form.
Back substitution for solving Lower/Upper decomposition
Parameters
LU points to the LU matrix
b points to the boundary condition vector b
x points to the solution vector x
indx is the permutation vector.
n is the size of the matrix.
Referenced by ApproximateBsplineCurve(), InterpolateBsplineCurve(), and MatrixLUInverse().
void Chol (const double * A, int size, double * R)
Cholesky factorization of a square symmetric matrix. This function uses dynamic memory allocation.
Parameters
A is a square symmetric matrix.
size is the size of matrix A.
R is the resulting upper-triangular Cholesky factor such that A = R'*R.
References CholEx().
void CholEx (const double * A, int size, double * R, double * ATemp)
Cholesky factorization of a square symmetric matrix. This function uses caller supplied storage for temporary data space.
Parameters
A is a square symmetric matrix.
size is the size of matrix A.
R is the resulting upper-triangular Cholesky factor such that A = R'*R.
ATemp points to temporary space equal in size to A.
References MatrixCopy(), and MatrixZeros().
Referenced by Chol().
void CholUpdate (const double * R, int nR, const double * X, int mX, double u, double * R1)
Rank update of a Cholesky factorization. This computes the Cholesky factor R1 of the matrix A + sqrt(u)*X*X'(update) or A - sqrt(u)*X*X'(downdate), knowing R - the Cholesky factor of original matrix A.
Parameters
R is an upper-triangular Cholesky factor.
nR is the size of matrix R.
X is a column vector or a matrix.
mX is the number of columns in X.
u is the update factor (positive for an update, negative for a downdate).
R1 is the resulting upper-triangular Cholesky factor such that A +/- sqrt(u)*X*X' = R1'*R1.
References MatrixCopy(), schdd(), schud(), and sign().
void EigQR (const double * A, int n, double * lambda, double * V)
Compute the eigenvalues and eigenvectors of a square matrix using QR algorithm.
Compute the eigenvalues and eigenvectors of a square matrix using QR algorithm.
Parameters
A is a square matrix.
n is the number of rows/columns in matrix A.
lambda is the vector of resulting eigenvalues.
V is the matrix of resulting eigenvectors.
References HouseQR(), MatrixCopy(), MatrixEye(), MatrixMultiply(), and MatrixNormInf().
void HouseQR (const double * A, int rows, int cols, double * Q, double * R)
QR factorization using Householder reflections. Function returns Q and R such that A = Q*R.
Parameters
A is a matrix.
rows is the number of rows in matrix A.
cols is the number of columns in matrix A.
Q is an unitary matrix.
R is an upper-triangular matrix.
References MatrixCopy(), MatrixEye(), and MatrixMultiply().
Referenced by EigQR().
void MatrixAdd (const double * pA, const double * pB, int rows, int cols, double * pC)
Add two matrices of the same size. The data in a matrix are stored such that A[row][col] = A[row*n + col].
Parameters
pA is a pointer to the first matrix A to be added
pB is a pointer to the second matrix B to be added
rows is the number of rows of matrices A and B
cols is the number of columns of matrices A and B
pC is a pointer to the resulting matrix sum C = A + B.
Referenced by ModChol().
void MatrixAddf (const float * pA, const float * pB, int rows, int cols, float * pC)
Add two matrices of the same size. The data in a matrix are stored such that A[row][col] = A[row*n + col].
Parameters
pA is a pointer to the first matrix A to be added
pB is a pointer to the second matrix B to be added
rows is the number of rows of matrices A and B
cols is the number of columns of matrices A and B
pC is a pointer to the resulting matrix sum C = A + B.
void MatrixConcatenateH (const double * pA, int colsA, const double * pB, int colsB, int rows, double * pC)
Concatenate two matrices horizontally C = [A B]
Parameters
pA is a pointer to the first matrix A
colsA is the number of columns in matrix A
pB is a pointer to the second matrix B
colsB is the number of columns in matrix B
rows is the number of rows of both A and B (must be equal)
pC is a pointer to the resulting block matrix C of size rows x (colsA+colsB)
void MatrixConcatenateV (const double * pA, int rowsA, const double * pB, int rowsB, int cols, double * pC)
Concatenate two matrices vertically C = [A; B]
Parameters
pA is a pointer to the first matrix A
rowsA is the number of rows in matrix A
pB is a pointer to the second matrix B
rowsB is the number of rows in matrix B
cols is the number of columns of both A and B (must be equal)
pC is a pointer to the resulting block matrix C of size (rowsA+rowsB) x cols
void MatrixCopy (const double * pA, int rows, int cols, double * pB)
Copy the elements from a matrix A to a matrix B. Both matrices must have the same size.
Parameters
pA is a pointer to the source matrix A
rows is the number of rows in the source and destination matrices
cols is the number of columns in the source and destination matrices
pB is a pointer to the destination matrix B = A
Referenced by CholEx(), CholUpdate(), EigQR(), HouseQR(), MatrixLU(), ModChol(), ModCholInv(), schdd(), and schud().
double MatrixDet2 (const double A[4])
The determinant of a 2x2 matrix.
Parameters
A points to the matrix.
Returns
the determinant.
Referenced by MatrixInv2().
double MatrixDet3 (const double A[9])
The determinant of a 3x3 matrix.
Parameters
A points to the matrix.
Returns
the determinant.
Referenced by MatrixInv3().
float MatrixDet3f (const float A[9])
The determinant of a 3x3 matrix.
Parameters
A points to the matrix.
Returns
the determinant.
Referenced by MatrixInv3f().
double MatrixDet4 (const double A[16])
Calculate the determinant of a 4x4 matrix.
Parameters
A points to the matrix.
Returns
the determinant.
Referenced by MatrixInv4().
void MatrixDiag (const double * pV, int dim, double * pA)
Create a square matrix and copy the elements from vector V to the main diagonal of matrix A. The rest of elements in matrix A will be initialized to zero.
Parameters
pV is a pointer to the source vector V
dim is the dimension of the vector V
pA is a pointer to the resulting diagonal matrix A.
References MatrixZeros().
void MatrixEye (int rows, int cols, double * pA)
Create an identity matrix. If the matrix is not square, then the additional rows or columns will contain only zeros.
Parameters
rows is the number of rows of the identity matrix
cols is the number of columns of the identity matrix
pA is a pointer to the resulting identity matrix A
Referenced by EigQR(), GetNavToBodyMatFromVec(), and HouseQR().
void MatrixGetDiag (const double * pA, int dim, double * pV)
Extract the diagonal of a square matrix and return it as a vector
Parameters
pA is a pointer to a square matrix A
dim is the dimension of the matrix A (row = col)
pV is the diagonal of matrix A returned as a vector
void MatrixGetUpperTriangular (const double * pA, int dim, double * pV)
Create a vector of elements from a square upper-triangular matrix. For example, an upper-triangular matrix: A = [a11 a12 a13; 0 a22 a23; 0 0 a33] will result in a vector V = [a11 a12 a13 a22 a23 a33].
Parameters
pA is a pointer to the upper-triangular matrix.
dim is the matrix size.
pV points to space to receive the resulting vector with data.
References MatrixZeros(), sign(), and VectorMagnitude().
void MatrixInv2 (const double A[4], double Ainv[4])
The inverse of a 2x2 matrix
Parameters
A points to the matrix which will be inverted.
Ainv points to space to receive the inverse of matrix A.
References MatrixDet2().
Referenced by MatrixInverse().
void MatrixInv3 (const double A[9], double Ainv[9])
The inverse of a 3x3 matrix
Parameters
A points to the matrix which will be inverted.
Ainv points to space to receive the inverse of matrix A.
References MatrixDet3().
Referenced by MatrixInverse().
void MatrixInv3f (const float A[9], float Ainv[9])
The inverse of a 3x3 matrix
Parameters
A points to the matrix which will be inverted.
Ainv points to space to receive the inverse of matrix A.
References MatrixDet3f().
void MatrixInv4 (const double A[16], double Ainv[16])
The inverse of a 4x4 matrix
Parameters
A points to the matrix which will be inverted.
Ainv points to space to receive the inverse of matrix A.
References MatrixDet4().
Referenced by MatrixInverse().
void MatrixInverse (const double * A, int n, double * Ainv)
Compute the inverse of a square matrix. Uses explicit formulas if the matrix is 1x1, 2x2, or 3x3, and an LU factorization otherwise.
Parameters
A points to the matrix which will be inverted.
n is the matrix size.
Ainv points to space to receive the inverse of matrix A.
References MatrixInv2(), MatrixInv3(), MatrixInv4(), and MatrixLUInverse().
int MatrixInverseSVDf (float ** A, int m, int n, float ** Ainv)
Pseudo-inverse for non-square and singular matricies.
References SVDcmpf().
int MatrixLU (const double * A, int n, double * LU, int * indx)
Factorize a square matrix into a lower-triangular and an upper-triangular matrix.
Decompose a matrix A into a lower-triangular matrix L and an upper-triangular matrix U, such that A = L*U.
Parameters
A points to the source matrix.
n is the number of rows and columns of A.
LU points to space to receive the decomposed matrix
indx receives the permutations vector.
References MatrixCopy(), and MatrixLUInPlace().
Referenced by MatrixLUInverse().
int MatrixLUInPlace (double * LU, int n, int * indx)
Factorize a square matrix into LU form, in place.
Decompose a matrix A into a lower-triangular matrix L and an upper-triangular matrix U, such that A = L*U. The factorization is done in-place, operating directly on the input matrix.
Parameters
LU points to a square matrix that will be factorized in-place.
n is the number of rows and columns of A.
indx receives the permutations vector.
Referenced by ApproximateBsplineCurve(), InterpolateBsplineCurve(), and MatrixLU().
int MatrixLUInverse (const double * A, int n, double * Ainv)
Invert a matrix by LU factorization.
Invert a matrix by LU factorization and back substitution.
Parameters
A points to the matrix to invert.
n is the number of rows and columns of A.
Ainv points to space to received the inverted matrix
References BacksubLU(), and MatrixLU().
Referenced by MatrixInverse().
void MatrixMulScalar (double a, const double * pA, int rows, int cols, double * pB)
Multiply a matrix with a scalar. The data in a matrix are stored such that A[row][col] = A[row*n + col].
Parameters
a is the scalar
pA is a pointer to the matrix A
rows is the number of rows in matrix A
cols is the number of columns in matrix A
pB is a pointer to the resulting matrix B = a*A
Referenced by ModChol().
int MatrixMultiply (const double * pA, int rowsA, int innerD, const double * pB, int colsB, double * pC)
Multiply matrix A by matrix B (A x B) and put the resutl into matrix C. The data in a matrix are stored such that A[row][col] = A[row*n + col]. Note: by the definition of matrix multiplication, rows of B must be equal to the cols of A.
 example:    |A00,A01,A02|   |B00,B01,B02,B03|   |C00,C01,C02,C03|
             |A10,A11,A12| x |B10,B11,B12,B13| = |C10,C11,C12,C13|
             |A20,A21,A22|   |B20,B21,B22,B23|   |C20,C21,C22,C23|
             |A30,A31,A32| innerD = 3, colsB = 4 |C30,C31,C32,C33|
             |A40,A41,A42|                       |C40,C41,C42,C43|
             |A50,A51,A52|                       |C50,C51,C52,C53|
             rowsA = 6, innerD = 3               rowsA x colsB
         where: C13 = A10*B03 + A11*B13 + A12*B23
         Cij = scalar product of ith row of A by jth col of B
Parameters
pA points to the matrix A.
rowsA is the number of rows in matrix A.
innerD is the number of columns in matrix A and number of rows in matrix B.
pB points to the matrix B.
colsB is the number of columns in matrix B.
pC points to the solution space which must be large enough to hold rowsA x colsB elements.
Returns
Nonzero if successful.
Referenced by CreateRotationEx(), EigQR(), GetNavToBodyMatFromVec(), HouseQR(), ModCholInv(), RotateBody2Nav(), and RotateNav2Body().
int MatrixMultiplyf (const float * pA, int rowsA, int innerD, const float * pB, int colsB, float * pC)
Multiply matrix A by matrix B (A x B) and put the resutl into matrix C. The data in a matrix are stored such that A[row][col] = A[row*n + col]. Note: by the definition of matrix multiplication, rows of B must be equal to the cols of A.
 example:    |A00,A01,A02|   |B00,B01,B02,B03|   |C00,C01,C02,C03|
             |A10,A11,A12| x |B10,B11,B12,B13| = |C10,C11,C12,C13|
             |A20,A21,A22|   |B20,B21,B22,B23|   |C20,C21,C22,C23|
             |A30,A31,A32| innerD = 3, colsB = 4 |C30,C31,C32,C33|
             |A40,A41,A42|                       |C40,C41,C42,C43|
             |A50,A51,A52|                       |C50,C51,C52,C53|
             rowsA = 6, innerD = 3               rowsA x colsB
         where: C13 = A10*B03 + A11*B13 + A12*B23
         Cij = scalar product of ith row of A by jth col of B
Parameters
pA points to the matrix A.
rowsA is the number of rows in matrix A.
innerD is the number of columns in matrix A and number of rows in matrix B.
pB points to the matrix B.
colsB is the number of columns in matrix B.
pC points to the solution space which must be large enough to hold rowsA x colsB elements.
Returns
Nonzero if successful.
Referenced by CreateRotationExf(), RotateBody2Navf(), and RotateNav2Bodyf().
double MatrixNormInf (const double * A, int rows, int cols)
Get the infinity norm of a matrix.
Get the infinity norm of a matrix, which is the largest row sum of absolute values of matrix elements.
Parameters
A is a matrix.
rows is the number of rows in A.
cols is the number of columns in A.
Returns
The infinity norm of A.
References maximum().
Referenced by EigQR().
void MatrixSqr (const double * A, int nRows, int nCols, double * sqrA)
Calculate a matrix product of the form A'*A.
Calculate a matrix product of the form A'*A. This efficient algorithm calculates only the upper triangle of the square matrix, since the multiplication results in a square, symmetric matrix.
Parameters
A is the input matrix, of arbitrary dimensions.
nRows is the number of rows in A.
nCols is the number of columns in A.
sqrA is the resulting matrix M = A'*A.
Referenced by ApproximateBsplineCurve().
void MatrixSumCols (const double * A, int nRows, int nCols, double * v)
Add the columns of a matrix.
Parameters
A points to the source matrix.
nRows is the number of rows in matrix A.
nCols is the number of columns in matrix A.
v points to space to receive the resulting vector.
References MatrixZeros().
void MatrixUpperTriangular (const double * pV, int dim, double * pA)
Create a square upper-triangular matrix with elements from a vector. The matrix is populated in a left-to-right row fashion. For example, a vector with 6 elements: V = [a1 a2 a3 a4 a5 a6] will result in an upper-triangular matrix: A = [a1 a2 a3; 0 a4 a5; 0 0 a6].
Parameters
pV is the vector with data.
dim is the matrix size.
pA is a pointer to the resulting upper-triangular matrix.
References MatrixZeros().
void MatrixZeros (int rows, int cols, double * pA)
Create a matrix of zeros.
Parameters
rows is the number of rows of the matrix
cols is the number of columns of the matrix
pA is a pointer to the resulting matrix A
Referenced by CholEx(), MatrixDiag(), MatrixGetUpperTriangular(), MatrixSumCols(), MatrixUpperTriangular(), and ModChol().
void ModChol (const double * pP, int dim, double * pU, double * pD)
Compute the modified Cholesky factors U, D of symmetric positive definite matrix P such that U is unit upper triangular, D is diagonal and P = U*D*U'
Parameters
pP is a pointer to the symmetric positive-definite matrix P
dim is the number of rows/columns in matrix P
pU is a pointer to the resulting upper-triangular matrix U
pD is a pointer to the resulting diagonal matrix D
References MatrixAdd(), MatrixCopy(), MatrixMulScalar(), MatrixZeros(), and TransposeSquare().
void ModCholInv (const double * pU, const double * pD, int dim, double * pP)
Compute P = U*D*U'. This is the reverse of the transformation ModChol().
Parameters
pU is a pointer to the upper-triangular Cholesky factor U
pD is a pointer to the diagonal Cholesky factor D
dim is the size of the matrices U, D, and P
pP is a pointer to the symmetric positive-definite matrix P
References MatrixCopy(), MatrixMultiply(), and TransposeSquare().
void MultiplyVectorByScaler (double Scaler, const double Vector[], double Result[], int size)
Calculate the result of a vector multiplied by a scaler.
Parameters
Scaler is the scale factor to apply to the vector
Vector points to a vector array to be multiplied.
Result points to space to receive the result, this can be the same as Vector.
size is the number of elements in each vector
void schdd (const double * R, int n, const double * X, double * R1)
Cholesky factor downdate. This computes the Cholesky factor R1 of the matrix A - X*X', knowing R - the Cholesky factor of original matrix A.
Parameters
R is an upper-triangular Cholesky factor.
n is the size of matrix R.
X is a column vector or a matrix.
R1 is the resulting upper-triangular Cholesky factor such that A - X*X' = R1'*R1.
References MatrixCopy(), sdot(), sqr(), and VectorMagnitude().
Referenced by CholUpdate().
void schud (const double * R, int n, const double * X, double * R1)
Cholesky factor update. This computes the Cholesky factor R1 of the matrix A + X*X', knowing R - the Cholesky factor of original matrix A.
Parameters
R is an upper-triangular Cholesky factor.
n is the size of matrix R.
X is a column vector or a matrix.
R1 is the resulting upper-triangular Cholesky factor such that A + X*X' = R1'*R1.
References MatrixCopy(), and srotg().
Referenced by CholUpdate().
double sdot (const double * a, const double * b, int n)
Dot product of two vectors.
Parameters
a points to the first vector.
b points to the second vector.
n is the number of elements in each vector.
Returns
The dot product of the two vectors.
Referenced by schdd().
void SkewSymmetric3 (const double vec[3], double mat[9])
Create a 3x3 skew-symmetric matrix from a 3-element vector.
Create a 3x3 skew-symmetric matrix from a 3x1 vector.
Parameters
vec = the 3x1 input vector
mat = the 3x3 matrix result
Referenced by GetNavToBodyMatFromVec().
int SolveAugmentedMatrix (double * pA, double * pb, double * px, int n)
Use Gaussian elimination and backsolving to find the solution vector x in Ax = b, where x is a square matrix of size n.
 example:    |A00,A01,A02,A03| |x0| |b0|
             |A10,A11,A12,A13| |x1| |b1|
             |A20,A21,A22,A23|*|x2|=|b2|
             |A30,A31,A32,A33| |x3| |b3| : n=4
The data in A are stored such that A[row][col] = A[row*n + col].
Parameters
pA points to the matrix A.
pb points to the boundary condition vector b
px points to the solution vector x
n is the integer size of the matrix, n by n.
Returns
0 for singular matrices, else nonzero
void srotg (double * sa, double * sb, double * c, double * s)
Compute the Givens rotation.
References sign().
Referenced by schud().
void SubtractVectors (const double Vector1[], const double Vector2[], double Result[], int size)
Calculate the difference between two vectors
Parameters
Vector1 points to a vector array.
Vector2 points to a vector array.
Result points to space to receive the result
size is the number of elements in each vector
int SVDcmpf (float ** A, int m, int n, float * W, float ** V)
Singular value decomposition.
Referenced by MatrixInverseSVDf().
void TransposeGeneral (const double * pA, int rows, int cols, double * pB)
Take the transpose of a general matrix A and put the result into the matrix B. The data in A are stored such that A[row][col] = A[row*n + col]. A and B must not be colocated in memory.
 example:    |A00,A01,A02|
             |A10,A11,A12|
             |A20,A21,A22|
             |A30,A31,A32|
             |A40,A41,A42|
             |A50,A51,A52| rows = 6, cols = 3
 becomes:
             |A00,A10,A20,A30,A40|
             |A01,A11,A21,A31,A41|
             |A02,A12,A22,A32,A42| rows = 3, cols = 6
Parameters
pA points to the matrix A
rows is the integer number of rows in A.
cols is the integer number of columns in A.
pB points to storage for the result matrix B
void TransposeSquare (double * pA, int n)
Take the transpose of a square matrix A, putting the result back into A. If you want to preserve what is in A, call TransposeGeneral(). The data in A are stored such that A[row][col] = A[row*n + col].
 example:    |A00,A01,A02|
             |A10,A11,A12|
             |A20,A21,A22| n x n
 becomes:
             |A00,A10,A20|
             |A01,A11,A21|
             |A02,A12,A22| n x n
Parameters
pA points to the matrix A
n is the size of the matrix, n x n
Referenced by InterpolateBsplineCurve(), ModChol(), and ModCholInv().
void TransposeSquaref (float * pA, int n)
Take the transpose of a square matrix A, putting the result back into A. If you want to preserve what is in A, call TransposeGeneral(). The data in A are stored such that A[row][col] = A[row*n + col].
 example:    |A00,A01,A02|
             |A10,A11,A12|
             |A20,A21,A22| n x n
 becomes:
             |A00,A10,A20|
             |A01,A11,A21|
             |A02,A12,A22| n x n
Parameters
pA points to the matrix A
n is the size of the matrix, n x n
double VectorMagnitude (const double * pV, int size)
Compute the magnitude of a vector
Parameters
pV is a pointer to the vector
size is the size of the vector
Returns
The magnitude of the vector
Referenced by MatrixGetUpperTriangular(), schdd(), and VectorNormalize().
void VectorNormalize (const double * pV, int size, double * pVn)
Normalize a vector by dividing its elements by its magnitude
Parameters
pV is a pointer to the original vector
size is the size of the vector
pVn is a pointer to the normalized vector, this can be the same as pV
References VectorMagnitude().