Communications SDK: Network.h File Reference
Network.h File Reference
Stream multiplex logic for Piccolo.
#include "Types.h"
#include "Queue.h"
#include "stream.h"
#include "Timer.h"
Classes
struct Stream_t
struct Network_t
Macros
#define GS_STREAM 3
#define AUTOPILOT_STREAM_SIZE 4096
#define GIMBAL_STREAM_SIZE 1024
#define MAX_STREAM_SIZE AUTOPILOT_STREAM_SIZE
Enumerations
enum StreamIdentifiers {
POLLING_STREAM, DGPS_STREAM, PILOT_STREAM, AUTOPILOT_STREAM,
APP_STREAM, GIMBAL_STREAM, PAYLOAD_STREAM, PAYLOAD2_STREAM,
DEBUG_STREAM, CAN_STREAM, ADSB_STREAM, NUM_STREAMS,
USER_LOG_STREAM = 0xFD, KEEPALIVE_STREAM = 0xFE, ENUMERATION_STREAM = 0xFF
}
Functions
BOOL InitNetwork (Network_t *pNet, UInt16 DestID, UInt16 MyID)
void CloseNetwork (Network_t *pNet)
BOOL OpenStream (Network_t *pNet, UInt8 Stream, UInt8 dir, UInt32 QSize)
void CloseStream (Network_t *pNet, UInt8 Stream)
void ResetNetworkBuffers (Network_t *pNet)
void QueueDataForTransmit (Stream_t *pStream, const UInt8 *pBuf, UInt32 len)
Detailed Description
Stream multiplex logic for Piccolo.
The network module sits atop the stream module and provides functionality for dealing with the multiple streams that move over stream packets
Macro Definition Documentation
#define GS_STREAM 3
When talking to a ground station
Referenced by UdpAutoDetector::checkForNewServers(), and CommBase_SendGroundStationPacket().
Enumeration Type Documentation
enum StreamIdentifiers
Stream identifiers
Enumerator
POLLING_STREAM
Flow control stream.
DGPS_STREAM
Differential corrections stream.
PILOT_STREAM
Manual pilot command stream.
AUTOPILOT_STREAM
Autopilot command and telemetry stream.
APP_STREAM
Autopilot application stream.
GIMBAL_STREAM
Camera gimbal stream.
PAYLOAD_STREAM
Data from the payload comm port.
PAYLOAD2_STREAM
Data from the second payload comm port.
DEBUG_STREAM
Stream for moving debug data.
CAN_STREAM
Stream for moving CAN pass through data.
ADSB_STREAM
Stream for downlinking ADS-B receiver data.
NUM_STREAMS
The number of streams.
USER_LOG_STREAM
Stream for logging custom binary data from UI to tel file.
Function Documentation
void CloseNetwork (Network_t * pNet)
Release the resources being held by a network.
Parameters
pNet points to a network structure.
References CloseStream(), Network_t::DestID, Network_t::MyID, and Network_t::NumStreams.
Referenced by InitNetwork().
void CloseStream (Network_t * pNet, UInt8 Stream)
Destroy the buffers associated with the Stream. The buffer pointers are NULLed so that the stream manager stops servicing this stream.
Parameters
pNet points to a network structure.
Stream identifies the stream to close.
References DestroyQ(), Network_t::NumStreams, Stream_t::pRxQ, Stream_t::pTxQ, and Network_t::Streams.
Referenced by CloseNetwork().
BOOL InitNetwork (Network_t * pNet, UInt16 DestID, UInt16 MyID)
Initialize the network software. This involves allocating data for the individual streams and filling out the network structure.
Parameters
pNet points to a network structure which will hold the stream data.
DestID is the address of the device we talk to with this network.
MyID is our address.
Returns
TRUE if data successfully allocated, else FALSE.
References ADSB_STREAM, AUTOPILOT_STREAM, BOTH_DIR, CAN_STREAM, CloseNetwork(), DEBUG_STREAM, Network_t::DestID, DGPS_STREAM, GIMBAL_STREAM, Network_t::MyID, NUM_STREAMS, Network_t::NumStreams, OpenStream(), PAYLOAD2_STREAM, PAYLOAD_STREAM, and PILOT_STREAM.
BOOL OpenStream (Network_t * pNet, UInt8 Stream, UInt8 dir, UInt32 QSize)
Open a stream on the network, allocating the stream buffers.
Parameters
pNet points to a network structure.
Stream identifies which stream should be opened.
dir controls the stream directino (DIR_RX, DIR_TX, DIR_BOTH).
QSize controls the size of the transmit and receive buffers for the stream.
Returns
TRUE if the stream is opened, else FALSE.
References CreateQ(), DestroyQ(), Network_t::NumStreams, Stream_t::pRxQ, Stream_t::pTxQ, RX_DIR, Network_t::Streams, and TX_DIR.
Referenced by InitNetwork().
void QueueDataForTransmit (Stream_t * pStream, const UInt8 * pBuf, UInt32 len)
Queue data for transmit on a specific stream. This will load the data into the transmit buffer and it will set the send flag to indicate that data are waiting to go.
Parameters
pStream points to the stream to receive the data.
pBuf points to an array of data to send.
len is the amount of data to push onto the buffer.
References BlockEnQ(), Stream_t::pTxQ, and Stream_t::Send.
void ResetNetworkBuffers (Network_t * pNet)
Reset the transmit and stream receive buffers in the network. This will discard any data in the buffers.
Parameters
pNet points to a network structure.
References Stream_t::LocalSeq, Stream_t::NumberOfUnAcks, Network_t::NumStreams, Stream_t::pRxQ, Stream_t::pTxQ, Stream_t::RemoteAck, ResetQ(), Stream_t::Send, and Network_t::Streams.