Communications SDK: PiccoloXML.h File Reference
PiccoloXML.h File Reference
XML support routines for writing and reading configuration files.
#include <libxml/xinclude.h>
#include "PiccoloDefinitions.h"
#include <string>
Functions
void AddIndentingElements (xmlNodePtr cur, int IndentLevel)
xmlDocPtr OpenXMLNamedDoc (const char *filename, const char *name)
xmlDocPtr OpenXMLConfig (const char *filename)
xmlDocPtr CreateNewXMLNamedDoc (const char *name)
xmlDocPtr CreateNewXMLConfig (void)
xmlNodePtr FindNamedXMLChildNode (xmlNodePtr parent, const xmlChar *name)
xmlNodePtr FindIndexedNamedXMLChildNode (xmlNodePtr parent, const xmlChar *name, int index)
xmlNodePtr FindNamedXMLSiblingNode (xmlNodePtr Start, const xmlChar *name)
xmlNodePtr FindNextNamedXMLSiblingNode (xmlNodePtr Start, const xmlChar *name)
xmlNodePtr FindOrCreateNamedXMLChildNode (xmlNodePtr parent, const xmlChar *name, const xmlChar *content=NULL)
xmlNodePtr FindOrCreateIndexedNamedXMLChildNode (xmlNodePtr parent, const xmlChar *name, int index, const xmlChar *content=NULL)
BOOL ReadXMLDataContent (xmlDocPtr doc, xmlNodePtr root, const char *name, float *pValue)
BOOL ReadXMLDataContent (xmlDocPtr doc, xmlNodePtr root, const char *name, double *pValue)
BOOL ReadXMLDataContent (xmlDocPtr doc, xmlNodePtr root, const char *name, UInt8 *pValue)
BOOL ReadXMLDataContent (xmlDocPtr doc, xmlNodePtr root, const char *name, UInt16 *pValue)
BOOL ReadXMLDataContent (xmlDocPtr doc, xmlNodePtr root, const char *name, UInt32 *pValue)
BOOL ReadXMLDataContent (xmlDocPtr doc, xmlNodePtr root, const char *name, SInt8 *pValue)
BOOL ReadXMLDataContent (xmlDocPtr doc, xmlNodePtr root, const char *name, SInt16 *pValue)
BOOL ReadXMLDataContent (xmlDocPtr doc, xmlNodePtr root, const char *name, SInt32 *pValue)
BOOL WriteXMLDataContent (xmlNodePtr root, const char *name, char *content)
BOOL WriteXMLDataContent (xmlNodePtr root, const char *name, double Value)
BOOL WriteXMLDataContent (xmlNodePtr root, const char *name, double Value, int precision)
BOOL WriteXMLDataContent (xmlNodePtr root, const char *name, float Value)
BOOL WriteXMLDataContent (xmlNodePtr root, const char *name, UInt8 Value)
BOOL WriteXMLDataContent (xmlNodePtr root, const char *name, UInt16 Value)
BOOL WriteXMLDataContent (xmlNodePtr root, const char *name, UInt32 Value)
BOOL SetXMLMissionLimits (xmlDocPtr doc, const MissionLimits_t *pMissionLimits)
UInt32 GetXMLMissionLimits (xmlDocPtr doc, MissionLimits_t *pMissionLimits, std::string &Error, const MissionLimits_t *pToCompare=NULL)
BOOL SetXMLEuler (xmlDocPtr doc, const float Euler[NAXIS], const float IMUtoAnt[N3D], const float IMUtoAnt2[N3D])
UInt32 GetXMLEuler (xmlDocPtr doc, float Euler[NAXIS], float IMUtoAnt[N3D], float IMUtoAnt2[N3D], std::string &Error, const float *pEulerToCompare=NULL, const float *pIMUtoAntToCompare=NULL, const float *pIMUtoAnt2ToCompare=NULL)
BOOL SetXMLSurfaces (xmlDocPtr doc, const ActuatorTable_t Table[NUM_SURFACES], const UInt8 Types[NUM_SURFACES], const UInt8 Virtual[NUM_SURFACES], const UInt8 Fast[NUM_SURFACES])
UInt32 GetXMLSurfaces (xmlDocPtr doc, ActuatorTable_t Table[NUM_SURFACES], UInt8 Types[NUM_SURFACES], UInt8 Virtual[NUM_SURFACES], UInt8 Fast[NUM_SURFACES], std::string &Error, const ActuatorTable_t *pTableToCompare=NULL, const UInt8 *pTypesToCompare=NULL, const UInt8 *pVirtualToCompare=NULL, const UInt8 *pFastToCompare=NULL)
BOOL SetXMLPayload1 (xmlDocPtr doc, const ExternalIO_t ExternalIO[NUM_PAYLOAD_IO_PINS], UInt32 SampleTime)
UInt32 GetXMLPayload1 (xmlDocPtr doc, ExternalIO_t ExternalIO[NUM_PAYLOAD_IO_PINS], UInt32 *pSampleTime, std::string &Error)
BOOL SetXMLPayload2 (xmlDocPtr doc, const ExternalIO_t ExternalIO[NUM_PAYLOAD2_IO_PINS], UInt32 SampleTime)
UInt32 GetXMLPayload2 (xmlDocPtr doc, ExternalIO_t ExternalIO[NUM_PAYLOAD2_IO_PINS], UInt32 *pSampleTime, std::string &Error)
BOOL SetXMLPayload (xmlDocPtr doc, const ExternalIO_t ExternalIO[NUM_EXTERNAL_IO_PINS], UInt32 SampleTime)
UInt32 GetXMLPayload (xmlDocPtr doc, ExternalIO_t ExternalIO[NUM_EXTERNAL_IO_PINS], UInt32 *pSampleTime, std::string &Error, const ExternalIO_t *pExternalIOToCompare=NULL, const UInt32 *pSampleTimeToCompare=NULL)
BOOL SetXMLExternalSerial (xmlDocPtr doc, const ExternalSerial_t *pSerial)
UInt32 GetXMLExternalSerial (xmlDocPtr doc, ExternalSerial_t *pSerial, std::string &Error, const ExternalSerial_t *pToCompare=NULL)
BOOL SetXMLMagCal (xmlDocPtr doc, const float HardIronErr[N3D], const float ScaleFactErr[N3D])
UInt32 GetXMLMagCal (xmlDocPtr doc, float HardIronErr[N3D], float ScaleFactErr[N3D], std::string &Error, const float *pHardIronToCompare=NULL, const float *pScaleFactToCompare=NULL)
BOOL SetXMLSensorError (xmlDocPtr doc, const SensorErrorData_t *pSensorError)
UInt32 GetXMLSensorError (xmlDocPtr doc, SensorErrorData_t *pSensorError, std::string &Error, const SensorErrorData_t *pSensorErrorCmp=NULL)
Detailed Description
XML support routines for writing and reading configuration files.
PiccoloXML hosts the routines to read and write Piccolo configuration data to and from XML files. The XML support is based upon the GNU libxml tools version 2. Any application which uses the XML tools will need to link to libxml.
To use the routines you first open an XML file, then read or write to the file. Finally the file is saved and the XML document tree is freed.
BOOL SaveXMLMissionLimits(const MissionLimits_t* pMissionLimits)
{
    xmlDocPtr doc;
    // Load up the existing document so that we don't lose anything in it
    doc = OpenXMLConfig("MyXMLFile.xml");
    // If the file is bogus then create a new document tree
    if(doc == NULL) doc = CreateNewXMLConfig();
    if(doc == NULL)
    {
        // Failed to create docuemnt tree, configuration not saved"
        return FALSE;
    }
    // Update the mission limits part of the document tree
    SetXMLMissionLimits(doc, pMissionLimits);
    // Save the file
    xmlSaveFile("MyXMLFile.xml", doc);
    // Free the document tree
    xmlFreeDoc(doc);
    return TRUE;
}// SaveXMLMissionLimits
BOOL LoadXMLMissionLimits(MissionLimits_t* pMissionLimits)
{
    std::string ErrorString;
    xmlDocPtr doc;
    // Load up the existing document so that we don't lose anything in it
    doc = OpenXMLConfig("MyXMLFile.xml");
    if(doc == NULL)
    {
        // Failed to open document, data not loaded
        return FALSE;
    }
    // Get the mission limits part of the document
    if(GetXMLMissionLimits(doc, pMissionLimits, ErrorString) == 0)
    {
        // Free the document tree
        xmlFreeDoc(doc);
        return TRUE;
    }
    else
    {
        // Free the document tree
        xmlFreeDoc(doc);
        // Some problem with the file, ErrorString
        //   contains a description of the problem
        return FALSE;
    }
}// LoadXMLMissionLimits
Function Documentation
void AddIndentingElements (xmlNodePtr cur, int IndentLevel)
Add indenting elements to the document tree in order to get a nicely formatted document. This function will call itself recursively in order to correctly indent all children
Parameters
cur is the XML node pointer to begin added indenting elemetns.
IdentLevel is the number of tabs to move the data.
Referenced by SetXMLEuler(), SetXMLExternalSerial(), SetXMLMagCal(), SetXMLMissionLimits(), SetXMLPayload(), SetXMLPayload1(), SetXMLPayload2(), SetXMLSensorError(), and SetXMLSurfaces().
xmlDocPtr CreateNewXMLConfig (void)
Create a new XML config document tree for Piccolo. The new tree will have only the top level Piccolo node in it. The caller is responsible for freeing the docuemnt tree by calling xmlFreeDoc().
Returns
A pointer to the XML doc tree, or NULL if an error occurred
References CreateNewXMLNamedDoc().
xmlDocPtr CreateNewXMLNamedDoc (const char * name)
Create a new XML document tree with a specific name. The new tree will have only the top level node in it. The caller is responsible for freeing the docuemnt tree by calling xmlFreeDoc().
Returns
A pointer to the XML doc tree, or NULL if an error occurred
Referenced by CreateNewXMLConfig().
xmlNodePtr FindIndexedNamedXMLChildNode (xmlNodePtr parent, const xmlChar * name, int index)
Search the children of the passed XML node to find the N-th one with the specified name.
Parameters
parent is the parent of the node(s) to be searched
name is the name of the node to be found.
index is the desired number of name matches N (this is a 1-based index).
Returns
A node pointer to the found node, NULL if it cannot be found.
Referenced by FindOrCreateIndexedNamedXMLChildNode().
xmlNodePtr FindNamedXMLChildNode (xmlNodePtr parent, const xmlChar * name)
Search the children of the passed XML node to find the named one.
Parameters
parent is the parent of the node(s) to be searched
name is the name of the node to be found.
Returns
A node pointer to the found node, NULL if it cannot be found.
Referenced by FindOrCreateNamedXMLChildNode(), GetXMLEuler(), GetXMLExternalSerial(), GetXMLMagCal(), GetXMLMissionLimits(), GetXMLPayload(), GetXMLPayload1(), GetXMLPayload2(), GetXMLSensorError(), GetXMLSurfaces(), and ReadXMLDataContent().
xmlNodePtr FindNamedXMLSiblingNode (xmlNodePtr Start, const xmlChar * name)
Search the list of sibling nodes to find the named one. The search will beging at the first node following Start. If the named node is not found moving foward (next) the search begins again at the Start, but this time goes backwards.
Parameters
Start is the starting point of the node list to be searched
name is the name of the node to be found.
Returns
A node pointer to the found node, NULL if it cannot be found.
xmlNodePtr FindNextNamedXMLSiblingNode (xmlNodePtr Start, const xmlChar * name)
Search the list of sibling nodes to find the named one. The search will begin at the first node following Start, and will stop when the first matching node is found.
Parameters
Start is the starting point of the node list to be searched
name is the name of the node to be found.
Returns
A node pointer to the found node, NULL if it cannot be found.
xmlNodePtr FindOrCreateIndexedNamedXMLChildNode (xmlNodePtr parent, const xmlChar * name, int index, const xmlChar * content)
Search the children of the passed XML node to find the N-th one with a given name. If the N-th named node is not found then create it, specifying the name and content.
Parameters
parent is the parent of the node(s) to be searched
name is the name of the node to be found, or created if not found
index is the desired number of name matches N (this is a 1-based index).
content is the content to be given to the node if it is created.
Returns
A node pointer to the found or newly created node.
References FindIndexedNamedXMLChildNode().
xmlNodePtr FindOrCreateNamedXMLChildNode (xmlNodePtr parent, const xmlChar * name, const xmlChar * content)
Search the children of the passed XML node to find the named one. If the named node is not found then create it, specifying the name and content.
Parameters
parent is the parent of the node(s) to be searched
name is the name of the node to be found, or created if not found
content is the content to be given to the node if it is created.
Returns
A node pointer to the found or newly created node.
References FindNamedXMLChildNode().
Referenced by SetXMLEuler(), SetXMLExternalSerial(), SetXMLMagCal(), SetXMLMissionLimits(), SetXMLPayload(), SetXMLPayload1(), SetXMLPayload2(), SetXMLSensorError(), SetXMLSurfaces(), and WriteXMLDataContent().
UInt32 GetXMLEuler (xmlDocPtr doc, float Euler[NAXIS], float IMUtoAnt[N3D], float IMUtoAnt2[N3D], std::string & Error, const float * pEulerToCompare, const float * pIMUtoAntToCompare, const float * pIMUtoAnt2ToCompare)
Update the euler angles and IMU to antenna offsets with data from the node tree.
Parameters
doc is the XML document config tree.
Euler is an array of euler angles
IMUtoAnt is an array of position offsets for the primary GPS antenna relative to the IMU.
IMUtoAnt2 is an array of position offsets for the secondary GPS antenna relative to the IMU.
Error references space to receive an error string.
pEulerToCompare is an optional parameter that will be compared to the values in the doc
pIMUtoAntToCompare is an optional parameter that will be compared to the values found in the doc.
pIMUtoAnt2ToCompare is an optional parameter that will be compared to the values found in the doc.
Returns
The number of errors.
References FindNamedXMLChildNode(), PITCH_AXIS, ReadXMLDataContent(), ROLL_AXIS, SubtractAngles(), X_AXIS, Y_AXIS, YAW_AXIS, and Z_AXIS.
UInt32 GetXMLExternalSerial (xmlDocPtr doc, ExternalSerial_t * pSerial, std::string & Error, const ExternalSerial_t * pToCompare)
Update the ExternalSerial structure with data from the node tree.
Parameters
doc is the XML document config tree.
pSerial points to a structure to receive the serial configuration
Error references space to receive an error string.
pToCompare is an optional argument that will be compared to the ExternalSerial in the doc
Returns
The number of errors.
References FindNamedXMLChildNode(), and ReadXMLDataContent().
UInt32 GetXMLMagCal (xmlDocPtr doc, float HardIronErr[N3D], float ScaleFactErr[N3D], std::string & Error, const float * pHardIronToCompare, const float * pScaleFactToCompare)
Update the magnetic calibration structure with data from the node tree.
Parameters
doc is the XML document config tree.
HardIronErr is a 3x1 array of hard iron errors in body-axes.
ScaleFactErr is a 3x1 array of scale factor errors in body-axes.
Error references space to receive an error string.
pHardIronToCompare is an optional parameter that will be compared to the value in the doc
pScaleFactToCompare is an optional parameter that will be compared to the value in the doc
Returns
The number of errors.
References FindNamedXMLChildNode(), ReadXMLDataContent(), X_AXIS, Y_AXIS, and Z_AXIS.
UInt32 GetXMLMissionLimits (xmlDocPtr doc, MissionLimits_t * pMissionLimits, std::string & Error, const MissionLimits_t * pToCompare)
Update the mission limits structure with data from the node tree..
Parameters
doc is the XML document config tree.
pMissionLimits points to a structure of mission limits.
Error references space to receive an error string
pToCompare is an optional argument that will be compared to the MissionLimits in the doc
Returns
The number of errors, zero if none.
References MissionLimits_t::AltitudeMax, MissionLimits_t::AltitudeMin, MissionLimits_t::AutolandWaypoint, Failure_t::BoundaryCausesFT, Failure_t::CommCausesFT, MissionLimits_t::CommTimeout, MissionLimits_t::CritFuel, Failure_t::CritFuelCausesAbort, Failure_t::EngineKillsDeadman, MissionLimits_t::Failure, FindNamedXMLChildNode(), Failure_t::FlightTimeandCommCauseLanding, MissionLimits_t::FlightTimeout, Failure_t::FTCausesAbort, Failure_t::FTCausesAeroTerm, Failure_t::FTCausesParachute, Failure_t::FTDropsDeadman, Failure_t::FTKillsEngine, Failure_t::GPSandCommCauseFT, Failure_t::GPSCausesFT, MissionLimits_t::GPSTimeout, Failure_t::HighAltitudeCausesFT, Failure_t::IgnoreTimeoutsInPrelaunch, MissionLimits_t::LostCommWaypoint, Failure_t::LowAltitudeCausesFT, Failure_t::LowFuelCausesAutoLand, MissionLimits_t::MinFuel, MissionLimits_t::PilotTimeout, and ReadXMLDataContent().
UInt32 GetXMLPayload (xmlDocPtr doc, ExternalIO_t ExternalIO[NUM_EXTERNAL_IO_PINS], UInt32 * pSampleTime, std::string & Error, const ExternalIO_t * pExternalIOToCompare, const UInt32 * pSampleTimeToCompare)
Update the external IO array with data from the node tree. This function updates all of the digital and analog lines.
Parameters
doc is the XML document config tree.
ExternalIO is an array to receive the external IO configrations
pSampleTime points to space to receive the number of nanoseconds between samples
Error references space to receive an error string.
pExternalIOToCompare is an optional argument that will be compared to the ExternalIO in the doc
pSampleTimeToCompare is an optional argument that will be compared to the SampleTime in the doc
Returns
The number of errors
References FindNamedXMLChildNode(), and ReadXMLDataContent().
UInt32 GetXMLPayload1 (xmlDocPtr doc, ExternalIO_t ExternalIO[NUM_PAYLOAD_IO_PINS], UInt32 * pSampleTime, std::string & Error)
Update the external IO array with data from the node tree. This function updates only the configuration of the 12 digital I/O lines existing on the standard Piccolo / Piccolo Plus.
Parameters
doc is the XML document config tree.
ExternalIO is an array to receive the external IO configrations
pSampleTime points to space to receive the number of nanoseconds between samples
Error references space to receive an error string.
Returns
The number of errors.
References FindNamedXMLChildNode(), NUM_PAYLOAD_IO_PINS, and ReadXMLDataContent().
UInt32 GetXMLPayload2 (xmlDocPtr doc, ExternalIO_t ExternalIO[NUM_PAYLOAD2_IO_PINS], UInt32 * pSampleTime, std::string & Error)
Update the external IO array with data from the node tree. This function updates only the configuration of the 8 additional digital and analog lines existing on the Piccolo II.
Parameters
doc is the XML document config tree.
ExternalIO is an array to receive the external IO configrations
pSampleTime points to space to receive the number of nanoseconds between samples
Error references space to receive an error string.
Returns
The number of errors.
References FindNamedXMLChildNode(), NUM_PAYLOAD2_IO_PINS, NUM_PAYLOAD_IO_PINS, and ReadXMLDataContent().
UInt32 GetXMLSensorError (xmlDocPtr doc, SensorErrorData_t * pSensorError, std::string & Error, const SensorErrorData_t * pSensorErrorCmp)
Read and/or compare sensor error information from an xml file.
Parameters
doc is the XML document config tree.
pSensorError points to space to receive the errors.
Error references space to receive an error string.
pSensorErrorCmd is an optional parameter that will be compared to the value in the doc.
Returns
The number of errors.
References SensorErrorData_t::AGLOffset, SensorErrorData_t::AllowControllerTAS, SensorErrorData_t::DisableAlign, SensorErrorData_t::DisableAlt, SensorErrorData_t::DisableInternalMag, SensorErrorData_t::DisableSBAS, SensorErrorData_t::DisableVDown, FindNamedXMLChildNode(), SensorErrorData_t::MagOnlyInAHRS, SensorErrorData_t::OATfromStandardAtmo, SensorErrorData_t::PositionCorr, ReadXMLDataContent(), SensorErrorData_t::TASCutoff, SensorErrorData_t::TASFilterWindow, and SensorErrorData_t::TempRise.
UInt32 GetXMLSurfaces (xmlDocPtr doc, ActuatorTable_t Table[NUM_SURFACES], UInt8 Types[NUM_SURFACES], UInt8 Virtual[NUM_SURFACES], UInt8 Fast[NUM_SURFACES], std::string & Error, const ActuatorTable_t * pTableToCompare, const UInt8 * pTypesToCompare, const UInt8 * pVirtualToCompare, const UInt8 * pFastToCompare)
Update the surface structure with data from the node tree.
Parameters
doc is the XML document config tree.
Table points to an array of control surface calibration data.
Error references space to receive an error string.
Returns
The number of errors
References ELEVATOR, FindNamedXMLChildNode(), LEFT_AILERON, LEFT_FLAP, LEFT_THROTTLE, NOSEGEAR, NUM_ACTUATOR_POINTS, NUM_SURFACES, ReadXMLDataContent(), RIGHT_AILERON, RIGHT_FLAP, RIGHT_THROTTLE, RUDDER, and ActuatorTable_t::Width.
xmlDocPtr OpenXMLConfig (const char * filename)
Load up a Piccolo XML config file and verify its contents. The caller is responsible for freeing the docuemnt tree by calling xmlFreeDoc().
Parameters
filename is the name of the XML file.
Returns
A pointer to the XML doc tree, or NULL if an error occurred
References OpenXMLNamedDoc().
xmlDocPtr OpenXMLNamedDoc (const char * filename, const char * name)
Load a document tree with specific name from an XML file. The caller is responsible for freeing the document tree by calling xmlFreeDoc().
Parameters
filename is the name of the XML file.
Returns
A pointer to the XML doc tree, or NULL if an error occurred
Referenced by OpenXMLConfig().
BOOL ReadXMLDataContent (xmlDocPtr doc, xmlNodePtr root, const char * name, float * pValue)
Read the numeric contents of an XML element
Parameters
doc identifies a previously opened XML document
root is XML node pointer which is a parent to the desired node
name is a string which identifies the node of interest
pValue points to space to receive the data.
Returns
TRUE if the child node was found and data returned.
References FindNamedXMLChildNode().
Referenced by GetXMLEuler(), GetXMLExternalSerial(), GetXMLMagCal(), GetXMLMissionLimits(), GetXMLPayload(), GetXMLPayload1(), GetXMLPayload2(), GetXMLSensorError(), and GetXMLSurfaces().
BOOL ReadXMLDataContent (xmlDocPtr doc, xmlNodePtr root, const char * name, double * pValue)
Read the numeric contents of an XML element
Parameters
doc identifies a previously opened XML document
root is XML node pointer which is a parent to the desired node
name is a string which identifies the node of interest
pValue points to space to receive the data.
Returns
TRUE if the child node was found and data returned.
References FindNamedXMLChildNode().
BOOL ReadXMLDataContent (xmlDocPtr doc, xmlNodePtr root, const char * name, UInt8 * pValue)
Read the numeric contents of an XML element
Parameters
doc identifies a previously opened XML document
root is XML node pointer which is a parent to the desired node
name is a string which identifies the node of interest
pFloat points to space to receive the data.
Returns
TRUE if the child node was found and data returned.
References FindNamedXMLChildNode().
BOOL ReadXMLDataContent (xmlDocPtr doc, xmlNodePtr root, const char * name, UInt16 * pValue)
Read the numeric contents of an XML element
Parameters
doc identifies a previously opened XML document
root is XML node pointer which is a parent to the desired node
name is a string which identifies the node of interest
pFloat points to space to receive the data.
Returns
TRUE if the child node was found and data returned.
References FindNamedXMLChildNode().
BOOL ReadXMLDataContent (xmlDocPtr doc, xmlNodePtr root, const char * name, UInt32 * pValue)
Read the numeric contents of an XML element
Parameters
doc identifies a previously opened XML document
root is XML node pointer which is a parent to the desired node
name is a string which identifies the node of interest
pFloat points to space to receive the data.
Returns
TRUE if the child node was found and data returned.
References FindNamedXMLChildNode().
BOOL ReadXMLDataContent (xmlDocPtr doc, xmlNodePtr root, const char * name, SInt8 * pValue)
Read the numeric contents of an XML element
Parameters
doc identifies a previously opened XML document
root is XML node pointer which is a parent to the desired node
name is a string which identifies the node of interest
pFloat points to space to receive the data.
Returns
TRUE if the child node was found and data returned.
References FindNamedXMLChildNode().
BOOL ReadXMLDataContent (xmlDocPtr doc, xmlNodePtr root, const char * name, SInt16 * pValue)
Read the numeric contents of an XML element
Parameters
doc identifies a previously opened XML document
root is XML node pointer which is a parent to the desired node
name is a string which identifies the node of interest
pFloat points to space to receive the data.
Returns
TRUE if the child node was found and data returned.
References FindNamedXMLChildNode().
BOOL ReadXMLDataContent (xmlDocPtr doc, xmlNodePtr root, const char * name, SInt32 * pValue)
Read the numeric contents of an XML element
Parameters
doc identifies a previously opened XML document
root is XML node pointer which is a parent to the desired node
name is a string which identifies the node of interest
pFloat points to space to receive the data.
Returns
TRUE if the child node was found and data returned.
References FindNamedXMLChildNode().
BOOL SetXMLEuler (xmlDocPtr doc, const float Euler[NAXIS], const float IMUtoAnt[N3D], const float IMUtoAnt2[N3D])
Update the node tree with data from the sensor calibration structure. If the nodes don't exist this function will create them.
Parameters
doc is the XML document config tree.
Euler is an array of Euler angle rotations.
IMUtoAnt is an array that holds the position offset of the primary GPS antenna relative to the IMU.
IMUtoAnt2 is an array that holds the position offset of the secondary GPS antenna relative to the IMU.
Returns
FALSE if an errory occurs, else TRUE.
References AddIndentingElements(), FindOrCreateNamedXMLChildNode(), PITCH_AXIS, ROLL_AXIS, X_AXIS, Y_AXIS, YAW_AXIS, and Z_AXIS.
BOOL SetXMLExternalSerial (xmlDocPtr doc, const ExternalSerial_t * pSerial)
Update the ExternalSerial node tree with data from the structure. If the nodes don't exist this function will create them.
Parameters
doc is the XML document config tree.
pSerial points to a structure containing the serial configuration
Returns
FALSE if an errory occurs, else TRUE.
References AddIndentingElements(), and FindOrCreateNamedXMLChildNode().
BOOL SetXMLMagCal (xmlDocPtr doc, const float HardIronErr[N3D], const float ScaleFactErr[N3D])
Update the magnetic calibration node tree with data from the passed structure. If the nodes don't exist this function will create them.
Parameters
doc is the XML document config tree.
HardIronErr is a 3x1 array of hard iron errors in body-axes.
ScaleFactErr is a 3x1 array of scale factor errors in body-axes.
Returns
FALSE if an errory occurs, else TRUE.
References AddIndentingElements(), FindOrCreateNamedXMLChildNode(), X_AXIS, Y_AXIS, and Z_AXIS.
BOOL SetXMLMissionLimits (xmlDocPtr doc, const MissionLimits_t * pMissionLimits)
Update the mission limits node tree with data from the limits structure. If the nodes don't exist this function will create them.
Parameters
doc is the XML document config tree.
pMissionLimits points to a structure of mission limits.
Returns
FALSE if an errory occurs, else TRUE.
References AddIndentingElements(), MissionLimits_t::AltitudeMax, MissionLimits_t::AltitudeMin, MissionLimits_t::AutolandWaypoint, Failure_t::BoundaryCausesFT, Failure_t::CommCausesFT, MissionLimits_t::CommTimeout, MissionLimits_t::CritFuel, Failure_t::CritFuelCausesAbort, Failure_t::EngineKillsDeadman, MissionLimits_t::Failure, FindOrCreateNamedXMLChildNode(), Failure_t::FlightTimeandCommCauseLanding, MissionLimits_t::FlightTimeout, Failure_t::FTCausesAbort, Failure_t::FTCausesAeroTerm, Failure_t::FTCausesParachute, Failure_t::FTDropsDeadman, Failure_t::FTKillsEngine, Failure_t::GPSandCommCauseFT, Failure_t::GPSCausesFT, MissionLimits_t::GPSTimeout, Failure_t::HighAltitudeCausesFT, Failure_t::IgnoreTimeoutsInPrelaunch, MissionLimits_t::LostCommWaypoint, Failure_t::LowAltitudeCausesFT, Failure_t::LowFuelCausesAutoLand, MissionLimits_t::MinFuel, MissionLimits_t::PilotTimeout, and WriteXMLDataContent().
BOOL SetXMLPayload (xmlDocPtr doc, const ExternalIO_t ExternalIO[NUM_EXTERNAL_IO_PINS], UInt32 SampleTime)
Update the payload node tree with data from the external IO structure. If the nodes don't exist this function will create them. This function updates all of the digital and analog lines.
Parameters
doc is the XML document config tree.
ExternalIO is an array of external IO configrations
SampleTime is the number of nanoseconds between samples
Returns
FALSE if an errory occurs, else TRUE.
References AddIndentingElements(), and FindOrCreateNamedXMLChildNode().
BOOL SetXMLPayload1 (xmlDocPtr doc, const ExternalIO_t ExternalIO[NUM_PAYLOAD_IO_PINS], UInt32 SampleTime)
Update the payload node tree with data from the external IO structure. If the nodes don't exist this function will create them. This function updates only the configuration of the 12 digital I/O lines existing on Piccolo and Piccolo Plus.
Parameters
doc is the XML document config tree.
ExternalIO is an array of external IO configrations
SampleTime is the number of nanoseconds between samples
Returns
FALSE if an errory occurs, else TRUE.
References AddIndentingElements(), FindOrCreateNamedXMLChildNode(), and NUM_PAYLOAD_IO_PINS.
BOOL SetXMLPayload2 (xmlDocPtr doc, const ExternalIO_t ExternalIO[NUM_PAYLOAD2_IO_PINS], UInt32 SampleTime)
Update the payload node tree with data from the external IO structure. If the nodes don't exist this function will create them. This function updates only the configuration of the 8 additional digital and analog lines existing on Piccolo II.
Parameters
doc is the XML document config tree.
ExternalIO is an array of external IO configrations
SampleTime is the number of nanoseconds between samples
Returns
FALSE if an errory occurs, else TRUE.
References AddIndentingElements(), FindOrCreateNamedXMLChildNode(), NUM_PAYLOAD2_IO_PINS, and NUM_PAYLOAD_IO_PINS.
BOOL SetXMLSensorError (xmlDocPtr doc, const SensorErrorData_t * pSensorError)
Write out the SensorError data.
Parameters
doc is the XML document config tree.
pSensorError points to the data to write.
Returns
FALSE if an errory occurs, else TRUE.
References AddIndentingElements(), SensorErrorData_t::AGLOffset, SensorErrorData_t::AllowControllerTAS, SensorErrorData_t::DisableAlign, SensorErrorData_t::DisableAlt, SensorErrorData_t::DisableInternalMag, SensorErrorData_t::DisableSBAS, SensorErrorData_t::DisableVDown, FindOrCreateNamedXMLChildNode(), SensorErrorData_t::MagOnlyInAHRS, SensorErrorData_t::OATfromStandardAtmo, SensorErrorData_t::PositionCorr, SensorErrorData_t::TASCutoff, SensorErrorData_t::TASFilterWindow, and SensorErrorData_t::TempRise.
BOOL SetXMLSurfaces (xmlDocPtr doc, const ActuatorTable_t Table[NUM_SURFACES], const UInt8 Types[NUM_SURFACES], const UInt8 Virtual[NUM_SURFACES], const UInt8 Fast[NUM_SURFACES])
Update the surfaces node tree with data from the surfaces structure. If the nodes don't exist this function will create them.
Parameters
doc is the XML document config tree.
ActuatorTable points to an array of control surface calibration data
Types points to an array of control surface actuator types.
Virtual points to an array of virtual control surfaces flags.
Fast points to an array of fast control surfaces flags.
Returns
FALSE if a bad document, else TRUE.
References AddIndentingElements(), FindOrCreateNamedXMLChildNode(), NUM_ACTUATOR_POINTS, and NUM_SURFACES.
BOOL WriteXMLDataContent (xmlNodePtr root, const char * name, char * content)
Write the numeric contents of an XML element. If the element does exist this function will create it.
Parameters
root is XML node pointer which is a parent to the desired node
name is a string which identifies the node of interest
content is the string to write into the XML element.
Returns
TRUE if the child node was found and data returned.
References FindOrCreateNamedXMLChildNode().
Referenced by SetXMLMissionLimits().
BOOL WriteXMLDataContent (xmlNodePtr root, const char * name, double Value)
Write the numeric contents of an XML element. If the element does exist this function will create it.
Parameters
root is XML node pointer which is a parent to the desired node
name is a string which identifies the node of interest
Value is a double-precision floating-point number.
Returns
TRUE if the child node was found and data written.
References FindOrCreateNamedXMLChildNode().
BOOL WriteXMLDataContent (xmlNodePtr root, const char * name, double Value, int precision)
Write the numeric contents of an XML element. If the element does exist this function will create it.
Parameters
root is XML node pointer which is a parent to the desired node
name is a string which identifies the node of interest
Value is a double-precision floating-point number.
precision is the number of digits after the decimal point to print.
Returns
TRUE if the child node was found and data written.
References FindOrCreateNamedXMLChildNode().
BOOL WriteXMLDataContent (xmlNodePtr root, const char * name, float Value)
Write the numeric contents of an XML element. If the element does exist this function will create it.
Parameters
root is XML node pointer which is a parent to the desired node
name is a string which identifies the node of interest
Value is a single-precision floating-point number.
Returns
TRUE if the child node was found and data written.
References FindOrCreateNamedXMLChildNode().
BOOL WriteXMLDataContent (xmlNodePtr root, const char * name, UInt8 Value)
Write the numeric contents of an XML element. If the element does exist this function will create it.
Parameters
root is XML node pointer which is a parent to the desired node
name is a string which identifies the node of interest
Value is a 1-byte unsigned integer number.
Returns
TRUE if the child node was found and data written.
References FindOrCreateNamedXMLChildNode().
BOOL WriteXMLDataContent (xmlNodePtr root, const char * name, UInt16 Value)
Write the numeric contents of an XML element. If the element does exist this function will create it.
Parameters
root is XML node pointer which is a parent to the desired node
name is a string which identifies the node of interest
Value is a 2-byte unsigned integer number.
Returns
TRUE if the child node was found and data written.
References FindOrCreateNamedXMLChildNode().
BOOL WriteXMLDataContent (xmlNodePtr root, const char * name, UInt32 Value)
Write the numeric contents of an XML element. If the element does exist this function will create it.
Parameters
root is XML node pointer which is a parent to the desired node
name is a string which identifies the node of interest
Value is a 4-byte unsigned integer number.
Returns
TRUE if the child node was found and data written.
References FindOrCreateNamedXMLChildNode().