Communications SDK: Queue.h File Reference
Queue.h File Reference
First in first out ring buffer queues for 8-bit data.
#include "Types.h"
Classes
struct Queue_t
Functions
Queue_t * CreateQ (UInt32 Size)
void DestroyQ (Queue_t *pQ)
SInt16 DeQ (Queue_t *pQ)
SInt16 DeQFast (Queue_t *pQ)
UInt32 BlockDeQ (Queue_t *pQ, UInt8 *pData, UInt32 Size)
UInt32 BlockDeQFast (Queue_t *pQ, UInt8 *pData, UInt32 Size)
UInt32 ReverseDeQ (Queue_t *pQ, UInt32 Size)
UInt32 ReverseDeQFast (Queue_t *pQ, UInt32 Size)
void EnQFast (Queue_t *pQ, UInt8 Data)
void EnQSuperFast (Queue_t *pQ, UInt8 Data)
void EnQ (Queue_t *pQ, UInt8 Data)
UInt32 BlockEnQ (Queue_t *pQ, const UInt8 *pData, UInt32 Size)
UInt32 BlockEnQFast (Queue_t *pQ, const UInt8 *pData, UInt32 Size)
UInt32 BlockQTransfer (Queue_t *pRxQ, Queue_t *pTxQ, UInt32 Size)
UInt32 BlockQTransferFast (Queue_t *pRxQ, Queue_t *pTxQ, UInt32 Size)
void BlockEnQSmall (Queue_t *pQ, const UInt8 *pData, UInt32 Size)
void BlockEnQSmallFast (Queue_t *pQ, const UInt8 *pData, UInt32 Size)
UInt32 ReverseEnQ (Queue_t *pQ, UInt32 Size)
UInt32 ReverseEnQFast (Queue_t *pQ, UInt32 Size)
UInt32 QAvailable (Queue_t *pQ)
UInt32 QAvailableFast (Queue_t *pQ)
UInt32 QHolding (Queue_t *pQ)
UInt32 QHoldingFast (Queue_t *pQ)
BOOL IsQFull (Queue_t *pQ)
BOOL IsQFullFast (Queue_t *pQ)
void ResetQ (Queue_t *pQ)
void ResetQEx (Queue_t *pQ, UInt32 Value)
UInt32 BackupQueueIndex (UInt32 In, UInt32 Out, UInt32 Size, UInt32 Backup)
Detailed Description
First in first out ring buffer queues for 8-bit data.
The queue module defines a basic ring buffer format and functions for adding data (EnQ) and removing data (DeQ).
Function Documentation
UInt32 BlockDeQ (Queue_t * pQ, UInt8 * pData, UInt32 Size)
Return a block of the oldest data from the passed queue. This routine uses block memory transfers and is faster than calling DeQ multiple times. The actual number of bytes dequeued is returned. This may be less than Size if the queue does not hold enough bytes to complete the transaction. If the queue pointer is invalid this function returns 0;
Parameters
pQ points to a queue that was previously created with CreateQ().
pData points to a buffer to receive the data.
Size is the number of bytes to dequeue.
Returns
The number of bytes dequeued.
References BlockDeQFast().
Referenced by CctSocket::read(), ReadBlockQuick(), and CctSocket::write().
UInt32 BlockDeQFast (Queue_t * pQ, UInt8 * pData, UInt32 Size)
Return a block of the oldest data from the passed queue. This routine uses block memory transfers and is faster than calling DeQ() multiple times. The actual number of bytes dequeued is returned. This may be less than Size if the queue does not hold enough bytes to complete the transaction. This function is faster than BlockDeQ() since it does not check for a valid queue pointer.
Parameters
pQ points to a queue that was previously created with CreateQ().
pData points to a buffer to receive the data.
Size is the number of bytes to dequeue.
Returns
The number of bytes dequeued.
References Queue_t::In, Queue_t::Out, Queue_t::pBuf, and Queue_t::Size.
Referenced by BlockDeQ(), LookForCANPacket(), LookForGimbalPacketInQueue(), LookForSimplePacket(), and LookForStreamPacketInQueue().
UInt32 BlockEnQ (Queue_t * pQ, const UInt8 * pData, UInt32 Size)
Add a block of bytes to the queue. This function is faster than calling EnQ multiple times since it performs block memory transfers. The block transfer will be truncated to fit within the available space on the queue. The remaining free space on the queue is returned. This function incurs significant overhead and should only be used when large chunks of data are being moved. Small blocks of data should be moved using BlockEnQSmall()
Parameters
pQ points to a queue that was previously created with CreateQ().
pData points to a buffer of data to be added to the queued.
Size is the amount of data to add.
Returns
The number of bytes enqueued.
References BlockEnQFast().
Referenced by QueueDataForTransmit(), CctSocket::read(), and CctSocket::write().
UInt32 BlockEnQFast (Queue_t * pQ, const UInt8 * pData, UInt32 Size)
Add a block of bytes to the queue. This function is faster than calling EnQ multiple times since it performs block memory transfers. The block transfer will be truncated to fit within the available space on the queue. The remaining free space on the queue is returned. This function incurs significant overhead and should only be used when large chunks of data are being moved. Small blocks of data should be moved using BlockEnQSmall(). This function is faster than BlockEnQ() since it does not check if the queue pointer is valid.
Parameters
pQ points to a queue that was previously created with CreateQ().
pData points to a buffer of data to be added to the queued.
Size is the amount of data to add.
Returns
The number of bytes enqueued.
References Queue_t::In, Queue_t::pBuf, QAvailableFast(), and Queue_t::Size.
Referenced by BlockEnQ().
void BlockEnQSmall (Queue_t * pQ, const UInt8 * pData, UInt32 Size)
Add a small block of bytes to the queue.
Parameters
pQ points to a queue that was previously created with CreateQ().
pData points to a buffer of data to be added to the queued.
Size is the amount of data to add.
References BlockEnQSmallFast().
void BlockEnQSmallFast (Queue_t * pQ, const UInt8 * pData, UInt32 Size)
Add a small block of bytes to the queue. This function is faster than BlockEnQSmall() since it does not check if the queue pointer is valid.
Parameters
pQ points to a queue that was previously created with CreateQ().
pData points to a buffer of data to be added to the queued.
Size is the amount of data to add.
References EnQSuperFast().
Referenced by BlockEnQSmall().
UInt32 BlockQTransfer (Queue_t * pRxQ, Queue_t * pTxQ, UInt32 Size)
Move data directly from one queue to another.
Parameters
pRxQ gets new data.
pTxQ gives data up.
Size is the amount of data to transfer.
Returns
The amount of data transferred.
References BlockQTransferFast().
UInt32 BlockQTransferFast (Queue_t * pRxQ, Queue_t * pTxQ, UInt32 Size)
Move data directly from one queue to another. The data move will be truncated according to the space available in pRxQ and data held in pTxQ.
Parameters
pRxQ gets new data, must not be NULL.
pTxQ gives data up, must not be NULL.
Size is the amount of data to transfer.
Returns
The amount of data transferred.
References Queue_t::In, Queue_t::Out, Queue_t::pBuf, QAvailableFast(), QHoldingFast(), and Queue_t::Size.
Referenced by BlockQTransfer().
Queue_t* CreateQ (UInt32 Size)
Create a queue by dynamically allocating memory for the queue structure and buffer; and initializing In, Out, and Size elements of the queue.
Parameters
Size is one more than the number of elements the queue buffer can hold
Returns
A pointer to the queue. NULL is returned if the queue could not be allocated.
References Queue_t::In, Queue_t::Out, Queue_t::pBuf, and Queue_t::Size.
Referenced by CctSocket::open(), OpenCOMM(), OpenCOMMDev(), and OpenStream().
SInt16 DeQ (Queue_t * pQ)
Return the oldest 8 bit data in the queue, removing the data from the queue. If the queue is empty -1 is returned. This function will return -1 if the queue pointer is invalid.
Parameters
pQ points to a queue that was previously created with CreateQ()
Returns
The oldest data in the queue, or -1 if the queue is empty.
References DeQFast().
Referenced by DeQFast(), and ReadByteQuick().
SInt16 DeQFast (Queue_t * pQ)
Return the oldest 8 bit data in the queue, removing the data from the queue. If the queue is empty -1 is returned. This function is faster than DeQ() because it does not check for a valid queue pointer
Parameters
pQ points to a queue that was previously created with CreateQ()
Returns
The oldest data in the queue, or -1 if the queue is empty.
References DeQ(), Queue_t::In, Queue_t::Out, Queue_t::pBuf, and Queue_t::Size.
Referenced by DeQ(), LookForCANPacket(), LookForGimbalPacketInQueue(), LookForSimplePacket(), LookForStreamPacketInQueue(), and WriteFromQueueQuick().
void DestroyQ (Queue_t * pQ)
Free the memory associated with a queue.
Parameters
pQ points to a queue that was previously created with CreateQ.
Referenced by CctSocket::close(), CloseCOMM(), CloseStream(), and OpenStream().
void EnQ (Queue_t * pQ, UInt8 Data)
Add a byte to the queue. The remaining free space on the queue is returned.
Parameters
pQ points to a queue that was previously created with CreateQ().
Data is the new data to add.
References EnQSuperFast().
void EnQFast (Queue_t * pQ, UInt8 Data)
Add a byte to the queue. This function is faster than EnQ() since it doesn't return the free space remaining on the queue.
Parameters
pQ points to a queue that was previously created with CreateQ().
Data is the new data to add.
References EnQSuperFast().
Referenced by EnQSuperFast().
void EnQSuperFast (Queue_t * pQ, UInt8 Data)
Add a byte to the queue. This function is faster than EnQFast() since it doesn't check for a valid queue pointer.
Parameters
pQ points to a queue that was previously created with CreateQ().
Data is the new data to add.
References EnQFast(), Queue_t::In, Queue_t::Out, Queue_t::pBuf, and Queue_t::Size.
Referenced by BlockEnQSmallFast(), EnQ(), and EnQFast().
BOOL IsQFull (Queue_t * pQ)
Return TRUE if a queue is full.
Parameters
pQ points to a queue that was previously created with CreateQ()
Returns
TRUE if the queue is full, else FALSE
References IsQFullFast().
BOOL IsQFullFast (Queue_t * pQ)
Return TRUE if a queue is full. This function is faster than IsQFull() since it does not check if the queue pointer is valid.
Parameters
pQ points to a queue that was previously created with CreateQ()
Returns
TRUE if the queue is full, else FALSE
References QHoldingFast(), and Queue_t::Size.
Referenced by IsQFull().
UInt32 QAvailable (Queue_t * pQ)
Return the amount of space available on the queue. An empty queue will have Size-1 bytes available. This is because 1 byte of the buffer is used for overflow detection.
Parameters
pQ points to a queue that was previously created with CreateQ()
Returns
The space available on the queue.
References QAvailableFast().
Referenced by CctSocket::read(), and CctSocket::write().
UInt32 QAvailableFast (Queue_t * pQ)
Return the amount of space available on the queue. An empty queue will have Size-1 bytes available. This is because 1 byte of the buffer is used for overflow detection. This function is faster than QAvailable() since it does not check if the queue pointer is valid
Parameters
pQ points to a queue that was previously created with CreateQ()
Returns
The space available on the queue.
References Queue_t::In, Queue_t::Out, and Queue_t::Size.
Referenced by BlockEnQFast(), BlockQTransferFast(), QAvailable(), and ReverseDeQFast().
UInt32 QHolding (Queue_t * pQ)
Return the amount of data on the queue. A full queue will hold Size-1 bytes available. This is because 1 byte of the buffer is used for overflow detection. Zero will be returned if the queue is invalid
Parameters
pQ points to a queue that was previously created with CreateQ()
Returns
The amount of data on the queue.
References QHoldingFast().
Referenced by RxQHolding(), TxQAvailable(), and CctSocket::write().
UInt32 QHoldingFast (Queue_t * pQ)
Return the amount of data on the queue. A full queue will hold Size-1 bytes available. This is because 1 byte of the buffer is used for overflow detection. This function is faster than QHolding() because it does not check for a valid queue pointer
Parameters
pQ points to a queue that was previously created with CreateQ()
Returns
The amount of data on the queue.
References Queue_t::In, Queue_t::Out, and Queue_t::Size.
Referenced by BlockQTransferFast(), IsQFullFast(), QHolding(), ReverseEnQFast(), and WriteFromQueueQuick().
void ResetQ (Queue_t * pQ)
Reset the queue index variables, discarding any data in the queue
Parameters
pQ points to a queue that was previously created with CreateQ().
References Queue_t::In, and Queue_t::Out.
Referenced by ResetNetworkBuffers().
void ResetQEx (Queue_t * pQ, UInt32 Value)
Reset the queue index variables, discarding any data in the queue
Parameters
pQ points to a queue that was previously created with CreateQ().
Value is the value that the In an Out index variables will be assigned. Note that the actual value of In and Out will be ValuepQ->Size.
References Queue_t::In, Queue_t::Out, and Queue_t::Size.
UInt32 ReverseDeQ (Queue_t * pQ, UInt32 Size)
Reverse the DeQ process, effectively putting bytes back on the queue. All we are actually doing is moving the out pointer backwards so that it will return bytes we've already DeQueued. The queue will only reverse up to the newest data.
Parameters
pQ points to a queue that was previously created with CreateQ().
Size is the number of bytes to reverse.
Returns
The number of bytes reversed.
References ReverseDeQFast().
Referenced by ReverseSerialRxQueue().
UInt32 ReverseDeQFast (Queue_t * pQ, UInt32 Size)
Reverse the DeQ process, effectively putting bytes back on the queue. All we are actually doing is moving the out pointer backwards so that it will return bytes we've already DeQueued. The queue will only reverse up to the newest data. This function is faster than ReverseDeQ() since it doesn't check for a valid queue pointer.
Parameters
pQ points to a queue that was previously created with CreateQ().
Size is the number of bytes to reverse.
Returns
The number of bytes reversed.
References Queue_t::Out, QAvailableFast(), and Queue_t::Size.
Referenced by LookForCANPacket(), LookForSimplePacket(), LookForStreamPacketInQueue(), and ReverseDeQ().
UInt32 ReverseEnQ (Queue_t * pQ, UInt32 Size)
Reverse the EnQ process, effectively destroying the oldest bytes on the queue. All we are actually doing is moving the in pointer backwards so that it loses bytes we've queued. The queue will only reverse up to the oldest data.
Parameters
pQ points to a queue that was previously created with CreateQ().
Size is the number of bytes to reverse.
Returns
The number of bytes reversed.
References ReverseEnQFast().
UInt32 ReverseEnQFast (Queue_t * pQ, UInt32 Size)
Reverse the EnQ process, effectively destroying the oldest bytes on the queue. All we are actually doing is moving the in pointer backwards so that it loses bytes we've queued. The queue will only reverse up to the oldest data. This function is faster than ReverseEnQ() since it does not check if the queue pointer is valid
Parameters
pQ points to a queue that was previously created with CreateQ().
Size is the number of bytes to reverse.
Returns
The number of bytes reversed.
References Queue_t::In, QHoldingFast(), and Queue_t::Size.
Referenced by ReverseEnQ().