Communications SDK: Rotations.h File Reference
Rotations.h File Reference
Euler angle rotations.
#include "Indices.h"
#include "Types.h"
Functions
void EulerAngleLimits (double Euler[NAXIS])
void CreateRotation (double Rotation[N3D][N3D], double Yaw, double Pitch, double Roll)
void CreateRotationEx (double Rotation[N3D][N3D], double Yaw, double Pitch, double Roll, UInt8 Order[N3D])
void CreateYawRotation (double Rotation[N3D][N3D], double Yaw)
void CreatePitchRotation (double Rotation[N3D][N3D], double Pitch)
void CreateRollRotation (double Rotation[N3D][N3D], double Roll)
void InvertRotation (const double Source[N3D][N3D], double Invert[N3D][N3D])
void ApplyRotation (const double S[N3D][N3D], const double Source[N3D], double Result[N3D])
void EulerAngleLimitsf (float Euler[NAXIS])
void CreateRotationf (float Rotation[N3D][N3D], float Yaw, float Pitch, float Roll)
void CreateRotationExf (float Rotation[N3D][N3D], float Yaw, float Pitch, float Roll, UInt8 Order[N3D])
void CreateYawRotationf (float Rotation[N3D][N3D], float Yaw)
void CreatePitchRotationf (float Rotation[N3D][N3D], float Pitch)
void CreateRollRotationf (float Rotation[N3D][N3D], float Roll)
void InvertRotationf (const float Source[N3D][N3D], float Invert[N3D][N3D])
void ApplyRotationf (const float S[N3D][N3D], const float Source[N3D], float Result[N3D])
Detailed Description
Euler angle rotations.
Function Documentation
void ApplyRotation (const double S[N3D][N3D], const double Source[N3D], double Result[N3D])
Rotate a three-dimensional vector according to the rotation matrix.
Parameters
S points to a rotation matrix earlier created by CreateRotation().
Source is the three-dimensional source vector.
Result points to space to receive the rotated vector.
References X_AXIS, Y_AXIS, and Z_AXIS.
void ApplyRotationf (const float S[N3D][N3D], const float Source[N3D], float Result[N3D])
Rotate a three-dimensional vector according to the rotation matrix.
Parameters
S points to a rotation matrix earlier created by CreateRotation().
Source is the three-dimensional source vector.
Result points to space to receive the rotated vector.
References CreateRotation(), EulerAngleLimits(), N3D, X_AXIS, Y_AXIS, and Z_AXIS.
void CreatePitchRotation (double Rotation[N3D][N3D], double Pitch)
Create a rotation matrix which supplies a single Euler pitchrotation.
Parameters
Rotation points to memory to receive the 3x3 rotation matrix.
Pitch is the Euler Pitch angle of the rotation in radians.
References X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by CreateRotationEx().
void CreatePitchRotationf (float Rotation[N3D][N3D], float Pitch)
Create a rotation matrix which supplies a single Euler pitchrotation.
Parameters
Rotation points to memory to receive the 3x3 rotation matrix.
Pitch is the Euler Pitch angle of the rotation in radians.
References X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by CreateRotationExf().
void CreateRollRotation (double Rotation[N3D][N3D], double Roll)
Create a rotation matrix which supplies a single Euler roll rotation.
Parameters
Rotation points to memory to receive the 3x3 rotation matrix.
Roll is the Euler Roll angle of the rotation in radians.
References X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by CreateRotationEx().
void CreateRollRotationf (float Rotation[N3D][N3D], float Roll)
Create a rotation matrix which supplies a single Euler roll rotation.
Parameters
Rotation points to memory to receive the 3x3 rotation matrix.
Roll is the Euler Roll angle of the rotation in radians.
References X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by CreateRotationExf().
void CreateRotation (double Rotation[N3D][N3D], double Yaw, double Pitch, double Roll)
Create a rotation matrix which can be used to apply the transformations through three euler angles Yaw, Pitch, and Roll in that order.
Parameters
Rotation points to memory to receive the 3x3 rotation matrix.
Yaw is the Euler Yaw angle of the rotation in radians.
Pitch is the Euler Pitch angle of the rotation in radians.
Roll is the Euler Roll angle of the rotation in radians.
References X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by ApplyRotationf().
void CreateRotationEx (double Rotation[N3D][N3D], double Yaw, double Pitch, double Roll, UInt8 Order[N3D])
Create a rotation matrix which can be used to apply the transformations through three euler angles Yaw, Pitch, and Roll. The rotation order is user specified
Parameters
Rotation points to memory to receive the 3x3 rotation matrix.
Yaw is the Euler Yaw angle of the rotation in radians.
Pitch is the Euler Pitch angle of the rotation in radians.
Roll is the Euler Roll angle of the rotation in radians.
Order gives the rotation order. ROLL_AXIS is 0, PITCH_AXIS is 1, and YAW_AXIS is 2.
References CreatePitchRotation(), CreateRollRotation(), CreateYawRotation(), MatrixMultiply(), N3D, PITCH_AXIS, ROLL_AXIS, and YAW_AXIS.
void CreateRotationExf (float Rotation[N3D][N3D], float Yaw, float Pitch, float Roll, UInt8 Order[N3D])
Create a rotation matrix which can be used to apply the transformations through three euler angles Yaw, Pitch, and Roll. The rotation order is user specified
Parameters
Rotation points to memory to receive the 3x3 rotation matrix.
Yaw is the Euler Yaw angle of the rotation in radians.
Pitch is the Euler Pitch angle of the rotation in radians.
Roll is the Euler Roll angle of the rotation in radians.
Order gives the rotation order. ROLL_AXIS is 0, PITCH_AXIS is 1, and YAW_AXIS is 2.
References CreatePitchRotationf(), CreateRollRotationf(), CreateYawRotationf(), MatrixMultiplyf(), N3D, PITCH_AXIS, ROLL_AXIS, and YAW_AXIS.
void CreateRotationf (float Rotation[N3D][N3D], float Yaw, float Pitch, float Roll)
Create a rotation matrix which can be used to apply the transformations through three euler angles Yaw, Pitch, and Roll.
Parameters
Rotation points to memory to receive the 3x3 rotation matrix.
Yaw is the Euler Yaw angle of the rotation in radians.
Pitch is the Euler Pitch angle of the rotation in radians.
Roll is the Euler Roll angle of the rotation in radians.
References X_AXIS, Y_AXIS, and Z_AXIS.
void CreateYawRotation (double Rotation[N3D][N3D], double Yaw)
Create a rotation matrix which supplies a single Euler pitch rotation.
Parameters
Rotation points to memory to receive the 3x3 rotation matrix.
Yaw is the Euler Yaw angle of the rotation in radians.
References X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by CreateRotationEx().
void CreateYawRotationf (float Rotation[N3D][N3D], float Yaw)
Create a rotation matrix which supplies a single Euler pitch rotation.
Parameters
Rotation points to memory to receive the 3x3 rotation matrix.
Yaw is the Euler Yaw angle of the rotation in radians.
References X_AXIS, Y_AXIS, and Z_AXIS.
Referenced by CreateRotationExf().
void EulerAngleLimits (double Euler[NAXIS])
Adjust the Euler angles so that they are in a sensible range. Do this by first noting that pitch cannot exceed -PI/2 to PI/2. Note also that when pitch does exceed one of these values the aircraft roll and yaw angles are changing. For example, consider a loop. As soon as the aircraft passes PI/2 pitch, it is on its back, and going the other way.
Parameters
Euler is an array of the three Euler angles in yaw, pitch, roll order.
References PHI, PSI, and THETA.
Referenced by ApplyRotationf().
void EulerAngleLimitsf (float Euler[NAXIS])
Adjust the Euler angles so that they are in a sensible range. Do this by first noting that pitch cannot exceed -PI/2 to PI/2. Note also that when pitch does exceed one of these values the aircraft roll and yaw angles are changing. For example, consider a loop. As soon as the aircraft passes PI/2 pitch, it is on its back, and going the other way.
Parameters
Euler is an array of the three Euler angles in yaw, pitch, roll order.
References PHI, PSI, and THETA.
void InvertRotation (const double Source[N3D][N3D], double Invert[N3D][N3D])
Create the rotation matrix which is the inverse of Source. Do this by applying the knowledge that the inverse of a rotation matrix is equal to its transverse. This function is written such that Source and Invert could be the same memory space.
Parameters
Source points to a rotation matrix earlier created by CreateRotation().
Invert poitns to space to receive the inverted rotation matrix.
void InvertRotationf (const float Source[N3D][N3D], float Invert[N3D][N3D])
Create the rotation matrix which is the inverse of Source. Do this by applying the knowledge that the inverse of a rotation matrix is equal to its transverse. This function is written such that Source and Invert could be the same memory space.
Parameters
Source points to a rotation matrix earlier created by CreateRotation().
Invert poitns to space to receive the inverted rotation matrix.