Communications SDK: Serial.h File Reference
Serial.h File Reference
Top level asynchronous serial interfaces for the MPC5XX.
#include "Types.h"
#include "Queue.h"
Classes
struct Serial_t
Macros
Asynchronous serial direction constants
#define RX_DIR 1
Receive direction.
#define TX_DIR 2
Transmit direciton.
#define BOTH_DIR (RX_DIR|TX_DIR)
Both directions.
Asynchronous serial parity constants
#define NO_PARITY 0
No parity checking.
#define ODD_PARITY 1
Odd parity checking.
#define EVEN_PARITY 2
Even parity checking.
Asynchronous serial flow control constants
#define FLOW_NONE 0x00000000
No flow control.
#define FLOW_SOFT 0x00000001
Software flow control XON/XOFF.
#define FLOW_HARD 0x00000002
Hardware flow control RTS/CTS.
Enumerations
enum {
NO_SERIAL_PORT, SCI_PORT, TPU_PORT, PC_PORT,
TCPCLIENT_PORT, TCPSERVER_PORT, IPMULTI_PORT, NUM_PORT_TYPES,
INVALID_PORT = 0xFF
}
enum SerialPortNames {
COM1 = 0, COM2, COM3, COM4,
COM5, COM6, COM7, COM8,
COM9, COM10, COM11, COM12,
COM13, COM14, COM15, COM16,
COM17, COM18, COM19, COM20,
COM21, COM22, COM23, COM24,
COM25, COM26, COM27, COM28,
COM29, COM30, COM31, COM32,
COM33, COM34, NUM_COM
}
Functions
BOOL OpenCOMM (UInt8 chan, UInt8 dir, UInt32 baud, UInt8 parity, UInt8 data, UInt32 flow, UInt32 QSize, Serial_t *pPort)
BOOL OpenCOMMEx (UInt8 chan, UInt8 dir, UInt32 baud, UInt8 parity, UInt8 data, UInt32 flow, UInt32 QSize, BOOL Loop, Serial_t *pPort)
BOOL OpenCOMMDev (const char *sDevice, UInt8 dir, UInt32 baud, UInt8 parity, UInt8 data, UInt32 flow, UInt32 QSize, Serial_t *pPort)
void GetSerialPortDescriptor (UInt8 chan, Serial_t *pPort)
void CloseCOMM (Serial_t *pPort)
BOOL IsCOMMOpen (Serial_t *pPort)
UInt32 GetBaud (Serial_t *pPort)
void ChangeBaud (Serial_t *pPort, UInt32 baud)
void WriteByteQuick (Serial_t *pPort, UInt8 data)
SInt16 ReadByte (Serial_t *pPort)
SInt16 ReadByteQuick (Serial_t *pPort)
UInt32 ReadBlockQuick (Serial_t *pPort, UInt8 *pData, UInt32 Size)
UInt32 ReadString (Serial_t *pPort, char *pData, UInt32 Size)
UInt32 ReadStringUntil (Serial_t *pPort, char *pData, UInt32 MaxSize, const char *pString)
void ReverseSerialRxQueue (Serial_t *pPort, UInt32 Size)
void WriteBlockQuick (Serial_t *pPort, const UInt8 *pData, UInt32 Size)
void WriteFromQueueQuick (Serial_t *pPort, Queue_t *pQ, UInt32 Size)
UInt32 WriteStringQuick (Serial_t *pPort, const char *pData)
UInt32 RxQAvailable (Serial_t *pPort)
UInt32 RxQHolding (Serial_t *pPort)
UInt32 TxQAvailable (Serial_t *pPort)
UInt32 TxQHolding (Serial_t *pPort)
void PurgeRxQ (Serial_t *pPort)
void PurgeTxQ (Serial_t *pPort)
void AssertBreak (Serial_t *pPort)
void ClearBreak (Serial_t *pPort)
BOOL CheckForResponse (Serial_t *pPort, const char *pString)
BOOL CheckForMultipleResponse (Serial_t *pPort, const char *pString, UInt32 NumResponse)
BOOL CheckForResponseEx (Serial_t *pPort, const char *pString, BOOL Clear)
UInt32 CheckForMultipleResponseEx (Serial_t *pPort, const char *pString, UInt32 NumResponse, BOOL Clear)
Serial_t GetNullSerialPort (void)
BOOL bCarrierDetectIsActive (Serial_t *pPort)
void SetDTRActive (Serial_t *pPort)
void SetDTRInactive (Serial_t *pPort)
Detailed Description
Top level asynchronous serial interfaces for the MPC5XX.
Serial.c/h provides a highly abstracted, interrupt driven, interface to universal asynchronous receiver transmitters (UART). The interface is designed to work with different underlying hardware including the SCI, and the TPU. Flow control is not yet supported.
Enumeration constants are provided for refering to the serial port channels The names have the following meanings:
COM1-COM4 refer to SCI1_a, SCI2_a, SCI1_b, and SCI2_b respectively.
COM5-COM10 are reserved
COM11-COM18 refer to serial ports created with pairs of TPU A channels. The transmit channel is an even number and the receive channel is one greater than that (i.e. COM11 uses TPUA channel 0 for transmit and TPUA channel 1 for receive).
COM19-COM26 refer to serial ports created with pairs of TPU B channels. The transmit channel is an even number and the receive channel is one greater than that (i.e. COM19 uses TPUB channel 0 for transmit and TPUB channel 1 for receive).
COM27-COM34 refer to serial ports created with pairs of TPU C channels. The transmit channel is an even number and the receive channel is one greater than that (i.e. COM19 uses TPUC channel 0 for transmit and TPUC channel 1 for receive).
Macro Definition Documentation
#define BOTH_DIR (RX_DIR|TX_DIR)
Both directions.
Referenced by InitIridium(), and InitNetwork().
#define EVEN_PARITY 2
Even parity checking.
Referenced by psPurgeTxQ().
#define FLOW_HARD 0x00000002
Hardware flow control RTS/CTS.
#define FLOW_NONE 0x00000000
No flow control.
Referenced by InitIridium().
#define FLOW_SOFT 0x00000001
Software flow control XON/XOFF.
#define NO_PARITY 0
No parity checking.
Referenced by InitIridium().
#define ODD_PARITY 1
Odd parity checking.
Referenced by psPurgeTxQ().
#define RX_DIR 1
Receive direction.
Referenced by OpenStream().
#define TX_DIR 2
Transmit direciton.
Referenced by OpenStream().
Enumeration Type Documentation
anonymous enum
Enumerator
NO_SERIAL_PORT
Invalid serial port.
SCI_PORT
serial port on the SCI of the MPC555
TPU_PORT
serial port on the TPU of the MPC555
PC_PORT
serial port on a PC under windows or linux
TCPCLIENT_PORT
virtual serial port opened as an TCP client
TCPSERVER_PORT
virtual serial port opened as an TCP server
IPMULTI_PORT
virtual serial port as IP multicast
INVALID_PORT
Also an invalid serial port.
enum SerialPortNames
Serial port names
Function Documentation
void AssertBreak (Serial_t * pPort)
Assert a break condition on the physical serial line.
Parameters
pPort is the serial port descriptor returned from OpenCOMM().
References Serial_t::Handle, PC_PORT, psAssertBreak(), and Serial_t::Type.
BOOL bCarrierDetectIsActive (Serial_t * pPort)
Return the status of the carrier detect line
Parameters
pPort is the serial port descriptor returned from OpenCOMM().
Returns
TRUE if the carrier detect line is active
References Serial_t::Handle, PC_PORT, psIsCarrierDetectActive(), and Serial_t::Type.
Referenced by bIridiumCarrierDetectIsActive().
void ChangeBaud (Serial_t * pPort, UInt32 baud)
Change the baud rate of an open serial port. The channel will be temporarily disabled while the baud rate is changed. This may result in lost data words.
Parameters
pPort is the serial port descriptor returned from OpenCOMM().
baud is the new signalling rate of the port in bits per second.
References Serial_t::Handle, PC_PORT, psChangeBaud(), and Serial_t::Type.
Referenced by IridiumStateDriver().
BOOL CheckForMultipleResponse (Serial_t * pPort, const char * pString, UInt32 NumResponse)
Check to see if a string appears in the serial port receive buffer multiple times. The string to look for is given as a NULL-terminated ASCII string. This function starts at the oldest data in the receive buffer and moves forward matching bytes until there are not bytes left in the buffer or the string has been successfully matched the required number of times. If the function succeeds the buffer is emptied up to and including the last matched string.
Parameters
Port is the serial port descriptor returned from OpenCOMM().
pString points to a NULL-terminated string to search for.
NumResponse is the number of responses to find.
Returns
TRUE if the string is found, else FALSE.
References CheckForMultipleResponseEx().
UInt32 CheckForMultipleResponseEx (Serial_t * pPort, const char * pString, UInt32 NumResponse, BOOL Clear)
Check to see if a string appears in the serial port receive buffer multiple times. The string to look for is given as a NULL-terminated ASCII string. This function starts at the oldest data in the receive buffer and moves forward matching bytes until there are not bytes left in the buffer or the string has been successfully matched the required number of times. If the function succeeds the buffer may be emptied up to and including the last matched string.
Parameters
Port is the serial port descriptor returned from OpenCOMM().
pString points to a NULL-terminated string to search for.
NumResponse is the number of responses to find.
Clear should be TRUE to remove matched bytes from the buffer, if all strings are found.
Returns
Number of strings found.
References Queue_t::In, Queue_t::Out, Queue_t::pBuf, Serial_t::pRxQ, and Queue_t::Size.
Referenced by CheckForMultipleResponse(), and CheckForResponseEx().
BOOL CheckForResponse (Serial_t * pPort, const char * pString)
Check to see if a string is in the serial port receive buffer. The string to look for is given as a NULL-terminated ASCII string. This function starts at the oldest data in the receive buffer and moves forward matching bytes until there are not bytes left in the buffer or the string has been successfully matched. If a match occurs the receive buffer will be emptied up to and including the string bytes.
Parameters
Port is the serial port descriptor returned from OpenCOMM().
pString points to a NULL-terminated string to search for.
Returns
TRUE if the string is found, else FALSE.
References CheckForResponseEx().
Referenced by IridiumStateDriver().
BOOL CheckForResponseEx (Serial_t * pPort, const char * pString, BOOL Clear)
Check to see if a string is in the serial port receive buffer. The string to look for is given as a NULL-terminated ASCII string. This function starts at the oldest data in the receive buffer and moves forward matching bytes until there are not bytes left in the buffer or the string has been successfully matched. If a match occurs the receive buffer may be emptied up to and including the string bytes, according to Clear
Parameters
Port is the serial port descriptor returned from OpenCOMM().
pString points to a NULL-terminated string to search for.
Clear should be TRUE to remove matched bytes from the buffer
Returns
TRUE if the string is found, else FALSE.
References CheckForMultipleResponseEx().
Referenced by CheckForResponse().
void ClearBreak (Serial_t * pPort)
Clear a break condition on the physical serial line.
Parameters
pPort is the serial port descriptor returned from OpenCOMM().
References Serial_t::Handle, PC_PORT, psClearBreak(), and Serial_t::Type.
void CloseCOMM (Serial_t * pPort)
Close the requested serial port
Parameters
pPort is the serial port descriptor returned from OpenCOMM().
References Serial_t::chan, DestroyQ(), Serial_t::Handle, INVALID_PORT, PC_PORT, Serial_t::pRxQ, psCloseCOMM(), Serial_t::RxChan, Serial_t::TxChan, and Serial_t::Type.
Referenced by DeinitIridium().
UInt32 GetBaud (Serial_t * pPort)
Get the baud rate of a serial port.
Parameters
pPort is the serial port descriptor returned from OpenCOMM().
Returns
the baud rate in bits per second
Serial_t GetNullSerialPort (void)
Return a serial port descriptor that indicates an un-opened port
Returns
The NULL port descriptor.
References Serial_t::pRxQ, and Serial_t::pTxQ.
BOOL IsCOMMOpen (Serial_t * pPort)
Determine if the serial channel is open. This is done by checking to see if the transmitter or receiver for that channel is enabled.
Parameters
pPort is the serial port descriptor returned from OpenCOMM().
Returns
TRUE if the channel is open, else FALSE.
References IPMULTI_PORT, PC_PORT, and Serial_t::Type.
BOOL OpenCOMM (UInt8 chan, UInt8 dir, UInt32 baud, UInt8 parity, UInt8 data, UInt32 flow, UInt32 QSize, Serial_t * pPort)
Open the serial port acording to the passed parameters.
Parameters
chan is the serial port identifier (COM1, COM2, etc).
dir is the direction to open the port (RX_DIR, TX_DIR, BOTH_DIR).
baud is the signalling rate to open the port in bits per second.
parity is the parity type to use (NO_PARITY, ODD_PARITY, EVEN_PARITY).
data is the number of data bits in a tansfer.
flow is the flow control method used (FLOW_NONE, FLOW_SOFT, FLOW_HARD).
QSize is the size of the serial buffer which will be allocated.
Returns
TRUE if the port is sucessfully opened, else FALSE.
References Serial_t::chan, CreateQ(), Serial_t::Handle, PC_PORT, Serial_t::pRxQ, psOpenCOMM(), Serial_t::pTxQ, Serial_t::RxChan, Serial_t::TxChan, and Serial_t::Type.
Referenced by InitIridium(), and OpenCOMMEx().
BOOL OpenCOMMDev (const char * sDevice, UInt8 dir, UInt32 baud, UInt8 parity, UInt8 data, UInt32 flow, UInt32 QSize, Serial_t * pPort)
Open the serial port defined by the device name string, according to the passed parameters.
Parameters
sDevice is the serial port device name, or path (i.e. "/dev/ttyS0").
dir is the direction to open the port (RX_DIR, TX_DIR, BOTH_DIR).
baud is the signalling rate to open the port in bits per second.
parity is the parity type to use (NO_PARITY, ODD_PARITY, EVEN_PARITY).
data is the number of data bits in a tansfer.
flow is the flow control method used (FLOW_NONE, FLOW_SOFT, FLOW_HARD).
QSize is the size of the serial buffer which will be allocated.
Returns
TRUE if the port is sucessfully opened, else FALSE.
References Serial_t::chan, CreateQ(), Serial_t::Handle, PC_PORT, Serial_t::pRxQ, psOpenCOMMDev(), Serial_t::pTxQ, Serial_t::RxChan, Serial_t::TxChan, and Serial_t::Type.
BOOL OpenCOMMEx (UInt8 chan, UInt8 dir, UInt32 baud, UInt8 parity, UInt8 data, UInt32 flow, UInt32 QSize, BOOL Loop, Serial_t * pPort)
Open a asynchronous serial port according to the passed parameters. The specific hardware module which provides the serial port must be initialized before calling this function.
Parameters
chan is the COM port number of the desired serial port. Use the defined values given in serial.h.
dir is the direction to open the serial port. Valid values are RX_DIR, TX_DIR, or BOTH_DIR. If opening a TPU serial port and not using BOTH_DIR then only one TPU channel will be configured. The corresponding bi-directional channel will not be altered.
baud is the baud rate of the port in bits per second.
parity is the parity of the port, Valid values are PARITY_NONE, PARITY_EVEN, or PARITY_ODD.
data is the number of data bits in each word, usually 8. The valid range of this parameter depends on the low level hardware supplying the port.
flow is reserved for flow control options, set to FLOW_NONE.
QSize is the size in bytes of the transmit and receive queue to be used for the interrupt driven serial port. If this parameter is 0 then the serial port will be configured to operate in a polled fashion. If this parameter is not zero then transmit and receive queues will be dynamically allocated, the serial port will be configured to operate in an interrupt fashion, and the interrupt system must be correctly initialized before calling this function.
Loop should be true to enable loop back mode
Returns
A Serial_t port descriptor. The Type will be nonzero if the port opened successfully. Failures could occur due to trying to open an invalid port number, a port that was already open, or inability to allocate dynamic memory.
References OpenCOMM().
void PurgeRxQ (Serial_t * pPort)
Purge the receive buffer of a serial port. This includes the receive intermediate buffer.
Parameters
pPort is the serial port descriptor returned from OpenCOMM().
References Serial_t::Handle, Queue_t::In, Queue_t::Out, PC_PORT, Serial_t::pRxQ, psPurgeRxQ(), and Serial_t::Type.
Referenced by IridiumStateDriver().
void PurgeTxQ (Serial_t * pPort)
Purge the transmit buffer of the physical serial port, or the transmit buffer estimate of an emulated port
Parameters
pPort is the serial port descriptor returned from OpenCOMM().
References Serial_t::Handle, PC_PORT, psPurgeTxQ(), and Serial_t::Type.
Referenced by IridiumStateDriver().
UInt32 ReadBlockQuick (Serial_t * pPort, UInt8 * pData, UInt32 Size)
Read a block of data from the serial port. This function does not block. If the amount of data waiting to be read is less that the amount requested then all the available data is read and the actual amount read is returned.
Parameters
pPort is the serial port descriptor returned from OpenCOMM().
pData points to space to receive the array of bytes
Size is the number of bytes to read.
Returns
The actual amount of data read.
References BlockDeQ(), and Serial_t::pRxQ.
Referenced by LookForGimbalPacket(), LookForStreamPacket(), ReadBlock(), and ReadStringUntil().
SInt16 ReadByte (Serial_t * pPort)
Read a byte of data from a serial port. If the receive buffer is empty this function will block until data are available.
Parameters
pPort is the serial port descriptor returned from OpenCOMM().
Returns
the data from the serial port. If an error occurs -1 is returned.
References IPMULTI_PORT, PC_PORT, ReadByteQuick(), and Serial_t::Type.
Referenced by ReadString().
SInt16 ReadByteQuick (Serial_t * pPort)
Read a byte of data from a serial port. This function will not block even If the receive buffer is empty
Parameters
pPort is the serial port descriptor returned from OpenCOMM().
Returns
the data from the serial port. If no data are available -1 is returned.
References DeQ(), and Serial_t::pRxQ.
Referenced by LookForGimbalPacket(), LookForStreamPacket(), and ReadByte().
UInt32 ReadString (Serial_t * pPort, char * pData, UInt32 MaxSize)
Read a string of data from the serial pPort. ReadString() calls the function ReadByte() until a null character is read, or until MaxSize bytes have been read.
Parameters
Port is the serial port descriptor returned from OpenCOMM().
pData points to space to receive the array of bytes
MaxSize is the maximum number of bytes to read.
References ReadByte().
UInt32 ReadStringUntil (Serial_t * pPort, char * pData, UInt32 MaxSize, const char * pString)
Read a string of data from the serial pPort, until another string is reached in the buffer. The buffer will be emptied of bytes read and the match string will remain in the buffer.
Parameters
Port is the serial port descriptor returned from OpenCOMM().
pData points to space to receive the array of bytes
MaxSize is the maximum number of bytes to read.
pString is the match string.
Returns
The number of bytes read.
References Serial_t::chan, Serial_t::Handle, Queue_t::In, IPMULTI_PORT, Queue_t::Out, Queue_t::pBuf, PC_PORT, Serial_t::pRxQ, psReadBlockQuick(), ReadBlockQuick(), Queue_t::Size, and Serial_t::Type.
void ReverseSerialRxQueue (Serial_t * pPort, UInt32 Size)
Reverse the serial receive queue. In this case this is the intermediate receive buffer.
Parameters
pPort is the serial port descriptor returned from OpenCOMM().
Size is the number of bytes to reverse
References Serial_t::pRxQ, and ReverseDeQ().
Referenced by LookForStreamPacket().
UInt32 RxQHolding (Serial_t * pPort)
Return the amount of data in the serial receive queue. This will cause the receive intermediate buffer to be updated.
Parameters
pPort is the serial port descriptor returned from OpenCOMM().
Returns
The amount of data in the receive queue.
References Serial_t::pRxQ, and QHolding().
void SetDTRActive (Serial_t * pPort)
Set the DTR line of the serial port active
Parameters
pPort is the serial port descriptor returned from OpenCOMM().
References Serial_t::Handle, PC_PORT, psSetDTRActive(), and Serial_t::Type.
Referenced by SetIridiumDTRActive().
void SetDTRInactive (Serial_t * pPort)
Set the DTR line of the serial port inactive
Parameters
pPort is the serial port descriptor returned from OpenCOMM().
References Serial_t::Handle, PC_PORT, psSetDTRInactive(), and Serial_t::Type.
Referenced by SetIridiumDTRInactive().
UInt32 TxQAvailable (Serial_t * pPort)
Return the amount of space available in the serial transmit queue.
Parameters
pPort is the serial port descriptor returned from OpenCOMM().
Returns
The amount of space available in the transmit queue.
References QHolding(), and TxQHolding().
UInt32 TxQHolding (Serial_t * pPort)
Return the amount of data in the serial transmit queue.
Parameters
pPort is the serial port descriptor returned from OpenCOMM().
Returns
The amount of data in the transmit queue.
References UpdateTransmitBufferEstimate().
Referenced by TxQAvailable().
void WriteBlockQuick (Serial_t * pPort, const UInt8 * pData, UInt32 Size)
Write a block of data to a serial port. This function will not block even if the transmit buffer is full, instead the byte(s) will be lost.
Parameters
pPort is the serial port descriptor returned from OpenCOMM().
pData points to a buffer of data.
Size is the number of bytes in the buffer to send.
References Serial_t::Handle, PC_PORT, psWriteBlockQuick(), Serial_t::Type, and UpdateTransmitBufferEstimate().
Referenced by SendGimbalPacket(), WriteBlock(), WriteByteQuick(), and WriteStringQuick().
void WriteByteQuick (Serial_t * pPort, UInt8 data)
Write a byte of data to a serial port. This function will not block even if the transmit buffer is full, instead the byte will be lost.
Parameters
chan identifies a previously opened serial port.
data is the data to send to the serial port.
References WriteBlockQuick().
Referenced by WriteFromQueueQuick().
void WriteFromQueueQuick (Serial_t * pPort, Queue_t * pQ, UInt32 Size)
Write a block of data in a Queue_t to a serial port.
Parameters
Port is the serial port descriptor returned from OpenCOMM().
pQ points to the source queue to send from.
Size is the number of bytes to transfer.
References DeQFast(), QHoldingFast(), and WriteByteQuick().
UInt32 WriteStringQuick (Serial_t * pPort, const char * pData)
Write a null-terminated string of data to the serial port. This function calls the function WriteBlockQuick() for all bytes in the string except the terminating null.
Parameters
pPort is the serial port descriptor returned from OpenCOMM().
pData points to the null-terminated string.
Returns
The number of bytes sent to the serial port.
References Serial_t::chan, CreateTCPClient(), Serial_t::Handle, TCPCLIENT_PORT, TCPSERVER_PORT, Serial_t::Type, and WriteBlockQuick().
Referenced by IridiumStateDriver().