Communications SDK: stream.h File Reference
stream.h File Reference
Stream packet protocol for the Piccolo system.
#include "Types.h"
#include "Queue.h"
#include "Serial.h"
Classes
struct StreamPkt_t
Macros
#define STREAM_PKT_OVERHEAD 16
#define STREAM_PKT_HEADER (STREAM_PKT_OVERHEAD-2)
#define MAX_STREAM_DATA_SIZE 255
#define MAX_STREAM_PKT_SIZE (MAX_STREAM_DATA_SIZE+STREAM_PKT_OVERHEAD)
#define STREAM_SYNC 0x5A
First packet synchronization character.
#define STREAM_SYNC1 0xA5
Send packet synchronication character.
#define BROADCAST_ADDRESS 0xFFFF
Address for broadcasting to all avionics.
#define OI_ADDRESS 0xFFFE
Address for all operator interfaces.
#define GS_ADDRESS 0x0000
Address for all ground stations.
#define MIN_AUTOPILOT_ADDRESS 0x0001
Minimum address for avionics.
#define MAX_AUTOPILOT_ADDRESS 0xFFF0
Maximum address for avionics.
Functions
BOOL LookForStreamPacket (StreamPkt_t *pPkt, Serial_t *pPort)
BOOL LookForStreamPacketInQueue (StreamPkt_t *pPkt, Queue_t *pQ)
SInt32 LookForStreamPacketInByte (StreamPkt_t *pPkt, UInt8 Byte)
void MakePacketHeader (StreamPkt_t *pPkt, UInt16 DestinationID, UInt16 SourceID, UInt8 Stream, UInt8 Flags, UInt16 Sequence, UInt16 Acknowledge, UInt16 DataSize)
void MakePacket (StreamPkt_t *pPkt, UInt16 DestinationID, UInt16 SourceID, UInt8 Stream, UInt8 Flags, UInt16 Sequence, UInt16 Acknowledge, const UInt8 *pData, UInt16 DataSize)
void CRCPacket (StreamPkt_t *pPkt)
Detailed Description
Stream packet protocol for the Piccolo system.
The data sent to or from any one avionics are made up of multiple bi-directional streams which are multiplexed onto the communications channel. Each stream represents an endpoint in the avionics, which is either defined by software or by a physical port on the avionics. The stream module defines a basic stream packet format, and provides low level stream packet formatting and decoding routines.
Note that the stream packet protocol definition changed from software versions 1.1.x to 1.2.x. They changes are not backwards compatible
Macro Definition Documentation
#define BROADCAST_ADDRESS 0xFFFF
Address for broadcasting to all avionics.
#define GS_ADDRESS 0x0000
Address for all ground stations.
Referenced by CommBase_SendGroundStationPacket().
#define MAX_AUTOPILOT_ADDRESS 0xFFF0
Maximum address for avionics.
#define MAX_STREAM_DATA_SIZE 255
The maximum amount of data that a stream packet can contain is 255 bytes
Referenced by MakePacket().
#define MAX_STREAM_PKT_SIZE (MAX_STREAM_DATA_SIZE+STREAM_PKT_OVERHEAD)
The entire stream packet can be no more than 271 bytes
#define MIN_AUTOPILOT_ADDRESS 0x0001
Minimum address for avionics.
#define OI_ADDRESS 0xFFFE
Address for all operator interfaces.
Referenced by UdpAutoDetector::checkForNewServers().
#define STREAM_PKT_HEADER (STREAM_PKT_OVERHEAD-2)
Stream packets have 14 byte headers
Referenced by CRCPacket(), and LookForStreamPacketInByte().
#define STREAM_PKT_OVERHEAD 16
Stream packets have 16 bytes of overhead
#define STREAM_SYNC 0x5A
First packet synchronization character.
Referenced by LookForStreamPacketInByte(), and MakePacketHeader().
#define STREAM_SYNC1 0xA5
Send packet synchronication character.
Referenced by LookForStreamPacketInByte(), and MakePacketHeader().
Function Documentation
void CRCPacket (StreamPkt_t * pPkt)
Form the header check sum and packet CRC for the passed stream packet
Parameters
pPkt points to a stream packet structure which is complete except for the header checksum and crc.
References CRC16(), StreamPkt_t::Data, StreamPkt_t::HdrChk, StreamPkt_t::Size, and STREAM_PKT_HEADER.
Referenced by MakePacket().
BOOL LookForStreamPacket (StreamPkt_t * pPkt, Serial_t * pPort)
Search for a stream packet coming over a physical serial channel. If a stream packet is found this function returns TRUE. The packet storage provided by the caller MUST persist between calls, since this function may partially complete a packet and then return FALSE while waiting for more data to arrive.
Parameters
pPkt points to a stream packet structure which must persist between calls.
pPort identifies a previously opened serial port.
Returns
TRUE if a packet is found, else FALSE.
References StreamPkt_t::Data, StreamPkt_t::HdrChk, ReadBlockQuick(), ReadByteQuick(), ReverseSerialRxQueue(), and StreamPkt_t::Size.
SInt32 LookForStreamPacketInByte (StreamPkt_t * pPkt, UInt8 Byte)
Search for a stream packet contained in a series of single bytes passed to this function on multiple calls. The packet storage provided by the caller MUST persist between calls, since this function will partially complete a packet and then return -1 while waiting for more data to arrive.
Parameters
pPkt points to a stream packet structure which must persist between calls.
Byte contains the next piece of receive data.
Returns
0 if a packet is found, less than 0 if no packet is found. If the return is greater than zero then an error was detected in the byte sequence, and the return value represents the number of bytes to back up in order to minimize the amount of lost data.
References StreamPkt_t::AckHi, StreamPkt_t::AckLo, CRC16(), StreamPkt_t::Data, StreamPkt_t::DestHi, StreamPkt_t::DestLo, StreamPkt_t::Flags, StreamPkt_t::HdrChk, StreamPkt_t::SeqHi, StreamPkt_t::SeqLo, StreamPkt_t::Size, StreamPkt_t::SourceHi, StreamPkt_t::SourceLo, StreamPkt_t::Stream, STREAM_PKT_HEADER, STREAM_SYNC, STREAM_SYNC1, StreamPkt_t::Sync, and StreamPkt_t::Sync1.
Referenced by UdpAutoDetector::checkForNewServers().
BOOL LookForStreamPacketInQueue (StreamPkt_t * pPkt, Queue_t * pQ)
Search for a stream packet contained in a queue. If a stream packet is found this function returns TRUE. The packet storage provided by the caller MUST persist between calls, since this function may partially complete a packet and then return FALSE while waiting for more data to arrive.
Parameters
pPkt points to a stream packet structure which must persist between calls.
pQ points to a queue which contains received data.
Returns
TRUE if a packet is found, else FALSE.
References BlockDeQFast(), StreamPkt_t::Data, DeQFast(), StreamPkt_t::HdrChk, ReverseDeQFast(), and StreamPkt_t::Size.
void MakePacket (StreamPkt_t * pPkt, UInt16 DestinationID, UInt16 SourceID, UInt8 Stream, UInt8 Flags, UInt16 Sequence, UInt16 Acknowledge, const UInt8 * pData, UInt16 DataSize)
Form a packet from the passed parameters. The resulting packet will be ready to transmit, i.e. the header check and CRC will be complete
Parameters
pPkt points to a stream packet structure which will be formatted.
DestinationID is the destination network identifier.
SourceID is the source network identifier.
Stream is the stream identifier.
Flag is the flags field
Sequence is the seq field
Acknowledge is the ack field
pData points to a buffer of data to be included in the packet.
DataSize is the amount of data to be included in the packet.
References CRCPacket(), StreamPkt_t::Data, MakePacketHeader(), and MAX_STREAM_DATA_SIZE.
void MakePacketHeader (StreamPkt_t * pPkt, UInt16 DestinationID, UInt16 SourceID, UInt8 Stream, UInt8 Flags, UInt16 Sequence, UInt16 Acknowledge, UInt16 DataSize)
Form the header of a packet from the passed parameters. The resulting packet will still need the data copied into it, the header checksum, and the main CRC completed.
Parameters
pPkt points to a stream packet structure which will be formatted.
DestinationID is the destination network identifier.
SourceID is the source network identifier.
Stream is the stream identifier.
Flag is the flags field
Sequence is the seq field
Acknowledge is the ack field
DataSize is the amount of data to be included in the packet.
References StreamPkt_t::AckHi, StreamPkt_t::AckLo, StreamPkt_t::DestHi, StreamPkt_t::DestLo, StreamPkt_t::Flags, StreamPkt_t::SeqHi, StreamPkt_t::SeqLo, StreamPkt_t::Size, StreamPkt_t::SourceHi, StreamPkt_t::SourceLo, StreamPkt_t::Stream, STREAM_SYNC, STREAM_SYNC1, StreamPkt_t::Sync, and StreamPkt_t::Sync1.
Referenced by MakePacket().