Communications SDK: StreamPackets.h File Reference
StreamPackets.h File Reference
Stream packet utilities.
#include "Queue.h"
Classes
struct SimplePkt_t
struct CANPacket_t
Macros
#define MAX_SIMPLE_DATA 255
The maximum amount of data that a simple packet can contain is 255 bytes.
#define SIMPLE_PKT_HEADER 4UL
Simple stream packets have 4 byte headers.
#define SIMPLE_PKT_OVERHEAD 6UL
Simple stream packets have 6 bytes of overhead.
#define SIMPLE_SYNC 0xA0
First simple stream packet synchronization character.
#define SIMPLE_SYNC1 0x05
Second simple stream packet synchronization character.
#define MAX_CAN_DATA 8
The maximum amount of data that a CAN stream packet can contain is 8 bytes.
#define CAN_PKT_HEADER 10UL
CAN stream packets have 10 byte headers.
#define CAN_PKT_OVERHEAD 12UL
CAN stream packets have 12 bytes of overhead.
#define CAN_SYNC 0x05
First CAN stream packet synchronization character.
#define CAN_SYNC1 0xA0
Second CAN stream packet synchronization character.
Typedefs
typedef SimplePkt_t GroundStationPkt_t
typedef SimplePkt_t AutopilotPkt_t
typedef SimplePkt_t PilotPkt_t
Enumerations
enum PilotPacketTypes { RESERVED, PILOT_COMMAND_PULSE, GROUND_STATION_SWITCHES }
Functions
BOOL LookForCANPacket (Queue_t *pRxQ, CANPacket_t *pPkt)
BOOL LookForAutopilotPacket (Queue_t *pRxQ, AutopilotPkt_t *pPkt)
BOOL LookForPilotPacket (Queue_t *pRxQ, PilotPkt_t *pPkt)
BOOL LookForGroundStationPacket (Queue_t *pRxQ, GroundStationPkt_t *pPkt)
BOOL LookForAutopilotPacketInBuf (UInt8 *pData, AutopilotPkt_t *pPkt, UInt32 Size, UInt32 *pUsed)
BOOL LookForPilotPacketInBuf (UInt8 *pData, PilotPkt_t *pPkt, UInt32 Size, UInt32 *pUsed)
BOOL LookForGroundStationPacketInBuf (UInt8 *pData, GroundStationPkt_t *pPkt, UInt32 Size, UInt32 *pUsed)
BOOL LookForSimplePacket (Queue_t *pRxQ, SimplePkt_t *pPkt)
BOOL LookForSimplePacketInBuf (UInt8 *pData, SimplePkt_t *pPkt, UInt32 Size, UInt32 *pUsed)
SInt32 LookForCANPacketInByte (UInt8 Byte, CANPacket_t *pPkt)
SInt32 LookForAutopilotPacketInByte (UInt8 Byte, AutopilotPkt_t *pPkt)
SInt32 LookForPilotPacketInByte (UInt8 Byte, PilotPkt_t *pPkt)
SInt32 LookForGroundStationPacketInByte (UInt8 Byte, GroundStationPkt_t *pPkt)
SInt32 LookForSimplePacketInByte (UInt8 Byte, SimplePkt_t *pPkt)
void MakeCANPacket (CANPacket_t *pPkt, UInt32 ID, UInt16 Time, UInt8 Bus, UInt8 DataSize)
void MakeAutopilotPacket (AutopilotPkt_t *pPkt, UInt8 PktType, UInt8 DataSize)
void MakePilotPacket (PilotPkt_t *pPkt, UInt8 PktType, UInt8 DataSize)
void MakeGroundStationPacket (GroundStationPkt_t *pPkt, UInt8 PktType, UInt8 DataSize)
void MakeSimplePacket (SimplePkt_t *pPkt, UInt8 PktType, UInt8 DataSize)
Detailed Description
Stream packet utilities.
This module provides the functions required to parse ground station, pilot, autopilot, and CAN stream packets from input buffers.
Macro Definition Documentation
#define CAN_PKT_HEADER 10UL
CAN stream packets have 10 byte headers.
Referenced by MakeCANPacket().
#define CAN_PKT_OVERHEAD 12UL
CAN stream packets have 12 bytes of overhead.
#define CAN_SYNC 0x05
First CAN stream packet synchronization character.
Referenced by LookForCANPacket(), and MakeCANPacket().
#define CAN_SYNC1 0xA0
Second CAN stream packet synchronization character.
Referenced by LookForCANPacket(), and MakeCANPacket().
#define MAX_CAN_DATA 8
The maximum amount of data that a CAN stream packet can contain is 8 bytes.
Referenced by LookForCANPacket(), and LookForCANPacketInByte().
#define MAX_SIMPLE_DATA 255
The maximum amount of data that a simple packet can contain is 255 bytes.
Referenced by DecodeDeviceDetails(), DecodeGSDeviceDetails(), DecodeGSNamePacket(), DecodeGSUserWarningPacket(), DecodeUserWarningPacket(), FormControllerDataPacket(), and FormGSGPSHealthPacket().
#define SIMPLE_PKT_HEADER 4UL
Simple stream packets have 4 byte headers.
Referenced by LookForSimplePacket(), and MakeSimplePacket().
#define SIMPLE_PKT_OVERHEAD 6UL
Simple stream packets have 6 bytes of overhead.
#define SIMPLE_SYNC 0xA0
First simple stream packet synchronization character.
Referenced by LookForSimplePacketInByte(), and MakeSimplePacket().
#define SIMPLE_SYNC1 0x05
Second simple stream packet synchronization character.
Referenced by LookForSimplePacketInByte(), and MakeSimplePacket().
Typedef Documentation
typedef SimplePkt_t AutopilotPkt_t
Generic autopilot stream packet structure
typedef SimplePkt_t GroundStationPkt_t
Generic ground station stream packet structure
typedef SimplePkt_t PilotPkt_t
Generic pilot packet stream packet structure
Enumeration Type Documentation
enum PilotPacketTypes
Pilot in the loop stream message types
Enumerator
PILOT_COMMAND_PULSE
Pilot command packet containing pulse widths.
GROUND_STATION_SWITCHES
Ground station switches.
Function Documentation
BOOL LookForAutopilotPacket (Queue_t * pRxQ, AutopilotPkt_t * pPkt)
Search for a autopilot packet contained in a queue. If a packet is found this function returns TRUE. The packet storage provided by the caller MUST persist between calls, since this function may partially complete a packet and then return FALSE while waiting for more data to arrive.
Parameters
pRxQ points to a queue which contains received data.
pPkt points to a autopilot packet structure which must persist between calls.
Returns
TRUE if a packet is found, else FALSE.
References LookForSimplePacket().
BOOL LookForAutopilotPacketInBuf (UInt8 * pData, AutopilotPkt_t * pPkt, UInt32 Size, UInt32 * pUsed)
Search for a Autopilot packet contained in a buffer of data. If a packet is found this function returns TRUE. The packet storage provided by the caller MUST persist between calls, since this function may partially complete a packet and then return FALSE while waiting for more data to arrive.
Parameters
pData points to a buffer of data.
pPkt points to a packet structure which must persist between calls.
Size is the number of bytes in the pData buffer.
pUsed points to space to receive the number of bytes read from the buffer. If a packet is found it is possible that there may be more packets in the buffer following the first one. Use the pUsed value to detect this case.
Returns
TRUE if a packet is found, else FALSE.
References LookForSimplePacketInBuf().
SInt32 LookForAutopilotPacketInByte (UInt8 Byte, AutopilotPkt_t * pPkt)
Search for a autopilot packet contained in a series of single bytes passed to this function on multiple calls. The packet storage provided by the caller MUST persist between calls, since this function will partially complete a packet and then return -1 while waiting for more data to arrive.
Parameters
pPkt points to a autopilot packet structure which must persist between calls.
Byte contains the next piece of receive data.
Returns
0 if a packet is found, less than 0 if no packet is found. If the return is greater than zero then an error was detected in the byte sequence, and the return value represents the number of bytes to back up in order to minimize the amount of lost data.
References LookForSimplePacketInByte().
BOOL LookForCANPacket (Queue_t * pRxQ, CANPacket_t * pPkt)
Search for a CAN packet contained in a queue. If a packet is found this function returns TRUE. The packet storage provided by the caller MUST persist between calls, since this function may partially complete a packet and then return FALSE while waiting for more data to arrive.
Parameters
pRxQ points to a queue which contains received data.
pPkt points to a CAN packet structure which must persist between calls.
Returns
TRUE if a packet is found, else FALSE.
References BlockDeQFast(), CAN_SYNC, CAN_SYNC1, CRC16(), CANPacket_t::Data, DeQFast(), MAX_CAN_DATA, ReverseDeQFast(), CANPacket_t::Size, CANPacket_t::Sync, and CANPacket_t::Sync1.
SInt32 LookForCANPacketInByte (UInt8 Byte, CANPacket_t * pPkt)
Search for a CAN packet contained in a series of single bytes passed to this function on multiple calls. The packet storage provided by the caller MUST persist between calls, since this function will partially complete a packet and then return -1 while waiting for more data to arrive.
Parameters
pPkt points to a CAN packet structure which must persist between calls.
Byte contains the next piece of receive data.
Returns
0 if a packet is found, less than 0 if no packet is found. If the return is greater than zero then an error was detected in the byte sequence, and the return value represents the number of bytes to back up in order to minimize the amount of lost data.
References CRC16(), CANPacket_t::Data, MAX_CAN_DATA, and CANPacket_t::Size.
BOOL LookForGroundStationPacket (Queue_t * pRxQ, GroundStationPkt_t * pPkt)
Search for a ground station packet contained in a queue. If a packet is found this function returns TRUE. The packet storage provided by the caller MUST persist between calls, since this function may partially complete a packet and then return FALSE while waiting for more data to arrive.
Parameters
pRxQ points to a queue which contains received data.
pPkt points to a groundstation packet structure which must persist between calls.
Returns
TRUE if a packet is found, else FALSE.
References LookForSimplePacket().
BOOL LookForGroundStationPacketInBuf (UInt8 * pData, GroundStationPkt_t * pPkt, UInt32 Size, UInt32 * pUsed)
Search for a Groundstation packet contained in a buffer of data. If a packet is found this function returns TRUE. The packet storage provided by the caller MUST persist between calls, since this function may partially complete a packet and then return FALSE while waiting for more data to arrive.
Parameters
pData points to a buffer of data.
pPkt points to a packet structure which must persist between calls.
Size is the number of bytes in the pData buffer.
pUsed points to space to receive the number of bytes read from the buffer. If a packet is found it is possible that there may be more packets in the buffer following the first one. Use the pUsed value to detect this case.
Returns
TRUE if a packet is found, else FALSE.
References LookForSimplePacketInBuf().
SInt32 LookForGroundStationPacketInByte (UInt8 Byte, GroundStationPkt_t * pPkt)
Search for a ground station packet contained in a series of single bytes passed to this function on multiple calls. The packet storage provided by the caller MUST persist between calls, since this function will partially complete a packet and then return -1 while waiting for more data to arrive.
Parameters
pPkt points to a ground station packet structure which must persist between calls.
Byte contains the next piece of receive data.
Returns
0 if a packet is found, less than 0 if no packet is found. If the return is greater than zero then an error was detected in the byte sequence, and the return value represents the number of bytes to back up in order to minimize the amount of lost data.
References LookForSimplePacketInByte().
Referenced by UdpAutoDetector::checkForNewServers().
BOOL LookForPilotPacket (Queue_t * pRxQ, PilotPkt_t * pPkt)
Search for a pilot packet contained in a queue. If a packet is found this function returns TRUE. The packet storage provided by the caller MUST persist between calls, since this function may partially complete a packet and then return FALSE while waiting for more data to arrive.
Parameters
pRxQ points to a queue which contains received data.
pPkt points to a pilot packet structure which must persist between calls.
Returns
TRUE if a packet is found, else FALSE.
References LookForSimplePacket().
BOOL LookForPilotPacketInBuf (UInt8 * pData, PilotPkt_t * pPkt, UInt32 Size, UInt32 * pUsed)
Search for a Pilot packet contained in a buffer of data. If a packet is found this function returns TRUE. The packet storage provided by the caller MUST persist between calls, since this function may partially complete a packet and then return FALSE while waiting for more data to arrive.
Parameters
pData points to a buffer of data.
pPkt points to a packet structure which must persist between calls.
Size is the number of bytes in the pData buffer.
pUsed points to space to receive the number of bytes read from the buffer. If a packet is found it is possible that there may be more packets in the buffer following the first one. Use the pUsed value to detect this case.
Returns
TRUE if a packet is found, else FALSE.
References LookForSimplePacketInBuf().
SInt32 LookForPilotPacketInByte (UInt8 Byte, PilotPkt_t * pPkt)
Search for a pilot packet contained in a series of single bytes passed to this function on multiple calls. The packet storage provided by the caller MUST persist between calls, since this function will partially complete a packet and then return -1 while waiting for more data to arrive.
Parameters
pPkt points to a pilot packet structure which must persist between calls.
Byte contains the next piece of receive data.
Returns
0 if a packet is found, less than 0 if no packet is found. If the return is greater than zero then an error was detected in the byte sequence, and the return value represents the number of bytes to back up in order to minimize the amount of lost data.
References LookForSimplePacketInByte().
BOOL LookForSimplePacket (Queue_t * pRxQ, SimplePkt_t * pPkt)
Search for a simple packet contained in a queue. If a packet is found this function returns TRUE. The packet storage provided by the caller MUST persist between calls, since this function may partially complete a packet and then return FALSE while waiting for more data to arrive.
Parameters
pRxQ points to a queue which contains received data.
pPkt points to a simple packet structure which must persist between calls.
Returns
TRUE if a packet is found, else FALSE.
References BlockDeQFast(), CRC16(), SimplePkt_t::Data, DeQFast(), LookForSimplePacketInByte(), ReverseDeQFast(), SIMPLE_PKT_HEADER, and SimplePkt_t::Size.
Referenced by LookForAutopilotPacket(), LookForGroundStationPacket(), and LookForPilotPacket().
BOOL LookForSimplePacketInBuf (UInt8 * pData, SimplePkt_t * pPkt, UInt32 Size, UInt32 * pUsed)
Search for a simple packet contained in a buffer of data. If a packet is found this function returns TRUE. The packet storage provided by the caller MUST persist between calls, since this function may partially complete a packet and then return FALSE while waiting for more data to arrive.
Parameters
pData points to a buffer of data.
pPkt points to a packet structure which must persist between calls.
Size is the number of bytes in the pData buffer.
pUsed points to space to receive the number of bytes read from the buffer. If a packet is found it is possible that there may be more packets in the buffer following the first one. Use the pUsed value to detect this case.
Returns
TRUE if a packet is found, else FALSE.
References SimplePkt_t::Data, LookForSimplePacketInByte(), and SimplePkt_t::Size.
Referenced by LookForAutopilotPacketInBuf(), LookForGroundStationPacketInBuf(), and LookForPilotPacketInBuf().
SInt32 LookForSimplePacketInByte (UInt8 Byte, SimplePkt_t * pPkt)
Search for a simple packet contained in a series of single bytes passed to this function on multiple calls. The packet storage provided by the caller MUST persist between calls, since this function will partially complete a packet and then return -1 while waiting for more data to arrive.
Parameters
pPkt points to a simple packet structure which must persist between calls.
Byte contains the next piece of receive data.
Returns
0 if a packet is found, less than 0 if no packet is found. If the return is greater than zero then an error was detected in the byte sequence, and the return value represents the number of bytes to back up in order to minimize the amount of lost data.
References SimplePkt_t::Data, SIMPLE_SYNC, SIMPLE_SYNC1, SimplePkt_t::Size, and SimplePkt_t::Sync.
Referenced by LookForAutopilotPacketInByte(), LookForGroundStationPacketInByte(), LookForPilotPacketInByte(), LookForSimplePacket(), and LookForSimplePacketInBuf().
void MakeAutopilotPacket (AutopilotPkt_t * pPkt, UInt8 PktType, UInt8 DataSize)
Complete the formatting of a generic autopilot packet. The packet header and crc will be created using the data already contained in the packet.
Parameters
pPkt points to a autopilot packet structure which already contains the data to be sent.
PktType is the packet identifier.
DataSize is the amount of data in the packet.
References MakeSimplePacket().
Referenced by CommBase_RequestActuatorTablePacket(), CommBase_RequestBandwidthModePacket(), CommBase_RequestExternalIOSetupPacket(), CommBase_SendActuatorTypePacket(), CommBase_SendAirDataZeroPacket(), CommBase_SendBrakesCommandPacket(), CommBase_SendDescriptionPacket(), CommBase_SendDropCommandPacket(), CommBase_SendEngineKillPacket(), CommBase_SendLandNowPacket(), CommBase_SendLaunchNowPacket(), CommBase_SendLightsCommandPacket(), CommBase_SendManualAssistModePacket(), CommBase_SendParachuteCommandPacket(), CommBase_SendPrelaunchPacket(), CommBase_SendThrottleTrimPacket(), CommBase_SendTrackCommandPacket(), CommBase_SendUserSpacePacket(), CommBase_SendZeroLengthAutopilotPacket(), FormActuatorTablePacket(), FormActuatorTestPacket(), FormAltimeterSettingPacket(), FormAutopilotLoopControlPacketEx(), FormBandwidthModePacket(), FormBoundaryPacket(), FormConfigurationLockPacket(), FormConfigurationUnlockPacket(), FormControllerDataDefaultPacket(), FormControllerDataPacket(), FormControllerDataRequestPacket(), FormDoubletCommandPacket(), FormECUCommandPacket(), FormExternalIOSetupPacketEx(), FormExternalSerialSetupPacket(), FormFeatureCodePacket(), FormFrequencySweepCommandPacket(), FormGPSPosVelPacket(), FormLegacyWaypointListPacket(), FormLegacyWaypointPacket(), FormMagCalPacket(), FormMissionLimitsPacket(), FormMissionSettingsPacket(), FormOrientationPacket(), FormPayloadMassPacket(), FormRadioSettingsPacket(), FormSensorErrorPacket(), FormSetFuelIfLockedPacket(), FormSetFuelLevelPacket(), FormSimpleLandingPacket(), FormTerrainElevationDataPacket(), FormThrottleMinPacket(), FormTransponderControlPacket(), FormTransponderInstallationPacket(), FormTransponderPreflightPacket(), FormUserActionPacket(), FormWaypointListPacket(), FormWaypointListRangePacket(), and FormWaypointsPacket().
void MakeCANPacket (CANPacket_t * pPkt, UInt32 ID, UInt16 Time, UInt8 Bus, UInt8 DataSize)
Complete the formatting of a generic CAN packet. The packet header and crc will be created using the data already contained in the packet.
Parameters
pPkt points to a CAN packet structure which already contains the data to be sent.
ID is the CAN identifier, 11 (2.0A) or 29 (2.0B) bit.
Time is the 16-bit time field of the CAN packet.
Bus is nonzero to specific 2.0B
DataSize is the amount of data in the packet, max 8.
References CANPacket_t::Bus, CAN_PKT_HEADER, CAN_SYNC, CAN_SYNC1, CRC16(), CANPacket_t::Data, CANPacket_t::ID_0, CANPacket_t::ID_1, CANPacket_t::ID_2, CANPacket_t::ID_3, CANPacket_t::Size, CANPacket_t::Sync, CANPacket_t::Sync1, CANPacket_t::Time_0, and CANPacket_t::Time_1.
void MakeGroundStationPacket (GroundStationPkt_t * pPkt, UInt8 PktType, UInt8 DataSize)
Complete the formatting of a generic ground station packet. The packet header and crc will be created using the data already contained in the packet.
Parameters
pPkt points to a ground station packet structure which already contains the data to be sent.
PktType is the packet identifier.
DataSize is the amount of data in the packet.
References MakeSimplePacket().
Referenced by CommBase_RequestGSCoherentSpectrumSweepPacket(), CommBase_SendGSAddAddressPacket(), CommBase_SendGSAddPilotAddressPacket(), CommBase_SendGSDeleteAddressPacket(), CommBase_SendGSDynamicEnumerationPacket(), CommBase_SendZeroLengthGroundStationPacket(), FormDGPSBasePacket(), FormDualAntStatusPacket(), FormGroundStationConfigurationPacket(), FormGroupAddressPacket(), FormGSDeviceDetailsPacket(), FormGSGPSHealthPacket(), FormGSNamePacket(), FormGSRadioSettingsPacket(), FormGSResetReportPacket(), FormGSSpectrumPacket(), FormGSSpectrumSweepPacket(), FormGSTelemetryPacket(), FormGSUserWarningPacket(), and FormGSVersionPacket().
void MakePilotPacket (PilotPkt_t * pPkt, UInt8 PktType, UInt8 DataSize)
Complete the formatting of a generic pilot packet. The packet header and crc will be created using the data already contained in the packet.
Parameters
pPkt points to a pilot packet structure which already contains the data to be sent.
PktType is the packet identifier.
DataSize is the amount of data in the packet.
References MakeSimplePacket().
void MakeSimplePacket (SimplePkt_t * pPkt, UInt8 PktType, UInt8 DataSize)
Complete the formatting of a generic simple packet. The packet header and crc will be created using the data already contained in the packet.
Parameters
pPkt points to a simple packet structure which already contains the data to be sent.
PktType is the packet identifier.
DataSize is the amount of data in the packet.
References CRC16(), SimplePkt_t::Data, SimplePkt_t::PktType, SIMPLE_PKT_HEADER, SIMPLE_SYNC, SIMPLE_SYNC1, SimplePkt_t::Size, SimplePkt_t::Sync, and SimplePkt_t::Sync1.
Referenced by MakeAutopilotPacket(), MakeGroundStationPacket(), and MakePilotPacket().