Communications SDK: Timer.h File Reference
Timer.h File Reference
Countdown timers for MPC555 systems.
#include "Types.h"
#include "TimeBase.h"
#include <time.h>
Typedefs
typedef UInt64 Timer_t
Timer values are stored in 64 bits.
Functions
Timer_t StartElapsedTimer (void)
double ReadElapsedTime (Timer_t Start)
double ReadElapsedTimeEx (Timer_t *pStart)
UInt32 ReadElapsedTime32 (Timer_t Start)
UInt64 ReadElapsedTime64 (Timer_t Start)
Timer_t WrTimer (double CountDown)
Timer_t WrTimer32 (UInt32 CountDown)
Timer_t WrTimer64 (UInt64 CountDown)
UInt32 RdTimer (Timer_t Timer)
UInt64 RdTimer64 (Timer_t Timer)
double RdTimerRemaining (Timer_t Timer)
BOOL IsTimerElapsed (Timer_t Timer)
struct tm * gmtime (const time_t *timp)
Detailed Description
Countdown timers for MPC555 systems.
The count down timers are based upon the 64-bit timebase counter of the MPC555. The counters are used by first calling WrTimer(), and then later calling RdTimer() to determine if the timer has elapsed.
Typedef Documentation
typedef UInt64 Timer_t
Timer values are stored in 64 bits.
Function Documentation
BOOL IsTimerElapsed (Timer_t Timer)
Read the caller stored countdown timer and return TRUE if it has reached zero.
Parameters
Timer is the value of the caller stored timer, which should be been returned from an earlier call to WrTimer(), WrTimer32(), or WrTimer64().
Returns
TRUE if the timer has elapsed, else FALSE.
UInt32 RdTimer (Timer_t Timer)
Read the caller stored countdown timer.
Parameters
Timer is the value of the caller stored timer, which should be been returned from an earlier call to WrTimer(), WrTimer32(), or WrTimer64().
Returns
The number of timebase ticks before the timer elapses. If the timer is already elapsed, then 0 is returned. If the time required before elapse is greater than 32 bits than 0xFFFFFFFF is returned.
UInt64 RdTimer64 (Timer_t Timer)
Read the caller stored countdown timer.
Parameters
Timer is the value of the caller stored timer, which should be been returned from an earlier call to WrTimer(), WrTimer32(), or WrTimer64().
Returns
The number of timebase ticks before the timer elapses. If the timer is already elapsed, then 0 is returned.
Referenced by RdTimerRemaining().
double RdTimerRemaining (Timer_t Timer)
Read the number of seconds remaining for a countdown timer.
Parameters
Timer is the value of the caller stored timer, which should be been returned from an earlier call to WrTimer(), WrTimer32(), or WrTimer64().
Returns
The remaining time in seconds, which may be zero.
References RdTimer64().
double ReadElapsedTime (Timer_t Start)
Read the amount of time that has elapsed since StartElapsedTimer() was called.
Parameters
Start is the value returned from the prior call to StartElapsedTimer().
Returns
The elapsed time in seconds.
References ReadElapsedTime64().
UInt32 ReadElapsedTime32 (Timer_t Start)
Read the amount of time in timebase ticks that has elapsed since StartElapsedTimer() was called. The return value is limited to 32-bits
Parameters
Start is the value returned from the prior call to StartElapsedTimer().
Returns
The elapsed time in timebase ticks.
References ReadElapsedTime64().
UInt64 ReadElapsedTime64 (Timer_t Start)
Read the amount of time in timebase ticks that has elapsed since StartElapsedTimer() was called.
Parameters
Start is the value returned from the prior call to StartElapsedTimer().
Returns
The elapsed time in timebase ticks.
Referenced by ReadElapsedTime(), and ReadElapsedTime32().
double ReadElapsedTimeEx (Timer_t * pStart)
Read the amount of time that has elapsed since StartElapsedTimer() was called, also reset the elapsed timer
Parameters
pStart points to an elapsed timer start value. This value will be used for the elapsed time calculation, and will also be updated with the current time value for the next elapsed time calculation.
Returns
The elapsed time in seconds.
Timer_t StartElapsedTimer (void)
Reset the caller stored elapsed timer
Returns
The elapsed timer start point to be stored by the caller.
Timer_t WrTimer (double CountDown)
Reset the caller stored countdown timer. The timeout value must not be more than 2^31 bits of the timebase. Hence at 1MHz the maximum timeout is 2147.5 seconds, or about 36 minutes. If longer timeout values are needed use WrTimer64() or WrTimerLong().
Parameters
CountDown is the number of seconds to count down.
Returns
The countdown elapse time to be stored by the caller.
Timer_t WrTimer32 (UInt32 CountDown)
Reset the caller stored countdown timer
Parameters
CountDown is the number of time base ticks to count down.
Returns
The countdown elapse time to be stored by the caller.
Timer_t WrTimer64 (UInt64 CountDown)
Reset the caller stored countdown timer
Parameters
CountDown is the number of time base ticks to count down.
Returns
The countdown elapse time to be stored by the caller.